<h1> bioRxix and medRxiv: Retrieve data </h1>

We will be retrieving data from those two preprint servers

<h2></h2>

<h2>bioRxiv</h2>

Since bioRxiv was only founded in 2013, we will be able to fetch articles **starting from 2013**.

The code below will search the keywords withing **TITLE** and **ABSTRACT** of the article's JSON

In [17]:
import requests, time, pandas as pd

#THESE are keywords by which bioRxiv,medRxiv searches within its articles
PHRASES = [
    "healthy aging","healthy ageing",
    "anti-aging","anti-ageing","anti aging","anti ageing",
    "biohacking","living longer",
    "well aging","well ageing","aging well","ageing well",
    "slow aging","slow ageing",
    "health rejuvenation","nootropics",
]

#This function build a query for search
def build_query(server="bioRxiv", y0=2010, y1=2025, use_synonyms=False):
    or_block      = " OR ".join(f'"{p}"' for p in PHRASES) #joins articles using OR statement, e.g. ("healthy aging" OR "healthy ageing" OR ...)
    q = f'(SRC:PPR) AND ("{server}") AND TITLE_ABS:({or_block}) AND (PUB_YEAR:[{y0} TO {y1}])' #concatenates the query with 
    params = {
        "query": q,
        "format": "json",
        "pageSize": 1000,      # max page size
        "resultType": "core",  # includes abstractText, pmid/pmcid when present
        "cursorMark": "*",     # start of cursor pagination
        "synonym": str(use_synonyms).lower()
    }
    return params

def epmc_search_all(params, pause=0.2, max_pages=None):
    url = "https://www.ebi.ac.uk/europepmc/webservices/rest/search"
    rows, total, pages = [], None, 0
    while True:
        r = requests.get(url, params=params, timeout=60)
        r.raise_for_status()
        js = r.json()
        if total is None:
            total = js.get("hitCount")
            print(f"Reported hitCount: {total}") #how many articles found in total
        batch = js.get("resultList", {}).get("result", [])
        rows.extend(batch) # append results to "rows"
        next_cursor = js.get("nextCursorMark")
        if not batch or next_cursor == params["cursorMark"]:
            break
        params["cursorMark"] = next_cursor # paginate through results
        pages += 1
        if max_pages and pages >= max_pages: # if the number of pages is greater than the limit we set, break
            break
        time.sleep(pause) # wait between every fetch
    return rows

if __name__ == "__main__":
    params = build_query(server = "bioRxiv", y0=2010, y1=2025, use_synonyms=False) #HERE you can change "bioRxiv" to "medRxiv" to retreive from 2 different servers
    data   = epmc_search_all(params)
    df     = pd.json_normalize(data)
    
    keep = ["id","pmid","pmcid","doi","title","pubYear","abstractText","source","authorString", "citedByCount", "server"]
    keep = [c for c in keep if c in df.columns]
    df_subset = df.reindex(columns=keep)

    df_subset.to_csv("biorxiv_longevity_titleabs_2010_2025.csv", index=False)
    print(f"Saved {len(df_subset)} rows")

Reported hitCount: 648
Saved 1296 rows

In [18]:
import pandas as pd

df_bio = pd.read_csv("biorxiv_longevity_titleabs_2010_2025.csv")

In [19]:
df_bio.shape

(1296, 8)

In [20]:
df_bio.groupby('citedByCount').size()

citedByCount
0    1088
1     162
2      26
3      16
4       2
7       2
dtype: int64

In [21]:
df_bio['pubYear'].value_counts().sort_index()

pubYear
2015      2
2016     12
2017     34
2018     68
2019     98
2020    144
2021    122
2022    162
2023    244
2024    226
2025    184
Name: count, dtype: int64

<h2> medRxiv</h2>

Since medRxiv was only founded in 2019, we will be able to fetch articles **starting from 2019**.

The code below will search the keywords withing **TITLE** and **ABSTRACT** of the article's JSON

In [26]:
import requests, time, pandas as pd

#THESE are keywords by which bioRxiv,medRxiv searches within its articles
PHRASES = [
    "longevity", 
    "healthy aging","healthy ageing",
    "anti-aging","anti-ageing","anti aging","anti ageing",
    "biohacking","living longer",
    "well aging","well ageing","aging well","ageing well",
    "slow aging","slow ageing",
    "health rejuvenation","nootropics",
]

#This function build a query for search
def build_query(server="bioRxiv", y0=2010, y1=2025, use_synonyms=False):
    or_block      = " OR ".join(f'"{p}"' for p in PHRASES) #joins articles using OR statement, e.g. ("healthy aging" OR "healthy ageing" OR ...)
    q = f'(SRC:PPR) AND ("{server}") AND TITLE_ABS:({or_block}) AND (PUB_YEAR:[{y0} TO {y1}])' #concatenates the query with 
    params = {
        "query": q,
        "format": "json",
        "pageSize": 1000,      # max page size
        "resultType": "core",  # includes abstractText, pmid/pmcid when present
        "cursorMark": "*",     # start of cursor pagination
        "synonym": str(use_synonyms).lower()
    }
    return params

def epmc_search_all(params, pause=0.2, max_pages=None):
    url = "https://www.ebi.ac.uk/europepmc/webservices/rest/search"
    rows, total, pages = [], None, 0
    while True:
        r = requests.get(url, params=params, timeout=60)
        r.raise_for_status()
        js = r.json()
        if total is None:
            total = js.get("hitCount")
            print(f"Reported hitCount: {total}") #how many articles found in total
        batch = js.get("resultList", {}).get("result", [])
        rows.extend(batch) # append results to "rows"
        next_cursor = js.get("nextCursorMark")
        if not batch or next_cursor == params["cursorMark"]:
            break
        params["cursorMark"] = next_cursor # paginate through results
        pages += 1
        if max_pages and pages >= max_pages: # if the number of pages is greater than the limit we set, break
            break
        time.sleep(pause) # wait between every fetch
    return rows

if __name__ == "__main__":
    params = build_query(server = "medRxiv", y0=2010, y1=2025, use_synonyms=False) #HERE you can change "bioRxiv" to "medRxiv" to retreive from 2 different servers
    data   = epmc_search_all(params)
    df     = pd.json_normalize(data)

    keep = ["id","pmid","pmcid","doi","title","pubYear","abstractText","source","authorString","citedByCount", "server"]
    keep = [c for c in keep if c in df.columns]
    df_subset = df.reindex(columns=keep)

    # #Fill missing citedByCount with zero
    # if "citedByCount" in df_subset.columns:
    #     df_subset["citedByCount"] = df_subset["citedByCount"].fillna(0).astype(int)

    df_subset.to_csv("medrxiv_longevity_titleabs_2010_2025_2.csv", index=False)
    print(f"Saved {len(df_subset)} rows")

Reported hitCount: 428
Saved 856 rows

In [31]:
import json

for record in data[:2]:
    print(json.dumps(record, indent=2))  # pretty print with indentation
    print("="*50)  # separator

{
  "id": "PPR1068272",
  "source": "PPR",
  "doi": "10.1101/2025.08.18.25333703",
  "title": "Evidence-Based Interventions Across the Life Course for Healthy Aging: A Scoping Review made in Colombia",
  "authorString": "Gonz\u00e1lez B LM, Mojica LE, Riveros S, Vanegas Zamora V, G\u00f3mez A, Otero MdP, Chaves F, Jaimes MA, L\u00f3pez V, Ram\u00edrez L, S\u00e1nchez V.",
  "authorList": {
    "author": [
      {
        "fullName": "Gonz\u00e1lez B LM",
        "firstName": "Lina Mar\u00eda",
        "lastName": "Gonz\u00e1lez B",
        "initials": "LM"
      },
      {
        "fullName": "Mojica LE",
        "firstName": "Luis Eduardo",
        "lastName": "Mojica",
        "initials": "LE"
      },
      {
        "fullName": "Riveros S",
        "firstName": "Shannon",
        "lastName": "Riveros",
        "initials": "S"
      },
      {
        "fullName": "Vanegas Zamora V",
        "firstName": "Valentina",
        "lastName": "Vanegas Zamora",
        "initials": "V"
      },
      {
        "fullName": "G\u00f3mez A",
        "firstName": "Anamar\u00eda",
        "lastName": "G\u00f3mez",
        "initials": "A"
      },
      {
        "fullName": "Otero MdP",
        "firstName": "Mar\u00eda del Pilar",
        "lastName": "Otero",
        "initials": "MdP"
      },
      {
        "fullName": "Chaves F",
        "firstName": "Felipe",
        "lastName": "Chaves",
        "initials": "F"
      },
      {
        "fullName": "Jaimes MA",
        "firstName": "Mar\u00eda Alejandra",
        "lastName": "Jaimes",
        "initials": "MA"
      },
      {
        "fullName": "L\u00f3pez V",
        "firstName": "Valery",
        "lastName": "L\u00f3pez",
        "initials": "V"
      },
      {
        "fullName": "Ram\u00edrez L",
        "firstName": "Lina",
        "lastName": "Ram\u00edrez",
        "initials": "L"
      },
      {
        "fullName": "S\u00e1nchez V",
        "firstName": "Valeria",
        "lastName": "S\u00e1nchez",
        "initials": "V"
      }
    ]
  },
  "authorIdList": {
    "authorId": [
      {
        "type": "ORCID",
        "value": "0000-0002-7821-4506"
      },
      {
        "type": "ORCID",
        "value": "0000-0003-1557-1036"
      }
    ]
  },
  "pubYear": "2025",
  "abstractText": "<h4>Background</h4>  Population aging is a major demographic challenge, particularly in low- and middle-income countries, where the burden of chronic and neurocognitive conditions is projected to grow sharply. <h4>Objectives</h4>  This scoping review aimed to synthesize scientific evidence on interventions that promote healthy aging across the life course. It was conducted following the Joanna Briggs Institute PCC framework. <h4>Methods</h4>  A systematic search was performed across PubMed, Scielo, EMBASE, PsycINFO, Cochrane, and LiLACS, without language or date restrictions. <h4>Results</h4>  From 5,808 records screened, 219 studies met the inclusion criteria, comprising systematic reviews, meta-analyses, clinical trials, quasi-experimental, and observational studies. Interventions were classified by thematic domains, including physical and mental health, social participation, education, technology, nutrition, public policy, and cultural aspects. <h4>Conclusions</h4>  Most studies focused on adult and older populations, with physical and mental health representing the predominant areas addressed, while other dimensions were less represented. Significant gaps remain regarding racially diverse populations, advanced-aged older adults, genetic stratification, and life-course perspectives, underscoring the need for diversified research designs to guide equitable and comprehensive healthy ageing strategies.",
  "pubTypeList": {
    "pubType": [
      "Preprint"
    ]
  },
  "bookOrReportDetails": {
    "publisher": "medRxiv",
    "yearOfPublication": 2025
  },
  "fullTextUrlList": {
    "fullTextUrl": [
      {
        "availability": "Free",
        "availabilityCode": "F",
        "documentStyle": "doi",
        "site": "DOI",
        "url": "https://doi.org/10.1101/2025.08.18.25333703"
      }
    ]
  },
  "isOpenAccess": "N",
  "inEPMC": "N",
  "inPMC": "N",
  "hasPDF": "N",
  "hasBook": "N",
  "hasSuppl": "N",
  "citedByCount": 0,
  "hasData": "N",
  "hasReferences": "Y",
  "hasTextMinedTerms": "N",
  "hasDbCrossReferences": "N",
  "hasLabsLinks": "N",
  "license": "cc by-nc-nd",
  "hasEvaluations": "N",
  "authMan": "N",
  "epmcAuthMan": "N",
  "nihAuthMan": "N",
  "hasTMAccessionNumbers": "N",
  "dateOfCreation": "2025-08-22",
  "firstIndexDate": "2025-08-22",
  "firstPublicationDate": "2025-08-19"
}
==================================================
{
  "id": "PPR1064618",
  "source": "PPR",
  "doi": "10.1101/2025.08.08.25333313",
  "title": "Sleep chart of biological aging clocks across organs and omics",
  "authorString": "The MULTI study, O\u2019Toole CK, Song Z, Anagnostakis F, Yang Z, Tian YE, Duggan MR, Zou C, Leng Y, Cai Y, Bai W, Fu CH, Rafii MS, Aisen P, Wang G, De Jager PL, Zeng J, Oh HS, Zhou X, Walker KA, Belsky DW, Zalesky A, Simonsick EM, Resnick SM, Ferrucci L, Davatzikos C, Wen J.",
  "authorList": {
    "author": [
      {
        "collectiveName": "The MULTI study"
      },
      {
        "fullName": "O\u2019Toole CK",
        "firstName": "Cliodhna Kate",
        "lastName": "O\u2019Toole",
        "initials": "CK"
      },
      {
        "fullName": "Song Z",
        "firstName": "Zhiyuan",
        "lastName": "Song",
        "initials": "Z"
      },
      {
        "fullName": "Anagnostakis F",
        "firstName": "Filippos",
        "lastName": "Anagnostakis",
        "initials": "F"
      },
      {
        "fullName": "Yang Z",
        "firstName": "Zhijian",
        "lastName": "Yang",
        "initials": "Z"
      },
      {
        "fullName": "Tian YE",
        "firstName": "Ye Ella",
        "lastName": "Tian",
        "initials": "YE"
      },
      {
        "fullName": "Duggan MR",
        "firstName": "Michael",
        "lastName": "Duggan",
        "initials": "MR"
      },
      {
        "fullName": "Zou C",
        "firstName": "Chunrui",
        "lastName": "Zou",
        "initials": "C"
      },
      {
        "fullName": "Leng Y",
        "firstName": "Yue",
        "lastName": "Leng",
        "initials": "Y"
      },
      {
        "fullName": "Cai Y",
        "firstName": "Yi",
        "lastName": "Cai",
        "initials": "Y"
      },
      {
        "fullName": "Bai W",
        "firstName": "Wenjia",
        "lastName": "Bai",
        "initials": "W"
      },
      {
        "fullName": "Fu CH",
        "firstName": "Cynthia H.Y.",
        "lastName": "Fu",
        "initials": "CH"
      },
      {
        "fullName": "Rafii MS",
        "firstName": "Michael",
        "lastName": "Rafii",
        "initials": "MS"
      },
      {
        "fullName": "Aisen P",
        "firstName": "Paul",
        "lastName": "Aisen",
        "initials": "P"
      },
      {
        "fullName": "Wang G",
        "firstName": "Gao",
        "lastName": "Wang",
        "initials": "G"
      },
      {
        "fullName": "De Jager PL",
        "firstName": "Philip",
        "lastName": "De Jager",
        "initials": "PL"
      },
      {
        "fullName": "Zeng J",
        "firstName": "Jian",
        "lastName": "Zeng",
        "initials": "J"
      },
      {
        "fullName": "Oh HS",
        "firstName": "Hamilton Se-Hwee",
        "lastName": "Oh",
        "initials": "HS"
      },
      {
        "fullName": "Zhou X",
        "firstName": "Xia",
        "lastName": "Zhou",
        "initials": "X"
      },
      {
        "fullName": "Walker KA",
        "firstName": "Keenan",
        "lastName": "Walker",
        "initials": "KA"
      },
      {
        "fullName": "Belsky DW",
        "firstName": "Daniel",
        "lastName": "Belsky",
        "initials": "DW"
      },
      {
        "fullName": "Zalesky A",
        "firstName": "Andrew",
        "lastName": "Zalesky",
        "initials": "A"
      },
      {
        "fullName": "Simonsick EM",
        "firstName": "Eleanor",
        "lastName": "Simonsick",
        "initials": "EM"
      },
      {
        "fullName": "Resnick SM",
        "firstName": "Susan",
        "lastName": "Resnick",
        "initials": "SM"
      },
      {
        "fullName": "Ferrucci L",
        "firstName": "Luigi",
        "lastName": "Ferrucci",
        "initials": "L"
      },
      {
        "fullName": "Davatzikos C",
        "firstName": "Christos",
        "lastName": "Davatzikos",
        "initials": "C"
      },
      {
        "fullName": "Wen J",
        "firstName": "Junhao",
        "lastName": "Wen",
        "initials": "J"
      }
    ]
  },
  "pubYear": "2025",
  "abstractText": "Optimal sleep plays a vital role in promoting healthy aging and enhancing longevity. This study proposes a Sleep Chart to assess the relationship between sleep duration and 23 biological aging clocks across 17 organ systems or tissues and 3 omics data types (imaging, proteomics, and metabolomics). First, a systemic, U-shaped pattern shows that both short (<6 hours) and long (>8 hours) sleep duration are linked to elevated biological age gaps (BAGs) across 9 brain and body systems and 3 omics types, with optimal sleep time varying by organ and sex ([6.4-7.8] hours). Furthermore, short and long sleep duration, compared to a normal sleep duration ([6-8] hours), are consistently linked to increased risk of systemic diseases beyond the brain and all-cause mortality, with evidence from genetic correlations and time to incident disease predictions, such as migraine, depression, and diabetes. Finally, short and long sleep duration are associated with late-life depression via distinct pathways: long sleep may contribute indirectly through biological aging processes, while short sleep shows a more direct link. Although our Mendelian randomization does not show strong causal effects from disease to sleep disturbances, it does not fully rule out the possibility that sleep disturbances may, in part, reflect underlying disease burden. Our findings suggest that the U-shaped relationship is likely driven by modifiable sleep disturbances rather than genetic predisposition, highlighting the potential of sleep optimization to support healthy aging, lower disease risk, and extend longevity. An interactive web portal is available to explore the Sleep Chart at: https://labs-laboratory.com/sleepchart .",
  "pubTypeList": {
    "pubType": [
      "Preprint"
    ]
  },
  "bookOrReportDetails": {
    "publisher": "medRxiv",
    "yearOfPublication": 2025
  },
  "fullTextUrlList": {
    "fullTextUrl": [
      {
        "availability": "Free",
        "availabilityCode": "F",
        "documentStyle": "doi",
        "site": "DOI",
        "url": "https://doi.org/10.1101/2025.08.08.25333313"
      }
    ]
  },
  "isOpenAccess": "N",
  "inEPMC": "N",
  "inPMC": "N",
  "hasPDF": "N",
  "hasBook": "N",
  "hasSuppl": "N",
  "citedByCount": 0,
  "hasData": "N",
  "hasReferences": "N",
  "hasTextMinedTerms": "N",
  "hasDbCrossReferences": "N",
  "hasLabsLinks": "N",
  "hasEvaluations": "N",
  "authMan": "N",
  "epmcAuthMan": "N",
  "nihAuthMan": "N",
  "hasTMAccessionNumbers": "N",
  "dateOfCreation": "2025-08-18",
  "firstIndexDate": "2025-08-18",
  "firstPublicationDate": "2025-08-11"
}
==================================================

In [27]:
import pandas as pd

df_med=pd.read_csv('medrxiv_longevity_titleabs_2010_2025_2.csv')
df_med['pubYear'].value_counts()

pubYear
2024    176
2023    150
2022    140
2025    136
2021    128
2020    116
2019     10
Name: count, dtype: int64

In [28]:
df_med.shape

(856, 8)

In [29]:
df.groupby('citedByCount').size()

citedByCount
0     746
1      76
2      16
3       4
4       2
5       4
8       2
10      2
26      2
52      2
dtype: int64

<h1> bioRxix and medRxiv: Bertopic Analysis </h1>

<h2> Data preperation </h2>

We searched the articles first without the keyword "longevity" and with. We will run seperately the bertopic analysis on those data and see if the keyword "longevity" brings more noisy data or not.

In [32]:
import pandas as pd

df_bio = pd.read_csv("biorxiv_longevity_titleabs_2010_2025.csv")
print(df_bio.shape)
df_med = pd.read_csv("medrxiv_longevity_titleabs_2010_2025.csv")
print(df_med.shape)
df_bio_lon = pd.read_csv("biorxiv_longevity_titleabs_2010_2025_2.csv") # data with keyword "longevity"
print(f'Data with longevit keyword: {df_bio_lon.shape}')
df_med_lon = pd.read_csv("medrxiv_longevity_titleabs_2010_2025_2.csv") # data with keyword "longevity"
print(f'Data with longevit keyword: {df_med_lon.shape}')

(1296, 8)
(404, 8)
Data with longevit keyword: (1866, 8)
Data with longevit keyword: (856, 8)

In [33]:
#let's assign server column
df_bio['server'] = 'bioRxiv'
df_med['server'] = 'medRxiv'
df_bio_lon['server'] = 'bioRxiv'
df_med_lon['server'] = 'medRxiv'

In [34]:
#Let's concat the dataframes
import pandas as pd
df = pd.concat([df_bio, df_med], ignore_index=True)
df_lon = pd.concat([df_bio_lon, df_med_lon], ignore_index=True)

In [35]:
#Let's check for the duplicates
print(f"Duplicates without longevity {df['doi'].duplicated().sum()}")
print(f"Duplicates with longevity {df_lon['doi'].duplicated().sum()}")

Duplicates without longevity 852
Duplicates with longevity 434

In [36]:
#droping duplicates
df = df.drop_duplicates(subset=['doi'], keep='first')
df_lon = df_lon.drop_duplicates(subset=['doi'], keep='first')

#check again
print(f"Duplicates without longevity {df['doi'].duplicated().sum()}")
print(f"Duplicates with longevity {df_lon['doi'].duplicated().sum()}")

Duplicates without longevity 0
Duplicates with longevity 0

In [37]:
#Let's check for the null values
print(f'Without longevity: \n{df.isnull().sum()}')
print(f'With longevity: \n{df_lon.isnull().sum()}')

Without longevity:
id              0
doi             0
title           0
pubYear         0
abstractText    0
source          0
authorString    0
citedByCount    0
server          0
dtype: int64
With longevity:
id              0
doi             0
title           0
pubYear         0
abstractText    1
source          0
authorString    0
citedByCount    0
server          0
dtype: int64

In [38]:
#let's deal with the null 
df_lon['abstractText'] = df_lon['abstractText'].fillna("")

In [39]:
#Let's check again
print(f'Without longevity: \n{df.isnull().sum()}')
print(f'With longevity: \n{df_lon.isnull().sum()}')

Without longevity:
id              0
doi             0
title           0
pubYear         0
abstractText    0
source          0
authorString    0
citedByCount    0
server          0
dtype: int64
With longevity:
id              0
doi             0
title           0
pubYear         0
abstractText    0
source          0
authorString    0
citedByCount    0
server          0
dtype: int64

In [45]:
#Last shape of the data
print(f'Without longevity: {df.shape}')
print(f'With longevity: {df_lon.shape}')

Without longevity: (848, 9)
With longevity: (2288, 9)

We have collected **842 articles** without adding the keyword longevity and **2285 articles** with keyword longevity. Let's save the file and check the topics

In [46]:
#Save data
df.to_csv("../data/clean_biomedRXiv.csv", index=False)
df_lon.to_csv("../data/clean_biomedRXiv_lon.csv", index=False)

<h2> Bertopic run</h2>

<h3> First data (without longevity)</h3>

In [1]:
import pandas as pd
df = pd.read_csv("../data/clean_biomedRXiv.csv")
df.head()

,id,doi,title,pubYear,abstractText,source,authorString,citedByCount,server
0,PPR1019256,10.1101/2025.05.11.651908,Discrimination of Normal from Slow-Aging Mice ...,2025,Tests that can predict whether a drug is likel...,PPR,"Badenoch B, Fiehn O, Rappaport N, Srivastava P...",0,bioRxiv
1,PPR1056170,10.1101/2025.07.25.666736,Nanoalgosomes from <i>Tetraselmis chuii</i>: M...,2025,The search for effective dermocosmetic treatme...,PPR,"Gargano P, Picciotto S, Paterna A, Raccosta S,...",0,bioRxiv
2,PPR1046197,10.1101/2025.06.30.660585,"Reporting quality, effect sizes, and biases fo...",2025,Though interest has grown significantly over t...,PPR,"Parish A, Ioannidis JP, Zhang K, Barardo D, Sw...",0,bioRxiv
3,PPR1047709,10.1101/2025.07.09.663908,Multi-omics characterization of the skin micro...,2025,Shifts in the skin microbiome have shown a clo...,PPR,"Guo D, Chen Y, Wu Y, Cheng J, Lai W, Ma W, Yan...",0,bioRxiv
4,PPR994570,10.1101/2025.03.25.645228,Bisphosphonates Trigger Anti-Ageing Effects Ac...,2025,Bisphosphonates (BPs) have been the major clas...,PPR,"Lu J, Rao SR, Knowles H, Zhan H, Gamez B, Plat...",0,bioRxiv

In [2]:
#Prepare the data
df['text'] = (
    df['title'].fillna('') + ". " + df['abstractText'].fillna('')
).str.lower().str.strip()

docs = df['text'].fillna("").tolist()

In [22]:
#Bertopic
import umap
from hdbscan import HDBSCAN
from bertopic import BERTopic
from nltk.corpus import stopwords
from sentence_transformers import SentenceTransformer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS

# Embedding model
model = SentenceTransformer("all-mpnet-base-v2")

# Custom stopwords
custom_stopwords = list(stopwords.words("english")) # + ["which stopwords can i add for biomedarix?"]

# Vectorizer
vectorizer_model = CountVectorizer(
    stop_words=custom_stopwords,
    ngram_range=(1, 2),
    max_df=0.9,   #0.85
    min_df=1,    # 2
    max_features=3000
)

# UMAP
umap_model = umap.UMAP(
    n_neighbors=10,   #15
    n_components=10,  # 5
    min_dist=0.0,
    random_state=42
)

# HDBSCAN
hdbscan_model = HDBSCAN(
    min_cluster_size=10,  #20
    min_samples=3,        # 5
    cluster_selection_epsilon=0.0,
    prediction_data=True
)


# BERTopic
topic_model = BERTopic(
    embedding_model=model,
    vectorizer_model=vectorizer_model,
    hdbscan_model=hdbscan_model,
    umap_model=umap_model,
    nr_topics=None,
    top_n_words=10,
    calculate_probabilities=True,
)

In [4]:
#Calculate the embeddings
embeddings = model.encode(docs, 
                          batch_size=4, 
                          normalize_embeddings=True, 
                          show_progress_bar=True).astype("float32")

Batches:   0%|          | 0/212 [00:00<?, ?it/s]

In [7]:
import numpy as np
np.save("../data/topics/embeddings.npy", embeddings)

In [9]:
#Run the bertopic
topics, probs = topic_model.fit_transform(docs, embeddings)

In [10]:
#Let's check out the topics
tp = topic_model.get_topic_info()
tp

,Topic,Count,Name,Representation,Representative_Docs
0,-1,196,-1_cognitive_health_older_adults,"[cognitive, health, older, adults, lifespan, g...",[ambient pollution components and sources asso...
1,0,55,0_ad_microglia_brain_alzheimer,"[ad, microglia, brain, alzheimer, plcγ2, neuro...",[trem2-dependent senescent microglia conserved...
2,1,38,1_covid_covid 19_19_pandemic,"[covid, covid 19, 19, pandemic, patients, sars...",[connecting bcg vaccination and covid-19: addi...
3,2,32,2_drosophila_lifespan_fathers_insulin,"[drosophila, lifespan, fathers, insulin, offsp...",[mapping<i>drosophila</i>insulin receptor stru...
4,3,31,3_connectivity_brain_network_functional,"[connectivity, brain, network, functional, net...",[how synchrony and metastable network dynamics...
5,4,28,4_memory_visual_older_episodic,"[memory, visual, older, episodic, neural, adul...",[the vertical position of visual information c...
6,5,23,5_care_social_health_dementia,"[care, social, health, dementia, end life, cog...",[piloting a minimum data set for older people ...
7,6,22,6_mci_mri_asl_slides,"[mci, mri, asl, slides, cognitive, segmentatio...","[multi-cohort, multi-sequence harmonisation fo..."
8,7,22,7_elegans_daf_lifespan_longevity,"[elegans, daf, lifespan, longevity, daf 16, da...",[daf-2/insulin igf-1 receptor regulates motili...
9,8,22,8_childhood_poverty_health_frailty,"[childhood, poverty, health, frailty, course, ...","[growing up in poverty, growing old with multi..."
10,9,21,9_mice_metabolic_male_cr,"[mice, metabolic, male, cr, 17α, treatment, mi...",[metabolic benefits of 17α-estradiol in liver ...
11,10,20,10_gut_microbiota_microbial_microbiome,"[gut, microbiota, microbial, microbiome, gut m...",[<i>ganoderma lucidum</i>alleviates kidney agi...
12,11,19,11_senescence_cells_evs_rv,"[senescence, cells, evs, rv, pulmonary, lung, ...","[senset, a novel human lung senescence cell ge..."
13,12,19,12_gaba_dopaminergic_cortex_glx,"[gaba, dopaminergic, cortex, glx, cso, metabol...",[the macromolecular mr spectrum in healthy agi...
14,13,18,13_cells_immune_cell_cd4,"[cells, immune, cell, cd4, antibodies, cmv, an...",[single-cell transcriptomics reveals expansion...
15,14,18,14_cognitive_wmh_white matter_matter,"[cognitive, wmh, white matter, matter, white, ...",[spatial distribution and cognitive impact of ...
16,15,15,15_organ_biological_biological age_df,"[organ, biological, biological age, df, mortal...",[blood omics models for system-specific mortal...
17,16,15,16_semantic_language_word_adults,"[semantic, language, word, adults, older, lp, ...",[dissociable electrophysiological measures of ...
18,17,15,17_music_auditory_speech_listening,"[music, auditory, speech, listening, older, ne...",[age-related variability in network engagement...
19,18,15,18_cortical_matter_neuromelanin_diffusion,"[cortical, matter, neuromelanin, diffusion, wh...",[quantification of alterations in diffusion me...
20,19,14,19_drug_drugs_metformin_anti,"[drug, drugs, metformin, anti, machine learnin...",[gene expression-based drug repurposing to tar...
21,20,14,20_stem_cells_sirt1_reprogramming,"[stem, cells, sirt1, reprogramming, dna, neura...",[multi-omic rejuvenation of human cells by mat...
22,21,14,21_skin_uv_hdfs_senescence,"[skin, uv, hdfs, senescence, derivatives, ca, ...",[multi-targeted effects of novel cycloastragen...
23,22,14,22_connectivity_lc_functional_functional conne...,"[connectivity, lc, functional, functional conn...",[age-related increase in locus coeruleus activ...
24,23,13,23_yeast_heme_aal1_cells,"[yeast, heme, aal1, cells, damage, ribosome, r...",[dietary change without caloric restriction ma...
25,24,13,24_movements_proprioceptive_young_adults,"[movements, proprioceptive, young, adults, old...",[the stop signal stepping task: how action can...
26,25,12,25_mitochondrial_mtdna_deletions_neurons,"[mitochondrial, mtdna, deletions, neurons, rep...",[decreasing pdzd8-mediated mitochondrial-er co...
27,26,12,26_curcumin_haao_stress_ferroptosis,"[curcumin, haao, stress, ferroptosis, resistan...","[the 1 –cys peroxiredoxin, prdx-6, suppresses ..."
28,27,12,27_gamma_power_eeg_hz,"[gamma, power, eeg, hz, oscillations, aperiodi...",[auditory and visual gratings elicit distinct ...
29,28,12,28_epigenetic_clocks_methylation_epigenetic cl...,"[epigenetic, clocks, methylation, epigenetic c...",[dna methylation aging and transcriptomic stud...
30,29,12,29_bat_killifish_lived_fish,"[bat, killifish, lived, fish, mole, species, z...",[limited cell-autonomous anticancer mechanisms...
31,30,11,30_sleep_functional disability_sleep quality_d...,"[sleep, functional disability, sleep quality, ...",[sleep chart of biological aging clocks across...
32,31,11,31_muscle_exercise_skeletal_skeletal muscle,"[muscle, exercise, skeletal, skeletal muscle, ...",[exercise preserves fitness capacity during ag...
33,32,10,32_variants_longevity_model organisms_stress,"[variants, longevity, model organisms, stress,...",[deep phenotyping and lifetime trajectories re...
34,33,10,33_clocks_epigenetic_methylation_biological,"[clocks, epigenetic, methylation, biological, ...",[dna methylation clocks struggle to distinguis...
35,34,10,34_brain_frequency_eeg_meg,"[brain, frequency, eeg, meg, rs, activity, dyn...",[robust and replicable effects of ageing on re...
36,35,10,35_t2d_ancestry_neuroticism_genetic,"[t2d, ancestry, neuroticism, genetic, genome, ...",[genetic regulation of fatty acid content in a...

In [11]:
#create topic column
df['topic'] = topics

<h4>Saving the data</h4>

In [12]:
import numpy as np
import pandas as pd
import pickle


tp.to_csv('../data/topics/topics.csv', index=False)
topic_model.save("../data/topics/topic_model")
np.save('../data/topics/topic_probabilities.npy', probs)
with open('../data/topics/preprocessed_data.pkl', 'wb') as f:
    pickle.dump(docs, f)
df.to_csv('../data/topics/data.csv', index=False)

2025-09-05 14:37:39,352 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

In [13]:
#Saving without UMAP
topic_model.umap_model = None
topic_model.save("../data/topics/topic_model_no_umap")

2025-09-05 14:38:14,508 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

<h3> Second data (with longevity)</h3>

In [16]:
import pandas as pd
df_lon = pd.read_csv("../data/clean_biomedRXiv_lon.csv")
df_lon.head()

,id,doi,title,pubYear,abstractText,source,authorString,citedByCount,server
0,PPR1019256,10.1101/2025.05.11.651908,Discrimination of Normal from Slow-Aging Mice ...,2025,Tests that can predict whether a drug is likel...,PPR,"Badenoch B, Fiehn O, Rappaport N, Srivastava P...",0,bioRxiv
1,PPR1078166,10.1101/2025.08.29.673072,Evolution of increased longevity and slowed ag...,2025,Evolution has given rise to lifespans in extan...,PPR,"Foley J, McPherson J, Roger M, Batista C, Maux...",0,bioRxiv
2,PPR1056170,10.1101/2025.07.25.666736,Nanoalgosomes from <i>Tetraselmis chuii</i>: M...,2025,The search for effective dermocosmetic treatme...,PPR,"Gargano P, Picciotto S, Paterna A, Raccosta S,...",0,bioRxiv
3,PPR1027860,10.1101/2025.05.26.656117,Methyl Nicotinate Is a Novel Geroprotective Co...,2025,Aging involves cellular decline and reduced st...,PPR,"Mingtong G, Alfatah M.",0,bioRxiv
4,PPR996689,10.1101/2025.03.26.645451,Dietary restriction is evolutionary conserved ...,2025,<h4>ABSTRACT</h4> The anti-ageing response of ...,PPR,"Gautrey SL, Dunning LT, Gossmann TI, Simons MJP.",0,bioRxiv

In [19]:
#Prepare the data
df_lon['text'] = (
    df_lon['title'].fillna('') + ". " + df_lon['abstractText'].fillna('')
).str.lower().str.strip()

docs_lon = df_lon['text'].fillna("").tolist()

In [20]:
#Calculate the embeddings
embeddings = model.encode(docs_lon, 
                          batch_size=4, 
                          normalize_embeddings=True, 
                          show_progress_bar=True).astype("float32")

Batches:   0%|          | 0/572 [00:00<?, ?it/s]

In [21]:
import numpy as np
np.save("../data/topics_lon/embeddings.npy", embeddings)

In [23]:
#Bertopic
import umap
from hdbscan import HDBSCAN
from bertopic import BERTopic
from nltk.corpus import stopwords
from sentence_transformers import SentenceTransformer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS

# Embedding model
model = SentenceTransformer("all-mpnet-base-v2")

# Custom stopwords
custom_stopwords = list(stopwords.words("english")) # + ["which stopwords can i add for biomedarix?"]

# Vectorizer
vectorizer_model = CountVectorizer(
    stop_words=custom_stopwords,
    ngram_range=(1, 2),
    max_df=0.9,   #0.85
    min_df=1,    # 2
    max_features=3000
)

# UMAP
umap_model = umap.UMAP(
    n_neighbors=10,   #15
    n_components=10,  # 5
    min_dist=0.0,
    random_state=42
)

# HDBSCAN
hdbscan_model = HDBSCAN(
    min_cluster_size=10,  #20
    min_samples=3,        # 5
    cluster_selection_epsilon=0.0,
    prediction_data=True
)


# BERTopic
topic_model = BERTopic(
    embedding_model=model,
    vectorizer_model=vectorizer_model,
    hdbscan_model=hdbscan_model,
    umap_model=umap_model,
    nr_topics=None,
    top_n_words=10,
    calculate_probabilities=True,
)

In [24]:
#Run the bertopic
topics, probs = topic_model.fit_transform(docs_lon, embeddings)

In [34]:
tp_lon = topic_model.get_topic_info()
tp_lon

,Topic,Count,Name,Representation,Representative_Docs
0,-1,406,-1_aging_lifespan_protein_cell,"[aging, lifespan, protein, cell, genes, mice, ...",[transcriptome analysis of the nematode <i>cae...
1,0,317,0_brain_cognitive_adults_older,"[brain, cognitive, adults, older, healthy, mem...",[resting-state eeg aperiodic exponent moderate...
2,1,86,1_biological_dnam_clocks_methylation,"[biological, dnam, clocks, methylation, epigen...",[evaluation of epigenetic and metabolomic biom...
3,2,85,2_genetic_variants_association_risk,"[genetic, variants, association, risk, diabete...",[robust inference and widespread genetic corre...
4,3,69,3_drosophila_dr_flies_lifespan,"[drosophila, dr, flies, lifespan, diet, dietar...",[dietary restriction is evolutionary conserved...
5,4,65,4_cells_cell_cd4_cd8,"[cells, cell, cd4, cd8, immune, hiv, memory, e...",[single-cell transcriptomics reveals expansion...
6,5,54,5_yeast_lifespan_cerevisiae_cells,"[yeast, lifespan, cerevisiae, cells, saccharom...",[rapid nuclear exclusion of hcm1 in aging<i>sa...
7,6,51,6_cancer_mole_genes_evolution,"[cancer, mole, genes, evolution, species, rat,...",[long-lived rodents reveal signatures of posit...
8,7,49,7_microglia_ad_plcγ2_alzheimer,"[microglia, ad, plcγ2, alzheimer, brain, disea...",[protective variant in plcγ2 mitigates alzheim...
9,8,41,8_mitochondrial_atfs_mitochondria_upr mt,"[mitochondrial, atfs, mitochondria, upr mt, up...",[developmental disruption of the mitochondrial...
10,9,39,9_mosquitoes_mosquito_aegypti_vector,"[mosquitoes, mosquito, aegypti, vector, aedes,...",[analysis of <i>aedes aegypti</i> micrornas in...
11,10,38,10_seed_seed longevity_seeds_germination,"[seed, seed longevity, seeds, germination, ara...",[<i>phytoene synthase</i> modulates seed longe...
12,11,36,11_queens_queen_bee_honey,"[queens, queen, bee, honey, bees, workers, col...",[the lifespan and levels of oxidative stress b...
13,12,33,12_gut_microbiota_gut microbiota_microbiome,"[gut, microbiota, gut microbiota, microbiome, ...",[gut microbiota predicts healthy late-life agi...
14,13,32,13_elegans_fmo_stress_stress resistance,"[elegans, fmo, stress, stress resistance, life...","[the 1 –cys peroxiredoxin, prdx-6, suppresses ..."
15,14,32,14_electrodes_electrode_neural_arrays,"[electrodes, electrode, neural, arrays, record...",[the “sewing machine” for minimally invasive n...
16,15,31,15_muscle_skeletal_skeletal muscle_exercise,"[muscle, skeletal, skeletal muscle, exercise, ...",[transferrin receptor (tfr1) ablation in satel...
17,16,30,16_sars_cov_sars cov_vaccine,"[sars, cov, sars cov, vaccine, vaccination, co...",[the bnt162b2 mrna vaccine induces polyfunctio...
18,17,27,17_sperm_mating_males_fathers,"[sperm, mating, males, fathers, fitness, male,...",[sperm competition influences sperm quality an...
19,18,27,18_ad_apoe_risk_kl,"[ad, apoe, risk, kl, alzheimer, dementia, alzh...",[<i>apoe</i>loss-of-function variants: compati...
20,19,25,19_species_life history_genetic diversity_history,"[species, life history, genetic diversity, his...",[aquatic and terrestrial organisms display con...
21,20,25,20_resistance_antibiotic_bacterial_gram,"[resistance, antibiotic, bacterial, gram, bact...",[tripartite loops reverse antibiotic resistanc...
22,21,25,21_drosophila_flies_neuronal_neurons,"[drosophila, flies, neuronal, neurons, fly, pd...",[comprehensive modeling of spinal muscular atr...
23,22,24,22_epigenetic_methylation_clocks_epigenetic cl...,"[epigenetic, methylation, clocks, epigenetic c...",[dna methylation age analysis of rapamycin in ...
24,23,23,23_flies_drosophila_host_microbiota,"[flies, drosophila, host, microbiota, immune, ...",[strong experimental support for the hologenom...
25,24,23,24_host_elegans_bacterial_bacteria,"[host, elegans, bacterial, bacteria, strain, g...",[from pathogen to commensal to probiotic: modi...
26,25,23,25_trees_tree_plant_plants,"[trees, tree, plant, plants, growth, leaf, his...",[chromosome-level baobab (<i>adansonia digitat...
27,26,22,26_social_adversity_early life_offspring,"[social, adversity, early life, offspring, mat...",[population density and temperature influence ...
28,27,22,27_covid 19_covid_19_mortality,"[covid 19, covid, 19, mortality, risk, co, pan...",[covid-19 severity is predicted by earlier evi...
29,28,21,28_germline_reproductive_mutants_reproduction,"[germline, reproductive, mutants, reproduction...",[cost-free lifespan extension via optimisation...
30,29,21,29_mice_dietary_lifespan_dr,"[mice, dietary, lifespan, dr, restriction, die...",[a reevaluation of the effect of dietary restr...
31,30,20,30_care_impairment_end life_policy,"[care, impairment, end life, policy, india, ol...",[intrinsic capacity as a framework for integra...
32,31,19,31_sars_sars cov_cov_covid,"[sars, sars cov, cov, covid, covid 19, 19, pcr...",[sars-cov-2 seroconversion in health care work...
33,32,18,32_lipid_elegans_restriction_fat,"[lipid, elegans, restriction, fat, caloric, me...",[nutrient sensing pathways regulating adult re...
34,33,18,33_drugs_drug_compounds_machine learning,"[drugs, drug, compounds, machine learning, mac...",[a deep learning proteomic scale approach for ...
35,34,17,34_senescence_aging_ageing_biological,"[senescence, aging, ageing, biological, p53, s...",[cross-species functional modules link proteos...
36,35,17,35_estradiol_nad_mice_treatment,"[estradiol, nad, mice, treatment, male, male m...","[health benefits attributed to 17α-estradiol, ..."
37,36,16,36_skin_anti aging_zinc_anti,"[skin, anti aging, zinc, anti, extract, aging ...",[the novel roles of bovine milk-derived exosom...
38,37,16,37_organoids_culture_3d_chip,"[organoids, culture, 3d, chip, liver, endothel...",[a novel bioreactor technology for modelling f...
39,38,16,38_cardiac_bone_implant_heart,"[cardiac, bone, implant, heart, pulmonary, cel...",[self-assembled chambered cardiac organoids fo...
40,39,15,39_daf_daf 16_16_iis,"[daf, daf 16, 16, iis, insulin, elegans, insul...",[the pp2a/4/6 subfamily of phosphoprotein phos...
41,40,15,40_countries_expectancy_life expectancy_mortality,"[countries, expectancy, life expectancy, morta...",[potential gains in health-adjusted life expec...
42,41,15,41_pandemic_covid_covid 19_19,"[pandemic, covid, covid 19, 19, 19 pandemic, m...",[social determinants of recovery from ongoing ...
43,42,14,42_purpose_life purpose_social_loneliness,"[purpose, life purpose, social, loneliness, re...",[associations of loneliness and social isolati...
44,43,14,43_rapamycin_mtor_treatment_acarbose,"[rapamycin, mtor, treatment, acarbose, mice, m...",[sexual identity of enterocytes regulates rapa...
45,44,14,44_er_upr_17_neuronal,"[er, upr, 17, neuronal, neurons, il, nervous s...",[homeodomain-interacting protein kinase mainta...
46,45,13,45_methylation_epigenetic_dnam_epigenetic aging,"[methylation, epigenetic, dnam, epigenetic agi...",[genetic loci and metabolic states associated ...
47,46,13,46_sirt3_sirt6_pd_synuclein,"[sirt3, sirt6, pd, synuclein, activity, dna, s...",[dna stimulates sirt6 to mono-adp-ribosylate p...
48,47,13,47_mir_mirnas_rna_small,"[mir, mirnas, rna, small, muscle, biogenesis, ...",[mir-1 coordinately regulates lysosomal v-atpa...
49,48,13,48_ha_rat_growth_mole rat,"[ha, rat, growth, mole rat, aging, zebrafish, ...",[evolution of high-molecular-mass hyaluronic a...
50,49,13,49_histone_set_elegans_lifespan,"[histone, set, elegans, lifespan, oxidative, f...",[impact of inhibitors of histone post-translat...
51,50,13,50_lifespan_assays_elegans_interventions,"[lifespan, assays, elegans, interventions, aut...",[nemalife: a structured microfluidic culture d...
52,51,12,51_patients_sars_sars cov_cov,"[patients, sars, sars cov, cov, neutralizing, ...",[longevity of sars-cov-2 immune responses in h...
53,52,12,52_hypoxia_germline_hsf_heat,"[hypoxia, germline, hsf, heat, animals, elegan...",[hsb-1 inhibition and hsf-1 overexpression tri...
54,53,12,53_antibodies_cov_sars cov_sars,"[antibodies, cov, sars cov, sars, antibody, an...",[characterising heterogeneity and sero-reversi...
55,54,12,54_malaria_zikv_vivax_vaccine,"[malaria, zikv, vivax, vaccine, antibody, resp...",[naturally acquired antibody kinetics against ...
56,55,12,55_mtdna_mitochondrial_single_mutations,"[mtdna, mitochondrial, single, mutations, copy...",[mammalian mitochondrial mutational spectrum a...
57,56,12,56_childhood_frailty_poverty_income,"[childhood, frailty, poverty, income, unhealth...","[growing up in poverty, growing old with multi..."
58,57,11,57_hypertension_pulmonary_blood pressure_women,"[hypertension, pulmonary, blood pressure, wome...",[validating a previously untested ‘intentions ...
59,58,11,58_physical_physical activity_devices_activity,"[physical, physical activity, devices, activit...",[light at night and modeled circadian disrupti...
60,59,10,59_bat_bats_protocol_viruses,"[bat, bats, protocol, viruses, primary, viral,...",[limited cell-autonomous anticancer mechanisms...
61,60,10,60_exposure_nmn_fecundity_age related,"[exposure, nmn, fecundity, age related, fish, ...",[regeneration leads to global tissue rejuvenat...
62,61,10,61_reprogramming_rejuvenation_stem_intestinal,"[reprogramming, rejuvenation, stem, intestinal...",[chemical reprogramming ameliorates cellular h...
63,62,10,62_soil_root_autophagy_plant,"[soil, root, autophagy, plant, virus, plants, ...",[a study on tomato brown rugose fruit virus lo...
64,63,10,63_wolbachia_larvae_hosts_insect,"[wolbachia, larvae, hosts, insect, infected, h...",[bacterial supergroup specific “cost” of <i>wo...
65,64,10,64_telomere_telomere length_glucose_length,"[telomere, telomere length, glucose, length, o...",[maternal glucocorticoids promote offspring gr...
66,65,10,65_tdp 43_43_tdp_pathology,"[tdp 43, 43, tdp, pathology, neurons, behaviou...",[amygdala tdp-43 pathology is associated with ...

In [30]:
df_lon['topic']=topics

In [32]:
df_lon.head()

,id,doi,title,pubYear,abstractText,source,authorString,citedByCount,server,text,topic
0,PPR1019256,10.1101/2025.05.11.651908,Discrimination of Normal from Slow-Aging Mice ...,2025,Tests that can predict whether a drug is likel...,PPR,"Badenoch B, Fiehn O, Rappaport N, Srivastava P...",0,bioRxiv,discrimination of normal from slow-aging mice ...,33
1,PPR1078166,10.1101/2025.08.29.673072,Evolution of increased longevity and slowed ag...,2025,Evolution has given rise to lifespans in extan...,PPR,"Foley J, McPherson J, Roger M, Batista C, Maux...",0,bioRxiv,evolution of increased longevity and slowed ag...,-1
2,PPR1056170,10.1101/2025.07.25.666736,Nanoalgosomes from <i>Tetraselmis chuii</i>: M...,2025,The search for effective dermocosmetic treatme...,PPR,"Gargano P, Picciotto S, Paterna A, Raccosta S,...",0,bioRxiv,nanoalgosomes from <i>tetraselmis chuii</i>: m...,36
3,PPR1027860,10.1101/2025.05.26.656117,Methyl Nicotinate Is a Novel Geroprotective Co...,2025,Aging involves cellular decline and reduced st...,PPR,"Mingtong G, Alfatah M.",0,bioRxiv,methyl nicotinate is a novel geroprotective co...,5
4,PPR996689,10.1101/2025.03.26.645451,Dietary restriction is evolutionary conserved ...,2025,<h4>ABSTRACT</h4> The anti-ageing response of ...,PPR,"Gautrey SL, Dunning LT, Gossmann TI, Simons MJP.",0,bioRxiv,dietary restriction is evolutionary conserved ...,3

<h4>Saving the data</h4>

In [35]:
import numpy as np
import pandas as pd
import pickle


tp_lon.to_csv('../data/topics_lon/topics.csv', index=False)
topic_model.save("../data/topics_lon/topic_model")
np.save('../data/topics_lon/topic_probabilities.npy', probs)
with open('../data/topics_lon/preprocessed_data.pkl', 'wb') as f:
    pickle.dump(docs_lon, f)
df_lon.to_csv('../data/topics_lon/data.csv', index=False)

2025-09-05 22:21:33,995 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

In [36]:
#Saving without UMAP
topic_model.umap_model = None
topic_model.save("../data/topics_lon/topic_model_no_umap")

2025-09-05 22:23:04,258 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

<h2> Analyze bertopic </h2>

<h3>Topics with longevity</h3>

Let's first analyze the topics with the word longevity. The "longevity" keyword is the one of the important ones. It will be better to inlude it in our data. That's why we will analyze this data first, and if it will be good, then we will use it.

In [5]:
#To show max amount of vidoes
pd.set_option("display.max_rows", None)

In [6]:
import pandas as pd

tp = pd.read_csv("../data/topics_lon/topics.csv")
df = pd.read_csv("../data/topics_lon/data.csv")

Let's check the each topic individually to see whether it is related or not.

In [7]:
tp

,Topic,Count,Name,Representation,Representative_Docs
0,-1,406,-1_aging_lifespan_protein_cell,"['aging', 'lifespan', 'protein', 'cell', 'gene...",['transcriptome analysis of the nematode <i>ca...
1,0,317,0_brain_cognitive_adults_older,"['brain', 'cognitive', 'adults', 'older', 'hea...",['resting-state eeg aperiodic exponent moderat...
2,1,86,1_biological_dnam_clocks_methylation,"['biological', 'dnam', 'clocks', 'methylation'...",['evaluation of epigenetic and metabolomic bio...
3,2,85,2_genetic_variants_association_risk,"['genetic', 'variants', 'association', 'risk',...",['robust inference and widespread genetic corr...
4,3,69,3_drosophila_dr_flies_lifespan,"['drosophila', 'dr', 'flies', 'lifespan', 'die...",['dietary restriction is evolutionary conserve...
5,4,65,4_cells_cell_cd4_cd8,"['cells', 'cell', 'cd4', 'cd8', 'immune', 'hiv...",['single-cell transcriptomics reveals expansio...
6,5,54,5_yeast_lifespan_cerevisiae_cells,"['yeast', 'lifespan', 'cerevisiae', 'cells', '...",['rapid nuclear exclusion of hcm1 in aging<i>s...
7,6,51,6_cancer_mole_genes_evolution,"['cancer', 'mole', 'genes', 'evolution', 'spec...",['long-lived rodents reveal signatures of posi...
8,7,49,7_microglia_ad_plcγ2_alzheimer,"['microglia', 'ad', 'plcγ2', 'alzheimer', 'bra...",['protective variant in plcγ2 mitigates alzhei...
9,8,41,8_mitochondrial_atfs_mitochondria_upr mt,"['mitochondrial', 'atfs', 'mitochondria', 'upr...",['developmental disruption of the mitochondria...
10,9,39,9_mosquitoes_mosquito_aegypti_vector,"['mosquitoes', 'mosquito', 'aegypti', 'vector'...",['analysis of <i>aedes aegypti</i> micrornas i...
11,10,38,10_seed_seed longevity_seeds_germination,"['seed', 'seed longevity', 'seeds', 'germinati...",['<i>phytoene synthase</i> modulates seed long...
12,11,36,11_queens_queen_bee_honey,"['queens', 'queen', 'bee', 'honey', 'bees', 'w...",['the lifespan and levels of oxidative stress ...
13,12,33,12_gut_microbiota_gut microbiota_microbiome,"['gut', 'microbiota', 'gut microbiota', 'micro...",['gut microbiota predicts healthy late-life ag...
14,13,32,13_elegans_fmo_stress_stress resistance,"['elegans', 'fmo', 'stress', 'stress resistanc...","['the 1 –cys peroxiredoxin, prdx-6, suppresses..."
15,14,32,14_electrodes_electrode_neural_arrays,"['electrodes', 'electrode', 'neural', 'arrays'...",['the “sewing machine” for minimally invasive ...
16,15,31,15_muscle_skeletal_skeletal muscle_exercise,"['muscle', 'skeletal', 'skeletal muscle', 'exe...",['transferrin receptor (tfr1) ablation in sate...
17,16,30,16_sars_cov_sars cov_vaccine,"['sars', 'cov', 'sars cov', 'vaccine', 'vaccin...",['the bnt162b2 mrna vaccine induces polyfuncti...
18,17,27,17_sperm_mating_males_fathers,"['sperm', 'mating', 'males', 'fathers', 'fitne...",['sperm competition influences sperm quality a...
19,18,27,18_ad_apoe_risk_kl,"['ad', 'apoe', 'risk', 'kl', 'alzheimer', 'dem...",['<i>apoe</i>loss-of-function variants: compat...
20,19,25,19_species_life history_genetic diversity_history,"['species', 'life history', 'genetic diversity...",['aquatic and terrestrial organisms display co...
21,20,25,20_resistance_antibiotic_bacterial_gram,"['resistance', 'antibiotic', 'bacterial', 'gra...",['tripartite loops reverse antibiotic resistan...
22,21,25,21_drosophila_flies_neuronal_neurons,"['drosophila', 'flies', 'neuronal', 'neurons',...",['comprehensive modeling of spinal muscular at...
23,22,24,22_epigenetic_methylation_clocks_epigenetic cl...,"['epigenetic', 'methylation', 'clocks', 'epige...",['dna methylation age analysis of rapamycin in...
24,23,23,23_flies_drosophila_host_microbiota,"['flies', 'drosophila', 'host', 'microbiota', ...",['strong experimental support for the hologeno...
25,24,23,24_host_elegans_bacterial_bacteria,"['host', 'elegans', 'bacterial', 'bacteria', '...",['from pathogen to commensal to probiotic: mod...
26,25,23,25_trees_tree_plant_plants,"['trees', 'tree', 'plant', 'plants', 'growth',...",['chromosome-level baobab (<i>adansonia digita...
27,26,22,26_social_adversity_early life_offspring,"['social', 'adversity', 'early life', 'offspri...",['population density and temperature influence...
28,27,22,27_covid 19_covid_19_mortality,"['covid 19', 'covid', '19', 'mortality', 'risk...",['covid-19 severity is predicted by earlier ev...
29,28,21,28_germline_reproductive_mutants_reproduction,"['germline', 'reproductive', 'mutants', 'repro...",['cost-free lifespan extension via optimisatio...
30,29,21,29_mice_dietary_lifespan_dr,"['mice', 'dietary', 'lifespan', 'dr', 'restric...",['a reevaluation of the effect of dietary rest...
31,30,20,30_care_impairment_end life_policy,"['care', 'impairment', 'end life', 'policy', '...",['intrinsic capacity as a framework for integr...
32,31,19,31_sars_sars cov_cov_covid,"['sars', 'sars cov', 'cov', 'covid', 'covid 19...",['sars-cov-2 seroconversion in health care wor...
33,32,18,32_lipid_elegans_restriction_fat,"['lipid', 'elegans', 'restriction', 'fat', 'ca...",['nutrient sensing pathways regulating adult r...
34,33,18,33_drugs_drug_compounds_machine learning,"['drugs', 'drug', 'compounds', 'machine learni...",['a deep learning proteomic scale approach for...
35,34,17,34_senescence_aging_ageing_biological,"['senescence', 'aging', 'ageing', 'biological'...",['cross-species functional modules link proteo...
36,35,17,35_estradiol_nad_mice_treatment,"['estradiol', 'nad', 'mice', 'treatment', 'mal...","['health benefits attributed to 17α-estradiol,..."
37,36,16,36_skin_anti aging_zinc_anti,"['skin', 'anti aging', 'zinc', 'anti', 'extrac...",['the novel roles of bovine milk-derived exoso...
38,37,16,37_organoids_culture_3d_chip,"['organoids', 'culture', '3d', 'chip', 'liver'...",['a novel bioreactor technology for modelling ...
39,38,16,38_cardiac_bone_implant_heart,"['cardiac', 'bone', 'implant', 'heart', 'pulmo...",['self-assembled chambered cardiac organoids f...
40,39,15,39_daf_daf 16_16_iis,"['daf', 'daf 16', '16', 'iis', 'insulin', 'ele...",['the pp2a/4/6 subfamily of phosphoprotein pho...
41,40,15,40_countries_expectancy_life expectancy_mortality,"['countries', 'expectancy', 'life expectancy',...",['potential gains in health-adjusted life expe...
42,41,15,41_pandemic_covid_covid 19_19,"['pandemic', 'covid', 'covid 19', '19', '19 pa...",['social determinants of recovery from ongoing...
43,42,14,42_purpose_life purpose_social_loneliness,"['purpose', 'life purpose', 'social', 'lonelin...",['associations of loneliness and social isolat...
44,43,14,43_rapamycin_mtor_treatment_acarbose,"['rapamycin', 'mtor', 'treatment', 'acarbose',...",['sexual identity of enterocytes regulates rap...
45,44,14,44_er_upr_17_neuronal,"['er', 'upr', '17', 'neuronal', 'neurons', 'il...",['homeodomain-interacting protein kinase maint...
46,45,13,45_methylation_epigenetic_dnam_epigenetic aging,"['methylation', 'epigenetic', 'dnam', 'epigene...",['genetic loci and metabolic states associated...
47,46,13,46_sirt3_sirt6_pd_synuclein,"['sirt3', 'sirt6', 'pd', 'synuclein', 'activit...",['dna stimulates sirt6 to mono-adp-ribosylate ...
48,47,13,47_mir_mirnas_rna_small,"['mir', 'mirnas', 'rna', 'small', 'muscle', 'b...",['mir-1 coordinately regulates lysosomal v-atp...
49,48,13,48_ha_rat_growth_mole rat,"['ha', 'rat', 'growth', 'mole rat', 'aging', '...",['evolution of high-molecular-mass hyaluronic ...
50,49,13,49_histone_set_elegans_lifespan,"['histone', 'set', 'elegans', 'lifespan', 'oxi...",['impact of inhibitors of histone post-transla...
51,50,13,50_lifespan_assays_elegans_interventions,"['lifespan', 'assays', 'elegans', 'interventio...",['nemalife: a structured microfluidic culture ...
52,51,12,51_patients_sars_sars cov_cov,"['patients', 'sars', 'sars cov', 'cov', 'neutr...",['longevity of sars-cov-2 immune responses in ...
53,52,12,52_hypoxia_germline_hsf_heat,"['hypoxia', 'germline', 'hsf', 'heat', 'animal...",['hsb-1 inhibition and hsf-1 overexpression tr...
54,53,12,53_antibodies_cov_sars cov_sars,"['antibodies', 'cov', 'sars cov', 'sars', 'ant...",['characterising heterogeneity and sero-revers...
55,54,12,54_malaria_zikv_vivax_vaccine,"['malaria', 'zikv', 'vivax', 'vaccine', 'antib...",['naturally acquired antibody kinetics against...
56,55,12,55_mtdna_mitochondrial_single_mutations,"['mtdna', 'mitochondrial', 'single', 'mutation...",['mammalian mitochondrial mutational spectrum ...
57,56,12,56_childhood_frailty_poverty_income,"['childhood', 'frailty', 'poverty', 'income', ...","['growing up in poverty, growing old with mult..."
58,57,11,57_hypertension_pulmonary_blood pressure_women,"['hypertension', 'pulmonary', 'blood pressure'...",['validating a previously untested ‘intentions...
59,58,11,58_physical_physical activity_devices_activity,"['physical', 'physical activity', 'devices', '...",['light at night and modeled circadian disrupt...
60,59,10,59_bat_bats_protocol_viruses,"['bat', 'bats', 'protocol', 'viruses', 'primar...",['limited cell-autonomous anticancer mechanism...
61,60,10,60_exposure_nmn_fecundity_age related,"['exposure', 'nmn', 'fecundity', 'age related'...",['regeneration leads to global tissue rejuvena...
62,61,10,61_reprogramming_rejuvenation_stem_intestinal,"['reprogramming', 'rejuvenation', 'stem', 'int...",['chemical reprogramming ameliorates cellular ...
63,62,10,62_soil_root_autophagy_plant,"['soil', 'root', 'autophagy', 'plant', 'virus'...",['a study on tomato brown rugose fruit virus l...
64,63,10,63_wolbachia_larvae_hosts_insect,"['wolbachia', 'larvae', 'hosts', 'insect', 'in...",['bacterial supergroup specific “cost” of <i>w...
65,64,10,64_telomere_telomere length_glucose_length,"['telomere', 'telomere length', 'glucose', 'le...",['maternal glucocorticoids promote offspring g...
66,65,10,65_tdp 43_43_tdp_pathology,"['tdp 43', '43', 'tdp', 'pathology', 'neurons'...",['amygdala tdp-43 pathology is associated with...

In [10]:
#to show the columns
pd.set_option("display.max_colwidth", None)

In [32]:
df['is_relevant']=True
tp['is_relevant']=True

In [112]:
#check topics
dfp = df[df['topic']==65].reset_index()
tpp = tp[tp['Topic']==65]
print(f"Keywords: {tpp['Representation'].head()}")
for i in range(0, 6):
    print(f"\n--- Title {i} ---\n{dfp.iloc[i]['title']}")
    print(f"--- Abstract {i} ---\n{dfp.iloc[i]['abstractText']}")

Keywords: 66    ['tdp 43', '43', 'tdp', 'pathology', 'neurons', 'behavioural', 'repeat', 'mice', 'th', 'progressive']
Name: Representation, dtype: object

--- Title 0 ---
Artemin sensitises mouse (<i>Mus musculus</i>) and naked mole-rat (<i>Heterocephalus glaber</i>) sensory neurons <i>in vitro</i>
--- Abstract 0 ---
The naked mole-rat (NMR, Heterocephalus glaber ) is a subterranean rodent that exhibits a range of unusual physiological traits, including diminished inflammatory pain. For example, nerve growth factor (NGF), a key inflammatory mediator, fails to induce sensitization of sensory neurons and thermal hyperalgesia in NMRs. This lack of NGF-induced neuronal sensitization and thermal hyperalgesia results from hypofunctional signaling of the NGF receptor, tropomyosin receptor kinase A (TrkA). Like NGF-TrkA signaling, the neurotrophic factor artemin, a member of the glial cell line-derived neurotrophic factor (GDNF) family, is implicated in mediating inflammatory pain through its receptor, GDNF family receptor α3 (GFRα3), which is expressed by a subset of dorsal root ganglia (DRG) sensory neurons. Here we investigated GFRα3 expression in DRG neurons of mice and NMRs, as well as measuring the impact of artemin on DRG sensory neuron function in both species in vitro . Using immunohistochemistry, we observed a similar abundance of GFRα3 in mouse and NMR DRG sensory neurons, high coexpression with the transient receptor potential vanilloid 1 (TRPV1) ion channel suggesting that these neurons are nociceptive neurons. Using in vitro electrophysiology to record from cultured DRG sensory neurons, we observed that artemin induced depolarization of the resting membrane potential and decreased the rheobase in both species, as well as diminishing the degree of TRPV1 desensitization to multiple capsaicin stimuli. Overall, results indicate that artemin similarly sensitizes sensory neurons in both mice and NMRs, future in vivo studies being required to confirm if the conserved in vitro sensitization also occurs in vivo .

--- Title 1 ---
Aging disrupts the coordination between mRNA and protein expression in mouse and human midbrain
--- Abstract 1 ---
Age-related dopamine (DA) neuron loss is a primary feature of Parkinson’s disease. However, it remains unclear whether similar biological processes occur during healthy aging, albeit to a lesser degree. We therefore determined whether midbrain DA neurons degenerate during aging in mice and humans. In mice, we identified no changes in midbrain neuron numbers throughout aging. Despite this, we found age-related decreases in midbrain mRNA expression of tyrosine hydroxylase ( Th ), the rate limiting enzyme of DA synthesis. Among midbrain glutamatergic cells, we similarly identified age-related declines in vesicular glutamate transporter 2 ( Vglut2 ) mRNA expression. In co-transmitting Th + / Vglut2 + neurons, Th and Vglut2 transcripts decreased with aging. Importantly, striatal Th and Vglut2 protein expression remained unchanged. In translating our findings to humans, we found no midbrain neurodegeneration during aging and identified age-related decreases in TH and VGLUT2 mRNA expression similar to mouse. Unlike mice, we discovered diminished density of striatal TH + dopaminergic terminals in aged human subjects. However, TH and VGLUT2 protein expression were unchanged in the remaining striatal boutons. Finally, in contrast to Th and Vglut2 mRNA, expression of most ribosomal genes in Th + neurons was either maintained or even upregulated during aging. This suggests a homeostatic mechanism where age-related declines in transcriptional efficiency are overcome by ongoing ribosomal translation. Overall, we demonstrate species-conserved transcriptional effects of aging in midbrain dopaminergic and glutamatergic neurons that are not accompanied by marked cell death or lower striatal protein expression. This opens the door to novel therapeutic approaches to maintain neurotransmission and bolster neuronal resilience.

--- Title 2 ---
Homeostatic changes maintain the gain control of spinal motoneurones across the lifetime of C57BL/6J mice
--- Abstract 2 ---
<h4>ABSTRACT</h4> Age-related changes in the excitability of spinal motoneurone have been observed in mouse models of neurodegenerative diseases affecting these neurones. How the excitability of spinal motoneurones change with healthy ageing in mice and how this compares with that seen in neurodegenerative diseases is unknown. Therefore, we performed in vivo intracellular recording from identified spinal motoneurones in C57BL/6 mice at three different ages (100, 300-400 and 600-750 days old). Behavioral tests confirmed a linear reduction in motor function across these ages (using the rotorod test). Significant differences were observed with respect to the features of individual somatic action potential with ageing including a decreased rate of rise and fall in aged mice. Surprisingly, the rate of rise of the action potential at the initial segment was altered in middle aged mice. Immunohistochemical labelling of the axon initial segment of the motoneurones confirmed structural changes occurring at middle age (decreased length and diameter) but returning to the earlier parameters in aged mice. To explore the effects on repetitive firing, this was tested across the age groups which showed surprising little difference as the mice aged, with a similar rheobase and I-f gain across all age groups (with the exception of a lower voltage threshold for action potential initiation in middle-aged mice). However, amplitudes of the after-hyperpolarization and the input resistance were both found to be significantly altered with age. We conclude that there are changes occurring in the intrinsic properties of spinal motoneurones that control their excitability over the lifetime of mice, although these do not develop in a linear fashion from young to old. We propose that these changes are homeostatic in nature and are able to compensate for one another to maintain a constant gain control across the lifetime.

--- Title 3 ---
Amygdala TDP-43 pathology is associated with behavioural dysfunction and ferritin accumulation in amyotrophic lateral sclerosis
--- Abstract 3 ---
<h4>Background</h4> Cognitive and behavioural symptoms associated with amyotrophic lateral sclerosis and frontotemporal spectrum disorders (ALSFTSD) are thought to be driven, at least in part, by the pathological accumulation of TDP-43. <h4>Methods</h4> Here we examine post-mortem tissue from six brain regions associated with cognitive and behavioural symptoms in a cohort of 30 people with sporadic ALS (sALS), a proportion of which underwent standardized neuropsychological behavioural assessment as part of the Edinburgh Cognitive ALS Screen (ECAS). <h4>Results</h4> Overall, the behavioural screen performed as part of the ECAS predicted accumulation of pathological phosphorylated TDP-43 (pTDP-43) with 100% specificity and 86% sensitivity in behaviour-associated brain regions. Notably, of these regions, pathology in the amygdala was the most predictive correlate of behavioural dysfunction in sALS. In the amygdala of sALS patients, we show variation in morphology, cell type predominance, and severity of pTDP-43 pathology. Further, we demonstrate that the presence and severity of intra-neuronal pTDP-43 pathology, but not astroglial pathology, or phosphorylated Tau pathology, is associated with behavioural dysfunction. Cases were also evaluated using a TDP-43 aptamer (TDP-43 APT ), which revealed that pathology was not only associated with behavioural symptoms, but also with ferritin levels, a measure of brain iron. <h4>Conclusions</h4> Intra-neuronal pTDP-43 and cytoplasmic TDP-43 APT pathology in the amygdala is associated with behavioural symptoms in sALS. TDP-43 APT staining intensity is also associated with increased ferritin, regardless of behavioural phenotype, suggesting that ferritin increases may occur upstream of clinical manifestation, in line with early TDP-43 APT pathology, representing a potential region-specific imaging biomarker of early disease in ALS. <h4>Key Messages</h4> <h4>What is already known on this topic</h4> The amygdala is a key brain region in regulating behavior and emotional cognition and has been shown recently, through imaging studies, to be affected in ALS and FTD patients. <h4>What this study adds</h4> Here we examine the underlying pathology driving the association between the amygdala and behavioural symptoms in sporadic ALS demonstrating that region specific TDP-43 pathology and brain iron accumulation could represent potential early biomarkers of dysfunction. <h4>How this study might affect research, practice, or policy</h4> The correlation between early TDP-43 pathology (detected by RNA aptamer) and increased ferritin (brain iron accumulation) occurring upstream of clinical manifestation represents a potential, region-specific (amygdala), early imaging biomarker in ALS. This means that people at risk could be identified early and stratified for clinical trials prior to substantial neuronal cell loss and symptom onset.

--- Title 4 ---
Chronically low NMNAT2 expression causes sub-lethal SARM1 activation and altered response to nicotinamide riboside in axons
--- Abstract 4 ---
Nicotinamide mononucleotide adenylyltransferase 2 (NMNAT2) is an endogenous axon survival factor that maintains axon health by blocking activation of the downstream pro-degenerative protein SARM1 (sterile alpha and TIR motif containing protein 1). While complete absence of NMNAT2 in mice results in extensive axon truncation and perinatal lethality, the removal of SARM1 completely rescues these phenotypes. Reduced levels of NMNAT2 can be compatible with life, however they compromise axon development and survival. Mice born expressing sub-heterozygous levels of NMNAT2 remain overtly normal into old age but develop axonal defects in vivo and in vitro as well as behavioural phenotypes. Therefore, it is important to examine the effects of constitutively low NMNAT2 expression on SARM1 activation and disease susceptibility. Here we demonstrate that chronically low NMNAT2 levels reduce prenatal viability in mice in a SARM1-dependent manner and lead to sub-lethal SARM1 activation in morphologically intact axons of superior cervical ganglion (SCG) primary cultures. This is characterised by a depletion in NAD(P) and compromised neurite outgrowth. We also show that chronically low NMNAT2 expression reverses the NAD-enhancing effect of nicotinamide riboside (NR) in axons in a SARM1-dependent manner. These data indicate that low NMNAT2 levels can trigger sub-lethal SARM1 activation which is detectable at the molecular level and could predispose to human axonal disorders.

--- Title 5 ---
TDP-43-M323K causes abnormal brain development and progressive cognitive and motor deficits associated with mislocalised and increased levels of TDP-43
--- Abstract 5 ---
TDP-43 pathology is found in several neurodegenerative disorders, collectively referred to as “TDP-43 proteinopathies”. Aggregates of TDP-43 are present in the brains and spinal cords of >97% of amyotrophic lateral sclerosis (ALS), and in brains of ∼50% of frontotemporal dementia (FTD) patients. While mutations in the TDP-43 gene ( TARDBP ) are usually associated with ALS, many clinical reports have linked these mutations to cognitive impairments and/or FTD, but also to other neurodegenerative disorders including Parkinsonism (PD) or progressive supranuclear palsy (PSP). TDP-43 is a ubiquitously expressed, highly conserved RNA-binding protein that is involved in many cellular processes, mainly RNA metabolism. To investigate systemic pathological mechanisms in TDP-43 proteinopathies, aiming to capture the pleiotropic effects of TDP-43 mutations, we have further characterised a mouse model carrying a point mutation (M323K) within the endogenous Tardbp gene. Homozygous mutant mice developed cognitive and behavioural deficits as early as 3 months of age. This was coupled with significant brain structural abnormalities, mainly in the cortex, hippocampus, and white matter fibres, together with progressive cortical interneuron degeneration and neuroinflammation. At the motor level, progressive phenotypes appeared around 6 months of age. Thus, cognitive phenotypes appeared to be of a developmental origin with a mild associated progressive neurodegeneration, while the motor and neuromuscular phenotypes seemed neurodegenerative, underlined by a progressive loss of upper and lower motor neurons as well as distal denervation. This is accompanied by progressive elevated TDP-43 protein and mRNA levels in cortex and spinal cord of homozygous mutant mice from 3 months of age, together with increased cytoplasmic TDP-43 mislocalisation in cortex, hippocampus, hypothalamus, and spinal cord at 12 months of age. In conclusion, we find that Tardbp M323K homozygous mutant mice model many aspects of human TDP-43 proteinopathies, evidencing a dual role for TDP-43 in brain morphogenesis as well as in the maintenance of the motor system, making them an ideal in vivo model system to study the complex biology of TDP-43.

In [103]:
dfp.shape

(12, 13)

- The topic 6 is about mostly the longevity of the animals. Should be deleted or not?
- The topic 9 is about the pests and mosquitos
- The topic 10 is about seed longevity. Should be deleted or not?
- Topic 11: anti - aging and longevity mechanism in bees
- Topic 16: about vaccines. Should be deleted or not?
- Topic 17: about mating pests
- Topic 19: about globalization and population of the species
- Topic 20: About antibiotics (not related to longevity or health)
- Topic 21: ? not related
- Topic 22: delete
- Topic 25: About the longevity in the trees
- Topic 26: Delete:
- Topic 31: focused exclusively on the SARS-CoV-2 virus and the pandemic response
- Topic 52: only talks about o SARS-CoV-2 (COVID-19) and other viruses, without talking linking it with longevity
- Topic 53: focused on the practical public health and clinical aspects of the pandemic, not the underlying biological links to the aging process.
- Topic 54: focused on vaccine development and the immune response to infectious diseases, specifically malaria and, in one case, Zika virus.
- Topic 59: bats as a model organism for exceptional longevity
- Topic 62: focused on botany, agriculture, and plant pathology.
- Topic 63: focused on entomology and microbiology

In [114]:
#List of unrelated topics
u_list = [6, 9, 10, 11, 16, 17, 19, 20, 21, 22, 25, 26, 31, 52, 53, 54, 59, 62, 63]

In [115]:
#False if not relevant
for i in u_list:
    df.loc[df['topic']==i, 'is_relevant']=False
    tp.loc[tp['Topic']==i, 'is_relevant']=False

In [117]:
tp.to_csv("../data/topics_lon/final_topics.csv", index=False)
df.to_csv("../data/topics_lon/final_data.csv", index=False)

In [118]:
df.groupby('is_relevant').size()

is_relevant
False     450
True     1838
dtype: int64

Out of of 2288 articles, 1838 are analyzed as related