# Library Inclusion and Utilities

<!-- structured-notebook -->
## Notebook Summary
Purpose: document an earlier ProQuest cleaning workflow, including full-text cleanup, title cleanup, relevance scoring, and a long manual audit trail of topic keep/drop decisions before exporting a cleaned dataset.

Main steps:
- Load an older processed ProQuest snapshot and clean the article text fields.
- Compute relevance ratios that help rank noisy topics for manual review.
- Walk through topic-specific decisions in audit-log form, then export the cleaned dataframe.

In [ ]:
# structured-notebook-bootstrap
from pathlib import Path
import sys


def find_repo_root(start: Path) -> Path:
    start = start.resolve()
    for candidate in [start, *start.parents]:
        if (candidate / ".git").exists():
            return candidate
    return start


_repo_root = find_repo_root(Path.cwd())
if str(_repo_root) not in sys.path:
    sys.path.append(str(_repo_root))

from src.project_paths import (
    ARXIV_RAW_DIR,
    CHROMA_DIR,
    EXTERNAL_NEWS_DIR,
    GUARDIAN_DATA_DIR,
    LLM_CLASSIFICATION_DIR,
    NEWS_HTML_DIR,
    NEWS_OUTPUT_DIR,
    PREPRINT_RAW_DIR,
    PROQUEST_PROCESSED_DIR,
    PROQUEST_UNPROCESSED_DIR,
    PUBMED_PROCESSED_DIR,
    PUBMED_RAW_DIR,
    PUBLICATIONS_TABLE_DIR,
    REDDIT_DATA_DIR,
    ROOT,
    RQ1_FIGURES_DIR,
    RQ4_PLOTS_DIR,
    TOPIC_MATCHING_DIR,
    YOUTUBE_DATA_DIR,
)

In [1]:
import pandas as pd, re
import itables.options as opt
from itables import show
from src.news.nlp import *
from src.news.data_processor import *

/home/iskender/anaconda3/envs/bertopic-env/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

# Load Data

## Load Pre-built Data

In [2]:
df = pd.read_csv(PROQUEST_PROCESSED_DIR / 'df_v3.csv')

# Cleaning

## Clean Full Text

***
Delete articles with non-available full text
***

In [3]:
col = 'Full text'
mask = (df[col].isna()) | (df[col].str.strip() == '') | (df[col].str.startswith('Not available'))
df[mask]
df = df[~mask]

***
Average amount of words per article
***

In [4]:
total_l = 0
for title in df['Full text']:
    total_l += len(title)
print(total_l/len(df))

4380.29849528644

***
Cleaning "\n" and "\"
***

In [5]:
df['Full text'] = df['Full text'].str.replace("\n", " ")

***
Tokenizing sentences
***

In [6]:
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')
from nltk.tokenize import sent_tokenize

[nltk_data] Downloading package punkt to /home/iskender/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     /home/iskender/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

In [7]:
df['last'] = [' '.join(sent_tokenize(text)[-4:]) for text in df['Full text']]

***
Cleaning the last sentence part
***

In [8]:
df_dedup = df.copy()

In [9]:
df_dedup['last'].tolist()

['Info Box:How to sign up for ICL spring classes Registration begins Jan. 3 and classes begin Jan. 10. When: Monday through Thursday 9:30 a.m. to 2:30 p.m. Where: The ICL office located at 658 E. 200 South. Cost: $40 for the entire year. Can also register online at www.dixie.edu/com/icl.',
 'A wheel chair, walkers, hospital bed, and other items are available to borrow. Memorial donations received during December were: From Toby Young, in memory of Marie Wright; from Barbara Greenough, in memory of Alice and Harold Shattuck and Fran Streeter; from Paul and Shirley Schofield, in memory of Pat Jennison; from Catherine Kurkul, in memory of Christopher Kurkul; from Dr. Ralph, in memory of Pat Jennison; from Barbara Angers, in memory of Harold Angers; from Peggy and Dirk Jager, in memory of Patty Vigevano; from Rebecca and William Noyes, in memory of Pat Jennison; from Verna and Donald Newcomb, in memory of Leslie and Avis Dodge; from Irene and Jeffrey Michaud, in memory of Gert French; from Bill Arnold, in memory of Camilla Arnold; from Evelyn Rhoades, in memory of her husband Hollis; from Pete and Judy Harrison, in memory of Victor and Eunice Harrison; from Ruth Grandy, in memory of Jim Grandy; from Lois Woodard, in memory of Clarence Woodard and Marilyn Crawford; from John and Suzanne Stoodley, in memory of Donat A. Perrault; from Marion Wilder, in memory of Bill Wilder; from Jean and Martin Collins, in memory of Marie Wright; from Susan and Rich Talbot, in memory of Nancy Aldrich; from Phil and Jane Savoy, in memory of Fran Streeter; from Allison and David Deen, in memory of Marie Wright; from Kirk Hemelberg, in memory of Suzanne Jovin and Raymond Lemme; from Dena and Howard Weiss-Tisman, in memory of Marie Wright; from Eshagh and Rose Shaoul, in memory of Patricia Jennison; anonymous in memory of Ellen Crowley; from Abigail Littlefield/Martha Wilmot, in memory of Agatha Littlefield; from John Benzaia, in memory of Edna Perry; from Paul and Lillian Chaffee, in memory of Harold Chaffee; from Don and Donna Dawson, in memory of Marguerite Dawson; from Lester Cook, in memory of Bernice Cook, from Douglas Barton and David Sault, in memory of Fred Barton; from Richard Michelman, in memory of Charles Edson; from Gary and Kim Wood, in memory of Timothy Corcoran; from Ila Mitchell, in memory of Rose Fowler; from Fran Walsh, in memory of Jeff Walsh; from Janice Wojick and Pat Mulligan, in memory of Pat Jennison; from George and Georgina Cheney, in memory of Katherine and Robie Palmer; from Carlton H. Palmer II, in memory of Margret Palmer. Memorial donations received during December were: From Toby Young, in memory of Marie Wright; from Barbara Greenough, in memory of Alice and Harold Shattuck and Fran Streeter; from Paul and Shirley Schofield, in memory of Pat Jennison; from Catherine Kurkul, in memory of Christopher Kurkul; from Dr. Ralph, in memory of Pat Jennison; from Barbara Angers, in memory of Harold Angers; from Peggy and Dirk Jager, in memory of Patty Vigevano; from Rebecca and William Noyes, in memory of Pat Jennison; from Verna and Donald Newcomb, in memory of Leslie and Avis Dodge; from Irene and Jeffrey Michaud, in memory of Gert French; from Bill Arnold, in memory of Camilla Arnold; from Evelyn Rhoades, in memory of her husband Hollis; from Pete and Judy Harrison, in memory of Victor and Eunice Harrison; from Ruth Grandy, in memory of Jim Grandy; from Lois Woodard, in memory of Clarence Woodard and Marilyn Crawford; from John and Suzanne Stoodley, in memory of Donat A. Perrault; from Marion Wilder, in memory of Bill Wilder; from Jean and Martin Collins, in memory of Marie Wright; from Susan and Rich Talbot, in memory of Nancy Aldrich; from Phil and Jane Savoy, in memory of Fran Streeter; from Allison and David Deen, in memory of Marie Wright; from Kirk Hemelberg, in memory of Suzanne Jovin and Raymond Lemme; from Dena and Howard Weiss-Tisman, in memory of Marie Wright; from Eshagh and Rose Shaoul, in memory of Patricia Jennison; anonymous in memory of Ellen Crowley; from Abigail Littlefield/Martha Wilmot, in memory of Agatha Littlefield; from John Benzaia, in memory of Edna Perry; from Paul and Lillian Chaffee, in memory of Harold Chaffee; from Don and Donna Dawson, in memory of Marguerite Dawson; from Lester Cook, in memory of Bernice Cook, from Douglas Barton and David Sault, in memory of Fred Barton; from Richard Michelman, in memory of Charles Edson; from Gary and Kim Wood, in memory of Timothy Corcoran; from Ila Mitchell, in memory of Rose Fowler; from Fran Walsh, in memory of Jeff Walsh; from Janice Wojick and Pat Mulligan, in memory of Pat Jennison; from George and Georgina Cheney, in memory of Katherine and Robie Palmer; from Carlton H. Palmer II, in memory of Margret Palmer. The following donations were made in honor of: From Phyllis and Hank Anderson, in honor of Frank and Karen Walter; anonymous, in honor of Artie Aiken; from Norah and Dennis Payne, in honor of volunteer drivers; from Mary Hoyt, in honor of Gerald and Ella LeFevre; from Betty and Hugh Haggerty, in honor of Frank and Karen Walter; from Kathryn Bowry, in honor of her parents, Don and Jane Bowry; from Real and Carol Bazin, in honor of Trudy Byington.',
 '"All it takes is music to get me tapping." In order to participate, Althoff said just show up at Battell, 904 N. Main St., Mishawaka. Donations are accepted for the class, and dance partners are not necessary. Staff writer Katlyn Smith: ksmith@sbtinfo.com  People: Nelson, Thelma; Helen Althoff, Nelson.',
 '"This policy is about ensuring women have information and support to take control of their immediate and longer term health." The policy notes health issues such as obesity, anxiety and depression had become increasing issues for women over the past 20 years. Health priority areas identified in the policy include chronic diseases, mental health, sexual and reproductive health and healthy ageing. Credit: ALISON REHN',
 'Ms Cox said many people did not understand that dentistry was not covered by Medicare or believed it was safer to go to a private obstetrician than to a public midwife service. "There\'s a lot of mythology around the health system and the medicalisation of our health rather than the wellbeing model we really aspire to," Ms Cox said. The Public Health Association of Australia welcomed the emphasis on the prevention of chronic disease, and on sexual and reproductive health. Credit: MARK METHERELL HEALTH CORRESPONDENT',
 "The Public Health Association of Australia welcomed the policy's emphasis on the prevention of chronic disease, and on sexual and reproductive health. The association's president, Professor Helen Keleher, called on the government to integrate the policy direction with the government's proposals for the Medicare Locals community health organisations. TEN LEADING CAUSES OF BURDEN OF DISEASE MEN Ischaemic heart disease Type 2 diabetes Anxiety and depression Lung cancer Stroke Chronic obstructive pulmonary disease Adult-onset hearing loss Suicide and self-inflicted injury Prostate cancer Colorectal cancer WOMEN Anxiety and depression Ischaemic heart disease Stroke Type 2 diabetes Dementia Breast cancer Chronic obstructive pulmonary disease Lung cancer Asthma Colorectal cancer Australia in 2003 SOURCE: AUSTRALIAN GOVERNMENT - NATIONAL WOMENS HEALTH POLICY 2010 Credit: Mark Metherell HEALTH CORRESPONDENT Illustration Caption: PHOTO: Darlene Cox ... call for better information. Photo: Gary Schafer",
 'The conference was attended by 150 dermatologists, who heard six leading experts from France, Canada, the US, Greece and Belgium in addition to Israelis. (c) Copyright Jerusalem Post. All rights reserved. Company / organization: Name: Tel Aviv University; NAICS: 611310.',
 "Expectations: My life turned out better than I imagined, thanks to a good marriage. Regrets: Not getting a higher education and not having the courage to travel and learn more about the world. Aging boomers: We are educated, more involved, active, up to date on technology, healthier, happier and don't consider aging a negative. Credit: Rebecca Nappi rebeccan@spokesman.com, (509) 459-5496",
 '"For a professor like me, there\'s nothing like this." "Cool in School" is a weekly look at some of the interesting people, events and programs in schools and universities throughout South Florida. For more on what\'s going on in South Florida schools, go to www.sunsentinel.com/schools and see our blogs at www.sunsentinel.com/schoolblog. Credit: By Scott Travis Staff writer Illustration Photo(s); Caption: Ted Kaplan, of Highland Beach, reads a booklet on FAU\'s Lifelong Learning services as he waits for a lecture to begin, one in a series last week celebrating the program\'s 30th year.Carline Jean/Sun Sentinel',
 "General healthy aging: Overall healthy aging may help keep your brain as well as your body fit. These strategies may even offer some protection against developing Alzheimer's or related disorders. Try to keep your weight within recommended guidelines, avoid tobacco and excess alcohol, stay socially connected, and exercise both your body and mind. (To be continued)  People: Vincent, Bruce.",
 'In addition, CRIS Rural Transit is canceling all rural transportation services in Vermilion and Champaign counties for today. There will be limited service within the city of Danville. Normal service should be reinstated on Wednesday. Credit: By The News-Gazette',
 'CHESTER - Commonwealth Power Sports presents every type of Bike Night from 6-8 p.m. each Thursday at Steel Horse Bar & Grill, 1920 W. Hundred Road. HOPEWELL - St. Joseph Catholic School holds bingo every Thursday at AHEPA Hall, 810 w. Poythress Street. Doors open 5 p.m. Games start at 7 p.m. Food is available for nominal fee. For more information, call St. Joseph School at 732-3931. Credit: Staff Report  Company / organization: Name: American Legion; NAICS: 813410.',
 'During the presentation, she will provide tips on how to beat the winter blues, as well as identify the signs and symptoms of depression and seasonal affective disorder. The informational event is free to community members, and all ages are welcome. Preregistration is requested for planning purposes. To register or for information, call the Sylvia Ross Home at 992-2674.',
 "The money comes from the Richard M. Schulze Family Foundation, set up by the Best Buy founder. Wilder officials say the money will be used over five years to: * Model best practices in aging services * Develop new models of support for caregivers * Design research and outcome measures * Provide community leadership through convening and collaboration The grant comes just as Wilder prepares to open its newly renovated Community Center for Aging, which will consolidate most of the Wilder Foundation's services for older adults and caregivers serve as a hub for resources related to healthy aging, memory loss and caregiver support. The Schulze grant won't go toward the capital costs of the Center, to open in January, but the grant will spur program growth at this site, Wilder says. Credit: Joe Kimball",
 "Nova Southeastern University offers classes on its Davie campus; call 954-262-8471 or go to undergrad.nova.edu/lli. The University of Miami has classes in Coral Gables and Miami Shores; call 305-284-6554 or go to miami.edu/olli. Florida International University's program is based at its Biscayne Bay campus in North Miami; call 305-919-5910 or go to olli.fiu.edu. Credit: By Scott Travis Staff Writer Illustration Photo(s) Graphic(s); Caption: A 500-seat auditorium at FAU's Boca Raton campus was built to include headphones for the hearing-impaired and other amenities that seniors might need.Carline Jean/Sun SentinelTed Kaplan, of Highland Beach, reads as he waits for a lecture on Florida Atlantic University's Lifelong Learning program, in which older adults learn about art, music, religion or politics.Carline Jean/Sun Sentinel",
 'Send an e-mail to health@latimes.com. Read more at latimes.com/skeptic. health@latimes.com Illustration Caption: PHOTO: UNCAPPED: Sold since 2007, TA-65 is available through some doctors. ; PHOTOGRAPHER:TA Sciences',
 'Legacies Arts grew out of workshops held in 2007 by experts from Washington, D.C., in coordination with the local premiere of the public TV documentary "Do Not Go Gently," filmed in part in Green Bay. Screening of the documentary will be part of activities surrounding the Neville exhibit. If you go * What: "Legacies Arts Project: Empowering the Mind Through Creative Expression" * Where: Northern Waters Gallery, 310 Pine St., Green Bay * Hours: 1-4 p.m. Mondays, Fridays, Saturdays * Admission: Donations accepted, including for note cards and framed watercolor paintings ($30 minimum) * Information: (920) 593-3532 Ahead What: "Hear My Voice" exhibit of watercolors by 17 people with memory-impairment illnesses from early stage to end of life When: March-April Where: Neville Public Museum of Brown County, 210 Museum Place, Green Bay Associated events: March 19, caregiver workshops; March 23, workshop, "Healthy Aging vs. Early Memory Loss;" April 6 and 9, screening of film "I Remember Better When I Paint;" April 16, two screenings of documentary "Do Not Go Gently" and one of documentary "Runaway Train," written and acted by people with memory impairment.',
 "That's why it is essential that people with the disorder have access to a system of treatment - otherwise the illness can affect their education, ability to work and thus their economic circumstances and health. The study has been published in the December 2010 edition of Acta Neurological Scandinavia. Published by HT Syndication with permission from Asian News International. For any query with respect to this article or any other content requirement, please contact Editor at htsyndication@hindustantimes.com",
 '"It is crucial that we plan early enough in life while we have more options available, rather than waiting until we reach our mid 60s when the only stark choices might be to keep working into our 70s or accept a lower than expected standard of living in retirement. "As part of this planning, it is important to consider whether we are still on target to be able to retire when we want or whether we need to take further action and indeed whether our aspirations for our life in retirement have changed. "Employers can play a pivotal role in encouraging and supporting their employees to ensure their savings are on track to meet their retirement goals, especially as they reach their mid 50s and the prospect of retirement begins to take more significance in their thoughts", said Matthews. Illustration Caption: YOUNG AT HEART: By 2020, the face of retirement will look completely different from the one that we have become familiar with in recent years.',
 '(Dr. Gott is a retired physician and the author of the book "Dr. Gott\'s No Flour, No Sugar Diet." Quill Driver Books, www.quilldriverbooks.com; 800-605-7176. Readers can write to Dr. Gott in care of United Media, 200 Madison Ave., fourth floor, New York, N.Y. 10016.)',
 'PETER GOTT, M.D., is a retired general internist. Send questions to Dr. Gott, c/o United Media, 200 Madison Ave., 4th Floor, New York, NY 10016. His website is www.askdrgottmd.com. Credit: Staff Report',
 "Lenalidomide is a more modern drug and is considered safer than thalidomide. But its close structural similarity means that women of child-bearing age must use contraception while taking it. Dr Goetzl says that while the very low doses needed should not produce any side-effects, he would never advise giving the drug to young women. f.macrae@dailymail.co.uk 'A shorter period of frailty' Credit: By Fiona MacRae Science Reporter Illustration Caption: Sci-fi: Cronyn and Gilford in Cocoon  People: Goetzl, Edward.",
 '"Get Fit to Go" is available through her website www.fittogohealthandfitness.com. Jake Remaly: 973-428-6621; jremaly1@gannett.com Fitness tips for the holidays from "Get Fit to Go" * Increase the duration of your cardio workouts * Drink lots of water to stay hydrated and improve your metabolism * Combine cardio with resistance work, i.e., do a set of jumping jacks, stop, and then do a set of lower or upper body weight exercises. * Use good manners. When someone offers you an extra piece of pie, say, "No, thank you!"',
 'Install grab bars near toilets, bathtubs and showers. Buy an emergency response device that alerts family, neighbors and friends should you fall and become immobile. Sources: Mayo Clinic, Salt Lake County Aging Services Credit: By Patty Henetz The Salt Lake Tribune Illustration Caption: Evelyn Vernon. courtesy of Bonnie Lloyd.',
 'The five-year Harvard Aging Brain Study will include yearly brain scans and memory tests. Participants from all walks of life are sought. Contact study coordinator Lauren Wadsworth, 617-643-0413, or go to www.nmr.mgh.harvard.edu/harvardagingbrain. 13gside1.ART',
 '"People need to lead active and healthy lives, but what is going to happen to them in 20 years I wouldn\'t worry about. It\'s what they are doing right now that can help right now." Kay Lazar can be reached at klazar@globe.com. 13gcover.ART',
 'THE number of pensioners in Ireland will treble over the next 30 years, with the elderly living in rural areas to suffer most, a conference in Galway has been told. According to the last census in 2006, there were 468,000 people aged 65 or older -- about 11% of the population. Data compiled by the Healthy Ageing in Rural Communities (HARC) research network showed that by 2041, the number of people in this country aged 65 or older will be 1.4 million. The conference heard those in rural areas had lower incomes than their urban peers but had bigger costs like transport.',
 'The society is seeking volunteers. For more information, call 801-467-8712. The society also holds health classes in Tongan for elders 55 years and older Thursdays from 1-2 p.m. at the Sunday Anderson Westside Senior Center, 868 W. 900 South, Salt Lake City. Credit: By Patty Henetz The Salt Lake Tribune',
 'The character in the title is a sharp 15-year-old girl who finds herself apprenticed to none other than Sherlock Holmes. For more information, call 626-812-5268. Columnist Anissa V. Rivera can be reached at 626-301-1461 or by e-mail at anivriv@yahoo.com or write to her care of the Highlanders, 1210 N. Azusa Canyon Road, West Covina, CA 91790. People: Pusztai, Julie.',
 'People aged 85 (80-90 for Maori) are still being sought for the study, phone 0800 545 227. Park opens to public The 1650ha TECT All Terrain Park is opening to the public this Saturday. Divided into four large corners, the park enables active sports to be separated from the passive and non-motorised activities. The facility, on State Highway 36, midway between Tauranga and Rotorua, will cater for motorsports, off-road four-wheel driving, motorbike and trail bike riding, mountain biking, target shooting, horse riding, walking, running, abseiling and dog sledding.',
 'COTA ACT: Volunteers required. Meet new people, learn new skills and share your knowledge. COTA is recruiting volunteers aged 50 years plus to talk to seniors about healthy ageing issues. Ph:62823777. Credit: The Canberra Times',
 '_ Healthy Ageing Forum starts in Canberra. I do need to look at what might be potential paths that lead to a family. Kylie Minogue tells a British magazine she has thought about her options for having a child, including egg donation. Credit: MATT BUCHANAN and LEESHA McKENNY Illustration Caption: PHOTO: Photo: Splashnews',

## Clean Title

In [10]:
df['Title']

0                           ICL registration begins Jan. 3
1                   Westminster Cares announces activities
2                                        dancing longevity
3                         Healthier future for Gen Y girls
4                           Women's health 'short changed'
                               ...
11097    United States: Aging may change some brain cel...
11098                 What Is The Ideal Breakfast Formula?
11099    Stay Calm, Sleep, and 5 More Tips for a Long a...
11100                         SIMPLE STEPS for a good LIFE
11101                WHAT you NEED TO DO FOR A LONGER LIFE
Name: Title, Length: 11032, dtype: object

In [11]:
[title for title in df['Title'] if len(title) < 10]

['The Diary',
 '[Diary ]',
 'Events',
 'Cafe chat',
 'Calendar',
 'Town Talk',
 'Purple',
 'Health',
 'Notices',
 'tv talk',
 'Activity',
 'Sponsor',
 "What's On",
 'BRIEFCASE',
 'Homehunt',
 'Calendar',
 'SENIORS',
 'Briefs',
 'DIGEST',
 'try these',
 'Briefly',
 'Club News',
 'IN BRIEF',
 'LEARN',
 'DURBAN',
 'TIPS',
 "What's On",
 'IN BRIEF',
 'Near you',
 'SENIORS',
 'Reunions',
 "What's On",
 'Try these',
 'DATEBOOK',
 "What's On",
 '3',
 'LOOK OUT',
 'YOUR SAY',
 'Monday/28',
 'Briefly',
 'WERNER',
 'Briefs',
 'Q & A',
 'calendar',
 'COLUMNIST',
 'Club News',
 'ACRES',
 'LETTERS',
 'IN BRIEF',
 'Signpost',
 'Briefly',
 'Players',
 'Events',
 'FYI',
 'IN BRIEF',
 'calendar',
 'PLAYERS',
 "WHAT'S ON",
 'brief',
 'LETTERS',
 'YOUR VIEW',
 'Clipboard',
 'PLAYERS',
 'Diary',
 'Calendar',
 'GO!',
 'BIRTHDAYS',
 'FYI',
 'Community',
 'What’s on',
 'Diet 16:8',
 'BIRTHDAYS',
 'FYI',
 'Calendar',
 'Clipboard',
 'hjlfuil',
 'Community',
 'PLAYERS',
 'BRIEFS',
 'PLAYERS',
 'Aging',
 'FYI',
 'BIRTHDAYS',
 "What's On",
 'Community',
 'BIRTHDAYS',
 'FEATURE',
 'AFCI News',
 'CALENDAR',
 'AFCI news',
 'Clipboard',
 'BIRTHDAYS',
 'HELPDESK',
 'SENIORS',
 'Will King',
 'BIRTHDAYS',
 'SENIORS',
 'Listings',
 'Ourtowns',
 'NQ faces',
 'COMMENT',
 'GRAY WAVE']

total_l = 0
for title in df['Title']:
    total_l += len(title)
print(total_l/len(df))

***
The average length of a title is 64 words.
***

## Relevance Ratio

In [12]:
def find_relevance_ratio(group_df:pd.DataFrame, by: list[str] = ['Title', 'Abstract', 'Full text']):
    keywords = [
        "healthy aging", "healthy ageing",
        "anti-aging", "anti-ageing", "anti aging", "anti ageing",
        "biohacking", "living longer", "health rejuvenation", "nootropics",
        "well aging", "well ageing", "aging well", "ageing well",
        "slow aging", "slow ageing"
    ]
    pattern = "|".join(keywords)
    
    relevant = 0
    for index, record in group_df.iterrows():
        full_str = ".".join([record[col] for col in by]).lower()
        if re.search(pattern, full_str):
            relevant += 1
    group_df['rel_ratio'] = relevant/len(group_df)

    return group_df

In [13]:
df = (
    df.groupby("topic", group_keys=False)
      .apply(find_relevance_ratio)
      .reset_index(drop=True)
)

/tmp/ipykernel_14457/1970550472.py:3: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(find_relevance_ratio)

In [14]:
df['rel_bins'] = pd.cut(df['rel_ratio'], [0.2,0.4,0.6,0.8,1], ['Low', 'Average', 'Moderate', 'High'])

In [15]:
show(df.groupby('topic')['rel_ratio'].mean())

<!-- structured-notebook -->
## Manual Topic Review Log
The long sequence below is best read as an audit trail. Topics are grouped by relevance-ratio bands, inspected manually, and then either removed entirely or kept with explicit exception IDs.

## Topic Cleaning

In [16]:
def remove_topic(df:pd.DataFrame, topic_num:int, exceptions:list[int]):
    mask = (df['topic'] == topic_num) & (~df.index.isin(exceptions))
    print(f"The orig length:{len(df)} -> cropped: {len(df[~mask])}")
    return df[~mask]

### Topic rel_ratio 0.2 - 0.4

In [17]:
df[(df["rel_ratio"] > 0.2) & (df["rel_ratio"] <= 0.4)]['topic'].unique()

array([114., 196.,  94.])

#### Topic 114

***
Topic keywords
***

In [18]:
df[df['topic']==114]['topic_keywords'].unique()

array(["['season', 'players', 'hes', 'game', 'strengths', 'coach', 'league', 'games', 'football', 'win', 'louis', 'player', 'guy', 'played', 'teams', 'ryan', 'field', 'knee', 'probably', 'surgery', 'era', 'manager', 'line', 'summer', 'knows', 'man', 'heat', 'runs', 'super', 'return']"],
      dtype=object)

In [19]:
df[df['topic']==114]

,Title,Abstract,Full text,Subject,Publication title,Publication year,Publication date,Section,Publisher,Place of publication,...,Document type,ProQuest document ID,Document URL,Last updated,topic,topic_prob,topic_keywords,last,rel_ratio,rel_bins
125,"Hossa is aging well: Veteran winger healthy,...","Along with an equally hot Patrick Sharp, who c...",Jonathan Toews has seen Blackhawks linemate Ma...,Athletes; Professional hockey -- Chicago Black...,"Chicago Tribune; Chicago, Ill.",2010,"Oct 20, 2010",Chicago Sports,"Tribune Publishing Company, LLC","Chicago, Ill.",...,Feature,759143597,https://www.proquest.com/globalnewsfed/newspap...,2017-11-17,114.0,0.063781,"['season', 'players', 'hes', 'game', 'strength...",After he was moved out of the Hawks' GM slot i...,0.344828,"(0.2, 0.4]"
421,Healthy Garnett lifts Celtics: Vet delivers ...,Boston Celtics coach Doc Rivers has joked in t...,BOSTON -- Boston Celtics coach Doc Rivers has ...,Athletes; Tournaments & championships; Profess...,"USA TODAY; McLean, Va.",2010,"May 14, 2010\n\nDateline: BOSTON",SPORTS,"USA Today, a division of Gannett Satellite Inf...","McLean, Va.",...,News,276456059,https://www.proquest.com/globalnewsfed/newspap...,2022-10-12,114.0,0.214336,"['season', 'players', 'hes', 'game', 'strength...","After the game, James stuck around on the cour...",0.344828,"(0.2, 0.4]"
490,Cox's last stand may be fruitful: Braves focus...,"""There's going to come a point in time where t...",Braves players wore T-shirts beneath their jer...,Coaches & managers; Professional baseball -- A...,"The Atlanta Journal - Constitution; Atlanta, Ga.",2010,"Apr 5, 2010",Sports,"Atlanta Journal Constitution, LLC","Atlanta, Ga.",...,Feature,337696423,https://www.proquest.com/globalnewsfed/newspap...,2017-11-07,114.0,1.000000,"['season', 'players', 'hes', 'game', 'strength...","Jason Heyward, RF 8. Nate McLouth, CF 9. Derek...",0.344828,"(0.2, 0.4]"
586,"NFL:: Free agency, draft offer hope for '10;...","Strengths: QB Matt Ryan, WR Roddy White, agele...","MIAMI, Fla. - The Super Bowl's over, Drew Bree...",NaN,"The Charleston Gazette; Charleston, W.V.\n\nFi...",2010,"Feb 10, 2010",Sports,Charleston Newspapers,"Charleston, W.V.",...,News,331732159,https://www.proquest.com/globalnewsfed/newspap...,2017-11-05,114.0,1.000000,"['season', 'players', 'hes', 'game', 'strength...",Strengths: CB Nnamdi Asomugha; kicking game wi...,0.344828,"(0.2, 0.4]"
629,Todd makes FSC proud: Alum helps coach Hawks,"""It's easy for all of us to second guess and b...",Ray Allen can still hear former Washington Bul...,Coaches & managers; Surgery; Professional bask...,"Telegram & Gazette; Worcester, Mass.\n\nFirst ...",2010,"Jan 17, 2010\n\ncolumn: NBA",SPORTS,"GateHouse Media, Inc.","Worcester, Mass.",...,News,269045258,https://www.proquest.com/globalnewsfed/newspap...,2025-08-08,114.0,0.058438,"['season', 'players', 'hes', 'game', 'strength...",KG has deep pockets Davis joked he would colle...,0.344828,"(0.2, 0.4]"
724,"NO LUCK, SO MAYBE WAITIN' FOR PEYTON?","Oh, he's hurt. He's 35. He's expensive. His ov...",Here's my only problem with being out front on...,NaN,"South Florida Sun - Sentinel; Fort Lauderdale,...",2011,"Nov 16, 2011\n\ncolumn: DAVE HYDE Commentary",Sports,"Tribune Publishing Company, LLC","Fort Lauderdale, Fla.",...,COLUMN,904229285,https://www.proquest.com/globalnewsfed/newspap...,2017-11-18,114.0,1.000000,"['season', 'players', 'hes', 'game', 'strength...",But some good can still come out a Dolphins se...,0.344828,"(0.2, 0.4]"
808,Red Wings talent outweighs issues,An aging group of core players cant stay healt...,An aging group of core players cant stay healt...,Athletes\n\nCompany / organization: Name: Detr...,"Washington Examiner; Washington, D.C.\n\nFirst...",2011,"Oct 14, 2011",Sports,"Clarity Media Group, Inc.","Washington, D.C.",...,News,898326906,https://www.proquest.com/globalnewsfed/newspap...,2022-11-11,114.0,1.000000,"['season', 'players', 'hes', 'game', 'strength...",With stars like Henrik Zetterberg and the bril...,0.344828,"(0.2, 0.4]"
904,Jaguars scratch out victory,None available.,"no David Garrard, no problem for the Jacksonvi...","Professional football\n\nPeople: Garrard, Davi...",The Toronto Sun; Toronto\n\nFirst page: S.5,2011,"Sep 12, 2011",Sports,Postmedia Network Inc.,Toronto,...,News,2227834520,https://www.proquest.com/globalnewsfed/newspap...,2019-05-21,114.0,0.096953,"['season', 'players', 'hes', 'game', 'strength...","With a 13-0 lead, Jacksonville coach Jack Del ...",0.344828,"(0.2, 0.4]"
1096,Heat failure leaves James just a prince,This isn't to tattoo James with the latter lab...,"When it comes to LeBron James, it may be time ...",NaN,"Chattanooga Times Free Press; Chattanooga, Ten...",2011,"Jun 14, 2011",Sports,Chattanooga Times Free Press,"Chattanooga, Tenn.",...,News,871638385,https://www.proquest.com/globalnewsfed/newspap...,2011-07-20,114.0,1.000000,"['season', 'players', 'hes', 'game', 'strength...","Said Prince Jimmy: ""A team is not built on thr...",0.344828,"(0.2, 0.4]"
1666,YO-YO JOHAN Up & down lefty insists he's healthy,WASHINGTON - The important thing for [Johan Sa...,WASHINGTON - The important thing for Johan San...,NaN,"New York Daily News; New York, N.Y.\n\nFirst p...",2012,"Aug 18, 2012",SPORTS,"Tribune Publishing Company, LLC","New York, N.Y.",...,News,1034101542,https://www.proquest.com/globalnewsfed/newspap...,2017-11-19,114.0,0.328420,"['season', 'players', 'hes', 'game', 'strength...","In order to ensure that continues, the Mets de...",0.344828,"(0.2, 0.4]"
1737,YANKEES (52-33) AT THE ALL-STAR BREAK,Not force-feeding David Robertson into the clo...,"If anything, these Yankees have been superbly ...",NaN,The Record; Hackensack\n\nFirst page: S.6,2012,"Jul 10, 2012",SPORTS,Gannett Media Corp,Hackensack,...,News,3193120298,https://www.proquest.com/globalnewsfed/newspap...,2025-04-22,114.0,1.000000,"['season', 'players', 'hes', 'game', 'strength...",Help on the way? Joba Chamberlain is targeted ...,0.344828,"(0.2, 0.4]"
2036,World Series chance fading for Phils? ** Looki...,The Phillies were the oldest team in the major...,Ruben Amaro Jr.'s checklist is probably almost...,Professional baseball; Athletes\n\nPeople: Rol...,"Morning Call; Allentown, Pa.\n\nFirst page: C.1",2012,"Feb 18, 2012\n\nDateline: CLEARWATER, Fla.",Sports,"Tribune Publishing Company, LLC","Allentown, Pa.",...,News,922309657,https://www.proquest.com/globalnewsfed/newspap...,2017-11-19,114.0,1.000000,"['season', 'players', 'hes', 'game', 'strength...",April 2-3: Exhibition games vs. Pirates at Cit...,0.344828,"(0.2, 0.4]"
2234,YOUR VIEWS - LETTERS FROM OUR READERS; OPINION,None available.,Cardinals fans were welcoming As a former resi...,NaN,"St. Louis Post - Dispatch; St. Louis, Mo.",2013,"Oct 30, 2013",Editorial,"Pulitzer, Inc.","St. Louis, Mo.",...,News,1446895957,https://www.proquest.com/globalnewsfed/newspap...,2017-11-20,114.0,0.019134,"['season', 'players', 'hes', 'game', 'strength...",Having helped to create another model of aging...,0.344828,"(0.2, 0.4]"
2244,No Stanley Cup hangover for Crawford,"""I don't even think about it,"" [Corey Crawford...",Even for a team like the Blackhawks that has w...,NaN,"Daily Herald; Arlington Heights, Ill.\n\nFirst...",2013,"Oct 22, 2013",SPORTS,Daily Herald,"Arlington Heights, Ill.",...,News,1443831297,https://www.proquest.com/globalnewsfed/newspap...,2017-11-21,114.0,1.000000,"['season', 'players', 'hes', 'game', 'strength...",And to the surprise of no one in his locker ro...,0.344828,"(0.2, 0.4]"
2624,SELIG: NO CRISIS NOW,Commissioner Bud Selig said Major League Baseb...,Commissioner Bud Selig said Major League Baseb...,Professional baseball; Athletes,"Newsday, Combined editions; Long Island, N.Y.\...",2013,"Apr 26, 2013",SPORTS,Newsday LLC,"Long Island, N.Y.",...,News,1346067953,https://www.proquest.com/globalnewsfed/newspap...,2017-11-20,114.0,1.000000,"['season', 'players', 'hes', 'game', 'strength...","""Their denials are very emphatic. There is not...",0.344828,"(0.2, 0.4]"
2661,"A-RUDE INTRODUCTION Alex arrives in Bronx, but...","""We're going to leave that up to the doctors,""...",ALEX Rodriguez isn't ready for his closeup. At...,NaN,"New York Daily News; New York, N.Y.\n\nFirst p...",2013,"Apr 2, 2013",SPORTS,"Tribune Publishing Company, LLC","New York, N.Y.",...,News,1322472489,https://www.proquest.com/globalnewsfed/newspap...,2017-11-20,114.0,1.000000,"['season', 'players', 'hes', 'game', 'strength...","""Once I'm mended and back to being 100%, there...",0.344828,"(0.2, 0.4]"
2767,FOR THE AGES Rothschild keeps veteran Yank sta...,"""I think, obviously, it's nice to have those g...",TAMPA - Larry Rothschild says he's not superst...,NaN,"New York Daily News; New York, N.Y.\n\nFirst p...",2013,"Feb 8, 2013",SPORTS,"Tribune Publishing Company, LLC","New York, N.Y.",...,News,1285189420,https://www.proquest.com/globalnewsfed/newspap...,2017-11-20,114.0,1.000000,"['season', 'players', 'hes', 'game', 'strength...","""He's a veteran guy, knows what he needs. You ...",0.344828,"(0.2, 0.4]"
2782,Baseball Officials Navigate Puzzle of Anti-Agi...,"Hernan Dominguez Jr., who said he was a longti...","This article is by Steve Eder, Lizette Alvarez...",Professional baseball; Drugs & sports; Athlete...,"New York Times, Late Edition (East Coast); New...",2013,"Feb 2, 2013",D,New York Times Company,"New York, N.Y.",...,News,1283629896,https://www.proquest.com/globalnewsfed/newspap...,2017-11-20,114.0,0.208520,"['season', 'players', 'hes', 'game', 'strength...",Alain Delaquérière contributed research from N...,0.344828,"(0.2, 0.4]"
2959,Spurs continue to innovate through staff hirin...,The Spurs made use of another Canadian connect...,After the San Antonio Spurs won their fifth NB...,NaN,"The Globe and Mail; Toronto, Ont.\n\nFirst pag...",2014,"Oct 22, 2014",Sports,The Globe and Mail,"Toronto, Ont.",...,News,1614570091,https://www.proquest.com/newspapers/spurs-cont...,2017-11-22,114.0,0.041152,"['season', 'players', 'hes', 'game', 'strength...","Schelling's title is ""applied sports scientist...",0.344828,"(0.2, 0.4]"
3577,A'S SIGN MADSON FOR BULLPEN HELP: RIGHTY CAN...,[...]there is a risk for the A's in committing...,OAKLAND -- Don't expect the A's to stop addres...,Professional baseball; Athletes; Social networks,"San Jose Mercury News; San Jose, Calif.\n\nFir...",2015,"Dec 7, 2015",Sports,Bay Area News Group,"San Jose, Calif.",...,News,1746044786,https://www.proquest.com/globalnewsfed/newspap...,2015-12-08,114.0,1.000000,"['season', 'players', 'hes', 'game', 'strength...",Follow him on Twitter at twitter.com/JHickey3....,0.344828,"(0.2, 0.4]"
4130,Physical therapist stretches limits,When a health care provider possesses a passio...,When a health care provider possesses a passio...,Physical therapists; Physical therapy; Rehabil...,"Statesman Journal; Salem, Or.\n\nFirst page: D.1",2015,"Mar 16, 2015",Life,Gannett Media Corp,"Salem, Or.",...,News,1792192280,https://www.proquest.com/globalnewsfed/newspap...,2017-11-23,114.0,0.016601,"['season', 'players', 'hes', 'game', 'strength...","Twenty years ago, the deterioration of neurolo...",0.344828,"(0.2, 0.4]"
4484,Ravens' man in the middle Entering his third s...,"In the offseason, the Ravens defense parted wa...","After a recent Ravens practice, Zachary Orr wa...",Professional football; Salary caps\n\nCompany ...,"The Baltimore Sun; Baltimore, Md.\n\nFirst pag...",2016,"Sep 11, 2016",NaN,"Tribune Publishing Company, LLC","Baltimore, Md.",...,News,1818147315,https://www.proquest.com/globalnewsfed/newspap...,2017-11-23,114.0,0.040117,"['season', 'players', 'hes', 'game', 'strength...","Later, C.J. told his brother this was not the ...",0.344828,"(0.2, 0.4]"
4549,Birches baseball fans spend the day at Wrigley...,"""My favorite part was seeing Wrigley Field rem...","On August 3, residents of The Birches Assisted...",NaN,"Daily Herald; Arlington Heights, Ill.",2016,"Aug 10, 2016",Submitted Content,Daily Herald,"Arlington Heights, Ill.",...,News,1810442914,https://www.proquest.com/globalnewsfed/newspap...,2017-11-23,114.0,1.000000,"['season', 'players', 'hes', 'game', 'strength...",The Birches offers purposeful programming and ...,0.344828,"(0.2, 0.4]"
4804,Yankees preview: Aging lineup must stay health...,[...]manager Joe Girardi and company must unde...,"Over the years, the narrative hasn't changed m...",Seasons,"Newsday, Combined editions; Long Island, N.Y.",2016,"Apr 1, 2016",NEWS,Newsday LLC,"Long Island, N.Y.",...,News,1777415427,https://www.proquest.com/globalnewsfed/newspap...,2017-11-23,114.0,0.291405,"['season', 'players', 'hes', 'game', 'strength...",The most reliable options may be a pair of 26-...,0.344828,"(0.2, 0.4]"
6009,HEALTHY AGING: Alzheimer's Association and Bra...,None available.,Atlanta seniors living with dementia were rece...,Dementia; Professional baseball\n\nLocation: C...,"The Atlanta Journal - Constitution; Atlanta, G...",2018,"Jun 18, 2018",LIVING & ARTS,"Atlanta Journal Constitution, LLC","Atlanta, Ga.",...,News,2056318713,https://www.proquest.com/globalnewsfed/newspap...,2018-06-18,114.0,1.000000,"['season', 'players', 'hes', 'game', 'strength...",He said he started playing baseball at age 9 b...,0.344828,"(0.2, 0.4]"
6517,Peyton's place: Archie on Colts' legendary q...,None available.,"Of Archie Manning's three boys, Peyton is prob...",Coaches & managers; Secondary schools; High sc...,"Indianapolis Star; Indianapolis, Ind.\n\nFirst...",2019,"Sep 25, 2019\n\ncolumn: Sports",Sports,Gannett Media Corp,"Indianapolis, Ind.",...,News,2296531354,https://www.proquest.com/globalnewsfed/newspap...,2019-09-26,114.0,0.045525,"['season', 'players', 'hes', 'game', 'strength...",Reach her via e-mail: dbenbow@indystar.com. Fo...,0.344828,"(0.2, 0.4]"
10378,He's a hit He's a hit,Adamo joined McDonnell Aircraft in 1959 and st...,"V ito Adamo, 91, held out his palm in front of...",Retirement; Aging; Sports officiating\n\nBusin...,"St. Louis Post - Dispatch; St. Louis, Mo.\n\nF...",2025,"Aug 31, 2025",D,"Pulitzer, Inc.","St. Louis, Mo.",...,News,3245099576,https://www.proquest.com/globalnewsfed/newspap...,2025-08-30,114.0,0.120975,"['season', 'players', 'hes', 'game', 'strength...","Then, he brushes his own doubts aside. ""Yes, y...",0.344828,"(0.2, 0.4]"
10481,WINDOW REMAINS NARROW WILL AGING VETERANS BE A...,None available.,Omar Khan insists the Steelers are not putting...,Coaches & managers\n\nCompany / organization: ...,"Pittsburgh Post - Gazette; Pittsburgh, Pa.\n\n...",2025,"Jul 28, 2025",SPORTS,Pittsburgh Post - Ga zette,"Pittsburgh, Pa.",...,News,3233896005,https://www.proquest.com/globalnewsfed/newspap...,2025-07-30,114.0,1.000000,"['season', 'players', 'hes', 'game', 'strength...",PHOTO: Sebastian Foltz/Post-Gazette photos: De...,0.344828,"(0.2, 0.4]"
10682,WVU baseball: Mountaineers' pitching searching...,The change of some postseason conference baseb...,"ARLINGTON, Texas -- The change of some postsea...",Tournaments & championships; Mountain climbing...,"Charleston Gazette - Mail; Charleston, W.V.\n\...",2025,"May 27, 2025",NaN,Charleston Newspapers,"Charleston, W.V.",...,News,3211747820,https://www.proquest.com/globalnewsfed/newspap...,2025-05-27,114.0,1.000000,"['season', 'players', 'hes', 'game', 'strength...","""He [had to] throw some heaters in hitter's co...",0.344828,"(0.2, 0.4]"

Leave documents: 4171, 6059

In [20]:
df = remove_topic(df, 114, [4171,6059])

The orig length:11032 -> cropped: 11003

#### Topic 196

***
Topic keywords
***

In [21]:
df[df['topic']==196]['topic_keywords'].unique()

array(["['lifestyle factors', 'alzheimers', 'risk developing', 'cognitive', 'healthy lifestyle', 'reduce risk', 'alzheimers disease', 'smoking', 'alcohol', 'risk dementia', 'lower risk', 'blood pressure', 'brains', 'evidence', 'mediterranean', 'brain health', 'high blood', 'cholesterol', 'combination', 'habits', 'decline', 'review', 'followed', 'study researchers', 'cent', 'map', 'behaviors', 'met', 'cognitive decline', 'memory']"],
      dtype=object)

In [22]:
df[df['topic']==196]

,Title,Abstract,Full text,Subject,Publication title,Publication year,Publication date,Section,Publisher,Place of publication,...,Document type,ProQuest document ID,Document URL,Last updated,topic,topic_prob,topic_keywords,last,rel_ratio,rel_bins
542,Learning keeps brain healthy: [1 ],None available.,"Washington, March. 3 -- Learning keeps the bra...",NaN,The Hindustan Times; New Delhi,2010,"Mar 3, 2010\n\nDateline: Washington",NaN,HT Digital Streams Limited,New Delhi,...,WIRE FEED,471209938,https://www.proquest.com/globalnewsfed/newspap...,2018-02-25,196.0,1.0,"['lifestyle factors', 'alzheimers', 'risk deve...",Study results appear in the early online editi...,0.235294,"(0.2, 0.4]"
856,Healthy living could help fight dementia,"According to Dr. Kenneth Rockwood, MD, a profe...",Many people are apprehensive about getting old...,Dementia; Brain; Medical research; Cardiovascu...,"Prince George Citizen; Prince George, B.C.\n\n...",2011,"Sep 27, 2011",Seniors,Postmedia Network Inc.,"Prince George, B.C.",...,News,894789111,https://www.proquest.com/globalnewsfed/newspap...,2023-10-09,196.0,1.0,"['lifestyle factors', 'alzheimers', 'risk deve...",Reading is a way to stimulate vocabulary and a...,0.235294,"(0.2, 0.4]"
2416,Let the mind games begin: WELLBEING,Exercise could help reduce the risks of develo...,Exercise could help reduce the risks of develo...,Brain; Physical fitness; Exercise; Age; Dement...,"Sydney Morning Herald; Sydney, N.S.W.\n\nFirst...",2013,"Aug 3, 2013",Life,Fairfax Digital,"Sydney, N.S.W.",...,News,1416802993,https://www.proquest.com/globalnewsfed/newspap...,2017-11-20,196.0,1.0,"['lifestyle factors', 'alzheimers', 'risk deve...","""The implication is that environmental factors...",0.235294,"(0.2, 0.4]"
2863,Simple ways to reduce Alzheimer's risks,"The charity's review, which included the lates...",Lifestyle is responsible for about three-quart...,Dementia; Older people; Studies; Lifestyles; A...,Irish Examiner; Cork,2014,"Dec 16, 2014",Ireland,The Examiner Echo Group Ltd.,Cork,...,News,1636453180,https://www.proquest.com/newsp apers/simple-wa...,2023-10-09,196.0,1.0,"['lifestyle factors', 'alzheimers', 'risk deve...",But the evidence review also showed that a hea...,0.235294,"(0.2, 0.4]"
2864,"Follow five golden rules to prevent dementia, ...","According to the latest estimates, there are 8...",Lifestyle is responsible for more than three q...,Older people; Studies; Dementia; Exercise; Alz...,Telegraph.co.uk; London,2014,"Dec 15, 2014",News,Telegraph Media Group Holdings Limited,London,...,News,1636342640,https://www.proquest.com/newspapers/follow-fiv...,2023-10-09,196.0,1.0,"['lifestyle factors', 'alzheimers', 'risk deve...",It's now time for these messages to start reac...,0.235294,"(0.2, 0.4]"
2866,Follow four golden rules to ward off dementia:...,"According to the latest estimates, there are 8...",FOLLOWING four out of five golden rules for he...,Older people; Studies; Hypertension; Age; Phys...,The Daily Telegraph; London (UK)\n\nFirst page: 1,2014,"Dec 15, 2014",News; Front Page,Daily Telegraph,London (UK),...,News,1636249243,https://www.proquest.com/newspapers/follow-fou...,2023-12-06,196.0,1.0,"['lifestyle factors', 'alzheimers', 'risk deve...","""and keeping your cholesterol in check."" Howev...",0.235294,"(0.2, 0.4]"
3907,United States: A Healthy Body Often Equals a H...,"By keeping the brain both healthy and active, ...",People who want to stay sharp as they age ofte...,Aging; Dementia; Brain; Diet; Alzheimer's dise...,Asia News Monitor; Bangkok,2015,"Jul 8, 2015",Health News,Thai News Service Group,Bangkok,...,News,1694542447,https://www.proquest.com/globalnewsfed/newspap...,2024-12-04,196.0,1.0,"['lifestyle factors', 'alzheimers', 'risk deve...","Do something that requires thought, whether th...",0.235294,"(0.2, 0.4]"
4828,United States: A Healthy Heart May Protect an ...,"""The results of our study highlight the need f...",New research adds to a growing body of evidenc...,Cholesterol; Older people; Memory; Studies; He...,Asia News Monitor; Bangkok,2016,"Mar 22, 2016",Health News,Thai News Service Group,Bangkok,...,News,1774643954,https://www.proquest.com/globalnewsfed/newspap...,2024-12-04,196.0,1.0,"['lifestyle factors', 'alzheimers', 'risk deve...",Fonarow recommended that older adults might al...,0.235294,"(0.2, 0.4]"
6015,Dementia checks from 40 to be carried out by G...,None available.,Family doctors will start assessing patients’ ...,Cardiovascular disease; Public health; Disease...,Telegraph.co.uk; London,2018,"Jun 15, 2018",News,Telegraph Media Group Holdings Limited,London,...,News,2055780860,https://www.proquest.com/globalnewsfed/newspap...,2018-06-16,196.0,1.0,"['lifestyle factors', 'alzheimers', 'risk deve...","She said: “Sadly, less than a third of people ...",0.235294,"(0.2, 0.4]"
6397,HOW TO FIGHT DEMENTIA,None available.,HEALTH Recent research in the battle against d...,Exercise; Physical fitness; Memory; Blood pres...,"The Australian; Canberra, A.C.T.\n\nFirst page...",2019,"Nov 22, 2019",Life,Nationwide News Pty Ltd,"Canberra, A.C.T.",...,News,2316440485,https://www.proquest.com/globalnewsfed/newspap...,2019-11-21,196.0,1.0,"['lifestyle factors', 'alzheimers', 'risk deve...","After two years, both groups showed improvemen...",0.235294,"(0.2, 0.4]"
7307,Healthy lifestyle traits could lower Alzheimer...,None available.,A newly published study shows there are lifest...,Researchers; Health behavior; Aging; Lifestyle...,"Bismarck Tribune; Bismarck, ND\n\nFirst page: 10",2020,"Jul 20, 2020",A0,Bismarck Tribune,"Bismarck, ND",...,News,2425012472,https://www.proquest.com/newspapers/healthy-li...,2023-10-09,196.0,1.0,"['lifestyle factors', 'alzheimers', 'risk deve...",People who adhered to four or all five factors...,0.235294,"(0.2, 0.4]"
7338,Healthy lifestyle could lower Alzheimer's risk...,None available.,A newly published U.S. study shows there are l...,Researchers; Health behavior; Aging; Lifestyle...,"Toronto Star; Toronto, Ont.\n\nFirst page: B.12",2020,"Jun 25, 2020",Life,"Torstar Syndication Services, a Division of To...","Toronto, Ont.",...,News,2416837233,https://www.proquest.com/newspapers/healthy-li...,2023-10-09,196.0,1.0,"['lifestyle factors', 'alzheimers', 'risk deve...",People who adhered to four or all five factors...,0.235294,"(0.2, 0.4]"
7344,United States: Combination of healthy lifestyl...,None available.,Combining more healthy lifestyle behaviors was...,Health behavior; Blood pressure; Studies; Heal...,Asia News Monitor; Bangkok,2020,"Jun 19, 2020",General News,Thai News Service Group,Bangkok,...,News,2414414597,https://www.proquest.com/newspapers/united-sta...,2024-11-20,196.0,1.0,"['lifestyle factors', 'alzheimers', 'risk deve...",About the National Institutes of Health (NIH):...,0.235294,"(0.2, 0.4]"
7345,Certain lifestyle habits may reduce risk of Al...,None available.,A combination of different factors have been s...,Research; Researchers; Health behavior; Diet; ...,The Driffield Times; Driffield (UK),2020,"Jun 18, 2020",Traffic and Travel,National World,Driffield (UK),...,News,2414623090,https://www.proquest.com/newspapers/certain-li...,2023-10-09,196.0,1.0,"['lifestyle factors', 'alzheimers', 'risk deve...",This included undertaking at least 150 minutes...,0.235294,"(0.2, 0.4]"
8626,Game of Thrones star Emilia Clarke is missing ...,None available.,Source: The Conversation (Au and NZ) - By Anth...,Supercomputers; Exercise; Rehabilitation; Phys...,EveningReport.nz; Auckland,2022,"Jul 20, 2022",NaN,Athena Information Solutions Pvt. Ltd.,Auckland,...,News,2692182918,https://www.proquest.com/globalnewsfed/newspap...,2023-10-09,196.0,1.0,"['lifestyle factors', 'alzheimers', 'risk deve...",- ref. Game of Thrones star Emilia Clarke is m...,0.235294,"(0.2, 0.4]"
8809,Healthy options push back dementia six years: ...,None available.,A HEALTHY lifestyle could push back the onset ...,Health behavior; Life expectancy; Aging; Demen...,The Daily Telegraph; London (UK)\n\nFirst page...,2022,"Apr 14, 2022",News,Daily Telegraph,London (UK),...,News,2649869314,https://www.proquest.com/globalnewsfed/newspap...,2023-10-09,196.0,1.0,"['lifestyle factors', 'alzheimers', 'risk deve...","In a linked article in the BMJ, Dr HwaJung Cho...",0.235294,"(0.2, 0.4]"
10458,"To stay sharper while aging, get active, chall...",None available.,BY LAURAN NEERGAARD The Associated Press WASHI...,Brain; Exercise; Diet; Physical fitness; Heart...,"Telegraph - Herald; Dubuque, Iowa\n\nFirst pag...",2025,"Aug 4, 2025",NaN,Telegraph Herald,"Dubuque, Iowa",...,News,3236273119,https://www.proquest.com/globalnewsfed/newspap...,2025-08-05,196.0,1.0,"['lifestyle factors', 'alzheimers', 'risk deve...",But she hadn't realized her diet slipped when ...,0.235294,"(0.2, 0.4]"

#### Topic 94

***
Topic keywords
***

In [23]:
df[df['topic']==94]['topic_keywords'].unique()

array(["['australia', 'healthy brain', 'people dementia', 'syndrome', 'centre healthy', 'people living', 'estimated', 'alzheimers', 'readers', 'rice', 'id', 'memory', 'henry', 'awareness', 'billion', 'number people', 'street', 'september', 'supported', 'appeal', 'john', 'australians', '2050', '2025', 'executive officer', 'van', 'dedicated', 'encourage', 'projected', 'prevalence']"],
      dtype=object)

In [24]:
df[df['topic']==94]

,Title,Abstract,Full text,Subject,Publication title,Publication year,Publication date,Section,Publisher,Place of publication,...,Document type,ProQuest document ID,Document URL,Last updated,topic,topic_prob,topic_keywords,last,rel_ratio,rel_bins
923,Hoarding can be a serious disease,"Then there is the worst form of hoarding, know...","Q: Mymother, now in her 80s, is starting to ho...",NaN,"The Spectator; Hamilton, Ont.\n\nFirst page: GO.5",2011,"Sep 2, 2011",Go,"Torstar Syndication Services, a Division of To...","Hamilton, Ont.",...,News,886948564,https://www.proquest.com/globalnewsfed/newspap...,2017-11-18,94.0,0.061603,"['australia', 'healthy brain', 'people dementi...",But I would first recommend that you have your...,0.375,"(0.2, 0.4]"
929,To plan and prepare for this change,To plan and prepare for this change in demogra...,To plan and prepare for this change in demogra...,Dementia,"Port Macquarie News; Port Macquarie, N.S.W.\n\...",2011,"Aug 31, 2011",NaN,Rural Press Pty Ltd Australian Community Media...,"Port Macquarie, N.S.W.",...,News,885865551,https://www.proquest.com/globalnewsfed/newspap...,2011-08-30,94.0,1.000000,"['australia', 'healthy brain', 'people dementi...",North Coast Institute of TAFE head teacher of ...,0.375,"(0.2, 0.4]"
1460,"Prostate group hears about dementia, healthy a...",The Murray Bridge Prostate Cancer Support Grou...,The Murray Bridge Prostate Cancer Support Grou...,Older people; Meetings,"The Murray Valley Standard; Murray Bridge, S. ...",2012,"Nov 13, 2012",NaN,Rural Press Pty Ltd Australian Community Media...,"Murray Bridge, S. Aust.",...,News,1151095597,https://www.proquest.com/glob alnewsfed/newspa...,2012-11-12,94.0,0.103003,"['australia', 'healthy brain', 'people dementi...",Key elements to help find things were motivati...,0.375,"(0.2, 0.4]"
3019,Dementia-friendly nation,"DURING Dementia Awareness Month in September, ...","DURING Dementia Awareness Month in September, ...",Dementia; Alzheimer's disease,"Bay Post; Batemans Bay, N.S.W.",2014,"Sep 25, 2014",NaN,Rural Press Pty Ltd Australian Community Media...,"Batemans Bay, N.S.W.",...,News,1565566994,https://www.proquest.com/newspapers/dementia-f...,2023-10-06,94.0,1.000000,"['australia', 'healthy brain', 'people dementi...",Greater awareness and understanding of dementi...,0.375,"(0.2, 0.4]"
3037,Dementia-friendly future,During Dementia Awareness Month throughout Sep...,During Dementia Awareness Month throughout Sep...,Dementia; Inner city,"Illawarra Mercury; Wollongong, N.S.W.\n\nFirst...",2014,"Sep 15, 2014",NaN,Rural Press Pty Ltd Australian Community Media...,"Wollongong, N.S.W.",...,News,1561938209,https://www.proquest.com/newspapers/dementia-f...,2017-11-22,94.0,0.210679,"['australia', 'healthy brain', 'people dementi...",The tour along various inner city streets woul...,0.375,"(0.2, 0.4]"
3051,Fast response appreciated: opinion YOUR SAY,"Fast response appreciated LAST Sunday, a two-y...","Fast response appreciated LAST Sunday, a two-y...",Dementia\n\nLocation: Australia; United States...,"Newcastle Herald; Newcastle, N.S.W.\n\nFirst p...",2014,"Sep 13, 2014",Letters,Rural Press Pty Ltd Australian Community Media...,"Newcastle, N.S.W.",...,News,1561787894,https://www.proquest.com/newspapers/fast-respo...,2014-09-14,94.0,1.000000,"['australia', 'healthy brain', 'people dementi...",Newcastle is growing up under its own steam an...,0.375,"(0.2, 0.4]"
3175,Dementia project for Kiama,UNIVERSITY of Wollongong researchers will see ...,UNIVERSITY of Wollongong researchers will see ...,Dementia; Older people; Age; Design; Alzheimer...,"Illawarra Mercury; Wollongong, N.S.W.\n\nFirst...",2014,"Jun 27, 2014",NaN,Rural Press Pty Ltd Australian Community Media...,"Wollongong, N.S.W.",...,News,1540647878,https://www.proquest.com/newspapers/dementia-p...,2023-10-09,94.0,1.000000,"['australia', 'healthy brain', 'people dementi...",Dr Phillipson said the research would lead to ...,0.375,"(0.2, 0.4]"
3182,Second health event at practice,None available.,Following the success of the Academy Medical C...,NaN,Forfar Dispatch; Forfar (UK),2014,"Jun 24, 2014",Local News,NLA Media,Forfar (UK),...,News,1539533818,https://www.proquest.com/newspapers/second-hea...,2014-06-24,94.0,0.044688,"['australia', 'healthy brain', 'people dementi...",The subject of this talk is 'Memory and Mental...,0.375,"(0.2, 0.4]"
3744,Dementia awareness,"During Dementia Awareness Month this year, whi...","During Dementia Awareness Month this year, whi...",Executives; Aging; Mental health,"The Scone Advocate; Scone, N.S.W.",2015,"Sep 24, 2015",NaN,Rural Press Pty Ltd Australian Community Media...,"Scone, N.S.W.",...,News,1716962914,https://www.proquest.com/globalnewsfed/newspap...,2015-09-28,94.0,1.000000,"['australia', 'healthy brain', 'people dementi...",Alzheimer's Australia NSW also has a range of ...,0.375,"(0.2, 0.4]"
3760,"Call for community to be ""dementia friendly""","During Dementia Awareness Month this year, whi...","Note: John Watkins AM, Chief Executive Officer...",Dementia,Mudgee Guardian and Gulgong Advertiser; Mudgee...,2015,"Sep 20, 2015",NaN,Rural Press Pty Ltd Australian Community Media...,"Mudgee, N.S.W.",...,News,1717553177,https://www.proquest.com/globalnewsfed/newspap...,2015-09-30,94.0,1.000000,"['australia', 'healthy brain', 'people dementi...","Find out more about dementia, increase your un...",0.375,"(0.2, 0.4]"
3958,We're not prepared for rise in dementia in the...,"Sensibly, everyone seems to be planning for an...","Sensibly, everyone seems to be planning for an...",Older people; Age; Workers; Superannuation; De...,"Sydney Morning Herald; Sydney, N.S.W.\n\nFirst...","2015\n\nPublicationdate: Jun 8, 2015",NaN,Opinion,Fairfax Digital,"Sydney, N.S.W.",...,News,1686281580,https://www.proquest.com/globalnewsfed/newspap...,2023-12-06,94.0,1.000000,"['australia', 'healthy brain', 'people dementi...","Ultimately, the challenge is to improve access...",0.375,"(0.2, 0.4]"
3999,Down syndrome and the challenge of dementia: ...,People in the general population between the a...,People with Down syndrome and other intellectu...,"Dementia\n\nPeople: Hillery, John; Quinn, Vinc...",Irish Times; Dublin\n\nFirst page: 11,2015,"May 19, 2015",Health,The Irish Times DAC,Dublin,...,News,1681375133,https://www.proquest.com/globalnewsfed/newspap...,2023-12-06,94.0,0.067105,"['australia', 'healthy brain', 'people dementi...","""Other successes in the lives of people with D...",0.375,"(0.2, 0.4]"
4115,Business in fight against dementia,Genworth Mortgage Insurance chairman Richard G...,Genworth Mortgage Insurance chairman Richard G...,Dementia; Aging; Brain research; Big Data; Dis...,The Australian Financial Review; Melbourne\n\n...,2015,"Mar 24, 2015",NaN,Fairfax Media Publications Pty Limited,Melbourne,...,News,1747368654,https://www.proquest.com/globalnewsfed/newspap...,2024-12-05,94.0,1.000000,"['australia', 'healthy brain', 'people dementi...","Mr McGrath, chairman of McGrathNicol, said: ""T...",0.375,"(0.2, 0.4]"
4467,September is Dementia Awareness Month and the ...,September is Dementia Awareness Month and the ...,September is Dementia Awareness Month and the ...,Dementia\n\nLocation: Australia,"Daily Liberal and Macquarie Advocate; Dubbo, N...",2016,"Sep 20, 2016",NaN,Rural Press Pty Ltd Australian Community Media...,"Dubbo, N.S.W.",...,News,1823837126,https://www.proquest.com/globalnewsfed/newspap...,2016-09-28,94.0,1.000000,"['australia', 'healthy brain', 'people dementi...","They just may need a little bit more time, und...",0.375,"(0.2, 0.4]"
4697,Grenfell to host Dementia Services Expo,Alzheimer's Australia NSW is holding a FREE De...,Alzheimer's Australia NSW is holding a FREE De...,Dementia,"The Cowra Guardian; Cowra, N.S.W.",2016,"May 19, 2016",NaN,Rural Press Pty Ltd Australian Community Media...,"Cowra, N.S.W.",...,News,1790108215,https://www.proquest.com/globalnewsfed/newspap...,2016-06-21,94.0,1.000000,"['australia', 'healthy brain', 'people dementi...",The Grenfell Dementia Services Expo is being h...,0.375,"(0.2, 0.4]"
4720,Dementia Services Expo,QUESTIONS ABOUT DEMENTIA? GET ANSWERS AT THE D...,QUESTIONS ABOUT DEMENTIA? GET ANSWERS AT THE D...,Dementia,The Grenfell Record and Bland Advertiser; Gren...,2016,"May 11, 2016",NaN,Rural Press Pty Ltd Australian Community Media...,"Grenfell, N.S.W.",...,News,1792801808,https://www.proquest.com/globalnewsfed/newspap...,2016-06-01,94.0,1.000000,"['australia', 'healthy brain', 'people dementi...","The program will include: Your Brain Matters, ...",0.375,"(0.2, 0.4]"
4729,Know the brain health signs,MEMORY loss may seem a normal part of the agei...,MEMORY loss may seem a normal part of the agei...,Aging,"The Irrigator; Leeton, N.S.W.",2016,"May 7, 2016",NaN,Rural Press Pty Ltd Australian Community Media...,"Leeton, N.S.W.",...,News,1787334081,https://www.proquest.com/globalnewsfed/newspap...,2016-05-08,94.0,0.037796,"['australia', 'healthy brain', 'people dementi...",The organisation's healthy brain ageing and me...,0.375,"(0.2, 0.4]"
4870,Support available for dementia sufferers,New dementia figures for 2016 show more people...,New dementia figures for 2016 show more people...,Chief executive officers,Mudgee Guardian and Gulgong Advertiser; Mudgee...,2016,"Mar 6, 2016",NaN,Rural Press Pty Ltd Australian Community Media...,"Mudgee, N.S.W.",...,News,1772119259,https://www.proquest.com/globalnewsfed/newspap...,2016-03-11,94.0,1.000000,"['australia', 'healthy brain', 'people dementi...",We encourage your readers who have a diagnosis...,0.375,"(0.2, 0.4]"
4871,Depression and dementia link,MORE than 500 residents packed out the Port Ma...,MORE than 500 residents packed out the Port Ma...,Dementia; Mental depression; Seminars,"Port Macquarie News; Port Macquarie, N.S.W.",2016,"Mar 3, 2016",NaN,Rural Press Pty Ltd Australian Community Media...,"Port Macquarie, N.S.W.",...,News,1771938685,https://www.proquest.com/globalnewsfed/newspap...,2016-03-11,94.0,0.202343,"['australia', 'healthy brain', 'people dementi...",There were a lot more people than we were exce...,0.375,"(0.2, 0.4]"
5075,Norwich consultant psychiatrist recognised in ...,None available.,A consultant psychiatrist with the region's me...,Nominations; Psychiatrists; Dementia,Eastern Daily Press; Norwich (UK),2017,"Nov 11, 2017",Social News,NLA Media,Norwich (UK),...,News,1962533775,https://www.proquest.com/globalnewsfed/newspap...,2017-11-11,94.0,1.000000,"['australia', 'healthy brain', 'people dementi...","""It was completely unexpected, but it goes wit...",0.375,"(0.2, 0.4]"
5194,Increasing dementia cases in Sutherland Shire ...,"There were 3,635 recorded cases of dementia am...","There were 3,635 recorded cases of dementia am...",Councils; Advisors; Seminars; Brain research; ...,St. George and Sutherland Shire Leader; Rockda...,2017,"Sep 15, 2017",NaN,Rural Press Pty Ltd Australian Community Media...,"Rockdale, N.S.W.",...,News,1938663134,https://www.proquest.com/globalnewsfed/newspap...,2017-11-03,94.0,0.098861,"['australia', 'healthy brain', 'people dementi...","""Dementia often develops slowly but needs to b...",0.375,"(0.2, 0.4]"
5466,Letter: Bat stench,A new report just released has found that the ...,A new report just released has found that the ...,Councils; Dementia\n\nLocation: Australia\n\nC...,"Port Macquarie News; Port Macquarie, N.S.W.",2017,"Apr 7, 2017",Domain,Rural Press Pty Ltd Australian Community Media...,"Port Macquarie, N.S.W.",...,News,1884639864,https://www.proquest.com/globalnewsfed/newspap...,2017-04-07,94.0,1.000000,"['australia', 'healthy brain', 'people dementi...",The section of Ocean Drive from approximately ...,0.375,"(0.2, 0.4]"
5478,More spending needed to wipe out dementia,"Governments, the corporate sector and the comm...","Governments, the corporate sector and the comm...",Dementia; Costs\n\nBusiness indexing term: Sub...,The Australian Financial Review; Melbourne\n\n...,2017,"Mar 30, 2017",Market Wrap,Fairfax Media Publications Pty Limited,Melbourne,...,News,188180365 4,https://www.proquest.com/globalnewsfed/newspap...,2024-12-08,94.0,1.000000,"['australia', 'healthy brain', 'people dementi...","""It is one of many health concerns but it gets...",0.375,"(0.2, 0.4]"
5497,"Dear Editor, A new report just released has fo...","Dear Editor, A new report just released has fo...","Dear Editor, A new report just released has fo...",Dementia; Rebates\n\nLocation: Australia\n\nCo...,"Cootamundra Herald; Cootamundra, N.S.W.\n\nFir...",2017,"Mar 22, 2017",Opinion,Rural Press Pty Ltd Australian Community Media...,"Cootamundra, N.S.W.",...,News,1879372041,https://www.proquest.com/globalnewsfed/newspap...,2017-03-22,94.0,1.000000,"['australia', 'healthy brain', 'people dementi...","Earlier this month, we doubled the rebate to $...",0.375,"(0.2, 0.4]"
5540,THERE will be several free information session...,THERE will be several free information session...,THERE will be several free information session...,Older people; Memory; Dementia\n\nLocation: Au...,"Central Western Daily; Orange, N.S.W.\n\nFirst...",2017,"Mar 3, 2017",NaN,Rural Press Pty Ltd Australian Community Media...,"Orange, N.S.W.",...,News,1873515941,https://www.proquest.com/globalnewsfed/newspap...,2017-03-03,94.0,0.190056,"['australia', 'healthy brain', 'people dementi...",The Alzheimer's Australia NSW memory van will ...,0.375,"(0.2, 0.4]"
5848,What’s on,None available.,"Tuesday, September 11 Breath Ezi will meet at ...",Womens health; Aging; Dementia\n\nLocation: Au...,"Western Advocate; Bathurst, N.S.W.\n\nFirst pa...",2018,"Sep 11, 2018",Opinion,Rural Press Pty Ltd Australian Community Media...,"Bathurst, N.S.W.",...,News,2110267730,https://www.proquest.com/globalnewsfed/newspap...,2018-09-21,94.0,1.000000,"['australia', 'healthy brain', 'people dementi...","Call 0407 615 480, email Jenny.roberts@dementi...",0.375,"(0.2, 0.4]"
6665,Mornington aged trial,None available.,ELDERLY residents on the Mornington Peninsula ...,Researchers; Dementia\n\nLocation: Australia; ...,"Herald Sun; Melbourne, Vic.\n\nFirst page: 9",2019,"Jul 18, 2019",News,Nationwide News Pty Ltd,"Melbourne, Vic.",...,News,2258969609,https://www.proquest.com/globalnewsfed/newspap...,2019-07-17,94.0,0.172482,"['australia', 'healthy brain', 'people dementi...",ELDERLY residents on the Mornington Peninsula ...,0.375,"(0.2, 0.4]"
7871,World: New WHO toolkit promotes inclusion of p...,None available.,Towards a dementia-inclusive society: WHO tool...,Dementia; Initiatives\n\nCompany / organizatio...,Asia News Monitor; Bangkok,2021,"Aug 12, 2021",General News,Thai News Service Group,Bangkok,...,News,2560091948,https://www.proquest.com/newspapers/world-new-...,2024-11-15,94.0,1.000000,"['australia', 'healthy brain', 'people dementi...",The modules can be used together or separately...,0.375,"(0.2, 0.4]"
8341,VIPS in visit to centre that aids elderly,None available.,A pioneering charity dedicated to older people...,Clinical trials; Older people; Memory; Dementi...,The Bath Chronicle; Bath (UK),2022,"Nov 24, 2022",News,MGN Ltd.,Bath (UK),...,News,2739357457,https://www.proquest.com/globalnewsfed/newspap...,2023-10-09,94.0,0.123400,"['australia', 'healthy brain', 'people dementi...",The institute's aim is to find a cure for deme...,0.375,"(0.2, 0.4]"
8625,Dementia team launches drive to expand research,None available.,A Bath charity launched an appeal this week to...,Charities; Older people; Memory; Dementia\n\nL...,The Bath Chronicle; Bath (UK),2022,"Jul 21, 2022",News,MGN Ltd.,Bath (UK),...,News,2691983157,https://www.proquest.com/globalnewsfed/newspap...,2022-07-21,94.0,0.044478,"['australia', 'healthy brain', 'people dementi...","""Roy established one of the first memory clini...",0.375,"(0.2, 0.4]"
9394,PJ’s emotional connection to his dementia fund...,None available.,The motive was sparked after witnessing the de...,Brain research; Dementia; Alzheimer's disease\...,"The Daily Telegraph (Online); Surrey Hills, N....",2023,"Aug 29, 2023",NaN,Nationwide News Pty Ltd,"Surrey Hills, N.S.W.",...,News\n\nPublication history : \n\nMilestone da...,2858511394,https://www.proquest.com/newspapers/pj-s-emoti...,2023-10-09,94.0,0.099509,"['australia', 'healthy brain', 'people dementi...",“I don’t think they understand that it’s not o...,0.375,"(0.2, 0.4]"
9408,PJ’s personal link to marathon dementia fundra...,None available.,"It’s more than just a run for PJ Lane, son of ...",Fund raising; Brain research; Dementia; Alzhei...,"The Daily Telegraph; Surry Hills, N.S.W.\n\nFi...",2023,"Aug 25, 2023",News,Nationwide News Pty Ltd,"Surry Hills, N.S.W.",...,News,2856624254,https://www.proquest.com/newspapers/pj-s-perso...,2023-10-09,94.0,0.039746,"['australia', 'healthy brain', 'people dementi...",“It’s absolutely heartbreaking.” Dementia is t...,0.375,"(0.2, 0.4]"

### Topic rel_ratio 0.4 - 0.6

In [25]:
df[(df["rel_ratio"] > 0.4) & (df["rel_ratio"] <= 0.6)]['topic'].unique()

array([158., 136., 214.])

#### Topic 158

In [26]:
df[df['topic']==158]['topic_keywords'].unique()

array(["['dance', 'dancing', 'classes', 'music', 'youve', 'youve got', 'margaret', 'moves', 'australian', 'sydney', 'line', 'class', 'physical activity', 'fun', 'mood', 'popular', 'floor', 'health wellbeing', 'felt', 'love', 'began', 'happiness', 'examining', 'stage', 'happy', 'kelly', 'balance', 'professional', 'husband', 'sharp']"],
      dtype=object)

In [27]:
df[df['topic']==158]

,Title,Abstract,Full text,Subject,Publication title,Publication year,Publication date,Section,Publisher,Place of publication,...,Document type,ProQuest document ID,Document URL,Last updated,topic,topic_prob,topic_keywords,last,rel_ratio,rel_bins
2,dancing longevity,"""It's good both physically and mentally becaus...","For instructor, is key to Thelma Nelson believ...",NaN,"South Bend Tribune; South Bend, Ind.\n\nFirst ...",2010,"Dec 30, 2010",NaN,South Bend Tribune Corporation,"South Bend, Ind.",...,News,821827067,https://www.proquest.com/globalnewsfed/newspap...,2011-02-07,158.0,0.541152,"['dance', 'dancing', 'classes', 'music', 'youv...","""All it takes is music to get me tapping."" In ...",0.571429,"(0.4, 0.6]"
657,A DANCE TO THE MUSIC OF TIME,Company budgets mostly don't stretch to assist...,Sometimes retirement comes too early. Jane Alb...,Ballet; Dance; Retirement\n\nCompany / organiz...,"Weekend Australian; Canberra, A.C.T.\n\nFirst ...",2011,"Dec 31, 2011",Review,Nationwide News Pty Ltd,"Canberra, A.C.T.",...,News,913038388,https://www.proquest.com/globalnewsfed/newspap...,2011-12-30,158.0,1.000000,"['dance', 'dancing', 'classes', 'music', 'youv...","""I don't miss the day-to-day slog, I don't mis...",0.571429,"(0.4, 0.6]"
2682,Area News in Brief: Seniors can learn health...,None available.,The Long Beach Island Health Department is hos...,NaN,"Asbury Park Press; Asbury Park, N.J.\n\nFirst ...",2013,"Mar 21, 2013",A,Gannett Media Corp,"Asbury Park, N.J.",...,News,1321088862,https://www.proquest.com/globalnewsfed/newspap...,2017-11-20,158.0,0.018672,"['dance', 'dancing', 'classes', 'music', 'youv...","For more information, go to www.noyesmuseum.or...",0.571429,"(0.4, 0.6]"
3528,Is this the reel cure for old age?: Scots co...,"Elizabeth Foster, executive officer of the Roy...",IT is known and loved worldwide for its boiste...,Physical fitness; Dance; Studies,Mail on Sunday; London (UK)\n\nFirst page: 48,2014,"Jan 12, 2014",News,"Solo Syndication, a division of Associated New...",London (UK),...,News,1476559717,https://www.proquest.com/newspapers/is-this-re...,2014-01-12,158.0,1.000000,"['dance', 'dancing', 'classes', 'music', 'youv...","Elizabeth Foster, executive officer of the Roy...",0.571429,"(0.4, 0.6]"
3852,"Happy, healthy & fit golden years: Dance gat...","""I have to wear high heels,"" the Yakima woman ...",Sue MacMichaels is 99 years old and still danc...,NaN,"Yakima Herald - Republic; Yakima, Wash.\n\nFir...",2015,"Jul 30, 2015",NaN,Yakima Herald Republic,"Yakima, Wash.",...,News,1701982265,https://www.proquest.com/globalnewsfed/newspap...,2015-08-06,158.0,1.000000,"['dance', 'dancing', 'classes', 'music', 'youv...","They're my inspiration,"" Cooper said. ""I'm hop...",0.571429,"(0.4, 0.6]"
4040,news briefs: [2 ],ANDOVERGet your broken stuff fixed at this cli...,ANDOVERGet your broken stuff fixed at this cli...,NaN,"Star Tribune; Minneapolis, Minn.\n\nFirst page...",2015,"Apr 29, 2015",NEWS,Star Tribune Media Company LLC,"Minneapolis, Minn.",...,News,1676473091,https://www.proquest.com/globalnewsfed/newspap...,2017-11-22,158.0,0.008890,"['dance', 'dancing', 'classes', 'music', 'youv...",Those who are interested may attend two meetin...,0.571429,"(0.4, 0.6]"
5126,Dance your way to a healthier ageing brain,None available.,NYT Syndicate Dance classes may beat tradition...,Researchers; Exercise; Physical fitness; Older...,Qatar Tribune; Doha,2017,"Oct 17, 2017",NaN,"Disco Digital Media, Inc.",Doha,...,News,1951389576,https://www.proquest.com/globalnewsfed/newspap...,2023-10-09,158.0,1.000000,"['dance', 'dancing', 'classes', 'music', 'youv...",But he agreed that exercise in general plus a ...,0.571429,"(0.4, 0.6]"
5689,Health benefits of dancing for the elderly,None available.,"Pakistan, Dec. 1 -- ""Dance, when you are broke...",Population; Older people; Dance\n\nLocation: P...,Daily Times; Lahore,2018,"Dec 1, 2018\n\nDateline: Pakistan",NaN,HT Digital Streams Limited,Lahore,...,News,2139684210,https://www.proquest.com/globalnewsfed/newspap...,2018-11-30,158.0,0.324265,"['dance', 'dancing', 'classes', 'music', 'youv...",Your hearts are still very young. Stay blessed...,0.571429,"(0.4, 0.6]"
5690,Dance in old age,None available.,"Pakistan, Nov. 30 -- ""Dance, when you are brok...",Older people; Dance\n\nLocation: Pakistan; Isl...,Daily Times; Lahore,2018,"Nov 30, 2018\n\nDateline: Pakistan",NaN,HT Digital Streams Limited,Lahore,...,News,2139498227,https://www.proquest.com/globalnewsfed/newspap...,2018-12-13,158.0,1.000000,"['dance', 'dancing', 'classes', 'music', 'youv...",Your hearts are still very young. Stay blessed...,0.571429,"(0.4, 0.6]"
6138,Dance your way to healthier ageing,None available.,You may want to put on your dancing shoes and ...,Older people; Ballet\n\nLocation: Queensland A...,The Hindu; Chennai,2018,"Apr 16, 2018",Metro Plus,THG Publishing Private Limited,Chennai,...,News,20 25246196,https://www.proquest.com/globalnewsfed/newspap...,2018-04-16,158.0,1.000000,"['dance', 'dancing', 'classes', 'music', 'youv...",Queensland Ballet and QUT released the results...,0.571429,"(0.4, 0.6]"
6144,Dance your way to healthier aging,None available.,"Washington D.C. [USA], Apr 14 (ANI): Oldies, y...",Older people; Dance; Aging; Ballet\n\nLocation...,Asian News International; New Delhi,2018,"Apr 14, 2018",NaN,"Disco Digital Media, Inc.",New Delhi,...,News,2024715368,https://www.proquest.com/globalnewsfed/newspap...,2018-04-14,158.0,1.000000,"['dance', 'dancing', 'classes', 'music', 'youv...","""The physical benefits of movement and dance o...",0.571429,"(0.4, 0.6]"
6153,"Dancing through life is the key to happy, heal...",The owner and operator of Outloud Dance Studio...,Lara Armstrong is on a mission - to get Margar...,Older people; Dance studios; Dancers & choreog...,"Augusta - Margaret River Mail; Margaret River,...",2018,"Apr 11, 2018",Entertainment,Rural Press Pty Ltd Australian Community Media...,"Margaret River, W.A.",...,News,2023494043,https://www.proquest.com/globalnewsfed/newspap...,2018-04-10,158.0,1.000000,"['dance', 'dancing', 'classes', 'music', 'youv...",Jade is our brilliant choreographer and teache...,0.571429,"(0.4, 0.6]"
8591,Dancing Past 100,None available.,"Enlarge this image. At 104, my great-aunt Len...",Girls; Exercise; Community centers; Physical f...,"St. Joseph News - Press; St. Joseph, Mo.",2022,"Aug 6, 2022",News-Press NOW,St. Joseph News - Press,"St. Joseph, Mo.",...,News,2699209593,https://www.proquest.com/globalnewsfed/newspap...,2022-08-07,158.0,1.000000,"['dance', 'dancing', 'classes', 'music', 'youv...","* Lenore Schaeffer died on Dec. 16, 2004, at a...",0.571429,"(0.4, 0.6]"
8967,HOW TO ENJOY HEALTHY AGEING,None available.,SPONSORED CONTENT Active steps people can take...,Exercise; Music; Physical fitness; Age; Aging;...,"The Courier - Mail; Brisbane, Qld.\n\nFirst pa...",2022,"Jan 29, 2022",News,Nationwide News Pty Ltd,"Brisbane, Qld.",...,News,2623147265,https://www.proquest.com/globalnewsfed/newspap...,2022-01-27,158.0,0.029140,"['dance', 'dancing', 'classes', 'music', 'youv...","“In a suburb, everyone is more involved with t...",0.571429,"(0.4, 0.6]"
9127,Bắc Giang's district popularises dance clubs,None available.,Dance clubs in Lục Ngạn District in the northe...,Older people; Dance; Clubs,Viet Nam News; Hanoi,2023,"Nov 20, 2023\n\nDateline: LỤC NGẠN",NaN,Vietnam News Agency,Hanoi,...,News,2893982976,https://www.proquest.com/newspapers/bắc-giangs...,2023-11-27,158.0,1.000000,"['dance', 'dancing', 'classes', 'music', 'youv...","""But we search for dances specifically for the...",0.571429,"(0.4, 0.6]"
9134,Angela's Strictly moves inspiring older dancer...,None available.,A NGELA Rippon's starring role on Strictly Com...,Dance education; Older people; Ballroom dancin...,The Western Morning News; Plymouth (UK),2023,"Nov 18, 2023",News,MGN Ltd.,Plymouth (UK),...,News,2891135217,https://www.proquest.com/newspapers/angelas-st...,2023-11-18,158.0,1.000000,"['dance', 'dancing', 'classes', 'music', 'youv...","""Studies show one in three over 65s and one in...",0.571429,"(0.4, 0.6]"
10099,Discovering the dance steps to healthier lifes...,None available.,Dancing into old age is one way of living long...,Public health; Music; Older people; Councils; ...,Yorkshire Evening Post; Leeds (UK),2024,"Aug 8, 2024",News,NLA Media,Leeds (UK),...,News,3090049588,https://www.proquest.com/globalnewsfed/newspap...,2024-08-08,158.0,1.000000,"['dance', 'dancing', 'classes', 'music', 'youv...","For more information on Dance On, which runs 1...",0.571429,"(0.4, 0.6]"
10118,The dance steps to healthier lifestyle: Danc...,None available.,DISCO dancing Margaret Nutter has still got al...,Public health; Older people; Councils; Age; Da...,The Yorkshire Post; Leeds (UK),2024,"Jul 29, 2024",News,NLA Media,Leeds (UK),...,News,3085266603,https://www.proquest.com/globalnewsfed/newspap...,2024-07-28,158.0,1.000000,"['dance', 'dancing', 'classes', 'music', 'youv...",Creating more opportunities for people to keep...,0.571429,"(0.4, 0.6]"
10396,Does exercise really make people more happy?,None available.,"Above all else, she is genuinely happy. “I lov...",Endorphins; Exercise; Physical fitness; Happin...,"The Australian (Online); Canberra, A.C.T.",2025,"Aug 25, 2025",NaN,Nationwide News Pty Ltd,"Canberra, A.C.T.",...,News\n\nPublication history : \n\nMilestone da...,3243183190,https://www.proquest.com/globalnewsfed/newspap...,2025-08-26,158.0,0.037623,"['dance', 'dancing', 'classes', 'music', 'youv...",It’s one of the forms of activity he speaks ab...,0.571429,"(0.4, 0.6]"
10397,Pirouette and glide your way to life of wellbeing,None available.,Tie Yamato is graceful and poised as she glide...,Well being; Endorphins; Exercise; Physical fit...,"The Australian; Canberra, A.C.T.\n\nFirst page: 3",2025,"Aug 25, 2025",TheNation,Nationwide News Pty Ltd,"Canberra, A.C.T.",...,News,3242782360,https://www.proquest.com/globalnewsfed/newspap...,2025-08-25,158.0,1.000000,"['dance', 'dancing', 'classes', 'music', 'youv...",So it releases these endorphins to regulate an...,0.571429,"(0.4, 0.6]"
10479,Trip the night fantastic: Spots around LI fo...,None available.,By Natalia de Cuba Romero Special to Newsday S...,Social dance; Line dancing\n\nLocation: Cuba; ...,"Newsday, Combined editions; Long Island, N.Y.\...",2025,"Jul 29, 2025",EXPLORE LI,Newsday LLC,"Long Island, N.Y.",...,News,3234114560,https://www.proquest.com/globalnewsfed/newspap...,2025-07-29,158.0,1.000000,"['dance', 'dancing', 'classes', 'music', 'youv...",MORE INFO theboatyardny.com Monday Night Dance...,0.571429,"(0.4, 0.6]"

Noisy articles: 4080, 2716

In [28]:
df = df[~df.index.isin([4080,2716])]

#### Topic 34

In [29]:
df[df['topic']==34]['topic_keywords'].unique()

array(["['company organization', 'naics', 'laura', 'texas', 'jones', 'md', 'susan', 'linda', 'cross', 'text', 'edition', 'julie', 'print', 'don', 'document', 'jr', 'pat', 'stephen', 'ann', 'nancy', 'eric', 'jean', 'display', 'lisa', 'jennifer', 'william', 'kim', 'jim', 'carol', 'tom']"],
      dtype=object)

In [30]:
df[df['topic']==34]

,Title,Abstract,Full text,Subject,Publication title,Publication year,Publication date,Section,Publisher,Place of publication,...,Document type,ProQuest document ID,Document URL,Last updated,topic,topic_prob,topic_keywords,last,rel_ratio,rel_bins
1682,High-protein diet crucial for healthy aging [F...,None available.,Display of this document is currently not perm...,NaN,"The Province; Vancouver, B.C.",2012,"Aug 10, 2012",NaN,Postmedia Network Inc.,"Vancouver, B.C.",...,News,1033574815,https://www.proquest.com/globalnewsfed/newspap...,2017-11-19,34.0,0.010055,"['company organization', 'naics', 'laura', 'te...",Display of this document is currently not perm...,1.0,"(0.8, 1.0]"

***
Let's drop these since Full text is not available for them. If we need more data later, we can search it.
***

In [31]:
df = remove_topic(df,34,[])

The orig length:11001 -> cropped: 11000

#### Topic 136

In [32]:
df[df['topic']==136]['topic_keywords'].unique()

array(["['games', 'game', 'video', 'cognitive', 'memory', 'played', 'computer', 'playing', 'mild', 'cognition', 'skills', 'cognitive impairment', 'functioning', 'impairment', 'visual', 'app', 'alzheimers', 'cognitive function', 'fitness', 'memory loss', 'function', 'grace', 'san francisco', 'journal', 'francisco', 'brains', 'tasks', 'prof', 'performed', 'san']"],
      dtype=object)

In [33]:
df[df['topic']==136]

,Title,Abstract,Full text,Subject,Publication title,Publication year,Publication date,Section,Publisher,Place of publication,...,Document type,ProQuest document ID,Document URL,Last updated,topic,topic_prob,topic_keywords,last,rel_ratio,rel_bins
96,EVERYONE'S TALKING ABOUT SUCCESSFUL AGING ACTI...,"According to the U.S. Census Bureau, 35 millio...",Note: SPECIAL SECTION: SUCCESSFUL AGING HEALTH...,Aging; Older people; Colleges & universities; ...,"Daily News; Los Angeles, Calif.\n\nFirst page:...",2010,"Nov 4, 2010",L.A. Life,Los Angeles Newspaper Group,"Los Angeles, Calif.",...,News,762401249,https://www.proquest.com/globalnewsfed/newspap...,2023-10-09,136.0,1.000000,"['games', 'game', 'video', 'cognitive', 'memor...","Where: Sheraton Universal Hotel, Universal Cit...",0.56,"(0.4, 0.6]"
200,Mind games: Does play really help the brain?,"""Even if brain-fitness programs can improve th...","Crosswords, Sudoku, Nintendo - now scientists ...",NaN,"The Globe and Mail; Toronto, Ont.",2010,"Sep 22, 2010",National News,The Globe and Mail,"Toronto, Ont.",...,News,751959679,https://www.proquest.com/globalnewsfed/newspap...,2017-11-17,136.0,1.000000,"['games', 'game', 'video', 'cognitive', 'memor...","""Even if brain-fitness programs can improve th...",0.56,"(0.4, 0.6]"
1300,Higher levels of social activity cut the risk ...,None available.,"Washington, Feb. 18 -- Higher levels of social...",NaN,The Hindustan Times; New Delhi,2011,"Feb 18, 2011\n\nDateline: Washington",NaN,HT Digital Streams Limited,New Delhi,...,WIRE FEED,852626739,https://www.proquest.com/globalnewsfed/newspap...,2018-02-26,136.0,0.064593,"['games', 'game', 'video', 'cognitive', 'memor...",Future research is needed to determine whether...,0.56,"(0.4, 0.6]"
1879,Can video games promote healthier aging?,Video game technology has significant benefits...,"Berlin, April 26 -- Video game technology has ...",Older people; Social interaction; Journals\n\n...,The South Asian Times; Hicksville,2012,"Apr 26, 2012\n\nDateline: Berlin",NaN,HT Digital Streams Limited,Hicksville,...,NEWSPAPER,1010045636,https://www.proquest.com/globalnewsfed/newspap...,2012-04-28,136.0,1.000000,"['games', 'game', 'video', 'cognitive', 'memor...",The second study was conducted in three Europe...,0.56,"(0.4, 0.6]"
2300,HEALTHY LIVING: Computer games exercise aging ...,Because of the success of high-tech memory pro...,If you're worried about age-related memory los...,Physical fitness; Memory; Brain research; Olde...,"The Atlanta Journal - Constitution; Atlanta, Ga.",2013,"Sep 29, 2013",FEATURES,"Atlanta Journal Constitution, LLC","Atlanta, Ga.",...,Feature,1437433298,https://www.proquest.com/globalnewsfed/newspap...,2017-11-20,136.0,1.000000,"['games', 'game', 'video', 'cognitive', 'memor...",> Engage in social activities that emphasize i...,0.56,"(0.4, 0.6]"
2349,Play for your brain,A VIDEO game can help elderly people fight cog...,A VIDEO game can help elderly people fight cog...,Older people; Medical research,"Herald Sun; Melbourne, Vic.\n\nFirst page: 32",2013,"Sep 6, 2013",GENERALNEW,Nationwide News Pty Ltd,"Melbourne, Vic.",...,News,142984 9063,https://www.proquest.com/globalnewsfed/newspap...,2017-11-20,136.0,1.000000,"['games', 'game', 'video', 'cognitive', 'memor...","The 3D game had hidden complexities, pushing p...",0.56,"(0.4, 0.6]"
2355,Video games may boost brain power,Studies have shown that specially-made games c...,Video games may seem like a mindless way to wa...,Older people; Computer & video games; Children...,"The Poughkeepsie Journal; Poughkeepsie, N.Y.\n...",2013,"Sep 8, 2013",E,Gannett Media Corp,"Poughkeepsie, N.Y.",...,News,1430760286,https://www.proquest.com/globalnewsfed/newspap...,2019-12-06,136.0,1.000000,"['games', 'game', 'video', 'cognitive', 'memor...",Forcing people to keep driving up windy mounta...,0.56,"(0.4, 0.6]"
2356,Study Finds Video Games Aid Memory In Elderly,"""Challenging yourself with new situations is n...","SAN FRANCISCO - Video games, largely considere...",NaN,"The Times - Tribune; Scranton, Pa.",2013,"Sep 5, 2013\n\nDateline: Scranton, PA",News,The Times-Tribune,"Scranton, Pa.",...,News,143 0276384,https://www.proquest.com/globalnewsfed/newspap...,2013-09-05,136.0,1.000000,"['games', 'game', 'video', 'cognitive', 'memor...","The task split the players' attention, requiri...",0.56,"(0.4, 0.6]"
2460,A gym for the mind: Brain 'training' gains cur...,Though it's too early to know what kind of tra...,"About 18 months ago, Hope began forgetting thi...",Hospitals; Health care; Brain; Computer & vide...,"Boston Globe; Boston, Mass.",2013,"Jul 15, 2013",Lifestyle,"Boston Globe Media Partners, LLC","Boston, Mass.",...,News,1399885449,https://www.proquest.com/globalnewsfed/newspap...,2017-11-20,136.0,1.000000,"['games', 'game', 'video', 'cognitive', 'memor...","That's the whole thing,"" he said. By Karen Wei...",0.56,"(0.4, 0.6]"
3149,HEALTHY AGING: Giving a twist to aging gracefu...,While baby boomers make up the greatest group ...,"We're swimming,"" calls out Sandy Bramlett, rot...",Assisted living facilities; Music; Creativity;...,"The Atlanta Journal - Constitution; Atlanta, Ga.",2014,"Jul 20, 2014",FEATURES,"Atlanta Journal Constitution, LLC","Atlanta, Ga.",...,Feature,1551474882,https://www.proquest.com/newspapers/healthy-ag...,2017-11-21,136.0,0.136725,"['games', 'game', 'video', 'cognitive', 'memor...","--- Heart muscle, cardio conditioning, spinal ...",0.56,"(0.4, 0.6]"
3292,Pakistan: Can video games promote healthier ag...,New research is showing that exergames have si...,"ISLAMABAD, May 3 -- Videogame technology is pr...",Older people; Computer & video games\n\nLocati...,Right Vision News; Lahore,2014,"May 3, 2014\n\nDateline: ISLAMABAD",NaN,HT Digital Streams Limited,Lahore,...,NEWSPAPER,1520436769,https://www.proquest.com/newspapers/pakistan-c...,2014-05-02,136.0,1.000000,"['games', 'game', 'video', 'cognitive', 'memor...",All of these benefits can improve the well-bei...,0.56,"(0.4, 0.6]"
4533,Pokemon Go benefits Birches resident with memo...,While the average Pokemon Go user is likely in...,"For the past two months, Pokemon Go-mania has ...",NaN,"Daily Herald; Arlington Heights, Ill.",2016,"Aug 18, 2016",Submitted Content,Daily Herald,"Arlington Heights, Ill.",...,News,1812329267,https://www.proquest.com/globalnewsfed/newspap...,2017-11-24,136.0,1.000000,"['games', 'game', 'video', 'cognitive', 'memor...",The Birches offers purposeful programming and ...,0.56,"(0.4, 0.6]"
4557,Computer game may help delay Alzheimer's; Cogn...,"Monday in Toronto, a research team led by Jerr...",You're staring at a computer screen. Two objec...,Diversity training; Dementia; Memory; Cognitio...,"The Vancouver Sun; Vancouver, B.C.\n\nFirst pa...",2016,"Jul 30, 2016",Weekend Review,Postmedia Network Inc.,"Vancouver, B.C.",...,News,1807750589,https://www.proquest.com/globalnewsfed/newspap...,2017-11-23,136.0,1.000000,"['games', 'game', 'video', 'cognitive', 'memor...","""But we need more understanding. I don't think...",0.56,"(0.4, 0.6]"
5305,Scientists Develop Computer Game to Combat Dem...,None available.,London - British neuroscientists have develope...,Memory; Studies; Dementia; Alzheimer's disease...,"Asharq Alawsat, English ed.; London",2017,"Jul 5, 2017",NaN,"Disco Digital Media, Inc.",London,...,News,1915748890,https://www.proquest.com/globalnewsfed/newspap...,2023-10-09,136.0,1.000000,"['games', 'game', 'video', 'cognitive', 'memor...",Savulich said that as well as improving their ...,0.56,"(0.4, 0.6]"
5308,'Brain training' app improves memory in people...,None available.,A brain training computer game developed by Br...,Memory; Dementia; Alzheimer's disease\n\nCompa...,Yerepouni Daily News; Beirut,2017,"Jul 3, 2017",NaN,"Disco Digital Media, Inc.",Beirut,...,News,1915236415,https://www.proquest.com/globalnewsfed/newspap...,2023-10-09,136.0,1.000000,"['games', 'game', 'video', 'cognitive', 'memor...","""While this type of brain training will not ul...",0.56,"(0.4, 0.6]"
5311,New 'brain training' app lets you game your wa...,None available.,"Washington D.C. [USA], Jul 3 (ANI): A team of ...",Researchers; Motivation; Memory; Studies; Deme...,Asian News International; New Delhi,2017,"Jul 3, 2017",NaN,"Disco Digital Media, Inc.",New Delhi,...,News,1915222213,https://www.proquest.com/globalnewsfed/newspap...,2023-10-09,136.0,1.000000,"['games', 'game', 'video', 'cognitive', 'memor...",The study is published in The International Jo...,0.56,"(0.4, 0.6]"
5422,Video games could aid dementia fight,None available.,Elderly people can stave off Alzheimer's disea...,Kayaking; Exercise; Computer & video games; Ph...,Western Daily Press; Bristol (UK)\n\nFirst pag...,2017,"May 4, 2017",News,MGN Ltd.,Bristol (UK),...,News,1894830571,https://www.proquest.com/globalnewsfed/newspap...,2023-10-09,136.0,1.000000,"['games', 'game', 'video', 'cognitive', 'memor...","He said: ""With an ageing population these game...",0.56,"(0.4, 0.6]"
5423,Video game hope in dementia fight,Experts at the University of Manchester have f...,VIDEO games could prevent the worsening of Alz...,Computer & video games; Colleges & universitie...,Manchester Evening News; Glasgow (UK)\n\nFirst...,2017,"May 4, 2017",News,MGN Ltd.,Glasgow (UK),...,News,1894766375,https://www.proquest.com/globalnewsfed/newspap...,2023-10-11,136.0,1.000000,"['games', 'game', 'video', 'cognitive', 'memor...","""The brain benefits may be because these activ...",0.56,"(0.4, 0.6]"
6664,"Elderly battle in a galaxy far, far away",None available.,AGED-CARE residents of the NSW North Coast hav...,Research; Older people; Aging; Dementia; Gradu...,"Daily News; Tweed Heads, N.S.W.\n\nFirst page: 3",2019,"Jul 20, 2019",NaN,Nationwide News Pty Ltd,"Tweed Heads, N.S.W.",...,News,2259711042,https://www.proquest.com/globalnewsfed/newspap...,2019-07-19,136.0,1.000000,"['games', 'game', 'video', 'cognitive', 'memor...",“It’s great to think that one day youngsters m...,0.56,"(0.4, 0.6]"
6894,High-Tech Aids Help Seniors Stay Healthy; A tw...,None available.,"COMMUNITY ASAP ""This is a mobile app that comm...",Community; Older people; Memory; Dementia; Adu...,"Leader Post; Regina, Sask.\n\nFirst page: A.3",2019,"Mar 15, 2019",City + Region,Postmedia Network Inc.,"Regina, Sask.",...,News,2191749094,https://www.proquest.com/globalnewsfed/newspap...,2019-03-16,136.0,1.000000,"['games', 'game', 'video', 'cognitive', 'memor...",Chignell also showcased the Experiential Centi...,0.56,"(0.4, 0.6]"
8011,Don’t be a stereotypical technophobe,[...]most of the senior citizens I know who ca...,"It’s no secret many ""mature Americans"" are scr...",Exercise; Internet; Physical fitness; Smartpho...,"Daily Herald; Arlington Heights, Ill.\n\nFirst...",2021,"May 24, 2021",Health Fitness,Daily Herald,"Arlington Heights, Ill.",...,News,2531277196,https://www.proquest.com/newspapers/don-t-be-s...,2021-05-24,136.0,1.000000,"['games', 'game', 'video', 'cognitive', 'memor...",Video game systems that are controlled by moti...,0.56,"(0.4, 0.6]"
9819,Boost your memory power with games: Crossword ...,None available.,"Losing keys, forgetting passwords and misplaci...",Brain; Crossword puzzles; Computer & video gam...,"The Atlanta Journal - Constitution; Atlanta, G...",2024,"Nov 3, 2024",AGING,"Atlanta Journal Constitution, LLC","Atlanta, Ga.",...,News,3123499452,https://www.proquest.com/globalnewsfed/newspap...,2024-11-03,136.0,1.000000,"['games', 'game', 'video', 'cognitive', 'memor...",“It takes my focus off my surroundings and kee...,0.56,"(0.4, 0.6]"
9856,Are video games unfairly antagonised? Study cl...,None available.,"India, Oct. 18 -- Playing video games may make...",Exercise; Computer & video games; Physical fit...,The Hindustan Times; New Delhi,2024,"Oct 18, 2024",NaN,HT Digital Streams Limited,New Delhi,...,News,3117927947,https://www.pro quest.com/globalnewsfed/newspa...,2024-10-18,136.0,1.000000,"['games', 'game', 'video', 'cognitive', 'memor...","These included puzzle games such as Minecraft,...",0.56,"(0.4, 0.6]"
9859,Video games 'make your brain younger': Regul...,None available.,PLAYING video games makes your brain younger b...,Exercise; Computer & video games; Physical fit...,The Daily Telegraph; London (UK)\n\nFirst page...,2024,"Oct 18, 2024",News,Daily Telegraph,London (UK),...,News,3117781319,https://www.proquest.com/globalnewsfed/newspap...,2024-10-18,136.0,1.000000,"['games', 'game', 'video', 'cognitive', 'memor...",Any gamer also knows that these games are desi...,0.56,"(0.4, 0.6]"
9862,Video games make your brain younger but exerci...,None available.,"’Surprising’ results show playing FIFA, Grand ...",Exercise; Computer & video games; Physical fit...,Telegraph.co.uk; London,2024,"Oct 17, 2024",News,Telegraph Media Group Holdings Limited,London,...,News,3117747269,https://www.proquest.com/globalnewsfed/newspap...,2024-10-18,136.0,1.000000,"['games', 'game', 'video', 'cognitive', 'memor...",They were also asked to estimate the average n...,0.56,"(0.4, 0.6]"

#### Topic 214

In [34]:
df[df['topic']==214]['topic_keywords'].unique()

array(["['workshops', 'ohio', 'living healthy', 'located', 'chronic health', 'workshop', 'manage', 'medical center', 'chronic conditions', 'arthritis', 'stanford', 'chronic disease', 'calling', 'score', 'confidence', 'elder', '300', 'condition', 'avenue', 'health conditions', 'options', 'metro', 'leaders', 'register', 'bureau', 'healthy living', 'class', 'managing', 'officer', 'stroke']"],
      dtype=object)

In [35]:
df[df['topic']==214]

,Title,Abstract,Full text,Subject,Publication title,Publication year,Publication date,Section,Publisher,Place of publication,...,Document type,ProQuest document ID,Document URL,Last updated,topic,topic_prob,topic_keywords,last,rel_ratio,rel_bins
131,Aging gracefully: Program that helps seniors...,"""Take Charge of your Health: Live Well, Be Wel...",CHAMPAIGN - A program that helps seniors - or ...,NaN,"News Gazette; Champaign, Ill.\n\nFirst page: A.1",2010,"Oct 16, 2010",NaN,News Gazette,"Champaign, Ill.",...,News,761077019,https://www.proquest.com/globalnewsfed/newspap...,2016-08-21,214.0,1.0,"['workshops', 'ohio', 'living healthy', 'locat...","""Seeing renewed energy, hope and confidence re...",0.533333,"(0.4, 0.6]"
1044,Edgewood Fine Arts Academy hosts free Healthy ...,"On Friday, July 29, Spanishspeaking San Antoni...","On Friday, July 29, Spanishspeaking San Antoni...",Meetings; Hispanic Americans; Health; Aging; C...,"La Prensa; San Antonio, Tex.\n\nVolume: 23\n\n...",2011,"Jul 10, 2011",NaN,La Prensa San Antonio,"San Antonio, Tex.",...,News,878898524,https://www.proquest.com/globalnewsfed/newspap...,2013-12-31,214.0,1.0,"['workshops', 'ohio', 'living healthy', 'locat...",There will be a thorough explanation of differ...,0.533333,"(0.4, 0.6]"
1047,Elder Options offers help with chronic illnesses,"""Living Healthy is a program that works,"" said...",Are you looking for ways to manage your chroni...,NaN,"Gainesville Sun; Gainesville, Fla.",2011,"Jul 7, 2011",NaN,Halifax Media Group,"Gainesville, Fla.",...,News,875247783,https://www.proquest.com/globalnewsfed/newspap...,2012-10-12,214.0,1.0,"['workshops', 'ohio', 'living healthy', 'locat...",They have experience they can share and it wor...,0.533333,"(0.4, 0.6]"
1514,PIH Health is the communities' health and well...,"Better Choices, Better Health : This evidence-...","The ""pay it forward"" concept - the idea that i...",NaN,"Whittier Daily News; Whittier, Calif.",2012,"Oct 19, 2012",News,Los Angeles Newspaper Group,"Whittier, Calif.",...,News,1113477241,https://www.proquest.com/globalnewsfed/newspap...,2012-10-20,214.0,1.0,"['workshops', 'ohio', 'living healthy', 'locat...","To learn how you can ""pay it forward,"" contact...",0.533333,"(0.4, 0.6]"
1592,St. Nicholas offers help for living with chron...,Living Well is a component of the Wisconsin In...,How do you put life back in your life when you...,Older people; Hospitals\n\nCompany / organizat...,"Press; Sheboygan, Wis.",2012,"Sep 19, 2012",Life & Style,Sheboygan Press,"Sheboygan, Wis.",...,News,1080963178,https://www.proquest.com/globalnewsfed/newspap...,2017-11-19,214.0,1.0,"['workshops', 'ohio', 'living healthy', 'locat...",Living Well is a component of the Wisconsin In...,0.533333,"(0.4, 0.6]"
2011,Find ways to live well through workshops,"Living Well might be the workshop for you, if ...",Are you an adult with an ongoing health condit...,Workshops; Aging; Patient education,"Marshfield News Herald; Marshfield, Wis.",2012,"Mar 2, 2012",MNH,"Ogden Newspapers, Inc.","Marshfield, Wis.",...,News,925776949,https://www.proquest.com/globalnewsfed/newspap...,2017-11-19,214.0,1.0,"['workshops', 'ohio', 'living healthy', 'locat...",Spring is an energizing time for renewal of li...,0.533333,"(0.4, 0.6]"
3039,Healthy U free classes kick off Oct. 9,The six-week series will run from Oct. 9 to No...,Do you have a chronic health condition like di...,Cardiovascular disease; Diabetes\n\nCompany / ...,"Cincinnati Enquirer; Cincinnati, Ohio\n\nFirst...",2014,"Sep 18, 2014\n\ncolumn: Hyde Park",S,Gannett Media Corp,"Cincinnati, Ohio",...,News,1563040159,https://www.proquest.com/newspapers/healthy-u-...,2014-09-19,214.0,1.0,"['workshops', 'ohio', 'living healthy', 'locat...","Now, I focus on what I can do to make my life ...",0.533333,"(0.4, 0.6]"
3201,People with chronic conditions needed to share...,"So, [Ronald Jones] signed up for a free progra...","Last year, Ronald Jones decided to get some he...",NaN,"Gainesville Sun; Gainesville, Fla.",2014,"Jun 12, 2014",NaN,Halifax Media Group,"Gainesville, Fla.",...,News,1535207063,https://www.proquest.com/newspapers/people-wit...,2014-06-13,214.0,1.0,"['workshops', 'ohio', 'living healthy', 'locat...",The program and its training for volunteer ses...,0.533333,"(0.4, 0.6]"
3322,Monmouth Medical Center presents May community...,"DIABETES SELF-MANAGEMENT SERIES Fridays, May 2...",Reader Submitted SECRETS FOR SUCCESSFUL AGING ...,Hospitals; First aid; Stroke; Diabetes; Hospit...,"Asbury Park Press; Asbury Park, N.J.",2014,"Apr 17, 2014",Your News,Gannett Media Corp,"Asbury Park, N.J.",...,News,1517418470,https://www.proquest.com/newspapers/monmouth-m...,2017-11-21,214.0,1.0,"['workshops', 'ohio', 'living healthy', 'locat...","This program, for ages 50 and older, will be h...",0.533333,"(0.4, 0.6]"
3385,Healthy U offers help managing health conditions,Participants in the Healthy U program will rec...,"Healthy U, a program for residents in or near ...",Aging; Older people; Senior citizen centers\n\...,"Chillicothe Gazette; Chillicothe, Ohio",2014,"Mar 11, 2014",Local News,Gannett Media Corp,"Chillicothe, Ohio",...,News,1506354186,https://www.proquest.com/newspapers/healthy-u-...,2017-11-21,214.0,1.0,"['workshops', 'ohio', 'living healthy', 'locat...",215. Class size is limited. The deadline to re...,0.533333,"(0.4, 0.6]"
4003,"Learn to be healthier in community, online, on...",Nearly three out of four adults age 60 or olde...,COLUMBUS -- Nearly three out of four adults ag...,Aging; Chronic illnesses; Older people; Diabet...,"Lancaster Eagle - Gazette; Lancaster, Ohio\n\n...",2015,"May 17, 2015",S,Gannett Media Corp,"Lancaster, Ohio",...,News,1681274316,https://www.proquest.com/globalnewsfed/newspap...,2017-11-22,214.0,1.0,"['workshops', 'ohio', 'living healthy', 'locat...",To learn more about HEALTHY U Ohio and find a ...,0.533333,"(0.4, 0.6]"
4749,Healthy-U classes lead to better lives for tho...,None available.,If you have a chronic condition such as diabet...,Infections; Diabetes; Appointments & personnel...,"Cincinnati Enquirer; Cincinnati, Ohio\n\nFirst...",2016,"Apr 23, 2016\n\ncolumn: Area news",Hometown,Gannett Media Corp,"Cincinnati, Ohio",...,News,1993369559,https://www.proquest.com/globalnewsfed/newspap...,2018-05-04,214.0,1.0,"['workshops', 'ohio', 'living healthy', 'locat...","With the sharing of needles, there is a fear t...",0.533333,"(0.4, 0.6]"
5199,Carroll aging bureau workshop to address livin...,"The series of workshops beginning Thursday, Se...",Around 80 percent of older adults experience s...,Community centers; Arthritis; Workshops; Aging...,"Carroll County Times; Westminster, Md.",2017,"Sep 12, 2017",News/health,"Tribune Publishing Company, LLC","Westminster, Md.",...,News,1938107266,https://www.proquest.com/globalnewsfed/newspap...,2017-09-13,214.0,1.0,"['workshops', 'ohio', 'living healthy', 'locat...","If you go What: Living Healthy, Living Well wo...",0.533333,"(0.4, 0.6]"
5993,FDL County to host workshop on chronic health,None available.,FOND DU LAC - A managing chronic health condit...,Chronic illnesses\n\nLocation: Wisconsin\n\nCo...,"The Reporter; Fond du Lac, Wis.\n\nFirst page:...",2018,"Jun 27, 2018",News,Gannett Media Corp,"Fond du Lac, Wis.",...,News,2062331994,https://www.proquest.com/globalnewsfed/newspap...,2018-07-01,214.0,1.0,"['workshops', 'ohio', 'living healthy', 'locat...",These high-level evidenced-based programs are ...,0.533333,"(0.4, 0.6]"
6534,Free chronic conditions workshop on living hea...,None available.,It’s not too late to join the Carroll County B...,Workshops; Aging; Chronic illnesses,"Carroll County Times; Westminster, Md.",2019,"Sep 17, 2019",Maryland - Carroll - News,"Tribune Publishing Company, LLC","Westminster, Md.",...,News,2377664409,https://www.proquest.com/globalnewsfed/newspap...,2020-03-17,214.0,1.0,"['workshops', 'ohio', 'living healthy', 'locat...",That series will be held from 9 a.m. to 11:30 ...,0.533333,"(0.4, 0.6]"

### Topic rel_ratio 0.6 - 0.8

In [36]:
df[(df["rel_ratio"] > 0.6) & (df["rel_ratio"] <= 0.8)]['topic'].unique()

array([104.,  97.,  54.,  72.,  26., 177., 178.,  17.,  48., 134.,  67.,
       210., 147.,  20., 118.,   0., 113.,   9., 115.,  47., 188., 201.,
        28., 151., 108., 212., 141.,  30., 164., 122., 140., 174., 219.,
        83.,  81., 216., 217.,  82.,  74., 123., 121.,  12., 160.,  45.,
        70.,  33.,  59., 131.,  62., 222.,   6.,  85., 155., 198., 125.,
       199., 126., 120., 181., 135., 152.])

In [37]:
subset = df[(df["rel_ratio"] > 0.6) & (df["rel_ratio"] <= 0.8)]
for topic, keywords in subset.groupby('topic')['topic_keywords'].unique().items():
    print(topic, "\n", keywords)

0.0
 ["['skin', 'hair', 'beauty', 'products', 'cream', 'face', 'lines', 'antiaging', 'vitamin', 'ingredients', 'appearance', 'sun', 'antiageing', 'product', 'natural', 'oil', 'youthful', 'treatments', 'damage', 'acid', 'fine', 'antioxidants', 'signs', 'makeup', 'production', 'water', 'pounds', 'contains', 'spots', 'dry']"]
6.0
 ["['singapore', 'mr', 'programmes', 'programme', 'ageing population', 'cent', 'retirement', 'silver', 'ms', 'government', 'generation', 'residents', 'life expectancy', 'expectancy', 'minister', 'prof', 'workers', 'savings', 'financial', 'ministry', 'costs', 'centres', '2030', 'employees', 'lee', 'encourage', 'aged 65', 'workforce', 'managing', 'retirement age']"]
9.0
 ["['alzheimers', 'alzheimers disease', 'memory', 'cognitive', 'diagnosis', 'symptoms', 'alzheimers association', 'brains', 'memory loss', 'tests', 'decline', 'clinical', 'brain health', 'impairment', 'test', 'progression', 'healthy brain', 'cognitive impairment', 'risk factors', 'mild', 'risk dementia', 'testing', 'medications', 'diagnosed', 'cure', 'slow', 'cognition', 'cases', 'function', 'trials']"]
12.0
 ["['fatty', 'fish', 'acids', 'foods', 'vegetables', 'mediterranean', 'olive oil', 'cognitive', 'nuts', 'brain health', 'olive', 'oil', 'alzheimers', 'serving', 'eating', 'fats', 'diets', 'fruit', 'function', 'dietary', 'ate', 'nutrients', 'alzheimers disease', 'brain function', 'cognitive decline', 'meat', 'grains', 'fruits', 'memory', 'salmon']"]
17.0
 ["['genetic', 'genes', 'centenarians', 'longevity', 'dna', 'exceptional', 'gene', 'genetics', 'scientists', 'long life', 'boston', 'super', 'mr', 'predict', 'lived', 'samples', 'oldest', '110', 'died', 'rare', 'test', '90', 'testing', 'heart disease', '150', 'thomas', 'identify', 'people live', 'markers', 'born']"]
20.0
 ["['pm', 'wednesday', 'st', 'monday', 'thursday', 'bridge', 'club', 'tuesday', 'ave', 'friday', 'thursdays', 'river', 'tuesdays', '130', 'church', 'noon', 'fridays', 'mondays', '1130', 'wednesdays', '55', 'rd', 'register', 'lunch', 'support group', 'dance', 'sept', 'dancing', 'afternoon', 'floor']"]
26.0
 ["['ireland', 'residential', 'cent', 'ageing population', 'beds', 'nhs', 'wales', 'life expectancy', 'expectancy', 'government', 'older population', 'pensioners', 'burden', 'aged 65', 'retirement', 'pension', 'uk', 'rise', 'irish', 'peoples', 'ageism', 'living longer', 'economic', 'people living', 'tax', 'contribution', 'health social', 'figures', 'strategy', 'policies']"]
28.0
 ["['expo', 'fair', 'speakers', 'tables', 'talks', 'takes place', 'ontario', 'topics', 'healthy living', 'abuse', 'feature', 'arts', 'organizations', 'programs services', 'pm', 'presentations', 'businesses', 'active aging', 'hall', 'prizes', 'annual', 'community health', 'hosting', 'workshops', 'hill', 'presented', 'st', 'older adult', 'resource', 'hosted']"]
30.0
 ["['retirement', 'retire', 'job', 'financial', 'social security', 'boomers', 'security', 'workers', 'career', 'retirees', 'pension', 'life expectancy', 'expectancy', 'careers', 'retirement age', 'savings', 'survey', 'age 65', 'business', 'jobs', 'money', 'longevity', 'expect', 'economic', 'economy', 'reasons', 'employees', 'youre', 'baby boomers', 'workplace']"]
33.0
 ["['older persons', 'countries', 'asia', 'japan', 'region', 'pension', 'policies', 'economic', 'demographic', 'workers', '2050', 'productivity', 'proportion', 'systems', 'policy', 'labour', 'growth', 'societies', 'rights', 'projected', 'force', 'pacific', 'inclusive', 'economy', 'rapidly', 'populations', 'rapid', 'income', 'percent', 'china']"]
45.0
 ["['travel', 'massage', 'wellness', 'hotel', 'treatments', 'guests', 'meditation', 'yoga', 'holiday', 'experiences', 'aarp', 'sea', 'holistic', 'relaxation', 'beauty', 'beach', 'rooms', 'water', 'pounds', 'visitors', 'holidays', 'nights', 'trip', 'programme', 'lake', 'fitness', 'list', 'health wellness', 'trend', 'bodys']"]
47.0
 ["['china', 'cooperation', 'countries', 'economic', 'chinese', 'growth', 'economy', 'policy', 'global', 'rates', 'japan', 'demographic', 'populations', 'policies', 'rural', 'percent', 'productivity', 'foreign', 'life expectancy', 'expectancy', 'innovation', 'billion', 'welcomed', 'trade', 'fiveyear', 'peoples', 'countrys', 'noted', 'decline', 'sustainable']"]
48.0
 ["['dogs', 'dog', 'owners', 'humans', 'drug', 'animal', 'dear', 'henry', 'hes', 'behavior', 'animals', 'house', 'drugs', 'kidney', 'trial', 'feature', 'scientists', 'life span', 'washington', 'gone', 'span', 'eyes', 'eye', 'night', 'dry', 'owner', 'died', 'root', 'web', 'matt']"]
54.0
 ["['caregivers', 'caregiving', 'caregiver', 'parents', 'caring', 'loved', 'georgia', 'mother', 'grandparents', 'nursing', 'loved ones', 'kelly', 'aarp', 'families', 'states', 'adult', 'nursing home', 'family members', 'mom', 'agency', 'son', 'relative', 'relatives', 'father', 'parent', 'fulltime', 'house', 'ask', 'assistance', 'home care']"]
59.0
 ["['physical activity', 'cognitive', 'memory', 'cognition', 'risk dementia', 'fitness', 'brains', 'walking', 'cognitive decline', 'decline', 'speed', 'midlife', 'aerobic', 'brain health', 'moderate', 'physical exercise', 'intensive', 'alzheimers', 'function', 'physically active', 'lead author', 'alzheimers disease', 'cognitive impairment', 'impairment', 'suggests', 'thinking', 'published', 'physically', 'leg', 'journal']"]
62.0
 ["['cells', 'cell', 'tissues', 'drugs', 'mayo', 'drug', 'stem', 'agerelated', 'bone', 'damage', 'lifespan', 'scientists', 'trial', 'effects', 'immune', 'fat', 'tissue', 'humans', 'inflammation', 'normal', 'agerelated diseases', 'clear', 'trials', 'van', 'kill', 'eliminate', 'cellular', 'reverse', 'function', 'boys']"]
67.0
 ["['sex', 'sexual', 'partner', 'percent', 'heart attack', 'relationship', 'attack', 'revealed', 'desire', 'love', '45', 'boomers', 'survey', 'menopause', '60s', 'reported', 'men women', 'yes', 'book', 'partners', 'cases', 'cardiovascular', 'doctor', 'numbers', 'satisfaction', 'pleasure', 'percentage', 'aarp', 'age group', 'relationships']"]
70.0
 ["['memory', 'cognitive', 'brains', 'task', 'alzheimers', 'remember', 'memories', 'decline', 'rest', 'words', 'suggests', 'differences', 'tasks', 'tests', 'processing', 'normal', 'visual', 'thinking', 'ani', 'impairment', 'details', 'processes', 'patterns', 'stimulation', 'connections', 'published', 'function', 'alzheimers disease', 'abilities', 'affected']"]
72.0
 ["['cells', 'cell', 'dna', 'genes', 'gene', 'cellular', 'length', 'proteins', 'damage', 'lifespan', 'reverse', 'scientists', 'genetic', 'mechanisms', 'function', 'humans', 'ends', 'inflammation', 'biological', 'oxygen', 'shorter', 'ageing process', 'stop', 'discovered', 'agerelated', 'immune', 'animals', 'antiaging', 'organs', 'drugs']"]
74.0
 ["['atlanta', 'county', 'census', 'summit', 'centers', 'communities', 'rates', 'file', 'states', 'housing', 'worst', 'indicators', 'massachusetts', 'percent', 'georgia', 'ohio', 'residents', 'funding', 'senior center', 'transportation', 'count', 'policy', 'nurse', 'ranked', 'council aging', 'council', 'hill', 'award', 'tax', 'leadership']"]
81.0
 ["['running', 'rice', 'ran', 'pace', 'records', 'performance', 'finish', 'runs', 'masters', 'race', 'distance', 'track', 'minutes', 'muscle', 'physiology', 'seconds', 'train', 'fit', 'muscles', 'impressive', 'age group', 'record', 'shes', 'competitive', 'fitness', 'won', 'van', 'legs', 'competition', 'sports']"]
82.0
 ["['negative', 'thoughts', 'anxiety', 'attitudes', 'happy', 'attitude', 'feelings', 'messages', 'feeling', 'later life', 'sense', 'reality', 'happiness', 'chose', 'getting older', 'values', 'gains', 'laugh', 'psychology', 'arise', 'assume', 'centenarians', 'mindset', 'purpose', 'loved', 'emotional', 'friends family', 'moment', 'accept', 'psychological']"]
83.0
 ["['cognitive', 'memory', 'brain health', 'alzheimers', 'brains', 'cognitive decline', 'sleep', 'memory loss', 'risk dementia', 'decline', 'alzheimers disease', 'learn new', 'blood pressure', 'aerobic', 'language', 'evidence', 'sharp', 'impairment', 'remember', 'physical activity', 'healthy brain', 'stimulate', 'high blood', 'function', 'reserve', 'risk developing', 'cognition', 'trials', 'head', 'delay']"]
85.0
 ["['cities', 'agefriendly', 'app', 'outdoor', 'gym', 'pounds', 'australians', 'card', 'smart', 'innovation', 'deliver', 'customers', 'uk', 'bike', 'tennis', 'health insurance', 'healthy ageing', 'communities', 'organisations', 'insurance', 'plans', 'housing', 'youth', 'urban', 'programmes', 'delivery', 'park', 'delivered', 'private', 'volunteering']"]
97.0
 ["['united', 'award', 'campaign', 'valley', 'ymca', 'county', 'board', 'volunteers', 'transportation', 'volunteer', 'rides', 'agencies', 'nonprofit', 'business', 'schools', 'raised', 'awards', 'president', 'funding', 'champion', 'fundraising', 'percent', 'air', 'organizations', 'students', 'rural', 'money', 'ride', 'contributions', 'presented']"]
104.0
 ["['muscle', 'muscles', 'muscle mass', 'mass', 'tissue', 'sedentary', 'cells', 'proteins', 'lifelong', 'aerobic', 'gene', 'strength', 'humans', 'stem', 'function', 'resistance', 'fat', 'journal', 'cell', 'times week', 'capacity', 'endurance', 'metabolism', 'effects', 'agerelated', 'stronger', 'running', 'ani', 'moderate', 'different types']"]
108.0
 ["['games', 'class', '55', 'ohio', 'senior center', '55 older', 'classes', 'church', 'county', 'sept', 'agency', 'club', 'membership', 'fee', 'safety', 'centers', 'hosted', 'date', 'recreation', 'adult', 'atlanta', 'road', 'students', 'thursdays', 'wellness', 'facility', 'veterans', 'tuesdays', 'location', 'programming']"]
113.0
 ["['classes', 'fair', 'class', 'mondays', 'pm', 'yoga', 'tuesdays', 'wednesdays', 'thursdays', 'fridays', 'ave', 'support group', 'dance', 'games', 'march', 'meditation', 'registration', 'meets', 'medical center', 'screenings', 'instructor', '630', 'regional', 'room', 'wellness', 'monday', 'fitness', 'tuesday', 'park', 'tai']"]
115.0
 ["['fitness', 'silver', 'walk', 'ymca', 'walking', 'classes', 'fit', 'walks', 'class', 'moving', 'jersey', 'friday', 'students', 'wellness', 'equipment', 'black', 'county', 'clinic', 'offered', 'balance', 'centers', 'physical activity', 'howard', 'locations', 'active aging', 'valley', 'join', 'instructor', 'breathing', 'residents']"]
118.0
 ["['driving', 'drivers', 'car', 'driver', 'safety', 'vehicle', 'cars', 'traffic', 'drive', 'transportation', 'seat', 'road', 'vision', 'aarp', 'keys', 'safer', 'skills', 'stop', 'head', 'atlanta', 'miles', 'occupational', 'mobility', 'independence', 'tests', 'trouble', 'georgia', '65 older', 'rock', 'medications']"]
120.0
 ["['diets', 'calories', 'animals', 'intake', 'lifespan', 'weight', 'trial', 'effects', 'metabolic', 'prolonged', 'national institute', 'reduced', 'institute aging', 'eating', 'humans', 'extend', 'effect', 'life span', 'laboratory', 'reduction', 'immune', 'live longer', 'weight loss', 'new study', 'allowed', 'scientists', 'old age', 'eat', 'ate', 'span']"]
121.0
 ["['centenarians', 'birthday', 'born', 'census', 'percent', 'lived', '100 years', 'boomers', 'oldest', 'married', 'wife', 'century', '2010', 'secret', 'reaching', 'baby boomers', 'baby', 'survive', 'survey', 'sister', 'party', 'celebrating', 'died', 'moved', 'world war', 'war', 'long life', 'daughter', 'mother', 'longevity']"]
122.0
 ["['sustainable', 'protection', 'countries', 'policies', 'asia', 'gender', 'rights', 'pacific', 'economic', 'poverty', 'demographic', 'climate', 'action', 'region', 'global', 'girls', 'womens', 'agenda', 'conference', 'trends', 'growth', 'united nations', 'gaps', 'cooperation', 'anniversary', 'promoting', 'nations', 'workers', 'employment', 'universal']"]
123.0
 ["['fish', 'fatty', 'acids', 'oil', 'acid', 'salmon', 'fats', 'liver', 'olive', 'fat', 'heart disease', 'olive oil', 'consumption', 'supplements', 'disease cancer', 'lower risk', 'cholesterol', 'dietary', 'beneficial', 'journal', 'contains', 'consumed', 'ate', 'minerals', 'inflammation', 'eat', 'unhealthy', 'properties', 'intake', 'healthy ageing']"]
125.0
 ["['life expectancy', 'expectancy', 'healthy life', 'countries', 'expect', 'good health', 'gap', 'figures', 'men women', 'born', 'lowest', 'statistics', 'average life', 'compared', 'gender', 'poor health', 'male', '84', 'number years', 'percentage', 'poor', '2030', 'uk', 'female', 'ireland', 'europe', 'recorded', 'indicators', 'birth', '2010']"]
126.0
 ["['length', 'dna', 'shorter', 'cellular', 'ends', 'lifestyle changes', 'cells', 'biological', 'endurance', 'cell', 'findings', 'genes', 'score', 'short', 'effects', 'intensity', 'plastic', 'points', 'processed', 'grains', 'protect', 'slow', 'test', 'zero', 'genetic', 'resistance', 'obesity', 'combining', 'premature', 'controlled']"]
131.0
 ["['alzheimers', 'alzheimers disease', 'brains', 'inflammation', 'models', 'rest', 'cognitive', 'memory', 'syndrome', 'decline', 'cognitive decline', 'memory loss', 'animal', 'drug', 'patterns', 'normal', 'damage', 'model', 'response', 'discovery', 'mechanism', 'pace', 'proteins', 'advanced', 'effects', 'therapies', 'identify', 'scientists', 'ani', 'drugs']"]
134.0
 ["['alcohol', 'drinking', 'drink', 'moderate', 'consumption', 'wine', 'drinks', 'glass', 'units', 'good health', 'lower risk', 'dad', 'beneficial', 'cent', 'compared', 'wise', '70', 'days week', '125', 'harvard', 'guidelines', 'men women', 'successful', 'health benefits', 'effect', 'risk dementia', 'harm', 'harmful', '50s', 'evidence']"]
135.0
 ["['biological', 'chronological', 'dna', 'faster', 'tests', 'represents', 'markers', 'clock', 'test', '38', 'measured', 'liver', 'measure', 'says dr', 'scientists', 'accelerated', 'cent', 'fast', 'premature', 'lung', 'cells', 'young adults', 'ageing process', 'habits', 'genetic', 'cholesterol', 'walking', 'agerelated', 'cellular', 'alcohol']"]
140.0
 ["['healthy eating', 'eating', 'dietitian', 'cooking', 'march', 'foods', 'garden', 'bus', 'vegetables', 'valley', 'eat', 'cook', 'agency', 'fruits', 'registered', 'nutritional', 'kitchen', 'eating healthy', 'lunch', 'fresh', 'recipes', 'eat healthy', 'nutritious', 'fats', 'seminars', 'concern', 'fruits vegetables', 'discussion', 'grocery', 'meal']"]
141.0
 ["['veterans', 'frank', 'parents', 'parent', 'advance', 'decisions', 'johnson', 'miss', 'surgery', 'suicide', 'hospice', 'toronto', 'war', 'doctors', 'palliative', 'father', 'conversations', 'combat', 'martin', 'didnt', 'cafe', 'loved ones', 'conversation', 'dying', 'loved', 'relationships', 'emotional', 'struggling', 'im', 'die']"]
147.0
 ["['gardening', 'garden', 'gardens', 'plants', 'extension', 'trees', 'cognitive', 'nature', 'traffic', 'students', 'brain health', 'awards', 'vegetables', 'fresh', 'tree', 'beds', 'raised', 'blue', 'county', 'therapeutic', 'plant', 'function', 'safety', 'hundreds', 'award', 'residents', 'lifestyles', 'brain function', 'rarely', '79']"]
151.0
 ["['farmers', 'volunteers', 'market', 'victoria', 'volunteer', 'farm', 'county', 'markets', 'email', 'store', 'mountain', 'award', 'lake', 'produce', 'business', 'summer', 'salt', 'shifts', 'mobile', 'pm', 'united', 'fresh', '2012', 'st', 'flexible', 'agriculture', 'agencies', 'assistance', 'computer', 'bus']"]
152.0
 ["['race', 'swimming', 'masters', 'tour', 'finish', 'martin', 'netherlands', 'grace', 'champion', 'ms', 'dog', 'win', 'cycling', 'season', 'competition', 'jump', 'stage', 'won', 'record', 'endurance', 'riding', 'records', 'lee', 'war', 'jones', 'running', 'couple', 'definitely', 'town', 'britain']"]
155.0
 ["['language', 'cognitive', 'brains', 'matter', 'memory', 'thinking', 'advantages', 'brain health', 'later life', 'evidence', 'onset', 'delay', 'child', 'leisure', 'skills', 'alzheimers', 'function', 'white', 'games', 'cognition', 'writing', 'healthy brain', 'english', 'terms', 'tests', 'task', 'wrong', 'trial', 'reading', 'alzheimers disease']"]
160.0
 ["['drugs', 'cell', 'cells', 'lifespan', 'biological', 'scientists', 'extend', 'biology', 'longevity', 'drug', 'trials', 'slow', 'people live', 'division', 'inflammation', 'agerelated', 'ageing process', 'gene', 'genes', 'length', 'live longer', 'heart disease', 'trying', 'decades', 'die', 'panel', 'animals', 'dna', 'getting older', 'immune']"]
164.0
 ["['home care', 'canada', 'canadians', 'census', 'ontario', 'province', 'government', 'act', 'caregiver', 'longterm care', 'housing', 'caregivers', 'homes', 'agefriendly', 'boomers', 'transformation', 'long possible', 'english', 'cent', 'money', 'health social', 'toronto', 'bc', 'minister', 'star', 'social services', 'retire', 'recognition', 'costs', 'income']"]
174.0
 ["['pm', 'st', 'tuesday', 'tickets', 'ave', 'friday', 'dance', 'rd', 'sept', 'monday', 'club', 'theatre', 'victoria', 'wednesday', '830', 'details', 'howard', '730', 'register', 'donation', 'lunch', 'band', 'columbia', 'music', 'saturday', 'thursday', 'april', 'tuesdays', 'nov', 'weekly']"]
177.0
 ["['productivity', 'australia', 'political', 'housing', 'labour', 'commission', 'policy', 'communities', 'economy', 'growth', 'skilled', 'failed', 'sector', 'rise', 'cent', 'primary', 'participation', 'australian', 'mr', 'secretary', 'economic', 'government', 'deliver', 'crisis', 'nhs', 'nurses', 'december', 'nation', 'provision', 'capital']"]
178.0
 ["['competition', 'room', 'photos', 'entry', '2011', '45', 'act', 'photo', 'images', 'students', 'phone', 'lifes', 'image', 'festival', 'secondary', 'miller', 'helen', 'selected', 'relationships', 'celebrate', 'agefriendly', 'enlarge image', 'enlarge', 'october', 'shes', 'february', 'primary', 'favourite', 'promotes', 'towns']"]
181.0
 ["['negative', 'emotions', 'happiness', 'attitudes', 'getting older', 'mindset', 'martin', 'emotional', 'psychology', 'happy', 'feelings', 'old age', 'sense', 'views', 'positively', 'kim', 'game', 'behaviors', 'lived', 'goals', 'authors', 'younger people', 'live longer', 'depression', 'maybe', 'specializes', 'behavioral', 'longevity', 'suggests', 'aspects']"]
188.0
 ["['foot', 'feet', 'shoes', 'cream', 'steps', 'mobility', 'walking', 'leg', 'wear', 'falls', 'pain', 'balance', 'ms', 'walk', 'buy', 'muscles', 'skin', 'arthritis', '5000', 'impairment', 'file', 'dry', 'upper', 'fix', 'strength', 'surgery', 'cognitive impairment', 'rule', 'function', 'symptoms']"]
198.0
 ["['dental', 'oral', 'teeth', 'mouth', 'illinois', 'nursing', 'nursing home', 'dry', 'smile', 'nursing homes', 'pain', 'overall health', 'poor', 'broken', 'tobacco', 'cleaning', 'residents', 'bank', 'coverage', 'infections', 'states', 'caused', 'infection', 'homes', 'routine', 'severe', 'properly', 'coffee', 'visits', 'checkups']"]
199.0
 ["['innovation', 'nhs', 'ireland', 'business', 'digital', 'technology', 'uk', 'european', 'wales', 'healthy ageing', 'businesses', 'active healthy', 'deliver', 'technologies', 'gp', 'competition', 'northern', 'programme', 'card', 'prof', 'reference', 'bond', 'investment', 'products', 'preventable', 'market', 'providers', 'private', 'companies', 'recognised']"]
201.0
 ["['expo', 'successful aging', 'coalition', 'screenings', 'speaker', 'health screenings', 'class', 'presentation', 'nancy', 'medicare', 'successful', 'sale', 'caregiving', 'book', 'guest', '1130', 'columnist', 'oct', 'alzheimers', 'fun', 'festival', 'pm', 'preventive', 'wellness', 'fundraising', 'offered', 'club', 'dec', 'older americans', 'fitness']"]
210.0
 ["['labour', 'workers', 'pension', 'participation', 'retirement', 'retirement age', 'employers', 'employment', 'wealth', 'countries', 'force', 'market', 'employees', '2000', 'net', 'rising', 'sustainable', 'workforce', 'rise', 'talent', 'supply', 'retire', 'financial', 'age group', 'tax', 'flexible', 'job', 'temporary', 'developments', 'percentage']"]
212.0
 ["['books', 'james', 'novel', 'michael', 'book', 'secrets', 'lisa', 'mary', 'charles', 'jane', 'tim', 'david', 'britain', 'paul', 'rose', 'library', 'love', 'april', 'elizabeth', 'girl', 'daughter', 'susan', 'wife', 'hunger', 'karen', '81', 'edge', 'peter', 'joseph', 'john']"]
216.0

#### Topic 6

In [38]:
df[df['topic']==6]

,Title,Abstract,Full text,Subject,Publication title,Publication year,Publication date,Section,Publisher,Place of publication,...,Document type,ProQuest document ID,Document URL,Last updated,topic,topic_prob,topic_keywords,last,rel_ratio,rel_bins
747,Govt to shoulder larger burden of medical care...,HEALTH-CARE spending will go up as Singapore a...,HEALTH-CARE spending will go up as Singapore a...,Older people; Hospitals; Health care expenditu...,The Straits Times; Singapore,2011,"Nov 4, 2011",Prime News,SPH Media Limited,Singapore,...,News,902138110,https://www.proquest.com/globalnewsfed/newspap...,2011-11-04,6.0,0.475679,"['singapore', 'mr', 'programmes', 'programme',...",It is not extra-curricular activity. It's part...,0.785124,"(0.6, 0.8]"
802,Aid schemes for those unable to afford nominal...,The Health Promotion Board (HPB) launched the ...,We would like to thank Mrs Lillian Lee for her...,Medical screening,The Straits Times; Singapore,2011,"Oct 16, 2011",Think,SPH Media Limited,Singapore,...,News,898466502,https://www.proquest.com/globalnewsfed/newspap...,2011-10-16,6.0,0.020079,"['singapore', 'mr', 'programmes', 'programme',...","Nevertheless, we believe that, by co-paying fo...",0.785124,"(0.6, 0.8]"
1196,Help for the elderly before they need it: Pl...,"The Tsao Foundation, a non-profit organisation...",MANY elderly people have physical and mental h...,Older people; Health care; Aging; Health servi...,The Straits Times; Singapore,2011,"Apr 16, 2011",Saturday Special Report,SPH Media Limited,Singapore,...,Feature,862133995,https://www.proquest.com/globalnewsfed/newspap...,2011-07-22,6.0,0.321205,"['singapore', 'mr', 'programmes', 'programme',...",So this project will look at issues such as ho...,0.785124,"(0.6, 0.8]"
1197,Ageing with grace: Research is gearing up he...,[...] research is moving away from this model ...,SINGAPORE'S top minds are rallying to tackle a...,Aging; Quality of life; Older people\n\nCompan...,The Straits Times; Singapore,2011,"Apr 16, 2011\n\ncolumn: country for old men",Saturday Special Report,SPH Media Limited,Singapore,...,Feature,862133975,https://www.proquest.com/globalnewsfed/newspap...,2011-07-22,6.0,0.215474,"['singapore', 'mr', 'programmes', 'programme',...","'At this time, health will be the most valuabl...",0.785124,"(0.6, 0.8]"
1243,Silver lining: What are the major challenges...,In order to achieve the goal of self-sufficien...,Wong Su-Yen Senior Partner and Asean Managing ...,Older people; Society; Aging; Stereotypes; Old...,The Business Times; Singapore,2011,"Mar 21, 2011\n\ncolumn: THIS WEEK'S TOPIC",Views From The Top,SPH Media Limited,Singapore,...,News,857946989,https://www.proquest.com/globalnewsfed/newspap...,2024-12-01,6.0,0.042489,"['singapore', 'mr', 'programmes', 'programme',...",Many countries face a similar situation as the...,0.785124,"(0.6, 0.8]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10660,More synergy on the cards for schemes like Hea...,None available.,"In his second term as Health Minister, Mr Ong ...",Walking; Age; Chronic illnesses\n\nLocation: S...,The Straits Times; Singapore,2025,"Jun 2, 2025",Front Page Singapore,SPH Media Limited,Singapore,...,News,3214464016,https://www.proquest.com/globalnewsfed/newspap...,2025-06-02,6.0,0.092555,"['singapore', 'mr', 'programmes', 'programme',...",The information technology operations executiv...,0.785124,"(0.6, 0.8]"
10773,Seniors are taking the kampung spirit beyond t...,None available.,Much is being done to help seniors in Singapor...,Connectivity; Long term health care; Collabora...,The Straits Times; Singapore,2025,"Apr 26, 2025",Front Page Opinion,SPH Media Limited,Singapore,...,News,3194911867,https://www.proquest.com/globalnewsfed/newspap...,2025-04-26,6.0,0.035630,"['singapore', 'mr', 'programmes', 'programme',...",An ageing-in-networks approach allows seniors ...,0.785124,"(0.6, 0.8]"
10888,'Don't suffer in silence': Women leaders worki...,None available.,"By many measures of health, women in Singapore...",Premenstrual syndrome--PMS; Menopause; Womens ...,The Straits Times; Singapore,2025,"Mar 9, 2025",features,SPH Media Limited,Singapore,...,News,3175298753,https://www.proquest.com/globalnewsfed/newspap...,2025-03-09,6.0,0.011525,"['singapore', 'mr', 'programmes', 'programme',...",Women should take proactive steps to safeguard...,0.785124,"(0.6, 0.8]"
10942,Silver linings: Unlocking the potential streng...,None available.,SINGAPORE'S population is ageing rapidly. It i...,Population; Older workers; Older people; Life ...,The Business Times; Singapore,2025,"Feb 13, 2025\n\ncolumn: THE BOTTOM LINE",Opinion,SPH Media Limited,Singapore,...,News,3166105036,https://www.proquest.com/globalnewsfed/newspap...,2025-02-13,6.0,1.000000,"['singapore', 'mr', 'programmes', 'programme',...",Nearly one-third of older adults anticipate fi...,0.785124,"(0.6, 0.8]"
10976,Ageing in Singapore: It takes a village to sup...,None available.,With Chinese New Year celebrations in full swi...,Well being; Frailty; Older people; Geriatrics;...,The Straits Times; Singapore,2025,"Jan 31, 2025",Opinion,SPH Media Limited,Singapore,...,News,3161734137,https://www.proquest.com/globalnewsfed/newspap...,2025-01-31,6.0,0.304467,"['singapore', 'mr', 'programmes', 'programme',...",By placing this endeavour at the heart of our ...,0.785124,"(0.6, 0.8]"

#### Topic 20

In [39]:
df[df['topic']==20]

,Title,Abstract,Full text,Subject,Publication title,Publication year,Publication date,Section,Publisher,Place of publication,...,Document type,ProQuest document ID,Document URL,Last updated,topic,topic_prob,topic_keywords,last,rel_ratio,rel_bins
64,"too good to miss: For nonprofit, charity or ...",Alzheimer Society of Hamilton and Halton Care ...,All numbers are in 905 area code unless otherw...,NaN,"The Spectator; Hamilton, Ont.\n\nFirst page: G...",2010,"Nov 22, 2010",Go,"Torstar Syndication Services, a Division of To...","Hamilton, Ont.",...,News,807637429,https://www.proquest.com/globalnewsfed/newspap...,2017-11-17,20.0,1.000000,"['pm', 'wednesday', 'st', 'monday', 'thursday'...","The McQuesten's Childhood Christmas, Nov. 20, ...",0.791667,"(0.6, 0.8]"
147,COUNTY BRIEFS,None available.,"Expo Annual 50+EXPO, presented by the Howard C...",NaN,"The Baltimore Sun; Baltimore, Md.\n\nFirst pag...",2010,"Oct 10, 2010",LOCAL,"Tribune Publishing Company, LLC","Baltimore, Md.",...,News,757292946,https://www.proquest.com/globalnewsfed/newspap...,2017-11-17,20.0,0.083322,"['pm', 'wednesday', 'st', 'monday', 'thursday'...",Vendors needed Hickory Ridge Community Associa...,0.791667,"(0.6, 0.8]"
213,Access Transcona offers the following. Call 93...,"Age & Opportunity Inc. ABC's of Fraud, seldom ...",Access Transcona offers the following. Call 93...,NaN,"Winnipeg Free Press; Winnipeg, Man.\n\nFirst p...",2010,"Sep 17, 2010",NaN,FP Canadian Newspapers Limited Partnership,"Winnipeg, Man.",...,News,751110174,https://www.proquest.com/globalnewsfed/newspap...,2017-11-17,20.0,1.000000,"['pm', 'wednesday', 'st', 'monday', 'thursday'...",The study includes physical assessment of the ...,0.791667,"(0.6, 0.8]"
219,Access East offers the following. Call 938-500...,"Age & Opportunity Inc. ABC's of Fraud, seldom ...",Access East offers the following. Call 938-500...,NaN,"Winnipeg Free Press; Winnipeg, Man.",2010,"Sep 15, 2010",NaN,FP Canadian Newspapers Limited Partnership,"Winnipeg, Man.",...,News,750514928,https://www.proquest.com/globalnewsfed/newspap...,2017-11-17,20.0,1.000000,"['pm', 'wednesday', 'st', 'monday', 'thursday'...",The study includes physical assessment of the ...,0.791667,"(0.6, 0.8]"
224,Access River East offers the following. Call 9...,"Age & Opportunity Inc. ABC's of Fraud, seldom ...",Access River East offers the following. Call 9...,NaN,"Winnipeg Free Press; Winnipeg, Man.\n\nFirst p...",2010,"Sep 10, 2010",NaN,FP Canadian Newspapers Limited Partnership,"Winnipeg, Man.",...,News,750102943,https://www.proquest.com/globalnewsfed/newspap...,2017-11-17,20.0,1.000000,"['pm', 'wednesday', 'st', 'monday', 'thursday'...",The study includes physical assessment of the ...,0.791667,"(0.6, 0.8]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8683,'Combat social isolation' 5 questions with Jes...,None available.,5 QUESTIONS WITH | Jess Ray Each week The Pant...,Committees; Recreation; Blood & organ donation...,"Pantagraph; Bloomington, Ill.\n\nFirst page: A2",2022,"Jun 12, 2022",lifestyles/health-med-fit,Pantagraph Publishing Co.,"Bloomington, Ill.",...,News,2698675074,https://www.proquest.com/globalnewsfed/newspap...,2022-08-05,20.0,1.000000,"['pm', 'wednesday', 'st', 'monday', 'thursday'...",What have you done prior to this position? Bef...,0.791667,"(0.6, 0.8]"
8883,Things To Do,None available.,"Wednesday, March 9 ONLINE: Bingocize, 10-11 a....",Bible; Biblical studies; Aging,"Bangor Daily News; Bangor, Me.",2022,"Mar 7, 2022",NaN,Bangor Daily News,"Bangor, Me.",...,News,2637161192,https://www.proquest.com/globalnewsfed/newspap...,2022-03-09,20.0,0.057084,"['pm', 'wednesday', 'st', 'monday', 'thursday'...",All others need to follow the 6 foot distance....,0.791667,"(0.6, 0.8]"
9013,What's Happening,None available.,"Wednesday, Jan. 5 CARIBOU: Miss Erin's Picture...",Support groups; Public libraries; Food; Caregi...,"Bangor Daily News; Bangor, Me.",2022,"Jan 3, 2022",NaN,Bangor Daily News,"Bangor, Me.",...,News,2616368550,https://www.proquest.com/globalnewsfed/newspap...,2022-01-14,20.0,1.000000,"['pm', 'wednesday', 'st', 'monday', 'thursday'...","ONLINE: Caregiver Support Group, 12-1 p.m., ho...",0.791667,"(0.6, 0.8]"
9014,Community Calendar,None available.,"Wednesday, Jan. 5 FORT FAIRFIELD: Senior commo...",Caregivers; Aging; Commodities\n\nBusiness ind...,"Bangor Daily News; Bangor, Me.",2022,"Jan 3, 2022",NaN,Bangor Daily News,"Bangor, Me.",...,News,2616368538,https://www.proquest.com/globalnewsfed/newspap...,2022-01-14,20.0,1.000000,"['pm', 'wednesday', 'st', 'monday', 'thursday'...",Combines bingo with moderate exercise. For any...,0.791667,"(0.6, 0.8]"
9287,"Get set for live music, Oktoberfest",None available.,FOND DU LAC — Singer/songwriter Dan Rodriguez ...,Internal medicine; Diabetes; Vaccines; Opera h...,"The Reporter; Fond du Lac, Wis.\n\nFirst page:...",2023,"Oct 2, 2023\n\ncolumn: Weekly dose",News,Gannett Media Corp,"Fond du Lac, Wis.",...,News,2871351397,https://www.proquest.com/newspapers/get-set-li...,2023-10-02,20.0,0.050142,"['pm', 'wednesday', 'st', 'monday', 'thursday'...","The classes are free, but a $10 donation is re...",0.791667,"(0.6, 0.8]"

***
This topic mainly contains advertisements
***

#### Topic 28

In [40]:
df[df['topic']==28].head()

,Title,Abstract,Full text,Subject,Publication title,Publication year,Publication date,Section,Publisher,Place of publication,...,Document type,ProQuest document ID,Document URL,Last updated,topic,topic_prob,topic_keywords,last,rel_ratio,rel_bins
139,Seniors symposium puts focus on healthy aging,"""We've been lucky, we've had a lot of support ...","For almost two decades, the Seniors' Wellness ...",NaN,"Penticton Western News; Penticton, B.C.\n\nFir...",2010,"Oct 14, 2010",News,Black Press Group Ltd.,"Penticton, B.C.",...,News,758611903,https://www.proquest.com/globalnewsfed/newspap...,2010-10-16,28.0,1.000000,"['expo', 'fair', 'speakers', 'tables', 'talks'...",The Senior's Wellness Society and the South Ok...,0.783333,"(0.6, 0.8]"
142,November health meeting scheduled,Current committees are focused on child obesit...,Special to the News-Record & Sentinel The Madi...,Meetings,"Asheville Citizen - Times; Asheville, N.C.\n\n...",2010,"Oct 13, 2010",News,Gannett Media Corp,"Asheville, N.C.",...,News,1471241710,https ://www.proquest.com/globalnewsfed/newspa...,2017-11-20,28.0,0.176862,"['expo', 'fair', 'speakers', 'tables', 'talks'...",Some who can't attend meetings have contribute...,0.783333,"(0.6, 0.8]"
230,Wellness Expo set for seniors,It will showcase local organizations offering ...,You don't have to be elderly to take a day to ...,NaN,"Tribune; Guelph, Ont.\n\nFirst page: 1",2010,"Sep 9, 2010",News,"Torstar Syndication Services, a Division of To...","Guelph, Ont.",...,News,7501238 75,https://www.proquest.com/globalnewsfed/newspap...,2010-09-10,28.0,1.000000,"['expo', 'fair', 'speakers', 'tables', 'talks'...",A large number of presentations are also sched...,0.783333,"(0.6, 0.8]"
438,HEALTHY LIVING RESOURCES FOR OLDER ADULTS,Programs for older adults including caregiver ...,Visit CITIZEN-TIMES.com for a copy of the Bunc...,Aging; Older people; Swimming; Sports training...,"Asheville Citizen - Times; Asheville, N.C.",2010,"May 9, 2010",News,Gannett Media Corp,"Asheville, N.C.",...,News,275736287,https://www.proquest.com/globalnewsfed/newspap...,2017-11-06,28.0,0.244114,"['expo', 'fair', 'speakers', 'tables', 'talks'...",Register at 225-1904 or www.onecenteryoga.com....,0.783333,"(0.6, 0.8]"
504,Senior Resource Expo connects seniors with var...,"""Spread the word and encourage your friends an...","""Let's keep your walker in the closet and your...",NaN,"Oakland Tribune; Oakland, Calif.",2010,"Mar 24, 2010",My Town,Bay Area News Group,"Oakland, Calif.",...,News,352454723,https://www.proquest.com/globalnewsfed/newspap...,2011-08-24,28.0,0.118034,"['expo', 'fair', 'speakers', 'tables', 'talks'...","""Students come over for dinner with our reside...",0.783333,"(0.6, 0.8]"

***
The topic 28 is mainly about symposium and expos related to healthy aging.
***

#### Topic 48

In [41]:
df[df['topic']==48]

,Title,Abstract,Full text,Subject,Publication title,Publication year,Publication date,Section,Publisher,Place of publication,...,Document type,ProQuest document ID,Document URL,Last updated,topic,topic_prob,topic_keywords,last,rel_ratio,rel_bins
43,Walking for exercise,The problem was that [Zak] had never been arou...,We discovered walking for exercise before we r...,NaN,"The Weekly Anchor; Edson, Alta.\n\nFirst page: 6",2010,"Nov 29, 2010\n\ncolumn: A Retired Farmer's Alm...",Comment,Postmedia Network Inc.,"Edson, Alta.",...,Column,816798544,https://www.proquest.com/globalnewsfed/newspap...,2014-03-08,48.0,0.284350,"['dogs', 'dog', 'owners', 'humans', 'drug', 'a...",Being fit has really enriched our retirement. ...,0.75,"(0.6, 0.8]"
290,SCIENCE FARE,Millions of Americans with disabilities rely o...,"Upcoming science, nature and technology progra...",NaN,"The Santa Fe New Mexican; Santa Fe, N.M.\n\nFi...",2010,"Aug 7, 2010",HEALTH/SCIENCE,Santa Fe New Mexican,"Santa Fe, N.M.",...,News,742442353,https://www.proquest.com/globalnewsfed/newspap...,2017-11-17,48.0,1.000000,"['dogs', 'dog', 'owners', 'humans', 'drug', 'a...",Face Facts also will educate viewers about wha...,0.75,"(0.6, 0.8]"
502,Dogs' lives may offer answers to cancer-free l...,"Waters, head of the Gerald P. Murphy Cancer Fo...",Purdue University researcher David Waters hope...,Studies; Cancer; Bone density; Research parks;...,"Daily Record; Morristown, N.J.",2010,"Mar 23, 2010",NaN,Gannett Media Corp,"Morristown, N.J.",...,News,440206150,https://www.proquest.com/globalnewsfed/newspap...,2017-11-16,48.0,1.000000,"['dogs', 'dog', 'owners', 'humans', 'drug', 'a...",This is where the fresh ideas on cancer resear...,0.75,"(0.6, 0.8]"
686,Aging cat might have senile dementia,"Again, we had to return because his cough had ...","Dear Dr. Fox:My 18-year-old tabby, Nick, has l...",Vitamin E; Asthma; Weight control; Dementia,"The Washington Post; Washington, D.C.",2011,"Dec 8, 2011",LOCAL LIVING,WP Company LLC d/b/a The Washington Post,"Washington, D.C.",...,News,909167535,https://www.proquest.com/globalnewsfed/newspap...,2023-12-06,48.0,1.000000,"['dogs', 'dog', 'owners', 'humans', 'drug', 'a...","Michael W. Fox, author of a newsletter and boo...",0.75,"(0.6, 0.8]"
736,Aging gracefully: Tips to keep your senior d...,Keep on movin': Muscles will atrophy from lack...,Most dog owners consider their pet to be a par...,NaN,"The Spectator; Hamilton, Ont.\n\nFirst page: G.1",2011,"Nov 9, 2011",GO,"Torstar Syndication Services, a Division of To...","Hamilton, Ont.",...,News,902723296,https://www.proquest.com/globalnewsfed/newspap...,2017-11-18,48.0,1.000000,"['dogs', 'dog', 'owners', 'humans', 'drug', 'a...",This means don't let your older dog lie around...,0.75,"(0.6, 0.8]"
1338,Globe West People: Tufts veterinarians write t...,"According to Dr. Nicholas Dodman, an animal be...","OLD DOGS, NEW TIPS: Thanks to advances in medi...",Humane societies; Veterinarians; Nonfiction; V...,"Boston Globe; Boston, Mass.",2011,"Jan 23, 2011",West,"Boston Globe Media Partners, LLC","Boston, Mass.",...,News,846998980,https://www.proquest.com/globalnewsfed/newspap...,2017-11-18,48.0,1.000000,"['dogs', 'dog', 'owners', 'humans', 'drug', 'a...","That was huge."" For more information, visit ww...",0.75,"(0.6, 0.8]"
1425,Keeping cat claws off the couch,Give your dog water flavored with chicken or b...,Q. Yesterday we adopted a kitten from the Huma...,Cats; Dogs; Diet; Surgery,"Asbury Park Press; Asbury Park, N.J.\n\nFirst ...",2012,"Dec 1, 2012\n\ncolumn: ANIMAL DOCTOR",B,Gannett Media Corp,"Asbury Park, N.J.",...,News,1316685534,https://www.proquest.com/globalnewsfed/newspap...,2017-11-20,48.0,1.000000,"['dogs', 'dog', 'owners', 'humans', 'drug', 'a...","Your dog's eyes must be constantly monitored, ...",0.75,"(0.6, 0.8]"
1469,Dry corneas can lead to blindness,Any rapid blinking (blepharospasm) or rubbing ...,Dear Dr. Fox: Our 4-year-old schnauzer has had...,Cats; Eyes & eyesight,"The Washington Post; Washington, D.C.",2012,"Nov 8, 2012",LOCAL LIVING,WP Company LLC d/b/a The Washington Post,"Washington, D.C.",...,News,1140804262,https://www.proquest.com/globalnewsfed/newspap...,2017-11-19,48.0,1.000000,"['dogs', 'dog', 'owners', 'humans', 'drug', 'a...","Michael W. Fox, author of a newsletter and boo...",0.75,"(0.6, 0.8]"
1472,"Special diet, lots of water can help prevent s...",Give your dog water flavored with chicken or b...,"Question -- I have a 13-pound, 6-year-old neut...",Cats; Diet; Surgery\n\nLocation: Australia,"The Journal News; White Plains, N.Y.",2012,"Nov 6, 2012",D,Gannett Media Corp,"White Plains, N.Y.",...,News,1240417196,https://www.proquest.com/globalnewsfed/newspap...,2017-11-20,48.0,1.000000,"['dogs', 'dog', 'owners', 'humans', 'drug', 'a...","Dr. Fox, author of many books on animal care, ...",0.75,"(0.6, 0.8]"
2428,Saving the Hands That Heal: After Dog Attack...,"""I've watched my practice age as well,"" Kellog...","Lebanon - When the pit bull came charging, Sus...",NaN,"Valley News; White River Junction, Vt.",2013,"Jul 27, 2013",News,Valley News,"White River Junction, Vt.",...,News,1412885034,https://www.proquest.com/globalnewsfed/newspap...,2015-04-04,48.0,1.000000,"['dogs', 'dog', 'owners', 'humans', 'drug', 'a...",All the things I've instructed other people to...,0.75,"(0.6, 0.8]"
2588,Does owning a dog make you more active than th...,"First Person Dr Sarah Ellis, of the school of ...",Are dog owners aged 65 and over more physicall...,Dogs,Lincolnshire Echo; Lincoln (UK)\n\nFirst page: 66,2013,"May 16, 2013",News,MGN Ltd.,Lincoln (UK),...,News,1352014651,https://www.proquest.com/globalnewsfed/newspap...,2016-03-14,48.0,1.000000,"['dogs', 'dog', 'owners', 'humans', 'drug', 'a...",We are just as interested in those who do litt...,0.75,"(0.6, 0.8]"
2844,How to keep your ageing dog healthy [Pets ],None available.,"As your pet ages, he might be susceptible to s...",NaN,The Times of India; New Delhi,2014,"Dec 29, 2014",NaN,"Bennett, Coleman & Company Limited",New Delhi,...,NEWSPAPER,1640704223,https://www.proquest.com/newspapers/how-keep-y...,2014-12-29,48.0,1.000000,"['dogs', 'dog', 'owners', 'humans', 'drug', 'a...",That's why it's important to give it ample tim...,0.75,"(0.6, 0.8]"
3114,Combat aging in pets,[...]she's middle-aged. Find her on Facebook a...,I got quite a shock at the dog park the other ...,Dogs; Age; Aging; Pets; Arthritis,"The News Journal; Wilmington, Del.\n\nFirst pa...",2014,"Aug 12, 2014\n\ncolumn: wellness",E,Gannett Media Corp,"Wilmington, Del.",...,News,1552654505,https://www.proquest.com/newspapers/combat-agi...,2014-08-12,48.0,1.000000,"['dogs', 'dog', 'owners', 'humans', 'drug', 'a...","(302) 998-2281, ext. 331, delspca.org Nominati...",0.75,"(0.6, 0.8]"
3586,Stay! Mircale pill could let dogs live FOUR YE...,"The scientists add: ""We expect that as researc...",DELIGHTED dog owners have welcomed the develop...,Dogs; Aging; Studies\n\nLocation: United Kingd...,Daily Star (Online); London (UK),2015,"Dec 4, 2015",NaN,Express Newspapers PLC,London (UK),...,News,1739231423,https://www.proquest.com/globalnewsfed/newspap...,2015-12-05,48.0,1.000000,"['dogs', 'dog', 'owners', 'humans', 'drug', 'a...",GETTY MASS: Nearly a quarter of families own d...,0.75,"(0.6, 0.8]"
3587,Common drug that could add years to your dog's...,"The drug rapamycin, an anti-rejection medicine...",COMMON drugs could help increase the lifespan ...,Dogs; Aging; Pets\n\nCompany / organization: N...,The Daily Telegraph; London (UK)\n\nFirst page: 5,2015,"Dec 4, 2015",News,Daily Telegraph,London (UK),...,News,1739191080,https://www.proquest.com/globalnewsfed/newspap...,2017-11-23,48.0,0.228579,"['dogs', 'dog', 'owners', 'humans', 'drug', 'a...","""I don't think there is a set maximum longevit...",0.75,"(0.6, 0.8]"
3589,Anti-ageing dog trial could see pets live for ...,Some dogs have been known to survive until the...,Scientists have begun trialling the drug rapam...,Dogs; Rodents; Aging; Pets\n\nCompany / organi...,Telegraph.co.uk; London,2015,"Dec 3, 2015",News,Telegraph Media Group Holdings Limited,London,...,News,1738871357,https://www.proquest.com/globalnewsfed/newspap...,2015-12-04,48.0,0.244893,"['dogs', 'dog', 'owners', 'humans', 'drug', 'a...","""I don't think there is a set maximum longevit...",0.75,"(0.6, 0.8]"
3720,"Tips to help pets age gracefully, and stay hap...","""Pets are living longer and it's wonderful whe...",(BPT) - Nearly half of all American pet parent...,NaN,"St. Joseph News - Press; St. Joseph, Mo.",2015,"Oct 7, 2015",Online Features,St. Joseph News - Press,"St. Joseph, Mo.",...,Feature,1720322696,https://www.proquest.com/globalnewsfed/newspap...,2015-10-09,48.0,1.000000,"['dogs', 'dog', 'owners', 'humans', 'drug', 'a...","As you're switching your dog to a senior food,...",0.75,"(0.6, 0.8]"
4352,When your pet reaches the golden years,"Aging is not a disease. We see many fit, healt...",The golden years are that wonderful time when ...,NaN,"Alaska Highway News; Fort St. John, B.C.\n\nFi...",2016,"Nov 17, 2016\n\ncolumn: North Peace Creature F...",Community,Postmedia Network Inc.,"Fort St. John, B.C.",...,Column,1841213679,https://www.proquest.com/globalnewsfed/newspap...,2016-11-18,48.0,1.000000,"['dogs', 'dog', 'owners', 'humans', 'drug', 'a...",Remember that old age is not a disease and we ...,0.75,"(0.6, 0.8]"
4539,Five things to know about dog lifespan,None available.,"1 WILD DOGS LIVE LONGER THAN FIDO On average ,...",Dogs\n\nCompany / organization: Name: Daily Te...,The London Free Press; London\n\nFirst page: N.2,2016,"Aug 15, 2016",National Post,Postmedia Network Inc.,London,...,News,2232447164,https://www.proquest.com/globalnewsfed/newspap...,2019-05-31,48.0,1.000000,"['dogs', 'dog', 'owners', 'humans', 'drug', 'a...",But scientists have seen heart improvements . ...,0.75,"(0.6, 0.8]"
4541,Why a dog's life may soon be a lot longer: S...,"""The key findings are that there were no signi...",A MEDICAL trial to discover whether it is poss...,Dogs; Aging; Studies\n\nCompany / organization...,The Daily Telegraph; London (UK)\n\nFirst page: 7,2016,"Aug 15, 2016",News,Daily Telegraph,London (UK),...,News,1811259402,https://www.proquest.com/globalnewsfed/newspap...,2017-11-23,48.0,0.245218,"['dogs', 'dog', 'owners', 'humans', 'drug', 'a...","""We are finishing the analysis of the data for...",0.75,"(0.6, 0.8]"
4553,ASK THE VET: How can I help my dog age well?,Other signs are house-soiling and having an al...,Q: I have a wonderful poodle named Arthur who ...,NaN,"Charleston Gazette - Mail; Charleston, W.V.\n\...",2016,"Aug 4, 2016",NaN,Charleston Newspapers,"Charleston, W.V.",...,News,1808834874,https://www.proquest.com/globalnewsfed/newspap...,2017-11-23,48.0,1.000000,"['dogs', 'dog', 'owners', 'humans', 'drug', 'a...",Good luck. Send questions for Dr. Allison Dasc...,0.75,"(0.6, 0.8]"
4704,Dogs test drug aimed at humans' biggest killer...,"""I would resist the idea that we should shift ...",A treatment that lengthened the lives of labor...,NaN,International New York Times; Paris\n\nFirst p...,2016,"May 18, 2016",NaN,New York Times Company,Paris,...,News,1789280823,https://www.proquest.com/globalnewsfed/newspap...,2017-11-22,48.0,0.221623,"['dogs', 'dog', 'owners', 'humans', 'drug', 'a...","The other night, when she got home from work, ...",0.75,"(0.6, 0.8]"
4706,Dogs Test Drug Aimed at Slowing Aging Process:...,A handful of drugs tested by federally funded ...,"SEATTLE -- Ever since last summer, when Lynn G...",Biology; Aging; Clinical trials; Prescription ...,"New York Times, Late Edition (East Coast); New...",2016,"May 17, 2016\n\ncolumn: Chasing Immortality",A,New York Times Company,"New York, N.Y.",...,News,1789132163,https://www.proquest.com/globalnewsfed/newspap...,2023-10-09,48.0,0.147606,"['dogs', 'dog', 'owners', 'humans', 'drug', 'a...","; Lynn Gemmell and Her Dog, Bela, in Seattle. ...",0.75,"(0.6, 0.8]"
5081,Tips on how to care for your senior pet,Overfeeding increases the risk of cancer and v...,Due to advances in veterinary medicine and imp...,Exercise; Physical fitness; Arthritis; Food; D...,"Chronicle - Herald; Halifax, N.S.\n\nFirst pag...",2017,"Nov 9, 2017",NaN,CNW Group Ltd.,"Halifax, N.S.",...,News,1972386522,https://www.proquest.com/globalnewsfed/newspap...,2017-12-05,48.0,1.000000,"['dogs', 'dog', 'owners', 'humans', 'drug', 'a...",Regular grooming helps keep your pet's coat he...,0.75,"(0.6, 0.8]"
5418,Help your dog navigate his golden years,"Pet owners can't slow their canine's aging, bu...",Aging is inevitable. Our furry friends transit...,Dogs; Cardiovascular disease; Pain management;...,USA Today (Online); Arlington,2017,"May 6, 2017",news,"USA Today, a division of Gannett Satellite Inf...",Arlington,...,News,1895564731,https://www.proquest.com/globalnewsfed/newspap...,2017-05-07,48.0,1.000000,"['dogs', 'dog', 'owners', 'humans', 'drug', 'a...","So, as long as they feel good, and you are the...",0.75,"(0.6, 0.8]"
5769,Navigating aging with senior pets,None available.,Enlarge this image. Spunky pups and curious k...,Pain; Diabetes; Geriatrics; Cancer therapies; ...,"St. Joseph News - Press; St. Joseph, Mo.",2018,"Oct 19, 2018",Josephine,St. Joseph News - Press,"St. Joseph, Mo.",...,News,2193293283,https://www.proquest.com/g lobalnewsfed/newspa...,2019-03-18,48.0,1.000000,"['dogs', 'dog', 'owners', 'humans', 'drug', 'a...",Radiosurgery can target cancerous tissue with ...,0.75,"(0.6, 0.8]"
6010,"More food, treats aimed at keeping aging felin...",None available.,Every time I go to the pet store for supplies ...,Food; Middle age; Product development; Nutriti...,"Daily Herald; Arlington Heights, Ill.\n\nFirst...",2018,"Jun 17, 2018",Neighbor,Daily Herald,"Arlington Heights, Ill.",...,News,2056402260,https://www.proquest.com/globalnewsfed/newspap...,2018-06-18,48.0,0.218872,"['dogs', 'dog', 'owners', 'humans', 'drug', 'a...",Benji and Simba are together in senior Room Fo...,0.75,"(0.6, 0.8]"
6108,U.S. News: U.S. Watch,None available.,"IMMIGRATION Texas, Other States Sue to End DAC...",Pets; Air travel; Dogs; Medical databases; Non...,"Wall Street Journal, Eastern edition; New York...",2018,"May 2, 2018",NaN,Dow Jones & Company Inc.,"New York, N.Y.",...,News,2033181640,https://www.proquest.com/globalnewsfed/newspap...,2024-08-26,48.0,1.000000,"['dogs', 'dog', 'owners', 'humans', 'drug', 'a...",Mr. Pickett's truck plowed into a pack of bicy...,0.75,"(0.6, 0.8]"
6228,Live life well with your dog: With a NEW and...,"Redefining the ageing process EUKANUBA's new, ...",From long walks in the park to cosy cuddles on...,Pet food; Recipes; Nutrition,Daily Express; London (UK)\n\nFirst page: 30,2018,"Mar 5, 2018",News,Express Newspapers PLC,London (UK),...,News,2010277666,https://www.proquest.com/globalnewsfed/newspap...,2018-03-05,48.0,0.162644,"['dogs', 'dog', 'owners', 'humans', 'drug', 'a...",HOW DID EUKANUBA GET ITS NAME? The company's f...,0.75,"(0.6, 0.8]"
6360,United States: Dogs Might Teach Us How to Age ...,None available.,Bleak news from the Centers for Disease Contro...,Researchers; Family medical history; Age; Agin...,Asia News Monitor; Bangkok,2019,"Dec 9, 2019",General News,Thai News Service Group,Bangkok,...,News,2322487626,https://www.proquest.com/globalnewsfed/newspap...,2024-11-22,48.0,1.000000,"['dogs', 'dog', 'owners', 'humans', 'drug', 'a...",The goal here is to really keep dogs and peopl...,0.75,"(0.6, 0.8]"
7056,Old Dogs' Secrets: [Science Desk ],None available.,"Dogs go through stages in their life, just as ...",DNA methylation; Research; Scientists; Interne...,"New York Times, Late Edition (East Coast); New...",2020,"Nov 10, 2020",D,New York Times Company,"New York, N.Y.",...,News,2458848691,https://www.proquest.com/newspapers/old-dogs-s...,2020-11-10,48.0,1.000000,"['dogs', 'dog', 'owners', 'humans', 'drug', 'a...",Scientists think not. But the photos are meant...,0.75,"(0.6, 0.8]"
7664,5 Holiday Travel Tips for Pet Parents,None available.,(StatePoint) Traveling with pets over the holi...,Travel; Holidays & special occasions; Pets; Dogs,"The Times - Tribune; Scranton, Pa.",2021,"Dec 3, 2021",News,The Times-Tribune,"Scranton, Pa.",...,News,2714942040,https://www.proquest.com/newspapers/5-holiday-...,2022-09-16,48.0,0.316259,"['dogs', 'dog', 'owners', 'humans', 'drug', 'a...",If you’re unsure if your pet is fit for air tr...,0.75,"(0.6, 0.8]"
8219,Canopy Animal Health Launches SurityPro Line O...,None available.,"Canopy Animal Health, a unit of Canadian canna...",NaN,RTTNews; Williamsville,2021,"Feb 5, 2021",NaN,"ContentEngine LLC, a Florida limited liability...",Williamsville,...,News,24869 56889,https://www.proquest.com/newspapers/canopy-ani...,2021-02-14,48.0,1.000000,"['dogs', 'dog', 'owners', 'humans', 'drug', 'a...","In addition to SurityPro, Canopy Animal Health...",0.75,"(0.6, 0.8]"
8304,Will your dog have dementia?,None available.,UNITED STATES -- Around the time Dante turned ...,Cognitive ability; Age; Animal cognition; Brai...,The Straits Times; Singapore,2022,"Dec 14, 2022",living well,SPH Media Limited,Singapore,...,News,2754017078,https://www.proquest.com/globalnewsfed/newspap...,2023-10-09,48.0,0.353286,"['dogs', 'dog', 'owners', 'humans', 'drug', 'a...","""Look at your dog looking into your eyes and s...",0.75,"(0.6, 0.8]"
8564,"Rover, Too, May End Up Struggling With Dementi...",None available.,"The risk of canine cognitive dysfunction, a.k....",Veterinary medicine; Life expectancy; Cognitiv...,"New York Times, Late Edition (East Coast); New...",2022,"Aug 26, 2022",A,New York Times Company,"New York, N.Y.",...,News,2706498679,https://www.proquest.com/globalnewsfed/newspap...,2023-10-09,48.0,0.328391,"['dogs', 'dog', 'owners', 'humans', 'drug', 'a...","""This is a two-way street: Anything we're goin...",0.75,"(0.6, 0.8]"
8638,Is your pet ageing? Here are ways to take care...,None available.,"India, July 13 -- Our pets with their uncondit...",Food; Pets; Nutrition,The Hindustan Times; New Delhi,2022,"Jul 13, 2022",NaN,HT Digital Streams Limited,New Delhi,...,News,2688462585,https://www.proquest.com/globalnewsfed/newspap...,2022-07-13,48.0,1.000000,"['dogs', 'dog', 'owners', 'humans', 'drug', 'a...","Even though aging is a natural part of life, i...",0.75,"(0.6, 0.8]"
8829,A DOG’S LIFE,None available.,Researchers are looking for a medication to de...,Clinical trials; Big Data; Veterinary medicine...,The Independent (Daily Edition); London (UK)\n...,2022,"Apr 5, 2022",Section 2,Independent Digital News & Media,London (UK),...,News,2646826517,https://www.proquest.com/globalnewsfed/newspap...,2022-04-05,48.0,0.286197,"['dogs', 'dog', 'owners', 'humans', 'drug', 'a...","As a pioneer in a new field, Halioua believes ...",0.75,"(0.6, 0.8]"
8881,Could DOGS hold the answer to AGEING WELL?: ...,None available.,"FRISBEE is part German shepherd, chow chow and...",Growth factors; Laboratories; Cancer; Biomarke...,Daily Mail; London (UK)\n\nFirst page: 21,2022,"Mar 15, 2022",News,"Solo Syndication, a division of Associated New...",London (UK),...,News,2638910821,https://www.proquest.com/globalnewsfed/newspap...,2022-03-15,48.0,1.000000,"['dogs', 'dog', 'owners', 'humans', 'drug', 'a...",Dr Promislow describes the work of the Dog Agi...,0.75,"(0.6, 0.8]"
8904,United States: Dog Aging Project goal is to he...,None available.,Through the NIA-supported Dog Aging Project (D...,Clinical trials; Biomarkers; Veterinary medici...,Asia News Monitor; Bangkok,2022,"Feb 28, 2022",General News,Thai News Service Group,Bangkok,...,News,2632978885,https://www.proquest.com/globalnewsfed/newspap...,2024-11-13,48.0,1.000000,"['dogs', 'dog', 'owners', 'humans', 'drug', 'a...","Like other longitudinal studies, the success o...",0.75,"(0.6, 0.8]"

***
This topic is more about the healthy aging of pets
***

#### Topic 97

In [42]:
df[df['topic']==97]

,Title,Abstract,Full text,Subject,Publication title,Publication year,Publication date,Section,Publisher,Place of publication,...,Document type,ProQuest document ID,Document URL,Last updated,topic,topic_prob,topic_keywords,last,rel_ratio,rel_bins
10,"Meal sites, service for Tuesday canceled",The closure includes the Senior Meal sites in ...,CRIS Healthy-Aging Center is closing all Senio...,NaN,"News Gazette; Champaign, Ill.\n\nFirst page: B.3",2010,"Dec 21, 2010",NaN,News Gazette,"Champaign, Ill.",...,News,839009193,https://www.proquest. com/globalnewsfed/newspa...,2016-08-21,97.0,0.071765,"['united', 'award', 'campaign', 'valley', 'ymc...","In addition, CRIS Rural Transit is canceling a...",0.78125,"(0.6, 0.8]"
71,United Way seeks to recover shortfall,"Programs assist with rental assistance, food a...",Marshfield-Marshfield Area United Way's campai...,Savings banks\n\nCompany / organization: Name:...,"Marshfield News Herald; Marshfield, Wis.",2010,"Nov 19, 2010",MNH,"Ogden Newspapers, Inc.","Marshfield, Wis.",...,News,807414869,https://www.proquest.com/globalnewsfed/newspap...,2017-11-17,97.0,1.000000,"['united', 'award', 'campaign', 'valley', 'ymc...",Companies that increased contributions by 50 p...,0.78125,"(0.6, 0.8]"
116,'The need is great',"""We don't have enough (volunteers), either,"" s...","URBANA - Once or twice a month, Marilyn Boasti...",NaN,"News Gazette; Champaign, Ill.\n\nFirst page: A.8",2010,"Oct 24, 2010",NaN,News Gazette,"Champaign, Ill.",...,News,762486933,https://www.proquest.com/globalnewsfed/new spa...,2016-08-21,97.0,0.045488,"['united', 'award', 'campaign', 'valley', 'ymc...",Provena Faith in Action will hold two orientat...,0.78125,"(0.6, 0.8]"
154,Faith in Action program seeking more volunteers,Volunteers help people 55 and older who need h...,URBANA - Volunteers are needed to help older a...,NaN,"News Gazette; Champaign, Ill.\n\nFirst page: B.2",2010,"Oct 8, 2010",NaN,News Gazette,"Champaign, Ill.",...,News,759595128,https://www.pro quest.com/globalnewsfed/newspa...,2016-08-21,97.0,0.029714,"['united', 'award', 'campaign', 'valley', 'ymc...",The Provena Center for Healthy Aging's Faith i...,0.78125,"(0.6, 0.8]"
671,"Severn River Middle students raise $4,200 for ...","""With this $4,200, we can pay people's utiliti...",The cafeteria at Severn River Middle School fi...,NaN,Capital; Annapolis\n\nFirst page: A.7,2011,"Dec 19, 2011",NaN,"Tribune Publishing Company, LLC",Annapolis,...,News,912001793,https://www.proquest.com/globalnewsfed/newspap...,2016-10-22,97.0,0.029641,"['united', 'award', 'campaign', 'valley', 'ymc...","""Last year, we collected enough toys on the Sa...",0.78125,"(0.6, 0.8]"
769,Need greater than expected in northern Champai...,"According to [Amy Marchant], CRIS defines nort...",RANTOUL - When CRIS Rural Mass Transit Distric...,NaN,"News Gazette; Champaign, Ill.\n\nFirst page: B.1",2011,"Oct 24, 2011",NaN,News Gazette,"Champaign, Ill.",...,News,902214594,htt ps://www.proquest.com/globalnewsfed/newspa...,2016-08-21,97.0,0.105113,"['united', 'award', 'campaign', 'valley', 'ymc...",Rides within the north part of the county cost...,0.78125,"(0.6, 0.8]"
912,"2011-12 campaign sets off toward $700,000 goal","United Way officials hope to raise $700,000 th...","DANVILLE - Last year, thousands of students in...",NaN,"News Gazette; Champaign, Ill.\n\nFirst page: B.1",2011,"Sep 7, 2011",NaN,News Gazette,"Champaign, Ill.",...,News,893379657,https://www. proquest.com/globalnewsfed/newspa...,2016-08-21,97.0,1.000000,"['united', 'award', 'campaign', 'valley', 'ymc...",n Project SuccessI 21st Century Community Lear...,0.78125,"(0.6, 0.8]"
1186,Volunteers needed for Faith in Action program,Volunteers provide transportation to doctorIs ...,CHAMPAIGN - Volunteers are needed to help olde...,NaN,"News Gazette; Champaign, Ill.\n\nFirst page: B.3",2011,"Apr 22, 2011",NaN,News Gazette,"Champaign, Ill.",...,News,866956828,https://www.proq uest.com/globalnewsfed/newspa...,2016-08-21,97.0,0.025730,"['united', 'award', 'campaign', 'valley', 'ymc...",CHAMPAIGN - Volunteers are needed to help olde...,0.78125,"(0.6, 0.8]"
1310,Rural transit buses; expanding service,"""We were chosen for the contract because of ou...",CHAMPAIGN - CRIS Rural Transit will begin prov...,NaN,"News Gazette; Champaign, Ill.\n\nFirst page: B.3",2011,"Feb 12, 2011",NaN,News Gazette,"Champaign, Ill.",...,News,853819520,https://www.proques t.com/globalnewsfed/newspa...,2016-08-21,97.0,1.000000,"['united', 'award', 'campaign', 'valley', 'ymc...","Children, age 12 and younger, and accompanied ...",0.78125,"(0.6, 0.8]"
1356,United Way fails to reach goal for 2nd-straigh...,"""I would like to thank everyone involved with ...",By BLADE STAFF WRITER MONROE - For the second ...,NaN,"The Blade; Toledo, Ohio\n\nFirst page: N.5",2011,"Jan 12, 2011",Neighbors,The Blade,"Toledo, Ohio",...,News,861961536,https://www.proquest.com/globalnewsfed/newspap...,2011-04-15,97.0,1.000000,"['united', 'award', 'campaign', 'valley', 'ymc...",The funding year for those services will begin...,0.78125,"(0.6, 0.8]"
1379,Revamped planning process set to begin,"""The board suggested the recent graduates,"" Eh...",DANVILLE - Planning for Danville schools takes...,NaN,"News Gazette; Champaign, Ill.\n\nFirst page: A.1",2011,"Jan 3, 2011",NaN,News Gazette,"Champaign, Ill.",...,News,846022476,https://www.proquest .com/globalnewsfed/newspa...,2016-08-21,97.0,0.033414,"['united', 'award', 'campaign', 'valley', 'ymc...","""We feel opening the meetings up to a wide var...",0.78125,"(0.6, 0.8]"
1730,Awards will aid human services programs,The Hawaii Kai independent senior living commu...,"-- The Atherton Foundation awarded a $10,000 g...",Fund raising; Breast cancer; Innovations; Nonp...,"Honolulu Star - Advertiser; Honolulu, Hawaii",2012,"Jul 14, 2012",Hawaii News Premium,Oahu Publications Inc.,"Honolulu, Hawaii",...,News,1024851163,https://www.proquest.com/globalnewsfed/newspap...,2014-03-01,97.0,0.038158,"['united', 'award', 'campaign', 'valley', 'ymc...",-- The Office of Hawaiian Affairs awarded Heei...,0.78125,"(0.6, 0.8]"
1987,Area volunteers are recognized by United Way (...,Several community members were honored Thursda...,What was hyped with a flash mob of teens risin...,Volunteers; Students; Appointments & personnel...,"Livingston County Daily Press & Argus; Howell,...",2012,"Mar 16, 2012",NEWS,Gannett Media Corp\n\nPlaceof publication: How...,NaN,...,News,928406798,https://www.proquest.com/globalnewsfed/newspap...,2017-11-18,97.0,1.000000,"['united', 'award', 'campaign', 'valley', 'ymc...","Dawn Boss, who previously served as vice presi...",0.78125,"(0.6, 0.8]"
2623,SeniorsPlus receives award,"SeniorsPlus, the aging and disability resource...","LEWISTON -- SeniorsPlus, the aging and disabil...",NaN,"Sun Journal; Lewiston, Me.",2013,"Apr 26, 2013",Business,Sun Journal,"Lewiston, Me.",...,News,1346244023,https://www.proquest.com/globalnewsfed/newspap...,2013-04-27,97.0,0.056218,"['united', 'award', 'campaign', 'valley', 'ymc...","This year, 59 nominations were submitted. Seni...",0.78125,"(0.6, 0.8]"
2736,Para-transit boom spurs rate hike plan,DMT sought bids last year for para-transit ser...,"DANVILLE -- In the last 10 years, para-transit...",NaN,"News Gazette; Champaign, Ill.\n\nFirst page: C.1",2013,"Feb 21, 2013",NaN,News Gazette,"Champaign, Ill.",...,News,1317630341,https://www.proquest .com/globalnewsfed/newspa...,2016-08-21,97.0,1.000000,"['united', 'award', 'campaign', 'valley', 'ymc...",Total para-transit rides in Danville The follo...,0.78125,"(0.6, 0.8]"
3198,United Way awards millions to Valley nonprofit...,[...]Communities in Schools will not only cont...,Sixty-one area nonprofit agencies will share m...,Nonprofit organizations; Appointments & person...,"Morning Call; Allentown, Pa.\n\nFirst page: A.20",2014,"Jun 13, 2014",News,"Tribune Publishing Company, LLC","Allentown, Pa.",...,News,1535387242,https://www.proquest.com/newspapers/united-way...,2021-12-13,97.0,1.000000,"['united', 'award', 'campaign', 'valley', 'ymc...",The complete list of the United Way's funding ...,0.78125,"(0.6, 0.8]"
3408,Celebrating women,AN outstanding trio of women were bestowed wit...,AN outstanding trio of women were bestowed wit...,Women,"Port Lincoln Times; Port Lincoln, S. Aust.\n\n...",2014,"Mar 4, 2014",NaN,Rural Press Pty Ltd Australian Community Media...,"Port Lincoln, S. Aust.",...,News,1503658697,https://www.proquest.com/newspapers/celebratin...,2014-03-03,97.0,0.101378,"['united', 'award', 'campaign', 'valley', 'ymc...","Christine Jettner was recognised for her ""tire...",0.78125,"(0.6, 0.8]"
3682,Volunteers are the heart of Aging Matters,The Retired and Senior Volunteer Program place...,Most of us have heard about that village it ta...,Meals; Older people; Aging; Grocery stores\n\n...,"Florida Today; Melbourne, Fla.\n\nFirst page: 9",2015,"Oct 22, 2015",A,Gannett Media Corp,"Melbourne, Fla.",...,News,1725015399,https://www.proquest .com/globalnewsfed/newspa...,2017-11-22,97.0,0.027196,"['united', 'award', 'campaign', 'valley', 'ymc...",Information: 321-639-8770. The nonprofit also ...,0.78125,"(0.6, 0.8]"
3887,Champions of Health winners announced,The Tulsa-based program focuses on improving t...,TULSA (JR) - The Family & Children's Services ...,Professional baseball; Children & youth\n\nBus...,"Journal Record; Oklahoma City, Okla.",2015,"Jul 14, 2015",News,BridgeTower Media Holding Company,"Oklahoma City, Okla.",...,News,1697168167,https://www.proquest.com/globalnewsfed/newspap...,2024-11-30,97.0,0.096152,"['united', 'award', 'campaign', 'valley', 'ymc...",The Champions of Health awards program is pres...,0.78125,"(0.6, 0.8]"
4452,OLDER ADULTS: An 'Age' Of Giving Back: Leaders...,The Corporation for National and Community Ser...,When Kate Miller retired last year - after a c...,Older people; Age; Imprisonment; Baby boomers;...,"Hartford Courant; Hartford, Conn.\n\nFirst pag...",2016,"Sep 25, 2016",NaN,"Tribune Publishing Company, LLC","Hartford, Conn.",...,News,1822761659,https://www.proquest.com/globalnewsfed/newspap...,2016-09-25,97.0,0.057500,"['united', 'award', 'campaign', 'valley', 'ymc...","""Positive lifestyle choices go beyond healthy ...",0.78125,"(0.6, 0.8]"
4551,Hunterdon Medical Center employee receives award,"Registered Nurse Linda Bryant, director of Hun...","Registered Nurse Linda Bryant, director of Hun...",NaN,"Courier - News; Bridgewater, N.J.\n\nFirst pag...",2016,"Aug 7, 2016",Features,Gannett Media Corp,"Bridgewater, N.J.",...,Feature,1809412515,https://www.proquest.com/globalnewsfed/newspap...,2017-11-23,97.0,1.000000,"['united', 'award', 'campaign', 'valley', 'ymc...",She is someone I can always reach out to espec...,0.78125,"(0.6, 0.8]"
4556,C-U one of driest locales in region during July,"A decorated fighter pilot in the Korean War, r...",CHAMPAIGN -- Although rainfall was near normal...,NaN,"News Gazette; Champaign, Ill.\n\nFirst page: B.5",2016,"Aug 2, 2016",NaN,News Gazette,"Champaign, Ill.",...,News,1822610974,https://www.proquest.com/globalnewsfed/newspap...,2016-09-24,97.0,0.074308,"['united', 'award', 'campaign', 'valley', 'ymc...",Urbana school board meetings will be held on A...,0.78125,"(0.6, 0.8]"
5143,A hundred years of sharing and caring; Foremos...,None available.,The United Way of the Greater Lehigh Valley to...,Social networks; Fund raising; Students; Older...,"Morning Call; Allentown, Pa.\n\nFirst page: A.1",2017,"Oct 9, 2017",NaN,"Tribune Publishing Company, LLC","Allentown, Pa.",...,News,1948352248,https://www.proquest.com/globalnewsfed/newspap...,2017-11-24,97.0,1.000000,"['united', 'award', 'campaign', 'valley', 'ymc...",PPL Corporate Relations Specialist Janice Osbo...,0.78125,"(0.6, 0.8]"
5281,PLAYERS,None available.,STEVEN FISHER and AARON BASKERVILLE Fisher and...,Nominations; Political appointments; Sociology...,"Morning Call; Allentown, Pa.\n\nFirst page: B.2",2017,"Jul 23, 2017",NaN,"Tribune Publishing Company, LLC","Allentown, Pa.",...,News,1922263552,https://www.proquest.com/globalnewsfed/newspap...,2017-11-24,97.0,1.000000,"['united', 'award', 'campaign', 'valley', 'ymc...",Poling has been a financial adviser with Wells...,0.78125,"(0.6, 0.8]"
6028,Lehigh Valley United Way makes $13.5M investment,None available.,The United Way of the Greater Lehigh Valley is...,NaN,"Morning Call; Allentown, Pa.\n\nFirst page: A.8",2018,"Jun 7, 2018",NaN,"Tribune Publishing Company, LLC","Allentown, Pa.",...,News,2051080984,https://www.proquest.com/globalnewsfed/newspap...,2018-06-07,97.0,1.000000,"['united', 'award', 'campaign', 'valley', 'ymc...","""Since we began intentionally focusing on thes...",0.78125,"(0.6, 0.8]"
6127,United Way has; record effort; Organization re...,None available.,The United Way of the Greater Lehigh Valley ha...,Awards & honors\n\nLocation: Lehigh Valley\n\n...,"Morning Call; Allentown, Pa.\n\nFirst page: A.4",2018,"Apr 21, 2018",NaN,"Tribune Publishing Company, LLC","Allentown, Pa.",...,News,2028100768,https://www.proquest.com/globalnewsfed/newspap...,2018-08-08,97.0,1.000000,"['united', 'award', 'campaign', 'valley', 'ymc...",Trisha Higgins: Carbon County Champion Award. ...,0.78125,"(0.6, 0.8]"
6277,New West End YMCA director outlines vision for...,"After a national search, the West End YMCA boa...","As the new CEO for the West End YMCA, Damon Co...",Chief executive officers; Nonprofit organizati...,"Inland Valley Daily Bulletin; Ontario, Calif.",2018,"Jan 30, 2018",Local News,Los Angeles Newspaper Group,"Ontario, Calif.",...,News,1992237734,https://www.proquest.com/globalnewsfed/newspap...,2018-01-30,97.0,0.072588,"['united', 'award', 'campaign', 'valley', 'ymc...",Colaluca said part of the work will emphasize ...,0.78125,"(0.6, 0.8]"
6939,"YMCA hands out awards to volunteer, aging office",None available.,YMCA of Metropolitan Lansing presented two pre...,Presidents; Awards & honors; Volunteers; Aging...,"Lansing State Journal; Lansing, Mich.\n\nFirst...",2019,"Feb 17, 2019",News,Gannett Media Corp,"Lansing, Mich.",...,News,2182117718,https://www.proquest.com/globalnewsfed/newspap...,2019-02-17,97.0,1.000000,"['united', 'award', 'campaign', 'valley', 'ymc...",YMCA of Metropolitan Lansing Presenting the YM...,0.78125,"(0.6, 0.8]"
8067,Lehigh Valley United Way raises $18M million i...,None available.,Responding to the surge in community needs lai...,Coronaviruses; COVID-19\n\nLocation: Lehigh Va...,"Morning Call; Allentown, Pa.\n\nFirst page: A.22",2021,"Apr 16, 2021",NaN,"Tribune Publishing Company, LLC","Allentown, Pa.",...,News,2513035508,https://www.proquest.com/newspapers/lehigh-val...,2022-05-03,97.0,1.000000,"['united', 'award', 'campaign', 'valley', 'ymc...","Other sponsors included Dual Temp, Capital Blu...",0.78125,"(0.6, 0.8]"
8318,Local Players,None available.,Laurie Hackett United Way of the Greater Lehig...,Higher education; Appointments & personnel cha...,"Morning Call; Allentown, Pa.\n\nFirst page: A.13",2022,"Dec 8, 2022",NaN,"Tribune Publishing Company, LLC","Allentown, Pa.",...,News,274780 6697,https://www.proquest.com/globalnewsfed/newspap...,2024-07-15,97.0,1.000000,"['united', 'award', 'campaign', 'valley', 'ymc...","In his health care law practice, he counsels h...",0.78125,"(0.6, 0.8]"
8743,Company News,None available.,United Way of the Greater Lehigh Valley raises...,Small business; Girls clubs; Awards & honors; ...,"Morning Call; Allentown, Pa.\n\nFirst page: A.10",2022,"May 19, 2022",NaN,"Tribune Publishing Company, LLC","Allentown, Pa.",...,News,2666318971,https://www.proquest.com/globalnewsfed/newspap...,2022-05-19,97.0,1.000000,"['united', 'award', 'campaign', 'valley', 'ymc...",First Commonwealth first launched its Business...,0.78125,"(0.6, 0.8]"
9343,FOUR SPECIFIC GO ALS DESERVE YOUR DONATION: ...,None available.,The United Way of Dane County has set four spe...,Families & family life; Students; Poverty; Don...,"Wisconsin State Journal; Madison, Wis.\n\nFirs...",2023,"Sep 17, 2023",FORUM,"Madison Newspapers, Inc.","Madison, Wis.",...,News,2865476933,https://www.proquest.com/newspapers/four-speci...,2024-07-15,97.0,0.235104,"['united', 'award', 'campaign', 'valley', 'ymc...","(Full disclosure: Jenny Price, a member of the...",0.78125,"(0.6, 0.8]"

In [43]:
df.loc[119,'Full text']

'Sharing the belief that it\'s important for baby boomers and older adults to explore conservative measures in addition to surgical procedures when treating back pain, orthopedist John Hicks and Pardee Rehab and Wellness Center\'s manual physical therapist David Gerrer are the keynote speakers at the Thursday, Oct. 28, Great Life Series workshop, "Living Well with Your Aching Back." The lunch and learn program will be held from 11:15 a.m. to 2 p.m. in the Jamison Conference Room at Pardee Hospital. A complimentary lunch will be provided by Chef Starr to Go, and free valet parking is available at Pardee\'s front entrance off of 800 N. Justice St. "Back surgery is pretty gratifying," said Hicks of Blue Ridge Bone and Joint. "It can provide astonishing pain relief from symptoms of nerve compression such as the rip roaring pain down the leg that is triggered by nerve pressure from a bulging disc in the back." As effective as surgical procedures are, however, Hicks encourages patients not to jump into back surgery immediately. The fellowship-trained spine surgeon emphasized that people who suffer from chronic back pain often have a range of other options, including medications, steroid injections, physical therapy and rest. In the workshop, Hicks and Gerrer will explain how the spine changes as people age, what is normal and what is not normal. They will discuss the lifestyle issues that trigger back pain and how to avoid back injuries. Therapy techniques that can help patients manage and get past back pain will be shared, and special chair exercises helpful to the back will be demonstrated. In addition, they will explain the risk factors, diagnosis and treatment of common back problems. Topics will include disc disease, lumbar muscle strain, spondylolysthesis and spinal stenosis. Conditions such as lumbar spine arthritis, and osteoporosis and its related and unexpected fractures will be among other topics covered. Pain from fractures is something Gerrer understands both personally and professionally. More than 15 years ago, he broke a small bone in his back when he fell off a ladder while painting. "From my own experience recovering from that back injury, I know that manual physical therapy can offer significant conservative support in helping to identify and deal with the true cause of pain," he said. Research shows that strengthening exercises done under guidance of a physical therapist can help decrease the pain and prevent it from recurring. The Great Life Series is presented by Great Life Healthy Aging LLC in collaboration with various community partners, including Pardee Hospital, First Citizens Bank, and the Grice Ward and Surrett team of Merrill Lynch and Chef Starr to Go. Scholarships are available to individuals in need of financial assistance by calling 696-4758. Registration for the workshops and excursions is available at the Pardee Health Education Center at the Blue Ridge Mall; checks, cash or credit cards are accepted. Checks should be made payable to the Great Life Series. In addition to the Oct. 28 workshop, other events include "Hypertension, More Common Than You Think" from 10:00 a.m. to noon Nov. 6, and "Feisty and Independent ... Strategies for Living Well into Your 80s, 90s, and Beyond," which will be held on Nov. 11. An excursion by coach to Western Carolina University is planned for Dec. 5 for the "Sounds of the Season," holiday concert with dinner. Mail-in registrations can be sent to the Great Life Series, 601 Sixth Ave. W., Hendersonville, NC 28739. The cost of each workshop is $22; the dinner/theater excursion is $65 per person. Pardee Health Education Center accepts registrations. To access detailed information about the Great Life Series schedule of events and online registration, visit www.greatlifehealthyaging.com. For more information about the series, contact Marcia Caserio at 828-696-4758.  People: Hicks, John; Gerrer, David.'

***
This topic is more about volunteering for the elderly than actually about healthy ageing.
***

In [44]:
df = remove_topic(df,48,[])

The orig length:11000 -> cropped: 10952

#### Topic 113

In [45]:
df[df['topic']==113]

,Title,Abstract,Full text,Subject,Publication title,Publication year,Publication date,Section,Publisher,Place of publication,...,Document type,ProQuest document ID,Document URL,Last updated,topic,topic_prob,topic_keywords,last,rel_ratio,rel_bins
75,Eye health fair scheduled,URBANA - Provena Covenant Medical Center will ...,URBANA - Provena Covenant Medical Center will ...,NaN,"News Gazette; Champaign, Ill.\n\nFirst page: B.4",2010,"Nov 17, 2010",NaN,News Gazette,"Champaign, Ill.",...,News,815397225,https://www.proquest.com/globalnewsf ed/newspa...,2016-08-21,113.0,0.082936,"['classes', 'fair', 'class', 'mondays', 'pm', ...","There will also be information booths, refresh...",0.655172,"(0.6, 0.8]"
138,Fall Health Fair coming next week,The event is sponsored by Prowers Medical Cent...,The Healthy Aging Fall Health Fair will take p...,Senior citizen centers,"The Lamar Ledger; Lamar, Colo.",2010,"Oct 14, 2010",Health,Prairie Mountain Media,"Lamar, Colo.",...,News,918645397,https://www.proquest.com/globalnewsfed/newspap...,2012-03-19,113.0,1.000000,"['classes', 'fair', 'class', 'mondays', 'pm', ...",Those attending are recommended to have an 8-1...,0.655172,"(0.6, 0.8]"
461,Active Adults Get Results at the Senior Health...,"Workshops will include Chair Yoga, Healthy Coo...",Reader Submitted BRIDGEWATER Residents are inv...,Aging; Older people; Community centers,"Courier - News; Bridgewater, N.J.",2010,"Apr 26, 2010",GETPUBLISHED,Gannett Media Corp,"Bridgewater, N.J.",...,News,193934129,https://www.proquest.com/globalnewsfed/newspap...,2017-11-03,113.0,0.092732,"['classes', 'fair', 'class', 'mondays', 'pm', ...",Vendor demonstrations will include blood press...,0.655172,"(0.6, 0.8]"
547,Health fair,None available.,Strathcona County women will have a chance to ...,Health services\n\nIdentifier / keyword: count...,Sherwood Park News; Sherwood Park\n\nFirst pag...,2010,"Mar 2, 2010",News,Postmedia Network Inc.,Sherwood Park,...,News,2177180798,https://www.proquest.com/globalnewsfed/newspap...,2019-02-08,113.0,0.093027,"['classes', 'fair', 'class', 'mondays', 'pm', ...","Edmonton's Rejuvenation Health Services, a cer...",0.655172,"(0.6, 0.8]"
632,Health calendar: SPECIAL,"AARP DRIVER SAFETY CLASSES for those over 50, ...","""CAMP COOL,"" a two-day multimedia, interactive...",Fees & charges; Digital photography; Workshops...,"Honolulu Advertiser; Honolulu, Hawaii",2010,"Jan 14, 2010",LIFE,Gannett Media Corp,"Honolulu, Hawaii",...,News,414953309,https://www.proquest.com/globalnewsfed/newspap...,2017-11-14,113.0,1.000000,"['classes', 'fair', 'class', 'mondays', 'pm', ...",Mammograms for uninsured and underinsured wome...,0.655172,"(0.6, 0.8]"
938,Summer WHAM returns Aug. 30,The event was created and organized by a group...,"Summer WHAM, a free seniors wellness event, re...",NaN,"The Review; Richmond, B.C.\n\nFirst page: 1",2011,"Aug 25, 2011",Community,"Torstar Syndication Services, a Division of To...","Richmond, B.C.",...,News,885299446,https://www.proquest.com/globalnewsfed/newspap...,2011-08-26,113.0,0.130959,"['classes', 'fair', 'class', 'mondays', 'pm', ...","In addition, there will be 20 display tables o...",0.655172,"(0.6, 0.8]"
1010,Annual Healthy Aging Summit event Friday,None available.,"Be it the economy, lack of health insurance or...",Diabetes; Older people; Diabetic retinopathy; ...,Record Searchlight; Redding\n\nFirst page: C.2,2011,"Jul 29, 2011",Life,Gannett Media Corp,Redding,...,News,2592962173,https://www.proquest.com/globalnewsfed/newspap...,2021-11-04,113.0,0.075008,"['classes', 'fair', 'class', 'mondays', 'pm', ...",This particular exam is free to those who qual...,0.655172,"(0.6, 0.8]"
1099,Hispanic fair aims at good health: 400 atten...,[...] the last time he had a checkup was at th...,"testing, education By Joseph Gerth jgerth@cour...",Diet; Aging; Bone density; Hispanic Americans,"Courier - Journal; Louisville, Ky.",2011,"Jun 12, 2011",News,Gannett Media Corp,"Louisville, Ky.",...,News,871554550,https://www.proquest.com/globalnewsfed/newspap...,2017-11-18,113.0,1.000000,"['classes', 'fair', 'class', 'mondays', 'pm', ...",Reporter Joseph Gerth can be reached at (502) ...,0.655172,"(0.6, 0.8]"
1134,Health matters: Wellness events in the area,None available.,*National Senior Fitness Day: Healthy Aging Co...,NaN,"Daily News; Bowling Green, Ky.",2011,"May 21, 2011",NaN,Daily News,"Bowling Green, Ky.",...,News,867880884,https://www.proquest.com/globalnewsfed/newspap...,2011-08-01,113.0,1.000000,"['classes', 'fair', 'class', 'mondays', 'pm', ...",Preregistration is required. -- For more infor...,0.655172,"(0.6, 0.8]"
1209,Goldie oldies: Residents gear up for the 25t...,"""I play to have fun. They played for blood at ...","Nine years ago, a friend called Henry Thiel lo...",NaN,"Times - News; Burlington, N.C.\n\nFirst page: 29",2011,"Apr 10, 2011",Accent,Halifax Media Group,"Burlington, N.C.",...,NaN,861215353,https://www.proquest.com/globalnewsfed/newspap...,2012-10-12,113.0,1.000000,"['classes', 'fair', 'class', 'mondays', 'pm', ...","""It's the best prescription for healthy aging,...",0.655172,"(0.6, 0.8]"
1262,Cashin center to host free kidney screenings,"In honor of National Kidney Month, the Nationa...",MANCHESTER -- In honor of National Kidney Mont...,Diabetes; Kidney diseases; Blood pressure; Hos...,"The Union Leader; Manchester, N.H.\n\nFirst pa...",2011,"Mar 7, 2011",NaN,Union Leader Corporation,"Manchester, N.H.",...,News,856122525,https://www.proquest.com/globalnewsfed/newspap...,2017-11-17,113.0,1.000000,"['classes', 'fair', 'class', 'mondays', 'pm', ...",The Air Force Brass Band will perform at 1 p.m...,0.655172,"(0.6, 0.8]"
2045,Health fair and run/walk set for Saturday in PoCo,Held at Wilson Centre in the Port Coquitlam Re...,Port Coquitlam residents can explore the healt...,Yoga; Chronic illnesses; Sleep,"Coquitlam Now; New Westminster, B.C.\n\nFirst ...",2012,"Feb 15, 2012",Community,Postmedia Network Inc.,"New Westminster, B.C.",...,News,922005956,https://www.proquest.com/globalnewsfed/newspap...,2013-11-09,113.0,0.083184,"['classes', 'fair', 'class', 'mondays', 'pm', ...",. 2: 30 p.m. - The role of exercise in prevent...,0.655172,"(0.6, 0.8]"
2444,Free seniors wellness event at West Richmond A...,"""Our goal with Summer WHAM is to give seniors ...",A free seniors wellness event offering lively ...,NaN,"The Review; Richmond, B.C.\n\nFirst page: 12",2013,"Jul 19, 2013",Community,"Torstar Syndication Services, a Division of To...","Richmond, B.C.",...,News,1404739092,https://www.proquest.com/globalnewsfed/newspap...,2013-07-20,113.0,0.093232,"['classes', 'fair', 'class', 'mondays', 'pm', ...",1 Rd.) or at any community centre in Richmond....,0.655172,"(0.6, 0.8]"
2573,Free senior health fair in South Pasadena,"Elderly residents, people with aging parents a...",The South Pasadena Senior Center will have its...,NaN,"Pasadena Star - News; Pasadena, Calif.",2013,"May 21, 2013",News,Los Angeles Newspaper Group,"Pasadena, Calif.",...,News,1353660266,https://www.proquest.com/globalnewsfed/newspap...,2013-05-22,113.0,0.094032,"['classes', 'fair', 'class', 'mondays', 'pm', ...",The first 150 people who RSVP for the event wi...,0.655172,"(0.6, 0.8]"
2683,Expanding health and wellness,The usual high quality seminar schedule will a...,The premier health fair in the mid island regi...,NaN,"Parksville - Qualicum News; Parksville, B.C.\n...",2013,"Mar 21, 2013",Lifestyles,Black Press Group Ltd.,"Parksville, B.C.",...,News,1318831259,https://www.proquest.com/globalnewsfed/newspap...,2013-03-22,113.0,1.000000,"['classes', 'fair', 'class', 'mondays', 'pm', ...",Admission is free but donations will be accept...,0.655172,"(0.6, 0.8]"
2847,Senior Games/SilverArts promotes healthy aging,The kickoff event is sponsored by Gentiva Home...,Cleveland County and North Carolina Senior Gam...,Aging; Older people; Stadiums; Registration; B...,"Shelby Star; Shelby, NC",2014,"Dec 26, 2014",News,Halifax Media Group,"Shelby, NC",...,News,1640502488,https://www.proquest.com/newspapers/senior-gam...,2014-12-26,113.0,1.000000,"['classes', 'fair', 'class', 'mondays', 'pm', ...","For more information, call 704-482-3488. Entry...",0.655172,"(0.6, 0.8]"
2971,UNCA to host 4th annual wellness celebration M...,"The event, which celebrates healthful living a...",ASHEVILLE -- UNC Asheville will host its fourt...,Biofeedback,"Asheville Citizen - Times; Asheville, N.C.\n\n...",2014,"Oct 18, 2014",NaN,Gannett Media Corp,"Asheville, N.C.",...,News,1613429729,https://www.proquest.com/newspapers/unca-host-...,2017-11-21,113.0,1.000000,"['classes', 'fair', 'class', 'mondays', 'pm', ...",HAPI Lab Open House: This event will take plac...,0.655172,"(0.6, 0.8]"
3223,Hone healthy lifestyles at Smiths Falls festival,Activities on hand will include a rock climbin...,"People lunge, twist, jump and get moving along...",Festivals,"The Ottawa Citizen; Ottawa, Ont.\n\nFirst page...",2014,"May 31, 2014",Travel,Postmedia Network Inc.,"Ottawa, Ont.",...,News,1530915436,https://www.proquest.com/newspapers/hone-healt...,2017-11-21,113.0,0.057745,"['classes', 'fair', 'class', 'mondays', 'pm', ...","""It's an opportunity to try new types of fitne...",0.655172,"(0.6, 0.8]"
3373,Tuesday night mini med sessions focus on health,The 6th Annual Mini Med School starts next Tue...,The free health information offered on four co...,NaN,"The Chilliwack Progress; Chilliwack, B.C.\n\nF...",2014,"Mar 17, 2014",News,Black Press Group Ltd.,"Chilliwack, B.C.",...,News,1508160939,https://www.proquest.com/newspapers/tuesday-ni...,2014-03-18,113.0,1.000000,"['classes', 'fair', 'class', 'mondays', 'pm', ...",No registration. Free drop in. For more detail...,0.655172,"(0.6, 0.8]"
3518,Library Partnership hosting health fair,"""This year, the health fair is really differen...",After indulging in all those holiday dinners a...,NaN,"Gainesville Sun; Gainesville, Fla.",2014,"Jan 15, 2014",NaN,Halifax Media Group,"Gainesville, Fla.",...,News,1477756401,https://www.proquest.com/newspapers/library-pa...,2014-01-16,113.0,1.000000,"['classes', 'fair', 'class', 'mondays', 'pm', ...","""This event is an opportunity for the local co...",0.655172,"(0.6, 0.8]"
3943,The Boyz gear up for men's health fair at Fisk,"Heart disease, prostate cancer and access to h...","Heart disease, prostate cancer and access to h...",Men; Medicare; Aging; Chronic illnesses; Denti...,"The Tennessean; Nashville, Tenn.\n\nFirst page: 8",2015,"Jun 15, 2015",A,Gannett Media Corp,"Nashville, Tenn.",...,News,1688015186,https://www.proquest.com/globalnewsfed/newspap...,2017-11-22,113.0,1.000000,"['classes', 'fair', 'class', 'mondays', 'pm', ...",Reach Holly Fletcher at 615-259-8287 or on Twi...,0.655172,"(0.6, 0.8]"
4056,Health fair Friday in Las Cruces,Services and information provided at the event...,LAS CRUCES The New Mexico Office of Border Hea...,NaN,"Las Cruces Sun - News; Las Cruces, N.M.",2015,"Apr 20, 2015",News,Gannett Media Corp,"Las Cruces, N.M.",...,News,1674478357,https://www.proquest.com/globalnewsfed/newspap...,2015-04-21,113.0,1.000000,"['classes', 'fair', 'class', 'mondays', 'pm', ...",Services and information provided at the event...,0.655172,"(0.6, 0.8]"
4240,SeniorsPlus announces March classes,Maine Woods: How to Get Found If You Get Lost:...,LEWISTON -- SeniorsPlus is a private nonprofit...,NaN,"Sun Journal; Lewiston, Me.",2015,"Feb 18, 2015",Connections,Sun Journal,"Lewiston, Me.",...,News,1655943952,https://www.proquest.com/globalnewsfed/newspap...,2015-02-19,113.0,0.083571,"['classes', 'fair', 'class', 'mondays', 'pm', ...","As the disease progresses, new questions refle...",0.655172,"(0.6, 0.8]"
5147,"Healthy happenings: THURSDAY, OCT. 5",None available.,AARP Meeting The local Chapter of AARP will pr...,Genealogy; Personal health; Registration; Obje...,"Las Cruces Sun - News; Las Cruces, N.M.\n\nFir...",2017,"Oct 6, 2017",Features,Gannett Media Corp,"Las Cruces, N.M.",...,Feature,1962150062,https://www.proquest.com/globalnewsfed/newspap...,2017-11-10,113.0,1.000000,"['classes', 'fair', 'class', 'mondays', 'pm', ...",Enhance-fitness with Alex Palacios: 8 to 9 a.m...,0.655172,"(0.6, 0.8]"
5406,THINGS TO DO,Get hands-on tools to help you incorporate the...,"TUESDAY, MAY 16 HEALTHY LIVING FOR YOUR BRAIN ...",Dementia,"Dayton Daily News; Dayton, Ohio\n\nFirst page:...",2017,"May 11, 2017",Southern Montgomery County/Warren County,"Atlanta Journal Constitution, LLC","Dayton, Ohio",...,News,1897364510,https://www.proquest.com/globalnewsfed/newspap...,2017-11-24,113.0,1.000000,"['classes', 'fair', 'class', 'mondays', 'pm', ...",If you or someone you know is affected by deme...,0.655172,"(0.6, 0.8]"
5509,FYI,None available.,Classes SATURDAY “Mindful Pruning Strategies F...,Aviation; Bands; Music; Choirs; Taoism; Health...,"Columbian; Vancouver, Wash.\n\nFirst page: C.4",2017,"Mar 17, 2017",FYI,Columbian Publishing Company,"Vancouver, Wash.",...,News,1878414614,https://www.proquest.com/globalnewsfed/newspap...,2021-10-16,113.0,1.000000,"['classes', 'fair', 'class', 'mondays', 'pm', ...","117th St., Vancouver. Precision Personal Train...",0.655172,"(0.6, 0.8]"
6259,Young at Heart-conference on aging in a health...,"The theme of the workshop was, ""aging is norma...","On Thursday, February 8, the Potton's Retired ...",Heart; Pharmacists\n\nIdentifier / keyword: re...,"Record; Sherbrooke, Que.\n\nFirst page: A.2",2018,"Feb 12, 2018",News,Postmedia Network Inc.,"Sherbrooke, Que.",...,News,2001314982,https://www.proquest.com/globalnewsfed/newspap...,2018-02-13,113.0,0.058706,"['classes', 'fair', 'class', 'mondays', 'pm', ...",For more information about this and other upco...,0.655172,"(0.6, 0.8]"
7581,Senior athletes to compete at NMSU,None available.,LAS CRUCES - New Mexico State University and t...,Olympic games; Workshops; Summer\n\nLocation: ...,"Silver City Daily Press; Silver City, N.M.\n\n...",2020,"Jan 15, 2020",News,Gannett Media Corp,"Silver City, N.M.",...,News,2337765410,https://www.proquest.com/newspapers/senior-ath...,2020-01-15,113.0,1.000000,"['classes', 'fair', 'class', 'mondays', 'pm', ...","For information, call New Mexico Senior Olympi...",0.655172,"(0.6, 0.8]"
9401,Groups offer free counseling,None available.,The Joslyn Center and Volunteers in Medicine a...,Medicine; Counseling\n\nLocation: Coachella Va...,"The Desert Sun; Palm Springs, Calif.\n\nFirst ...",2023,"Aug 27, 2023",News,Gannett Media Corp,"Palm Springs, Calif.",...,News,2857530519,https://www.proquest.com/newspapers/groups-off...,2023-08-27,113.0,0.097956,"['classes', 'fair', 'class', 'mondays', 'pm', ...","Who do I contact? For more information, call K...",0.655172,"(0.6, 0.8]"

In [46]:
df.loc[472,'Full text']

"Several local natives took part Monday in the grueling Boston Marathon, including 2006 Miss Southeastern Ohio Jenna Wilson. A native of Zanesville and contestant in the Miss Ohio scholarship pageant the past two years, Wilson, 23, completed the course in 5 hours, 40 minutes and 43 seconds, which put her at 22,242nd in the sprawling field. She was 9,311th among women and 4,865th in her age group. According to her blog, Wilson has been training for about six months and ran as part of the Tufts University team's Tufts Presidents Marathon Challenge. She had to raise $1,000 to support nutrition, medical and fitness programs at Tufts. Tufts is a leader in research on healthy aging, childhood obesity and in its work to eliminate famine. Wilson, who also competed in several tune-up races and the Miss Boston pageant, is an Emerson-Tufts grad student in the Health Communication program. The Zanesville High grad finished as fourth-runner-up in the Miss Ohio pageant in 2008 and third in 2009. Others found among those crossing the finish line of the 26.2-mile race in Beantown were William Allen, 50, of Zanesville, who clocked in at 3:24:47, good for 373rd in his age group, 4,789th among men and 5,592nd overall. Herb Michel, 56, of Zanesville, ran a 4:02.11, good enough for 720th in his division, 9,998th among men and 15,752nd overall. Danette Warner, 31, of Zanesville, came in at 3:51.02, which was 2,795th in her age group, 4,219th among women and 13,050th overall. Former Zanesville resident Chuck Hagedorn, 55, ran in the marathon for the eighth straight year and was joined by son David and daughter Kati. Hagedorn ran a 5:44.38 for 1,094th in his division, 12,960th among men and 22,282nd overall. Crossing the finish line just ahead of him were David, 25, in 5:44.37 with a 4,623rd showing in his division, 12,959th among men and 22,280th overall; and Kati, 23, also at 5:44.37, 4,874th in her division, 9,322nd among women and 22,281st overall. Hagedorn previously worked for Zanesville Federal and now lives in Southborough, Mass., with his wife, the former Robin Jesse of Zanesville, and works for Massachusetts Mutual. Robin Jesse is the daughter of Gene and Genie Jesse of Nashport."

***
This topic is more about the Healthy Aging Fairs being held and the advertisements for their services.
***

In [47]:
df = remove_topic(df,113,[])

The orig length:10952 -> cropped: 10923

#### Topic 122

In [48]:
df[df['topic']==122]

,Title,Abstract,Full text,Subject,Publication title,Publication year,Publication date,Section,Publisher,Place of publication,...,Document type,ProQuest document ID,Document URL,Last updated,topic,topic_prob,topic_keywords,last,rel_ratio,rel_bins
256,Southeast Asian health ministers' meet in Thai...,None available.,"New Delhi, Aug. 30 -- Health ministers from 11...",NaN,The Hindustan Times; New Delhi,2010,"Aug 30, 2010\n\nDateline: New Delhi",NaN,HT Digital Streams Limited,New Delhi,...,WIRE FEED,748812701,https://www.proquest.com/globalnewsfed/newspap...,2018-02-26,122.0,0.059485,"['sustainable', 'protection', 'countries', 'po...",The health ministers' meeting are expected to ...,0.666667,"(0.6, 0.8]"
1971,The human dynamo behind WHO: Director-genera...,"'What is development if, at the end of the day...","If you passed Dr Margaret Chan on the street, ...",Cardiovascular disease; Antibiotics; Tobacco; ...,The Straits Times; Singapore,2012,"Mar 25, 2012",Think,SPH Media Limited,Singapore,...,News,940553189,https://www.proquest.com/globalnewsfed/newspap...,2012-04-25,122.0,0.058637,"['sustainable', 'protection', 'countries', 'po...","I can store up sleep. On weekends, I can sleep...",0.666667,"(0.6, 0.8]"
5239,Vietnam: Health issues to heat up APEC SOM 3 a...,None available.,Health officials from the Asia-Pacific Economi...,Working groups; Tuberculosis\n\nLocation: Asia...,Asia News Monitor; Bangkok,2017,"Aug 25, 2017",General News,Thai News Service Group,Bangkok,...,News,1931698337,https://www.proquest.com/globalnewsfed/newspap...,2024-11-26,122.0,1.000000,"['sustainable', 'protection', 'countries', 'po...","Besides, APEC officials will mull over other i...",0.666667,"(0.6, 0.8]"
5244,Asia: Producing a Healthy Asia Pacific by 2020...,None available.,The health of all residents in the Asia-Pacifi...,Working groups; Cooperation; Aging\n\nLocation...,Asia News Monitor; Bangkok,2017,"Aug 23, 2017",General News,Thai News Service Group,Bangkok,...,News,1930807388,https://www.proquest.com/globalnewsfed/newspap...,2024-11-26,122.0,0.060279,"['sustainable', 'protection', 'countries', 'po...","The chair of the working group, Rocío Cathia C...",0.666667,"(0.6, 0.8]"
5807,World: Helping ensure growth is shared by men ...,None available.,Challenge No country can achieve its potential...,Gender differences; Collaboration; Initiatives...,Asia News Monitor; Bangkok,2018,"Oct 3, 2018",General News,Thai News Service Group,Bangkok,...,News,2115449909,https://www.proquest.com/globalnewsfed/newspap...,2024-12-05,122.0,0.045248,"['sustainable', 'protection', 'countries', 'po...",Moving Forward The WBG is building further mom...,0.666667,"(0.6, 0.8]"
6525,ASEAN: Joint Statement of the 14th ASEAN Healt...,None available.,"WE, the Ministers of Health of ASEAN Member St...",Food safety; Collaboration; Nutrition; Disease...,Asia News Monitor; Bangkok,2019,"Sep 23, 2019",General News,Thai News Service Group,Bangkok,...,News,2295103530,https://www.proquest.com/globalnewsfed/newspap...,2024-11-24,122.0,0.225398,"['sustainable', 'protection', 'countries', 'po...",13. We recognise and appreciate the contributi...,0.666667,"(0.6, 0.8]"
6659,United Nations: Big Challenges Remain to Healt...,None available.,Following are UN Secretary-General Antonio Gut...,International conferences; Population; Young a...,Asia News Monitor; Bangkok,2019,"Jul 22, 2019",General News,Thai News Service Group,Bangkok,...,News,2260589328,https://www.proquest.com/globalnewsfed/newspap...,2024-11-25,122.0,1.000000,"['sustainable', 'protection', 'countries', 'po...","In November, the Governments of Kenya and Denm...",0.666667,"(0.6, 0.8]"
6660,United Nations: Despite Gains in Lowering Mate...,None available.,Following is UN Secretary-General António Gute...,Population growth; Trends; Maternal mortality;...,Asia News Monitor; Bangkok,2019,"Jul 22, 2019",General News,Thai News Service Group,Bangkok,...,News,2260585784,https://www.proquest.com/globalnewsfed/newspap...,2024-11-25,122.0,1.000000,"['sustainable', 'protection', 'countries', 'po...","In November, a summit marking the twenty-fifth...",0.666667,"(0.6, 0.8]"
6671,United Nations/Bangladesh: Thursday's Daily Br...,None available.,"This Thursday, we cover: New poverty report ci...",Population; Experts; Internet; Poverty; Wind; ...,Asia News Monitor; Bangkok,2019,"Jul 15, 2019",General News,Thai News Service Group,Bangkok,...,News,2257390476,https://www.proquest.com/globalnewsfed/newspap...,2024-11-25,122.0,0.052188,"['sustainable', 'protection', 'countries', 'po...",Amid ongoing threats and violence against jour...,0.666667,"(0.6, 0.8]"
6672,United Nations: 'Unlock opportunities' and pav...,None available.,As the number of people on the planet continue...,Violence; Girls; Pregnancy; Population; Womens...,Asia News Monitor; Bangkok,2019,"Jul 15, 2019",General News,Thai News Service Group,Bangkok,...,News,2257389851,https://www.proquest.com/globalnewsfed/newspap...,2024-11-25,122.0,1.000000,"['sustainable', 'protection', 'countries', 'po...",Our future depends on it. It's time to usher i...,0.666667,"(0.6, 0.8]"
6675,UN chief calls for recognizing link between po...,None available.,"UNITED NATIONS, July 13 -- Amid rising world's...",Girls; Population; Pregnancy; Womens health; S...,Right Vision News; Lahore,2019,"Jul 13, 2019",NaN,HT Digital Streams Limited,Lahore,...,News,2256576078,https://www.proquest.com/globalnewsfed/newspap...,2019-07-13,122.0,1.000000,"['sustainable', 'protection', 'countries', 'po...","""Our future depends on it."" It's time to ""ushe...",0.666667,"(0.6, 0.8]"
6678,‘Unlock opportunities’ and pave the way for su...,None available.,"NEW YORK, 11th July, 2019 (WAM) -- As the numb...",Population; Sustainable development; Trends\n\...,Emirates News Agency (WAM); Abu Dhabi,2019,"Jul 11, 2019",NaN,"Disco Digital Media, Inc.",Abu Dhabi,...,News,2255728442,https://www.proquest.com/globalnewsfed/newspap...,2019-07-11,122.0,1.000000,"['sustainable', 'protection', 'countries', 'po...","Since then, a number of a number of UN Populat...",0.666667,"(0.6, 0.8]"
6679,Sustainable dev largely depends on successful ...,None available.,"Dhaka, July 11 -- UN Secretary-General Antonio...",Sustainable development; Population growth; Ur...,United News of Bangladesh; Dhaka,2019,"Jul 11, 2019",NaN,HT Digital Streams Limited,Dhaka,...,News,2255544340,https://www.proquest.com/globalnewsfed/newspap...,2019-07-11,122.0,1.000000,"['sustainable', 'protection', 'countries', 'po...","In November, a summit marking the 25th anniver...",0.666667,"(0.6, 0.8]"
8530,Protecting workers good for us,None available.,MOST of Asia Pacific’s 2.1 billion-strong work...,Gross Domestic Product--GDP; Economic growth; ...,New Straits Times; Kuala Lumpur\n\nFirst page: 8,2022,"Sep 9, 2022",NaN,The New Straits Times Press (M) Berhad,Kuala Lumpur,...,News,2711609134,https://www.proquest.com/globalnewsfed/newspap...,2022-09-09,122.0,0.043159,"['sustainable', 'protection', 'countries', 'po...","For most countries, these reforms are affordab...",0.666667,"(0.6, 0.8]"
8534,Asia-Pacific: Op-Ed - The right policies can p...,None available.,Most of the 2.1 billion strong workforces in A...,Coronaviruses; Employment; Pandemics; COVID-19...,Asia News Monitor; Bangkok,2022,"Sep 8, 2022",General News,Thai News Service Group,Bangkok,...,News,2711048827,https://www.proquest.com/globalnewsfed/newspap...,2024-12-20,122.0,0.043771,"['sustainable', 'protection', 'countries', 'po...","For most countries, these reforms are affordab...",0.666667,"(0.6, 0.8]"
8539,The right policies can protect the workers of ...,None available.,Most of the 2.1 billion strong workforce in As...,Coronaviruses; Employment; Pandemics; COVID-19...,Viet Nam News; Hanoi,2022,"Sep 6, 2022",NaN,Vietnam News Agency,Hanoi,...,News,2711208000,https://www.proquest.com/globalnewsfed/newspap...,2022-09-08,122.0,0.042396,"['sustainable', 'protection', 'countries', 'po...",For most countries these reforms are affordabl...,0.666667,"(0.6, 0.8]"
8543,OP-ED: The right policies can protect the work...,None available.,OP-ED by Armida Salsiah Alisjahbana - United N...,Coronaviruses; Employment; Pandemics; COVID-19...,EveningReport.nz; Auckland,2022,"Sep 5, 2022",NaN,Athena Information Solutions Pvt. Ltd.,Auckland,...,News,2709557497,https://www.proquest.com/globalnewsfed/newspap...,2022-09-04,122.0,0.057220,"['sustainable', 'protection', 'countries', 'po...",For most countries these reforms are affordabl...,0.666667,"(0.6, 0.8]"
9078,"China, ROK and Japan sign health memorandum",None available.,"Health officials from China, Japan and the Rep...",Cooperation; Memoranda\n\nLocation: China; Jap...,"China Daily, Hong Kong ed.; Aberdeen\n\nFirst ...",2023,"Dec 4, 2023",NaN,China Daily,Aberdeen,...,News,2896421447,https://www.proquest.com/newspapers/china-rok-...,2023-12-04,122.0,1.000000,"['sustainable', 'protection', 'countries', 'po...",It also called for enhancing the resilience of...,0.666667,"(0.6, 0.8]"
9225,Qatar to host conference marking 30th annivers...,None available.,Tribune News Network New York To mark the 30th...,International conferences; Trends; Empowerment...,Qatar Tribune; Doha,2023,"Oct 19, 2023",NaN,"Disco Digital Media, Inc.",Doha,...,News,2880327416,https://www.proquest.com/newspapers/qatar-host...,2023-10-23,122.0,1.000000,"['sustainable', 'protection', 'countries', 'po...","” HE Mubarak Ajlan Al-Kuwari, Executive Direct...",0.666667,"(0.6, 0.8]"
9820,"Family policies in Arab region, global best pr...",None available.,"Doha, Qatar: The 30th Anniversary of the Inter...",Social change; Demography\n\nLocation: Armenia...,The Peninsula; Doha,2024,"Nov 1, 2024",NaN,"Disco Digital Media, Inc.",Doha,...,News,3123106189,https://www.proquest.com/globalnewsfed/newspap...,2024-11-01,122.0,1.000000,"['sustainable', 'protection', 'countries', 'po...","” Mkrtchyan said, “Another important challenge...",0.666667,"(0.6, 0.8]"
9930,Planet Overload,None available.,"Sri Lanka, Oct. 2 -- Youth unemployment, unres...",Poverty; Food; Demographics; Disease; Labor fo...,Daily News; Colombo,2024,"Oct 2, 2024",NaN,HT Digital Streams Limited,Colombo,...,News,3112089667,https://www.proquest.com/globalnewsfed/newspap...,2024-10-02,122.0,1.000000,"['sustainable', 'protection', 'countries', 'po...",She pointed out that some plastic recycling pr...,0.666667,"(0.6, 0.8]"
10209,PM Hasina opens 2-day global dialogue on demog...,None available.,"DHAKA, May 15 -- Prime Minister Sheikh Hasina ...",Reproductive rights; Population; Fertility; De...,United News of Bangladesh; Dhaka,2024,"May 15, 2024",NaN,HT Digital Streams Limited,Dhaka,...,News,3054667023,https://www.proquest.com/globalnewsfed/newspap...,2024-05-15,122.0,1.000000,"['sustainable', 'protection', 'countries', 'po...","The impact of climate on habitable spaces, rel...",0.666667,"(0.6, 0.8]"
10210,Two-day ICPD30 Global Dialogue begins in Dhaka...,None available.,"Dhaka, May 14 -- The governments of Bangladesh...",Reproductive rights; Population; Fertility; De...,United News of Bangladesh; Dhaka,2024,"May 14, 2024",NaN,HT Digital Streams Limited,Dhaka,...,News,3054424878,https://www.proquest.com/globalnewsfed/newspap...,2024-05-14,122.0,1.000000,"['sustainable', 'protection', 'countries', 'po...",Other sessions will cover - demographic divers...,0.666667,"(0.6, 0.8]"
10214,PM Hasina to attend ICPD30 Global Dialogue to ...,None available.,"DHAKA, May 11 -- The governments of Bangladesh...",International conferences; Reproductive rights...,United News of Bangladesh; Dhaka,2024,"May 11, 2024",NaN,HT Digital Streams Limited,Dhaka,...,News,3053424982,https://www.proquest.com/globalnewsfed/newspap...,2024-05-11,122.0,1.000000,"['sustainable', 'protection', 'countries', 'po...",The Programme of Action from the conference tr...,0.666667,"(0.6, 0.8]"
10436,"Philippines: CPD presents pros, cons of large ...",None available.,The Commission on Population and Development (...,NaN,Asia News Monitor; Bangkok,2025,"Aug 11, 2025",NaN,Thai News Service Group,Bangkok,...,News,3237773582,https://www.proquest.com/globalnewsfed/newspap...,2025-08-08,122.0,1.000000,"['sustainable', 'protection', 'countries', 'po...",Here lies the critical importance of populatio...,0.666667,"(0.6, 0.8]"
10887,Philippines: Commission calls for stronger pol...,None available.,As the country celebrates National Women's Mon...,Population; Women; Family planning; Unemployme...,Asia News Monitor; Bangkok,2025,"Mar 10, 2025",General News,Thai News Service Group,Bangkok,...,News,3175434857,https://www.proquest.com/globalnewsfed/newspap...,2025-03-10,122.0,1.000000,"['sustainable', 'protection', 'countries', 'po...",The strategies include the promotion of respon...,0.666667,"(0.6, 0.8]"
10899,Commission calls for stronger policies to brid...,None available.,"Manila, March 6 -- As the country celebrates N...",Population; Women; Family planning; Unemployme...,PNA Phillipines News Agency; New Delhi,2025,"Mar 6, 2025",NaN,HT Digital Streams Limited,New Delhi,...,News,3174411224,https://www.proquest.com/globalnewsfed/newspap...,2025-03-06,122.0,1.000000,"['sustainable', 'protection', 'countries', 'po...",The strategies include the promotion of respon...,0.666667,"(0.6, 0.8]"

In [49]:
df.loc[6575,'Full text']

'WORRIES about ageing are almost exclusively a concern for the ageing themselves. The young are too busy living fast to give a thought to what happens when the mind and body start slowing down. Even in Silicon Valley, where millions are being pumped into research aimed at turning back the clock, the leading practitioners and experts tend to be of a certain age themselves. With one exception. Laura Deming is only 25, yet her professional focus is entirely on finding ways to increase the healthy human lifespan of those in their 40s, 50s and beyond. Her goal isn\'t that pie-in-the-sky dream of life without any expiration date, but about how we can live longer, and grow old while still enjoying the physical and mental advantages of being young. \'Most people think of the body as something that breaks down over time and is unfixable, similar to a car rusting,\' she says. \'But there are some cars that have been around since 1910 because people are maintaining them and replacing the parts. Our goal, eventually, is to be able to do that with the human body. \'It\'s trying to figure out what kinds of damage accumulates with age, how to reverse that accumulation and the search for switches that we can flip in human biology to increase a healthy lifespan,\' she says. The science prodigy turned venture capitalist, who heads her own $37m (€33m) Longevity Fund that backs entrepreneurs developing therapies for age-related diseases, has already racked up some successes. One company Laura supports is developing a drug that would eliminate senescent cells - decaying cells that are the drivers of many age-associated diseases. Another start-up she is excited about is one that is using the biology of hibernation to aid in recovery from heart attack and stroke. \'It\'s no longer implausible that in the future we will have drugs and therapies that will make us feel healthier or younger later in life, potentially increasing our healthy lifespan,\' she says. We meet in San Francisco, amid Siliby con Valley\'s hottest new tech companies. Wearing a flowery sundress and Nike trainers, her dark hair tied back in a ponytail, Laura greets me with a firm handshake and an impish smile. DOTTED about her surprisingly modest office are pictures of illustrious scientists when they were young. She looks extremely youthful herself, with clear eyes and unblemished, make-up-free skin. There\'s the 19th-century Scottish scientist James Clerk Maxwell, who published papers on mathematical physics in his teens; the US computer scientist Margaret Hamilton with the software she and her team produced for the Apollo Space Mission when she was 33; and Serbianborn engineer and physicist Nikola Tesla who, as a young man, designed the alternating current (AC) electric system that still powers the world today. \'Some of these great scientists were geeky, awkward kids, who were just figuring life out and that was when their best ideas were coming to fruition,\' she says. It\'s clear she takes her inspiration from them and her own story is remarkable. Born in New Zealand in 1994, Laura admits she was also a \'geeky kid\' and was home-schooled by her mother Tabitha and father John, who disliked formal education. Laura says she taught herself calculus, probability and statistics as well as French literature and history. She also loved science, and her interest in life extension, finding ways to reduce or reverse the effects of ageing, was sparked by her maternal grandmother Bertie, who had neuro-muscular problems in her 70s and 80s. \'When you see a family member suffering from the ageing process, you realise the rate at which someone ages or the time he or she dies is so random and variable,\' she explains. \'It\'s determined by their environment and their genetics and isn\'t set in stone. \'I wondered "why can\'t we predict this?" I thought weshould be able to control those factors and change what happens.\' When she was 12, she wrote a fan letter to Cynthia Kenyon, a renowned American molecular biologist, who studies the genetics of ageing and who is now vice-president of the Google-backed healthcare subsidiary Calico. Kenyon, one of the world\'s foremost authorities on ageing, was impressed by the precocious child\'s passion and invited Laura to work in her laboratory. Laura\'s father, who works in finance and whose job was transferable, agreed to move, and the whole family upped sticks to the United States. While other boys and girls her age were partying and going to the beach, Laura was in a lab coat conducting experiments with possibly profound implications for the human race. Soon, she was helping to genetically engineer worms in her mentor\'s laboratory to make them live longer. At 14, she got a place at the highly acclaimed Massachusetts Institute of Technology (MIT) and the family moved again, to Boston. \'I took it for granted that my family let me have these opportunities, but I see now that I was really lucky,\' she laughs. She was invited to take part in an unusual educational experiment funded by billionaire Peter Thiel, cofounder of PayPal and an early investor in Facebook. He offered her and other bright young things $100,000 (€90,000) over two years to drop out of formal higher education and pursue other work. Aged 16, Laura grabbed the opportunity and founded her venture capital firm that invests in life-extension technology. Not many people took the teenager seriously at first - unsurprisingly perhaps - but she persisted and has raised millions from investors. Until the 1980s, anti-ageing research was regarded as a scientific backwater. Then, in the 1990s, researchers discovered that ageing is not necessarily an inevitability. Separate groups of scientists, including her mentor Cynthia Kenyon, determined that the worm species Caenorhabditis elegans, which is evolutionarily related to the genes that humans have, could be genetically engineered to live twice as long as its usual 20-day lifespan. \'These worms are fascinating because they were the first animals to challenge the idea that ageing is fixed,\' says Laura. \'You can genetically change their core DNA and double their lifespan or even increase it tenfold. It suggests there are pathways to regulate ageing and if there are pathways, there are proteins and that means you can eventually develop drugs.\' It was also discovered that some genes, when mutated, can make mice live longer. \'These worms don\'t have bones, blood, skin, hearts or any of the things that mice have, but the same genes that are found in worms to make them live longer also make mice live longer. \'And these fundamental mechanisms in very different species is one of the reasons people are very excited about ageing research. You impact aging in worms and mice and then move onto humans,\' she continues. Laura\'s job is to seek out and invest in ground-breaking research projects that may help undo the ravages of time - and make money for her investors, of course. She does not believe, however, that we are going to see massive increases in lifespans any time soon. \'The first drugs to come to market within the next few years will maybe add a couple of years [to lifespans],\' she says. \'It\'s not going to be a big leap, but the exciting thing is that we\'re no longer seeing ageing as a preordained decline.\' The most common question she is asked is how do we live longer now, while we wait for the scientists to do their work? What can we do to maximise our chances of living golden years? Calorie restriction or intermittent fasting (including popular diets such as the 5:2) is popular among people who want to stay youthful longer. In the 1930s, scientists found that feeding rats less made them live longer. It also works in mice, but long-term human studies are sparse, says Laura. \'I think intermittent fasting - fasting for eight-plus hours a day or five days a month or other cycles - might be helpful, but it\'s not going to give you a twofold increase in lifespan,\' she says. \'When researchers tried calorie restriction in mice, half lived longer and half of them lived shorter. So, these types of intervention can be helpful, but in a way that might be very personal to each individual. \'But intermittent fasting has aided recovery in patients undergoing chemotherapy - it makes them more robust - so I think that it could be of interest.\' But she sounds a note of caution about other techniques. Cryotherapy, where the body is exposed to extremely cold temperatures for several minutes per session, is also said to have rejuvenating effects. \'I don\'t know enough about it to recommend it,\' she shrugs. Parabiosis, the transfusion (or drinking) of blood from a younger person, has been thought to be a rejuvenation method since ancient times. In 2011, research was published showing that injecting young blood into old mice made them better at remembering things, and improved heart and muscle function. This led to a wave of start-ups offering the procedure for humans. \'These things are very much unproven. We don\'t have any evidence they work. I wouldn\'t say I know enough to say they would never work, but I would not recommend that anybody go and look for a blood transfusion clinic,\' she laughs. THERE may already be some drugs on the market, however, that can help with antiageing, she points out. The drug metaformin, which is taken by millions of people with Type 2 diabetes, is thought to add more benefits to patients\' lives than just treating their illness. Research is ongoing into whether this drug also helps with cognitive function as well as giving protection against Alzheimer\'s, cancer and heart disease. Trials of an immune function drug called rapamycin are under way with hundreds of elderly patients in the US, she says, to see if it has anti-ageing properties. \'We know rapamycin makes mice live ten to 14 per cent longer than normal and it appears to be making these patients healthier and improve their immune system function later in life so that\'s hopeful,\' she says. Of course, Laura points out, other ways of getting the best out of our advancing years is to eat well, exercise and have a purpose in our lives. These are all terrific anti-ageing medicines. Will it soon be normal for us to live to 100? \'I wish I could give you an answer, but it would be scientifically inaccurate to try,\' she laughs. \'We could not predict in the 1950s that we could make worms or mice live twice as long as normal. On some level, the difficulty is not the science, but the time and cost of drug development - to achieve that would take a very sobering timeframe,\' says Laura. I ask this 25-year-old if she personally worries about living to a ripe old age. With the nonchalance of the young, she says she does not do anything special to take care of her health. \'I should exercise more, and I eat a lot of cookies and chocolate,\' she confesses. \'What I care about is not lifespan, it\'s being cognitively alert as long as possible,\' she says. \'I would love to tutor my grandchildren in their scientific projects, to be able to be properly conversant with them. \'Ageing without illness - that\'s the goal. What we want is to be able to give everyone in the world the ability to choose how long they want to live. \'It\'s about having the freedom of choice. I think that\'s the most you can do.\' 82.8 The average Irish life expectancy for a woman - it is 78.4 for men CREDIT: Barbara McMahon CAPTION: Looking into the future: Laura Deming Picture: GABRIELA HASBUN/REDUX/EYEVINE.'

***
This one is more about the politics on general health within Asia
***

In [50]:
df = remove_topic(df,122,[])

The orig length:10923 -> cropped: 10896

#### Topic 151

In [51]:
df[df['topic']==151]

,Title,Abstract,Full text,Subject,Publication title,Publication year,Publication date,Section,Publisher,Place of publication,...,Document type,ProQuest document ID,Document URL,Last updated,topic,topic_prob,topic_keywords,last,rel_ratio,rel_bins
175,Your town in brief: Flu shots for seniors in M...,None available.,All communities Know someone 'locally inspirin...,NaN,"The Salt Lake Tribune; Salt Lake City, Utah",2010,"Sep 29, 2010",NaN,The Salt Lake Tribune,"Salt Lake City, Utah",...,News,755669970,https://www.proquest.com/globalnewsfed/newspap...,2017-11-17,151.0,0.143256,"['farmers', 'volunteers', 'market', 'victoria'...","Salt Lake County Ban hunger, not books - Salt ...",0.73913,"(0.6, 0.8]"
299,Farmers' Market helps seniors stay healthy,Without being able to purchase fresh fruits an...,CLEVELAND - Many Northeast Ohio senior residen...,Cities; Vegetables; Fruits; Older people; Nutr...,"Call & Post, All-Ohio edition; Cleveland, Ohio...",2010,"Jul 28-Aug 3, 2010",HEALTH,Call and Post,"Cleveland, Ohio",...,News,750539226,https://www.proquest.com/globalnewsfed/newspap...,2011-06-03,151.0,0.108688,"['farmers', 'volunteers', 'market', 'victoria'...",The program starts in the month of June and ru...,0.73913,"(0.6, 0.8]"
475,Volunteer opportunities abound,Salt Lake County Aging Services Healthy Aging ...,Here are some ways provided by the 2-1-1 Infor...,NaN,"Deseret News; Salt Lake City, Utah\n\nFirst pa...",2010,"May 2, 2010",Local,Deseret Digital Media,"Salt Lake City, Utah",...,News,230760848,https://www.proquest.com/globalnewsfed/newspap...,2011-10-27,151.0,1.000000,"['farmers', 'volunteers', 'market', 'victoria'...",Head Start Salt Lake CAP -- Classroom voluntee...,0.73913,"(0.6, 0.8]"
573,At your service,"Activities Unlimited of Cowichan Valley, non-p...",VOLUNTEER OPPORTUNITIES Saanich Emergency Soci...,Volunteers; Yoga; Spirituality; Mens health; M...,"Times - Colonist; Victoria, B.C.\n\nFirst page...",2010,"Feb 14, 2010",Life,Postmedia Network Inc.,"Victoria, B.C.",...,News,348405545,https://www.proquest.com/globalnewsfed/newspap...,2023-07-11,151.0,1.000000,"['farmers', 'volunteers', 'market', 'victoria'...","Peace Vigil. Wednesdays at the cenotaph, Belle...",0.73913,"(0.6, 0.8]"
619,Volunteers are needed in varied areas,Maliheh Free Clinic -- Volunteer interpreters ...,Here are ways to share time and talents with o...,NaN,"Deseret News; Salt Lake City, Utah\n\nFirst pa...",2010,"Jan 24, 2010",Local,Deseret Digital Media,"Salt Lake City, Utah",...,News,351807716,https://www.proquest.com/globalnewsfed/newspap...,2011-10-23,151.0,1.000000,"['farmers', 'volunteers', 'market', 'victoria'...",Volunteers must understand medical terminology...,0.73913,"(0.6, 0.8]"
620,Volunteer corner,Salt Lake County Aging Services Healthy Aging ...,Dial 2-1-1 for the volunteer information desk ...,Volunteers,"The Salt Lake Tribune; Salt Lake City, Utah",2010,"Mar 31, 2010",NaN,The Salt Lake Tribune,"Salt Lake City, Utah",...,News,280584134,https://www.proquest.com/globalnewsfed/newspap...,2017-11-06,151.0,1.000000,"['farmers', 'volunteers', 'market', 'victoria'...",Salt Lake CAP Head Start - Volunteers are need...,0.73913,"(0.6, 0.8]"
1068,Asheville-area business briefs: Construction...,None available.,NEWLAND - North Carolina developer O2 Energies...,NaN,"Asheville Citizen - Times; Asheville, N.C.",2011,"Jun 26, 2011",LIVING,Gannett Media Corp,"Asheville, N.C.",...,News,873665752,https://www.proquest.com/globalnewsfed/newspap...,2017-11-18,151.0,1.000000,"['farmers', 'volunteers', 'market', 'victoria'...","For more information, contact the county manag...",0.73913,"(0.6, 0.8]"
1069,BRIEFCASE,None available.,Briefcase Construction begins on solar farm NE...,NaN,"Asheville Citizen - Times; Asheville, N.C.\n\n...",2011,"Jun 26, 2011",News,Gannett Media Corp,"Asheville, N.C.",...,News,1471190578,https://www.proquest.com/globalnewsfed/newspap...,2017-11-20,151.0,1.000000,"['farmers', 'volunteers', 'market', 'victoria'...",Best Buy donates Wii Fit System BLACK MOUNTAIN...,0.73913,"(0.6, 0.8]"
1084,Grocers make plans for healthier products,Festival's private label brands include Home L...,Marshfield News-Herald Retail giant Wal-Mart S...,Discount department stores; Natural products; ...,"Marshfield News Herald; Marshfield, Wis.",2011,"Jun 18, 2011",MNH,"Ogden Newspapers, Inc.","Marshfield, Wis.",...,News,872338733,https://www.proquest.com/globalnewsfed/newspap...,2017-11-18,151.0,1.000000,"['farmers', 'volunteers', 'market', 'victoria'...","The brand has done fairly well, but it's not b...",0.73913,"(0.6, 0.8]"
1389,United Way of Chittenden County Volunteer Conn...,VITA's goal is to help lower-income individual...,The listings below are a small sample of the m...,Aging; Tax credits; Tax preparation; Nutrition...,"The Burlington Free Press; Burlington, Vt.",2012,"Dec 27, 2012",B,Gannett Media Corp,"Burlington, Vt.",...,News,1245566503,https://www.proquest.com/g lobalnewsfed/newspa...,2017-11-19,151.0,1.000000,"['farmers', 'volunteers', 'market', 'victoria'...",Lake Champlain Committee - Stuffing and sealin...,0.73913,"(0.6, 0.8]"
2480,Volunteers wanted for many events,Volunteers reach out to their peers to talk ab...,The listings below are a small sample of the 3...,Aging; Volunteers,"The Burlington Free Press; Burlington, Vt.\n\n...",2013,"Jul 1, 2013",B,Gannett Media Corp,"Burlington, Vt.",...,News,1372728511,https://www.proquest.com/globalnewsfed/newspap...,2017-11-20,151.0,1.000000,"['farmers', 'volunteers', 'market', 'victoria'...",Shifts run from 10 a.m. to 1 p.m. and 1-4 p.m....,0.73913,"(0.6, 0.8]"
2586,United Way Volunteer Connection,"NFI VERMONT - Help out at ""Pitchin' for Famili...",The listings below are a small sample of the m...,Aging; Telephone hotlines; Counseling; Volunte...,"The Burlington Free Press; Burlington, Vt.\n\n...",2013,"May 16, 2013",B,Gannett Media Corp,"Burlington, Vt.",...,News,1352324254,https://www.proquest.com/globalnewsfed/newspap...,2017-11-20,151.0,1.000000,"['farmers', 'volunteers', 'market', 'victoria'...","Volunteers can help with setup, breakdown, reg...",0.73913,"(0.6, 0.8]"
3239,"Agriculture business healthy, but farmers agin...","According to the USDA, total farm production e...",Dave Polcyn/News Journal The state of agricult...,Costs; Agriculture; Net losses; Corn; Farms\n\...,"News Journal; Mansfield, Ohio",2014,"May 24, 2014",Local News,Gannett Media Corp,"Mansfield, Ohio",...,News,1528044265,https://www.proquest.com/newspapers/agricultur...,2017-11-21,151.0,1.000000,"['farmers', 'volunteers', 'market', 'victoria'...",Delaware County led the state in that category...,0.73913,"(0.6, 0.8]"
3967,Broomfield Farmers' Market back with community...,"In past years, WIC recipients could spend $10 ...",If you go What: Broomfield Farmers Market When...,Farmers markets; Nutrition; Food stamps; Episc...,"Broomfield Enterprise; Broomfield, Colo.",2015,"Jun 4, 2015",News,Prairie Mountain Media,"Broomfield, Colo.",...,News,1685953369,https://www.proquest.com/globalnewsfed/newspap...,2015-06-04,151.0,1.000000,"['farmers', 'volunteers', 'market', 'victoria'...","Megan Quinn: 303-410-2649, quinnm@broomfielden...",0.73913,"(0.6, 0.8]"
4117,United Way Volunteer Center,SUMMER INTERNSHIP - Winooski Valley Park Distr...,Volunteer Now! Choose one of the options below...,Volunteers; Older people\n\nLocation: Vermont\...,"The Burlington Free Press; Burlington, Vt.\n\n...",2015,"Mar 23, 2015",A,Gannett Media Corp,"Burlington, Vt.",...,News,1665138927,https://www.proquest.com/globalnewsfed/newspap...,2017-11-22,151.0,1.000000,"['farmers', 'volunteers', 'market', 'victoria'...",Contact Candace Taylor at 863-2345 or email vo...,0.73913,"(0.6, 0.8]"
4527,Stonehill College takes its discount 'Mobile M...,"Much of the city is a federally designated ""fo...","EASTON -- Every other Wednesday this summer, M...",Food; Vouchers\n\nCompany / organization: Name...,Boston Globe (Online); Boston,2016,"Aug 24, 2016",Regional,"Boston Globe Media Partners, LLC",Boston,...,News,1813591629,https://www.proquest.com/globalnewsfed/newspap...,2016-08-24,151.0,0.114910,"['farmers', 'volunteers', 'market', 'victoria'...",Credit: By Jacob Carozza Globe Correspondent I...,0.73913,"(0.6, 0.8]"
5229,United Way Volunteer Connection,None available.,LEND A HAND. VOLUNTEER - United Way of Northwe...,Families & family life; Children & youth; Volu...,"The Burlington Free Press; Burlington, Vt.\n\n...",2017,"Aug 28, 2017\n\ncolumn: United Way Volunteer C...",Features,Gannett Media Corp,"Burlington, Vt.",...,Feature,1932715652,https://www.proquest.com/globalnewsfed/newspap...,2017-11-24,151.0,1.000000,"['farmers', 'volunteers', 'market', 'victoria'...",Background check required. Scheduling through ...,0.73913,"(0.6, 0.8]"
5336,HEALTHY AGING: Program boosts value of produce...,Note: GEORGIA FRESH FOR LESS Participating far...,Note: GEORGIA FRESH FOR LESS Participating far...,Agriculture; Fruits; Food; Older people; Farme...,"The Atlanta Journal - Constitution; Atlanta, Ga.",2017,"Jun 19, 2017",LIVING & ARTS,"Atlanta Journal Constitution, LLC","Atlanta, Ga.",...,News,1910711763,https://www.proquest.com/globalnewsfed/newspap...,2017-11-24,151.0,0.111549,"['farmers', 'volunteers', 'market', 'victoria'...",Through the Fruit and Vegetable Prescription P...,0.73913,"(0.6, 0.8]"
5864,PENINSULA ZOOMERS: A stronger sense of community,None available.,Wasn't that a party! This August in White Roc...,"Aging\n\nLocation: Canada\n\nPeople: Trudeau, ...","The Peace Arch News; White Rock, B.C.",2018,"Aug 29, 2018",Community,Black Press Group Ltd.,"White Rock, B.C.",...,News,2096760451,https://www.proquest.com/globalnewsfed/newspap...,2018-08-30,151.0,1.000000,"['farmers', 'volunteers', 'market', 'victoria'...",Call Denice at 604-538-5778 for details. #CARP...,0.73913,"(0.6, 0.8]"
5940,volunteer opportunities,None available.,Shoe donation organizer: St. Vincent de Paul i...,Older people; Volunteers\n\nLocation: Wisconsi...,"Wausau Daily Herald; Wausau, Wis.\n\nFirst pag...",2018,"Jul 30, 2018",News,Gannett Media Corp,"Wausau, Wis.",...,News,2078343334,https://www.proquest.com/globalnewsfed/newspap...,2018-07-30,151.0,1.000000,"['farmers', 'volunteers', 'market', 'victoria'...",Tools: Stable Hands Equine Therapy Center can ...,0.73913,"(0.6, 0.8]"
6021,FILLING A SUMMER NEED: A summer program prov...,None available.,Volunteers lined tables and chairs at the Mang...,Meals; Aging; Low income groups; Nutrition edu...,Tampa Bay Times; Tampa Bay\n\nFirst page: 1,2018,"Jun 10, 2018\n\nDateline: SEFFNER",TAMPA TRIBUNE,Times Publishing Company,Tampa Bay,...,News,2054927009,https://www.proquest.com/globalnewsfed/newspap...,2018-06-14,151.0,0.101807,"['farmers', 'volunteers', 'market', 'victoria'...","""I'll be anxious at the end of the summer to s...",0.73913,"(0.6, 0.8]"
8238,In your region,None available.,Grants available to Carbon nonprofits To suppo...,Maple syrup; Hydroponics; Coronaviruses; Fundi...,"Morning Call; Allentown, Pa.\n\nFirst page: A.13",2021,"Jan 24, 2021",NaN,"Tribune Publishing Company, LLC","Allentown, Pa.",...,News,2480046062,https://www.proquest.com/newspapers/your-regio...,2021-01-31,151.0,1.000000,"['farmers', 'volunteers', 'market', 'victoria'...",The course consist of six hours of classroom w...,0.73913,"(0.6, 0.8]"
9228,Pop-up Mobile Markets‘ a hit in nine towns,None available.,STILLWATER Pop-up Mobile Markets were a big hi...,NaN,"Journal Record; Oklahoma City, Okla.",2023,"Oct 18, 2023",NaN,BridgeTower Media Holding Company,"Oklahoma City, Okla.",...,News,2880600786,https:// www.proquest.com/newspapers/pop-up-mo...,2023-10-24,151.0,0.095842,"['farmers', 'volunteers', 'market', 'victoria'...",I just love it.” The markets in Muskogee were ...,0.73913,"(0.6, 0.8]"

***
Amongst these topics, there are valuable articles such as 308,5385 but others are about farmers aging and the agriculture downfall as well as volunteers.
***

In [52]:
df = remove_topic(df,151,[308,5385])

The orig length:10896 -> cropped: 10873

#### Topic 174

In [53]:
df[df['topic']==174]

,Title,Abstract,Full text,Subject,Publication title,Publication year,Publication date,Section,Publisher,Place of publication,...,Document type,ProQuest document ID,Document URL,Last updated,topic,topic_prob,topic_keywords,last,rel_ratio,rel_bins
306,Articles for Growing Older from non-profit org...,"Age & Opportunity Inc. ABC's of Fraud, seldom ...",Articles for Growing Older from non-profit org...,NaN,"Winnipeg Free Press; Winnipeg, Man.",2010,"Apr 7, 2010",NaN,FP Canadian Newspapers Limited Partnership,"Winnipeg, Man.",...,News,578687712,https://www.proquest.com/globalnewsfed/newspap...,2017-11-17,174.0,1.0,"['pm', 'st', 'tuesday', 'tickets', 'ave', 'fri...",Centrally located in Osborne Village. Informat...,0.789474,"(0.6, 0.8]"
374,Bangor senior center plans gardening talk,BANGOR - Seniors interested in learning more a...,BANGOR - Seniors interested in learning more a...,Senior citizen centers,"Bangor Daily News; Bangor, Me.\n\nFirst page: 3",2010,"Jun 11, 2010",B,Bangor Daily News,"Bangor, Me.",...,News,366709778,https://www.proquest.com/globalnewsfed/newspap...,2017-11-06,174.0,1.0,"['pm', 'st', 'tuesday', 'tickets', 'ave', 'fri...",Gardeners Gayle Crowley and Charlie Taylor wil...,0.789474,"(0.6, 0.8]"
385,What's going on for seniors,The fair will serve as a resource centre for s...,Healthy Aging Fair: Nurse Next Door Home Healt...,Aging,"North Shore News; North Vancouver, B.C.\n\nFir...",2010,"Jun 6, 2010",Seniors,Postmedia Network Inc.,"North Vancouver, B.C.",...,News,365901213,https://www.proquest.com/globalnewsfed/newspap...,2012-02-07,174.0,1.0,"['pm', 'st', 'tuesday', 'tickets', 'ave', 'fri...",Drop-in: $4.40. Info: 604-983-6362 or kshubert...,0.789474,"(0.6, 0.8]"
411,Senior Expo to feature Silver Frame Awards,Hammond Street Senior Center is offering a Hea...,Among the many activities that are part of the...,Garage sales; Health services; Senior citizen ...,"Bangor Daily News; Bangor, Me.\n\nFirst page: 4",2010,"May 18, 2010",B,Bangor Daily News,"Bangor, Me.",...,Column,288301606,https://www.proquest.com/globalnewsfed/newspap...,2017-11-05,174.0,1.0,"['pm', 'st', 'tuesday', 'tickets', 'ave', 'fri...","There is no admission to attend and ""hear old ...",0.789474,"(0.6, 0.8]"
779,Health fair features exhibits for every need,"VON Meals on Wheels, Bayshore Home Health Care...",Centres for Seniors Windsor presents The Senio...,Martial arts; Mental health; Home health care,"The Windsor Star; Windsor, Ont.\n\nFirst page:...",2011,"Oct 22, 2011",Life,Postmedia Network Inc.,"Windsor, Ont.",...,News,900344253,https://www.proquest.com/globalnewsfed/newspap...,2017-11-18,174.0,1.0,"['pm', 'st', 'tuesday', 'tickets', 'ave', 'fri...","Mail information to Natalie Taylor, 3448 Turne...",0.789474,"(0.6, 0.8]"
819,County digest,None available.,"50+EXPO Annual event, geared toward adults 50 ...",NaN,"The Baltimore Sun; Baltimore, Md.\n\nFirst pag...",2011,"Oct 9, 2011",LOCAL,"Tribune Publishing Company, LLC","Baltimore, Md.",...,News,912727289,https://www.proquest.com/globalnewsfed/newspap...,2017-11-18,174.0,1.0,"['pm', 'st', 'tuesday', 'tickets', 'ave', 'fri...","Daily fee of $26 includes snacks, lunch, coffe...",0.789474,"(0.6, 0.8]"
821,Happenings,"Sarah Nixon-Jackel, an Older Adult Wellness Nu...",New organizations and groups changing their sc...,Farmers markets; Libraries; Biodiversity,"Saskatoon Sun; Saskatoon, Sask.\n\nFirst page: 11",2011,"Oct 9, 2011",News,Postmedia Network Inc.,"Saskatoon, Sask.",...,News,898126800,https://www.proquest.com/globalnewsfed/newspap...,2020-03-12,174.0,1.0,"['pm', 'st', 'tuesday', 'tickets', 'ave', 'fri...",For information call 652-6831 or 653-5339. AGL...,0.789474,"(0.6, 0.8]"
1021,North State in brief,None available.,New members sought for band The Shasta College...,Bands,Record Searchlight; Redding\n\nFirst page: B.1,2011,"Jul 23, 2011",Local,Gannett Media Corp,Redding,...,News,2593421124,https://www.proquest.com/globalnewsfed/newspap...,2021-11-05,174.0,1.0,"['pm', 'st', 'tuesday', 'tickets', 'ave', 'fri...",The summit is held to educate those 55 and old...,0.789474,"(0.6, 0.8]"
1314,Go calendar,FRIDAY FEB. 11 AUTHOR Planet Earth Poetry pres...,FRIDAY FEB. 11 AUTHOR Planet Earth Poetry pres...,Resorts & spas; Reading; Dance; Jazz,"Times - Colonist; Victoria, B.C.\n\nFirst page...",2011,"Feb 10, 2011",Go!,Postmedia Network Inc.,"Victoria, B.C.",...,News,851487375,https://www.proquest.com/globalnewsfed/newspap...,2017-11-17,174.0,1.0,"['pm', 'st', 'tuesday', 'tickets', 'ave', 'fri...",Performance at 7:30 p.m. See Friday for detail...,0.789474,"(0.6, 0.8]"
2947,SeniorsPlus classes for November include discu...,"Flu & Pneumonia: Instructors, nursing students...","LEWISTON -- SeniorsPlus Education Center, 8 Fa...",NaN,"Sun Journal; Lewiston, Me.",2014,"Oct 29, 2014",Connections,Sun Journal,"Lewiston, Me.",...,News,1618000832,https://www.proquest.com/newspapers/seniorsplu...,2014-10-30,174.0,1.0,"['pm', 'st', 'tuesday', 'tickets', 'ave', 'fri...",SeniorsPlus is a private nonprofit corporation...,0.789474,"(0.6, 0.8]"
3157,Fall classes being offered at Kuhn Center,"The Sisters of Charity, BVM, will host fall cl...","The Sisters of Charity, BVM, will host fall cl...",NaN,"Telegraph - Herald; Dubuque, Iowa\n\nFirst pag...",2014,"Jul 16, 2014\n\nDateline: Dubuque",NaN,Telegraph Herald,"Dubuque, Iowa",...,News,1545352066,https://www.proquest.com/newspapers/fall-class...,2014-07-17,174.0,1.0,"['pm', 'st', 'tuesday', 'tickets', 'ave', 'fri...",A variety of other classes also will be offere...,0.789474,"(0.6, 0.8]"
3447,Valentines social a good break from winter,None available.,Two couples met about 18 years ago while out d...,Volunteers; Aging,"Evansville Courier & Press; Evansville, Ind.\n...",2014,"Feb 12, 2014",Local,Gannett Media Corp,"Evansville, Ind.",...,News,2584213727,https://www.proquest.com/newspapers/valentines...,2021-10-22,174.0,1.0,"['pm', 'st', 'tuesday', 'tickets', 'ave', 'fri...",Marilyn Pruiett and Marjorie and Paul Holcolb ...,0.789474,"(0.6, 0.8]"
3771,Calendar of events,None available.,New Brunswick's Collaborative for Healthy Agin...,NaN,"The Times - Transcript; Moncton, N.B.\n\nFirst...",2015,"Sep 15, 2015",Features,Postmedia Network Inc.,"Moncton, N.B.",...,News,1712306327,https://www.proquest.com/globalnewsfed/newspap...,2015-09-15,174.0,1.0,"['pm', 'st', 'tuesday', 'tickets', 'ave', 'fri...","For more information, call Chuck at 384-7428 o...",0.789474,"(0.6, 0.8]"
4758,Healthy Aging: May-June Senior Lunch & Activit...,With socialization a critical component to agi...,With socialization a critical component to agi...,NaN,"Daily Herald; Arlington Heights, Ill.",2016,"Apr 14, 2016",Submitted Content,Daily Herald,"Arlington Heights, Ill.",...,News,1781026562,https://www.proquest.com/globalnewsfed/newspap...,2017-11-22,174.0,1.0,"['pm', 'st', 'tuesday', 'tickets', 'ave', 'fri...","Our ""Welcome To Summer"" Luncheon will include ...",0.789474,"(0.6, 0.8]"
5228,[Strathcona Centre [Eth ] News & Views Sept. 2...,None available.,Strathcona Centre [Eth] News & Views Sept. 201...,Gardens & gardening; Meals; Garden clubs; Age;...,"The Medicine Hat News; Medicine Hat, Alta.\n\n...",2017,"Aug 28, 2017",B,Postmedia Network Inc.,"Medicine Hat, Alta.",...,News,1932886454,https://www.proquest.com/globalnewsfed/newspap...,2017-08-28,174.0,1.0,"['pm', 'st', 'tuesday', 'tickets', 'ave', 'fri...",Age of Champions is the award-winning document...,0.789474,"(0.6, 0.8]"
5269,50 plus Submit your events at dailyherald.com/...,None available.,Events that specify they are for those who are...,Registration; West Nile virus; Aging; Dementia...,"Daily Herald; Arlington Heights, Ill.\n\nFirst...",2017,"Jul 31, 2017",NEIGHBOR,Daily Herald,"Arlington Heights, Ill.",...,News,1924520971,https://www.proquest.com/globalnewsfed/newspap...,2017-11-24,174.0,1.0,"['pm', 'st', 'tuesday', 'tickets', 'ave', 'fri...",Rich Scheflow of Edward Jones explains how to ...,0.789474,"(0.6, 0.8]"
5347,Assembly approves Munoz nurse bill,None available.,The full Assembly recently approved a bill spo...,Blood & organ donations; Nursing; Aging; Yoga;...,"Home News Tribune; East Brunswick, N.J.\n\nFir...",2017,"Jun 13, 2017\n\ncolumn: heartbeats",Features,Gannett Media Corp,"East Brunswick, N.J.",...,Feature,1908638848,https://www.proquest.com/globalnewsfed/newspap...,2018-05-03,174.0,1.0,"['pm', 'st', 'tuesday', 'tickets', 'ave', 'fri...",Steve SanAntonio at 908-231-7168 or Sheriff's ...,0.789474,"(0.6, 0.8]"
6205,Coming up this week on the Miramichi,"Friday, March 16 -9 a.m. to 12 p.m., weekly, a...","Friday, March 16 -9 a.m. to 12 p.m., weekly, a...",Cancer; Older people; Irish Americans; Women; ...,"Miramichi Leader; Miramichi, N.B.\n\nFirst pag...",2018,"Mar 16, 2018",NaN,Postmedia Network Inc.,"Miramichi, N.B.",...,News,2014550486,https://www.proquest.com/globalnewsfed/newspap...,2018-03-18,174.0,1.0,"['pm', 'st', 'tuesday', 'tickets', 'ave', 'fri...",Regular bingo starts at 7 p.m. Full card jackp...,0.789474,"(0.6, 0.8]"
6217,FYI,None available.,Classes Saturday Growing Food For Almost Free ...,Fund raising; Students; Beekeeping; Public lib...,"Columbian; Vancouver, Wash.\n\nFirst page: C.4",2018,"Mar 9, 2018",FYI,Columbian Publishing Company,"Vancouver, Wash.",...,News,2013167844,https://www.proquest.com/globalnewsfed/newspap...,2021-10-15,174.0,1.0,"['pm', 'st', 'tuesday', 'tickets', 'ave', 'fri...",Professional hairdressers and floral designers...,0.789474,"(0.6, 0.8]"

***
These all are noise articles.
***

In [54]:
df = remove_topic(df,174,[])

The orig length:10873 -> cropped: 10854

#### Topic 177

In [55]:
df[df['topic']==177]

,Title,Abstract,Full text,Subject,Publication title,Publication year,Publication date,Section,Publisher,Place of publication,...,Document type,ProQuest document ID,Document URL,Last updated,topic,topic_prob,topic_keywords,last,rel_ratio,rel_bins
33,[Diary ],"Enquiries: Centre for Public Management, 02616...",December December 7: Leader to Leader series J...,Politics; International relations; Editing; Cl...,"The Canberra Times; Canberra, A.C.T.\n\nFirst ...",2010,"Dec 7, 2010",NaN,Rural Press Pty Ltd Australian Community Media...,"Canberra, A.C.T.",...,News,1020454324,https://www.proquest.com/globalnewsfed/newspap...,2012-06-15,177.0,1.000000,"['productivity', 'australia', 'political', 'ho...","Enquiries: Bayley and Associates, 0262825660 o...",0.684211,"(0.6, 0.8]"
109,Growing old no barrier to helping out,"NESTA, the National Endowment for Science, Tec...",People in their 50s and 60s are being challeng...,NaN,Evening News; Edinburgh (UK)\n\nFirst page: 10,2010,"Oct 27, 2010",NaN,National World,Edinburgh (UK),...,News,760040954,https://www.proquest.com /globalnewsfed/newspa...,2012-02-09,177.0,0.197877,"['productivity', 'australia', 'political', 'ho...","NESTA, the National Endowment for Science, Tec...",0.684211,"(0.6, 0.8]"
1449,"Good buy, old friend Small shopping strips hav...",A Monash University study confirms small strip...,SMALL shopping strips fill a crucial role for ...,Older people; Food; Shopping centers,"Sunday Herald - Sun; Melbourne, Vic.\n\nFirst ...",2012,"Nov 18, 2012",NEWS,Nationwide News Pty Ltd,"Melbourne, Vic.",...,News,1162942399,https://www.proquest.com/globalnewsfed/newspap...,2012-11-18,177.0,1.000000,"['productivity', 'australia', 'political', 'ho...","There is also an Indian restaurant, organic fr...",0.684211,"(0.6, 0.8]"
1743,So that's the Origin of the dreaded b-word: ...,"Typical, bloody typical. In a week when the ca...","Typical, bloody typical. In a week when the ca...",Interest rates,"Sydney Morning Herald; Sydney, N.S.W.\n\nFirst...",2012,"Jul 7, 2012",NaN,Fairfax Digital,"Sydney, N.S.W.",...,News,1023729373,https://www.proquest.com/globalnewsfed/newspap...,2017-11-19,177.0,1.000000,"['productivity', 'australia', 'political', 'ho...",Scientologists were denounced by a tweeting Ru...,0.684211,"(0.6, 0.8]"
2380,Rudd's Condong whistlestop,"After nearly an hour at Condong, Rudd slipped ...",THERE'S a lot to be said for a country where y...,Aging; Beer,"Daily News; Tweed Heads, N.S.W.\n\nFirst page: 6",2013,"Aug 24, 2013",NaN,Nationwide News Pty Ltd,"Tweed Heads, N.S.W.",...,News,1427015889,https://www.proquest.com/globalnewsfed/newspap...,2013-08-23,177.0,1.000000,"['productivity', 'australia', 'political', 'ho...",Alas Steve never got to tend to the nation's m...,0.684211,"(0.6, 0.8]"
2909,Experts reveal eight ways to keep people healt...,Alamy Regular exercise can keep you fit and we...,ILL health in old age can be prevented if loca...,Older people; Public health; Age; Aging,Express (Online); London (UK),2014,"Nov 16, 2014",NaN,Express Newspapers PLC,London (UK),...,News,1625267269,https://www.proquest.com/newspapers/experts-re...,2014-11-17,177.0,1.000000,"['productivity', 'australia', 'political', 'ho...","But it warned that ""it also has the potential ...",0.684211,"(0.6, 0.8]"
3909,Millions allocated for rural nurses,A $6.4 million commitment from the Abbott gove...,A $6.4 million commitment from the Abbott gove...,Health care industry; Chronic illnesses; Prima...,"Nyngan Observer; Nyngan, N.S.W.",2015,"Jul 7, 2015",NaN,Rural Press Pty Ltd Australian Community Media...,"Nyngan, N.S.W.",...,News,1694865226,https://www.proquest.com/globalnewsfed/newspap...,2015-07-08,177.0,1.000000,"['productivity', 'australia', 'political', 'ho...",'The government's commitment builds on APNA's ...,0.684211,"(0.6, 0.8]"
3986,HELP FOR ELDERLYON THEIR OWN: Campaign targe...,Town hall bosses across the region want to set...,LONELINESS and ill health among Greater Manche...,NaN,Manchester Evening News; Glasgow (UK)\n\nFirst...,2015,"May 27, 2015",News,MGN Ltd.,Glasgow (UK),...,News,1683212907,https://www.proquest.com/globalnewsfed/newspap...,2015-05-27,177.0,1.000000,"['productivity', 'australia', 'political', 'ho...","Greater Manchester's 10 councils, New Economy ...",0.684211,"(0.6, 0.8]"
4245,Swap shop on wellbeing and health at Zinc Arts...,"Anne Brown, Essex County Council's cabinet mem...",A SWAP shop providing the opportunity to debat...,Barter,Brentwood Gazette; Brentwood (UK)\n\nFirst pag...,2015,"Jan 28, 2015",News,MGN Ltd.,Brentwood (UK),...,News,1648514759,https://www.proquest.com/globalnewsfed/newspap...,2016-03-13,177.0,1.000000,"['productivity', 'australia', 'political', 'ho...","Speakers include Christina Victor, professor o...",0.684211,"(0.6, 0.8]"
4673,Forums tackle aged concerns,SINGLE aged pensioners in the New England regi...,SINGLE aged pensioners in the New England regi...,Older people; Elder care; Aging; Meetings; Bab...,"The Northern Daily Leader; Tamworth, N.S.W.",2016,"Jun 2, 2016",NaN,Rural Press Pty Ltd Australian Community Media...,"Tamworth, N.S.W.",...,News,1793679124,https://www.proquest.com/globalnewsfed/newspap...,2016-06-03,177.0,1.000000,"['productivity', 'australia', 'political', 'ho...","""You can electronically monitor the bodily hea...",0.684211,"(0.6, 0.8]"
7048,Project brings Protestants and Catholics toget...,None available.,A PEACE IV Project allowing local people from ...,Older people; Aging,News Letter; Belfast\n\nFirst page: 33,2020,"Dec 4, 2020",News,NLA Media,Belfast,...,News,2466684533,https://www.proquest.com/newspapers/project-br...,2020-12-04,177.0,1.000000,"['productivity', 'australia', 'political', 'ho...",While some of the latter activities were curta...,0.684211,"(0.6, 0.8]"
7378,Help to the homeless,None available.,HOMELESS people in central Melbourne will be h...,Coronaviruses; Homeless people; Pandemics; COV...,"Herald Sun; Melbourne, Vic.\n\nFirst page: 21",2020,"May 17, 2020",News,Nationwide News Pty Ltd,"Melbourne, Vic.",...,News,2403828147,https://www.proquest.com/newspapers/help-homel...,2020-05-18,177.0,1.000000,"['productivity', 'australia', 'political', 'ho...",The budget will also include a further $1 mill...,0.684211,"(0.6, 0.8]"
8104,What next for the social care sector?,None available.,The future of social care was discussed in a n...,Leadership\n\nBusiness indexing term: Subject:...,The Herald; Glasgow (UK)\n\nFirst page: 15,2021,"Mar 30, 2021",NaN,Gannett Media Corp,Glasgow (UK),...,News,2506703446,https://www.proquest.com/newspapers/what-next-...,2021-03-30,177.0,1.000000,"['productivity', 'australia', 'political', 'ho...",“Labour’s leader seems to have focused on maki...,0.684211,"(0.6, 0.8]"
8106,PM must build back better for the elderly: C...,None available.,POLITICAL juggernauts Ken Clarke and David Blu...,Retirement communities; Task forces; Older peo...,Daily Express; London (UK)\n\nFirst page: 6,2021,"Mar 29, 2021",News,Express Newspapers PLC,London (UK),...,News,2506127473,https://www.proquest.com/newspapers/pm-must-bu...,2021-03-30,177.0,1.000000,"['productivity', 'australia', 'political', 'ho...","Conservative MP Damian Green, who chairs the A...",0.684211,"(0.6, 0.8]"
8107,"A promising care plan: One Canada Square, Lo...",None available.,JUST as the end of the Second World War herald...,NaN,Daily Express; London (UK)\n\nFirst page: 12,2021,"Mar 29, 2021",News,Express Newspapers PLC,London (UK),...,News,2506127451,https://www.proquest.com/newspapers/promising-...,2021-03-30,177.0,1.000000,"['productivity', 'australia', 'political', 'ho...","It is not just the fear of dying in one, but t...",0.684211,"(0.6, 0.8]"
10303,Time to address inequalities faced by Roma com...,None available.,HEALTH outcomes amongst the UK’s Roma communit...,Health disparities; Romani people; Health care...,The Herald; Glasgow (UK)\n\nFirst page: 21,2024,"Mar 2, 2024",NaN,Gannett Media Corp,Glasgow (UK),...,News,2933693415,https://www.proquest.com/globalnewsfed/newspap...,2024-03-02,177.0,1.000000,"['productivity', 'australia', 'political', 'ho...","From a healthcare angle, we need a “systems ch...",0.684211,"(0.6, 0.8]"
10680,"We’ve got issues, but we’re still a lucky country",None available.,BeyondWords Text to Speech David's voice Austr...,Birth rate; Fertility; Gross Domestic Product-...,"The Australian (Online); Canberra, A.C.T.",2025,"May 27, 2025",NaN,Nationwide News Pty Ltd,"Canberra, A.C.T.",...,News\n\nPublication history : \n\nMilestone da...,3212794044,https://www.proquest.com/globalnewsfed/newspap...,2025-05-28,177.0,1.000000,"['productivity', 'australia', 'political', 'ho...",There is no certainty we can continue to impro...,0.684211,"(0.6, 0.8]"
10732,AUSTRALIA CAN BE BIG AND BOLD,None available.,Labor should use its super-sized electoral maj...,Standard of living; Workers; Fertility; Foreig...,"Weekend Australian; Canberra, A.C.T.\n\nFirst ...",2025,"May 10, 2025",Inquirer,Nationwide News Pty Ltd,"Canberra, A.C.T.",...,News,3202200902,https://www.proquest.com/globalnewsfed/newspap...,2025-05-10,177.0,1.000000,"['productivity', 'australia', 'political', 'ho...",While he doesn’t doubt there are visions for A...,0.684211,"(0.6, 0.8]"
10736,"With Labor’s super-sized majority, it’s time t...",None available.,BeyondWords Text to Speech David's voice Among...,Standard of living; Workers; Fertility; Foreig...,"The Australian (Online); Canberra, A.C.T.",2025,"May 8, 2025",NaN,Nationwide News Pty Ltd,"Canberra, A.C.T.",...,News\n\nPublication history : \n\nMilestone da...,3202190611,https://www.proquest.com/globalnewsfed/newspap...,2025-05-10,177.0,1.000000,"['productivity', 'australia', 'political', 'ho...",There are decent building blocks in place for ...,0.684211,"(0.6, 0.8]"

In [56]:
df = remove_topic(df,177,[])

The orig length:10854 -> cropped: 10835

### Topic rel_ratio 0.8 - 1

In [57]:
df[(df["rel_ratio"] > 0.8) & (df["rel_ratio"] <= 1)]['topic'].unique()

array([ 55.,  56.,  58., 116.,  -1.,   8.,  51.,  24.,  86.,  29.,  50.,
       107.,  40.,   4.,  23.,   5., 189.,  98.,  44.,  14.,   1., 105.,
       109., 187., 138.,  13., 110., 142.,  16.,  66., 170., 148.,  91.,
       215., 154.,  21.,  46., 137., 165.,  49.,   7., 159.,  11., 132.,
         2.,  95., 139., 163., 190.,  27.,  18., 103., 202.,  10.,  77.,
        41.,  39., 213.,  42.,  43., 191., 211., 153.,  96., 117.,  19.,
       218., 208.,  92., 205., 130.,  75.,  84.,  36., 166., 106., 150.,
       184., 220., 128., 209.,  76.,  79.,  89.,  88., 112., 173.,  63.,
       157., 197.,  52.,  80., 175.,  15.,  38.,  87.,  22.,  64.,  37.,
       186.,  31.,  57.,  69., 129., 101., 127.,  61.,  32., 133., 207.,
       162.,  35., 182., 146., 200., 156., 100., 124., 203., 192.,  73.,
       185., 206.,   3., 195., 102., 221.,  68.,  53.,  60., 145., 180.,
        71., 223.,  93., 167.,  90., 119., 161.,  78., 179., 183., 143.,
        99.,  65., 225., 224., 169., 144., 176., 194., 168., 226., 172.,
       149., 171., 204.,  25., 111., 193.])

In [58]:
subset = df[(df["rel_ratio"] > 0.8) & (df["rel_ratio"] <= 1)]
for topic, keywords in subset.groupby('topic')['topic_keywords'].unique().items():
    print(topic, "\n", keywords)

-1.0
 ['[]']
1.0
 ["['india', 'senior citizens', 'citizens', 'geriatric', 'elders', 'welfare', 'indian', 'government', 'programme', 'delhi', 'older persons', 'ministry', 'healthy ageing', 'facilities', 'organised', 'published ht', 'ht', 'permission', 'geriatric medicine', 'homes', 'old age', 'content', 'elderly people', 'policy', 'sector', 'occasion', 'programmes', 'world health', 'palliative', 'requirement']"]
2.0
 ["['foods', 'vitamin', 'eat', 'eating', 'vegetables', 'fats', 'fish', 'vitamins', 'fruits', 'nuts', 'grains', 'nutrients', 'protein', 'beans', 'meat', 'sugar', 'dietary', 'fruits vegetables', 'fruit', 'eggs', 'mediterranean', 'diets', 'antioxidants', 'dairy', 'oil', 'intake', 'heart disease', 'rice', 'red', 'cholesterol']"]
3.0
 ["['al', 'rehabilitation', 'geriatric', 'clinic', 'corporation', 'patient', 'national health', 'strategy', 'geriatrics', 'healthy ageing', 'integrated', 'longterm care', 'medical director', 'primary', 'syndigateinfo', 'programme', 'syndigate', 'provided syndigate', 'media syndigateinfo', 'syndigate media', 'tribune', 'collaboration', 'agefriendly', 'older persons', 'clinics', 'teams', 'unit', 'ministry', 'evidencebased', 'explained']"]
4.0
 ["['australians', 'retirement', 'village', 'australia', 'residential', 'sector', 'council', 'communities', 'australian', 'rural', 'housing', 'government', 'ageing population', 'residents', 'transport', 'healthy ageing', 'strategy', 'workforce', 'ms', 'agefriendly', 'organisations', 'councils', 'providers', 'intergenerational', 'health wellbeing', 'isolation', 'care services', 'port', 'mr', 'district']"]
5.0
 ["['cells', 'stem', 'scientists', 'drugs', 'cell', 'humans', 'drug', 'antiageing', 'biology', 'animals', 'slow', 'agerelated', 'trials', 'extend', 'biological', 'longevity', 'lifespan', 'genes', 'scientific', 'reverse', 'field', 'harvard', 'ageing process', 'therapies', 'agerelated diseases', 'tissue', 'die', 'span', 'scientist', 'cellular']"]
7.0
 ["['falls', 'falling', 'balance', 'injuries', 'injury', 'strength', 'fear', 'vision', 'medications', 'matter', 'deaths', '65 older', 'county', 'emergency', 'leg', 'hip', 'centers disease', 'exercises', 'disease control', 'preventing', 'extension', 'leading cause', 'fallen', 'awareness', 'tai', 'classes', 'class', 'mobility', 'control prevention', 'independence']"]
8.0
 ["['pm', 'st', 'ave', 'club', 'road', 'saturday', 'library', 'church', 'oct', 'noon', 'port', 'county', 'museum', 'park', 'friday', 'tickets', 'sale', 'thursday', 'sunday', 'nov', '730', 'drive', '10 pm', '630', 'registration', 'april', 'doors', 'christmas', 'beach', 'high school']"]
10.0
 ["['agefriendly', 'hamilton', 'friendly', 'communities', 'council', 'housing', 'town', 'residents', 'spaces', 'buildings', 'village', 'committee', 'mayor', 'cities', 'bc', 'outdoor', 'vancouver', 'accessible', 'transportation', 'participation', 'survey', 'province', 'longterm care', 'citys', 'parks', 'inclusion', 'space', 'recreation', 'shore', 'cent']"]
11.0
 ["['weight', 'obesity', 'weight loss', 'obese', 'fat', 'eating', 'lose weight', 'lose', 'overweight', 'gain', 'eat', 'mass', 'pounds', 'body mass', 'muscle', 'foods', 'calories', 'type diabetes', 'physical activity', 'middle', 'im', 'percent', 'happiness', 'youre', 'sugar', 'diets', 'habits', 'sleep', 'losing', 'protein']"]
13.0
 ["['lifespan', 'gene', 'humans', 'cells', 'cellular', 'genes', 'scientists', 'cell', 'proteins', 'animals', 'metabolism', 'effect', 'metabolic', 'mechanisms', 'discovery', 'discovered', 'glucose', 'species', 'longevity', 'protein', 'dietary', 'pathways', 'compound', 'agerelated diseases', 'response', 'extend', 'energy', 'published', 'dna', 'agerelated']"]
14.0
 ["['uk', 'innovation', 'european', 'industrial', 'investment', 'economy', 'jobs', 'climate', 'universities', 'business', 'funding', 'east', 'strategy', 'businesses', 'global', 'industry', 'projects', 'technology', 'economic', 'companies', 'growth', 'britain', 'sciences', 'prof', 'fund', 'union', 'technologies', 'council', 'sector', 'europe']"]
15.0
 ["['nursing', 'nursing homes', 'province', 'nursing home', 'homes', 'government', 'summit', 'beds', 'stakeholders', 'longterm care', 'minister', 'aging population', 'premier', 'panel', 'council', 'communities', 'home care', 'organizations', 'cent', 'collaborative', 'ideas', 'hospitals', 'governments', 'executive director', 'strategy', 'weve', 'citizens', 'canada', 'theyre', 'discussion']"]
16.0
 ["['dairy', 'milk', 'products', 'consumers', 'product', 'india', 'markets', 'consumer', 'market', 'ingredients', 'industry', 'asia', 'protein', 'growth', 'brand', 'global', 'nutritional', 'china', 'sales', 'new zealand', 'zealand', 'companies', 'demand', 'business', 'ireland', 'innovation', 'pacific', 'billion', 'value', 'functional']"]
18.0
 ["['loneliness', 'isolation', 'pandemic', 'lonely', 'social isolation', 'percent', 'coronavirus', 'isolated', 'covid19', 'survey', 'feeling', 'friends family', 'relationships', 'felt', 'adults ages', 'reported', 'video', 'visits', 'loved', 'connect', 'vulnerable', 'connections', 'avoid', 'depression', 'spread', 'social media', 'family members', 'technology', 'visiting', 'family friends']"]
19.0
 ["['vaccine', 'flu', 'vaccines', 'covid19', 'shot', 'complications', 'infection', 'immunity', 'phone', 'protect', 'respiratory', 'cases', 'infectious', 'dose', 'infections', 'immune', 'appointments', 'respondents', 'coronavirus', 'protected', 'providers', 'percent', 'clinics', 'vulnerable', 'india', 'deaths', '50 years', 'disease control', 'adult', 'season']"]
21.0
 ["['gut', 'inflammation', 'inflammatory', 'composition', 'immune', 'diversity', 'beneficial', 'foods', 'mediterranean', 'frailty', 'oil', 'minutes', 'species', 'published', 'linked', 'harmful', 'function', 'acids', 'showed', 'barrier', 'reduced', 'heat', 'olive oil', 'metabolism', 'olive', 'chemicals', 'immunity', 'findings', 'vegetables', 'agerelated']"]
22.0
 ["['physical activity', 'minutes', 'muscles', 'heart rate', 'minute', 'exercises', 'fitness', 'weight', 'regular exercise', 'exercising', 'sedentary', 'intensity', 'fit', 'running', 'cardiovascular', 'strength', 'physically', 'physically active', 'aerobic', 'late', 'moderate', 'sustained', 'walk', 'walking', '30 minutes', 'workout', 'moving', 'inactivity', 'health benefits', 'lose']"]
23.0
 ["['canada', 'canadians', 'government', 'minister', 'housing', 'communities', 'income', 'security', 'advocate', 'bc', 'governments', 'programs services', 'province', 'homes', 'extended', 'guide', 'aging population', 'federal', 'elders', 'organizations', 'affordable', 'action', 'tax', 'website', 'canadian', 'energy', 'pension', 'supplement', 'costs', 'long possible']"]
24.0
 ["['sleep', 'sleeping', 'night', 'bed', 'disorder', 'nights', 'disorders', 'watch', 'cardiovascular health', 'trouble', 'deep', 'breathing', 'hormone', 'poor', 'wake', 'tired', 'cardiovascular', 'rest', 'short', 'negative', 'lack', 'duration', 'minutes', 'schedule', 'suffer', 'clock', 'chris', 'alcohol', 'lifes', 'patterns']"]
25.0
 ["['alzheimers', 'al', 'alzheimers disease', 'awareness', 'diagnosis', 'geriatric', 'corporation', 'risk factors', 'memory', 'national health', 'symptoms', 'global', 'people dementia', 'said dr', 'condition', 'tribune', 'media syndigateinfo', 'syndigate', 'syndigate media', 'provided syndigate', 'syndigateinfo', 'consultant', 'reserved provided', 'memory loss', 'people living', 'rights reserved', 'caregivers', 'reserved', 'rehabilitation', 'september']"]
27.0
 ["['ymca', 'port', 'details', 'registration', 'medical center', 'instructor', 'mondays', 'class', 'screenings', 'fitness', 'arthritis', 'yoga', 'meets', 'classes', 'st', 'register', 'july', 'support group', 'april', 'pm', 'center healthy', 'active aging', 'tai', 'chi', 'tai chi', 'senior center', 'ave', 'tuesdays', 'thursdays', 'blue']"]
29.0
 ["['fitness', 'gym', 'workout', 'muscle', 'strength', 'trainer', 'minutes', 'physical activity', 'fit', 'weights', 'weight', 'youre', 'walking', 'muscles', 'walk', 'exercising', 'cycling', 'im', 'motivation', 'strength training', 'movement', 'routine', 'classes', 'running', 'mass', 'muscle mass', 'exercises', 'sport', 'intensity', 'aerobic']"]
31.0
 ["['johnson', 'longevity', 'oxygen', 'therapy', 'supplements', 'tech', 'sleep', 'die', 'im', 'wellness', 'treatments', 'claims', 'routine', 'chamber', 'forever', 'antiageing', 'founder', 'cold', 'mr', 'clinic', 'hes', 'son', 'biological', 'therapies', 'bed', 'cells', 'cellular', 'tests', 'extreme', 'function']"]
32.0
 ["['sleep', 'longevity', 'youre', 'heart disease', 'muscle', 'eat', 'voice', 'minutes', 'inflammation', 'live longer', 'eating', 'night', 'blood pressure', 'walking', 'alcohol', 'smoking', 'moderate', 'foods', 'drink', 'whats', 'fat', 'strength', 'sugar', 'teeth', 'muscles', 'vegetables', 'risk heart', 'weight', 'avoid', 'processed']"]
35.0
 ["['intelligence', 'artificial', 'technology', 'technologies', 'uk', 'innovation', 'digital', 'nhs', 'diagnosis', 'discovery', 'investment', 'systems', 'records', 'tool', 'companies', 'transform', 'detect', 'business', 'industrial', 'earlier', 'centres', 'smart', 'japan', 'global', 'health information', 'patient', 'businesses', 'programme', 'funding', 'economy']"]
36.0
 ["['technology', 'devices', 'digital', 'users', 'smart', 'device', 'internet', 'tech', 'watch', 'tracking', 'technologies', 'lab', 'phone', 'homes', 'tools', 'features', 'loneliness', 'boomers', 'app', 'monitor', 'design', 'monitoring', 'facebook', 'baby', 'consumers', 'mobile', 'search', 'baby boomers', 'social media', 'market']"]
37.0
 ["['projects', 'communitybased', 'funding', 'organizations', 'canada', 'inclusion', 'apply', 'communities', 'help seniors', 'abuse', 'eligible', 'grant', 'supporting', 'supports', 'government', 'minister', 'elder', 'grants', 'invited', 'receive', 'priorities', 'federal', 'diversity', 'stay active', 'promoting', 'participate', 'contributions', 'pandemic', 'celebrating', 'engaged']"]
38.0
 ["['pm', 'st', 'library', 'oct', 'road', '630', 'saturday', 'museum', '730', 'aug', 'meets', 'church', 'wed', 'ave', 'friday', 'club', 'music', 'tuesday', '930', 'welcome', 'art', 'thursday', 'street', 'sunday', 'league', '830', 'theatre', 'arts', 'dance', '29']"]
39.0
 ["['fruits', 'vegetables', 'antioxidants', 'sweet', 'fruits vegetables', 'fruit', 'vitamin', 'contain', 'red', 'health benefits', 'potatoes', 'cup', 'rich', 'fresh', 'properties', 'add', 'source', 'green', 'apple', 'seeds', 'contains', 'powerful', 'sugar', 'color', 'nutrients', 'vitamins', 'antiinflammatory', 'protect', 'white', 'eat']"]
40.0
 ["['festival', 'november', 'tea', 'expo', 'april', 'club', 'details', 'phone', 'heads', 'workshops', 'bay', 'morning', 'fun', 'entertainment', 'friday', 'sunday', 'sessions', 'hall', 'healthy ageing', 'celebrate', 'council', 'essential', 'october', 'leisure', 'parking', 'councils', 'wednesday', 'st', 'saturday', 'concert']"]
41.0
 ["['depression', 'psychological', 'psychiatry', 'cardiac', 'elders', 'anxiety', 'old age', 'cardiovascular', 'health problems', 'geriatric', 'feelings', 'symptoms', 'seek', 'awareness', 'ht', 'published ht', 'disorders', 'organised', 'permission', 'surgery', 'india', 'illness', 'content', 'disorder', 'heart disease', 'burden', 'professionals', 'transition', 'medication', 'feeling']"]
42.0
 ["['meals', 'meal', 'wheels', 'hunger', 'peace', 'clients', 'agency', 'illinois', 'ice', 'volunteers', 'hot', 'dining', 'atlanta', 'delivery', 'sarah', 'delivered', 'funding', 'grocery', 'volunteer', 'nutritious', 'senior center', 'restaurant', 'receive', 'deliver', 'county', 'business', 'serves', 'counties', 'central', 'friday']"]
43.0
 ["['frailty', 'frail', 'wales', 'healthy ageing', 'people aged', 'australia', 'poor', 'ageing population', 'aged 65', 'agefriendly', 'new zealand', 'zealand', 'organisations', 'decade', 'nhs', 'gerontology', 'cent', 'active healthy', 'district', 'launch', 'programme', '75', 'interventions', 'contribution', 'survey', 'policy', 'inevitable', 'uk', 'australians', 'issue']"]
44.0
 ["['medication', 'medications', 'september', 'doctor', 'staying', 'habits', 'medicines', 'prescription', 'smoking', 'balance', 'make sure', 'blood pressure', 'walking', 'physically', 'high blood', 'loved', 'regularly', 'foods', 'physical activity', 'eat', 'falls', 'checkups', 'healthy lifestyle', 'consider', 'ask', 'list', 'physical mental', 'guide', 'americans', 'physician']"]
46.0
 ["['protein', 'plantbased', 'muscle', 'plant', 'meat', 'eggs', 'intake', 'animal', 'beans', 'muscle mass', 'proteins', 'foods', 'ate', 'milk', 'sources', 'mass', 'cup', 'add', 'weight', 'dietary', 'meal', 'trends', 'vegetables', 'nuts', 'eating', 'dairy', 'products', 'recipes', 'eat', 'trend']"]
49.0
 ["['new york', 'older americans', 'york', 'elder', 'americans', 'longterm care', 'housing', 'abuse', 'security', 'social security', 'medicare', 'master', 'federal', 'administration', 'residents', 'conference', 'financial', 'nursing', 'states', 'retirement', 'justice', 'affordable', 'act', 'advocates', 'agencies', 'income', 'caregivers', 'homes', 'florida', 'communities']"]
50.0
 ["['tax', 'centers', 'county', 'aarp', 'conference', 'volunteers', 'ward', 'michigan', 'sessions', 'york', 'caregivers', 'secretary', 'income', 'senior center', 'presentations', 'grant', 'volunteer', 'atlanta', 'cabinet', 'caregiver', 'topics', 'agency', 'agencies', 'session', '55', 'elders', 'listening', 'showing', 'commission', 'texas']"]
51.0
 ["['art', 'creative', 'singing', 'arts', 'music', 'museum', 'concert', 'residents', 'sense', 'expression', 'teaching', 'ms', 'memory', 'york', 'conference', 'professional', 'joy', 'fun', 'class', 'alzheimers', 'drawing', 'cultural', 'plays', 'created', 'musical', 'began', 'nov', 'studio', 'therapist', 'voice']"]
52.0
 ["['blue', 'black', 'zone', 'linda', 'life expectancy', 'expectancy', 'longevity', 'white', 'centenarians', 'states', 'purpose', 'united states', 'environmental', 'dan', 'socioeconomic', 'habits', 'status', 'male', 'rates', 'united', 'healthy life', 'people live', 'italy', 'survival', 'plantbased', 'beans', 'percent', 'mortality', 'odds', 'neighborhood']"]
53.0
 ["['longevity', 'dna', 'global', 'wellness', 'al', 'ceo', 'sector', 'innovation', 'investments', 'advanced', 'personalized', 'therapy', 'scientific', 'therapies', 'functional', 'knowledge', 'vision', 'aims', '2024', 'holistic', 'investment', 'field', 'region', 'largest', 'capital', 'innovative', 'expertise', 'billion', 'platform', 'healing']"]
55.0
 ["['courses', 'lifelong learning', 'classes', 'students', 'lifelong', 'writing', 'class', 'lectures', 'campus', 'student', 'topics', 'interested', 'taught', 'gerontology', 'educational', 'spring', 'continuing', 'history', 'lifetime', 'reading', 'florida', 'colleges', 'offered', 'georgia', 'joy', 'degree', 'registration', 'retired', 'state university', 'membership']"]
56.0
 ["['memory', 'honor', 'board', 'wheels', 'equipment', 'volunteers', 'meals', 'donations', 'pieces', 'classes', 'appointments', 'rides', 'committee', 'directors', 'memorial', 'susan', 'disabled', 'total', 'barbara', 'pat', 'volunteer', 'attending', 'attended', 'dignity', 'contribution', 'chairs', 'secrets', 'creates', 'miles', 'december']"]
57.0
 ["['sport', 'sports', 'gym', 'fitness', 'physical activity', 'equipment', 'classes', 'football', 'outdoor', 'lake', 'ireland', 'fit', 'sessions', 'club', 'programme', 'shed', '50s', 'exercising', 'games', 'grant', 'recreation', 'mens', 'healthy ageing', 'organisations', 'gold', 'clubs', 'retirement', 'promoting healthy', 'class', 'aimed']"]
58.0
 ["['womens health', 'womens', 'gender', 'pregnancy', 'australian', 'suicide', 'eggs', 'sex', 'policy', 'guidelines', 'strategy', 'australia', 'ill', 'male', 'screening', 'sexual', 'menopause', 'life expectancy', 'expectancy', 'female', 'deaths', 'prostate', 'mothers', 'woman', '100000', '2022', 'mens', 'girls', 'gap', 'healthy ageing']"]
60.0
 ["['countries', 'ageism', 'abuse', 'decade', 'older persons', 'global', 'aged 60', 'policies', 'united nations', 'healthy ageing', 'nations', 'world health', '2050', 'action', 'civil', 'health organization', 'dignity', 'respect', '60 years', 'billion', 'longterm care', 'attitudes', 'people aged', 'societies', 'elder', 'progress', 'united', 'media', 'negative', 'poverty']"]
61.0
 ["['yoga', 'traditional', 'india', 'modern', 'holistic', 'practices', 'body mind', 'ancient', 'meditation', 'therapies', 'pain', 'class', 'soul', 'healing', 'indian', 'longevity', 'breathing', 'natural', 'treatments', 'energy', 'nature', 'medicines', 'relief', 'flexibility', 'relaxation', 'spiritual', 'systems', 'balance', 'breath', 'conventional']"]
63.0
 ["['womens health', 'womens', 'menopause', 'offices', 'hormone', 'cardiovascular disease', 'brown', 'cardiovascular', 'breast cancer', 'jackson', 'breast', 'healthy ageing', 'cent', 'social security', 'heart disease', 'therapy', 'sleep', 'gene', 'processed', '70', 'brain health', 'men women', 'secrets', 'chronic disease', 'ireland', 'screening', 'linked', '30 years', 'security', 'later years']"]
64.0
 ["['los angeles', 'angeles', 'los', 'successful aging', 'expo', 'dean', 'photo', '2019', 'hills', 'successful', 'band', 'saturday', 'april', 'music', '2018', 'assisted living', 'guests', 'assisted', 'residents', 'fun', 'older americans', 'audience', 'dance', 'valley', 'americans', 'sponsors', 'walker', 'playing', 'walk', 'hospitals']"]
65.0
 ["['drug', 'drugs', 'trial', 'humans', 'effects', 'antiaging', 'animals', 'scientists', 'dose', 'agerelated', 'trials', 'type diabetes', 'immune', 'clinical', 'delay', 'extend', 'agerelated diseases', 'slow', 'longevity', 'widely', 'pharmaceutical', 'lifespan', 'aging research', 'clinical trials', 'cells', 'healthy people', 'type', 'prescribed', 'administration', 'target']"]
66.0
 ["['sport', 'sports', 'football', 'players', 'games', 'tennis', 'playing', 'film', 'game', 'womens', 'im', 'played', 'fun', 'ball', 'player', 'match', 'record', 'apple', 'pool', 'competition', 'court', 'heart rate', 'king', 'fitness', 'festival', 'male', 'physical activity', '90', 'hes', 'youre']"]
68.0
 ["['nuts', 'california', 'acid', 'consumption', 'handful', 'cholesterol', 'plantbased', 'dietary', 'cardiovascular', 'fatty', 'commission', 'cardiovascular disease', 'linda', 'health benefits', 'heart disease', 'fats', 'heart health', 'acids', 'ani', 'eating', 'lower risk', 'findings', 'nutrients', 'reduced', 'weight', 'consumed', 'study participants', 'trial', 'source', 'intake']"]
69.0
 ["['alzheimers association', 'alzheimers', 'chapter', 'social engagement', 'register', 'illinois', 'engagement', 'handson', 'incorporate', 'healthy living', 'workshop', 'recommendations', 'tools', 'nov', 'library', 'african', 'cognitive', 'ave', 'tips', 'alzheimers disease', 'shore', 'road', 'insights', 'pm', 'habits', 'reduce risk', 'wednesday', 'thursday', 'connected', 'lifestyle choices']"]
71.0
 ["['optimistic', 'confidence', 'emotions', 'lifespan', 'lee', 'outlook', 'live longer', 'stressful', 'boston', 'confident', '85', 'negative', 'relatively', 'exceptional', 'situations', 'university school', 'suggests', 'findings', 'completed', 'achieve', 'school medicine', 'longevity', 'link', 'religious', 'psychological', 'thinking', 'said research', 'risk factors', 'glass', 'premature']"]
73.0
 ["['senior citizens', 'citizens', 'government', 'healthy ageing', 'ageing population', 'welfare', 'parents', 'nation', 'conference', 'policy', 'cent', 'world health', 'infrastructure', 'policies', 'congress', 'commission', 'health services', 'decade', 'health organization', 'profile', 'homes', 'agencies', 'aged 60', 'nations', 'facilities', 'action', '2030', '2023', 'older persons', 'centres']"]
75.0

#### Topic 8

In [59]:
show(df[df['topic']==8]['Title'])

In [60]:
df.loc[10806,'Full text']

'According to an ever-increasing army of biohackers who are taking a DIY approach to making their brains, bodies and heart function better, and longer, death may be optional. As a cardiologist, here’s my take and what I do myself Death may be optional. At least, that is according to an ever-increasing army of biohackers who are taking a DIY approach to making their brains, bodies and hearts function better, and longer, by “hacking” their biology. Devotees of biohacking use biology, science, personal and shared experience, and technology to optimise health, wellbeing and lifespan, often with lifestyle interventions but sometimes with self-experimentation. The list of “biohacks” is extensive and includes extreme diets, supplement use, juicing, red-light therapy, cold exposure in the form of ice baths and cryotherapy, nootropics (aka “smart drugs”), full-body scans and frequent blood tests. At the most extreme end, biohackers are even attempting to modify their bodies with DIY gene-editing and self-implanted devices. With claims that you prevent memory loss, stop your hair turning grey and even change your DNA, it’s easy to see why biohacking is catching people’s attention. But as a cardiologist who has a vested interest in people living long and healthy lives, I’d prefer people listen to the science than to Hailey Bieber or Bryan Johnson. So just how credible are these claims, are they worth spending money on and, most importantly of all, are they any good for the body and the heart? Supplements Starting at the more “normal” end of the biohacking spectrum is supplementation. While taking the odd fish oil tablet to boost our omega 3s may be relatively harmless, in extreme cases some biohackers are living on extensive and costly regimes of hundreds of supplements such as NAD + in a bid to achieve peak nutrition. But the reality is that we don’t need anything more than a healthy, balanced diet to get the nutrients we need. The benefit of supplementation only comes for people with a known nutrient or mineral deficiency, typically identified through blood testing. For everyone else the best-case scenario is expensive urine. Worst case? Toxic levels of nutrients build up in the body – as has been seen in recent reports of peripheral neuropathy in people who unknowingly consumed high amounts of vitamin B6 through supplements. Supplements may also come with safety risks – particularly overseas-imported supplements that may contain stimulants or derivatives of amphetamines. This can be the case with nootropics – also referred to as “smart drugs” – which claim to improve cognition and boost brain power. But while stimulants can be used to treat conditions such as ADHD, misuse in the form of over-the-counter supplements can come with serious side-effects – including increased heart rate and blood pressure. This is of particular concern for those with underlying heart issues. These drugs may also interact with existing medications, which is why they should be used only under the guidance of your doctor. Diet Dietary changes are also a mainstay of biohacking in a similar way to supplements. Of particular note are the more extreme diets, such as the meat-heavy carnivore diet. While it’s true there are a variety of ways to achieve a healthy diet, there are some fundamentals that come up time and again in research. A recent 30-year study of more than 100,000 people found those who ate more fruits, vegetables, whole grains, unsaturated fats, nuts, legumes and low-fat dairy products had a higher likelihood of healthy ageing. On the flip side, the study found higher intakes of trans fats, sodium, sugary beverages and red or processed meats (or both) were negatively associated with healthy ageing. This confirms one truth we have long known about nutrition – eating a balanced diet with plenty of plant foods, with low or moderate amounts of animal foods, is good for our health and longevity. Cold exposure Most of us know people who swear a morning ice bath has changed their lives. But while ice baths can be beneficial for muscle recovery and wellbeing, the science is still out on whether cold exposure offers any longevity benefits. While initial research findings suggested there may be time-dependent effects of cold-water immersion (including cold shower, ice bath, or plunge) on inflammation, stress, immunity, sleep quality and quality of life, researchers involved in these studies note that more research is needed to understand whether this effect is long-term, and the potential impacts on different populations. Along with being unclear about its benefits, cold exposure also comes with its risks – including an initial shock to the body that causes vasoconstriction, where the blood vessels constrict to conserve heat. This results in a jump in blood pressure and heart rate, which can trigger irregular heartbeats – aka arrhythmias. In a healthy person, this may not be an issue, but for those with existing heart conditions it could be dangerous – whether they have been diagnosed yet or not. For those who want to experiment with cold exposure, it’s important to discuss it with your doctor – and never do it alone. Red-light therapy Red-light therapy is an emerging therapy that exposes a person to low levels of red light. So far, the therapy looks promising for skin health – such as treating acne, signs of ageing and skin cancers, etc. But research on heart health and longevity is still in its infancy. While potential benefits have been noted in animal and in vitro studies such as lower rates of blood clots, the potential slowing down of cardiovascular ageing and also delayed onset of heart attack, stroke and high blood pressure, these are yet to be verified through large-scale clinical trials in humans. Full-body scans Being able to scan your whole body and find any underlying issues may be a tempting prospect. But full body CT or MRI can be eye-wateringly expensive – in excess of $1000. These scans also have their fair share of downsides, including unnecessary exposure to radiation for a CT scan, contrast dyes, false positives, incidental findings and overdiagnosis of issues that would never have caused any noticeable problems. There is also no strong evidence for the benefits of full-body scans over more targeted screening for conditions such as breast and bowel cancer. Along with these risks, full-body scans can have significant impacts on a person’s mental health – causing us to worry about things we need never have worried about. Following a targeted screening program based on your sex, age and risk factors is a much more effective, less time-consuming and less expensive way to go. If not biohacking, then what? It’s boring, but ultimately true, that the best place to start is by doubling down on the fundamentals before you start putting your time and money into strategies whose benefits are unclear. Maintaining a healthy lifestyle These fundamentals include eating a healthy diet with plenty of plant foods, getting regular exercise and good-quality sleep, minimising stress and pollution exposure (including light and noise pollution), quitting smoking and drinking less alcohol or, ideally, no alcohol. Almost no one I see as a cardiologist has perfected all these areas. In fact, only 5 per cent of us get our recommended fruit and veg each day. Keeping a check on your blood pressure, blood sugar and cholesterol levels Along with these basics, there is a point to be made for tighter control of blood pressure, cholesterol and blood glucose – as we know that if not controlled well, these factors can increase the risk of heart disease and other chronic illnesses that have significant impacts on both quality of life and longevity. This may include both lifestyle changes and more aggressive use of medications, such as cholesterol-lowering statins in those with elevated levels. The introduction of GLP-1 receptor agonists such as semaglutide (marketed as Ozempic and Wegovy) may also have a role to play in managing these risk factors. However, what impact they could have on longevity in people of normal body weight and without diabetes or heart disease is unknown. Building a good relationship with your GP is also important as this can help guide you on how to manage potential risk factors, identify health issues early, and get individualised advice on the best approach to blood testing and other screening tools. Along with regular blood tests to check the standard cholesterol panel (total cholesterol, LDL “bad” cholesterol, HDL “good” cholesterol and triglycerides), it may also be worth being tested for Lp(a), also known as Lipoprotein(a). This is another type of “bad cholesterol” associated with increased heart disease risk. Lp(a) is influenced by our genetics, and hence it can be high even in those who live a healthy lifestyle. Testing of Lp(a) levels is not currently covered by Medicare, but most people only need to be tested once, and in Australia the cost for an Lp(a) blood test is about $50. The medical tests proven to work Coronary artery calcium scoring, sometimes referred by doctors to as a “CAC score”, may also be appropriate for people with intermediate risk of heart disease, for example, those with one or more risk factors, or those in their 50s and 60s. This test uses a CT scan of the heart to measure the amount of calcified plaque (calcium) in the walls of the coronary arteries that supply blood to the heart, and can help to estimate your 10-year risk of heart attack or stroke. With this knowledge we can then identify patients who would benefit from particularly aggressive risk factor management. A CT coronary angiogram is another test that is particularly helpful for people who are experiencing chest pain to determine if that chest pain is due to coronary obstructive disease or not. Some physicians perform them almost as an executive screening test in people who are not experiencing chest pain, but that’s not guideline-recommended. So, what are the headline takeaway messages? What do I tell my patients? And what do I do myself? Stick to what is proven and skip the expensive vitamin supplements and questionable potions. If you want to live a healthy and long life, make sure you do the very best you can by getting the fundamentals right. The American Heart Association refers to them as “life’s essential eight”: blood pressure, cholesterol, glucose levels (diabetes), healthy diet, exercise (more than 150 minutes of moderate intensity per week), maintaining a healthy body weight, not smoking, and getting the right amount of sleep (seven to nine hours for adults). The data supporting the importance of these eight modifiable factors for a healthy life is overwhelming. If you have any further questions, please speak to your doctor and try to avoid consulting social media. Professor Jason Kovacic is a cardiologist and director of the Victor Chang Cardiac Research Institute. This column is published for information purposes only. It is not intended to be used as medical advice and should not be relied on as a substitute for independent professional advice about your personal health or a medical condition from your doctor or other qualified health professional. CREDIT: JASON Kovacic'

***
Advertisement topic
***

In [61]:
df = remove_topic(df,8,[])

The orig length:10835 -> cropped: 10730

#### Topic 14

In [62]:
show(df[df['topic']==14]['Title'])

In [63]:
df.loc[2942,'Full text']

'URBANA -- Plans for a $13.3 million Feed Technology Complex at the University of Illinois got a $3.5 million boost from the state Friday. Gov. Pat Quinn visited campus to announce that the state will contribute money from the Illinois Jobs Now program toward the project on the UI\'s South Farms, which will replace the 1927 feed mill at the corner of Fourth Street and St. Mary\'s Road. The new Feed Technology Complex is a public-private partnership involving the UI, state of Illinois, industry partners and private donors. Archer Daniels Midland Co. will donate $1.5 million for the project, hoping to work with the UI to "create new and innovative food and feed solutions," according to Brent Fenton, president of the company\'s animal feeds division. The facility will allow students and professors to process customized animal feeds and support research and educational programs in crop and animal sciences, nutrition and food science. It will be used to develop technologies for the manufacture of animal and human foods, and will support research on safe food production, animal nutrition and sustainable livestock practices. The state money will go toward design and construction of the facility. No timetable has been set, as the UI needs to raise several million more dollars for the project, but planning will begin "very shortly," said Neal Merchen, associate dean for research in the College of Agricultural, Consumer and Environmental Sciences. The UI has committed $6 million toward the project, and the money from the state and ADM boosts the total raised to $11 million, he said. The Feed Technology Complex will be built on Race Street south of Curtis Road, across from the UI\'s beef cattle farm. The old feed mill sits in what is now the UI\'s Research Park, just south of State Farm Center. Other livestock- and animal-research facilities in that area have gradually been moved south over the past 15 years to make way for new development. Though the feed mill has done "yeoman\'s work" over the past 77 years in making the UI a global leader in animal nutrition research, the college needs a modern facility in line with university\'s research capabilities, Merchen said. "It needed to be moved. It was time," Merchen said. The new facility will give the college a much better training platform for students, providing skilled workers for the industry, he said. College officials said it will also be vital for research and education in food security and safety, alternative energy and health issues such as obesity, cancer and healthy aging. Many health researchers use farm animals in their studies, and diet preparation is key, Merchen said. Combined with the new Integrated Bioprocessing Research Laboratory already under construction, and renovation of the food-processing pilot plant, the new feed complex puts the UI in position to be the "national leader in research on food and feed processing, in addition to nutrition and animal science," he said. ACES Dean Robert Hauser said the facility should help graduates be aggressively recruited for positions in food manufacturing, feed technology, bioenergy and livestock industries. "We need to make sure our students breaking into agribusiness have access to cutting-edge technology and resources in order to keep the industry thriving," Quinn said in a news release. Credit: By JULIE WURTH, jwurth@news-gazette.com Illustration Caption: John Dixon/The News-Gazette Gov. Pat Quinn announces a $3. 5 million state grant Friday for the University of Illinois<< planned Feed Technology Complex. He was at the ACES Library in Urbana.'

***
This topic focuses mainly on innovation, technology, and while healthy aging is mentioned, it only comes in-between sentences, i.e. it is not the main topic of these articles.
***

In [64]:
df = remove_topic(df, 14, [])

The orig length:10730 -> cropped: 10650

#### Topic 38

In [65]:
df[df['topic']==38]

,Title,Abstract,Full text,Subject,Publication title,Publication year,Publication date,Section,Publisher,Place of publication,...,Document type,ProQuest document ID,Document URL,Last updated,topic,topic_prob,topic_keywords,last,rel_ratio,rel_bins
436,Your thanks,[...] we would also like to thank all of the v...,"Monday May 10, 2010 Editor of the Reformer: Th...",Fund raising; Travel; Libraries,"The Brattleboro Reformer; Brattleboro, Vt.",2010,"May 10, 2010",Opinion,"New England Newspapers, Inc.","Brattleboro, Vt.",...,News,252163348,https://www. proquest.com/globalnewsfed/newspa...,2011-11-01,38.0,0.064874,"['pm', 'st', 'library', 'oct', 'road', '630', ...","The cards, phone calls, generosity and incredi...",0.890909,"(0.8, 1.0]"
524,Channel 12,None available.,QVO|| SZ.?@.^¢}U¢O{.AQVSR¥ZS.T}¢.[O¢QV.?B;@> :...,NaN,"Idaho State Journal; Pocatello, Idaho\n\nFirst...",2010,"Mar 14, 2010",TV Schedules,Idaho State Journal,"Pocatello, Idaho",...,News,238850550,https://www.proquest.com/globalnewsfed/newspap...,2017-11-10,38.0,0.183601,"['pm', 'st', 'library', 'oct', 'road', '630', ...",[O'QV. @> 4:00 pm: Loma Linda University Churc...,0.890909,"(0.8, 1.0]"
545,Across the Valley: News from every city: Coa...,"Model schools show academic excellence, respon...",Community forum on violence is tonight A commu...,Scholarships & fellowships; Councils; Students...,"The Desert Sun; Palm Springs, Calif.",2010,"Mar 3, 2010",Valley,Gannett Media Corp,"Palm Springs, Calif.",...,News,439863159,https://www.proquest.com/globalnewsfed/newspap...,2017-11-16,38.0,0.131336,"['pm', 'st', 'library', 'oct', 'road', '630', ...",The library will provide the tools to make pai...,0.890909,"(0.8, 1.0]"
613,Daily guide,Teresa Heinz Kerry on breast cancer; Taste of ...,"ON BOSTON.COM Chat 10 a.m. Talk ""American Idol...",Musicians & conductors; Earthquakes; Classical...,"Boston Globe; Boston, Mass.",2010,"Jan 27, 2010",Living Arts,"Boston Globe Media Partners, LLC","Boston, Mass.",...,News,405196815,https://www.proquest.com/globalnewsfed/newspap...,2017-11-10,38.0,0.120763,"['pm', 'st', 'library', 'oct', 'road', '630', ...",NR (1951) Terminator 2: Judgment Day 10:30 p.m...,0.890909,"(0.8, 1.0]"
639,tv talk,"DAYTIME Early Show (7 a.m., CBS/2) - Airport l...","DAYTIME Early Show (7 a.m., CBS/2) - Airport l...",Aging; Television programs,"Newsday, Combined editions; Long Island, N.Y.\...",2010,"Jan 12, 2010",EXPLORE LI,Newsday LLC,"Long Island, N.Y.",...,News,280377388,https://www.proquest.com/globalnewsfed/newspap...,2017-11-07,38.0,0.086457,"['pm', 'st', 'library', 'oct', 'road', '630', ...","DAYTIME Early Show (7 a.m., CBS/2) - Airport l...",0.890909,"(0.8, 1.0]"
718,GATHERING IN GRATITUDE: Ceremony to honor ve...,None available.,"FAIRGROUNDS More than 1,000 people, including ...",Governors; Memorial services; Emotions,"Kitsap Sun; Bremerton, Wash.\n\nFirst page: A.1",2011,"Nov 21, 2011",Local,Gannett Media Corp,"Bremerton, Wash.",...,News,2582724766,https://www.proquest.com/globalnewsfed/newspap...,2021-10-18,38.0,0.066113,"['pm', 'st', 'library', 'oct', 'road', '630', ...","It's the camaraderie, he said. I like the spea...",0.890909,"(0.8, 1.0]"
746,Advisory CNN Wire Outlook,(CNN) -- Supervising News Editor Maggie Leung ...,(CNN) -- Supervising News Editor Maggie Leung ...,NaN,"St. Joseph News - Press; St. Joseph, Mo.",2011,"Nov 4, 2011",NaN,St. Joseph News - Press,"St. Joseph, Mo.",...,News,902235525,https://www.proquest.com/globalnewsfed/newspap...,2011-11-05,38.0,0.118151,"['pm', 'st', 'library', 'oct', 'road', '630', ...",COMMENTARY-Risman-Sexual-Harassment In my mind...,0.890909,"(0.8, 1.0]"
801,Community Briefing,None available.,ACTON CHILDREN COPING WITH STRESS - The Acton-...,NaN,"Boston Globe; Boston, Mass.",2011,"Oct 16, 2011",West,"Boston Globe Media Partners, LLC","Boston, Mass.",...,News,898515285,https://www.proquest.com/globalnewsfed/newspap...,2017-11-18,38.0,1.000000,"['pm', 'st', 'library', 'oct', 'road', '630', ...",Registration is required; call 617-730-2069 or...,0.890909,"(0.8, 1.0]"
869,Around Windham County,"A graduate of Wellesley College, Haas is the a...","Saturday September 24, 2011 In Bellows Falls ....",Books; Reading; Poets,"The Brattleboro Reformer; Brattleboro, Vt.",2011,"Sep 24, 2011",Lifestyle,"New England Newspapers, Inc.","Brattleboro, Vt.",...,News,893877392,https://ww w.proquest.com/globalnewsfed/newspa...,2011-09-24,38.0,0.135236,"['pm', 'st', 'library', 'oct', 'road', '630', ...",This course is being funded by the American Re...,0.890909,"(0.8, 1.0]"
958,Matteson will be Living History Day honoree on...,The local Batten Kill Valley Runners group has...,"Monday August 15, 2011 NORTH BENNINGTON -- Rob...",Awards & honors,"Bennington Banner; Bennington, Vt.",2011,"Aug 15, 2011",News,"New England Newspapers, Inc.","Bennington, Vt.",...,News,883410619,https://www.proquest. com/globalnewsfed/newspa...,2011-08-17,38.0,0.047032,"['pm', 'st', 'library', 'oct', 'road', '630', ...",He was president of the Vermont Antiques Deale...,0.890909,"(0.8, 1.0]"
1147,Tickets for Long Beach's TEDxSoCal go on sale ...,The conference is an independently organized e...,LONG BEACH - It's almost time to meet Long Bea...,NaN,"Press - Telegram; Long Beach, Calif.",2011,"May 12, 2011",News,Los Angeles Newspaper Group,"Long Beach, Calif.",...,News,866349842,https://www.proquest.com/globalnewsfed/newspap...,2011-05-13,38.0,1.000000,"['pm', 'st', 'library', 'oct', 'road', '630', ...",Rosie Romo - Chef and director of culinary ope...,0.890909,"(0.8, 1.0]"
1477,Community Calendar,PELHAM PARKS & RECREATION: Offers the followin...,TROOP 83 RECRUITMENT: Scout Troop 83 will hold...,NaN,"The Sun; Lowell, Mass.",2012,"Mar 27, 2012",Comunity Calendar,The Lowell Sun,"Lowell, Mass.",...,News,940972742,https://www.proquest.com/globalnewsfed/newspap...,2012-03-27,38.0,0.067640,"['pm', 'st', 'library', 'oct', 'road', '630', ...",Welcoming all parents to participate in curren...,0.890909,"(0.8, 1.0]"
1535,Briefly,"A two-day course on ""Medical Preparedness and ...",Program for medical staff AUBURN -- A two-day ...,NaN,"Sun Journal; Lewiston, Me.",2012,"Oct 9, 2012",Connections,Sun Journal,"Lewiston, Me.",...,News,1095408941,https://www.proquest.com/globalnewsfed/newspap...,2012-10-10,38.0,0.091170,"['pm', 'st', 'library', 'oct', 'road', '630', ...",The program will be based on a display of pres...,0.890909,"(0.8, 1.0]"
1659,Club News,BILLERICA SENIOR CENTER: 25 Concord Road; Bill...,Send information for this listing 10 days in a...,NaN,"The Sun; Lowell, Mass.",2012,"Aug 24, 2012",Lifestyle,The Lowell Sun,"Lowell, Mass.",...,News,1038366612,https://www.proquest.com/globalnewsfed/newspap...,2012-09-07,38.0,1.000000,"['pm', 'st', 'library', 'oct', 'road', '630', ...",YOUNG WRITERS' GROUP: Meets first & third Mon....,0.890909,"(0.8, 1.0]"
1980,Channel 12,None available.,"CHANNEL 12 SCHEDULE FOR MARCH 18-24 , 2012 Fea...",NaN,"Idaho State Journal; Pocatello, Idaho\n\nFirst...",2012,"Mar 18, 2012",Local,Idaho State Journal,"Pocatello, Idaho",...,News,928832121,https://www.proquest.com/globalnewsfed/newspap...,2017-11-19,38.0,1.000000,"['pm', 'st', 'library', 'oct', 'road', '630', ...",10:30 p.m.: The Conn Jackson 12:30 p.m.: Danci...,0.890909,"(0.8, 1.0]"
2003,WHAT'S UP - HEADS UP,None available.,WHAT'S UP FROM EVENTS.STLTODAY.COM 03.06 McDon...,NaN,"St. Louis Post - Dispatch; St. Louis, Mo.",2012,"Mar 6, 2012\n\nDateline: 0",News,"Pulitzer, Inc.","St. Louis, Mo.",...,News,926436927,https://www.proquest.com/globalnewsfed/newspap...,2017-11-19,38.0,1.000000,"['pm', 'st', 'library', 'oct', 'road', '630', ...",Plans for reinforcing an interior room can be ...,0.890909,"(0.8, 1.0]"
2029,"Little Argus - Feb. 21, 2012",RPENM speaker Retired Public Employees of New ...,Today Lions speaker Carlsbad Downtown Lions wi...,Parks & recreation areas; Christianity; Nomina...,"Carlsbad Current - Argus; Carlsbad, N.M.",2012,"Feb 20, 2012",News,Gannett Media Corp,"Carlsbad, N.M.",...,News,965055731,https://www.proquest.com/globalnewsfed/newspap...,2012-04-05,38.0,0.214977,"['pm', 'st', 'library', 'oct', 'road', '630', ...",Lions fundraiser The Carlsbad Downtown Lions C...,0.890909,"(0.8, 1.0]"
2135,Greater Boston author readings Dec. 15-21,"Glenn Morris (""Obligation for Justice"") reads ...","SUNDAY Ted Reinstein (""New England Notebook: O...",Aging; Libraries; Books\n\nCompany / organizat...,"Boston Globe; Boston, Mass.",2013,"Dec 15, 2013",Arts,"Boston Globe Media Partners, LLC","Boston, Mass.",...,News,1468079680,https://www.proquest.com/globalnewsfed/newspap...,2017-11-20,38.0,0.107880,"['pm', 'st', 'library', 'oct', 'road', '630', ...","SUNDAY Ted Reinstein (""New England Notebook: O...",0.890909,"(0.8, 1.0]"
2260,Berkshire Calendar for October 17-18,None available.,Today ART Berkshire Museum 'PaperWorks' Origam...,NaN,"The Berkshire Eagle; Pittsfield, Mass.",2013,"Oct 16, 2013",Calendar,"New England Newspapers, Inc.","Pittsfield, Mass.",...,News,1442474291,https://www.proquest.com/globalnewsfed/newspap...,2013-10-17,38.0,0.359844,"['pm', 'st', 'library', 'oct', 'road', '630', ...",Ongoing events must be updated monthly. Inform...,0.890909,"(0.8, 1.0]"
2287,"Berkshire Calendar, Oct. 4-5",None available.,Today ART Artswalk Arts openings along North S...,NaN,"The Berkshire Eagle; Pittsfield, Mass.",2013,"Oct 3, 2013",Calendar,"New England Newspapers, Inc.","Pittsfield, Mass.",...,News,1439290565,https://www.proquest.com/globalnewsfed/newspap...,2013-10-04,38.0,1.000000,"['pm', 'st', 'library', 'oct', 'road', '630', ...",Ongoing events must be updated monthly. Inform...,0.890909,"(0.8, 1.0]"
2290,"Calendar, October 3-4",None available.,Today ART Becket Arts Center Gallery Special E...,NaN,"The Berkshire Eagle; Pittsfield, Mass.",2013,"Oct 2, 2013",Calendar,"New England Newspapers, Inc.","Pittsfield, Mass.",...,News,1439110629,https://www.proquest.com/globalnewsfed/newspap...,2013-10-03,38.0,0.168563,"['pm', 'st', 'library', 'oct', 'road', '630', ...",Ongoing events must be updated monthly. Inform...,0.890909,"(0.8, 1.0]"
2338,"Calendar, September 12-13",None available.,"Today ART First Congregational Church of Lee ""...",NaN,"The Berkshire Eagle; Pittsfield, Mass.",2013,"Sep 11, 2013",Calendar,"New England Newspapers, Inc.","Pittsfield, Mass.",...,News,1433262868,https://www.proquest.com/globalnewsfed/newspap...,2013-09-18,38.0,0.066213,"['pm', 'st', 'library', 'oct', 'road', '630', ...",Ongoing events must be updated monthly. Inform...,0.890909,"(0.8, 1.0]"
2515,Today's news,KAREN HUPPERTZ FOR THE AJC FULTON Golf tournam...,COBB Black history tour beginning in Marietta ...,Firearms; Visual artists; Cities; Animal control,"The Atlanta Journal - Constitution; Atlanta, Ga.",2013,"Jun 16, 2013",METRO,"Atlanta Journal Constitution, LLC","Atlanta, Ga.",...,News,1367743866,https://www.proquest.com/globalnewsfed/newspap...,2017-11-20,38.0,0.051957,"['pm', 'st', 'library', 'oct', 'road', '630', ...",The presentation is for anyone considering bec...,0.890909,"(0.8, 1.0]"
3024,AROUND TOWN: Sept. 24,"Osher Lifelong Learning Institute: ""Inside the...","Wednesday Osher Lifelong Learning Institute: ""...",NaN,"The Tuscaloosa News; Tuscaloosa, Ala.",2014,"Sep 23, 2014",NaN,Halifax Media Group,"Tuscaloosa, Ala.",...,News,1564426840,https://www.proquest.com/newspapers/around-tow...,2014-09-24,38.0,0.064344,"['pm', 'st', 'library', 'oct', 'road', '630', ...",Registration required. Call Ann F. Smith at 20...,0.890909,"(0.8, 1.0]"
3071,Wednesday/10,"Celebrating National Senior Month 10:30 a.m., ...",Fitchburg Celebrating National Senior Month 10...,Art galleries & museums\n\nBusiness indexing t...,"Telegram & Gazette; Worcester, Mass.\n\nFirst ...",2014,"Sep 5, 2014",Weeklies,"GateHouse Media, Inc.","Worcester, Mass.",...,News,1559998710,https://www.proquest.com/newspapers/wednesday-...,2023-11-20,38.0,0.072898,"['pm', 'st', 'library', 'oct', 'road', '630', ...",1-2 p.m. and 6:30-7:30 p.m. Fitchburg Public L...,0.890909,"(0.8, 1.0]"
3140,Monday/28,Beaver Brook Farmers Market 9:30 a.m.-2 p.m. M...,Worcester Music Common Vision Tour featuring H...,NaN,"Telegram & Gazette; Worcester, Mass.\n\nFirst ...",2014,"Jul 25, 2014",Weeklies,"GateHouse Media, Inc.","Worcester, Mass.",...,News,1548136797,https://www.proquest.com/newspapers/monday-28/...,2017-11-21,38.0,0.136615,"['pm', 'st', 'library', 'oct', 'road', '630', ...","Music Singer/songwriter Lexi Weege, 8 p.m. Nic...",0.890909,"(0.8, 1.0]"
3145,Transcript Digest,-- Tuesday Night Blues 6:30-8 p.m. Todos Santo...,Digest Singin' the blues -- Tuesday Night Blue...,NaN,"Oakland Tribune; Oakland, Calif.",2014,"Jul 23, 2014",My Town,Bay Area News Group,"Oakland, Calif.",...,News,1547749826,https://www.proquest.com/newspapers/transcript...,2014-07-23,38.0,0.153640,"['pm', 'st', 'library', 'oct', 'road', '630', ...","Learn caring for dogs, cats. Ages 12, older, f...",0.890909,"(0.8, 1.0]"
3199,Thursday/19: [1 ],"Healthy Aging Symposium The Senior Focus, Cent...","Rutland Stress Seminar ""Coping with Stress and...",NaN,"Telegram & Gazette; Worcester, Mass.\n\nFirst ...",2014,"Jun 13, 2014",Weeklies,"GateHouse Media, Inc.","Worcester, Mass.",...,News,1535150607,https://www.proquest.com/newspapers/thursday-1...,2017-11-21,38.0,1.000000,"['pm', 'st', 'library', 'oct', 'road', '630', ...","Music begins at 6 p.m. and movies at dusk. ""Th...",0.890909,"(0.8, 1.0]"
3262,Wednesday/21,"Documentary Film ""The Anonymous People,"" about...",Fitchburg Smoking Cessation Class 6-7:30 p.m. ...,Public libraries; Senior citizen centers\n\nBu...,"Telegram & Gazette; Worcester, Mass.\n\nFirst ...",2014,"May 16, 2014",NEWS,"GateHouse Media, Inc.","Worcester, Mass.",...,News,1524761918,https://www.proquest.com/newspapers/wednesday-...,2024-12-01,38.0,0.081886,"['pm', 'st', 'library', 'oct', 'road', '630', ...",Registration required. (978) 630-3354. Gardner...,0.890909,"(0.8, 1.0]"
3303,Monday (4/28)/Tuesday (4/29) Events,[Holden] Grange 78 Open House Don Post of 'The...,Auburn Program Humanities Scholars Collaborati...,Public libraries; Registration; Blood & organ ...,"Telegram & Gazette; Worcester, Mass.\n\nFirst ...",2014,"Apr 27, 2014",Local,"GateHouse Media, Inc.","Worcester, Mass.",...,News,1519101454,https://www.proquest.com/newspapers/monday-4-2...,2024-12-01,38.0,1.000000,"['pm', 'st', 'library', 'oct', 'road', '630', ...",www.worcestercountypoetry.org. Poetry Forrest ...,0.890909,"(0.8, 1.0]"
3304,Tuesday/29,Interactive Program Scott Maloney will present...,"Auburn Meet the ""Teddy Bears,"" a dynamic vocal...",Public libraries; Secondary schools; Books; Ag...,"Telegram & Gazette; Worcester, Mass.\n\nFirst ...",2014,"Apr 28, 2014",Local,"GateHouse Media, Inc.","Worcester, Mass.",...,News,1519229145,https://www.proquest.com/newspapers/tuesday-29...,2024-12-01,38.0,1.000000,"['pm', 'st', 'library', 'oct', 'road', '630', ...",10 a.m. April 29. Pre-register by April 25. Co...,0.890909,"(0.8, 1.0]"
3402,What the Sentinel & Enterprise is working on W...,By Katina Caraganis | kcaraganis@sentinelanden...,Some of the stories the Sentinel & Enterprise ...,NaN,"Sentinel & Enterprise; Fitchburg, Mass.",2014,"Mar 5, 2014",News,The Lowell Sun,"Fitchburg, Mass.",...,News,1504285595,https://www.proquest.com/newspapers/what-senti...,2014-03-06,38.0,1.000000,"['pm', 'st', 'library', 'oct', 'road', '630', ...",By Katina Caraganis | kcaraganis@sentinelanden...,0.890909,"(0.8, 1.0]"
3677,calendar,Old Town Farmers' Market: Drop by Scottsdale's...,"To list an event, go to http://submit.azcentra...",Farmers markets; Restaurants\n\nLocation: Ariz...,"Arizona Republic; Phoenix, Ariz.\n\nFirst page...",2015,"Oct 24, 2015",Scottsdale Republic 8,Gann ett Media Corp,"Phoenix, Ariz.",...,News,1726470974,https://www.proquest.com/globalnewsfed/newspap...,2017-11-22,38.0,1.000000,"['pm', 'st', 'library', 'oct', 'road', '630', ...","8 p.m. Saturday, Oct. 31. Talking Stick Resort...",0.890909,"(0.8, 1.0]"
3699,Club News,"BEDFORD COUNCIL ON AGING: Mudge Way, Bedford: ...",Email information for this listing 10 days in ...,NaN,"The Sun; Lowell, Mass.",2015,"Oct 16, 2015",Lifestyle,The Lowell Sun,"Lowell, Mass.",...,News,1722458086,https://www.proquest.com/globalnewsfed/newspap...,2015-10-16,38.0,1.000000,"['pm', 'st', 'library', 'oct', 'road', '630', ...","To register, call 978-640-4490, ext. 205, or e...",0.890909,"(0.8, 1.0]"
4051,Things To Do 4/26-4/29,Aspiring film location scouts and managers loo...,THURSDAY ARTS Artist reception: 5-7 p.m. Thurs...,Americans with Disabilities Act 1990-US; Art e...,"Las Cruces Sun - News; Las Cruces, N.M.",2015,"Apr 22, 2015",Entertainment,Gannett Media Corp,"Las Cruces, N.M.",...,News,1675013659,https://www.proquest.com/globalnewsfed/newspap...,2015-04-23,38.0,0.143180,"['pm', 'st', 'library', 'oct', 'road', '630', ...","Be sure to include date, time, complete addres...",0.890909,"(0.8, 1.0]"
4101,What's Up/Heads Up,McCaskill serves as the top-ranking Democrat o...,WHAT'S UP * FROM EVENTS.STLTODAY.COM 03.31 Sen...,Older people; Circuses; Listening\n\nLocation:...,"St. Louis Post - Dispatch; St. Louis, Mo.",2015,"Mar 31, 2015",News,"Pulitzer, Inc.","St. Louis, Mo.",...,News,1667650497,https://www.proquest.com/globalnewsfed/newspap...,2017-11-22,38.0,0.063483,"['pm', 'st', 'library', 'oct', 'road', '630', ...",Group rates are available. Proceeds from trape...,0.890909,"(0.8, 1.0]"
4160,WEST VALLEY CALENDAR,None available.,Wednesday Lifestyle Enhancements: How to Take ...,NaN,"Arizona Republic; Phoenix, Ariz.\n\nFirst page...",2015,"Mar 4, 2015",Northwest Valley 20,Gannett Media Corp,"Phoenix, Ariz.",...,News,1660635866,https://www.proquest.com/globalnewsfed/newspap...,2017-11-22,38.0,0.198192,"['pm', 'st', 'library', 'oct', 'road', '630', ...","10:15-12 a.m. Tuesday, March 10. Banner Del E....",0.890909,"(0.8, 1.0]"
4174,Thursday/5,Homeschool Programs Build a Bat House. For age...,Worcester Homeschool Programs Build a Bat Hous...,Registration; Blood & organ donations; Senior ...,"Telegram & Gazette; Worcester, Mass.\n\nFirst ...",2015,"Feb 27, 2015",Weeklies,"GateHouse Media, Inc.","Worcester, Mass.",...,News,1658616160,https://www.proquest.com/globalnewsfed/newspap...,2024-12-01,38.0,1.000000,"['pm', 'st', 'library', 'oct', 'road', '630', ...",Registration requested. Free. Worcester Senior...,0.890909,"(0.8, 1.0]"
4185,Community News Briefs,Groton Grange #7 invites you to our traditiona...,Forum series will discuss issues of aging SHIR...,NaN,"The Sun; Lowell, Mass.",2015,"Feb 22, 2015",News,The Lowell Sun,"Lowell, Mass.",...,News,1657196472,https://www.proquest.com/globalnewsfed/newspap...,2015-02-22,38.0,0.070548,"['pm', 'st', 'library', 'oct', 'road', '630', ...",is organized by the Recycling Committee. The r...,0.890909,"(0.8, 1.0]"
4275,"Love Sunday JANUARY 11, 2015",Lifestyle 12 FASHION Cosy up in these winter w...,Big reads 4 COVER STORYKris Marshall on puttin...,Sons,The People; London (UK)\n\nFirst page: 3,2015,"Jan 11, 2015",Love Sunday,MGN Ltd.,London (UK),...,News,1644319252,https://www.proquest.com/globalnewsfed/ne wspa...,2015-01-11,38.0,0.052298,"['pm', 'st', 'library', 'oct', 'road', '630', ...",Enjoy! 54 THEN & NOW/ HOROSCOPES Dolls' houses...,0.890909,"(0.8, 1.0]"
4501,calendar,First Draft Book Club: The Girls: Join Arizona...,"To list an event, go to http://submit.azcentra...",Museum exhibits; Museums; Brain research; Nutr...,"Arizona Republic; Phoenix, Ariz.\n\nFirst page...",2016,"Aug 24, 2016",Northeast Phoenix Republic 7,Gannett Media Corp,"Phoenix, Ariz.",...,News,1813632892,https://www.proquest.com/globalnewsfed/newspap...,2017-11-23,38.0,1.000000,"['pm', 'st', 'library', 'oct', 'road', '630', ...","7:30 pm Thursday, Sept. 1. Musical Instrument ...",0.890909,"(0.8, 1.0]"

In [66]:
df.loc[718,'Full text']

"FAIRGROUNDS More than 1,000 people, including the governor, gathered Friday for an emotional celebration of area veterans. Many had tears in their eyes or lumps in their throats at various times throughout the 90-minute event at Kitsap Pavilion. For many in the crowd, it was hard to avoid the intense emotions as two dozen people were recognized for losing family members to war. Those in attendance watched somberly when the symbol of a fallen soldier was formed with rifle, helmet, boots and dog tags; when bagpipes moaned; rifles fired in salute; and buglers sounded taps. Navy Petty Officer Robert Medal choked up while reciting the POW/MIA place setting remembrance service, a symbol of the thousands of POW/MIAs still unaccounted for. It's very emotional for me, he said. Every time I lose one of my military brothers or sisters, even though I may not have known them, knowing of the sacrifice they made for the country and their families, it's beyond belief. Chris Gregoire said her most difficult job as governor is attending funerals and memorial services for state residents killed in battle. In 2007, governors were authorized to lower the American flag to honor service members killed overseas. She has ordered it 51 times. I can't forget them, and I'm sure neither can you, she said. Service members returning from Iraq and Afghanistan suffer challenges, including post-traumatic stress disorder, traumatic brain injuries and, in today's economy, just finding work. I'm going to make sure when they come home to say, 'Thank you. God bless you. We owe you and we're going to make sure you get a job to support you and your family,' Gregoire said. Guest speaker Jerry Mixon served in the Army for a couple years, which he said didn't stack up to lifetime commitment of many in the room. But he remembers them as eventful years. In 1967, his 47-man unit engaged the enemy in Vietnam. Mixon was shot eight times, hit by shrapnel and bayoneted. He lived. Forty of his pals did not. I met the toughest, strongest, most dedicated young men it's been my honor and pleasure to know. Most of them are dead now, said Mixon, who is an authority on healthy aging, radio host and founder of Longevity Medical Clinic. Though the annual event can be somber, the emotions of the day were shared by members of all services, of many conflicts, by friends and families of veterans and others in attendance. Carolyn Dankers, co-master of ceremonies and president of the Bremerton-Olympic Council of the Navy League, said she asked an old vet why he keeps coming back every year. It's the camaraderie, he said. I like the speakers and all, but I come to be with my friends. The annual event is a production of more than 40 military and fraternal organizations, directed by Sandra and Earle Smith. CREDIT:"

***
These all are noise topics
***

In [67]:
df = remove_topic(df,38,[])

The orig length:10650 -> cropped: 10595

#### Topic 87

In [68]:
df[df['topic']==87]

,Title,Abstract,Full text,Subject,Publication title,Publication year,Publication date,Section,Publisher,Place of publication,...,Document type,ProQuest document ID,Document URL,Last updated,topic,topic_prob,topic_keywords,last,rel_ratio,rel_bins
449,CELEBRATE LIFE IN THE MIDST OF CONSTANT CHANGE,"""She's always been a little reserved,"" [Ulla P...",Kindred Spirits Animal Sanctuary hosts annual ...,NaN,"The Santa Fe New Mexican; Santa Fe, N.M.\n\nFi...",2010,"May 2, 2010",SCOOP,Santa Fe New Mexican,"Santa Fe, N.M.",...,News,231292605,https://www.proquest.com/globalnewsfed/newspap...,2017-11-02,87.0,1.000000,"['dogs', 'dog', 'owners', 'animal', 'animals',...","On May 9, veterinarian Mary Anne Schadler offe...",0.882353,"(0.8, 1.0]"
2629,A dog's life may keep you young [Scot Region ],The researchers from Glasgow Caledonian Univer...,SCIENTISTS are set to find out if owning a dog...,Dogs; Older people; Health sciences,Daily Mail; London (UK)\n\nFirst page: 29,2013,"Apr 23, 2013",News,"Solo Syndication, a division of Associated New...",London (UK),...,News,1335037430,https://www.proquest.com/globalnewsfed/newspap...,2013-04-23,87.0,0.317050,"['dogs', 'dog', 'owners', 'animal', 'animals',...",The research will concentrate on the 'incident...,0.882353,"(0.8, 1.0]"
3117,Fundraiser today at Animal Friends Humane Society,Falls are a major reason older adults need to ...,The Animal Friends Humane Society will celebra...,Older people; Assisted living facilities; Ther...,"Cincinnati Enquirer; Cincinnati, Ohio\n\nFirst...",2014,"Aug 9, 2014\n\ncolumn: Area news",S,Gannett Media Corp,"Cincinnati, Ohio",...,News,1552130975,https://www.proquest.com/newspapers/fundraiser...,2014-08-09,87.0,1.000000,"['dogs', 'dog', 'owners', 'animal', 'animals',...",The Racer also is credited for sparking a roll...,0.882353,"(0.8, 1.0]"
3854,The Birches celebrates the dog days of summer,"""This event was a great opportunity for everyo...","With a late-summer heat wave in full force, it...",NaN,"Daily Herald; Arlington Heights, Ill.",2015,"Jul 29, 2015",Submitted Content,Daily Herald,"Arlington Heights, Ill.",...,News,1700215353,https://www.proquest.com/globalnewsfed/newspap...,2017-11-22,87.0,0.382768,"['dogs', 'dog', 'owners', 'animal', 'animals',...",The Birches Assisted Living in Clarendon Hills...,0.882353,"(0.8, 1.0]"
4418,What have cats ever done for us?,[...]The Cats Protection charity summarises th...,They argue that cats' tendency to kill birds a...,Dogs; Cardiovascular disease; Older people; Ag...,The Garstang Courier; Garstang (UK),2016,"Oct 5, 2016",Offbeat,NLA Media,Garstang (UK),...,News,1826777897,https://www.proquest.com/globalnewsfed/newspap...,2016-10-07,87.0,1.000000,"['dogs', 'dog', 'owners', 'animal', 'animals',...",Please try again. By uploading your file you a...,0.882353,"(0.8, 1.0]"
4665,HEALTHY AGING: Getting older gracefully with a...,"Volunteers from Good Mews, Cobb County Animal ...","Junior Nesbitt of Smyrna found his Princess, a...",Dogs; Animal shelters; Humane societies; Older...,"The Atlanta Journal - Constitution; Atlanta, Ga.",2016,"Jun 4, 2016",LIVING & ARTS,"Atlanta Journal Constitution, LLC","Atlanta, Ga.",...,News,1793712153,https://www.proquest.com/globalnewsfed/newspap...,2017-11-23,87.0,1.000000,"['dogs', 'dog', 'owners', 'animal', 'animals',...",Small dogs with short legs and long bodies -- ...,0.882353,"(0.8, 1.0]"
4737,The Birches Assisted Living welcomes three the...,"Now that spring has sprung, The Birches' thera...",There are three new residents at The Birches A...,NaN,"Daily Herald; Arlington Heights, Ill.",2016,"Apr 30, 2016",Submitted Content,Daily Herald,"Arlington Heights, Ill.",...,News,1785849148,https://www.proquest.com/globalnewsfed/newspap...,2017-11-22,87.0,0.715474,"['dogs', 'dog', 'owners', 'animal', 'animals',...",The Birches Assisted Living in Clarendon Hills...,0.882353,"(0.8, 1.0]"
4938,THE POWER OF PETS Study shows benefits of dog ...,According to the Humane Society of the United ...,The black and white papillon snuggled his frec...,Dogs; Research; Cardiovascular disease; Studie...,"Spokesman Review; Spokane, Wash.\n\nFirst page...",2016,"Jan 31, 2016",NaN,"Cowles Publishing Company, d/b/a The Spokesman...","Spokane, Wash.",...,News,1762651253,https://www.proquest.com/globalnewsfed/newspap...,2017-11-23,87.0,0.341199,"['dogs', 'dog', 'owners', 'animal', 'animals',...",A job well done. SIDEBAR: For more information...,0.882353,"(0.8, 1.0]"
5014,Owning a pet isn't the secret to staying young...,None available.,OWNING a pet does not seem to slow down the ag...,Biomarkers; Studies; Aging\n\nCompany / organi...,The Daily Telegraph; London (UK)\n\nFirst page: 6,2017,"Dec 14, 2017",News,Daily Telegraph,London (UK),...,News,1976417249,https://www.proquest.com/globalnewsfed/newspap...,2017-12-14,87.0,1.000000,"['dogs', 'dog', 'owners', 'animal', 'animals',...",After they took into account variables such as...,0.882353,"(0.8, 1.0]"
5412,Chloe’s paw-some community work,CHLOE the German Shepherd may not have the gif...,CHLOE the German Shepherd may not have the gif...,Quality of life; Older people; Volunteers; Dog...,"The Bendigo Advertiser; Bendigo, Vic.\n\nFirst...",2017,"May 9, 2017",News,Rural Press Pty Ltd Australian Community Media...,"Bendigo, Vic.",...,News,1896106628,https://www.proquest.com/globalnewsfed/newspap...,2017-05-08,87.0,0.374273,"['dogs', 'dog', 'owners', 'animal', 'animals',...",There were so many people in need in the commu...,0.882353,"(0.8, 1.0]"
5758,Meet the pets with 'special powers',None available.,The first Friday of every month is a special d...,Cardiovascular disease; Community; Stroke; Old...,Eastern Daily Press; Norwich (UK),2018,"Oct 23, 2018",Social News,NLA Media,Norwich (UK),...,News,2124031018,https://www.proquest.com/globalnewsfed/newspap...,2018-10-23,87.0,0.405605,"['dogs', 'dog', 'owners', 'animal', 'animals',...",Socialising: pets can act as a social icebreak...,0.882353,"(0.8, 1.0]"
6092,HEALTHY AGING: Power of pet therapy now an int...,None available.,When Arlene Sinanian shows up at a senior comm...,Animal training; Pets; Sleep deprivation\n\nLo...,"The Atlanta Journal - Constitution; Atlanta, G...",2018,"May 7, 2018",LIVING & ARTS,"Atlanta Journal Constitution, LLC","Atlanta, Ga.",...,News,2035203252,https://www.proquest.com/globalnewsfed/newspap...,2018-05-07,87.0,0.268622,"['dogs', 'dog', 'owners', 'animal', 'animals',...",|Handlers should also have the right temperame...,0.882353,"(0.8, 1.0]"
6863,Pets help older adults cope with health issues...,None available.,"CHICAGO, April 3 (Xinhua) -- A curled-up cat, ...",Older people; Health care policy; Dogs; Animal...,People's Daily; Beijing,2019,"Apr 4, 2019",NaN,Benchmark Information Limited,Beijing,...,News,2202641683,https://www.proquest.com/globalnewsfed/newspap...,2019-04-04,87.0,1.000000,"['dogs', 'dog', 'owners', 'animal', 'animals',...","While pets come with benefits, they can also b...",0.882353,"(0.8, 1.0]"
7008,Pet power to help the lonely,None available.,RESEARCHERS are drawing on the power of pets t...,Dogs; COVID-19,"Herald Sun; Melbourne, Vic.\n\nFirst page: 17",2020,"Dec 28, 2020",News,Nationwide News Pty Ltd,"Melbourne, Vic.",...,News,2472933726,https://www.proquest.com/newspapers/pet-power-...,2020-12-27,87.0,0.456985,"['dogs', 'dog', 'owners', 'animal', 'animals',...",Ms Davey said the game would be like a treasur...,0.882353,"(0.8, 1.0]"
7123,Chimps ‘choosy over pals’ in old age,None available.,Chimps get picky about who their friends are a...,Friendship,The Herald; Glasgow (UK)\n\nFirst page: 11,2020,"Oct 23, 2020",NaN,Gannett Media Corp,Glasgow (UK),...,News,2453609695,https://www.proquest.com/newspapers/chimps-cho...,2020-10-23,87.0,0.112577,"['dogs', 'dog', 'owners', 'animal', 'animals',...","The study draws on 78,000 hours of observation...",0.882353,"(0.8, 1.0]"
7244,Is this the right time to bring a pet into you...,None available.,"""That old September feeling, left over from sc...",Older people; Stress; Pets; Pandemics; Loneliness,"The Journal; Ashcroft, B.C.",2020,"Sep 2, 2020",Community,Black Press Group Ltd.,"Ashcroft, B.C.",...,News,2439646584,https://www.proquest.com/newspapers/is-this-ri...,2020-09-03,87.0,1.000000,"['dogs', 'dog', 'owners', 'animal', 'animals',...",Happy Birthday greetings to Heather Henri on S...,0.882353,"(0.8, 1.0]"
7290,Amazing benefits of having a pet,None available.,Pets bring much joy to the lives they touch. I...,Pain; Pets; Dogs\n\nIdentifier / keyword: brin...,"Times - Colonist; Victoria, B.C.\n\nFirst page...",2020,"Jul 30, 2020",News,Postmedia Network Inc.,"Victoria, B.C.",...,News,2428927234,https://www.proquest.com/newspapers/amazing-be...,2020-07-31,87.0,1.000000,"['dogs', 'dog', 'owners', 'animal', 'animals',...",Having structure after retirement can be impor...,0.882353,"(0.8, 1.0]"
7369,Amazing benefits for seniors who own pets,None available.,Pets bring much joy to the lives they touch. S...,Pain; Pets; Dogs,"Daily Herald; Arlington Heights, Ill.\n\nFirst...",2020,"May 24, 2020",Niche/Adv,Daily Herald,"Arlington Heights, Ill.",...,News,2406 664133,https://www.proquest.com/newspapers/amazing-be...,2020-05-26,87.0,1.000000,"['dogs', 'dog', 'owners', 'animal', 'animals',...",Having structure after retirement can be impor...,0.882353,"(0.8, 1.0]"
7418,The Mood-boosting Power Of Our Pets,None available.,"During the self isolation, I honestly don’t kn...",Exercise; Mental depression; Physical fitness;...,"Citizens' Voice; Wilkes-Barre, Pa.",2020,"Apr 11, 2020\n\nDateline: Wilkes-Barre, PA",Arts-Living,The Citizens' Voice,"Wilkes-Barre, Pa.",...,News,2388339029,https://www.proquest.com/newspapers/mood-boost...,2022-10-07,87.0,1.000000,"['dogs', 'dog', 'owners', 'animal', 'animals',...",See you next week. Dog bless. Resource: www.he...,0.882353,"(0.8, 1.0]"
7574,Spotify launches playlists for dogs left home ...,None available.,Spotify has created playlists to help soothe l...,Music; Animals; Dogs; Pets\n\nCompany / organi...,"Washington Examiner; Washington, D.C.",2020,"Jan 15, 2020",News,"Clarity Media Group, Inc.","Washington, D.C.",...,News,2338955191,https://www.proquest.com/newspapers/spotify-la...,2020-01-16,87.0,0.409920,"['dogs', 'dog', 'owners', 'animal', 'animals',...","Photo Caption:In this Monday, Nov. 11, 2019 ph...",0.882353,"(0.8, 1.0]"
7768,In Your Prime: 6 amazing benefits to having pets,None available.,Pets bring much joy to the lives they touch. S...,Exercise; Pets,Journal-News; Hamilton,2021,"Oct 3, 2021",Lifestyles,"Atlanta Journal Constitution, LLC",Hamilton,...,News,3179893874,https://www.proquest.co m/newspapers/your-prim...,2025-03-21,87.0,0.711470,"['dogs', 'dog', 'owners', 'animal', 'animals',...",-- Improved health: Ongoing research from Harv...,0.882353,"(0.8, 1.0]"
7872,There are amazing benefits to having a pet,None available.,Seniors may find having a pet is especially be...,Pain; Pets; Dogs,"Daily Herald; Arlington Heights, Ill.\n\nFirst...",2021,"Aug 11, 2021",DUQ,Daily Herald,"Arlington Heights, Ill.",...,News,2560068313,https://www.proquest.com/newspapers/there-are-...,2021-08-11,87.0,1.000000,"['dogs', 'dog', 'owners', 'animal', 'animals',...",* Stick to routine: Caring for pets helps seni...,0.882353,"(0.8, 1.0]"
8686,How robot pets are helping seniors fight lonel...,None available.,When Steve Hoover's 96-year-old mother calls h...,Councils; Cats; Aging; Pets; Dementia; Robotic...,"St. Cloud Times; St. Cloud, Minn.\n\nFirst pag...",2022,"Jun 10, 2022",News,Gannett Media Corp,"St. Cloud, Minn.",...,News,2674631393,https://www.proquest.com/globalnewsfed/newspap...,2022-06-10,87.0,0.080164,"['dogs', 'dog', 'owners', 'animal', 'animals',...","Well, the day after I dropped off the dog, she...",0.882353,"(0.8, 1.0]"
9020,Want to help prevent your cognition level from...,None available.,Owning a pet – especially a dog or cat – has b...,Public health; Older people; Cognitive ability...,Jerusalem Post; Jerusalem\n\nFirst page: 8,2023,"Dec 31, 2023",Health,The Jerusalem Post Ltd.,Jerusalem,...,News,2908461746,https://www.proquest.com/newspapers/want-help-...,2024-01-02,87.0,0.352575,"['dogs', 'dog', 'owners', 'animal', 'animals',...",The authors noted that further studies are nee...,0.882353,"(0.8, 1.0]"
9137,Could pets be an anti-aging ally?,None available.,Aging well is more important than ever in toda...,Older people; Cognitive ability; Age; Aging; D...,Malay Mail Online; Kuala Lumpur,2023,"Nov 17, 2023\n\nDateline: NEW YORK",NaN,Trinity Diligent Sdn Bdn,Kuala Lumpur,...,News,2891087276,https://www.proquest.com/newspapers/could-pets...,2023-11-18,87.0,0.339928,"['dogs', 'dog', 'owners', 'animal', 'animals',...",While these findings represent a significant c...,0.882353,"(0.8, 1.0]"
9353,Social studies; Interacting with humans and pe...,None available.,"Social interaction is good for human health, a...",Veterinary medicine; Animals; Aging; Dogs; Pet...,"Northern News This Week; Kirkland Lake, Ont.\n...",2023,"Sep 14, 2023",You,Postmedia Network Inc.,"Kirkland Lake, Ont.",...,News,2864713893,https://www.proquest.com/newspapers/social-stu...,2023-09-15,87.0,0.227002,"['dogs', 'dog', 'owners', 'animal', 'animals',...","""The more children or time that owners dedicat...",0.882353,"(0.8, 1.0]"
9436,TODAY’S TALKER,None available.,Dogs can age healthier by socializing with hum...,Aging; Dogs\n\nLocation: United States--US; Ar...,"The Atlanta Journal - Constitution; Atlanta, G...",2023,"Aug 16, 2023",MAIN,"Atlanta Journal Constitution, LLC","Atlanta, Ga.",...,News,2851065148,https://www.proquest.com/newspapers/today-s-ta...,2023-08-16,87.0,0.206862,"['dogs', 'dog', 'owners', 'animal', 'animals',...","Its goal is to learn how genes, lifestyle and ...",0.882353,"(0.8, 1.0]"
9636,Old people's home for dogs?,None available.,When Annie the cavoodle walks down the hall at...,Older people; Penicillin; Animals; Aging; Pets...,"Sunday Age; Melbourne, Vic.\n\nFirst page: 8",2023,"Feb 12, 2023",News,Fairfax Digital,"Melbourne, Vic.",...,News,2775214479,https://www.proquest.com/newspapers/old-people...,2023-02-12,87.0,0.038306,"['dogs', 'dog', 'owners', 'animal', 'animals',...","""Dogs can be great catalysts for social intera...",0.882353,"(0.8, 1.0]"
9828,PET HATES: Animals get grumpier as they mature,None available.,ANIMALS get grumpier as they get older - just ...,NaN,Daily Star; London (UK)\n\nFirst page: 11,2024,"Oct 30, 2024",News,Express Newspapers PLC,London (UK),...,News,3121874752,https://www.proquest.com/globalnewsfed/newspap...,2024-10-30,87.0,0.181449,"['dogs', 'dog', 'owners', 'animal', 'animals',...","Researchers in one study, which analysed 150 s...",0.882353,"(0.8, 1.0]"
10367,Let your dog run with their pack for healthy a...,None available.,"New Delhi, Jan. 10 -- One factor that's perhap...",Health care; Households; Pets; Dogs,The Hindustan Times; New Delhi,2024,"Jan 10, 2024",NaN,HT Digital Streams Limited,New Delhi,...,News,2912414496,https://www.proquest.com/globalnewsfed/newspap...,2024-01-10,87.0,1.000000,"['dogs', 'dog', 'owners', 'animal', 'animals',...",The study also brought out some interesting in...,0.882353,"(0.8, 1.0]"
10501,Animal rescue receives grant: Funds will hel...,None available.,The River Region Animal Rescue wants to unite ...,Older people; Pets,"Montgomery Advertiser; Montgomery, Ala.\n\nFir...",2025,"Jul 21, 2025",News,Gannett Media Corp,"Montgomery, Ala.",...,News,3231746956,https://www.proquest.com/globalnewsfed/newspap...,2025-07-21,87.0,1.000000,"['dogs', 'dog', 'owners', 'animal', 'animals',...","""A lot of times they've been in homes before.""...",0.882353,"(0.8, 1.0]"
10548,Owning dog or cat could preserve some brain fu...,None available.,As Britain’s population ages and dementia rate...,Birds; Animal cognition; Cats; Brain research;...,The Guardian; London (UK)\n\nFirst page: 16,2025,"Jul 5, 2025",Science,Guardian News & Media Limited,London (UK),...,News,3227242645,https://www.proquest.com/globalnewsfed/newspap...,2025-07-05,87.0,1.000000,"['dogs', 'dog', 'owners', 'animal', 'animals',...",“It is about how we live our life. What is nic...,0.882353,"(0.8, 1.0]"
10578,Kindred Spirits holding open house,"Since 2002, Kindred Spirits Animal Sanctuary h...","Since 2002, Kindred Spirits Animal Sanctuary h...",Horses; Volunteers; Animal shelters,"The Santa Fe New Mexican; Santa Fe, N.M.\n\nFi...",2025,"Jun 26, 2025",B,Santa Fe New Mexican,"Santa Fe, N.M.",...,News,3224363220,https://www.proquest.com/globalnewsfed/newspap...,2025-06-27,87.0,0.502336,"['dogs', 'dog', 'owners', 'animal', 'animals',...",Kindred Spirit open house When: 10 a.m.-2 p.m....,0.882353,"(0.8, 1.0]"
10908,Owners of this pet have a sharper mind in old ...,None available.,"India, March 1 -- A fascinating study from Jap...",Exercise; Social interaction; Social support; ...,The Hindustan Times; New Delhi,2025,"Mar 1, 2025",NaN,HT Digital Streams Limited,New Delhi,...,News,3172529413,https://www.proquest.com/globalnewsfed/newspap...,2025-03-01,87.0,1.000000,"['dogs', 'dog', 'owners', 'animal', 'animals',...","However, the study's results warrant further i...",0.882353,"(0.8, 1.0]"

***
This topic is about animals helping people live longer, while only one is about aging of an animal itself.
***

In [69]:
df = df[~df.index.isin([10367])]

#### Topic 95

In [70]:
df[df['topic']==95]

,Title,Abstract,Full text,Subject,Publication title,Publication year,Publication date,Section,Publisher,Place of publication,...,Document type,ProQuest document ID,Document URL,Last updated,topic,topic_prob,topic_keywords,last,rel_ratio,rel_bins
155,Beth Judea to show 'In the Family' film tonigh...,"Widowed support group: 7-8:30 p.m. Tuesday, Oc...",Items that focus on physical and mental health...,NaN,"Daily Herald; Arlington Heights, Ill.\n\nFirst...",2010,"Oct 7, 2010",NEIGHBOR,Daily Herald,"Arlington Heights, Ill.",...,News,759255201,https://www.proquest.com/globalnewsfed/newspap...,2017-11-17,95.0,0.109152,"['registration', 'support group', 'senior cent...",Call (847) 556-1777. Walkers club: The Arlingt...,0.9375,"(0.8, 1.0]"
247,Support Groups,AL-ANON ALCOHOLISM SUPPORT: An anonymous fello...,AL-ANON ALCOHOLISM SUPPORT: An anonymous fello...,NaN,"The Sun; Lowell, Mass.",2010,"Sep 15, 2010",Lifestyle,The Lowell Sun,"Lowell, Mass.",...,News,750927020,https://www.proque st.com/globalnewsfed/newspa...,2010-09-16,95.0,1.000000,"['registration', 'support group', 'senior cent...","Meets first and third Tues. of every month, 5:...",0.9375,"(0.8, 1.0]"
271,Area cyclists fight cancer,"Brian Finkele and Tammy Hanley, both of Worces...","Brian Finkele and Tammy Hanley, both of Worces...",Health insurance; Cancer; Health care; Accredi...,"Telegram & Gazette; Worcester, Mass.\n\nFirst ...",2010,"Aug 19, 2010\n\ncolumn: MEDICAL MEMOS",HEALTH,"GateHouse Media, Inc.","Worcester, Mass.",...,News,745936690,https://www.proquest.com/globalnewsfed/newspap...,2024-12-01,95.0,0.055975,"['registration', 'support group', 'senior cent...",UMass Memorial Health Care insurance counselor...,0.9375,"(0.8, 1.0]"
372,Health Briefs: Sacred Heart Health System of...,None available.,Sacred Heart Health System will provide free h...,NaN,"Pensacola News Journal; Pensacola, Fla.",2010,"Jun 13, 2010",Online Life,Gannett Media Corp,"Pensacola, Fla.",...,News,375164842,https://www.proquest.com/globaln ewsfed/newspa...,2017-11-03,95.0,1.000000,"['registration', 'support group', 'senior cent...",Blood donors will receive a free waffle coupon...,0.9375,"(0.8, 1.0]"
1013,Alexandria and Arlington health calendar,Sullivan gives a virtual tour of the surgical ...,"Thursday, July 28 Seniors walking program 8-9 ...",Aging; Cancer; Senior citizen centers; Cancer ...,"The Washington Post; Washington, D.C.",2011,"Jul 28, 2011",LOCAL LIVING,WP Company LLC d/b/a The Washington Post,"Washington, D.C.",...,News,879449461,https://www.proquest.com/globalnewsfed/newspap...,2017-11-18,95.0,1.000000,"['registration', 'support group', 'senior cent...",703-228-4721 or www.nvso.us. - Compiled by Ria...,0.9375,"(0.8, 1.0]"
1030,HEALTH DIGEST,None available.,Blood donations The Greater Chesapeake and Pot...,NaN,"The Baltimore Sun; Baltimore, Md.\n\nFirst pag...",2011,"Jul 10, 2011",LOCAL,"Tribune Publishing Company, LLC","Baltimore, Md.",...,News,876067516,https://www.proquest.com/globalnewsfed/newspap...,2017-11-18,95.0,1.000000,"['registration', 'support group', 'senior cent...",Women's group will be held from 11 a.m. to 1 p...,0.9375,"(0.8, 1.0]"
1082,Lifesaving lessons,"At Field Day , radio amateurs, also known as ""...",The Glen Burnie Volunteer Fire Department will...,Fires; Fire stations; Amateur radio; Aging,"Maryland Gazette; Glen Burnie, Md.\n\nFirst pa...",2011,"Jun 18, 2011",NaN,"Tribune Publishing Company, LLC","Glen Burnie, Md.",...,News,873368929,https://www.proquest.com/globalnewsfed/newspap...,2016-10-22,95.0,0.075362,"['registration', 'support group', 'senior cent...",The Amateur Radio Club of the National Electro...,0.9375,"(0.8, 1.0]"
1117,Asheville area health calendar,Learn about a cutting edge approach to address...,Health calendar The complete Health Calendar i...,Autism; Hospitals; Palliative care; Lutheran c...,"Asheville Citizen - Times; Asheville, N.C.",2011,"Jul 12, 2011",LIVING,Gannett Media Corp,"Asheville, N.C.",...,News,875927422,https://www.proquest.com/globaln ewsfed/newspa...,2017-11-18,95.0,0.088807,"['registration', 'support group', 'senior cent...",Call 452-8085 for a free consultation. WEIGHT ...,0.9375,"(0.8, 1.0]"
1189,TO SUBMIT AN ITEM,"""Fire and Home Safety,"" part of the healthy ag...",Seniors walking program 8-9 a.m. Thursdays and...,Senior citizen centers; Fires; Community cente...,"The Washington Post; Washington, D.C.",2011,"May 19, 2011\n\nDateline: A",LOCAL LIVING,WP Company LLC d/b/a The Washington Post,"Washington, D.C.",...,News,867487444,https://www.proquest.com/globalnewsfed/newspap...,2017-11-18,95.0,0.055964,"['registration', 'support group', 'senior cent...",E-mail: axliving@washpost.com Fax: 703-518-300...,0.9375,"(0.8, 1.0]"
1204,CONFERENCE TO EDUCATE SENIORS ON AGING WELL,"Seniors can attend a free conference, called ""...","Seniors can attend a free conference, called ""...",NaN,"Daily Press; Newport News, Va.\n\nFirst page: A.7",2011,"Apr 13, 2011\n\ncolumn: Health Notes",Local,"Tribune Publishing Company, LLC","Newport News, Va.",...,News,861755522,https://www.proquest.com/globalnewsfed/newspap...,2017-11-18,95.0,1.000000,"['registration', 'support group', 'senior cent...",Reach Salasky at 247-4784 or psalasky@dailypre...,0.9375,"(0.8, 1.0]"
1240,HEALTH BRIEFS,None available.,From staff reports Events to bring awareness t...,NaN,"Pensacola News Journal; Pensacola, Fla.",2011,"Sep 11, 2011",Online Life,Gannett Media Corp,"Pensacola, Fla.",...,News,889276737,https://www.proquest.com/globalnewsfed/newspap...,2017-11-18,95.0,0.176528,"['registration', 'support group', 'senior cent...",The procedure reduces hiatal hernia and create...,0.9375,"(0.8, 1.0]"
1429,"Montgomery County wellness calendar, Nov. 29-D...","Bethesda blood drive Saturday, 9 a.m.-2 p.m. B...","Lunchtime yoga course Take a mat, towel and wa...",Aging; Senior citizen centers,"The Washington Post; Washington, D.C.",2012,"Nov 29, 2012",LOCAL LIVING,WP Company LLC d/b/a The Washington Post,"Washington, D.C.",...,News,1220653657,https://www.proquest.com/globalnewsfed/newspap...,2017-11-19,95.0,0.093834,"['registration', 'support group', 'senior cent...","Mary Casamento, 301-253-4626. Hospice Caring s...",0.9375,"(0.8, 1.0]"
1468,"Montgomery County wellness calendar, Nov. 8-15","""Building Blocks of Tai Chi"" Thursdays at 11:1...","""Building Blocks of Tai Chi"" Thursdays at 11:1...",Senior citizen centers; Physical fitness; Bloo...,"The Washington Post; Washington, D.C.",2012,"Nov 8, 2012",LOCAL LIVING,WP Company LLC d/b/a The Washington Post,"Washington, D.C.",...,News,1140804295,https://www.proquest.com/globalnewsfed/newspap...,2017-11-19,95.0,0.170902,"['registration', 'support group', 'senior cent...",Meals on Wheels drivers needed Deliveries in t...,0.9375,"(0.8, 1.0]"
1486,"Montgomery wellness calendar, Nov. 1-8","Friendship Heights Village Center, 4433 S. Par...",Memory screening Register for appointments on ...,Senior citizen centers,"The Washington Post; Washington, D.C.",2012,"Nov 1, 2012",LOCAL LIVING,WP Company LLC d/b/a The Washington Post,"Washington, D.C.",...,News,1124611157,https://www.proquest.com/globalnewsfed/newspap...,2017-11-19,95.0,0.148169,"['registration', 'support group', 'senior cent...",Tuesday at 7 p.m. National Alliance on Mental ...,0.9375,"(0.8, 1.0]"
1501,"Alexandria and Arlington wellness calendar, De...","Seminar: ""Signs and Symptoms of Parkinson's Di...",Al-Anon/Alateen groups For relatives and frien...,Senior citizen centers; Hospitals; Older peopl...,"The Washington Post; Washington, D.C.",2012,"Dec 13, 2012",LOCAL LIVING,WP Company LLC d/b/a The Washington Post,"Washington, D.C.",...,News,1237771759,https://www.proquest.com/globalnewsfed/newspap...,2017-11-20,95.0,1.000000,"['registration', 'support group', 'senior cent...",Registration required. Blood pressure monitori...,0.9375,"(0.8, 1.0]"
1734,"Alexandria and Arlington wellness calendar, Ju...",Alzheimer's caregivers support Wednesday at 10...,"Alexandria blood drives Thursday, 9:30 a.m.-3:...",Senior citizen centers; Hospitals; Travel,"The Washington Post; Washington, D.C.",2012,"Jul 12, 2012",LOCAL LIVING,WP Company LLC d/b/a The Washington Post,"Washington, D.C.",...,News,1024454935,https://www.proquest.com/globalnewsfed/newspap...,2017-11-19,95.0,1.000000,"['registration', 'support group', 'senior cent...",855-694-6682. Free. Registration required. - C...,0.9375,"(0.8, 1.0]"
1785,"Alexandria and Arlington wellness calendar, Ju...",Pre-op class for breast cancer patients Breast...,Al-Anon/Alateen groups For family and friends ...,Senior citizen centers; Hospitals,"The Washington Post; Washington, D.C.",2012,"Jun 14, 2012",LOCAL LIVING,WP Company LLC d/b/a The Washington Post,"Washington, D.C.",...,News\n\nProQuest documentID: 1020166051,NaN,https://www.proquest.com/globalnewsfed/newspap...,2017-11-19,95.0,1.000000,"['registration', 'support group', 'senior cent...",Responsibilities include greeting donors and p...,0.9375,"(0.8, 1.0]"
1880,"Alexandria and Arlington wellness calendar, Ap...",Early-stage breast cancer support group Facili...,"Arlington blood drive Thursday, 8 a.m.-2 p.m. ...",Senior citizen centers; Support groups; Hospit...,"The Washington Post; Washington, D.C.",2012,"Apr 26, 2012",LOCAL LIVING,WP Company LLC d/b/a The Washington Post,"Washington, D.C.",...,News,1009372077,https://www.proquest.com/globalnewsfed/newspap...,2017-11-19,95.0,1.000000,"['registration', 'support group', 'senior cent...",Wednesdays at 7 p.m. Mount Vernon Recreation C...,0.9375,"(0.8, 1.0]"
1974,"Alexandria and Arlington wellness calendar, Ma...","Healthy aging workshop A presentation, ""Bringi...",Alexandria Al-Anon Confidential meetings for f...,Aging; Senior citizen centers; Travel; Head & ...,"The Washington Post; Washington, D.C.",2012,"Mar 22, 2012",LOCAL LIVING,WP Company LLC d/b/a The Washington Post,"Washington, D.C.",...,News,929384609,https://www.proquest.com/globalnewsfed/newspap...,2017-11-19,95.0,1.000000,"['registration', 'support group', 'senior cent...","Arlington blood drive Wednesday, 10:30-4 p.m. ...",0.9375,"(0.8, 1.0]"
2132,Health briefs for 11/17 print,None available.,Downeast Orthopedic to begin seeing patients B...,NaN,"Bangor Daily News; Bangor, Me.",2013,"Dec 16, 2013",NaN,Bangor Daily News,"Bangor, Me.",...,News,1468421909,https://www.proquest.com/globalnewsfed/newspap...,2017-11-20,95.0,1.000000,"['registration', 'support group', 'senior cent...",Outreach Specialist Yvette Seaman as well as s...,0.9375,"(0.8, 1.0]"
2617,Young cancer survivor to speak at Aroostook sy...,"The hospital, in partnership with the American...","PRESQUE ISLE, Maine -- For many cancer patient...",Aging; Chemotherapy; Cancer therapies; Caregiv...,"Bangor Daily News; Bangor, Me.",2013,"Apr 29, 2013",NaN,Bangor Daily News,"Bangor, Me.",...,News,1346908057,https://www.proquest.com/globalnewsfed/newspap...,2017-11-20,95.0,0.051394,"['registration', 'support group', 'senior cent...",TAMC will sponsor the Survivor Tent and host a...,0.9375,"(0.8, 1.0]"
2700,"Alexandria and Arlington wellness calendar, Ma...","Alzheimer's caregiver support group Wednesday,...","""Normal Memory Loss"" workshop A presentation b...",Hospitals; Older people; Blood & organ donatio...,"The Washington Post; Washington, D.C.",2013,"Mar 14, 2013",LOCAL LIVING,WP Company LLC d/b/a The Washington Post,"Washington, D.C.",...,News,1317929741,https://www.proquest.com/globalnewsfed/newspap...,2017-11-20,95.0,0.138460,"['registration', 'support group', 'senior cent...",Red Cross needs volunteers Help is needed with...,0.9375,"(0.8, 1.0]"
2737,"Alexandria and Arlington wellness calendar, Fe...",Red Cross needs volunteers Help is needed with...,Al-Anon/Alateen groups For relatives and frien...,Senior citizen centers; Hospitals; Older peopl...,"The Washington Post; Washington, D.C.",2013,"Feb 21, 2013",LOCAL LIVING,WP Company LLC d/b/a The Washington Post,"Washington, D.C.",...,News,1290644087,https://www.proquest.com/globalnewsfed/newspap...,2017-11-20,95.0,1.000000,"['registration', 'support group', 'senior cent...",Red Cross needs volunteers Help is needed with...,0.9375,"(0.8, 1.0]"
2934,Event Calendar,None available.,BLOOD DRIVES BLOOD DRIVE: 11 a.m. to 3:30 p.m....,NaN,"Asbury Park Press; Asbury Park, N.J.\n\nFirst ...",2014,"Oct 28, 2014\n\ncolumn: HEALTH CALENDAR",D,Gannett Media Corp,"Asbury Park, N.J.",...,News,1617800819,https://www.proquest.com/newspapers/event-cale...,2017-11-21,95.0,1.000000,"['registration', 'support group', 'senior cent...",T'AI CHI FOR PEOPLE WITH ARTHRITIS: 3:30 to 4:...,0.9375,"(0.8, 1.0]"
3021,Danvers family remembers mother with a charity...,"For the 12th year, All Saints Episcopal Church...",IN MEMORY OF A MOM: Stacy Talbot Bazylinski wa...,Breast cancer; Hospitals; Awards & honors,"Boston Globe; Boston, Mass.",2014,"Sep 25, 2014",Regional,"Boston Globe Media Partners, LLC","Boston, Mass.",...,News,1564544717,https://www.proquest.com/newspapers/danvers-fa...,2017-11-22,95.0,0.135737,"['registration', 'support group', 'senior cent...",Wendy Killeen can be reached at wdkilleen@gmai...,0.9375,"(0.8, 1.0]"
3090,Fletcher Valley Market to hold juicing class,Sickle cell disease is an inherited disease th...,"Fletcher Valley Market at 1151 Naples Road, He...",NaN,"Times News; Hendersonville, N.C.",2014,"Aug 27, 2014",NaN,Halifax Media Group,"Hendersonville, N.C.",...,News,1556102705,https://www.proquest.com/newspapers/fletcher-v...,2014-08-26,95.0,1.000000,"['registration', 'support group', 'senior cent...","Donors purchased hearing aids, pediatric cance...",0.9375,"(0.8, 1.0]"
3200,happenings,"Stop smoking: ""Quit Smoking Now,"" free smoking...","Stop smoking: ""Quit Smoking Now,"" free smoking...",Smoking cessation; Heart; Cancer; Meetings; Ch...,"Florida Today; Melbourne, Fla.\n\nFirst page: 5",2014,"Jun 12, 2014",D,Gannett Media Corp,"Melbourne, Fla.",...,News,1536082503,https://www.proquest.com/newspapers/happenings...,2017-11-21,95.0,0.075113,"['registration', 'support group', 'senior cent...",Subsequent sessions will be July 7 and 14. Cal...,0.9375,"(0.8, 1.0]"
3630,Health briefs: TEDMED live streaming event,None available.,Baptist Health Care invites members of the com...,NaN,"Pensacola News Journal; Pensacola, Fla.\n\nFir...",2015,"Nov 12, 2015\n\ncolumn: Health briefs",A,Gannett Media Corp,"Pensacola, Fla.",...,News,1732575315,https://www.proquest.com/globalnewsfed/newspap...,2017-11-22,95.0,1.000000,"['registration', 'support group', 'senior cent...",9 to 11:30 a.m. Tuesday at Cantonment Council ...,0.9375,"(0.8, 1.0]"
3633,Event Calendar,None available.,"CANCER SERVICES ""PARTY FOR PINK"" FUNDRAISER: 6...",NaN,"Asbury Park Press; Asbury Park, N.J.\n\nFirst ...",2015,"May 19, 2015\n\ncolumn: HEALTH CALENDAR",D,Gannett Media Corp,"Asbury Park, N.J.",...,News,1682653681,https://www.proquest.com/globalnewsfed/newspap...,2017-11-22,95.0,0.096081,"['registration', 'support group', 'senior cent...",SHIP: MEDICARE QUESTIONS ANSWERED! SESSION: 1:...,0.9375,"(0.8, 1.0]"
4525,Health Briefs: Disaster prep lecture planned,None available.,Bayhealth Medical Center's STEPS to Healthy Ag...,Emergency preparedness; Registration; Mammogra...,"The News Journal; Wilmington, Del.\n\nFirst pa...",2016,"Aug 25, 2016",News,Gannett Media Corp,"Wilmington, Del.",...,News,2191417187,https://www.proquest.com/globalnewsfed/newspap...,2019-03-15,95.0,0.108504,"['registration', 'support group', 'senior cent...",Beebe Healthcare earns award for surgery Highm...,0.9375,"(0.8, 1.0]"
4799,in brief: Scrapbooking event set,None available.,The Delaware Breast Cancer Coalition will host...,NaN,"Daily Times; Salisbury, Md.\n\nFirst page: T.45",2016,"Apr 3, 2016",Features,Gannett Media Corp,"Salisbury, Md.",...,Feature,1777827882,https://www.proquest.com/globalnewsfed/newspap...,2017-11-22,95.0,0.091753,"['registration', 'support group', 'senior cent...",Bayhealth names new officers Bayhealth Board o...,0.9375,"(0.8, 1.0]"
9603,HCE gets healthy aging tips and shares upcomin...,None available.,The Bingham/Ramsey HCE meeting was held March ...,NaN,"Daily Herald; Arlington Heights, Ill.\n\nFirst...",2023,"Mar 29, 2023",RNJ,Daily Herald,"Arlington Heights, Ill.",...,News,2791978993,https://www.proquest.com/newspapers/hce-gets-h...,2023-03-29,95.0,0.085019,"['registration', 'support group', 'senior cent...",The presentation will be at 1:30 p.m. at Unity...,0.9375,"(0.8, 1.0]"

***
These all are advertisements about different health programs
***

In [71]:
df = remove_topic(df,95,[])

The orig length:10594 -> cropped: 10562

#### Topic 107

In [72]:
df[df['topic']==107]

,Title,Abstract,Full text,Subject,Publication title,Publication year,Publication date,Section,Publisher,Place of publication,...,Document type,ProQuest document ID,Document URL,Last updated,topic,topic_prob,topic_keywords,last,rel_ratio,rel_bins
28,Anissa V. Rivera: Physical activity showcased,"This session highlights ""Physical Activity Opp...",The ever-popular Lunch at the Library program ...,NaN,"San Gabriel Valley Tribune; West Covina, Calif.",2010,"Dec 9, 2010",Local,Los Angeles Newspaper Group,"West Covina, Calif.",...,News,816798283,https://www.proquest.com/globalnewsfed/newspap...,2010-12-10,107.0,0.172898,"['ave', 'senior center', 'bay', 'st', 'pm', 'g...",The character in the title is a sharp 15-year-...,0.833333,"(0.8, 1.0]"
217,BULLETIN BOARD,TODAY * Highland Hospital will host its 14th a...,TODAY * Highland Hospital will host its 14th a...,NaN,"The Charleston Gazette; Charleston, W.V.\n\nFi...",2010,"Sep 15, 2010",Life,Charleston Newspapers,"Charleston, W.V.",...,News,750919174,https://www.proquest.com/globalnewsfed/newspap...,2017-11-17,107.0,0.123405,"['ave', 'senior center', 'bay', 'st', 'pm', 'g...",Refreshments will be served. The headquarters ...,0.833333,"(0.8, 1.0]"
817,Focus on wellness draws crowd of 300,Somehow we ended up with a whole heap of servi...,"IT started out with just an idea, to celebrate...",NaN,Derwent Valley Gazette; New Norfolk\n\nFirst p...,2011,"Oct 12, 2011",NaN,Font Public Relations,New Norfolk,...,News,897122446,https://www.proquest.com/globalnewsfed/newspap...,2011-10-11,107.0,1.000000,"['ave', 'senior center', 'bay', 'st', 'pm', 'g...",We are either slow learners or full of ambitio...,0.833333,"(0.8, 1.0]"
908,9/11 Anniversary Good Time To Give Back,Did you know that there are currently more tha...,Today is the 10th anniversary of one of Americ...,NaN,"Republican & Herald; Pottsville, Pa.",2011,"Sep 8, 2011\n\nDateline: Pottsville, PA",News,Republican & Herald,"Pottsville, Pa.",...,News,888304971,https://www.proquest.com/globalnewsfed/newspap...,2011-09-11,107.0,0.032816,"['ave', 'senior center', 'bay', 'st', 'pm', 'g...",Skills: A 45-hour training is mandatory. Locat...,0.833333,"(0.8, 1.0]"
1279,Provena Covenant hosts gathering,Photos by Sandra Gorman/for The News-Gazette D...,"Dr. Abraham Kocheril, a Christie Clinic cardio...",NaN,"News Gazette; Champaign, Ill.\n\nFirst page: B.5",2011,"Feb 27, 2011",NaN,News Gazette,"Champaign, Ill.",...,News,856629439,https://www.proquest.com/glob alnewsfed/newspa...,2016-08-21,107.0,1.000000,"['ave', 'senior center', 'bay', 'st', 'pm', 'g...",Photos by Sandra Gorman/for The News-Gazette T...,0.833333,"(0.8, 1.0]"
1403,Seniors Calendar,None available.,WALKING CLUB FOR SENIORS: 11 a.m. Thursdays; P...,NaN,"Daily Record; Morristown, N.J.",2012,"Dec 25, 2012",A,Gannett Media Corp,"Morristown, N.J.",...,News,1243240030,https://www.proquest.com/globalnewsfed/newspap...,2017-11-20,107.0,0.039208,"['ave', 'senior center', 'bay', 'st', 'pm', 'g...","204 Flanders-Drakestown Road, Flanders . Mount...",0.833333,"(0.8, 1.0]"
1760,Morsels: 'Healthy Eating' for budget-minded,The Carolina Mountain Ribfest is accepting app...,'Healthy Eating' for budget-minded Blue Ridge ...,NaN,"Times News; Hendersonville, N.C.",2012,"Jun 27, 2012",NaN,Halifax Media Group,"Hendersonville, N.C.",...,News,1022302764,https://www.proquest.com/globalnewsfed/newspap...,2012-11-02,107.0,0.064109,"['ave', 'senior center', 'bay', 'st', 'pm', 'g...",One National Grand SPAM Champion in the adult ...,0.833333,"(0.8, 1.0]"
1778,Check out the Senior Games,"The games, organized by the York County Area A...","York, PA - The York County Senior Games will b...",Aging; Older people,"York Daily Record; York, Pa.",2012,"Jun 18, 2012",News,Gannett Media Corp,"York, Pa.",...,News,1020927991,https://www.proquest.com/globalnewsfed/newspap...,2012-06-19,107.0,1.000000,"['ave', 'senior center', 'bay', 'st', 'pm', 'g...",89-year-old Mary Louise Smith of Shrewsbury ey...,0.833333,"(0.8, 1.0]"
2828,Check it out: Jan. 10,Film with nonverbal communication expert Jan H...,Body Language... What You Say Before You Say a...,Car washes; Wildlife sanctuaries; Support grou...,"Green Bay Press Gazette; Green Bay, Wis.\n\nFi...",2013,"Jan 9, 2013",Z,Gannett Media Corp,"Green Bay, Wis.",...,News,1346172793,https://www.proquest.com/globalnewsfed/newspap...,2017-11-20,107.0,0.061145,"['ave', 'senior center', 'bay', 'st', 'pm', 'g...","(920) 391-3671, www.baybeachwildlife.com. Jan....",0.833333,"(0.8, 1.0]"
3705,check it out,Family-friendly Halloween activities including...,Oct. 14 Healthy Habits for a Healthier You: 4-...,Meetings; Professional football; Trade shows; ...,"Green Bay Press Gazette; Green Bay, Wis.\n\nFi...",2015,"Oct 14, 2015",W,Gannett Media Corp,"Green Bay, Wis.",...,News,1721914721,https://www.proquest.com/globalnewsfed/newspap...,2023-10-09,107.0,1.000000,"['ave', 'senior center', 'bay', 'st', 'pm', 'g...",Nov. 4 Beginning computer seminar: Learn Compu...,0.833333,"(0.8, 1.0]"
4064,Daily planner calendar for June 25,"Having traveled to Antarctica and the Arctic, ...",HAPPENINGS Third Thursday series -- Beacon Ins...,Gastrointestinal surgery; Libraries; Autism; M...,"The Poughkeepsie Journal; Poughkeepsie, N.Y.\n...",2015,"Apr 16, 2015",A,Gannett Media Corp,"Poughkeepsie, N.Y.",...,News,1673379062,https://www.proquest.com/globalnewsfed/newspap...,2017-11-22,107.0,0.051525,"['ave', 'senior center', 'bay', 'st', 'pm', 'g...",Your submission will be reviewed by a Journal ...,0.833333,"(0.8, 1.0]"
4109,Senior games 30th competition begins April 13,"SENIOR GAMES SCHEDULE April 13, Spangler Stadi...",Cleveland County and North Carolina Senior Gam...,Aging; Women; Senior citizen centers; Billiard...,"Shelby Star; Shelby, NC",2015,"Mar 26, 2015",News,Halifax Media Group,"Shelby, NC",...,News,1667049083,https://www.proquest.com/globalnewsfed/newspap...,2015-03-27,107.0,1.000000,"['ave', 'senior center', 'bay', 'st', 'pm', 'g...",We are getting better. Aging can be fun. The s...,0.833333,"(0.8, 1.0]"
4159,NEWS BRIEFS: Cubs players at youth event,None available.,Mesa Youth Sports is partnering with the Chica...,NaN,"Arizona Republic; Phoenix, Ariz.\n\nFirst page...",2015,"Mar 4, 2015",Mesa Republic 11,Gannett Media Corp,"Phoenix, Ariz.",...,News,1660636138,https://www.proquest.com/globalnewsfed/newspap...,2017-11-21,107.0,0.041936,"['ave', 'senior center', 'bay', 'st', 'pm', 'g...",Lutheran Thrift Store auction The East Valley ...,0.833333,"(0.8, 1.0]"
4383,check it out,"Watch the film, ""Right to Harm,"" and join the ...",Through Dec. 7 Medicare Part D: Counseling Ser...,Libraries; Blood & organ donations; Aging; Dem...,"Green Bay Press Gazette; Green Bay, Wis.\n\nFi...",2016,"Oct 26, 2016",News,Gannett Media Corp,"Green Bay, Wis.",...,News,1832221476,https://www.proquest.com/globalnewsfed/newspap...,2017-11-24,107.0,0.035843,"['ave', 'senior center', 'bay', 'st', 'pm', 'g...",Keynote speaker: Judy Turba: House of Four Roo...,0.833333,"(0.8, 1.0]"
4536,9th Annual Community Health Fair to be held at...,Exhibitors will include the Institute for Popu...,The Temple of I AM will host its 9th Annual Co...,Medical screening; Religious organizations; Fa...,"Michigan Chronicle; Detroit, Mich.\n\nVolume: ...",2016,"Aug 17-Aug 23, 2016",praise connection,"Real Times, Inc.","Detroit, Mich.",...,News,1815498940,https://www.proquest.com/globalnewsfed/newspap...,2016-10-25,107.0,0.037704,"['ave', 'senior center', 'bay', 'st', 'pm', 'g...","Throughout the day, activities will include li...",0.833333,"(0.8, 1.0]"
4648,BULLETIN BOARD,"The Alzheimer's Association, West Virginia Cha...","The ""Folklore and Folklorists Little Lecture s...",NaN,"Charleston Gazette - Mail; Charleston, W.V.\n\...",2016,"Jun 10, 2016",NaN,Charleston Newspapers,"Charleston, W.V.",...,News,1795564043,https://www.proquest.com/globalnewsfed/newspap...,2017-11-23,107.0,1.000000,"['ave', 'senior center', 'bay', 'st', 'pm', 'g...",Items for Bulletin Board may be submitted by m...,0.833333,"(0.8, 1.0]"
4745,GRADD hosting Masters Athletic Challenge,Formerly known as the Green River Regional Sen...,The Green River Area Development District will...,Billiards; Golf,"Messenger Inquirer; Owensboro, Ky.",2016,"Apr 24, 2016",News,Owensboro Messenger Inquirer,"Owensboro, Ky.",...,News,1815811677,https://www.proqu est.com/globalnewsfed/newspa...,2016-10-04,107.0,1.000000,"['ave', 'senior center', 'bay', 'st', 'pm', 'g...",The Masters Athletic Challenge schedule: * Gol...,0.833333,"(0.8, 1.0]"
5536,Community,PeaceHealth Sleep Clinic Sleep Fair - Monday t...,Occupy Eugene General Assembly - 6 p.m. Monday...,Public libraries; Sleep; Sleep apnea\n\nCompan...,"The Register - Guard; Eugene, Or.",2017,"Mar 4, 2017",City Region,Gannett Media Corp,"Eugene, Or.",...,News,1874077165,https://www.proquest.com/globalnewsfed/newspap...,2017-03-04,107.0,1.000000,"['ave', 'senior center', 'bay', 'st', 'pm', 'g...",Free. Lane County recruitment coordinator Laur...,0.833333,"(0.8, 1.0]"
6167,Announcements,None available.,GilmantonProject Coyote The Gilmanton Year-Rou...,Students\n\nLocation: Italy\n\nCompany / organ...,"Con cord Monitor; Concord, N.H.",2018,"Apr 13, 2018",News,Concord Monitor/Sunday Monitor,"Concord, N.H.",...,News,2024338143,https://www.proquest.com/globalnewsfed/newspap...,2018-04-13,107.0,0.113230,"['ave', 'senior center', 'bay', 'st', 'pm', 'g...",He will live with two or three host families b...,0.833333,"(0.8, 1.0]"
6794,Monday... [Derived Headline ],None available.,Monday Willing Walkers: 3:30 p.m. Henniker Vil...,Public libraries; Community centers; Line danc...,"Concord Monitor; Concord, N.H.",2019,"May 12, 2019",News,Concord Monitor/Sunday Monitor,"Concord, N.H.",...,News,2223104190,https://www.proquest.com/globalnewsfed/newspap...,2019-05-12,107.0,0.037074,"['ave', 'senior center', 'bay', 'st', 'pm', 'g...","Mah Jongg: 3 p.m. White Birch Center, 51 Hall ...",0.833333,"(0.8, 1.0]"
6904,Event calendar,None available.,Classes Tuesday ENHANCEFITNESS: Group exercise...,Support groups; Public libraries; Grief; Careg...,"Columbian; Vancouver, Wash.\n\nFirst page: C.4",2019,"Mar 11, 2019",Metro,Columbian Publishing Company,"Vancouver, Wash.",...,News,2190605875,https://www.proquest.com/globalnewsfed/newspap...,2021-10-15,107.0,1.000000,"['ave', 'senior center', 'bay', 'st', 'pm', 'g...",franroserd1000@msn.com Survivors of Suicide: 6...,0.833333,"(0.8, 1.0]"
7099,HEALTH BULLETIN BOARD,None available.,Free Flu Vaccines for Uninsured Adults - Avail...,Conferences; Grief; Seminars; Dementia; Educat...,"Spokesman Review; Spokane, Wash.\n\nFirst page...",2020,"Nov 5, 2020",NaN,"Cowles Publishing Company, d/b/a The Spokesman...","Spokane, Wash.",...,News,2457695654,https://www.proquest.com/newspapers/health-bul...,2023-10-09,107.0,1.000000,"['ave', 'senior center', 'bay', 'st', 'pm', 'g...","Nov. 12, 4-5:30p.m. Hospice of North Idaho, 22...",0.833333,"(0.8, 1.0]"
7218,Williamson County Public Library,None available.,"1314 Columbia Ave., Franklin 615-794-3105, htt...",NaN,"The Tennessean; Nashville, Tenn.\n\nFirst page...",2020,"Sep 16, 2020\n\ncolumn: At your local library",News,Gannett Media Corp,"Nashville, Tenn.",...,News,2442834574,https://www.proquest.com/newspapers/williamson...,2020-09-16,107.0,1.000000,"['ave', 'senior center', 'bay', 'st', 'pm', 'g...","This applies to Bethesda, College Grove, Fairv...",0.833333,"(0.8, 1.0]"
7666,HEALTH BULLETIN BOARD,None available.,THIS WEEK Bloomsday Road Runners Club Turkey T...,Schedules; Support groups; COVID-19 vaccines; ...,"Spokesman Review; Spokane, Wash.\n\nFirst page...",2021,"Nov 25, 2021",NaN,"Cowles Publishing Company, d/b/a The Spokesman...","Spokane, Wash.",...,News,2603070862,https://www.proquest.com/newspapers/health-bul...,2021-11-27,107.0,1.000000,"['ave', 'senior center', 'bay', 'st', 'pm', 'g...","Masks are required. Shoshone Medical Center, 2...",0.833333,"(0.8, 1.0]"
7900,HEALTH BULLETIN,None available.,Trail Tales: Take a Walk; Enjoy a Story - Book...,Libraries; Books; Yoga; Nutrition,"Spokesman Review; Spokane, Wash.\n\nFirst page...",2021,"Jul 29, 2021",NaN,"Cowles Publishing Company, d/b/a The Spokesman...","Spokane, Wash.",...,News,2556395119,https://www.proquest.com/newspapers/health-bul...,2021-07-30,107.0,0.210577,"['ave', 'senior center', 'bay', 'st', 'pm', 'g...","Register at scld.org. Aug. 5, 2p.m. Presented ...",0.833333,"(0.8, 1.0]"
8296,SENIOR ACTIVITIES,National Active Retired Federal Employees - Se...,Events are free unless otherwise stated. Natio...,Federal employees; Site planning,"Spokesman Review; Spokane, Wash.\n\nFirst page...",2022,"Dec 19, 2022",NaN,"Cowles Publishing Company, d/b/a The Spokesman...","Spokane, Wash.",...,News,2755880574,https://www.proquest.com/globalnewsfed/newspap...,2022-12-20,107.0,1.000000,"['ave', 'senior center', 'bay', 'st', 'pm', 'g...",Pinochle - Double deck pinochle every Wednesda...,0.833333,"(0.8, 1.0]"
8302,BULLETIN BOARD,None available.,THIS WEEK Low Impact Aerobics - An ongoing cla...,NaN,"Spokesman Review; Spokane, Wash.\n\nFirst page...",2022,"Dec 15, 2022",NaN,"Cowles Publishing Company, d/b/a The Spokesman...","Spokane, Wash.",...,News,2754867240,https://www.proquest.com/globalnewsfed/newspap...,2022-12-16,107.0,1.000000,"['ave', 'senior center', 'bay', 'st', 'pm', 'g...",Visit alz.org/alzwa/helping_you/education to r...,0.833333,"(0.8, 1.0]"
8702,HEALTH BULLETIN BOARD,None available.,THIS WEEK Facility Use - Pool and Track - Publ...,Schedules; Cancer; Swimming pools; Support gro...,"Spokesman Review; Spokane, Wash.\n\nFirst page...",2022,"Jun 2, 2022",NaN,"Cowles Publishing Company, d/b/a The Spokesman...","Spokane, Wash.",...,News\n\nProQuestdocument ID: 2672730739,NaN,https://www.proquest.com/globalnewsfed/newspap...,2022-06-03,107.0,1.000000,"['ave', 'senior center', 'bay', 'st', 'pm', 'g...",Visit nicotine-anonymous.org/video-conference-...,0.833333,"(0.8, 1.0]"
9735,HEALTH BULLETIN BOARD,None available.,"THIS WEEK Yoga at Sinto - Bring a yoga mat, wa...",Support groups; Diabetes; Physical fitness; Fo...,"Spokesman Review; Spokane, Wash.\n\nFirst page...",2024,"Dec 5, 2024",NaN,"Cowles Publishing Company, d/b/a The Spokesman...","Spokane, Wash.",...,News,3142791914,https://www.proquest.com/globalnewsfed/newspap...,2024-12-11,107.0,1.000000,"['ave', 'senior center', 'bay', 'st', 'pm', 'g...","Meets Mondays and Wednesdays, September throug...",0.833333,"(0.8, 1.0]"
9748,SENIOR ACTIVITIES,None available.,Quilters and Crafting Group - Work on craft pr...,Computer & video games; Libraries; Memory; Yog...,"Spokesman Review; Spokane, Wash.\n\nFirst page...",2024,"Nov 4, 2024",NaN,"Cowles Publishing Company, d/b/a The Spokesman...","Spokane, Wash.",...,News,3125927652,https://www.proquest.com/globalnewsfed/newspap...,2024-11-08,107.0,0.121170,"['ave', 'senior center', 'bay', 'st', 'pm', 'g...",Senior Fitness - Rotating low-impact fitness c...,0.833333,"(0.8, 1.0]"

***
These are ad articles about health-related associations.
***

In [73]:
df = remove_topic(df,107,[])

The orig length:10562 -> cropped: 10532

#### Topic 109

In [74]:
df[df['topic']==109]

,Title,Abstract,Full text,Subject,Publication title,Publication year,Publication date,Section,Publisher,Place of publication,...,Document type,ProQuest document ID,Document URL,Last updated,topic,topic_prob,topic_keywords,last,rel_ratio,rel_bins
60,DVD seminar provides health advice,This DVD-based seminar was developed by Dr. Wi...,Are you wondering how to better boost your ene...,NaN,"The Dispatch; Lexington, N.C.",2010,"Nov 23, 2010",NaN,Halifax Media Group,"Lexington, N.C.",...,News,808533472,https://www.proquest.com/globalnewsfed/newspap...,2012-10-12,109.0,1.000000,"['september', 'active aging', 'ymca', 'seminar...",The program will be held at 1 p.m. Dec. 2 at t...,0.866667,"(0.8, 1.0]"
216,Center for Active Generations to have events f...,"Monday, Sept. 20- noon- ""Changing the way we a...",The Center for Active Generations will be host...,Aging; Older people,"Argus Leader; Sioux Falls, S.D.",2010,"Sep 16, 2010",UPDATES,Gannett Media Corp,"Sioux Falls, S.D.",...,News,750887012,https://www.proquest.com/globalnewsfed/newspap...,2017-11-17,109.0,0.044571,"['september', 'active aging', 'ymca', 'seminar...",Some of the weeks highlighted events incude: M...,0.866667,"(0.8, 1.0]"
242,"University of Wisconsin-Fox Valley presents ""A...","Oct. 18: ""Physical and Fit for Life"" with Jane...",MENASHA -- Four programs for healthy aging is ...,Aging; Health care; Medicine; Research; Corpor...,"The Post - Crescent; Appleton, Wis.",2010,"Sep 4, 2010",APC,Gannett Media Corp,"Appleton, Wis.",...,News,749465550,https://www.proquest.com/globalnewsfed/newspap...,2017-11-17,109.0,1.000000,"['september', 'active aging', 'ymca', 'seminar...","Oct. 18: ""Physical and Fit for Life"" with Jane...",0.866667,"(0.8, 1.0]"
329,Series on health and aging offered at Salem Ho...,None available.,A free five-week class on healthy living while...,NaN,"Statesman Journal; Salem, Or.",2010,"Jul 10, 2010",UPDATE,Gannett Media Corp,"Salem, Or.",...,News,607075383,https://www.proquest.com/globalnewsfed/newspap...,2017-11-17,109.0,0.087312,"['september', 'active aging', 'ymca', 'seminar...","SE, Building D, on the first floor. Registrati...",0.866667,"(0.8, 1.0]"
544,Healthy aging topic of USC Alumni Club mixer,None available.,The USC Alumni Club of the Desert mixer on Thu...,NaN,"The Desert Sun; Palm Springs, Calif.",2010,"Mar 3, 2010",LIFESTYLES,Gannett Media Corp,"Palm Springs, Calif.",...,News,439865787,https://www.proquest.com/globalnewsfed/newspap...,2017-11-16,109.0,1.000000,"['september', 'active aging', 'ymca', 'seminar...",The mixer is scheduled from 5 to 7 p.m. the De...,0.866667,"(0.8, 1.0]"
574,Healthy aging in spotlight,"u Thursday, March 4, 9:30 a.m.-noon: The Power...",If you want to know how to stay healthy longer...,NaN,"Times News; Hendersonville, N.C.",2010,"Feb 13, 2010",NaN,Halifax Media Group,"Hendersonville, N.C.",...,News,435372051,https://www.proq uest.com/globalnewsfed/newspa...,2012-11-02,109.0,1.000000,"['september', 'active aging', 'ymca', 'seminar...",The cost is $22 per person. To register online...,0.866667,"(0.8, 1.0]"
706,DR. OZ TO VISIT MIDLAND PARK,TV host Dr.,TV host Dr. Mehmet Oz will visit the Northwest...,NaN,The Record; Hackensack\n\nFirst page: L.2,2011,"Nov 26, 2011",LOCAL,Gannett Media Corp,Hackensack,...,News,3188220239,https ://www.proquest.com/globalnewsfed/newspa...,2025-04-22,109.0,1.000000,"['september', 'active aging', 'ymca', 'seminar...",TV host Dr. Mehmet Oz will visit the Northwest...,0.866667,"(0.8, 1.0]"
854,"Healthy Fall Festival targets families, kids",The free festival will include workshops and d...,Two Surprise businesses that promote good heal...,Aging; Physical fitness; Festivals,"Arizona Republic; Phoenix, Ariz.",2011,"Sep 28, 2011",Surprise Republic 1,Gannett Media Corp,"Phoenix, Ariz.",...,News,894706476,https://www.proquest.com/globalnewsfed/newspap...,2017-11-18,109.0,0.034086,"['september', 'active aging', 'ymca', 'seminar...",** Healthy Fall Festival When: 8 a.m. to 4 p.m...,0.866667,"(0.8, 1.0]"
879,Program to focus on healthy aging,None available.,"What: Dr. Craig B. Cairns, vice president of m...",NaN,"The Advocate; Newark, Ohio",2011,"Sep 21, 2011",NEWS,Gannett Media Corp,"Newark, Ohio",...,News,893402075,https://www.proquest.com/globalnewsfed/newspap...,2017-11-18,109.0,1.000000,"['september', 'active aging', 'ymca', 'seminar...","What: Dr. Craig B. Cairns, vice president of m...",0.866667,"(0.8, 1.0]"
897,LIBRARY CORNER: Active Aging at the Library,"According to ICAA, active aging describes indi...",The library in Marshall has a timely and infor...,Aging; Older people; Libraries; Risk assessmen...,"Asheville Citizen - Times; Asheville, N.C.\n\n...",2011,"Sep 14, 2011",News,Gannett Media Corp,"Asheville, N.C.",...,News,1471229385,https://www.proquest.com/globalnewsfed/newspap...,2017-11-20,109.0,0.039993,"['september', 'active aging', 'ymca', 'seminar...",Library Closing Reminder All locations of the ...,0.866667,"(0.8, 1.0]"
1502,"Many journeys, many destinations","Screenings, healthy aging information and even...",Some say the journey is just as good as the de...,Aging,"Asheville Citizen - Times; Asheville, N.C.\n\n...",2012,"Oct 24, 2012",A,Gannett Media Corp,"Asheville, N.C.",...,News,1471192419,https://www.proquest.com/globalnewsfed/newspap...,2017-11-20,109.0,0.040640,"['september', 'active aging', 'ymca', 'seminar...","For stimulating the mind, the week encouraged ...",0.866667,"(0.8, 1.0]"
1697,Free 'anti-aging' seminar set for Saturday,"A free health seminar about ""anti-aging"" is se...","A free health seminar about ""anti-aging"" is se...",NaN,"Messenger Inquirer; Owensboro, Ky.\n\nFirst pa...",2012,"Aug 2, 2012",NaN,Owensboro Messenger Inquirer,"Owensboro, Ky.",...,News,1030817302,https://www.proquest.com/globalnewsfed/newspap...,2016-07-23,109.0,0.133540,"['september', 'active aging', 'ymca', 'seminar...",Among the issues discussed will be how to slow...,0.866667,"(0.8, 1.0]"
1736,Seminar: Talking to your doctor,None available.,A free seminar on how to talk to your doctor w...,NaN,"Courier - Journal; Louisville, Ky.",2012,"Jul 11, 2012",In The Prime: Aging,Gannett Media Corp,"Louisville, Ky.",...,News,1024524254,https://www.proquest.com/globalnewsfed/newspap...,2017-11-19,109.0,0.064700,"['september', 'active aging', 'ymca', 'seminar...","Refreshments, desserts and free gifts will be ...",0.866667,"(0.8, 1.0]"
2128,"BUSINESS BRIEFCASE: Awards, honors",None available.,MARLETTE ThumbWorks in Marlette received a $15...,NaN,"Times Herald; Port Huron, Mich.\n\nFirst page: 6",2013,"Dec 18, 2013\n\ncolumn: BUSINESS BRIEFCASE",A,Gannett Media Corp,"Port Huron, Mich.",...,News,1468884023,https://www.proquest.com/globalnewsfed/newspap...,2017-11-21,109.0,1.000000,"['september', 'active aging', 'ymca', 'seminar...","To attend this event, call (888-637-2963). For...",0.866667,"(0.8, 1.0]"
2337,Lunch and learn about healthy aging program,"Dianne Phillips, LPC, certified gerontologist,...",To the editor: Healthy Aging Month is an annua...,Aging; Older people,"Daily News; Jacksonville, NC",2013,"Sep 11, 2013",Opinion,Halifax Media Group,"Jacksonville, NC",...,News,1467622841,https://www.proquest.com/globalnewsfed/newspap...,2013-12-13,109.0,1.000000,"['september', 'active aging', 'ymca', 'seminar...",Patrons pay for their own lunch and tip. Diann...,0.866667,"(0.8, 1.0]"
2553,Caring Connections scheduled women's health fa...,There will be numerous health-related vendor t...,Senior Beat by Carol Higgins Taylor Eastern Ar...,Aging; Womens health; Back pain; Bakeries; Reiki,"Bangor Daily News; Bangor, Me.",2013,"May 30, 2013",NaN,Bangor Daily News,"Bangor, Me.",...,News,1356488535,https://www.proquest.com/globalnewsfed/newspap...,2017-11-20,109.0,0.056195,"['september', 'active aging', 'ymca', 'seminar...","This fair is aptly named, ""Now Is Your Time: S...",0.866667,"(0.8, 1.0]"
3108,IN BRIEF: Bayhealth experts to speak on 'Sle...,None available.,Representatives from Bayhealth Sleep Center wi...,NaN,"Daily Times; Salisbury, Md.\n\nFirst page: 77",2014,"Aug 17, 2014",T,Gannett Media Corp,"Salisbury, Md.",...,News,1553639657,https://www.proquest.com/newspapers/brief/docv...,2017-11-21,109.0,0.057624,"['september', 'active aging', 'ymca', 'seminar...",The event will take place from 3-4:30 p.m. and...,0.866667,"(0.8, 1.0]"
3118,Margaret Todd Senior Center hosts workshop on ...,None available.,A free workshop on healthy aging for seniors l...,NaN,"Marin Independent Journal; Novato, Calif.",2014,"Aug 6, 2014",News,Bay Area News Group,"Novato, Calif.",...,News,1681472211,https://www.proquest.com/newspapers/mar garet-...,2015-05-19,109.0,1.000000,"['september', 'active aging', 'ymca', 'seminar...",Podwojski with provide tools to stay healthy a...,0.866667,"(0.8, 1.0]"
3179,Local programs promoting graceful aging,None available.,The list of quality local services for seniors...,Exercise; Physical fitness; Aging; Community s...,Seaforth Huron Expositor; Seaforth\n\nFirst pa...,2014,"Jun 25, 2014",News,Postmedia Network Inc.,Seaforth,...,News,2169230825,https://www.proquest.com/newspapers/local-prog...,2019-01-22,109.0,1.000000,"['september', 'active aging', 'ymca', 'seminar...",For a complete calendar of programming offered...,0.866667,"(0.8, 1.0]"
3202,"Seminar to offer tips on aging, detoxifying",The Owensboro Healthy and Wise Club will host ...,The Owensboro Healthy and Wise Club will host ...,NaN,"Messenger Inquirer; Owensboro, Ky.\n\nFirst pa...",2014,"Jun 12, 2014",NaN,Owensboro Messenger Inquirer,"Owensboro, Ky.",...,News,1535175250,https://www.proquest.com/newspapers/seminar-of...,2016-07-23,109.0,0.055341,"['september', 'active aging', 'ymca', 'seminar...",The Owensboro Healthy and Wise Club will host ...,0.866667,"(0.8, 1.0]"
3656,MILITARY BRIEFING: Successful aging is topic,None available.,"""Naval Hospital Bremerton's Wellness Wednesday...",NaN,"Kitsap Sun; Bremerton, Wash.\n\nFirst page: D.6",2015,"Oct 27, 2015",Military,Gannett Media Corp,"Bremerton, Wash.",...,News,2582479445,https://www.proquest.com/globalnewsfed/newspap...,2021-10-17,109.0,1.000000,"['september', 'active aging', 'ymca', 'seminar...",It will be led by Lt. Cmdr. Jim Garland in roo...,0.866667,"(0.8, 1.0]"
3701,Free workshops offered by York County on healt...,In an effort to educate York County seniors on...,It's important to age healthily. In an effort ...,NaN,"The York Dispatch; York, Pa.",2015,"Oct 15, 2015",News,The York Dispatch,"York, Pa.",...,News,1722487599,https://www.proquest.com/globalnewsfed/newspap...,2015-10-16,109.0,1.000000,"['september', 'active aging', 'ymca', 'seminar...",They include: *Lowering systolic blood pressur...,0.866667,"(0.8, 1.0]"
4076,Five-week '10 Keys to Healthy Aging' series of...,"The Red Lion Area Senior Center, 20-C Gotham P...","The Red Lion Area Senior Center, 20-C Gotham P...",NaN,"The York Dispatch; York, Pa.",2015,"Apr 12, 2015",News,The York Dispatch,"York, Pa.",...,News,1672752712,https://www.proquest.com/globalnewsfed/newspap...,2015-04-13,109.0,1.000000,"['september', 'active aging', 'ymca', 'seminar...",Developed by researchers at the University of ...,0.866667,"(0.8, 1.0]"
4699,Healthy Aging Seminar,The Healthy Aging Seminar is a Wellness Minist...,The Healthy Aging Seminar is a Wellness Minist...,NaN,"Daily Herald; Arlington Heights, Ill.",2016,"May 19, 2016",Submitted Content,Daily Herald,"Arlington Heights, Ill.",...,News,1789884793,https://www.proquest.com/globalnewsfed/newspap...,2017-11-22,109.0,1.000000,"['september', 'active aging', 'ymca', 'seminar...",Join in this engaging one hour healthy lifesty...,0.866667,"(0.8, 1.0]"
4730,North Suburban YMCA Offers Free Adult Workshop...,"""We are very excited by the interest the commu...",The North Suburban YMCA continues its new seri...,NaN,"Daily Herald; Arlington Heights, Ill.",2016,"May 5, 2016",Submitted Content,Daily Herald,"Arlington Heights, Ill.",...,News,1786971221,https://www.proquest.com/globalnewsfed/newspap...,2017-11-23,109.0,0.079773,"['september', 'active aging', 'ymca', 'seminar...",This new fitness program will be a new regular...,0.866667,"(0.8, 1.0]"
4973,Polk County calendar of health events (Jan. 12),About: Alzheimer's Association Florida Gulf Co...,TODAY Speaker at Heart-to-Heart Cardiac Suppor...,NaN,"The Ledger; Lakeland, Fla.",2016,"Jan 12, 2016",NEWS,Halifax Media Group,"Lakeland, Fla.",...,News,1755762190,https://www.proquest.com/globalnewsfed/newspap...,2016-01-12,109.0,0.093150,"['september', 'active aging', 'ymca', 'seminar...",Reserve at ChatAndChewRSVP@aol.com by Jan. 20;...,0.866667,"(0.8, 1.0]"
5205,The Glen Ellyn Public Library and the B.R. Rya...,None available.,The Glen Ellyn Public Library and the B.R. Rya...,Librarians; Public transportation; Public libr...,"Daily Herald; Arlington Heights, Ill.",2017,"Sep 8, 2017",Submitted Content,Daily Herald,"Arlington Heights, Ill.",...,News,1936579317,https://www.proquest.com/globalnewsfed/newspap...,2017-11-24,109.0,0.094586,"['september', 'active aging', 'ymca', 'seminar...",Start with Yes! IMPROVe Dementia Communication...,0.866667,"(0.8, 1.0]"
6528,The 'Healthy Aging' equation to know,None available.,Celebrate Healthy Aging month and focus on the...,NaN,"The Spectrum; St. George, Utah\n\nFirst page: A.3",2019,"Sep 22, 2019",News,Gannett Media Corp,"St. George, Utah",...,News,2294891206,https://www.proquest.com/globalnewsfed/newspap...,2019-09-22,109.0,0.106363,"['september', 'active aging', 'ymca', 'seminar...",The rest of the LiVe Well 2019 Health Fair wil...,0.866667,"(0.8, 1.0]"
6539,Healthy Aging,None available.,Healthy Aging is a free Wellness Ministry Prog...,Vitamin E; Aging\n\nCompany / organization: Na...,"Daily Herald; Arlington Heights, Ill.",2019,"Sep 12, 2019",Submitted Content,Daily Herald,"Arlington Heights, Ill.",...,News,2288754398,https://www.proquest.com/globalnewsfed/newspap...,2019-09-12,109.0,1.000000,"['september', 'active aging', 'ymca', 'seminar...","Adopting Healthy habits, staying involved in y...",0.866667,"(0.8, 1.0]"
10017,Live Boldly - September 2024 Message From Depa...,None available.,"DIRECTOR CHARON P.W. HINES Dear Seniors, Happy...",Oldest old people; Centenarians; Aging\n\nPeop...,"Washington Informer; Washington, D.C.\n\nVolum...",2024,"Sep 5-Sep 11, 2024",NaN,Washington Informer,"Washington, D.C.",...,News,3109489603,https://www.proquest.com/globalnewsfed/newspap...,2024-09-26,109.0,1.000000,"['september', 'active aging', 'ymca', 'seminar...","dc.gov, or download the DACL app. Let's make t...",0.866667,"(0.8, 1.0]"

***
Ad topic
***

In [75]:
df = remove_topic(df,109,[])

The orig length:10532 -> cropped: 10502

#### Topic 129

In [76]:
df[df['topic']==129]

,Title,Abstract,Full text,Subject,Publication title,Publication year,Publication date,Section,Publisher,Place of publication,...,Document type,ProQuest document ID,Document URL,Last updated,topic,topic_prob,topic_keywords,last,rel_ratio,rel_bins
566,FROM THE REGION,Police Chief Andrew J. Sluckis said the men go...,Auburn Pair rob man with knife at Auburn Mall ...,Older people; Stabbings; Motion picture festiv...,"Telegram & Gazette; Worcester, Mass.\n\nFirst ...",2010,"Feb 21, 2010\n\ncolumn: FROM THE REGION",LOCAL NEWS,"GateHouse Media, Inc.","Worcester, Mass.",...,News,269049246,https://www.proquest.com/globalnewsfed/newspap...,2024-12-01,129.0,1.000000,"['port', 'st', 'pm', 'ave', 'road', 'library',...",Tickets are $10 for the public; $7 for Fitchbu...,0.961538,"(0.8, 1.0]"
1046,Senior Citizen Activities,"Wednesday - Morning cards, 8:30 a.m.; Hometown...",Shamokin-Coal Township Sunday - Wii bowling an...,NaN,"The News - Item; Shamokin, Pa.",2011,"Jul 07, 2011\n\nDateline: Shamokin, PA",News,Sample News Group,"Shamokin, Pa.",...,News\n\nProQuestdocument ID: 875573649,NaN,https://www.proquest.com/globalnewsfed/newspap...,2016-08-21,129.0,0.156519,"['port', 'st', 'pm', 'ave', 'road', 'library',...","Thursday - Healthy Steps, 9:30 a.m.; line danc...",0.961538,"(0.8, 1.0]"
1095,DAILY CALENDAR,None available.,"Today Noon Used Book Sale, to 6 p.m. Knights o...",NaN,"Times Herald; Port Huron, Mich.",2011,"Apr 20, 2011",KIOSK,Gannett Media Corp,"Port Huron, Mich.",...,News,863800949,https://www.proquest.com/globalnewsfed/newspap...,2017-11-18,129.0,1.000000,"['port', 'st', 'pm', 'ave', 'road', 'library',...","Capac Library, 111 N Main St. 4:30 p.m. Interm...",0.961538,"(0.8, 1.0]"
1305,DAILY CALENDAR: Today,None available.,"10 a.m.Waffle Wednesday, to noon. Free waffles...",NaN,"Times Herald; Port Huron, Mich.",2011,"Feb 16, 2011",KIOSK,Gannett Media Corp,"Port Huron, Mich.",...,News,853863053,https://www.proquest.com/globalnewsfed/newspap...,2017-11-17,129.0,1.000000,"['port', 'st', 'pm', 'ave', 'road', 'library',...","2 p.m.Folk Concert: The Reminisers, Sanctuary ...",0.961538,"(0.8, 1.0]"
1828,IN BRIEF: Healthy Aging seminar on sleep is ...,None available.,St. Joseph Mercy Port Huron hospital is having...,NaN,"Times Herald; Port Huron, Mich.",2012,"May 21, 2012",A-Section,Gannett Media Corp,"Port Huron, Mich.",...,News,1019536299,https://www.proquest.com/globalnewsfed/newspap...,2017-11-19,129.0,1.000000,"['port', 'st', 'pm', 'ave', 'road', 'library',...",This will be the second time the German bands ...,0.961538,"(0.8, 1.0]"
1837,Daily calendar: Special Events,"Capac Library, 111 N. Main St. St. Clair Count...","6th Annual Lilac Festival, 10 a.m.-5 p.m. May ...",Cancer; Contractors; Meetings; Bands; Medical ...,"Times Herald; Port Huron, Mich.",2012,"May 16, 2012",KIOSK,Gannett Media Corp,"Port Huron, Mich.",...,News,1019537978,https://www.proquest.com/globalnewsfed/newspap...,2017-11-19,129.0,1.000000,"['port', 'st', 'pm', 'ave', 'road', 'library',...",St. Clair County Community College Fine Arts T...,0.961538,"(0.8, 1.0]"
1907,DAILY CALENDAR: Today,None available.,"Garage and Bake Sale, 9 a.m.-5 p.m. Lunch from...",NaN,"Times Herald; Port Huron, Mich.",2012,"Apr 18, 2012",KIOSK,Gannett Media Corp,"Port Huron, Mich.",...,News,1012297740,https://www.proquest.com/globalnewsfed/newspap...,2017-11-19,129.0,1.000000,"['port', 'st', 'pm', 'ave', 'road', 'library',...","Registration requested. (810) 794-4911, Ext. 1...",0.961538,"(0.8, 1.0]"
1993,Senior Activities,"Monday - Morning cards and puzzles, 8:30 a.m.;...",Shamokin-Coal Township Monday - Morning cards ...,NaN,"The News - Item; Shamokin, Pa.",2012,"Mar 11, 2012\n\nDateline: Shamokin, PA",News,Sample News Group,"Shamokin, Pa.",...,News,927590997,https://www.proquest.com/globalnewsfed/newspap...,2016-08-21,129.0,1.000000,"['port', 'st', 'pm', 'ave', 'road', 'library',...","Center St. Patrick's Day party will be held, a...",0.961538,"(0.8, 1.0]"
2035,IN BRIEF: Marysville man crashes into business,None available.,KIMBALL TWP. -- An 80-year-old Marysville man ...,NaN,"Times Herald; Port Huron, Mich.",2012,"Feb 18, 2012",A-Section,Gannett Media Corp,"Port Huron, Mich.",...,News,926918879,https://www.proquest.com/globalnewsfed/newspap...,2017-11-18,129.0,0.513535,"['port', 'st', 'pm', 'ave', 'road', 'library',...",The day will consist of three rounds of questi...,0.961538,"(0.8, 1.0]"
2065,Senior Citizen Activities Week Of Feb. 26-March 3,"Monday - Wii bowling, 9 to 10 a.m.; Exercise H...","Shamokin-Coal Township Monday - Morning cards,...",NaN,"The News - Item; Shamokin, Pa.",2012,"Feb 23, 2012\n\nDateline: Shamokin, PA",News,Sample News Group,"Shamokin, Pa.",...,News,923284890,https://www.proquest.com/globalnewsfed/newspap...,2016-08-21,129.0,0.206576,"['port', 'st', 'pm', 'ave', 'road', 'library',...",Snacks will be served and every one will have ...,0.961538,"(0.8, 1.0]"
2592,DAILY CALENDAR: Today,None available.,"Community Resource Fair, 10 a.m.-3 p.m. Offeri...",NaN,"Times Herald; Port Huron, Mich.\n\nFirst page:...",2013,"May 15, 2013\n\ncolumn: DAILY CALENDAR FOR MOR...",A-Section,Gannett Media Corp,"Port Huron, Mich.",...,News,1411134355,https://www.proquest.com/globalnewsfed/newspap...,2017-11-20,129.0,1.000000,"['port', 'st', 'pm', 'ave', 'road', 'library',...","May-O'Brien VFW Post 8465, 3815 Knapp Ave., Po...",0.961538,"(0.8, 1.0]"
2642,DAILY CALENDAR,None available.,"DAILY CALENDAR FOR MORE LISTINGS, GO TO WWW.TH...",NaN,"Lansing State Journal; Lansing, Mich.\n\nFirst...",2013,"Jan 13, 2013",B-Section,Gannett Media Corp,"Lansing, Mich.",...,News,1269465755,https://www.proquest.com/globalnewsfed/newspap...,2013-01-15,129.0,1.000000,"['port', 'st', 'pm', 'ave', 'road', 'library',...","St. Joseph Mercy Port Huron, 2601 Electric Ave...",0.961538,"(0.8, 1.0]"
2720,Man dies after falling from overpass onto I-69...,Sterling Heights Get your sensitive documents ...,WARREN Michigan State Police are trying to ide...,Tax abatement; Evacuations & rescues; Automobi...,"Detroit Free Press; Detroit, Mich.",2013,"Mar 3, 2013",Metro,Gannett Media Corp,"Detroit, Mich.",...,News,1314222003,https://www.proquest.com/globalnewsfed/newspap...,2017-11-19,129.0,1.000000,"['port', 'st', 'pm', 'ave', 'road', 'library',...",A forum Tuesday is 10:30-11 a.m. at the Monroe...,0.961538,"(0.8, 1.0]"
3301,AROUND TOWN: Award to honor keeper of Farmin...,The winner will receive a commemorative plaque...,The Farmington Heritage Preservation Commissio...,Cities; Awards & honors; Nominations; Wetlands...,"Star Tribune; Minneapolis, Minn.\n\nFirst page...",2014,"Apr 27, 2014",NEWS,Star Tribune Media Company LLC,"Minneapolis, Minn.",...,News,1519363465,https://www.proquest.com/newspapers/around-tow...,2017-11-20,129.0,1.000000,"['port', 'st', 'pm', 'ave', 'road', 'library',...",All proceeds will go toward purchasing a senio...,0.961538,"(0.8, 1.0]"
3432,DAILY CALENDAR: Special Events,None available.,46th Annual Beatrice Thornton Student Art Show...,NaN,"Times Herald; Port Huron, Mich.\n\nFirst page:...",2014,"Feb 17, 2014\n\ncolumn: DAILY CALENDAR FOR MOR...",A-Section,Gannett Media Corp,"Port Huron, Mich.",...,News,1498434622,https://www.proquest.com/newspapers/daily-cale...,2017-11-20,129.0,1.000000,"['port', 'st', 'pm', 'ave', 'road', 'library',...",Proceeds will be donated to a fund to benefit ...,0.961538,"(0.8, 1.0]"
3445,In brief: SC4 hosting Sanilac Academic Games,None available.,St. Clair County Community College will be hos...,NaN,"Times Herald; Port Huron, Mich.\n\nFirst page:...",2014,"Feb 14, 2014\n\ncolumn: in Brief",A-Section,Gannett Media Corp,"Port Huron, Mich.",...,News,1498083536,https://www.proquest.com/newspapers/brief/docv...,2017-11-21,129.0,0.515448,"['port', 'st', 'pm', 'ave', 'road', 'library',...","""I was interested to see up close the vast amo...",0.961538,"(0.8, 1.0]"
3478,CLUBS NEWS: Blue Water Audubon Society,"In addition to NACW, Bedore belongs to and con...",CLYDE TWP. -- Guest speaker will be Larry Corn...,Awards & honors; Cystic fibrosis; Secondary sc...,"Times Herald; Port Huron, Mich.\n\nFirst page:...",2014,"Jan 31, 2014\n\ncolumn: club news",A-Section,Gannett Media Corp,"Port Huron, Mich.",...,News,1492904831,https://www.proquest.com/newspapers/clubs-news...,2017-11-20,129.0,1.000000,"['port', 'st', 'pm', 'ave', 'road', 'library',...",Membership is open to women age 18 and older w...,0.961538,"(0.8, 1.0]"
3944,Daily Calendar,None available.,Today Marysville Knights of Columbus Seventh A...,NaN,"Times Herald; Port Huron, Mich.\n\nFirst page: 2",2015,"May 15, 2015",M,Gannett Media Corp,"Port Huron, Mich.",...,News,1680955112,https://www.proquest.com/globalnewsfed/newspap...,2017-11-22,129.0,1.000000,"['port', 'st', 'pm', 'ave', 'road', 'library',...","Mercy Health Center, First floor conference ro...",0.961538,"(0.8, 1.0]"
3963,In brief: Bridge work to close Lapeer Road F...,None available.,PORT HURON TWP. -- East and west Lapeer Road w...,NaN,"Times Herald; Port Huron, Mich.\n\nFirst page: 3",2015,"Jun 5, 2015",A,Gannett Media Corp,"Port Huron, Mich.",...,News,1686110076,https://www.proquest.com/globalnewsfed/newspap...,2017-11-22,129.0,1.000000,"['port', 'st', 'pm', 'ave', 'road', 'library',...",Guest speaker Holly Semrow is a board certifie...,0.961538,"(0.8, 1.0]"
4087,Club news: Blue Water Audubon Society,"The program, presented by SJMPH senior liaison...",The Blue Water Audubon Society will meet at 6:...,Wildlife observation\n\nLocation: Michigan,"Times Herald; Port Huron, Mich.\n\nFirst page: 4",2015,"Apr 5, 2015\n\ncolumn: club news",B,Gannett Media Corp,"Port Huron, Mich.",...,News,1669751584,https://www.proquest.com/globalnewsfed/newspap...,2017-11-22,129.0,1.000000,"['port', 'st', 'pm', 'ave', 'road', 'library',...",Healthy Aging Seminar St. Jospeh Mercy Port Hu...,0.961538,"(0.8, 1.0]"
4111,In brief: Blue Water Transit,None available.,public meeting scheduled MainStreet Port Huron...,NaN,"Times Herald; Port Huron, Mich.\n\nFirst page: 3",2015,"Mar 26, 2015",A,Gannett Media Corp,"Port Huron, Mich.",...,News,1666982350,https://www.pr oquest.com/globalnewsfed/newspa...,2017-11-22,129.0,0.473461,"['port', 'st', 'pm', 'ave', 'road', 'library',...","Upcoming seminars include ""Love Your Skin,"" Ma...",0.961538,"(0.8, 1.0]"
4199,Daily Calendar: Today,None available.,"Friends of the St. Clair Library Book Club, no...",NaN,"Times Herald; Port Huron, Mich.\n\nFirst page: 6",2015,"Feb 16, 2015\n\ncolumn: DAILY CALENDAR FOR MOR...",A,Gannett Media Corp,"Port Huron, Mich.",...,News,1655315283,https://www.proquest.com/globalnewsfed/newspap...,2017-11-21,129.0,1.000000,"['port', 'st', 'pm', 'ave', 'road', 'library',...","With Suzanne Povinelli, RN, of St. John Provid...",0.961538,"(0.8, 1.0]"
4273,In Brief: Chamber of commerce selects officers,None available.,Officers of the Blue Water Area Chamber of Com...,NaN,"Times Herald; Port Huron, Mich.\n\nFirst page: 1",2015,"Jan 11, 2015\n\ncolumn: in Brief",B,Gannett Media Corp,"Port Huron, Mich.",...,News,1644387928,https://www.proquest.com/globalnewsfed/newspap...,2017-11-21,129.0,1.000000,"['port', 'st', 'pm', 'ave', 'road', 'library',...","According to deputies, the man was northbound ...",0.961538,"(0.8, 1.0]"
5568,"DAILY CALENDAR FOR MORE LISTINGS, GO TO WWW.TH...",None available.,The Times Herald has moved to a new calendar d...,Hospitals; Gastrointestinal surgery; Registrat...,"Times Herald; Port Huron, Mich.\n\nFirst page:...",2017,"Feb 11, 2017",Production,Gannett Media Corp,"Port Huron, Mich.",...,News,1867122572,https://www.proquest.com/globalnewsfed/newspap...,2017-11-24,129.0,1.000000,"['port', 'st', 'pm', 'ave', 'road', 'library',...","POHO Pond Hockey, Feb. 17-19. Memorial Stadium...",0.961538,"(0.8, 1.0]"
6312,Fairfield Twp. promotes McCroskey to police se...,None available.,A 12-year Fairfield Township police officer is...,Primaries & caucuses; Pay structure; Firefight...,"Cincinnati Enquirer; Cincinnati, Ohio\n\nFirst...",2018,"Jan 11, 2018\n\ncolumn: Area news",Hometown,Gannett Media Corp,"Cincinnati, Ohio",...,News,1986318643,https://www.proquest.com/globalnewsfed/newspap...,2018-01-12,129.0,0.177349,"['port', 'st', 'pm', 'ave', 'road', 'library',...",On February 13 the registration costs will inc...,0.961538,"(0.8, 1.0]"
9073,LIVE NOW: It's Dec. 5. Our top story is: Could...,None available.,"Good morning, Barrie, Orillia and Simcoe Count...",Newsletters\n\nLocation: United States--US; Mi...,"Barrie - Advance; Barrie, Ont.",2023,"Dec 5, 2023",news,"Torstar Syndication Services, a Division of To...","Barrie, Ont.",...,News,2898649809,https://www.proquest.com/newspapers/live-now-d...,2023-12-07,129.0,1.000000,"['port', 'st', 'pm', 'ave', 'road', 'library',...","DINNER DATE: Explore our food guide, featuring...",0.961538,"(0.8, 1.0]"

***
Ad topic
***

In [77]:
df = remove_topic(df,129,[])

The orig length:10502 -> cropped: 10476

#### Topic 139

In [78]:
df[df['topic']==139]

,Title,Abstract,Full text,Subject,Publication title,Publication year,Publication date,Section,Publisher,Place of publication,...,Document type,ProQuest document ID,Document URL,Last updated,topic,topic_prob,topic_keywords,last,rel_ratio,rel_bins
159,Your town in brief: Tour 'mod' homes in WVC,None available.,West Valley City Mod home tour - Four homes in...,NaN,"The Salt Lake Tribune; Salt Lake City, Utah",2010,"Oct 6, 2010",NaN,The Salt Lake Tribune,"Salt Lake City, Utah",...,News,756776893,https://www.proquest.com/globalnewsfed/newspap...,2017-11-17,139.0,1.000000,"['vancouver', 'sept', 'st', 'hills', 'county',...",Uninsured seniors are asked to donate $20 for ...,0.88,"(0.8, 1.0]"
207,Too Good to Miss,Ancaster-Dundas-Flamborough Ontario Early Year...,"For nonprofit, charity or fundraising events i...",NaN,"The Spectator; Hamilton, Ont.\n\nFirst page: GO.6",2010,"Sep 20, 2010",Go,"Torstar Syndication Services, a Division of To...","Hamilton, Ont.",...,News,7515 06663,https://www.proquest.com/globalnewsfed/newspap...,2017-11-17,139.0,1.000000,"['vancouver', 'sept', 'st', 'hills', 'county',...","E., euchre, bid euchre, bingo, Wednesday, 1 p....",0.88,"(0.8, 1.0]"
373,Leadership program graduates 33 students,Following an initial two-day retreat to get to...,Thirty-three students graduated last month fro...,NaN,"Times News; Hendersonville, N.C.",2010,"Jun 12, 2010",NaN,Halifax Media Group,"Hendersonville, N.C.",...,News,375068722,https://www.proquest.com/globalnewsfed/newspap...,2012-11-02,139.0,1.000000,"['vancouver', 'sept', 'st', 'hills', 'county',...","Lee Smith Utilities director, city of Henderso...",0.88,"(0.8, 1.0]"
467,Have your say,"James Shapiro's op-ed (Alas Poor Shakespeare, ...","Goodbye, Bard of Avon James Shapiro's op-ed (A...",NaN,"Winnipeg Free Press; Winnipeg, Man.\n\nFirst p...",2010,"Apr 21, 2010",NaN,FP Canadian Newspapers Limited Partnership,"Winnipeg, Man.",...,News,580133637,https://www.proquest.com/g lobalnewsfed/newspa...,2017-11-17,139.0,1.000000,"['vancouver', 'sept', 'st', 'hills', 'county',...",The Transportation Options Network for Seniors...,0.88,"(0.8, 1.0]"
627,Antique Show Benefits Woman's Club,"Advance sale tickets are $4, which will go to ...",The 47th Annual Antique Show will support the ...,NaN,"The Ledger; Lakeland, Fla.",2010,"Jan 18, 2010",NaN,Halifax Media Group,"Lakeland, Fla.",...,Feature,390158088,https://www.proquest.com/globalnewsfed/newspap...,2012-10-12,139.0,1.000000,"['vancouver', 'sept', 'st', 'hills', 'county',...","[ Send your news regarding civic groups, socia...",0.88,"(0.8, 1.0]"
1370,Around the area,None available.,Clark county Nominees sought for Caring Hearts...,Public health; Nominations; Task forces; Older...,"Columbian; Vancouver, Wash.\n\nFirst page: C.3",2011,"Jan 7, 2011",Clark County,Columbian Publishing Company,"Vancouver, Wash.",...,News,2581187884,https://www.proquest.com/globalnewsfed/newspap...,2021-10-13,139.0,0.078537,"['vancouver', 'sept', 'st', 'hills', 'county',...",Building 17. The task force has to update its ...,0.88,"(0.8, 1.0]"
2018,The Pi Omega Chapter of Omega Psi Phi,"""Ever since the beginning, there's always been...","Since its inception, the Pi Omega Chapter of O...",Fraternities & sororities; Community service; ...,"Afro - American, 5 Star edition; Baltimore, Md...",2012,"Feb 25-Mar 2, 2012",NaN,Afro - American Company of Baltimore City,"Baltimore, Md.",...,News\n\nDocument feature: Photographs,928112028,https://www.proquest.com/globalnewsfed/newspap...,2012-03-15,139.0,1.000000,"['vancouver', 'sept', 'st', 'hills', 'county',...","Nearly eight months later, the Baltimore City ...",0.88,"(0.8, 1.0]"
2131,Your Thanks,"Morningside Shelter, Bonnyvale Environmental E...",Editor of the Reformer: From Nov. 8 through No...,Nonprofit organizations; Volunteers; Donations...,"The Brattleboro Reformer; Brattleboro, Vt.",2013,"Dec 16, 2013",Opinion,"New England Newspapers, Inc.","Brattleboro, Vt.",...,News,1468422445,https://www.proquest.com/globalnewsfed/newspap...,2013-12-16,139.0,1.000000,"['vancouver', 'sept', 'st', 'hills', 'county',...","Basketville, Dosolutions, Green Mountain Orcha...",0.88,"(0.8, 1.0]"
2438,In brief: Partnership offers services for se...,None available.,RHINEBECK -- Health Quest has announced a part...,NaN,"The Poughkeepsie Journal; Poughkeepsie, N.Y.\n...",2013,"Jul 23, 2013",B,Gannett Media Corp,"Poughkeepsie, N.Y.",...,News,1411088405,https://www.proquest.com/globalnewsfed/newspap...,2017-11-20,139.0,1.000000,"['vancouver', 'sept', 'st', 'hills', 'county',...",Call 845-758-8185 for tickets. Nonprofits can ...,0.88,"(0.8, 1.0]"
2571,Burnaby-based reality show up for three Leos,Aging fair Lougheed Town Centre and the Burnab...,"The Liquidator, the Burnaby-based reality TV s...",Aging; Television programs; Business plans; Se...,"Burnaby Now; Burnaby, B.C.\n\nFirst page: 11",2013,"May 22, 2013",Business,Postmedia Network Inc.,"Burnaby, B.C.",...,Column,1354605176,https://www.proquest.com/globalnewsfed/newspap...,2013-05-24,139.0,0.147741,"['vancouver', 'sept', 'st', 'hills', 'county',...",Netherworld Collectibles at 4251 Hastings St. ...,0.88,"(0.8, 1.0]"
2590,Best bets for the week,Family concert in Oak Brook Explore musical in...,Make Way for Music DuPage Children's Museum vo...,Musical instruments; Museums; Gardens & garden...,"Chicago Tribune; Chicago, Ill.",2013,"May 16, 2013",NaN,"Tribune Publishing Company, LLC","Chicago, Ill.",...,News,1351560902,https://www.proquest.com/globalnewsfed/newspap...,2017-11-20,139.0,1.000000,"['vancouver', 'sept', 'st', 'hills', 'county',...",Silver Lake at Blackwell Forest Preserve in Wa...,0.88,"(0.8, 1.0]"
3607,The Birches gives thanks and gives back,"At the beginning of November, The Birches bega...",Although Thanksgiving is best known as a time ...,NaN,"Daily Herald; Arlington Heights, Ill.",2015,"Nov 26, 2015",Submitted Content,Daily Herald,"Arlington Heights, Ill.",...,News,1736841016,https://www.proquest.com/globalnewsfed/newspap...,2017-11-22,139.0,1.000000,"['vancouver', 'sept', 'st', 'hills', 'county',...",The Birches offers purposeful programming and ...,0.88,"(0.8, 1.0]"
3765,Check out those vintage wheels,Burnaby resident Paul Fata is organizing the s...,"group of car enthusiasts, to raise money for t...",Food; Fund raising\n\nIdentifier / keyword: gr...,"Burnaby Now; Burnaby, B.C.\n\nFirst page: A.13",2015,"Sep 18, 2015",City,Postmedia Network Inc.,"Burnaby, B.C.",...,News,1713767761,https://www.proquest.com/globalnewsfed/newspap...,2015-09-19,139.0,1.000000,"['vancouver', 'sept', 'st', 'hills', 'county',...","The market is open this Saturday, from 9 a.m. ...",0.88,"(0.8, 1.0]"
3836,A taste from the north,"The Barrington Area Council on Aging, Barringt...",Bring the whole family to enjoy a Door County ...,NaN,"Daily Herald; Arlington Heights, Ill.\n\nFirst...",2015,"Aug 12, 2015",NEIGHBOR,Daily Herald,"Arlington Heights, Ill.",...,News,1703672507,https://www.proquest.com/globalnewsfed/newspap...,2017-11-22,139.0,1.000000,"['vancouver', 'sept', 'st', 'hills', 'county',...","The Barrington Area Council on Aging Inc., is ...",0.88,"(0.8, 1.0]"
3971,IN BRIEF,None available.,City fixing watermain Kelly Lake Road is down ...,Journalism; Rites & ceremonies; Older people; ...,"Sudbury Star; Sudbury, Ont.\n\nFirst page: A.2",2015,"Jun 3, 2015",News,Postmedia Network Inc.,"Sudbury, Ont.",...,News,2226245902,https://www.proquest.com/globalnewsfed/newspap...,2019-05-17,139.0,1.000000,"['vancouver', 'sept', 'st', 'hills', 'county',...","The camp will be led by Rachel Desaulniers, jo...",0.88,"(0.8, 1.0]"
4085,Around the area,The Clark County Commission on Aging is leadin...,vancouver Enlisted students to be recognized A...,Counties; Community; Restaurants; Health care;...,"Columbian; Vancouver, Wash.\n\nFirst page: C.4",2015,"Apr 7, 2015",Metro,Columbian Publishing Company,"Vancouver, Wash.",...,News,1673108053,https://www.proquest.com/globalnewsfed/newspap...,2021-10-14,139.0,0.137509,"['vancouver', 'sept', 'st', 'hills', 'county',...","Duties include patrolling, answering 911 calls...",0.88,"(0.8, 1.0]"
4629,"The Birches kicks off summer with 2nd annual ""...","""It was a classic beginning of summer barbecue...","On June 15, The Birches Assisted Living in Cla...",NaN,"Daily Herald; Arlington Heights, Ill.",2016,"Jun 18, 2016",Submitted Content,Daily Herald,"Arlington Heights, Ill.",...,News,179803080 8,https://www.proquest.com/globalnewsfed/newspap...,2017-11-23,139.0,1.000000,"['vancouver', 'sept', 'st', 'hills', 'county',...","For more information about The Birches, call 6...",0.88,"(0.8, 1.0]"
6019,Birches Assisted Living Hosts Antique Appraisa...,None available.,Have a family heirloom you’re sure is somethin...,Automobile shows; Automobiles\n\nCompany / org...,"Daily Herald; Arlington Heights, Ill.",2018,"Jun 12, 2018",Submitted Content,Daily Herald,"Arlington Heights, Ill.",...,News,2053533609,https://www.proquest.com/globalnewsfed/newspap...,2018-06-12,139.0,1.000000,"['vancouver', 'sept', 'st', 'hills', 'county',...",The Birches Assisted Living in Clarendon Hills...,0.88,"(0.8, 1.0]"
6609,Goodwill has tips on back-to-school shopping,None available.,"It's back-to-school time, and Goodwill Industr...",Clothing; Older people; Workshops; Donations; ...,"Herald Times Reporter; Manitowoc, Wis.\n\nFirs...",2019,"Aug 14, 2019\n\ncolumn: Briefs",News,Gannett Media Corp,"Manitowoc, Wis.",...,News,2272633692,https://www.proquest.com/globalnewsfed/newspap...,2019-08-14,139.0,0.097290,"['vancouver', 'sept', 'st', 'hills', 'county',...","For more information, call Felician Village at...",0.88,"(0.8, 1.0]"
6889,Public meetings,None available.,Monday Fort Vancouver Regional Library Board o...,Public schools; Agreements; Urban forestry; Co...,"Columbian; Vancouver, Wash.\n\nFirst page: C.7",2019,"Mar 17, 2019",Metro,Columbian Publishing Company,"Vancouver, Wash.",...,News,2193664326,https://www.proquest.com/globalnewsfed/newspap...,2021-10-15,139.0,1.000000,"['vancouver', 'sept', 'st', 'hills', 'county',...","n 6:30 p.m., public hearing: open space and ti...",0.88,"(0.8, 1.0]"
7599,Reservations now being accepted,None available.,The Horticulture Department of the Somerset Co...,Weddings; Gardens & gardening; Rites & ceremon...,"Home News Tribune; East Brunswick, N.J.\n\nFir...",2020,"Jan 7, 2020\n\ncolumn: central jersey daily ru...",News,Gannett Media Corp,"East Brunswick, N.J.",...,News,2333843876,https://www.proquest.com/newspapers/reservatio...,2020-01-07,139.0,0.064226,"['vancouver', 'sept', 'st', 'hills', 'county',...",Nearly $100 million has been raised so far to ...,0.88,"(0.8, 1.0]"
8433,Local veterans invited to Celebrating our Vete...,None available.,The Atrium at Oak Crest in Elgin will host a s...,Veterans,"Daily Herald; Arlington Heights, Ill.",2022,"Oct 11, 2022",Submitted Content,Daily Herald,"Arlington Heights, Ill.",...,News,2723504814,https://www.pr oquest.com/globalnewsfed/newspa...,2022-10-11,139.0,0.085193,"['vancouver', 'sept', 'st', 'hills', 'county',...",Its focus is on healthy aging to enrich the qu...,0.88,"(0.8, 1.0]"
9154,Coats for Kids event a big success,None available.,"The Mansfield Noon Optimist Club, in partnersh...",Donations; Aging; Education; School boards\n\n...,"News Journal; Mansfield, Ohio\n\nFirst page: A.3",2023,"Nov 11, 2023\n\ncolumn: Local news briefs",News,Gannett Media Corp,"Mansfield, Ohio",...,News,2888523431,https://www.proquest.com/newspapers/coats-kids...,2023-11-11,139.0,1.000000,"['vancouver', 'sept', 'st', 'hills', 'county',...",Grants are being distributed to counties to bo...,0.88,"(0.8, 1.0]"
9760,Lineup keeps seniors active,None available.,(Marie Reine) - Northern Sunrise County/Nampa ...,Older people; Community support; Christmas\n\n...,"The South Peace News; High Prairie, Alta.\n\nF...",2024,"Nov 27, 2024\n\nDateline: Marie Reine",News,Postmedia Network Inc.,"High Prairie, Alta.",...,News,3133569616,https://www.proquest.com/globalnewsfed/newspap...,2024-11-28,139.0,0.103496,"['vancouver', 'sept', 'st', 'hills', 'county',...",The concert is in both English and French and ...,0.88,"(0.8, 1.0]"

In [79]:
df = remove_topic(df,139,[])

The orig length:10476 -> cropped: 10452

#### Topic 154

In [80]:
df[df['topic']==154]

,Title,Abstract,Full text,Subject,Publication title,Publication year,Publication date,Section,Publisher,Place of publication,...,Document type,ProQuest document ID,Document URL,Last updated,topic,topic_prob,topic_keywords,last,rel_ratio,rel_bins
103,People & Changes,MARK BOSTICK has been elected as chairman of t...,MARK BOSTICK has been elected as chairman of t...,NaN,"The Ledger; Lakeland, Fla.",2010,"Nov 1, 2010",NEWS,Halifax Media Group,"Lakeland, Fla.",...,News,761401304,https://www.proquest.com/globalnewsfed/newspap...,2012-10-12,154.0,1.000000,"['named', 'vice president', 'vice', 'president...","[ Send information for People & Changes, On th...",1.0,"(0.8, 1.0]"
129,Companies Associations/nonprofits Communicatio...,ITT of McLean named Kenneth W. Hunzeker vice p...,Strategic Enterprise Solutions of Reston named...,Appointments & personnel changes; Intellectual...,"The Washington Post; Washington, D.C.",2010,"Oct 18, 2010\n\nDateline: A",A-SECTION,WP Company LLC d/b/a The Washington Post,"Washington, D.C.",...,News,758828779,https://www.proquest.com/globalnewsfed/newspap...,2017-11-17,154.0,1.000000,"['named', 'vice president', 'vice', 'president...","Vorys, Sater, Seymour and Pease of the Distric...",1.0,"(0.8, 1.0]"
267,APPOINTMENTS,The National Council on Aging of the District ...,"Gannett of McLean named Travis Fore, former se...",Appointments & personnel changes; Natural prod...,"The Washington Post; Washington, D.C.",2010,"Aug 23, 2010",A SECTION,WP Company LLC d/b/a The Washington Post,"Washington, D.C.",...,News,746398166,https://www.proquest.com/globalnewsfed/newspap...,2017-11-17,154.0,1.000000,"['named', 'vice president', 'vice', 'president...",Andrews Kurth of the District named Eric R. Ma...,1.0,"(0.8, 1.0]"
721,Business People Twin Cities,"ADVOCACY Nancy Kielhofner, a former Allina Hos...","ADVOCACY Nancy Kielhofner, a former Allina Hos...",Executives; Appointments & personnel changes; ...,"Saint Paul Pioneer Press; Saint Paul, Minn.",2011,"Nov 19, 2011",Business People,St Paul Pioneer Press,"Saint Paul, Minn.",...,News,905005578,https://www.proquest.com/globalnewsfed/newspap...,2011-11-20,154.0,1.000000,"['named', 'vice president', 'vice', 'president...",Complete Nutrition is a nutritional supplement...,1.0,"(0.8, 1.0]"
2080,Business & professional briefs,"Accounting firm promotes three. Wendy Hendon, ...",New jobs Heiser named to bank post. Ryan E. He...,NaN,"News Gazette; Champaign, Ill.\n\nFirst page: E.3",2012,"Jan 15, 2012",NaN,News Gazette,"Champaign, Ill.",...,News,919209617,https://www.proquest.com/globalnewsfed/newspap...,2016-08-21,154.0,1.000000,"['named', 'vice president', 'vice', 'president...",Items may be emailed to dodson@news-gazette.co...,1.0,"(0.8, 1.0]"
2109,Who's News: Claerbout inducted into industry...,"Wendee Hauch, office manager and chiropractic ...","Daven Claerbout, co-owner/executive vice presi...",Aging; Small business; Associations; Continuin...,"Press; Sheboygan, Wis.",2012,"Jan 1, 2012",SHE,Sheboygan Press,"Sheboygan, Wis.",...,News,913480503,https://www.proquest.com/globalnewsfed/newspap...,2017-11-18,154.0,1.000000,"['named', 'vice president', 'vice', 'president...",Certified Professional Restoration adds projec...,1.0,"(0.8, 1.0]"
2335,DID YOU MISS?,None available.,BOARD DIRECTORS Advertised: September 7 Employ...,NaN,"The Advertiser; Adelaide, S. Aust.\n\nFirst pa...",2013,"Sep 14, 2013",Careerone,Nationwide News Pty Ltd,"Adelaide, S. Aust.",...,News,1432025133,https://www.proquest.com/globalnewsfed/newspap...,2017-11-20,154.0,0.052161,"['named', 'vice president', 'vice', 'president...",It wants to recruit up to three future-focused...,1.0,"(0.8, 1.0]"
2797,business people,"Bell State Bank & Trust, Golden Valley, named ...","moving up Liberty Diversified International, N...",Acquisitions & mergers; Executives\n\nLocation...,"Star Tribune; Minneapolis, Minn.\n\nFirst page...",2013,"Jan 28, 2013",BUSINESS,Star Tribune Media Company LLC,"Minneapolis, Minn.",...,News,1282654201,https://www.proquest.com/globalnewsfed/newspap...,2017-11-20,154.0,1.000000,"['named', 'vice president', 'vice', 'president...","Bell State Bank & Trust, Golden Valley, named ...",1.0,"(0.8, 1.0]"
2812,"Business briefing, Sunday, Jan. 20",None available.,ASSOCIATIONS The North Star Chapter of the App...,NaN,"Saint Paul Pioneer Press; Saint Paul, Minn.",2013,"Jan 19, 2013",Business People,St Paul Pioneer Press,"Saint Paul, Minn.",...,News,1271150236,https://www.proquest.com/globalnewsfed/newspap...,2013-01-20,154.0,1.000000,"['named', 'vice president', 'vice', 'president...","REAL ESTATE NAI Everest, a full service broker...",1.0,"(0.8, 1.0]"
2908,COMMUNITY NEWS COMMUNITY NEWS,"The new, interactive Xfinity Store, the fourth...",XFINITY OPENS IN WEST HARTFORD WEST HARTFORD -...,Breast cancer; Accreditation; Food; Bankruptcy...,"Hartford Courant; Hartford, Conn.\n\nFirst pag...",2014,"Nov 16, 2014",MYTOWNS,"Tribune Publishing Company, LLC","Hartford, Conn.",...,News,1625399494,https://www.proquest.com/newspapers/community-...,2014-11-17,154.0,0.119949,"['named', 'vice president', 'vice', 'president...",The package also includes overnight accommodat...,1.0,"(0.8, 1.0]"
3826,CAREER LADDER,The Hospital for Special Care based in New Bri...,BANKS Chelsea Clary has joined the Hartford Fe...,Credit unions; Physicians; Education; Palliati...,"Hartford Courant; Hartford, Conn.\n\nFirst pag...",2015,"Oct 25, 2015",SUNDAYCT,"Tribune Publishing Company, LLC","Hartford, Conn.",...,News,1726855697,https://www.proquest.com/globalnewsfed/newspap...,2015-10-26,154.0,1.000000,"['named', 'vice president', 'vice', 'president...","Each week, The Courant highlights workplace pr...",1.0,"(0.8, 1.0]"
4036,Players,THOMAS N. LORD has been appointed vice preside...,NICHOLAS G. USZAKI has joined National Penn Ba...,Appointments & personnel changes; Corporate pr...,"Morning Call; Allentown, Pa.\n\nFirst page: A.18",2015,"Apr 30, 2015",News,"Tribune Publishing Company, LLC","Allentown, Pa.",...,News,1677309080,https://www.proquest.com/globalnewsfed/newspap...,2017-11-22,154.0,0.238358,"['named', 'vice president', 'vice', 'president...",Rittle has worked in the United Way system sin...,1.0,"(0.8, 1.0]"
4530,City Council will weigh DMD requests on grant ...,None available.,City Council on Monday will discuss a request ...,Community development block grants; Councils; ...,"Evansville Courier & Press; Evansville, Ind.\n...",2016,"Aug 22, 2016",News,Gannett Media Corp,"Evansville, Ind.",...,News,2591128356,https://www.proquest.com/globalnewsfed/newspap...,2021-11-02,154.0,0.038773,"['named', 'vice president', 'vice', 'president...",It begins at 4:15 p.m. Monday in room 301 of t...,1.0,"(0.8, 1.0]"
4559,PLAYERS,Reed came to Planned Parenthood after serving ...,MIKE KRAHLING and ERIC SAMLEY ATAS Internation...,Appointments & personnel changes; Public polic...,"Morning Call; Allentown, Pa.\n\nFirst page: A.19",2016,"Jul 29, 2016",NaN,"Tribune Publishing Company, LLC","Allentown, Pa.",...,News,1807530891,https://www.proquest.com/globalnewsfed/newspap...,2017-11-23,154.0,1.000000,"['named', 'vice president', 'vice', 'president...","In that capacity, she increased funding for pu...",1.0,"(0.8, 1.0]"
4579,CAREER LADDER,Farmington-based registered investment adviser...,ARTS Connecticut Repertory Theatre has named M...,Appointments & personnel changes; Chief execut...,"Hartford Courant; Hartford, Conn.\n\nFirst pag...",2016,"Jul 17, 2016",NaN,"Tribune Publishing Company, LLC","Hartford, Conn.",...,News,1804593414,https://www.proquest.com/globalnewsfed/newspap...,2016-07-18,154.0,1.000000,"['named', 'vice president', 'vice', 'president...",Farmington-based registered investment adviser...,1.0,"(0.8, 1.0]"
5177,PPL shouldn't support Sen. Toomey,None available.,PPL isn't slow to elevate its charitable givin...,Donations; Tax cuts\n\nLocation: Lehigh Valley...,"Morning Call; Allentown, Pa.\n\nFirst page: A.13",2017,"Sep 22, 2017",NaN,"Tribune Publishing Company, LLC","Allentown, Pa.",...,News,1941256590,https://www.proquest.com/globalnewsfed/newspap...,2017-11-24,154.0,0.045975,"['named', 'vice president', 'vice', 'president...",These malicious bills would kick millions off ...,1.0,"(0.8, 1.0]"
6236,Business & Professional Briefs,None available.,New jobs Three join RSM. RSM recently announce...,Science; Bone surgery; Bus drivers; Nurse prac...,"News Gazette; Champaign, Ill.\n\nFirst page: C.2",2018,"Feb 25, 2018",NaN,News Gazette,"Champaign, Ill.",...,News,2018313988,https://www.proquest.com/globalnewsfed/newspap...,2023-11-07,154.0,1.000000,"['named', 'vice president', 'vice', 'president...",Items may be emailed to tmitchel@news-gazette....,1.0,"(0.8, 1.0]"
6310,PLAYERS,None available.,JOHN WARD John Ward has been named dean of the...,Appointments & personnel changes; Energy; Educ...,"Morning Call; Allentown, Pa.\n\nFirst page: A.14",2018,"Jan 11, 2018",NaN,"Tribune Publishing Company, LLC","Allentown, Pa.",...,News,1986321481,https://www.proquest.com/globalnewsfed/newspap...,2018-01-11,154.0,1.000000,"['named', 'vice president', 'vice', 'president...",Bell holds a BA in liberal arts from City Coll...,1.0,"(0.8, 1.0]"
7247,Community,None available.,"Community Philip M. Reagan, executive director...",Marketing; Presidents; Geriatrics; Attorneys; ...,"South Florida Sun - Sentinel; Fort Lauderdale,...",2020,"Aug 30, 2020",NaN,"Tribune Publishing Company, LLC","Fort Lauderdale, Fla.",...,News,2438369164,https://www.proquest.com/newspapers/community/...,2020-08-30,154.0,1.000000,"['named', 'vice president', 'vice', 'president...",Cifre joined Veritas Farms in 2019 as a market...,1.0,"(0.8, 1.0]"
7850,Northwest Community Credit Union president win...,None available.,Northwest Community Credit Union president win...,Small business; Credit unions; Lakes; Camping;...,"Daily Herald; Arlington Heights, Ill.\n\nFirst...",2021,"Aug 23, 2021",Biz Ledger,Daily Herald,"Arlington Heights, Ill.",...,News,2563504216,https://www.proquest.com/newspapers/northwest-...,2021-08-23,154.0,0.070162,"['named', 'vice president', 'vice', 'president...","During the second quarter, Surgalign made sign...",1.0,"(0.8, 1.0]"
8948,NEWSMAKERS,None available.,Arnall Golden Gregory has announced the promot...,Retirement communities; Appointments & personn...,"The Atlanta Journal - Constitution; Atlanta, G...",2022,"Feb 6, 2022",BUSINESS,"Atlanta Journal Constitution, LLC","Atlanta, Ga.",...,News,2625726017,https://www.proquest.com/globalnewsfed/newspap...,2022-02-06,154.0,1.000000,"['named', 'vice president', 'vice', 'president...",Kilpatrick Townsend & Stockton announced that ...,1.0,"(0.8, 1.0]"
9471,Area Agency on Aging receives Aging Innovation...,None available.,ONTARIO — The Area Agency on Aging's Community...,Innovations; Patents; Awards & honors; Aging; ...,"Telegraph - Forum; Bucyrus, Ohio\n\nFirst page...",2023,"Aug 2, 2023\n\ncolumn: local news in brief",News,Gannett Media Corp,"Bucyrus, Ohio",...,News,2844456336,https://www.proquest.com/newspapers/area-agenc...,2023-08-02,154.0,0.044579,"['named', 'vice president', 'vice', 'president...",A number of communities have group sales in pu...,1.0,"(0.8, 1.0]"

***
Not a strongly related topic and also contains ads
***

In [81]:
df = remove_topic(df,154,[])

The orig length:10452 -> cropped: 10430

#### Topic 165

In [82]:
df[df['topic']==165]

,Title,Abstract,Full text,Subject,Publication title,Publication year,Publication date,Section,Publisher,Place of publication,...,Document type,ProQuest document ID,Document URL,Last updated,topic,topic_prob,topic_keywords,last,rel_ratio,rel_bins
120,Large print books available at library,If you are physically unable to visit the bran...,The Windsor Public Library's philosophy is tha...,Libraries; Stress; Blood pressure,"The Windsor Star; Windsor, Ont.\n\nFirst page:...",2010,"Oct 22, 2010",News,Postmedia Network Inc.,"Windsor, Ont.",...,News,759711796,https://www.proquest.com/globalnewsfed/newspap...,2017-11-17,165.0,1.0,"['church', 'pm', 'club', 'welcome', 'march', '...","130. Mail information to Natalie Taylor, 3448 ...",0.9,"(0.8, 1.0]"
1811,Fridge News; A Weekly Look At What's Happening...,The event goes Fridays from 10-11:30 a.m. It's...,TO GET YOUR ANNOUNCEMENT IN THE FRIDGE NEWS Ca...,NaN,"The Taber Times; Taber, Alta.\n\nFirst page: A.6",2012,"May 30, 2012",News,Postmedia Network Inc.,"Taber, Alta.",...,News,1018202590,https://www.proquest.com/globalnewsfed/newspap...,2016-09-17,165.0,1.0,"['church', 'pm', 'club', 'welcome', 'march', '...",GENERAL INFORMATION L.T. Westlake Parent Advis...,0.9,"(0.8, 1.0]"
1822,Local briefs: Center for aging to hold open ...,None available.,RHINEBECK - The Center for Healthy Aging at No...,NaN,"The Poughkeepsie Journal; Poughkeepsie, N.Y.",2012,"May 25, 2012",Local News,Gannett Media Corp,"Poughkeepsie, N.Y.",...,News,1015792740,https://www.proquest.com/globalnewsfed/newspap...,2017-11-19,165.0,1.0,"['church', 'pm', 'club', 'welcome', 'march', '...","For more information, call 845-889-4745 Ext. 1...",0.9,"(0.8, 1.0]"
2048,Church offers interesting Friday night date,Kathleen Shatt is on hiatus. [...] she returns...,The Women of John Wesley United Methodist Chur...,Dance; Bone density; Lutheran churches,"Maryland Gazette; Glen Burnie, Md.\n\nFirst pa...",2012,"Feb 11, 2012",NaN,"Tribune Publishing Company, LLC","Glen Burnie, Md.",...,News,921228207,https://www.proquest.com/globalnewsfed/news pa...,2016-10-22,165.0,1.0,"['church', 'pm', 'club', 'welcome', 'march', '...","Registration is not required. For details, cal...",0.9,"(0.8, 1.0]"
2228,SFU Surrey: The month ahead,The SFU Surrey campus will host a Police Fair ...,The following is a look ahead at events to be ...,NaN,"The Leader; Surrey, B.C.\n\nFirst page: 1",2013,"Nov 5, 2013",Business,"Torstar Syndication Services, a Division of To...","Surrey, B.C.",...,News,1448416665,https://www.proquest.com/globalnewsfed/newspap...,2013-11-05,165.0,1.0,"['church', 'pm', 'club', 'welcome', 'march', '...",Knowledge Creation @ SFU Surrey will feature a...,0.9,"(0.8, 1.0]"
2399,SENIORS,Seniors Crisis Counseling The Long Island Cris...,'Knit and Crochet for Charity' East Meadow: El...,Aging; Older people; Libraries; Nominations,"Newsday, Combined editions; Long Island, N.Y.\...",2013,"Aug 11, 2013",LI LIFE,Newsday LLC,"Long Island, N.Y.",...,News,1419107578,https://www.proquest.com/globalnewsfed/newspap...,2017-11-20,165.0,1.0,"['church', 'pm', 'club', 'welcome', 'march', '...",'Savvy Senior' Nominations LI Association of G...,0.9,"(0.8, 1.0]"
2672,The week ahead,None available.,SUNDAY MARCH 24 The Ottawa Gatineau Internatio...,NaN,"The Ottawa Citizen; Ottawa, Ont.\n\nFirst page...",2013,"Mar 23, 2013",Life,Postmedia Network Inc.,"Ottawa, Ont.",...,News,1318989427,https://www.proquest.com/globalnewsfed/newspap...,2017-11-20,165.0,1.0,"['church', 'pm', 'club', 'welcome', 'march', '...",There will be eggs and chocolate bunnies to be...,0.9,"(0.8, 1.0]"
2939,Save the Dates,The event benefit the patients of the AIDS Act...,CRIME FIGHTING GALA: The Officer David M. Petz...,Charitable foundations; Art galleries & museums,"Morning Call; Allentown, Pa.\n\nFirst page: Go.7",2014,"Nov 2, 2014",Sunday_Go_Guide,"Tribune Publishing Company, LLC","Allentown, Pa.",...,News,1619427284,https://www.proquest.com/newspapers/save-dates...,2017-11-21,165.0,1.0,"['church', 'pm', 'club', 'welcome', 'march', '...",Proceeds benefit the nonprofit ArtsQuest Found...,0.9,"(0.8, 1.0]"
3226,Top 5 things to do,The McGill library branch is hosting a Lego Cl...,Looking for something to do this weekend? Look...,Older people,"Burnaby Now; Burnaby, B.C.\n\nFirst page: A.24",2014,"May 30, 2014",News,Postmedia Network Inc.,"Burnaby, B.C.",...,News,1530748799,https://www.proquest.com/newspapers/top-5-thin...,2014-06-01,165.0,1.0,"['church', 'pm', 'club', 'welcome', 'march', '...","The event is free, and registration is not req...",0.9,"(0.8, 1.0]"
3240,What's Happening,May 23 Everyone is welcome to attend a talent ...,The deadline for community event submissions i...,NaN,"Ottawa South EMC; Ottawa, Ont.\n\nFirst page: ...",2014,"May 22, 2014",News,Postmedia Network Inc.,"Ottawa, Ont.",...,News,1527252584,https://www.proquest.com/newspapers/whats-happ...,2014-05-23,165.0,1.0,"['church', 'pm', 'club', 'welcome', 'march', '...",The Hogs Back 50-plus Club meets every Tuesday...,0.9,"(0.8, 1.0]"
3972,Community briefs,Recovery Point of Huntington is expanding to s...,Community meeting Recovery Point of Huntington...,NaN,"Charleston Daily Mail; Charleston, W.V.\n\nFir...",2015,"Jun 3, 2015",NaN,Charleston Newspapers,"Charleston, W.V.",...,News,1686492973,https://www.proquest.com/globalnewsfed/newspap...,2017-11-22,165.0,1.0,"['church', 'pm', 'club', 'welcome', 'march', '...",Cost is $75 for Pricketts Fort Memorial Founda...,0.9,"(0.8, 1.0]"
4614,SLICE OF LIFE: June 24 to July 1,Abbotsford Association for Healthy Aging (AAHA...,The following is a list of just some of the ac...,NaN,"The News; Abbotsford, B.C.",2016,"Jun 24, 2016",Community,Black Press Group Ltd.,"Abbotsford, B.C.",...,News,1799359630,https://www.proquest.com/globalnewsfed/newspap...,2016-06-25,165.0,1.0,"['church', 'pm', 'club', 'welcome', 'march', '...",See alsowww.sa.org. CARPET BOWLING Carpet bowl...,0.9,"(0.8, 1.0]"
5163,Coshocton County Senior Center October Events,None available.,Pancakes will be served every morning from 8 t...,Senior citizen centers\n\nCompany / organizati...,"Coshocton Tribune; Coshocton, Ohio\n\nFirst pa...",2017,"Sep 28, 2017",News,Gannett Media Corp,"Coshocton, Ohio",...,News,1943512832,https://www.proquest.com/globalnewsfed/newspap...,2017-11-24,165.0,1.0,"['church', 'pm', 'club', 'welcome', 'march', '...",A mystery trip will be from 9 a.m. to 6 p.m. O...,0.9,"(0.8, 1.0]"
6240,Here's what's going on in Miramichi,"Friday, Feb. 23 9 a.m. to 12 p.m., weekly, at ...","Friday, Feb. 23 9 a.m. to 12 p.m., weekly, at ...",Councils; Breastfeeding & lactation; Volunteer...,"Miramichi Leader; Miramichi, N.B.\n\nFirst pag...",2018,"Feb 23, 2018",NaN,Postmedia Network Inc.,"Miramichi, N.B.",...,News,2007294032,https://www.proquest.com/globalnewsfed/newspap...,2018-02-23,165.0,1.0,"['church', 'pm', 'club', 'welcome', 'march', '...",There will also be a half and half draw and th...,0.9,"(0.8, 1.0]"
7470,10 things to do in Halton this week,None available.,Here are 10 interesting things to do around Ha...,Public libraries; Food; Performing arts; Nutri...,"The Independent & Free Press; Georgetown, Ont.",2020,"Mar 8, 2020",WhatsOn,"Torstar Syndication Services, a Division of To...","Georgetown, Ont.",...,News,2374729722,https://www.proquest.com/newspapers/10-things-...,2020-03-09,165.0,1.0,"['church', 'pm', 'club', 'welcome', 'march', '...","Masters of Illusion When: Friday, March 13, 8 ...",0.9,"(0.8, 1.0]"
7598,CALENDAR,None available.,"Monday, Jan. 6 ARTS-ENTERTAINMENT-MUSIC: 1 hou...",Support groups; Masonic organizations; Luthera...,"Bismarck Tribune; Bismarck, ND\n\nFirst page: 2",2020,"Jan 6, 2020",B,Bismarck Tribune,"Bismarck, ND",...,News,2333649084,https://www.proquest.com/newspapers/calendar/d...,2020-01-06,165.0,1.0,"['church', 'pm', 'club', 'welcome', 'march', '...","Everyone is welcome. Lincoln City Council, 7 p...",0.9,"(0.8, 1.0]"
8449,About town,None available.,SEPTEMBER ONE MARKET FUTURE PLANS: Wilfrid Lau...,Art galleries & museums; Visual artists; Food;...,"Expositor; Brantford, Ont.\n\nFirst page: A.9",2022,"Sep 29, 2022",Community News,Postmedia Network Inc.,"Brantford, Ont.",...,News,2719273833,https://www.proquest.com/globalnewsfed/newspap...,2022-09-30,165.0,1.0,"['church', 'pm', 'club', 'welcome', 'march', '...",Each walk will be restricted to a maximum of 2...,0.9,"(0.8, 1.0]"
9624,DOWNYOURWAY,None available.,"Baldhu chapel Café Church was all about Lent, ...",Communion; Hymns; Methodist churches; Religiou...,The West Briton; Truro (UK),2023,"Mar 2, 2023",News,MGN Ltd.,Truro (UK),...,News,2781103705,https://www.proquest.com/newspapers/downyourwa...,2023-03-02,165.0,1.0,"['church', 'pm', 'club', 'welcome', 'march', '...",Visitors welcome. Why not join us? Email helst...,0.9,"(0.8, 1.0]"
9778,Macleod Calendar,None available.,Doris Daley will read from her new book Lucky ...,Libraries\n\nIdentifier / keyword: doris; dale...,"The Macleod Gazette; Fort Macleod, Alta.\n\nFi...",2024,"Nov 20, 2024",News,Postmedia Network Inc.,"Fort Macleod, Alta.",...,News,3131991012,https://www.proquest.com/globalnewsfed/newspap...,2024-11-23,165.0,1.0,"['church', 'pm', 'club', 'welcome', 'march', '...",Walshe school Middle School Market from 9 a.m....,0.9,"(0.8, 1.0]"
10780,About Town,None available.,APRIL BOOK FAIR: Brantford Symphony Orchestra ...,Bands; Trees; Girls clubs; Musical theater; Me...,"Expositor; Brantford, Ont.\n\nFirst page: A.6",2025,"Apr 24, 2025",Local,Postmedia Network Inc.,"Brantford, Ont.",...,News,3194368129,https://www.proquest.com/globalnewsfed/newspap...,2025-04-25,165.0,1.0,"['church', 'pm', 'club', 'welcome', 'march', '...","Each week, Expositor readers can find out abou...",0.9,"(0.8, 1.0]"

***
Ad topic
***

In [83]:
df = remove_topic(df,165,[])

The orig length:10430 -> cropped: 10410

#### Topic 166

In [84]:
df[df['topic']==166]

,Title,Abstract,Full text,Subject,Publication title,Publication year,Publication date,Section,Publisher,Place of publication,...,Document type,ProQuest document ID,Document URL,Last updated,topic,topic_prob,topic_keywords,last,rel_ratio,rel_bins
303,Annual Healthy Aging Fair a big draw for senio...,"""It offers us a chance to get checkups we othe...",HAYWARD -- Lucille Jackson considers any free ...,NaN,"Oakland Tribune; Oakland, Calif.",2010,"Jul 24, 2010",My Town,Bay Area News Group,"Oakland, Calif.",...,News,658343381,https://www.proquest.com/globalnewsfed/newspap...,2011-08-24,166.0,1.0,"['fair', 'vancouver', 'summer', 'feb', 'shore'...","""Free food and free gifts,"" Brown said. ""You c...",0.85,"(0.8, 1.0]"
588,NEIGHBORS BRIEFS: [Free program for senior c...,None available.,The Wellness Initiative for Senior Education P...,NaN,"Daily Journal; Vineland, N.J.",2010,"Feb 10, 2010",LOCAL,Gannett Media Corp,"Vineland, N.J.",...,News,1075124962,https://www.proquest.com/globalnewsfed/newspap...,2017-11-19,166.0,1.0,"['fair', 'vancouver', 'summer', 'feb', 'shore'...",Pottery classes at Clay College Cumberland Cou...,0.85,"(0.8, 1.0]"
628,Notices,Vancouver Coastal Health will be holding a com...,"Healthy Aging: The North Shore Chapter, Osteop...",Aging; Libraries; Young adults,"North Shore News; North Vancouver, B.C.\n\nFir...",2010,"Jan 17, 2010\n\ncolumn: Health Notes",Life,Postmedia Network Inc.,"North Vancouver, B.C.",...,News,361584312,https://www.proquest.com/globalnewsfed/newspap...,2012-02-08,166.0,1.0,"['fair', 'vancouver', 'summer', 'feb', 'shore'...","Info and registration: Lou, 604-924-2424, www....",0.85,"(0.8, 1.0]"
752,American Cancer Society representatives to speak,Current committees are focused on child obesit...,The Madison Community Health Consortium (MCHC)...,Advisors; Cancer; Meetings; Medical research\n...,"Asheville Citizen - Times; Asheville, N.C.\n\n...",2011,"Nov 2, 2011",A,Gannett Media Corp,"Asheville, N.C.",...,News,1471231656,https://www.proquest.com/globalnewsfed/newspap...,2017-11-21,166.0,1.0,"['fair', 'vancouver', 'summer', 'feb', 'shore'...",Some who can't attend meetings have contribute...,0.85,"(0.8, 1.0]"
932,Council offers useful programs,"Topics include mental health and well-being, m...","Have you ever wanted to learn a new skill, bec...",Aging; Older people,"Saskatoon Sun; Saskatoon, Sask.\n\nFirst page: 18",2011,"Aug 28, 2011\n\ncolumn: Prime Of Life",News,Postmedia Network Inc.,"Saskatoon, Sask.",...,Column,894374275,https://www.proquest.com/globalnewsfed/newspap...,2012-05-15,166.0,1.0,"['fair', 'vancouver', 'summer', 'feb', 'shore'...",Our blood pressure clinic continues to run on ...,0.85,"(0.8, 1.0]"
963,Healthy Aging Fair moves to Chabot College,"Jennifer Wu, of Fremont, gives Javier Romero, ...",HAYWARD -- There were some adjustments made fo...,NaN,"Oakland Tribune; Oakland, Calif.",2011,"Aug 13, 2011",My Town,Bay Area News Group,"Oakland, Calif.",...,News,883217 478,https://www.proquest.com/globalnewsfed/newspap...,2011-08-16,166.0,1.0,"['fair', 'vancouver', 'summer', 'feb', 'shore'...",The health fair included free health screening...,0.85,"(0.8, 1.0]"
1708,HEALTHY-AGING FAIR AT CHABOT COLLEGE,None available.,HAYWARD -- A Healthy Aging Fair will be held A...,NaN,"San Jose Mercury News; San Jose, Calif.\n\nFir...",2012,"Jul 30, 2012",Local,Bay Area News Group,"San Jose, Calif.",...,News,1033331251,https://www.proquest.com/globalnewsfed/newspap...,2012-08-14,166.0,1.0,"['fair', 'vancouver', 'summer', 'feb', 'shore'...",The countywide event provides a nutritious lun...,0.85,"(0.8, 1.0]"
1726,Summer WHAM offers wellness tips for seniors,"""Our goal with Summer WHAM is to give seniors ...",Discover the extensive communities and service...,NaN,"The Review; Richmond, B.C.\n\nFirst page: 12",2012,"Jul 16, 2012",Community,"Torstar Syndication Services, a Division of To...","Richmond, B.C.",...,News,1026539078,https://www.proquest.com/globalnewsfed/newspap...,2012-07-17,166.0,1.0,"['fair', 'vancouver', 'summer', 'feb', 'shore'...",Admission is free. Guests can register by call...,0.85,"(0.8, 1.0]"
2058,Montgomery County,CENTERVILLE & DAYTON Agency on Aging offers He...,CENTERVILLE & DAYTON Agency on Aging offers He...,Corporate sponsorship; Workshops,"Dayton Daily News; Dayton, Ohio\n\nFirst page:...",2012,"Jan 26, 2012",Local,"Atlanta Journal Constitution, LLC","Dayton, Ohio",...,News,928063776,https://www.proquest.com/globalnewsfed/newspap...,2017-11-19,166.0,1.0,"['fair', 'vancouver', 'summer', 'feb', 'shore'...",Montgomery County dog licenses are $20 for dog...,0.85,"(0.8, 1.0]"
2243,Avoiding falls focus of advice,None available.,Seniors can get a flu shot and advice how to a...,Falls; Older people; Aging\n\nIdentifier / key...,The Beacon Herald; Stratford\n\nFirst page: A.4,2013,"Oct 23, 2013",News,Postmedia Network Inc.,Stratford,...,News,2211701729,https://www.proquest.com/globalnewsfed/newspap...,2019-04-21,166.0,1.0,"['fair', 'vancouver', 'summer', 'feb', 'shore'...","Partners include One Care, Wellness for Senior...",0.85,"(0.8, 1.0]"
3080,"Senior Fest returns with screenings, resources...",Basic metabolic panel and lipid profile to che...,"Senior Fest, the one-stop event for seniors th...",Cholesterol; Immunization,"Reno Gazette - Journal; Reno, Nev.\n\nFirst pa...",2014,"Sep 2, 2014",A,Gannett Media Corp,"Reno, Nev.",...,News,1558808451,https://www.proquest.com/newspapers/senior-fes...,2017-11-21,166.0,1.0,"['fair', 'vancouver', 'summer', 'feb', 'shore'...",Shingle vaccinations are available free for ag...,0.85,"(0.8, 1.0]"
3286,Health Notes,Registration required. 604-982-3320 karyn.davi...,WWAP (Women Who Aren't Parents) A group for wo...,Naturopathy,"North Shore News; North Vancouver, B.C.\n\nFir...",2014,"Apr 27, 2014",Live,Postmedia Network Inc.,"North Vancouver, B.C.",...,News,1519233147,https://www.proquest.com/newspapers/health-not...,2014-04-28,166.0,1.0,"['fair', 'vancouver', 'summer', 'feb', 'shore'...",Registration required. 604-982-3320 karyn.davi...,0.85,"(0.8, 1.0]"
3464,PoCo plans Healthy Living Fair Feb. 15,Information sessions at the fair include: 10:0...,Port Coquitlam residents are invited to explor...,Aging,"The Tri - Cities NOW; Port Moody, B.C.\n\nFirs...",2014,"Feb 7, 2014",Community & Life,Postmedia Network Inc.,"Port Moody, B.C.",...,News,1496255012,https://www.proquest.com/newspapers/poco-plans...,2014-02-09,166.0,1.0,"['fair', 'vancouver', 'summer', 'feb', 'shore'...",Healthy snacks and lunch will be available for...,0.85,"(0.8, 1.0]"
3483,In brief: Hospital explores the brain on music,None available.,"Holly Semrow, a board certified music therapis...",NaN,"Times Herald; Port Huron, Mich.\n\nFirst page:...",2014,"Jan 30, 2014\n\ncolumn: in Brief",A-Section,Gannett Media Corp,"Port Huron, Mich.",...,News,1492526394,https://www.proquest.com/newspapers/brief/docv...,2017-11-21,166.0,1.0,"['fair', 'vancouver', 'summer', 'feb', 'shore'...",Sen. Pavlov announces February office hours St...,0.85,"(0.8, 1.0]"
3500,Wellness Events,What: Make Your Coffee Count neighbourhood cof...,Alzheimer's disease What: Make Your Coffee Cou...,NaN,"The Spectator; Hamilton, Ont.\n\nFirst page: G.8",2014,"Feb 4, 2014",Go,"Torstar Syndication Services, a Division of To...","Hamilton, Ont.",...,News,1494048916,https://www.proquest.com/newspapers/wellness-e...,2017-11-21,166.0,1.0,"['fair', 'vancouver', 'summer', 'feb', 'shore'...",Contact: Supportive & Palliative Care Program ...,0.85,"(0.8, 1.0]"
4564,Hats offto popular seniors' garden party,Events and programs such as the Summer Garden ...,Pop on your finest topper to celebrate Hats Of...,Organic gardening; Gardens & gardening\n\nIden...,"Richmond News; Richmond, B.C.\n\nFirst page: A.17",2016,"Jul 27, 2016",News,Postmedia Network Inc.,"Richmond, B.C.",...,News\n\nProQuestdocument ID: 1807272905,NaN,https://www.proquest.com/globalnewsfed/newspap...,2016-07-28,166.0,1.0,"['fair', 'vancouver', 'summer', 'feb', 'shore'...","ca/Register, call 604-276-4300 or visit the Mi...",0.85,"(0.8, 1.0]"
4693,Library to host coloring event,"""Part of the effort is to eliminate the stigma...",FRANKLIN - Franklin Township Library will host...,Mental disorders; Libraries; Older people; Men...,"Daily Journal; Vineland, N.J.\n\nFirst page: A.10",2016,"May 23, 2016\n\ncolumn: Briefs",Features,Gannett Media Corp,"Vineland, N.J.",...,Feature,1790462495,https://www.proquest.com/globalnewsfed/newspap...,2017-11-22,166.0,1.0,"['fair', 'vancouver', 'summer', 'feb', 'shore'...",Newfield National Bank is the event sponsor. A...,0.85,"(0.8, 1.0]"
6137,Library hosts series on healthy aging in place,None available.,Vancouver Library hosts series on healthy agin...,Support groups; Libraries; Aging in place; Alt...,"Columbian; Vancouver, Wash.\n\nFirst page: D.3",2018,"Apr 16, 2018",Health local,Columbian Publishing Company,"Vancouver, Wash.",...,News,2027122184,https://www.proquest.com/globalnewsfed/newspap...,2021-10-15,166.0,1.0,"['fair', 'vancouver', 'summer', 'feb', 'shore'...","The organization offers weekend retreats, supp...",0.85,"(0.8, 1.0]"
6896,Senior Olympic torch stops in Mescalero,None available.,The Mescalero Apache Seniors participated in t...,Print advertising; Older people\n\nLocation: N...,"Ruidoso News; Ruidoso, N.M.\n\nFirst page: B.2",2019,"Mar 15, 2019",Business,Gannett Media Corp,"Ruidoso, N.M.",...,News,2191331485,https://www.proquest.com/globalnewsfed/newspap...,2019-03-15,166.0,1.0,"['fair', 'vancouver', 'summer', 'feb', 'shore'...",Pamela L. Bonner can be reached at 575-202-555...,0.85,"(0.8, 1.0]"
8025,May celebrates host of public health awareness...,None available.,When I was searching for a theme for the colum...,Cardiovascular disease; Blood pressure; Health...,"The Intelligencer; Belleville, Ont.\n\nFirst p...",2021,"May 12, 2021\n\ncolumn: Senior Scene",Local,Postmedia Network Inc.,"Belleville, Ont.",...,News,2525939272,https://www.proquest.com/newspapers/may-celebr...,2022-05-20,166.0,1.0,"['fair', 'vancouver', 'summer', 'feb', 'shore'...",Information in this column is compiled by Shel...,0.85,"(0.8, 1.0]"

In [85]:
df.loc[752,'Full text']

"The Madison Community Health Consortium (MCHC) quarterly meeting is scheduled for Wednesday Nov. 16 from noon to 1:30 p.m. at Cooperative Extension Auditorium, Marshall, NC. Noon to 12:30 p.m. is lunch and networking followed with the program & MCHC Committee Updates/Reports from 12:30 p.m. to 1:30 p.m. The program presentation will be from the American Cancer Society representatives about current programs, resources, and information about a newly funded cancer prevention initiative for Madison, Yancey, and Mitchell counties. Kathlene Stith, Community Health Advisor Manager, will provide information regarding the new program to help women access mammograms and other lifesaving screenings. The new Community Health Advisor (CHA) program will recruit and train women to educate and navigate their community members to screenings for breast, cervical and colorectal cancer. This program will start recruiting volunteers this November. Sarah Gayle, Community Manager, will share information about services and programs offered to Madison County residents by the American Cancer Society. Kevin Mills, Community Manager, is speaking about future planning for Relay for Life Madison County. The Madison Community Health Consortium is a partnership that seeks to improve the overall health of Madison County citizens by networking with community agencies and groups in the on-going process of needs assessment, project development, implementation and evaluation. MCHC provides a forum for citizens, community agencies, groups and businesses to identify health issues of Madison County and to seek solutions for those needs. The Madison Community Health Consortium welcomes volunteers who may have a special interest in the health needs of the community. Some MCHC participants contribute to collaborative decision making by attending regular MCHC meetings and/or serving on MCHC committees. Current committees are focused on child obesity prevention, promoting healthy lifestyles for adults age 55 and better through Active Aging Activities and coordinating Active Aging Week, Senior Health Fair & Madison County Senior Games and meetings are coordinated for Mental Health providers and agencies to share information, network among providers, identify service gaps and facilitate collaboration to address identified gaps. Some who can't attend meetings have contributed to special MCHC-sponsored events such as health fairs. Others' schedules prohibit participation but they like staying informed via MCHC minutes and help disseminate project information to their staff, clients or communities. All levels of involvement are valuable to the MCHC process and create a network for promoting health! Lunch is provided but you must RSVP your plans to attend by Monday Nov. 14 to: Jodi Brazil, Madison Community Health Consortium, 649-3531 ext.225 or jbrazil@ madisoncountync.org."

***
Ad topic about health events
***

In [86]:
df = remove_topic(df,166,[])

The orig length:10410 -> cropped: 10390

#### Topic 170

In [87]:
df[df['topic']==170]

,Title,Abstract,Full text,Subject,Publication title,Publication year,Publication date,Section,Publisher,Place of publication,...,Document type,ProQuest document ID,Document URL,Last updated,topic,topic_prob,topic_keywords,last,rel_ratio,rel_bins
88,ACTIVITIES FOR 50-PLUS,The Healthy Aging Clinic is offering a communi...,Wheels To Meals starting up again The Wheels t...,Citizenship; Education; Meals; Older people; A...,"Daily Gleaner; Fredericton, N.B.\n\nFirst page...",2010,"Sep 21, 2010",Features,Postmedia Network Inc.,"Fredericton, N.B.",...,News,751827934,https://www.proquest.com/globalnewsfed/newspap...,2010-09-21,170.0,0.188212,"['noon', 'pm', 'class', 'sisters', 'begins', '...",UNB College of Extended Learning has No Limits...,1.0,"(0.8, 1.0]"
463,Healthy Aging Jamboree to be held Sunday at VF...,None available.,"Saturday April 24, 2010 BRATTLEBORO -- Brattle...",NaN,"The Brattleboro Reformer; Brattleboro, Vt.",2010,"Apr 24, 2010",Lifestyle,"New England Newspapers, Inc.","Brattleboro, Vt.",...,News,380329760,https://www.proquest.com/globalnewsfed/newspap...,2011-10-27,170.0,1.000000,"['noon', 'pm', 'class', 'sisters', 'begins', '...",Admission will be $5 and there will be dancing...,1.0,"(0.8, 1.0]"
508,FAITH IN THE CITY. A rock of devotion for near...,". Size and character of congregation: ""Approxi...",". Religious affiliation: The Episcopal Church,...",NaN,"New York Daily News; New York, N.Y.\n\nFirst p...",2010,"Mar 21, 2010",SUBURBAN,"Tribune Publishing Company, LLC","New York, N.Y.",...,News,306349576,https://www.proquest.com/globalnewsfed/newspap...,2017-11-02,170.0,1.000000,"['noon', 'pm', 'class', 'sisters', 'begins', '...",. Contact: (718) 885-1080; www.gracecityisland...,1.0,"(0.8, 1.0]"
1212,Moncton Headstart to host fundraising breakfas...,"Sue Stultz, New Brunswick minister for social ...","Sue Stultz, New Brunswick minister for social ...",Aging; Fund raising,"The Times - Transcript; Moncton, N.B.\n\nFirst...",2011,"Apr 9, 2011",Main,Postmedia Network Inc.,"Moncton, N.B.",...,News,861066321,https://www.proquest.com/globalnewsfed/newspap...,2011-04-09,170.0,1.000000,"['noon', 'pm', 'class', 'sisters', 'begins', '...",The event will begin at 8 a.m. with cost of ad...,1.0,"(0.8, 1.0]"
1447,Sisters in service Our Lady of Mercy nuns agin...,"""I know that God gives life, so I don't think ...",The OLM convent on James Island has a new supe...,NaN,"The Post and Courier; Charleston, S.C.\n\nFirs...",2012,"Nov 18, 2012",Features,The Post and Courier,"Charleston, S.C.",...,News,1163168249,https://www.proquest.com/globalnewsfed/newspap...,2012-11-18,170.0,1.000000,"['noon', 'pm', 'class', 'sisters', 'begins', '...","""Service never ends,"" Ritter adds. ""But we all...",1.0,"(0.8, 1.0]"
1546,Flamborough Seniors: Get on the bus,Flamborough Information and Community Services...,"Shelley Scott, executive director, Flamborough...",NaN,"Flamborough Review; Waterdown, Ont.",2012,"Oct 3, 2012",NaN,"Torstar Syndication Services, a Division of To...","Waterdown, Ont.",...,News,1082280027,https://www.proquest.com/glo balnewsfed/newspa...,2012-10-04,170.0,0.154009,"['noon', 'pm', 'class', 'sisters', 'begins', '...",You must have a registration card to attend th...,1.0,"(0.8, 1.0]"
2482,Meet & greet,The retirement community initiative has identi...,Reception set for newcomers Newcomers to this ...,Prostate cancer; Men,"The Windsor Star; Windsor, Ont.\n\nFirst page:...",2013,"Jun 29, 2013",Special Section,Postmedia Network Inc.,"Windsor, Ont.",...,Column,1372405106,https://www.proquest.com/globalnewsfed/newspap...,2017-11-20,170.0,1.000000,"['noon', 'pm', 'class', 'sisters', 'begins', '...",Email twhipp@windsorstar. com or call 519-255-...,1.0,"(0.8, 1.0]"
3474,Our Community: Full circle for volunteer's wor...,Because she grew up with a sister with a disab...,A young woman who came to Canada from Haiti as...,Colleges & universities; Music; Families & fam...,"Times - Colonist; Victoria, B.C.\n\nFirst page...",2014,"Feb 2, 2 014",Islander,Postmedia Network Inc.,"Victoria, B.C.",...,Column,1493955790,https://www.proquest.com/newspapers/our-commun...,2017-11-21,170.0,0.124544,"['noon', 'pm', 'class', 'sisters', 'begins', '...","For more information, go to blood.ca or call 1...",1.0,"(0.8, 1.0]"
3968,Lake County in 60 seconds,The thrift stores of St. Vincent de Paul Chica...,CLC receives federal grant: College of Lake Co...,NaN,"Daily Herald; Arlington Heights, Ill.\n\nFirst...",2015,"Jul 31, 2015",NEWS,Daily Herald,"Arlington Heights, Ill.",...,News,1700408068,https://www.proquest.com/globalnewsfed/newspap...,2017-11-22,170.0,1.000000,"['noon', 'pm', 'class', 'sisters', 'begins', '...","The senior volunteer program is a ""placement s...",1.0,"(0.8, 1.0]"
4007,Hamilton resident steps up to help with earthq...,Potential areas include: allied health profess...,Elizabeth Tromans of Hamilton is with Catholic...,Earthquakes; Agreements; Medicine; Emergency p...,"Cincinnati Enquirer; Cincinnati, Ohio\n\nFirst...",2015,"May 16, 2015\n\ncolumn: area news",S,Gannett Media Corp,"Cincinnati, Ohio",...,News,1681099778,https://www.proquest.com/globalnewsfed/newspap...,2015-05-16,170.0,1.000000,"['noon', 'pm', 'class', 'sisters', 'begins', '...",Performances are held on the fourth Tuesday of...,1.0,"(0.8, 1.0]"
4727,West Ouachita Senior Center: Annual Older Am...,WOSC aging advocate Terry Bratton will be on h...,"During the month of May, West Ouachita Senior ...",Medicare; Senior citizen centers; Dance; Semin...,"News - Star; Monroe, La.\n\nFirst page: D.2",2016,"May 9, 2016\n\ncolumn: WOSC calendar",Features,Gannett Media Corp,"Monroe, La.",...,Feature,1787490244,https://www.proquest.com/globalnewsfed/newspap...,2017-11-23,170.0,1.000000,"['noon', 'pm', 'class', 'sisters', 'begins', '...",Basic Yoga with Vantage Wellness 11:30 a.m. to...,1.0,"(0.8, 1.0]"
6091,West Ouachita Senior Center: West Ouachita S...,None available.,"Save the date: 10 a.m. to 12:30 p.m., May 16, ...",Needlework; Dance; Aerobics; Yoga; Senior citi...,"News - Star; Monroe, La.\n\nFirst page: A.3",2018,"May 7, 2018\n\ncolumn: West Ouachita Senior Ce...",New s,Gannett Media Corp,"Monroe, La.",...,News,2035210608,https://www.proquest.com/globalnewsfed/newspap...,2018-05-07,170.0,1.000000,"['noon', 'pm', 'class', 'sisters', 'begins', '...",Friendly Crochet Group 8 a.m. to noon. Bingo 1...,1.0,"(0.8, 1.0]"
6112,West Ouachita Senior Center: New Bible Study...,None available.,Join Ouachita Parish seniors Brother Mike Thom...,Needlework; Dance; Ballroom dancing; Aerobics;...,"News - Star; Monroe, La.\n\nFirst page: A.5",2018,"Apr 30, 2018\n\ncolumn: West Ouachita Senior C...",News,Gannett Media Corp,"Monroe, La.",...,News,2032337956,https://www.proquest.com/globalnewsfed/newspap...,2018-04-30,170.0,1.000000,"['noon', 'pm', 'class', 'sisters', 'begins', '...",Friendly Crochet Group 8 a.m. to noon. Bingo 1...,1.0,"(0.8, 1.0]"
6168,West Ouachita Senior Center: USDA commoditie...,None available.,The bi-annual USDA commodities distribution da...,Needlework; Dance; Aerobics; Yoga; Senior citi...,"News - Star; Monroe, La.\n\nFirst page: A.5",2018,"Apr 2, 2018\n\ncolumn: West Ouachita Senior Ce...",News,Gannett Media Corp,"Monroe, La.",...,News,2020455672,https://www.proquest.com/globalnewsfed/newspap...,2018-04-02,170.0,1.000000,"['noon', 'pm', 'class', 'sisters', 'begins', '...",Friendly Crochet Group 8 a.m. to noon. Bingo 1...,1.0,"(0.8, 1.0]"
6179,West Ouachita Senior Center: USDA commodities,None available.,distribution on April 4 The bi-annual USDA com...,Needlework; Dance; Aerobics; Yoga; Senior citi...,"News - Star; Monroe, La.\n\nFirst page: A.5",2018,"Mar 26, 2018\n\ncolumn: West Ouachita Senior C...",News,Gannett Media Corp,"Monroe, La.",...,News,2017922 138,https://www.proquest.com/globalnewsfed/newspap...,2024-10-10,170.0,1.000000,"['noon', 'pm', 'class', 'sisters', 'begins', '...",Friendly Crochet Group 8 a.m. to noon. Bingo 1...,1.0,"(0.8, 1.0]"
6195,West Ouachita Senior Center: West Ouachita S...,None available.,annual spring luncheon slated Walmart Neighbor...,Needlework; Dance; Aerobics; Yoga; Senior citi...,"News - Star; Monroe, La.\n\nFirst page: A.7",2018,"Mar 19, 2018\n\ncolumn: West Ouachita Senior C...",News,Gannett Media Corp,"Monroe, La.",...,News,2014902982,https://www.proquest.com/globalnewsfed/newspap...,2024-10-10,170.0,1.000000,"['noon', 'pm', 'class', 'sisters', 'begins', '...",Friendly Crochet Group 8 a.m. to noon. Bingo 1...,1.0,"(0.8, 1.0]"
6713,Manitowoc seniors,None available.,"With summer here, it sure seems like life gets...",Generic drugs; Memory; Communication; Aging; D...,"Herald Times Reporter; Manitowoc, Wis.\n\nFirs...",2019,"Jun 23, 2019",News,Gannett Media Corp,"Manitowoc, Wis.",...,News,2245155567,https://www.proquest.com/globalnewsfed/newspap...,2023-10-09,170.0,0.160348,"['noon', 'pm', 'class', 'sisters', 'begins', '...",Meal delivery drivers deliver to our home-boun...,1.0,"(0.8, 1.0]"
10450,Northern Sunrise offering outings for seniors,None available.,(Peace River) - Northern Sunrise County Family...,Older people; Community support\n\nLocation: P...,"The South Peace News; High Prairie, Alta.\n\nF...",2025,"Aug 6, 2025\n\ncolumn: Local Journalism Initia...",News,Postmedia Network Inc.,"High Prairie, Alta.",...,News,3237103017,https://www.proquest.com/globalnewsfed/newspap...,2025-08-07,170.0,1.000000,"['noon', 'pm', 'class', 'sisters', 'begins', '...",Northern Sunrise County has received funding t...,1.0,"(0.8, 1.0]"
10612,Trip to local events free for area seniors,None available.,(Peace River) - Seniors interested in attendin...,Older people; Community support\n\nIdentifier ...,"The South Peace News; High Prairie, Alta.\n\nF...",2025,"Jun 11, 2025\n\ncolumn: Local Journalism Initi...",News,Postmedia Network Inc.,"High Prairie, Alta.",...,News,3217856475,https://www.proquest.com/globalnewsfed/newspap...,2025-06-12,170.0,1.000000,"['noon', 'pm', 'class', 'sisters', 'begins', '...",Please ensure to re- serve your seat at least ...,1.0,"(0.8, 1.0]"
10639,Fort Macleod's many ways to celebrate Seniors'...,None available.,GAZETTE EDITOR Fort Macleod is celebrating its...,Libraries; Aging\n\nIdentifier / keyword: gaze...,"The Macleod Gazette; Fort Macleod, Alta.\n\nFi...",2025,"Jun 4, 2025",News,Postmedia Network Inc.,"Fort Macleod, Alta.",...,News,3216206668,https://www.proquest.com/globalnewsfed/newspap...,2025-06-06,170.0,1.000000,"['noon', 'pm', 'class', 'sisters', 'begins', '...",People are invited to drop in and watch the vi...,1.0,"(0.8, 1.0]"

***
Health ad topic
***

In [88]:
df = remove_topic(df,170,[])

The orig length:10390 -> cropped: 10370

#### Topic 173

In [89]:
df[df['topic']==173]

,Title,Abstract,Full text,Subject,Publication title,Publication year,Publication date,Section,Publisher,Place of publication,...,Document type,ProQuest document ID,Document URL,Last updated,topic,topic_prob,topic_keywords,last,rel_ratio,rel_bins
393,Health notes,LAKE WALES - As part of its Live Well! Communi...,LWMC will offer free screenings LAKE WALES - A...,NaN,"The Ledger; Lakeland, Fla.",2010,"Jan 10, 2010",NaN,Halifax Media Group,"Lakeland, Fla.",...,News,1177834866,https://www.proquest.com/globalnewsfed/newspap...,2012-11-21,173.0,1.000000,"['medical center', 'support group', 'valley', ...","The cost is $40, which includes a pet first ai...",1.0,"(0.8, 1.0]"
582,GET INVOLVED,RESOURCES American Heart Association Web site:...,RESOURCES American Heart Association Web site:...,Diabetes; Hospitals; Womens health; Cardiovasc...,"Morning Call; Allentown, Pa.\n\nFirst page: SP.1",2010,"Feb 11, 2010",Heart Health,"Tribune Publishing Company, LLC","Allentown, Pa.",...,News,393365150,https://www.proquest.com/globalnewsfed/newspap...,2017-11-06,173.0,1.000000,"['medical center', 'support group', 'valley', ...",225. WEIGHT LOSS New You Weight Loss Program W...,1.0,"(0.8, 1.0]"
644,Radiologist joins Fallon Clinic,Dr. Sharon J. Kuong has joined Fallon Clinic's...,Dr. Sharon J. Kuong has joined Fallon Clinic's...,Gastrointestinal surgery; Cancer therapies; Ag...,"Telegram & Gazette; Worcester, Mass.\n\nFirst ...",2010,"Jan 7, 2010\n\ncolumn: MEDICAL MEMOS",HEALTH & SCIENCE,"GateHouse Media, Inc.","Worcester, Mass.",...,News,269057504,https://www.proquest.com/globalnewsfed/newspap...,2024-12-01,173.0,1.000000,"['medical center', 'support group', 'valley', ...","For more information, call (888) 663-3688, ext...",1.0,"(0.8, 1.0]"
1160,Free self-care course offered,URBANA - If you or somebody you know has heart...,URBANA - If you or somebody you know has heart...,NaN,"News Gazette; Champaign, Ill.\n\nFirst page: B.3",2011,"May 9, 2011",NaN,News Gazette,"Champaign, Ill.",...,News,869553264,https://www.proquest.com/globalne wsfed/newspa...,2016-08-21,173.0,0.104733,"['medical center', 'support group', 'valley', ...",Participants are asked to bring their medicati...,1.0,"(0.8, 1.0]"
1309,Heart Health Resources,"Heart-Pound ing stories of survival, recovery ...",This story appears in the Special Scetion: Hea...,Physical fitness; Families & family life; Hear...,"Morning Call; Allentown, Pa.\n\nFirst page: SP.1",2011,"Feb 13, 2011",Heart Health,"Tribune Publishing Company, LLC","Allentown, Pa.",...,News,851577019,https://www.proquest.com/globalnewsfed/newspap...,2017-11-17,173.0,1.000000,"['medical center', 'support group', 'valley', ...",* Clearing the Air: Smoking Cessation Support ...,1.0,"(0.8, 1.0]"
1368,THERE'S HELP FOR KEEPING NEW YEAR'S RESOLUTIONS,"A No, that causes withdrawal symptoms. You can...","The annual resolve to live better, healthier l...",NaN,"Daily Press; Newport News, Va.\n\nFirst page: A.6",2011,"Jan 7, 2011",Local,"Tribune Publishing Company, LLC","Newport News, Va.",...,News,822780769,https://www.proquest.com/globalnewsfed/newspap...,2017-11-17,173.0,1.000000,"['medical center', 'support group', 'valley', ...",... A two-minute walk every hour on the hour b...,1.0,"(0.8, 1.0]"
2283,"""Take Control of Your Health"" by Kimball Medic...",To help older adults and their caregivers mana...,Reader Submitted Center for Healthy Aging at K...,Aging; Hospitals; Chronic illnesses; Health fa...,"Asbury Park Press; Asbury Park, N.J.",2013,"Oct 7, 2013",Your News,Gannett Media Corp,"Asbury Park, N.J.",...,News,1467410993,https://www.proquest.com/globalnewsfed/newspap...,2017-11-21,173.0,1.000000,"['medical center', 'support group', 'valley', ...",In addition to offering a full range of innova...,1.0,"(0.8, 1.0]"
2298,Pittsfield: Chronic disease management program...,In partnership with Home Instead Senior Care a...,In partnership with Home Instead Senior Care a...,Older people; Aging,"The Berkshire Eagle; Pittsfield, Mass.",2013,"Sep 30, 2013",Local,"New England Newspapers, Inc.","Pittsfield, Mass.",...,News,1437677373,https://www.proquest.com/globalnewsfed/newspap...,2013-10-01,173.0,1.000000,"['medical center', 'support group', 'valley', ...","Workshop sessions begin Thursday, Oct. 10, fro...",1.0,"(0.8, 1.0]"
2326,Kimball Medical Center presents Healthy Aging ...,Guests will enjoy buffet-style food while boar...,Reader Submitted Ocean County has the highest ...,Aging; Hospitals; Emergency medical care; Heal...,"Asbury Park Press; Asbury Park, N.J.",2013,"Sep 16, 2013",Your News,Gannett Media Corp,"Asbury Park, N.J.",...,News,1467324092,https://www.proquest.com/globalnewsfed/newspap...,2017-11-20,173.0,1.000000,"['medical center', 'support group', 'valley', ...",In addition to offering a full range of innova...,1.0,"(0.8, 1.0]"
2336,'Dietary Supplements' Informational Breakfast,About Kimball Medical Center Kimball Medical C...,"Reader Submitted LAKEWOOD, N.J. Ocean County h...",Aging; Hospitals; Health facilities; Older peo...,"Asbury Park Press; Asbury Park, N.J.",2013,"Sep 13, 2013",Your News,Gannett Media Corp,"Asbury Park, N.J.",...,News,1467325825,https://www.proquest.com/globalnewsfed/newspap...,2017-11-20,173.0,1.000000,"['medical center', 'support group', 'valley', ...",In addition to offering a full range of innova...,1.0,"(0.8, 1.0]"
2346,Kimball Medical Center to host Healthy Aging I...,Hospital clinicians will provide a variety of ...,Sponsored Content Kimball Medical Center is ho...,Aging; Hospitals; Older people,"Asbury Park Press; Asbury Park, N.J.",2013,"Sep 7, 2013",Barnabas,Gannett Media Corp,"Asbury Park, N.J.",...,News,1430618472,https://www.proquest.com/globalnewsfed/newspap...,2017-11-20,173.0,0.152934,"['medical center', 'support group', 'valley', ...",Buffet-style food will be served. Please regis...,1.0,"(0.8, 1.0]"
2361,Health Calendar,None available.,T'AI CHI CHIH: 3:30 p.m. Aug. 28. Gagnon Cardi...,NaN,"Daily Record; Morristown, N.J.\n\nFirst page: 6",2013,"Aug 27, 2013",A,Gannett Media Corp,"Morristown, N.J.",...,News,1428049853,https://www.proquest.com/globalnewsfed/newspap...,2017-11-20,173.0,1.000000,"['medical center', 'support group', 'valley', ...","Ledgewood Baptist Church, 233 Main St., Ledgew...",1.0,"(0.8, 1.0]"
2611,Kimball Medical Center Celebrates A Century of...,Joining the celebration were Barry H. Ostrowsk...,"Reader Submitted On May 1st, Kimball Medical C...",Hospitals; Community support; Presidents\n\nCo...,"Asbury Park Press; Asbury Park, N.J.",2013,"May 2, 2013",Your News,Gannett Media Corp,"Asbury Park, N.J.",...,News,1365670717,https://www.proquest.com/globalnewsfed/newspap...,2017-11-20,173.0,1.000000,"['medical center', 'support group', 'valley', ...",This relationship brought about collaborations...,1.0,"(0.8, 1.0]"
2657,Great Barrington: Info sessions planned for he...,"Information: Maria Connors, Healthy Aging prog...","Thursday April 4, 2013 Elder Services of Berks...",Aging; Older people,"The Berkshire Eagle; Pittsfield, Mass.",2013,"Apr 4, 2013",Local,"New England Newspapers, Inc.","Pittsfield, Mass.",...,News,1323687674,https://www.proquest.com/globalnewsfed/newspap...,2013-04-05,173.0,1.000000,"['medical center', 'support group', 'valley', ...","Session 1 of My Life, My Health will be held f...",1.0,"(0.8, 1.0]"
2761,Heart health programs and resources,RESOURCES American Heart Association Website: ...,RESOURCES American Heart Association Website: ...,Support groups; Hospitals; Womens health; Card...,"Morning Call; Allentown, Pa.\n\nFirst page: SP.2",2013,"Feb 10, 2013",Heart Health,"Tribune Publishing Company, LLC","Allentown, Pa.",...,News,1285590805,https://www.proquest.com/globalnewsfed/newspap...,2017-11-19,173.0,1.000000,"['medical center', 'support group', 'valley', ...","Check-in is 1 p.m. Where: Holiday Inn, Ninth a...",1.0,"(0.8, 1.0]"
3026,health calendar,"""Steps to Healthy Aging"" Clinics A registered ...","Tue. ""Steps to Healthy Aging"" Clinics A regist...",Hospitals; Gastrointestinal surgery; Blood pre...,"The News Journal; Wilmington, Del.\n\nFirst pa...",2014,"Sep 23, 2014",D,Gannett Media Corp,"Wilmington, Del.",...,News,1564206622,https://www.proquest.com/newspapers/health-cal...,2014-09-23,173.0,1.000000,"['medical center', 'support group', 'valley', ...",Includes a tour of the nursing unit and inpati...,1.0,"(0.8, 1.0]"
3194,Health and wellness events: Support groups and...,Compiled by Dora Robles Hernandez 4th Annual H...,MODAY Family Caregiver Support Group: For fami...,Hospitals; Support groups; Heart; Veins & arte...,"Detroit Free Press; Detroit, Mich.\n\nFirst pa...",2014,"Jun 15, 2014\n\ncolumn: Spotlight on health",Life And Ent ertainment,Gannett Media Corp,"Detroit, Mich.",...,News,1536069314,https://www.proquest.com/newspapers/health-wel...,2017-11-21,173.0,1.000000,"['medical center', 'support group', 'valley', ...",The event is free and runs 8 a.m.-2 p.m. at St...,1.0,"(0.8, 1.0]"
3343,Kimball Medical Center Holds Prescription Medi...,About Kimball Medical Center Kimball Medical C...,Reader Submitted Prescription drug-related dea...,Hospitals; Health facilities\n\nCompany / orga...,"Asbury Park Press; Asbury Park, N.J.",2014,"Apr 4, 2014",Your News,Gannett Media Corp,"Asbury Park, N.J.",...,News,1512701870,https://www.proquest.com/newspapers/kimball-me...,2017-11-21,173.0,1.000000,"['medical center', 'support group', 'valley', ...",In addition to offering a full range of innova...,1.0,"(0.8, 1.0]"
4502,in brief: Free blood pressure checks offered,None available.,Bayhealth offers free blood pressure clinics e...,NaN,"Daily Times; Salisbury, Md.\n\nFirst page: T.55",2016,"Sep 4, 2016",Features,Gannett Media Corp,"Salisbury, Md.",...,Feature,1816474975,https://www.proquest.com/globalnewsfed/newspap...,2017-11-23,173.0,1.000000,"['medical center', 'support group', 'valley', ...","For additional information, call 302-629-6224....",1.0,"(0.8, 1.0]"

In [90]:
df.loc[644,'Full text']

"Dr. Sharon J. Kuong has joined Fallon Clinic's Radiology Department at the Gold Star Boulevard practice in Worcester. She received her medical degree from Tufts University School of Medicine in Boston. Dr. Kuong completed her residency program at both Boston Medical Center and Santa Clara Valley Medical Center in San Jose, Calif., and completed a fellowship program in body imaging (CT, MRI Ultrasound) at Tufts Medical Center, as well as a musculoskeletal fellowship program at the University of Washington Medical Center in Seattle, Wash. Dr. Kuong is certified by the American Board of Radiology. The Putnam Lions Club recently awarded Day Kimball Healthcare pediatrician Marc Cerrone its Humanitarian of the Year award, in recognition of his recent activities serving the health needs of children and families in impoverished areas of the world, along with his significant involvement in this community. Look Good ... Feel Better, a free American Cancer Society program that teaches cancer patients hands-on cosmetics techniques to help them cope with appearance-related side effects from chemotherapy and radiation treatments, will be held from 2 to 4 p.m. Jan. 11 at the Levine Cancer Center at UMass Memorial Medical Center - Memorial Campus, 119 Belmont St., Worcester. To register, call (508) 270-4646. The Central Mass. Limb Loss Support Group will meet from 6 to 8 p.m. Jan. 12 at Clinton Hospital, 210 Highland St., Clinton. For more information, call (978) 365-2580. The Sutton Board of Health will hold an H1N1 (swine flu) vaccination clinic for Sutton residents ages 2 and older, from 9 a.m. to 1 p.m. Jan. 9 at Sutton Middle School, 383 Boston Road, Sutton. For more information, call (508) 865-8724. Fallon Clinic is hosting a free introductory meeting for people to learn about the bariatric surgery program at Fallon Clinic. Patients can meet the bariatric medicine team, which consists of surgeons, psychologists, dieticians, physicians, a physical therapy coordinator and case manager. The meeting will be held from 6 to 7:30 p.m. Jan. 14 in the fifth-floor North Conference Room at St. Vincent Hospital, 123 Summer St., Worcester. For more information, call (508) 368-3190 or (508) 852-6175. The Boylston Board of Health will hold an H1N1 (swine flu) vaccination clinic for Boylston residents from 9:30 a.m. to 12:30 p.m. Jan. 9 at Tahanto Regional High School, 1001 Main St., Boylston. For more information visit www.boylston-ma.gov or call (508) 869-6828. Fallon Community Health Plan will offer a free Quit to Win smoking cessation program at Clinton Hospital, 201 Highland St., Clinton. It begins Jan. 11. To register, call (888) 807-2908. Tufts Health Plan Foundation has awarded more than $1 million in grants to nonprofit organizations in Massachusetts, bringing the total amount awarded in 2009 to $2 million. Among the recipients is Great Brook Valley Health Center in Worcester, which received approximately $66,000. The money will be used to provide chronic disease management for low-income, minority older adults in the Worcester area, many of whom are current patients at the Great Brook Valley Health Center. By working with clinicians, case managers and social workers, patient navigators will assist patients in overcoming language/culture barriers and in accessing adjunct services to meet socioeconomic needs that can exacerbate chronic disease and interfere with adherence to treatment. Nutritionist services also will be provided by licensed nutritionists who are also certified diabetes educators. The Tufts Health Plan Foundation launched its Healthy Aging program in 2009. Through grants in the three areas of vibrant lifestyles, intergenerational collaboration and keeping our seniors safe, the foundation seeks to fund programs that will elevate the physical, mental, and emotional well-being of older adults; enable them to contribute their experiences and knowledge to their communities; and ultimately help older adults live longer, healthier lives. American Red Cross blood drives will be held from 2 to 7 p.m. today at St. Anne's Church, 75 King St., Littleton; 1 to 6 p.m. tomorrow at the Eastwood Club, 389 Townsend St., Fitchburg; 2 to 7 p.m. tomorrow at the Senior Center, 40 Brimfield Road, Holland; 3 to 8 p.m. tomorrow at the Paxton Center School, 19 West St., Paxton; 2 to 7 p.m. Jan. 11 at the American Legion, 450 South Barre Road, Barre; 2 to 7 p.m. Jan. 11 at Sacred Heart Church, 187 Hopedale St., Hopedale; 1 to 7 p.m. Jan. 12 at the Lodge of Elks, 134 North Main St., Leominster; 9 a.m. to 2 p.m. Jan. 13 at the Town Hall, 584 Main St., Athol. Donors will receive a coupon for a free pound of Dunkin' Donuts coffee. To schedule an appointment, call (800) 448-3543 or visit www.givelife.org. The VNA Care Network offers free keep-well clinics for people 60 and older, from 9 to 11 a.m. today at Our Lady of Mount Carmel Parish Center, 28 Mulberry St., Worcester; noon to 2 p.m. today at Canterbury Towers, 6 Wachusett St., Worcester; 11 a.m. to 1 p.m. Jan. 12 at the Council on Aging, 40 Wall St., Spencer; 1 to 2 p.m. Jan. 12 at the Colonial Apartments, 26 Village Drive, Northboro. For more information, call (888) 663-3688, ext. 5603, or visit www.vnacarenetwork.org. Send information for Medical Memos to submissions@telegram.com. Illustration PHOTOS; Caption: (1) Dr. Kuong (2) Dr. Cerrone"

***
Ad topic
***

In [91]:
df = remove_topic(df,173,[])

The orig length:10370 -> cropped: 10351

#### Topic 197

In [92]:
df[df['topic']==197]

,Title,Abstract,Full text,Subject,Publication title,Publication year,Publication date,Section,Publisher,Place of publication,...,Document type,ProQuest document ID,Document URL,Last updated,topic,topic_prob,topic_keywords,last,rel_ratio,rel_bins
399,City Sidelines - May 27,Studio Babette Puppet Theatre presents Little ...,THURSDAY TOASTMASTERS Valley Town Toastmasters...,NaN,"Ancaster News; Ancaster, Ont.\n\nFirst page: 1",2010,"May 27, 2010",News,"Torstar Syndication Services, a Division of To...","Ancaster, Ont.",...,News,34 7095417,https://www.proquest.com/globalnewsfed/newspap...,2011-11-02,197.0,1.0,"['december', 'pm', 'church', 'st', 'memorial',...","Meetings are held Wednesday nights, 7:30 p. m....",1.0,"(0.8, 1.0]"
599,Little Black Dress travels to The Oaks,Eye on the prize Congratulations go to interna...,The Oaks Club recently welcomed Saks Fifth Ave...,Visual artists\n\nCompany / organization: Name...,"Sarasota Herald Tribune; Sarasota, Fla.\n\nFir...",2010,"Feb 2, 2010",B,Halifax Media Group,"Sarasota, Fla.",...,News,270870860,https://www.proquest.com/globalnewsfed/newspap...,2017-11-03,197.0,1.0,"['december', 'pm', 'church', 'st', 'memorial',...",For more information on the Hermitage Artist R...,1.0,"(0.8, 1.0]"
810,Community events,To list an event hosted or sponsored by a non-...,To list an event hosted or sponsored by a non-...,Aging; Garage sales,"Abbotsford Times; Abbotsford, B.C.\n\nFirst pa...",2011,"Oct 13, 2011",News,Postmedia Network Inc.,"Abbotsford, B.C.",...,News,898448300,https:// www.proquest.com/globalnewsfed/newspa...,2012-01-27,197.0,1.0,"['december', 'pm', 'church', 'st', 'memorial',...",Come and join a free breastfeeding class at Ab...,1.0,"(0.8, 1.0]"
1237,Vermilion libraries to kick off Money Smart We...,The nine public libraries in Vermilion County ...,The nine public libraries in Vermilion County ...,NaN,"News Gazette; Champaign, Ill.\n\nFirst page: B.3",2011,"Mar 25, 2011",NaN,News Gazette,"Champaign, Ill.",...,News,862906803,https: //www.proquest.com/globalnewsfed/newspa...,2016-08-21,197.0,1.0,"['december', 'pm', 'church', 'st', 'memorial',...","April 7: - 1 to 2 p.m. Fraud, Scam and Burglar...",1.0,"(0.8, 1.0]"
1601,Apple baking contest set for this weekend...[D...,"At 12:30 p.m., Billy Williams will auction off...",owen Apple baking contest set for this weekend...,Aging; Middle schools,"The Herald - Times; Bloomington, Ind.\n\nFirst...",2012,"Sep 14, 2012",NaN,"GateHouse Media, Inc.","Bloomington, Ind.",...,News,1039 316300,https://www.proquest.com/globalnewsfed/newspap...,2012-09-14,197.0,1.0,"['december', 'pm', 'church', 'st', 'memorial',...",Anyone with questions may call 330-7763. Monro...,1.0,"(0.8, 1.0]"
1803,COMMUNITY CALENDAR: THE WEEK OF JUNE 3,None available.,SUNDAY Port Jefferson Farmers market Local pro...,NaN,"Newsday, Combined editions; Long Island, N.Y.\...",2012,"Jun 3, 2012",EXPLORE LI,Newsday LLC,"Long Island, N.Y.",...,News,1018198857,https: //www.proquest.com/globalnewsfed/newspa...,2017-11-19,197.0,1.0,"['december', 'pm', 'church', 'st', 'memorial',...","WHEN|WHERE 10 a.m.-3 p.m., Trinity Evangelical...",1.0,"(0.8, 1.0]"
2051,What's On,"DECEMBER 1 ""Jake's Puzzle"" sponsoring a Tea fo...",MUSIC DECEMBER 1 & 2 A service of Carols and R...,Anglican churches; Christmas; Music,"Record; Sherbrooke, Que.\n\nFirst page: 12",2012,"Nov 30, 2012",Talk Of The Townships,Postmedia Network Inc.,"Sherbrooke, Que.",...,News,1221085218,https://www.proquest.com/globalnewsfed/newspap...,2012-12-03,197.0,1.0,"['december', 'pm', 'church', 'st', 'memorial',...",EXHIBITS UNTIL DECEMBER 16 Uplands is pleased ...,1.0,"(0.8, 1.0]"
2112,Guthrie Library Notes: Space needed for book sale,"""Digger Dozer Dumper,"" by Hope Vestergaard; ""D...",Many of us approach the New Year with a list o...,NaN,"The Evening Sun; Hanover, Pa.",2013,"Dec 31, 2013",Lifestyle,Gannett Media Corp,"Hanover, Pa.",...,News,1472538320,https://www.proquest.com/globalnewsfed/newspap...,2016-12-10,197.0,1.0,"['december', 'pm', 'church', 'st', 'memorial',...","(Perpetual Memorial - Eugene M. Haas) ""Rick St...",1.0,"(0.8, 1.0]"
2379,Briefs: Family fun at V'land church,None available.,"South Vineland United Methodist Church, Main R...",NaN,"Daily Journal; Vineland, N.J.\n\nFirst page: 6",2013,"Aug 24, 2013\n\ncolumn: Briefs",B,Gannett Media Corp,"Vineland, N.J.",...,News,1427453755,https://www.proquest.com/globalnewsfed/newspap...,2017-11-20,197.0,1.0,"['december', 'pm', 'church', 'st', 'memorial',...","Who's the child?,"" at 1 p.m. Aug. 27 at the Ga...",1.0,"(0.8, 1.0]"
2406,Business in Brief,None available.,Pittsfield: Annual HillcrestFest set for Sept....,NaN,"The Berkshire Eagle; Pittsfield, Mass.",2013,"Aug 7, 2013",Business,"New England Newspapers, Inc.","Pittsfield, Mass.",...,News,1418436118,https://www.proquest.com/globalnewsfed/newspap...,2013-08-08,197.0,1.0,"['december', 'pm', 'church', 'st', 'memorial',...",To see the complete Healthgrades 2013 Bariatri...,1.0,"(0.8, 1.0]"
2801,Community events,"All Star Wrestling Jan. 25, All Star Wrestling...",To list an event hosted or sponsored by a non-...,Aging; Wrestling; Libraries; Literacy; Cancer\...,"Abbotsford Times; Abbotsford, B.C.\n\nFirst pa...",2013,"Jan 24, 2013",News,Postmedia Network Inc.,"Abbotsford, B.C.",...,News,1280985919,https://www.proquest.com/globalnewsfed/newspap...,2013-01-26,197.0,1.0,"['december', 'pm', 'church', 'st', 'memorial',...",Contact Queen Norma at 604-864-2916 for all th...,1.0,"(0.8, 1.0]"
3082,Fitchburg Senior Center Calendar,"4 p.m.: ""Play and Stay"" -- Prepared and served...",Thursdays 10:30 a.m.-noon: New! Creative Thurs...,NaN,"Sentinel & Enterprise; Fitchburg, Mass.",2014,"May 8, 2014",Community,The Lowell Sun,"Fitchburg, Mass.",...,News,1522193455,https://www.proquest.com/newspapers/fitchburg-...,2014-05-28,197.0,1.0,"['december', 'pm', 'church', 'st', 'memorial',...",Must sign up in the office by May 23. Watch fo...,1.0,"(0.8, 1.0]"
3221,Juniper Village plans June events,"Thursday at 4 p.m. -- Magdalene Zeppos, attorn...","Juniper Village at Lebanon, 1125 Birch Road, S...",NaN,"The Daily News; Lebanon, Pa.",2014,"Jun 1, 2014",Valley Life,Gannett Media Corp,"Lebanon, Pa.",...,News,1530871811,https://www.proquest.com/newspapers/juniper-vi...,2016-12-10,197.0,1.0,"['december', 'pm', 'church', 'st', 'memorial',...","June 25, 4:30 p.m. -- Juice-bar Happy Hour. Il...",1.0,"(0.8, 1.0]"
3937,SLICE OF LIFE: June 20 to 26,Abbotsford Association for Healthy Aging holds...,This is a list of just some of the activities ...,NaN,"The News; Abbotsford, B.C.",2015,"Jun 19, 2015",Community,Black Press Group Ltd.,"Abbotsford, B.C.",...,News,1689986152,https://www.proquest.com/globalnewsfed/newspap...,2015-06-20,197.0,1.0,"['december', 'pm', 'church', 'st', 'memorial',...",Cost is $2. Sessions are Tuesdays at 6:45 p.m....,1.0,"(0.8, 1.0]"
4517,REGIONAL EVENTS,None available.,"MILFORD, Iowa: Camp Okoboji invites you to an ...",Lutheran churches; Christianity; Aging; God; B...,"Argus Leader; Sioux Falls, S.D.\n\nFirst page:...",2016,"Aug 27, 2016\n\ncolumn: religous events",News,Gannett Media Corp,"Sioux Falls, S.D.",...,News,2191667889,https://www.proquest.com/globalnewsfed/newspap...,2019-03-16,197.0,1.0,"['december', 'pm', 'church', 'st', 'memorial',...","Sioux Falls Healing Rooms, Suite 45, Western M...",1.0,"(0.8, 1.0]"
5559,Library looking for Summer Reading programmer,None available.,Only four days until Get Reel is back in High ...,Libraries\n\nLocation: Canada\n\nCompany / org...,The High River Times; High River\n\nFirst page...,2017,"Feb 21, 2017",News,Postmedia Network Inc.,High River,...,News,2168282317,https://www.proquest.com/globalnewsfed/newspap...,2022-01-21,197.0,1.0,"['december', 'pm', 'church', 'st', 'memorial',...",Space is limited so reserve your spot. Any que...,1.0,"(0.8, 1.0]"
5591,check it out,"Learn about polar bears, glacial melting, habi...",Wednesdays and Mondays Faith Tabernacle Outrea...,Medicare; Blood & organ donations; Aging; Regi...,"Green Bay Press Gazette; Green Bay, Wis.\n\nFi...",2017,"Jan 18, 2017",News,Gannett Media Corp,"Green Bay, Wis.",...,News,1859463662,https://www.proquest.com/globalnewsfed/newspap...,2017-11-23,197.0,1.0,"['december', 'pm', 'church', 'st', 'memorial',...","Registration appreciated. (800) 272-3900, alz....",1.0,"(0.8, 1.0]"

In [93]:
df.loc[5591,'Full text']

'Wednesdays and Mondays Faith Tabernacle Outreach Ministries Food Pantry: 11 am.-1 p.m., Faith Tabernacle lower level, 436 S. Jefferson St., Green Bay. Jan. 18 Home School Workshop: The Arctic: 9:30 a.m.-noon for grades 3-5, and 1-3:30 p.m. for grades 6-8, The NEW Zoo, Suamico. Drop-off program where students get hands-on learning opportunities. Learn about polar bears, glacial melting, habitat loss, predators and endangered species. Students should dress in layers and be ready for indoor and outdoor activities. $12 Zoo Pass members, $15 nonmembers. Reservations required. Visit newzoo.org. Peek at the Past: 12:30 p.m. at Aging & Disability Resource Center of Brown County, 300 S. Adams St., Green Bay. History of the national parks. ronaldpoister@new.rr.com. Overeaters Anonymous: 7 p.m., The Bridge, 2514 Jenny Lane, Green Bay. www.oa.org. Jan. 18-21 Blood Drives: 1-6 p.m. Jan. 19; 8 a.m.-noon Jan. 21, Green Bay Blood Donation Center, 2131 Deckner Ave., Green Bay. Noon-4 p.m. Jan. 18, Rasmussen College, 904 S. Taylor St., Suite 100, Green Bay. 11:30 a.m.-5:30 p.m. Jan. 18, American Legion Hall, 135 N. St. Augustine St., Pulaski. 7:30 a.m.-12:30 p.m. Jan. 20, Ramada Plaza Hotel, 2750 Ramada Way, Ashwaubenon. For an appointment, visit redcrossblood.org or call 1 (800) 733-2767. Jan. 19 Alzheimer\'s Association Family Education Programs: Know the 10 Signs: Early Detection Matters: 6-7:30 p.m., Suamico Municipal Center, 12781 Velp Ave., Suamico. Free. Registration appreciated. (800) 272-3900, alz.org/gwwi. Jan. 19 Medicare Part D Planfinder: 10-11:30 a.m.; Aging & Disability Resource Center of Brown County, 300 S. Adams St., Green Bay. How to navigate your online medicare drug options. Registration requested, (920) 448-4300. Thursdays and Mondays Green Bay Gamblers Anonymous: 7 p.m. at The Bridge, 2514 Jenny Lane, Green Bay. Twelve-step program effective for anyone who is willing to accept help. If you or someone you know has a gambling problem, come to a meeting or call (920) 465-6878. Jan. 20 Jim Lenz The Science & Magic Guy: 1-2 p.m., Aging & Disability Center of Brown County, 300 S. Adams St., Green Bay. Learn the art and science of panning for gold. $6 per person. (920) 448-4300. Friday Matinee: 9:30 a.m., De Pere Community Center, 600 Grant St., De Pere. Free movie, 50-cent popcorn. Call for name of movie, (920) 339-4097. ReStore Volunteer Information session: 10-11 a.m., Greater Green Bay Habitat for Humanity ReStore, 2965 Ramada Way, Ashwaubenon. Learn about volunteering for ReStore, the history and mission of Habitat and ReStore, and orientation to the ReStore. Participants encouraged to volunteer, but it is not required. For information about other orientation sessions, visit giveffect.com/campaigns/2755-restore-volunteer-information-orientation-sessions. To register, call Chiara Boss (920) 338-1650 or email volunteer@restoregb.org. Flatfoot 56 and October Bird of Death: 7:30-10 p.m., Cup O\' Joy, 232 S. Broadway, Green Bay. New CD from FlatFoot56. Doors open 7 p.m. Donation. Get an early-bird pass for meet and greet with the artists, 6:30-7 p.m. (920) 435-3269, cupojoy.com. Preserving the Past for Future Generations-Introduction to Genealogy: 1-2 p.m. presentation, 2-3 p.m. open lab, Aging & Disability Center of Brown County, 300 S. Adams St., Green Bay. Presenter: Susan Hopf Lemerond, founder of HistARTory. No. fee. Register, (920) 448-4300. Jan. 21 New Leaf Winter Farmers Market: 8 a.m.-2 p.m., KI Convention Center, Exhibit Hall C, 333 Main St., Green Bay. Live music, cooking demos and more than 120 vendors. Music by Michael Gillespie. Free admission. Jan. 22 Obsessive Compulsive Anonymous: 2 p.m., The Bridge, 2514 Jenny Lane, Green Bay. The Twelve Steps of Alcoholics Anonymous can help those with OCD. (920) 265-0877, obsessivecompulsiveanonymous.org. Jan. 23 Recovery Intl. Support Group: 7:30 p.m., First United Church of Christ, 509 S. Webster Ave., Green Bay. Self-help support for people with anxiety, panic, depression, and other emotional problems. Walk in, or call Clara, (920) 336-6432, or visit us on the web LowSelfHelpSystems.org. Moments to Remember Caregiver Support Group: 4:30-5:45, McCormick Assisted Living, 212 Iroquois Ave., Allouez. Guest Speaker: Vicki Johnson, community outreach specialist at the Alzheimer\'s Association Greater Wisconsin Chapter, speaks: "Planning for the Future: A Checklist for Putting My Affairs in Order: What My Loved Ones Should Know." Call (920) 437-0883 with questions. No charge, no registration required. Jan. 24 Computer classes: 2:30-4:30 p.m., Aging & Disability Resource Center of Brown County, 300 S. Adams St., Green Bay. Bring your own ideas. Call for reservations, (920) 448-4300. Jan. 25 Alzheimer\'s Association Family Education Programs: Dementia conversations: 5:30-7 p.m., New Perspective Senior Living, 2790 Elm Tree Hill, Green Bay. Free. Registration appreciated. (800) 272-3900, alz.org/gwwi. Medicare Part D counseling services: Aging & Disability Center of Brown County, 300 S. Adams St., Green Bay. Appointments required, (920) 448-4300. An Evening to Learn & Connect: 5:45-7:15, Aspiro, 167 Dousman St., Green Bay. Dr. Tracy Sherman discusses the risk of developing Alzheimer\'s when you have Down syndrome. Dementia friendly coalition\'s down syndrome and Alzheimer\'s committee. Registration required. Linda Blohowiak, (920) 593-4308. Jan. 26 Alzheimer\'s Association Family Education Programs: Healthy Living for Your Brain & Body: Tips from the Latest Research: 12:30-2 p.m., Aging & Disability Resource Center, 300 S. Adams St., Green Bay. Participants learn about diet, exercise, cognitive activity, social engagement and how to create a plan for healthy aging. Free. Registration appreciated. (800) 272-3900, alz.org/gwwi. Submit events online: http://events.greenbaypress gazette.com/, or email localnews@greenbaypress gazette.com. For information call (920) 431-8321.'

***
Ad topic
***

In [94]:
df = remove_topic(df,197,[])

The orig length:10351 -> cropped: 10334

#### Topic 202

In [95]:
df[df['topic']==202]

,Title,Abstract,Full text,Subject,Publication title,Publication year,Publication date,Section,Publisher,Place of publication,...,Document type,ProQuest document ID,Document URL,Last updated,topic,topic_prob,topic_keywords,last,rel_ratio,rel_bins
182,Manitoba Movers,has been appointed clinical consultant pharmac...,PEOPLE Guy Robbins and Lorrie Koroscil have be...,NaN,"Winnipeg Free Press; Winnipeg, Man.\n\nFirst p...",2010,"Sep 27, 2010",Business,FP Canadian Newspapers Limited Partnership,"Winnipeg, Man.",...,News,754971632,https://www.proquest.com/globalnewsfed/newspap...,2017-11-17,202.0,1.000000,"['grant', 'grants', 'received', 'diversity', '...",Dan Ryall of Fillmore Riley LLP has been appoi...,0.9375,"(0.8, 1.0]"
191,UCR may house healthy aging center,"White and G. Richard Olds, M.D., vice chancell...",The Desert Sun Palm Desert could be home to a ...,Physicians; Councils; Primary care\n\nLocation...,"The Desert Sun; Palm Springs, Calif.",2010,"Sep 24, 2010",VALLEY,Gannett Media Corp,"Palm Springs, Calif.",...,News,754125774,https://www.proquest.com/globalnewsfed/newspap...,2017-11-17,202.0,0.147776,"['grant', 'grants', 'received', 'diversity', '...",He told the council the university also aims t...,0.9375,"(0.8, 1.0]"
849,HUNTER COLLEGE'S SCHOOL MOVES INTO EAST HARLEM,"""Hunter is committed to this neighborhood. The...",HUNTER College's venerated School of Social Wo...,NaN,"New York Daily News; New York, N.Y.\n\nFirst p...",2011,"Sep 29, 2011",UPTOWN NEWS,"Tribune Publishing Company, LLC","New York, N.Y.",...,Ne ws,894757888,https://www.proquest.com/globalnewsfed/newspap...,2017-11-18,202.0,1.000000,"['grant', 'grants', 'received', 'diversity', '...",Beshai is helping bakery trainees navigate the...,0.9375,"(0.8, 1.0]"
1355,"Future medical school taps valley physician, c...",The Desert Sun Coachella Valley physician and ...,The Desert Sun Coachella Valley physician and ...,Hospitals; Physicians\n\nLocation: Coachella V...,"The Desert Sun; Palm Springs, Calif.",2011,"Jan 13, 2011",VALLEY,Gannett Media Corp,"Palm Springs, Calif.",...,News,838205571,https://www.proquest.com/globalnewsfed/newspap...,2017-11-17,202.0,1.000000,"['grant', 'grants', 'received', 'diversity', '...","UCR will pay Ruiz $65,000 annually for the par...",0.9375,"(0.8, 1.0]"
1668,Sac Town Native Comes to Los Angeles,From first hand experiences of cultural barrie...,Headnote to Continue Progressing Diversity in ...,Health care; Medical personnel; Workplace dive...,"Los Angeles Sentinel; Los Angeles, Calif.\n\nV...",2012,"Aug 16-Aug 22, 2012",FAMILY,Los Angeles Sentinel,"Los Angeles, Calif.",...,News,1039271637,https://www.proquest.com/globalnewsfed/newspap...,2017-04-15,202.0,1.000000,"['grant', 'grants', 'received', 'diversity', '...",The Foundation prioritizes eight issues for fu...,0.9375,"(0.8, 1.0]"
1733,TCWF Recognizes Angela Minniefield for Commitm...,"Since its founding in 1992, TCWF has awarded 6...",Headnote Angela Minniefield Receives 2012 Cham...,Health care; Higher education; Awards & honors...,"Los Angeles Sentinel; Los Angeles, Calif.\n\nV...",2012,"Jul 12-Jul 18, 2012",LOCAL NEWS,Los Angeles Sentinel,"Los Angeles, Calif.",...,News\n\nDocument feature: Photographs,1030278985,https://www.proquest.com/globalnewsfed/newspap...,2017-04-15,202.0,1.000000,"['grant', 'grants', 'received', 'diversity', '...",Please visit TCWF's website at CalWellness.org...,0.9375,"(0.8, 1.0]"
2502,TCWF Honors Health Education Leaders Committed...,Most recognized for her program Instant Recess...,The California Wellness Foundation (TCWF) hono...,Minority & ethnic groups; Public health; Healt...,"Los Angeles Sentinel; Los Angeles, Calif.\n\nV...",2013,"Jun 20-Jun 26, 2013",FAMILY Lifestyle HEALTH,Los Angeles Sentinel,"Los Angeles, Calif.",...,News\n\nDocument feature: Photographs,1399278155,https://www.proquest.com/globalnewsfed/newspap...,2017-04-15,202.0,1.000000,"['grant', 'grants', 'received', 'diversity', '...",Please visit TCWF's website at CalWellness.org...,0.9375,"(0.8, 1.0]"
2506,What's New: APPOINTMENTS,"The members are Christina Bark, founder and pr...",Walkway welcomes new board members -- The Walk...,Law firms; Attorneys; Litigation; Associations...,"The Poughkeepsie Journal; Poughkeepsie, N.Y.\n...",2013,"Jun 20, 2013",B,Gannett Media Corp,"Poughkeepsie, N.Y.",...,News,1369801218,https://www.proquest.com/globalnewsfed/newspap...,2017-11-20,202.0,1.000000,"['grant', 'grants', 'received', 'diversity', '...",At a recent event hosting guests at the Beekma...,0.9375,"(0.8, 1.0]"
2554,What's New: APPOINTMENT,Barrett has worked as a community health worke...,Nonprofit names coordinator -- Mid-Hudson Love...,Aging\n\nCompany / organization: Name: Center ...,"The Poughkeepsie Journal; Poughkeepsie, N.Y.\n...",2013,"May 30, 2013",B,Gannett Media Corp,"Poughkeepsie, N.Y.",...,News,1356444675,https://www.proquest.com/globalnewsfed/newspap...,2017-11-20,202.0,1.000000,"['grant', 'grants', 'received', 'diversity', '...",Details and menus are at www.roundhousebeacon....,0.9375,"(0.8, 1.0]"
5581,Grants awarded to West Tennessee seniors groups,None available.,Several facilities for seniors in West Tenness...,Quality of life; Meals; Older people; Transpor...,"The Jackson Sun; Jackson, Tenn.\n\nFirst page:...",2017,"Jan 31, 2017\n\ncolumn: Community foundation o...",Business,Gannett Media Corp,"Jackson, Tenn.",...,News,1864931090,https://www.proquest.com/globalnewsfed/newspap...,2017-11-24,202.0,1.000000,"['grant', 'grants', 'received', 'diversity', '...",Outcomes achieved by each grantee will be repo...,0.9375,"(0.8, 1.0]"
6341,Department of Aging announces ‘Producing Healt...,None available.,"GIRARD, OH - The Ohio Department of Aging has ...",Aging\n\nLocation: Ohio\n\nCompany / organizat...,"Lima News; Lima, Ohio",2019,"Dec 18, 2019",News,The Lima News,"Lima, Ohio",...,News,2328355489,https://www.proquest.com/globalnewsfed/newspap...,2019-12-19,202.0,1.000000,"['grant', 'grants', 'received', 'diversity', '...","GIRARD, OH - The Ohio Department of Aging has ...",0.9375,"(0.8, 1.0]"
6933,Aging issues in Lehigh Valley highlighted 'Day...,None available.,"When Carmen Bell worked for LANTA, she would f...",Older people; Volunteers; Aging; Youth organiz...,"Morning Call; Allentown, Pa.\n\nFirst page: A.6",2019,"Feb 19, 2019",NaN,"Tribune Publishing Company, LLC","Allentown, Pa.",...,News,2183049333,https://www.proquest.com/globalnewsfed/newspap...,2019-02-19,202.0,1.000000,"['grant', 'grants', 'received', 'diversity', '...",asalamone@mcall.com 610-820-6694 LEARN MORE Fo...,0.9375,"(0.8, 1.0]"
8500,$1 million in grants awarded to senior centers,None available.,Gallatin Senior Citizen Center was recently aw...,Older people; Grants; Funding; Aging; State bu...,"The Tennessean; Nashville, Tenn.\n\nFirst page...",2022,"Sep 21, 2022",News,Gannett Media Corp,"Nashville, Tenn.",...,News,2715936530,https://www.proquest.com/globalnewsfed/newspap...,2022-09-21,202.0,1.000000,"['grant', 'grants', 'received', 'diversity', '...",Grants received by the centers will facilitate...,0.9375,"(0.8, 1.0]"
9251,Butler County to spend $1M enhancing senior se...,None available.,Butler County has nearly $1 million in new gra...,Medicaid; Older people; Councils; Costs; Fundi...,Journal-News; Hamilton,2023,"Oct 12, 2023",News,"Atlanta Journal Constitution, LLC",Hamilton,...,News,3178755748,https://www.proquest.com/newspapers/butler-cou...,2025-03-19,202.0,1.000000,"['grant', 'grants', 'received', 'diversity', '...",It is new technology that allows the client or...,0.9375,"(0.8, 1.0]"
9301,Commissioners considering how to best use stat...,None available.,COSHOCTON − Coshocton County commissioners are...,Older people; Funding; Aging\n\nLocation: Unit...,"Coshocton Tribune; Coshocton, Ohio\n\nFirst pa...",2023,"Sep 29, 2023",News,Gannett Media Corp,"Coshocton, Ohio",...,News,2869829167,https://www.proquest.com/newspapers/commission...,2023-09-29,202.0,1.000000,"['grant', 'grants', 'received', 'diversity', '...",How to best use the funds is still under consi...,0.9375,"(0.8, 1.0]"
10193,Commissioners open bids to replace old boilers...,None available.,"Officials say heating Dayspring, Richland Coun...",Boilers; Aging\n\nLocation: United States--US;...,"News Journal; Mansfield, Ohio\n\nFirst page: A.2",2024,"Jun 3, 2024",News,Gannett Media Corp,"Mansfield, Ohio",...,News,3063262163,https://www.proquest.com/globalnewsfed/newspap...,2024-06-03,202.0,1.000000,"['grant', 'grants', 'received', 'diversity', '...",Area agency officials said the funds would be ...,0.9375,"(0.8, 1.0]"

***
The focus of the topic is not on either longevity or seniors
***

In [96]:
df = remove_topic(df,202,[])

The orig length:10334 -> cropped: 10318

<!-- structured-notebook -->
## Final Review Round
This last section revisits a later cleaned version (`df_v4`) and records the final targeted removals before writing the output used by subsequent notebooks.

### Topic cleaning v4

In [99]:
df = pd.read_csv(PROQUEST_PROCESSED_DIR / 'df_v4.csv')

In [100]:
for topic, keywords in df.groupby('topic')['topic_keywords'].unique().items():
    print(topic, "\n", keywords)

-1.0
 ['[]']
0.0
 ["['skin', 'hair', 'beauty', 'products', 'cream', 'lines', 'antiaging', 'vitamin', 'ingredients', 'product', 'sun', 'appearance', 'antiageing', 'oil', 'youthful', 'treatments', 'damage', 'fine', 'acid', 'pounds', 'water', 'antioxidants', 'signs', 'production', 'stem', 'cells', 'dry', 'contains', 'spots', 'routine']"]
1.0
 ["['india', 'senior citizens', 'citizens', 'geriatric', 'indian', 'welfare', 'elders', 'delhi', 'elderly population', 'programme', 'care elderly', 'organised', 'ministry', 'facilities', 'elderly people', 'published ht', 'permission', 'ht', 'policy', 'older persons', 'geriatric medicine', 'homes', 'union', 'content', 'minister', 'sector', 'old age', 'demographic', 'economic', 'occasion']"]
2.0
 ["['al', 'rehabilitation', 'corporation', 'geriatric', 'clinic', 'patient', 'national health', 'geriatrics', 'strategy', 'collaborating', 'longterm care', 'integrated', 'medical director', 'care older', 'tribune', 'primary', 'older persons', 'teams', 'programme', 'collaboration', 'ministry', 'evidencebased', 'agefriendly', 'media syndigateinfo', 'syndigate', 'provided syndigate', 'syndigate media', 'syndigateinfo', 'unit', 'explained']"]
3.0
 ["['singapore', 'mr', 'programmes', 'ageing population', 'retirement', 'ms', 'productivity', 'silver', 'minister', 'generation', 'prof', 'workforce', 'residents', 'workers', 'savings', 'retirement age', 'life expectancy', 'expectancy', 'ministry', 'employees', 'costs', 'lee', 'financial', 'programme', 'centres', 'integrated', 'labour', '2030', 'economic', 'encourage']"]
4.0
 ["['negative', 'ageism', 'purpose', 'attitudes', 'old age', 'getting older', 'meaning', 'happy', 'attitude', 'happiness', 'mindset', 'relationships', 'psychology', 'feeling', 'im', 'wisdom', 'feelings', 'thoughts', 'psychological', 'emotions', 'emotional', 'tend', 'anxiety', 'felt', 'ive', 'messages', 'resilience', 'fear', 'later life', 'birthday']"]
5.0
 ["['australians', 'australia', 'retirement', 'residential', 'housing', 'sector', 'ms', 'ageing population', 'australian', 'workforce', 'residents', 'strategy', 'port', 'rural', 'organisations', 'care services', 'providers', 'village', 'villages', 'homes', 'transport', 'minister', 'councils', 'mr', 'jobs', 'governments', 'home care', 'remote', 'health wellbeing', 'career']"]
6.0
 ["['falls', 'balance', 'falling', 'injuries', 'prevent falls', 'injury', 'strength', 'fear', 'medications', 'matter', 'risk falls', 'county', 'deaths', 'cause', 'emergency', 'leg', '65 older', 'exercises', 'hip', 'centers disease', 'disease control', 'grab', 'extension', 'preventing', 'fractures', 'awareness', 'leading cause', 'tai', 'class', 'classes']"]
7.0
 ["['volunteer', 'award', 'volunteers', 'awards', 'nonprofit', 'county', 'organizations', 'valley', 'campaign', 'volunteering', 'donated', 'office', 'board', 'designated', 'business', 'counties', 'organization', 'served', 'high school', 'outstanding', 'contributions', 'transportation', 'medical center', 'raised', 'bus', 'agencies', 'centers', 'box', 'agency', 'donations']"]
8.0
 ["['race', 'games', 'chicago', 'sports', 'im', 'sport', 'masters', 'swimming', 'running', 'record', 'finish', 'tennis', 'track', 'won', 'playing', 'film', 'fit', 'win', 'womens', 'competition', 'fun', 'class', 'tour', 'park', 'club', 'prescription', 'pool', 'title', 'cycling', 'retired']"]
9.0
 ["['pm', 'st', 'wednesday', 'ave', 'church', 'club', 'thursday', 'monday', 'tuesday', 'thursdays', 'friday', 'bridge', 'tuesdays', 'wednesdays', 'noon', 'sept', 'april', 'rd', 'register', 'oct', '130', 'saturday', 'river', 'lunch', '930', 'feb', 'tickets', 'library', '13', 'nov']"]
10.0
 ["['nursing', 'nursing homes', 'province', 'homes', 'nursing home', 'longterm care', 'summit', 'beds', 'aging population', 'minister', 'home care', 'stakeholders', 'panel', 'hospitals', 'ontario', 'organizations', 'residents', 'canada', 'facilities', 'policy', 'workers', 'model', 'executive director', 'governments', 'weve', 'tv', 'coalition', 'strategy', 'creating', 'citizens']"]
11.0
 ["['biological', 'dna', 'clock', 'tests', 'scientists', 'markers', 'genes', 'test', 'agerelated', 'accelerated', 'exposure', 'testing', 'cells', 'measured', 'environmental', 'measure', 'genetic', 'cellular', 'molecular', 'faster', 'actual', 'smoking', 'sugar', 'cell', 'ageing process', 'damage', 'liver', 'patterns', 'blood sugar', 'longevity']"]
12.0
 ["['expo', 'pm', 'fair', 'register', 'library', 'speakers', 'takes place', 'ontario', 'oct', 'topics', 'hosted', 'st', 'presented', 'thursday', 'talks', 'presentation', 'recreation', 'wednesday', 'lunch', 'ave', 'prizes', 'presentations', 'jan', '10 pm', 'guest', 'registration', 'march', 'programs services', 'noon', 'workshops']"]
13.0
 ["['music', 'art', 'march', 'arts', 'creative', 'los angeles', 'angeles', 'los', 'creativity', 'admission', 'successful aging', 'film', 'dean', 'hills', 'successful', 'saturday', 'dance', 'expo', 'photo', 'residents', 'pm', 'april', 'assisted living', '2019', 'hall', 'assisted', 'vancouver', 'tour', 'rock', 'st']"]
14.0
 ["['retirement', 'workers', 'labour', 'job', 'retire', 'retirement age', 'financial', 'employers', 'employees', 'participation', 'employment', 'wealth', 'workforce', 'security', 'boomers', 'career', 'jobs', 'countries', 'careers', 'market', 'force', 'life expectancy', 'expectancy', 'business', 'savings', 'retirees', 'retiring', 'income', 'workplace', 'economic']"]
15.0
 ["['dairy', 'milk', 'products', 'consumers', 'markets', 'india', 'product', 'ingredients', 'industry', 'consumer', 'market', 'protein', 'brand', 'asia', 'global', 'nutritional', 'china', 'sales', 'business', 'demand', 'companies', 'new zealand', 'zealand', 'innovation', 'ireland', 'production', 'irish', 'value', 'foods', 'billion']"]
16.0
 ["['fatty', 'fish', 'acids', 'mediterranean', 'vegetables', 'foods', 'brain health', 'olive', 'oil', 'nuts', 'diets', 'serving', 'eating', 'dietary', 'fats', 'alzheimers disease', 'fruit', 'cognitive decline', 'brain function', 'meat', 'nutrients', 'acid', 'grains', 'seeds', 'vitamin', 'healthy diet', 'rich', 'cognitive function', 'eat', 'fruits']"]
17.0
 ["['technology', 'devices', 'digital', 'internet', 'users', 'technologies', 'smart', 'device', 'tech', 'innovation', 'tracking', 'watch', 'connected', 'homes', 'buy', 'independence', 'facebook', 'phone', 'video', 'app', 'tools', 'loneliness', 'mobile', 'consumers', 'lab', 'features', 'consumer', 'solutions', 'monitoring', 'market']"]
18.0
 ["['cooking', 'eating', 'eat', 'meals', 'vegetables', 'foods', 'healthy eating', 'cook', 'zones', 'advice', 'meal', 'dietitian', 'recipe', 'kitchen', 'appetite', 'fruits', 'line', 'protein', 'nutrients', 'fresh', 'blue', 'ingredients', 'nutritional', 'registered', 'class', 'fruits vegetables', 'march', 'nutritious', 'weight', 'rice']"]
19.0
 ["['genetic', 'centenarians', 'genes', 'longevity', 'dna', 'exceptional', 'gene', 'genetics', 'super', 'long life', 'mr', 'boston', 'scientists', 'predict', 'samples', 'lived', '110', 'oldest', 'died', 'rare', 'thomas', 'general population', 'heart disease', '90', 'testing', 'test', 'identify', 'markers', 'new england', 'eric']"]
20.0
 ["['weight', 'obesity', 'weight loss', 'obese', 'fat', 'bmi', 'overweight', 'lose', 'gain', 'eating', 'pounds', 'mass', 'eat', 'body mass', 'middle', 'im', 'type diabetes', 'muscle', 'foods', 'calories', 'lean', 'happiness', 'sugar', 'type', 'habits', 'diets', 'lost', 'protein', 'mass index', 'index']"]
21.0
 ["['abuse', 'elder', 'older americans', 'americans', 'georgia', 'longterm care', 'nursing', 'medicare', 'security', 'advocates', 'housing', 'council aging', 'administration', 'conference', 'nursing home', 'federal', 'law', 'homes', 'financial', 'act', 'county', 'atlanta', 'nursing homes', 'office', 'transportation', 'agencies', 'caregivers', 'policy', 'coalition', 'residents']"]
22.0
 ["['gut', 'bacteria', 'mice', 'inflammation', 'inflammatory', 'foods', 'dry', 'oil', 'composition', 'immune', 'dogs', 'diversity', 'chicken', 'beneficial', 'mediterranean', 'frailty', 'kidney', 'digestive', 'heat', 'ingredients', 'gradually', 'dog', 'fish', 'species', 'minutes', 'processed', 'vegetables', 'linked', 'fresh', 'fruits']"]
23.0
 ["['older persons', 'countries', 'asia', 'japan', 'region', 'policies', 'economic', 'demographic', 'workers', 'productivity', '2050', 'policy', 'systems', 'proportion', 'china', 'labour', 'societies', 'rights', 'fertility', 'projected', 'populations', 'force', 'inclusive', 'rapidly', 'economy', 'shift', 'governments', 'global', 'rapid', 'income']"]
24.0
 ["['sleep', 'sleeping', 'night', 'bed', 'disorder', 'nights', 'disorders', 'watch', 'cardiovascular health', 'deep', 'breathing', 'hormone', 'trouble', 'poor', 'cardiovascular', 'short', 'wake', 'tired', 'negative', 'schedule', 'lack', 'morning', 'duration', 'beach', 'coffee', 'minutes', 'suffer', 'chris', 'clock', 'evening']"]
25.0
 ["['agefriendly', 'friendly', 'housing', 'cities', 'buildings', 'spaces', 'mayor', 'residents', 'committee', 'town', 'participation', 'accessible', 'transportation', 'framework', 'citys', 'outdoor', 'health organization', 'council aging', 'world health', 'organization', 'vancouver', 'parks', 'survey', 'accessibility', 'aging population', 'places', 'inclusion', 'older adult', 'bc', 'civic']"]
26.0
 ["['canadian', 'health sciences', 'ontario', 'research institute', 'canada', 'sciences', 'canadians', 'northern', 'longitudinal', 'investigator', 'health research', 'principal investigator', 'principal', 'frailty', 'collection', 'awarded', 'breast', 'clinical', 'peoples', 'statistics', 'obesity', 'expectancy', 'fellowship', 'life expectancy', 'geriatric', '20 years', 'institutes health', 'patient', 'institutes', 'baby']"]
27.0
 ["['mobility', 'walking', 'exercises', 'strength', 'muscles', 'walk', 'legs', 'winter', 'pain', 'muscle', 'balance', 'movements', 'cold', 'leg', 'joints', 'resistance', 'hearing loss', 'weights', 'steps', 'hearing', 'warm', 'weather', 'disability', 'movement', 'core', 'lifting', 'walker', 'bone', 'muscle strength', 'compound']"]
28.0
 ["['al', 'awareness', 'alzheimers disease', 'diagnosis', 'geriatric', 'corporation', 'risk factors', 'national health', 'symptoms', 'global', 'people dementia', 'condition', 'said dr', 'tribune', 'media syndigateinfo', 'provided syndigate', 'syndigate media', 'syndigate', 'syndigateinfo', 'consultant', 'reserved provided', 'people living', 'memory loss', 'rights reserved', 'caregivers', 'rehabilitation', 'reserved', 'september', 'strategy', 'medical director']"]
29.0
 ["['lifespan', 'gene', 'cells', 'genes', 'humans', 'scientists', 'cell', 'cellular', 'proteins', 'mice', 'discovery', 'restriction', 'discovered', 'metabolic', 'animals', 'pathways', 'metabolism', 'protein', 'response', 'longevity', 'agerelated', 'mechanisms', 'glucose', 'compound', 'extend', 'effect', 'fruit', 'agerelated diseases', 'journal', 'extending']"]
30.0
 ["['club', 'november', 'expo', 'tea', 'april', 'details', 'phone', 'st', 'room', 'heads', 'park', 'hall', 'entertainment', 'sunday', 'morning', 'friday', 'workshops', 'bay', 'march', 'clubs', 'library', 'email', 'parking', 'leisure', 'fun', 'saturday', 'celebrate', 'october', 'tomorrow', 'wednesday']"]
31.0
 ["['medication', 'medications', 'september', 'staying', 'high blood', 'smoking', 'blood pressure', 'americans', 'physically', 'walking', 'checkups', 'make sure', 'youre', 'habits', 'prescription', 'medicines', 'regularly', 'eat', 'physical mental', 'ask', 'loved', 'list', 'balance', 'healthy lifestyle', 'mentally', 'avoid', 'falls', 'weight', 'physician', 'loved ones']"]
32.0
 ["['gym', 'club', 'classes', 'sport', 'equipment', 'sessions', 'recreation', 'outdoor', 'exercising', 'class', 'sports', 'lake', 'fit', 'parks', 'optimal', 'health fitness', 'moving', 'ride', 'fun', 'rates', 'shed', '50s', 'opened', 'staying', 'location', 'feb', 'fellow', 'gentle', 'coast', 'mens']"]
33.0
 ["['nhs', 'ireland', 'ageing population', 'wales', 'health social', 'life expectancy', 'expectancy', 'authorities', 'councils', 'uk', 'peoples', 'people living', 'care home', 'contribution', 'tax', 'strategy', 'britain', 'burden', 'old age', 'economic', 'aged 65', 'independence', 'care services', 'debate', 'figures', 'numbers', 'places', '85', 'living longer', 'residential']"]
34.0
 ["['eating', 'breakfast', 'foods', 'eat', 'sugar', 'fats', 'nuts', 'diets', 'vegetables', 'calories', 'processed', 'dietary', 'rice', 'fruits', 'meat', 'beans', 'grains', 'mediterranean', 'plantbased', 'fat', 'protein', 'fruits vegetables', 'fish', 'seeds', 'cholesterol', 'red', 'olive', 'milk', 'oil', 'fruit']"]
35.0
 ["['cells', 'drugs', 'scientists', 'cell', 'longevity', 'biology', 'drug', 'animals', 'humans', 'slow', 'agerelated', 'extend', 'dna', 'lifespan', 'mice', 'ageing process', 'biological', 'genes', 'processes', 'die', 'live longer', 'cellular', 'antiageing', 'repair', 'antiaging', 'reverse', 'stem', 'immune', 'damage', 'scientific']"]
36.0
 ["['sleep', 'inflammation', 'longevity', 'voice', 'heart disease', 'eat', 'live longer', 'muscle', 'night', 'foods', 'blood pressure', 'alcohol', 'strength', 'minutes', 'drink', 'fat', 'moderate', 'youre', 'eating', 'smoking', 'vegetables', 'risk heart', 'walking', 'lower risk', 'avoid', 'fruits vegetables', 'weight', 'sleeping', 'muscles', 'mass']"]
37.0
 ["['diets', 'foods', 'intake', 'grains', 'fat', 'calories', 'fats', 'protein', 'mortality', 'olive', 'chicken', 'rice', 'oil', 'bread', 'vegetables', 'eating', 'nutrients', 'sugar', 'meat', 'consumption', 'plantbased', 'proteins', 'moderate', 'weight loss', 'white', 'beans', 'dietary', 'weight', 'linked', 'cut']"]
38.0
 ["['midlife', 'book', 'cholesterol', 'protein', 'sleep', 'breakfast', 'success', 'muscle', 'habits', 'heart disease', 'weight', 'mood', 'peak', 'happiness', 'risk heart', 'healthy lifestyle', 'movement', 'hormones', 'pain', 'eat', 'depression', 'thoughts', 'gain', 'geriatrician', 'suggests', 'eating', 'high cholesterol', 'choices', 'gets', 'arteries']"]
39.0
 ["['cares', 'donations', 'board', 'honor', 'mission', 'wish', 'volunteers', 'wheels', 'equipment', 'meals', 'chairs', 'classes', 'list', 'directors', 'pieces', 'appointments', 'committee', 'paper', 'drive', 'gift', 'supplies', 'meeting', 'susan', 'attending', 'disabled', 'cards', 'memorial', 'items', 'barbara', 'saturday']"]
40.0
 ["['projects', 'communitybased', 'funding', 'organizations', 'canada', 'inclusion', 'apply', 'abuse', 'help seniors', 'supports', 'grant', 'minister', 'eligible', 'invited', 'elder', 'grants', 'priorities', 'federal', 'diversity', 'stay active', 'participate', 'celebrating', 'pandemic', 'connected', 'engaged', 'announcement', 'announced', 'submit', 'contributions', 'facts']"]
41.0
 ["['brain health', 'brains', 'risk dementia', 'alzheimers disease', 'risk developing', 'cognitive decline', 'memory loss', 'lifestyle factors', 'blood pressure', 'sleep', 'reduce risk', 'smoking', 'evidence', 'aerobic', 'alcohol', 'brain cells', 'high blood', 'healthy lifestyle', 'review', 'lower risk', 'mediterranean', 'healthy brain', 'protect', 'language', 'habits', 'trials', 'rush', 'learn new', 'reserve', 'impairment']"]
42.0
 ["['protein', 'plantbased', 'plant', 'eggs', 'muscle', 'meat', 'animal', 'intake', 'beans', 'proteins', 'foods', 'weight', 'muscle mass', 'products', 'sources', 'meal', 'mass', 'milk', 'trends', 'eat', 'eating', 'vegetables', 'dietary', 'add', 'trend', 'consumed', 'cup', 'supplements', 'diets', 'chicken']"]
43.0
 ["['length', 'immune', 'cells', 'cell', 'shorter', 'dna', 'fasting', 'ends', 'cellular', 'lifestyle changes', 'genes', 'endurance', 'short', 'protect', 'biological', 'findings', 'protective', 'vitamin', 'slow', 'virus', 'controls', 'infections', 'scientists', 'kill', 'resistance', 'points', 'ageing process', 'effect', 'ani', 'lifespan']"]
44.0
 ["['minute', 'regular exercise', 'heart rate', 'minutes', 'inactivity', 'depression', 'exercising', 'fit', 'sustained', 'walking', 'physically', 'heart disease', 'intensity', 'physically active', 'health benefits', 'vigorous', 'moderate', 'muscles', 'blog', 'bones', 'weight', 'im', 'average age', 'british', 'drinking', 'sports', 'absence', 'relatively', 'colleagues', 'gym']"]
45.0
 ["['countries', 'older persons', 'ageism', 'rights', '2050', 'united nations', 'abuse', 'dignity', 'aged 60', 'senior citizens', 'policies', 'nations', 'citizens', 'billion', 'contributions', '60 years', 'welfare', 'global', 'decade', 'economic', 'action', 'governments', 'protection', 'civil', 'capital', 'people aged', 'world health', 'societies', 'demographic', 'respect']"]
46.0
 ["['courses', 'students', 'classes', 'lifelong', 'games', 'lectures', 'class', 'topics', 'campus', 'universities', 'educational', 'spring', 'student', 'art', 'registration', 'gerontology', 'lifetime', 'continuing', 'writing', 'taught', 'florida', 'state university', 'lecture', 'joy', 'skills', 'offered', 'series', 'degree', 'june', 'music']"]
47.0
 ["['alzheimers disease', 'diagnosis', 'memory loss', 'brains', 'test', 'tests', 'symptoms', 'johnson', 'testing', 'slow', 'clinical', 'brain health', 'cognitive decline', 'progression', 'diagnosed', 'screening', 'lifetime', 'cases', 'brain function', 'healthy brain', 'risk factors', 'sister', 'identify', 'stimulation', 'trials', 'mild', 'signs', 'scientists', 'drugs', 'genetic']"]
48.0
 ["['fruits', 'vegetables', 'fruits vegetables', 'antioxidants', 'sweet', 'fruit', 'vitamin', 'red', 'cup', 'contain', 'rich', 'green', 'fresh', 'health benefits', 'add', 'source', 'color', 'sugar', 'protect', 'nutrients', 'white', 'powerful', 'vitamins', 'properties', 'contains', 'lower risk', 'taste', 'foods', 'immune', 'help reduce']"]
49.0
 ["['cells', 'stem', 'drugs', 'mice', 'drug', 'trials', 'scientists', 'antiageing', 'companies', 'cell', 'humans', 'labs', 'field', 'extend', 'therapies', 'lifespan', 'clinical', 'tissues', 'scientific', 'clinical trials', 'discovery', 'target', 'biology', 'promising', 'biological', 'reverse', 'tissue', 'trial', 'agerelated', 'longevity']"]
50.0
 ["['sex', 'sexual', 'partner', 'aids', 'heart attack', 'virus', 'relationship', 'attack', 'revealed', 'love', 'diagnosed', 'desire', '45', 'people living', 'survey', 'boomers', '60s', 'reported', 'cardiovascular', 'scott', 'menopause', 'partners', 'yes', 'men women', 'didnt', 'book', 'cases', 'premature', 'drugs', 'survivors']"]
51.0
 ["['canada', 'canadians', 'minister', 'security', 'guide', 'income', 'bc', 'province', 'caregivers', 'caregiver', 'retire', 'supplement', 'housing', 'website', 'act', 'english', 'governments', 'todays', 'action', 'aging population', 'retirement', 'consumer', '67', 'inclusion', 'contributions', 'organizations', 'projects', 'forum', 'supports', 'strategy']"]
52.0
 ["['vaccine', 'flu', 'vaccines', 'shot', 'covid19', 'phone', 'virus', 'infection', 'appointments', 'doses', 'coronavirus', 'respondents', 'cases', 'dose', 'providers', 'respiratory', 'immunity', 'disease control', 'infections', 'residents', 'control prevention', 'appointment', 'immune', 'clinics', 'officials', 'alert', 'centers disease', 'deaths', 'infectious', 'season']"]
53.0
 ["['sitting', 'sedentary', 'walking', 'vigorous', 'resistance', 'tv', 'exercises', 'watching', 'strength', 'muscle', 'muscles', 'minutes', 'weight', 'hours day', 'exercising', 'moderate', 'workout', 'protein', 'aerobic', 'television', 'running', 'strength training', 'weights', 'gym', 'physically active', 'physically', 'spent', 'standing', 'mortality', 'odds']"]
54.0
 ["['depression', 'psychiatry', 'geriatric', 'old age', 'elders', 'health problems', 'symptoms', 'india', 'depressed', 'awareness', 'feelings', 'seek', 'disorders', 'anxiety', 'ht', 'published ht', 'professionals', 'psychological', 'permission', 'people dementia', 'normal', 'caregivers', 'content', 'behaviour', 'thoughts', 'loved', 'medication', 'condition', 'mood', 'physical health']"]
55.0

#### Topic 9

In [101]:
df[df['topic']==9]

,Title,Abstract,Full text,Subject,Publication title,Publication year,Publication date,Section,Publisher,Place of publication,...,ISSN,Language of publication,Document type,ProQuest document ID,Document URL,Last updated,last,topic,topic_prob,topic_keywords
58,"too good to miss: For nonprofit, charity or ...",Alzheimer Society of Hamilton and Halton Care ...,All numbers are in 905 area code unless otherw...,NaN,"The Spectator; Hamilton, Ont.\n\nFirst page: G...",2010,"Nov 22, 2010",Go,"Torstar Syndication Services, a Division of To...","Hamilton, Ont.",...,11899417,English,News,807637429,https://www.proquest.com/globalnewsfed/newspap...,2017-11-17,"The McQuesten's Childhood Christmas, Nov. 20, ...",9.0,1.000000,"['pm', 'st', 'wednesday', 'ave', 'church', 'cl..."
139,Your town in brief: Winter symphony season sta...,None available.,Murray Come to the symphony - Murray's Symphon...,NaN,"The Salt Lake Tribune; Salt Lake City, Utah",2010,"Oct 6, 2010",NaN,The Salt Lake Tribune,"Salt Lake City, Utah",...,07463502,English,News,756774760,https://www.proquest.com/globalnewsfed/newspap...,2017-11-17,Murray Haul out your holly - The search is on ...,9.0,0.072010,"['pm', 'st', 'wednesday', 'ave', 'church', 'cl..."
152,Your town in brief: Fixing pit bulls for free ...,None available.,West Valley City Free neutering for pit bulls ...,NaN,"The Salt Lake Tribune; Salt Lake City, Utah",2010,"Sep 29, 2010",NaN,The Salt Lake Tribune,"Salt Lake City, Utah",...,07463502,English,News,755681980,https://www.proquest.com/globalnewsfed/newspap...,2017-11-17,The mall is located at 3601 S. 2700 West. Magn...,9.0,0.065165,"['pm', 'st', 'wednesday', 'ave', 'church', 'cl..."
187,Access Transcona offers the following. Call 93...,"Age & Opportunity Inc. ABC's of Fraud, seldom ...",Access Transcona offers the following. Call 93...,NaN,"Winnipeg Free Press; Winnipeg, Man.\n\nFirst p...",2010,"Sep 17, 2010",NaN,FP Canadian Newspapers Limited Partnership,"Winnipeg, Man.",...,08281785,English,News,751110174,https://www.proquest.com/globalnewsfed/newspap...,2017-11-17,The study includes physical assessment of the ...,9.0,1.000000,"['pm', 'st', 'wednesday', 'ave', 'church', 'cl..."
191,Access East offers the following. Call 938-500...,"Age & Opportunity Inc. ABC's of Fraud, seldom ...",Access East offers the following. Call 938-500...,NaN,"Winnipeg Free Press; Winnipeg, Man.",2010,"Sep 15, 2010",NaN,FP Canadian Newspapers Limited Partnership,"Winnipeg, Man.",...,08281785,English,News,750514928,https://www.proquest.com/globalnewsfed/newspap...,2017-11-17,The study includes physical assessment of the ...,9.0,1.000000,"['pm', 'st', 'wednesday', 'ave', 'church', 'cl..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8233,Things To Do,None available.,"Wednesday, March 9 ONLINE: Bingocize, 10-11 a....",Bible; Biblical studies; Aging,"Bangor Daily News; Bangor, Me.",2022,"Mar 7, 2022",NaN,Bangor Daily News,"Bangor, Me.",...,08928738\n\ne-ISSN: 26437457,English,News,2637161192,https://www.proquest.com/globalnewsfed/newspap...,2022-03-09,All others need to follow the 6 foot distance....,9.0,0.120718,"['pm', 'st', 'wednesday', 'ave', 'church', 'cl..."
8360,What's Happening,None available.,"Wednesday, Jan. 5 CARIBOU: Miss Erin's Picture...",Support groups; Public libraries; Food; Caregi...,"Bangor Daily News; Bangor, Me.",2022,"Jan 3, 2022",NaN,Bangor Daily News,"Bangor, Me.",...,08928738\n\ne-ISSN: 26437457,English,News,2616368550,https://www.proquest.com/globalnewsfed/newspap...,2022-01-14,"ONLINE: Caregiver Support Group, 12-1 p.m., ho...",9.0,0.129789,"['pm', 'st', 'wednesday', 'ave', 'church', 'cl..."
8361,Community Calendar,None available.,"Wednesday, Jan. 5 FORT FAIRFIELD: Senior commo...",Caregivers; Aging; Commodities\n\nBusiness ind...,"Bangor Daily News; Bangor, Me.",2022,"Jan 3, 2022",NaN,Bangor Daily News,"Bangor, Me.",...,08928738\n\ne-ISSN: 264 37457,English,News,2616368538,https://www.proquest.com/globalnewsfed/newspap...,2022-01-14,Combines bingo with moderate exercise. For any...,9.0,0.125181,"['pm', 'st', 'wednesday', 'ave', 'church', 'cl..."
8619,"Get set for live music, Oktoberfest",None available.,FOND DU LAC — Singer/songwriter Dan Rodriguez ...,Internal medicine; Diabetes; Vaccines; Opera h...,"The Reporter; Fond du Lac, Wis.\n\nFirst page:...",2023,"Oct 2, 2023\n\ncolumn: Weekly dose",News,Gannett Media Corp,"Fond du Lac, Wis.",...,NaN,English,News,2871351397,https://www.proquest.com/newspapers/get-set-li...,2023-10-02,"The classes are free, but a $10 donation is re...",9.0,0.145069,"['pm', 'st', 'wednesday', 'ave', 'church', 'cl..."
9250,Listings,None available.,"OCT. 1 Mass: 9 to 9:30 a.m., St. Patrick's Chu...",Older people; Art galleries & museums\n\nBusin...,"Sudbury Star; Sudbury, Ont.\n\nFirst page: B.4",2024,"Oct 1, 2024",You,Postmedia Network Inc.,"Sudbury, Ont.",...,08392544,English,News,3111751352,https://www.proquest.com/globalnewsfed/newspap...,2024-10-02,It will run until Oct. 25. Art: The Full Circl...,9.0,0.367869,"['pm', 'st', 'wednesday', 'ave', 'church', 'cl..."

***
Ad topic
***

In [107]:
df = remove_topic(df,9,[])

The orig length:10318 -> cropped: 10216

#### Topic 59

In [112]:
df[df['topic']==59]

,Title,Abstract,Full text,Subject,Publication title,Publication year,Publication date,Section,Publisher,Place of publication,...,ISSN,Language of publication,Document type,ProQuest document ID,Document URL,Last updated,last,topic,topic_prob,topic_keywords
11,'Winter Blues' talk at Sylvia Ross Home,None available.,"BANGOR - Rosscare will hold an event called ""B...",NaN,"Bangor Daily News; Bangor, Me.\n\nFirst page: 3",2010,"Dec 21, 2010",B,Bangor Daily News,"Bangor, Me.",...,08928738\n\ne-ISSN: 26437457,English,News,818937716,https://www.proquest.com/globalnewsfed/newspap...,2017-11-17,"During the presentation, she will provide tips...",59.0,0.111724,"['pm', 'health education', 'road', 'meets', 'r..."
193,Asheville area health calendar,First meeting is Sept. 22; group will meet Wed...,The complete Health Calendar is posted online ...,Womens health; Shoulder; Health insurance; Phy...,"Asheville Citizen - Times; Asheville, N.C.",2010,"Sep 21, 2010",LIVING,Gannett Media Corp,"Asheville, N.C.",...,NaN,English,News,751848869,https://www.proquest.com/globalnewsfed/newspap...,2019-12-06,Call 452-8085 for a free consultation. WEIGHT ...,59.0,0.146876,"['pm', 'health education', 'road', 'meets', 'r..."
462,Health calendar: Services,Prenatal yoga is a wonderful way to honor your...,Divorce Recovery: 6 p.m. Tuesdays through Apri...,Hospitals; Social support; Yoga; Families & fa...,"Pensacola News Journal; Pensacola, Fla.",2010,"Mar 14, 2010",Online Life,Gan nett Media Corp,"Pensacola, Fla.",...,NaN,English,News,436240836,https://www.proquest.com/globalnewsfed/newspap...,2023-10-09,"Cokesbury United Methodist Church, 5725 N. Nin...",59.0,1.000000,"['pm', 'health education', 'road', 'meets', 'r..."
569,WEST COUNTY: County offers way to get fit in 2010,"The center's book club will meet to discuss ""S...",The county Recreation and Parks Department wil...,NaN,"Maryland Gazette; Glen Burnie, Md.\n\nFirst pa...",2010,"Jan 2, 2010",Community,"Tribune Publishing Company, LLC","Glen Burnie, Md.",...,NaN,English,News,374464115,https://www.proquest.com/globalnewsfed/newspap...,2016-10-22,Sign-up is required and there is a $10 fee per...,59.0,0.070219,"['pm', 'health education', 'road', 'meets', 'r..."
630,Health and fitness Send items to nbrcalendar@d...,Alzheimer's Caregivers Support Group: 1:30 to ...,Items that focus on physical and mental health...,NaN,"Daily Herald; Arlington Heights, Ill.\n\nFirst...",2011,"Nov 17, 2011",NEIGHBOR,Daily Herald,"Arlington Heights, Ill.",...,NaN,English,News,904414345,https://www.proquest.com/globalnewsfed/newspap...,2017-11-18,Total body conditioning class for people of al...,59.0,1.000000,"['pm', 'health education', 'road', 'meets', 'r..."
641,Free Health Screenings Available at Saturday G...,Speakers and their schedules are: Tent 1: 11 a...,"DAVENPORT | For the third year in a row, The P...",NaN,"The Ledger; Lakeland, Fla.",2011,"Nov 10, 2011",NEWS,Halifax Media Group,"Lakeland, Fla.",...,01630288,English,News,903160359,https://www.proquest.com/globalnewsfed/newspap...,2012-10-13,Nonprofit organizations include the Alzheimer'...,59.0,1.000000,"['pm', 'health education', 'road', 'meets', 'r..."
770,Local health news: Saint Mary's offers disease...,Saint Mary's Regional Medical Center is offeri...,Saint Mary's Regional Medical Center is offeri...,Aging; Blindness; Meditation,"Reno Gazette - Journal; Reno, Nev.",2011,"Sep 20, 2011",LIV,Gannett Media Corp,"Reno, Nev.",...,NaN,English,News,892602293,https://www.proquest.com/globalnewsfed/newspap...,2017-11-18,"After the meditation, enjoy conscious dance wi...",59.0,0.074019,"['pm', 'health education', 'road', 'meets', 'r..."
777,Health calendar,Monthly presentations by health care professio...,The complete Health Calendar is posted online ...,Medical research; Cancer therapies; Personal h...,"Asheville Citizen - Times; Asheville, N.C.",2011,"Feb 8, 2011",LIVING,Gannett Media Corp,"Asheville, N.C.",...,NaN,English,News,849673261,https://www.proquest.com/globalnewsfed/newspap...,2017-11-17,Call 452-8085 for a free consultation. WEIGHT ...,59.0,1.000000,"['pm', 'health education', 'road', 'meets', 'r..."
849,Asheville area health calendar of events for t...,"Meal planning, medication usage, sick day care...",TOPS-Take Off Pounds Sensibly: 5-6:15 p.m. Tue...,Medical screening; Diabetes; Methodist churche...,"Asheville Citizen - Times; Asheville, N.C.",2011,"Aug 9, 2011",LIVING,Gannett Media Corp,"Asheville, N.C.",...,NaN,English,News,881736947,https://www.proquest.com/globalnewsfed/newspap...,2017-11-18,Call 452-8085 for a free consultation. WEIGHT ...,59.0,1.000000,"['pm', 'health education', 'road', 'meets', 'r..."
871,HEALTH CALENDAR: Events,None available.,"CITIZEN CPR: 12:30-1 p.m. today, Pardee Health...",NaN,"Asheville Citizen - Times; Asheville, N.C.",2011,"Aug 2, 2011",LIVING,Gannett Media Corp,"Asheville, N.C.",...,NaN,English,News,880350574,https://www.proquest.com/globalnewsfed/newspap...,2017-11-18,Call 452-8085 for a free consultation. WEIGHT ...,59.0,1.000000,"['pm', 'health education', 'road', 'meets', 'r..."
966,Wellness events,"What: Free, interactive educational event for ...","Dollars and Sense What: Free, interactive educ...",NaN,"The Spectator; Hamilton, Ont.\n\nFirst page: GO.6",2011,"Jun 7, 2011",Go,"Torstar Syndication Services, a Division of To...","Hamilton, Ont.",...,11899417,English,News,870464256,https://www.proquest.com/globalnewsfed/newspap...,2017-11-18,"When: Friday, July 8, 12:30 p.m. Where: The Ha...",59.0,1.000000,"['pm', 'health education', 'road', 'meets', 'r..."
1197,Rosscare to present 'Beat the Winter Blues',None available.,"Rosscare will present ""Beat the Winter Blues"" ...",NaN,"Bangor Daily News; Bangor, Me.\n\nFirst page: 8",2011,"Jan 11, 2011",C,Bangor Daily News,"Bangor, Me.",...,08928738\n\ne-ISSN: 26437457,English,News,834118880,https://www.proquest.com/globalnewsfed/newspap...,2017-11-17,She will discuss the symptoms of depression an...,59.0,0.107152,"['pm', 'health education', 'road', 'meets', 'r..."
1306,"D.C. Wellness calendar, November 1-8","Low-vision support group Thursday, 10-11:30 a....",Heart Walk volunteers needed Help out at the N...,Commissions; Entrepreneurs; Libraries; Yoga,"The Washington Post; Washington, D.C.",2012,"Nov 1, 2012",LOCAL LIVING,WP Company LLC d/b/a The Washington Post,"Washington, D.C.",...,01908286,English,News,1124618656,https://www.proquest.com/globalnewsfed/newspap...,2017-11-20,SE. 202-549-4172. $18 per session. - Compiled ...,59.0,0.208412,"['pm', 'health education', 'road', 'meets', 'r..."
1322,Healthy Family Training Camp offer includes fr...,"For a limited time, families that register for...",Registration has begun for the American Heart ...,Colleges & universities; Cardiovascular diseas...,"Courier - Journal; Louisville, Ky.",2012,"Oct 24, 2012",In The Prime: Fun,Gannett Media Corp,"Louisville, Ky.",...,19302177,English,News,1115159339,https://www.proquest.com/globalnewsfed/newspap...,2017-11-19,Free tickets are one per camp attendee during ...,59.0,0.110809,"['pm', 'health education', 'road', 'meets', 'r..."
1352,North State in Brief,None available.,Gallery features illness survivors Hill Countr...,Multimedia; Musical performances; Mental disor...,Record Searchlight; Redding\n\nFirst page: A.3,2012,"Oct 8, 2012",Local,Gannett Media Corp,Redding,...,NaN,English,News,2593191123,htt ps://www.proquest.com/globalnewsfed/newspa...,2021-11-04,The concert is in place of Sunday's 6 p.m. ser...,59.0,1.000000,"['pm', 'health education', 'road', 'meets', 'r..."
1449,Health Events,"Acupuncture helps with fertility, pregnancy, p...",Health events Fitness in the Parks series -- R...,Reflexology; Acupuncture; Clinics; Yoga\n\nCom...,"The Journal News; White Plains, N.Y.",2012,"Sep 2, 2012",F,Gannett Media Corp,"White Plains, N.Y.",...,NaN,English,News,1240575046,https://www.proquest.com/globalnewsfed/newspap...,2017-11-20,11:15 a.m. Saturdays through Sept. 29. $225 in...,59.0,0.275929,"['pm', 'health education', 'road', 'meets', 'r..."
1693,IN BRIEF: Pregnancy center announces summer ...,None available.,"Beginning May 5, the Blue Water Pregnancy Care...",NaN,"Times Herald; Port Huron, Mich.",2012,"Apr 18, 2012",A-Section,Gannett Media Corp,"Port Huron, Mich.",...,NaN,English,News,1012296968,https://www.proquest.com/globalnewsfed/newspap...,2017-11-19,Registration is available online at www.sc4.ed...,59.0,0.143910,"['pm', 'health education', 'road', 'meets', 'r..."
1840,Health and fitness Send items to nbrcalendar@d...,Alzheimer's Caregivers Support Group: 1:30-3 p...,Items that focus on physical and mental health...,NaN,"Daily Herald; Arlington Heights, Ill.\n\nFirst...",2012,"Jan 19, 2012",NEIGHBOR,Daily Herald,"Arlington Heights, Ill.",...,NaN,English,News,916784726,https://www.proquest.com/globalnewsfed/newspap...,2017-11-19,"Fitness Boot Camp: Elite Athletic Development,...",59.0,1.000000,"['pm', 'health education', 'road', 'meets', 'r..."
1886,Center for Healthy Aging at Kimball Medical Ce...,"Lunch & Learn: Now Hear This Wednesday, Januar...","Reader Submitted Body Fat Analysis Thursday, J...",Aging; Older people; Body fat; Bone density; H...,"Asbury Park Press; Asbury Park, N.J.",2013,"Dec 23, 2013",Your News,Gannett Media Corp,"Asbury Park, N.J.",...,NaN,English,News,1491141548,https://www.proquest.com/globalnewsfed/newspap...,2022-10-10,In addition to offering a full range of innova...,59.0,0.052499,"['pm', 'health education', 'road', 'meets', 'r..."
1897,S.A.D.: A discussion on seasonal affective dis...,None available.,Sponsored Content Have you ever felt as though...,NaN,"Asbury Park Press; Asbury Park, N.J.",2013,"Dec 13, 2013",Barnabas,Gannett Media Corp,"Asbury Park, N.J.",...,NaN,English,News,1467890009,https://www.proquest.com/globalnewsfed/newspap...,2017-11-20,Refreshments will be provided. Registration ca...,59.0,0.108229,"['pm', 'health education', 'road', 'meets', 'r..."
1948,Kimball Medical Center presents December Cente...,About Kimball Medical Center Kimball Medical C...,Reader Submitted Seasonal Affective Disorder W...,Aging; Older people; Hospitals; Health facilit...,"Asbury Park Press; Asbury Park, N.J.",2013,"Nov 21, 2013",Your News,Gannett Media Corp,"Asbury Park, N.J.",...,NaN,English,News,1491124450,https://www.proquest.com/globalnewsfed/newspap...,2017-11-21,In addition to offering a full range of innova...,59.0,0.091351,"['pm', 'health education', 'road', 'meets', 'r..."
1965,Meet Kimball Medical Center's health coaches a...,None available.,Reader Submitted Meet the Health Coaches from ...,NaN,"Asbury Park Press; Asbury Park, N.J.",2013,"Nov 10, 2013",Barnabas,Gannett Media Corp,"Asbury Park, N.J.",...,NaN,English,News,1449789501,https://www.proquest.com/globalnewsfed/newspap...,2017-11-20,You can also find out what wonderful events th...,59.0,0.079681,"['pm', 'health education', 'road', 'meets', 'r..."
2054,Health Digest,The 2013 Leadership Award was presented to Dr....,announcements NAMI Walk/Run NORMAL - The 2013 ...,NaN,"Pantagraph; Bloomington, Ill.\n\nFirst page: D.3",2013,"Sep 27, 2013",Life,Pantagraph Publishing Co.,"Bloomington, Ill.",...,26417634\n\ne-ISSN: 26417642,English,News,1445922929,https://www.proquest.com/globalnewsfed/newspap...,2017-11-20,Cancer society BLOOMINGTON - Ann Wheet of Bloo...,59.0,1.000000,"['pm', 'health education', 'road', 'meets', 'r..."
2086,September is Healthy Aging Month,"For more information and to register, call 1-8...",Sponsored Content Here are some upcoming event...,Aging; Chronic illnesses; Bone density; Osteop...,"Asbury Park Press; Asbury Park, N.J.",2013,"Sep 10, 2013",Barnabas,Gannett Media Corp,"Asbury Park, N.J.",...,NaN,English,News,1431395572,https://www.proquest.com/globalnewsfed/newspap...,2017-11-20,"To register, call 1-888-724-7123 Healthy Bones...",59.0,0.148018,"['pm', 'health education', 'road', 'meets', 'r..."
2377,ABUNDANT HEALTH EVENTS FREE ON PENINSULA,"The Peninsula Agency on Aging is sponsoring ""I...",It's rare that a week goes by when Peninsula h...,NaN,"Daily Press; Newport News, Va.\n\nFirst page: C.1",2013,"Mar 23, 2013\n\ncolumn: Health Notes",Life,"Tribune Publishing Company, LLC","Newport News, Va.",...,NaN,English,News,1318953918,https://www.proquest.com/globalnewsfed/newspap...,2017-11-19,Contact Prue Salasky at 757-247-4784 or email ...,59.0,1.000000,"['pm', 'health education', 'road', 'meets', 'r..."
2659,COMMUNITY NEWS,The National MS Society Connecticut Chapter's ...,FRIENDSHIP CLUBAT ADULT CENTER NEW BRITAIN -- ...,Multiple sclerosis; Adult day care; Libraries;...,"Hartford Courant; Hartford, Conn.\n\nFirst pag...",2014,"Oct 12, 2014",MY TOWNS,"Tribune Publishing Company, LLC","Hartford, Conn.",...,10474153,English,News,1610798718,https://www.proquest.com/newspapers/community-...,2014-10-13,The program is free. Call the library at 860-7...,59.0,1.000000,"['pm', 'health education', 'road', 'meets', 'r..."
2688,GUIDE TO A CLEAN BILL OF HEALTH: Multitude o...,Oct. 18: 9 a.m. to 1 p.m.: Concerned Citizens ...,"Each fall, health organizations organize event...",NaN,"Daily Press; Newport News, Va.\n\nFirst page: G.1",2014,"Sep 28, 2014",The Good Life,"Tribune Publishing Company, LLC","Newport News, Va.",...,NaN,English,News,1566023189,https://www.proquest.com/newspapers/guide-clea...,2017-11-22,Register online at https://nndvtbrownbagseries...,59.0,1.000000,"['pm', 'health education', 'road', 'meets', 'r..."
2904,Health events,The Dutchess County Department of Health will ...,Homemade Holistic Health Workshop Series -- Th...,Womens health; Recipes; Aging; Dance; Workshop...,"The Poughkeepsie Journal; Poughkeepsie, N.Y.\n...",2014,"May 18, 2014\n\ncolumn: HEALTH EVENTS",F,Gannett Media Corp,"Poughkeepsie, N.Y.",...,NaN,English,News,1538580085,https://www.proquest.com/newspapers/health-eve...,2017-11-21,Pre-registration not necessary. JFS caregiver ...,59.0,0.056705,"['pm', 'health education', 'road', 'meets', 'r..."
3026,Health Digest,None available.,Wellness classes Howard County General Hospita...,NaN,"The Baltimore Sun; Baltimore, Md.\n\nFirst pag...",2014,"Mar 9, 2014\n\ncolumn: health digest",LOCAL,"Tribune Publishing Company, LLC","Baltimore, Md.",...,19439504,English,News,1505479392,https://www.proquest.com/newspapers/health-dig...,2017-11-21,"Information: 410-792-0470, ext. 214. Bereaveme...",59.0,0.141102,"['pm', 'health education', 'road', 'meets', 'r..."
3267,Health and fitness Health & fitness,Toughman Cross Training: 6 a.m. Mondays and We...,Events that focus on physical and mental healt...,NaN,"Daily Herald; Arlington Heights, Ill.\n\nFirst...",2015,"Oct 29, 2015",NEIGHBOR,Daily Herald,"Arlington Heights, Ill.",...,NaN,English,News,1728125341,https://www.proquest.com/globalnewsfed/newspap...,2017-11-22,Complimentary Children's Yoga Classes: 3:30-4:...,59.0,0.141223,"['pm', 'health education', 'road', 'meets', 'r..."
3527,SeniorsPlus announces July classes,"Beginners Strength, Balance and Resistance Tra...",LEWISTON -- SeniorsPlus has announced its July...,NaN,"Sun Journal; Lewiston, Me.",2015,"Jun 24, 2015",Connections,Sun Journal,"Lewiston, Me.",...,NaN,English,News,1690938644,https://www.proquest.com/globalnewsfed/newspap...,2015-06-25,Maine Author Series will be held from 1-2:30 p...,59.0,0.101856,"['pm', 'health education', 'road', 'meets', 'r..."
3795,Aroostook hospital employees to wear red to ra...,A unique outdoor relay race and special commun...,"PRESQUE ISLE, Maine -- Employees at The Aroost...",Hospitals; Colleges & universities; Heart\n\nC...,"Bangor Daily News; Bangor, Me.",2015,"Feb 2, 2015",NaN,Bangor Daily News,"Bangor, Me.",...,08928738\n\ne-ISSN: 26437457,English,News,1650561821,https://www.proquest.com/globalnewsfed/newspap...,2017-11-22,"Gould Memorial campus on Academy Street, and a...",59.0,1.000000,"['pm', 'health education', 'road', 'meets', 'r..."
3838,in brief: Free walk-in cardiovascular clinic...,None available.,Bayhealth offers free weekly cardiovascular wa...,NaN,"Daily Times; Salisbury, Md.\n\nFirst page: 43",2015,"Jan 11, 2015",T,Gannett Media Corp,"Salisbury, Md.",...,NaN,English,News,1644375920,https://www.proquest.com/globalnewsfed/newspap...,2017-11-21,Registration is required. The classes are taug...,59.0,1.000000,"['pm', 'health education', 'road', 'meets', 'r..."
4148,YOUR HEALTH: CALENDAR,* GET A HEALTHY START TO SUMMER: CULINARY CLAS...,* WELLNESS INITIATIVE FOR SENIOR EDUCATION 6 W...,NaN,The Record; Hackensack\n\nFirst page: BL.3,2016,"Jun 28, 2016",BETTER LIVING,Gannett Media Corp,Hackensack,...,NaN,English,News,3193330343,https://www.proquest.com/globalnewsfed/newspap...,2025-04-22,* PREGNANCY/NEWBORN LOSS SUPPORT GROUP -- 7 p....,59.0,1.000000,"['pm', 'health education', 'road', 'meets', 'r..."
4330,Health and fitness Submit your events at daily...,Former NFL QB speaks on Mental Fitness: 6:30 p...,Events that focus on physical and mental healt...,NaN,"Daily Herald; Arlington Heights, Ill.\n\nFirst...",2016,"Mar 31, 2016",NEIGHBOR,Daily Herald,"Arlington Heights, Ill.",...,NaN,English,News,1777526207,https://www.proquest.com/globalnewsfed/newspa ...,2017-11-23,Former NFL QB speaks on Mental Fitness: 6:30 p...,59.0,1.000000,"['pm', 'health education', 'road', 'meets', 'r..."
4339,From yoga to child car seat checks.: Colling...,None available.,"Fancy a morning run? How about yoga, or pilate...",Yoga,"Philadelphia Inquirer; Philadelphia, Pa.\n\nFi...",2016,"Mar 25, 2016",SOUTH JERSEY & THE REGION,Philadelphia Media Network (Newspapers) LLC,"Philadelphia, Pa.",...,08856613,English,NEWSPAPER,1775745595,https://www.proquest.com/globalnewsfed/newspap...,2023-12-12,"For more information, visit the borough's Face...",59.0,0.095283,"['pm', 'health education', 'road', 'meets', 'r..."
4764,health briefs: Jazz organization donates $15...,None available.,Producers of the Rehoboth Beach Jazz Festival ...,Cancer; Music festivals\n\nCompany / organizat...,"The News Journal; Wilmington, Del.\n\nFirst pa...",2017,"Aug 10, 2017",News,Gannett Media Corp,"Wilmington, Del.",...,NaN,English,News,1927789482,https://www.proquest.com/globalnewsfed/newspap...,2017-08-11,Contact Meredith Newman at (302) 324-2386 or a...,59.0,1.000000,"['pm', 'health education', 'road', 'meets', 'r..."
4848,Health and fitness calendar Health and fitness...,"""In Your Hands: How to Be Your Own Health Advo...","Chair Yoga for Seniors: 2:30 p.m. Monday, Apri...",Families & family life; Meditation; Public lib...,"Daily Herald; Arlington Heights, Ill.\n\nFirst...",2017,"Apr 10, 2017",Health Fitness,Daily Herald,"Arlington Heights, Ill.",...,NaN,English,News,1886106639,https://www.proquest.com/globalnewsfed/newspap...,2017-11-24,Appointments preferred. Walk-ins welcome. Phot...,59.0,1.000000,"['pm', 'health education', 'road', 'meets', 'r..."
4976,Health and fitness calendar,"Elegantly combining nature, art and reading, T...",Transform Your Health with the Power of Essent...,Fund raising; Families & family life; Meditati...,"Daily Herald; Arlington Heights, Ill.\n\nFirst...",2017,"Mar 27, 2017",Health Fitness,Daily Herald,"Arlington Heights, Ill.",...,NaN,English,News,1881746356,https://www.proquest.com/globalnewsfed/newspap...,2023-10-09,Students with a valid ID can participate for $...,59.0,0.070220,"['pm', 'health education', 'road', 'meets', 'r..."
5019,Health and fitness,None available.,Events that focus on physical and mental healt...,Support groups\n\nCompany / organization: Name...,"Daily Herald; Arlington Heights, Ill.\n\nFirst...",2017,"Aug 3, 2017",NEIGHBOR,Daily Herald,"Arlington Heights, Ill.",...,NaN,English,News,1925432146,https://www.proquest.com/globalnewsfed/newspap...,2017-11-24,The support group will allow you to meet other...,59.0,1.000000,"['pm', 'health education', 'road', 'meets', 'r..."

***
Ad topic
***

In [116]:
df = remove_topic(df,59,[])

The orig length:10216 -> cropped: 10171

#### Topic 72

In [117]:
df[df['topic']==72]

,Title,Abstract,Full text,Subject,Publication title,Publication year,Publication date,Section,Publisher,Place of publication,...,ISSN,Language of publication,Document type,ProQuest document ID,Document URL,Last updated,last,topic,topic_prob,topic_keywords
291,INCORPORATIONS,"Noble Auto Body Shop, 06/02/10, Solomon Olubiy...",The following area businesses filed incorporat...,Condominiums; Aging,"Wisconsin State Journal; Madison, Wis.\n\nFirs...",2010,"Jul 8, 2010",BUSINESS,"Madison Newspapers, Inc.","Madison, Wis.",...,0749405X,English,News,596226566,https://www.proquest.com/globalnewsfed/newspap...,2017-11-17,The following area businesses filed incorporat...,72.0,1.000000,"['june', 'pm', 'county', 'road', 'monthly', 'r..."
396,Arts Briefs,Based on several popular Dr. Seuss stories inc...,Henderson County YouTheatre Camp Registration ...,NaN,"Times News; Hendersonville, N.C.",2010,"May 3, 2010",NaN,Halifax Media Group,"Hendersonville, N.C.",...,10422323,English,News,250013111,https://www.proquest.com/glob alnewsfed/newspa...,2012-11-02,Dance admission is $20. Info: www.wcca.net or ...,72.0,1.000000,"['june', 'pm', 'county', 'road', 'monthly', 'r..."
398,Henderson County,Based on several popular Dr. Seuss stories inc...,Registration is open for YouTheatre summer cam...,NaN,"Times News; Hendersonville, N.C.",2010,"May 2, 2010",NaN,Halifax Media Group,"Hendersonville, N.C.",...,10422323,English,News,231191186,https://www.proquest.com/globalnewsfed/newspap...,2012-11-02,"Dinner and dance tickets are $35, if purchased...",72.0,0.100961,"['june', 'pm', 'county', 'road', 'monthly', 'r..."
635,In the Berkshires: Boys Club to host ice skati...,"At 5:30 p.m., in Building #1 at Mass MoCA, Wil...","Tuesday November 15, 2011 Pittsfield: Boys Clu...",Girls clubs; Garden clubs; Children & youth; S...,"The Berkshire Eagle; Pittsfield, Mass.",2011,"Nov 14, 2011",News,"New England Newspapers, Inc.","Pittsfield, Mass.",...,08958793,English,News,903813665,https://www.proquest.com/globalnewsfed/newspap...,2011-11-16,Registration: email chwalliance@gmail.com no l...,72.0,0.050045,"['june', 'pm', 'county', 'road', 'monthly', 'r..."
675,Council candidates to drop in at Laurel Park T...,Four Seasons Rotary Club will join with Appleb...,Laurel Park--Council candidates to drop in at ...,NaN,"Times News; Hendersonville, N.C.",2011,"Oct 24, 2011",NaN,Halifax Media Group,"Hendersonville, N.C.",...,10422323,English,News,900431780,https://www.proquest.com/globalnewsfed/newspap...,2012-11-02,The Great Life Series is presented by Great Li...,72.0,0.143757,"['june', 'pm', 'county', 'road', 'monthly', 'r..."
718,Community Calendar: Special Events Clubs Health,None available.,FUNDRAISER: Trinity Reformed United Church of ...,NaN,Intelligencer Journal / Lancaster New Era; Lan...,2011,"Oct 6, 2011\n\ncolumn: Community Calendar",B,LNP Media Group Inc.,"Lancaster, Pa.",...,NaN,English,News,896471927,https://www.proquest.com/globalnewsfed/newspap...,2017-11-18,Community Calendar runs as space is available....,72.0,0.034556,"['june', 'pm', 'county', 'road', 'monthly', 'r..."
803,Senior centers plan special events in September,The Lexington Senior Center was established in...,The Davidson County Department of Senior Servi...,NaN,"The Dispatch; Lexington, N.C.",2011,"Sep 2, 2011",NaN,Halifax Media Group,"Lexington, N.C.",...,NaN,English,News,887259342,https://www.proquest.com/globalnewsfed/newspap...,2012-10-12,The Thomasville Senior Center opened its doors...,72.0,0.076241,"['june', 'pm', 'county', 'road', 'monthly', 'r..."
863,Globe North Community briefing,None available.,Andover MORE DEER HUNTING - The Board of Selec...,NaN,"Boston Globe; Boston, Mass.",2011,"Aug 7, 2011",North,"Boston Globe Media Partners, LLC","Boston, Mass.",...,07431791,English,News,881494900,https://www.proquest.com/globalnewsfed/newspap...,2017-11-18,The hours are 7 to 11 p.m. on Friday and Satur...,72.0,0.195929,"['june', 'pm', 'county', 'road', 'monthly', 'r..."
1138,Washoe government meetings,Consent for county parks to seek qualified con...,"WASHOE COUNTY COMMISSION 9 a.m. Tuesday, commi...",Counties,"Reno Gazette - Journal; Reno, Nev.",2011,"Feb 21, 2011",NEWS,Gannett Media Corp,"Reno, Nev.",...,NaN,English,News,852935965,https://www.proquest.com/globalnewsfed/newspap...,2017-11-17,"Dave Asher, of LiveLocal RenoSparks, will disc...",72.0,0.143907,"['june', 'pm', 'county', 'road', 'monthly', 'r..."
1339,Health fair with screenings offered in Wilmington,None available.,Wilmington Senior Center invites the community...,NaN,"The News Journal; Wilmington, Del.",2012,"Oct 15, 2012\n\ncolumn: Local",Health,Gannett Media Corp,"Wilmington, Del.",...,NaN,English,News,1112740658,https://www.proquest.com/globalnewsfed/newspap...,2013-01-04,"The center's Village Thrift Shop, located at 1...",72.0,0.060651,"['june', 'pm', 'county', 'road', 'monthly', 'r..."
1515,Monroe collection begins for school supplies,Many churches also are participating. Backpack...,MONROE -- The Salvation Army of Monroe County ...,NaN,"The Blade; Toledo, Ohio",2012,"Jul 30, 2012",Education,The Blade,"Toledo, Ohio",...,25789953\n\ne-ISSN: 25789961,English,News,1039592170,https://www.proquest.com/globalnewsfed/newspap...,2012-09-15,Backpacks are to be distributed Aug. 17 from 4...,72.0,0.047725,"['june', 'pm', 'county', 'road', 'monthly', 'r..."
1526,"Northside: North Fulton, Cherokee, Forsyth",According to the state Department of Transport...,Culvert work to close Roswell street till Sept...,Holiday decorations; Cities; Irrigation\n\nLoc...,"The Atlanta Journal - Constitution; Atlanta, Ga.",2012,"Jul 21, 2012",METRO,"Atlanta Journal Constitution, LLC","Atlanta, Ga.",...,15397459,NaN,News,1027168160,https://www.proquest.com/globalnewsfed/newspap...,2017-11-19,MARK WOOLSEY FOR THE AJC Holiday decoration sa...,72.0,1.000000,"['june', 'pm', 'county', 'road', 'monthly', 'r..."
2062,Community News: Warm Springs,Shelly Lam of King's Daughters Community Healt...,Gallery to present festival: Warm Springs Gall...,Aging; Senior citizen centers; Painting\n\nCom...,"The News Leader; Staunton, Va.\n\nFirst page: 4",2013,"Sep 24, 2013",A,Gannett Media Corp,"Staunton, Va.",...,NaN,English,News,1439076668,https://www.proquest.com/globalnewsfed/newspap...,2017-11-20,Potential candidates may make an appointment t...,72.0,1.000000,"['june', 'pm', 'county', 'road', 'monthly', 'r..."
2154,Dickson County business licenses,"Air Inc.; 1818 Williamson Branch, Vanleer; Jun...",Business licenses in Dickson County for June. ...,Automobile sales; Catalytic converters; Roads ...,"The Tennessean; Nashville, Tenn.\n\nFirst page: 7",2013,"Aug 2, 2013",A,Gannett Media Corp,"Nashville, Tenn.",...,10536590,English,News,1416769969,https://www.proquest.com/globalnewsfed/newspap...,2021-02-01,Information is listed in the following order p...,72.0,0.151083,"['june', 'pm', 'county', 'road', 'monthly', 'r..."
2256,"Northside: North Fulton, Cherokee, Forsyth",Forsyth schools poised to adopt $282M budget T...,Forsyth schools poised to adopt $282M budget T...,Electric vehicles; Aging; School boards; Budge...,"The Atlanta Journal - Constitution; Atlanta, Ga.",2013,"Jun 11, 2013",METRO,"Atlanta Journal Constitution, LLC","Atlanta, Ga.",...,15397459,English,News,1366224688,https://www.proquest.com/globalnewsfed/newspap...,2017-11-20,Officials say the entire project is set for a ...,72.0,0.129181,"['june', 'pm', 'county', 'road', 'monthly', 'r..."
2261,Community Calendar,None available.,nGRAVE CONCERN: Grave Concern will host a ceme...,NaN,Intelligencer Journal / Lancaster New Era; Lan...,2013,"Jun 18, 2013\n\ncolumn: Community Calendar",B,LNP Media Group Inc.,"Lancaster, Pa.",...,NaN,English,News,1368789039,https://www.proquest.com/globalnewsfed/newspap...,2017-11-20,NUTRITIONAL SESSION: Juniper Village of Mount ...,72.0,0.346549,"['june', 'pm', 'county', 'road', 'monthly', 'r..."
2262,Northside: Northside: Acworth woman pulled fro...,MARK WOOLSEY FOR THE AJC Johns Creek seeks art...,A 46-year-old Acworth woman who was pulled fro...,Real estate agents & brokers; Awards & honors;...,"The Atlanta Journal - Constitution; Atlanta, Ga.",2013,"Jun 7, 2013",METRO,"Atlanta Journal Constitution, LLC","Atlanta, Ga.",...,15397459,English,News,1365599367,https://www.proquest.com/globalnewsfed/newspap...,2017-11-20,"Excluded are motor oil, antifreeze, auto batte...",72.0,1.000000,"['june', 'pm', 'county', 'road', 'monthly', 'r..."
2291,"News Briefs For Wednesday, May 23, 2013",COLONIAL HEIGHTS - Dunlop House Assisted Livin...,Advisory committee to meet DINWIDDIE - The Spe...,NaN,"The Progress - Index; Petersburg, Va.",2013,"May 23, 2013\n\nDateline: Petersburg, VA",News,"GateHouse Media, Inc.","Petersburg, Va.",...,NaN,English,News,1354370629,https://www.proquest.com/globalnewsfed/newspap...,2016-05-14,Anyone interested in attending may contact Roy...,72.0,1.000000,"['june', 'pm', 'county', 'road', 'monthly', 'r..."
2366,Newly installed medicine drop box unveiled,PARKER Center for Healthy Aging collaborated w...,"Perth Amboy Mayor Wilda Diaz, Police Chief Ben...",Aging; Pain management; Exercise; Medicine; Ph...,"Courier - News; Bridgewater, N.J.\n\nFirst pag...",2013,"Apr 2, 2013\n\ncolumn: Heartbeats",B,Gannett Media Corp,"Bridgewater, N.J.",...,08958785,English,News,1323394938,https://www.proquest.com/globalnewsfed/newspap...,2017-11-20,"For more information on SAGE Eldercare, call 9...",72.0,0.057723,"['june', 'pm', 'county', 'road', 'monthly', 'r..."
2834,Briefly,COLONIAL HEIGHTS - Dunlop House Assisted Livin...,Auxiliary hosting yard sale Saturday HOPEWELL ...,NaN,"The Progress - Index; Petersburg, Va.",2014,"Jun 26, 2014\n\nDateline: Petersburg, VA",News,"GateHouse Media, Inc.","Petersburg, Va.",...,NaN,English,News,1540518750,https://www.proquest.com/newspapers/briefly/do...,2016-05-14,Learn how to ensure their wishes are carried o...,72.0,1.000000,"['june', 'pm', 'county', 'road', 'monthly', 'r..."
3160,"Local News Briefs For Monday, Jan. 6, 2014",COLONIAL HEIGHTS - Dunlop House Assisted Livin...,Health & Wellness Fair HOPEWELL - The Sunlight...,NaN,"The Progress - Index; Petersburg, Va.",2014,"Jan 6, 2014\n\nDateline: Petersburg, VA",News,"GateHouse Media, Inc.","Petersburg, Va.",...,NaN,English,News,1474365520,https://www.proquest.com/newspapers/local-news...,2016-05-14,Basic and intermediate computer classes are of...,72.0,1.000000,"['june', 'pm', 'county', 'road', 'monthly', 'r..."
3558,Upcoming events: Monday,Women Supporting Women Veterans will hold its ...,Genealogy for beginners -- The Brighton Distri...,Genealogy; Special Olympics; Blood & organ don...,"Livingston County Daily Press & Argus; Howell,...",2015,"Jun 5, 2015",C,Gannett Media Corp,"Howell, Mich.",...,21505667\n\ne-ISSN: 21505675,English,News,1686110367,https://www.proquest.com/globalnewsfed/newspap...,2017-11-22,Don't miss this delightful family-friendly pro...,72.0,1.000000,"['june', 'pm', 'county', 'road', 'monthly', 'r..."
3564,BULLETIN BOARD,"The Alzheimer's Association, West Virginia Cha...",Montessori picnic Mountaineer Montessori Schoo...,NaN,"The Charleston Gazette; Charleston, W.V.\n\nFi...",2015,"Jun 2, 2015",NaN,Charleston Newspapers,"Charleston, W.V.",...,NaN,English,News,1685374256,https://www.proquest.com/globalnewsfed/newspap...,2017-11-22,"For information about CCL, visit www.citizensc...",72.0,0.033091,"['june', 'pm', 'county', 'road', 'monthly', 'r..."
3642,Lakeshore Update: Dinner theater performance...,Items being auctioned include various confisca...,The Palace of Reifs Mills Dinner Event Theatre...,Auctions; Blood & organ donations,"Herald Times Reporter; Manitowoc, Wis.\n\nFirs...",2015,"Apr 19, 2015",A,Gannett Media Corp,"Manitowoc, Wis.",...,NaN,English,News,1674086737,https://www.proquest.com/globalnewsfed/newspap...,2017-11-22,"To make an appointment, visit redcrossblood.or...",72.0,0.037185,"['june', 'pm', 'county', 'road', 'monthly', 'r..."
4333,Spring bouquet of new programming in Ryde,For more information about our up-coming event...,2016 is shaping up to be a very busy and produ...,NaN,"Gravenhurst Banner; Gravenhurst, Ont.\n\nFirst...",2016,"Mar 30, 2016\n\nDateline: 20160330",Opinion,"Torstar Syndication Services, a Division of To...","Gravenhurst, Ont.",...,NaN,English,News,1777417378,https://www.proquest.com/globalnewsfed/newspap...,2016-04-01,For more information about our up-coming event...,72.0,0.139592,"['june', 'pm', 'county', 'road', 'monthly', 'r..."
5428,"DeKalb: Decatur, Dunwoody, Stone Mountain and ...",None available.,"WorkSource DeKalb will host its ""Workforce Wed...",Libraries; Workforce; Sales taxes; Keyboards; ...,"The Atlanta Journal - Constitution; Atlanta, G...",2018,"Jul 18, 2018",METRO,"Atlanta Journal Constitution, LLC","Atlanta, Ga.",...,15397459,English,News,2071091714,https://www.proquest.com/globalnewsfed/newspap...,2018-07-18,Perform some basic BioBus experiments. Each se...,72.0,1.000000,"['june', 'pm', 'county', 'road', 'monthly', 'r..."
5907,Port Clinton High School holding annual 'Spoo ...,None available.,PORT CLINTON - Port Clinton High School studen...,Secondary schools; Wildlife conservation\n\nLo...,"The News - Messenger; Fremont, Ohio\n\nFirst p...",2019,"Oct 22, 2019\n\ncolumn: News briefs",News,Gannett Media Corp,"Fremont, Ohio",...,NaN,English,News,2307312995,https://www.proquest.com/ globalnewsfed/newspa...,2019-10-22,gov/wildlife/education registration. Trained p...,72.0,1.000000,"['june', 'pm', 'county', 'road', 'monthly', 'r..."
6161,Manitowoc history detailed in new book,None available.,Manitowoc River History: Manitowoc Rapids-Lake...,Rivers; Books; Museums; Nuclear power plants\n...,"Herald Times Reporter; Manitowoc, Wis.\n\nFirs...",2019,"Jun 7, 2019\n\ncolumn: local briefs",News,Gannett Media Corp,"Manitowoc, Wis.",...,NaN,English,News,2236082554,https://www.proquest.com/globalnewsfed/newspap...,2022-01-26,"329, or email fvmarketing@felicianvillage.org....",72.0,1.000000,"['june', 'pm', 'county', 'road', 'monthly', 'r..."
6363,Borderland,None available.,Lucas County real estate taxes due Friday. Th...,Black history; Aging; Property taxes\n\nPeople...,"The Blade; Toledo, Ohio\n\nFirst page: B.1",2019,"Feb 7, 2019",SECOND NEWS,The Blade,"Toledo, Ohio",...,25789953\n\ne-ISSN: 25789961,English,News,2188096101,https://www.proquest.com/globalnewsfed/newspap...,2019-10-16,"As part of that series, journalist Shaun King ...",72.0,1.000000,"['june', 'pm', 'county', 'road', 'monthly', 'r..."
6418,Abbotsford seniors' group delivers surprise br...,None available.,Abbotsford Association for Healthy Aging (AAHA...,Coronaviruses; COVID-19\n\nLocation: Abbotsfor...,"The News; Abbotsford, B.C.",2020,"Dec 25, 2020",Community,Black Press Group Ltd.,"Abbotsford, B.C.",...,08393648,English,News,2472671183,https://www.proquest.com/newspapers/abbotsford...,2020-12-26,The deliveries took place to ensure that senio...,72.0,0.041145,"['june', 'pm', 'county', 'road', 'monthly', 'r..."
6431,"Community briefs for Thursday, Dec. 17",None available.,Salvation Army to hold Kettle Blitz Day LEWIST...,Age; Aging; Christmas\n\nLocation: Maine\n\nCo...,"Sun Journal; Lewiston, Me.",2020,"Dec 17, 2020",Connections,Sun Journal,"Lewiston, Me.",...,NaN,English,News,2470818692,https://www.proquest.com/newspapers/community-...,2020-12-18,Contact Jess Maurer at jmaurer@mainecouncilona...,72.0,1.000000,"['june', 'pm', 'county', 'road', 'monthly', 'r..."
6512,ManorCare Health Services Celebrates National ...,None available.,"In 1954, the United States designated November...",Health services\n\nLocation: United States--US,"Daily Herald; Arlington Heights, Ill.",2020,"Oct 31, 2020",Submitted Content,Daily Herald,"Arlington Heights, Ill.",...,NaN,English,News,245640 2791,https://www.proquest.com/newspapers/manorcare-...,2020-11-02,"WHAT: Veteran’s Day Celebration WHEN: Nov. 11,...",72.0,0.101258,"['june', 'pm', 'county', 'road', 'monthly', 'r..."
6866,Auditor's office plans benefit fundraiser,None available.,MARION – The Marion County Auditor's Office wi...,Aging\n\nLocation: Ohio\n\nCompany / organizat...,"Marion Star; Marion, Ohio\n\nFirst page: A.3",2020,"Mar 6, 2020\n\ncolumn: Local news briefs",News,Gannett Media Corp,"Marion, Ohio",...,NaN,English,News,2371587663,https://www.proquest.com/newspapers/auditors-o...,2020-03-06,Reservations are due by March 6 for this free ...,72.0,1.000000,"['june', 'pm', 'county', 'road', 'monthly', 'r..."
7043,Community Calendar,None available.,"Wednesday, Dec. 8 FORT FAIRFIELD: Senior commo...",Traditions; Blood & organ donations; Cocoa; Ag...,"Bangor Daily News; Bangor, Me.",2021,"Dec 6, 2021",NaN,Bangor Daily News,"Bangor, Me.",...,08928738\n\ne-ISSN: 26437457,English,News,2607324294,https://www.proquest.com/newspapers/community-...,2021-12-07,"FMI: Cindy, 435-6532, or Dawn, 227-5017. Tuesd...",72.0,0.035145,"['june', 'pm', 'county', 'road', 'monthly', 'r..."
8270,Age-Friendly Community Initiative,None available.,AFCI Perhaps you or a family member or friend ...,Older people\n\nLocation: United States--US; M...,"Sun Journal; Lewiston, Me.",2022,"Nov 3, 2022",NaN,Sun Journal,"Lewiston, Me.",...,NaN,English,News,2731619704,https://www.proquest.com/globalnewsfed/newspap...,2022-11-04,Send questions/comments to the editors. « Prev...,72.0,0.180868,"['june', 'pm', 'county', 'road', 'monthly', 'r..."
8486,Board of Elections announces post-election mee...,None available.,The Crawford County Board of Elections will me...,Soybeans; Aging; Elections\n\nLocation: United...,"Telegraph - Forum; Bucyrus, Ohio\n\nFirst page...",2023,"Nov 13, 2023\n\ncolumn: In brief",News,Gannett Media Corp,"Bucyrus, Ohio",...,NaN,English,News,2889136013,https://www.proquest.com/newspapers/board-elec...,2023-11-13,Grants are being distributed to counties to bo...,72.0,1.000000,"['june', 'pm', 'county', 'road', 'monthly', 'r..."
9396,Dub. Co. July vendor list,None available.,"Vendor Publication Report Dubuque County, IA 0...",Autopsies; Meetings; Cremation; Funeral homes;...,"Telegraph - Herald; Dubuque, Iowa\n\nFirst pag...",2024,"Aug 14, 2024",NaN,Telegraph Herald,"Dubuque, Iowa",...,1041293X,English,News,3092940170,https://www.proquest.com/globalnewsfed/newspap...,2024-08-15,"Vendor Publication Report Dubuque County, IA 0...",72.0,1.000000,"['june', 'pm', 'county', 'road', 'monthly', 'r..."
9839,Seniors Outreach News,None available.,"SENIORS OUTREACH LOCAL MISSION: ""To enhance th...",Meals; Shopping; Outreach services; Older peop...,"The Capital; Three Hills, Alta.\n\nFirst page:...",2025,"Mar 12, 2025",News,Postmedia Network Inc.,"Three Hills, Alta.",...,NaN,English,News,3177005978,https://www.proquest.com/globalnewsfed/newspap...,2025-03-14,"Kneehill South (Acme, Carbon, Linden, Swalwell...",72.0,0.088651,"['june', 'pm', 'county', 'road', 'monthly', 'r..."
9841,June busy for Men's Shed members,None available.,June has proven to be a very busy month for Pe...,NaN,Wiarton Echo; Wiarton\n\nFirst page: A.2,2025,"Jul 8, 2025",Local,Postmedia Network Inc.,Wiarton,...,08323402,English,News,3228161013,https://www.proquest.com/globalnewsfed/newspap...,2025-07-09,"""Somewhere to Go. Something to Do. Someone to ...",72.0,0.035842,"['june', 'pm', 'county', 'road', 'monthly', 'r..."

***
Ad topic
***

In [120]:
df = remove_topic(df,72,[])

The orig length:10171 -> cropped: 10132

# Saving dataframe

In [129]:
df.to_csv(PROQUEST_PROCESSED_DIR / 'df_v4_cleaned.csv',index=False)