# Preparation

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from NLP import *

guardian_out = pd.read_csv('../GuardianAPI/guardian_cleared1_topicsAttached.csv')
guardian_links = pd.read_csv('../GuardianAPI/guardian_data_2010_2025_links.csv')

/home/iskender/anaconda3/envs/bertopic-env/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Analysis

### Tag Analysis

`import re

keywords = ["ageing", "life", "health", "wellbeing","nutrition", "aging", "longevity", "healthy aging", "anti-aging", "anti ageing"]
<br>
pattern = "|".join([kw.replace(" ", r"\s+") for kw in keywords])

mask = guardian['tags'].str.contains(pattern, case=False, na=False)
<br>
guardian_age = guardian[mask].reset_index(drop=True)

print(f"Kept {len(guardian_age)} of {len(guardian)} articles related to ageing.")
***
Kept 1303 of 5498 articles related to ageing.
***
guardian_age.to_csv('../GuardianAPI/guardian_cleared1.csv')`

### BERTopic

model, topic_info, guardian_out = analyze_bertopic(guardian, v_min_df=2, v_max_df=0.60,text_col="bodyText",top_n_words=30,
                                     save_csv=None)

In [27]:
def full_keyword_getter(df):
    # 1. Only keep the rows where we actually assigned keywords
    df_map = df.dropna(subset=["topic_keywords"])
    
    # 2. Drop duplicates so each topic ID appears exactly once
    df_map = df_map.drop_duplicates(subset=["topic"])
    
    # 3. Build a mapping: topic_id → keyword list
    topic_to_keywords = (
        df_map.set_index("topic")["topic_keywords"]
              .astype(object)               # ensure lists aren’t cast to strings
              .to_dict()
    )
    
    # 4. Print them in ID order
    for tid, kws in sorted(topic_to_keywords.items()):
        print(f"{tid} → {kws}")
full_keyword_getter(guardian_out)

-1.0 → ['pfas', 'housing', 'spa', 'biobank', 'advent', 'calendar', 'public health', '23andme', 'epa', 'supplements', 'ink', 'calendars', 'social care', 'dogs', 'alzheimer', 'menopause', 'stratford', 'neuroticism', 'loneliness', 'tattoo', 'christmas tree', 'silicon valley', 'silicon', 'attia', 'people dementia', 'employees', 'christmas trees', 'obesity', 'motherhood', 'pessimism']
0.0 → ['pension', 'retirement', 'mice', 'centenarians', 'pensions', 'state pension', 'workout', 'cognitive', 'genes', 'social care', 'physical activity', 'senescent', 'calment', 'abortion', 'pension age', 'record', 'public health', 'dna', 'age related', 'senescent cells', 'ageing process', 'anti ageing', 'living longer', 'people aged', 'plasma', 'alzheimer', 'olds', 'year olds', 'mobility', 'amendment']
1.0 → ['shirt', 'clothing', 'jeans', 'leather', 'wardrobe', 'boots', 'fabric', 'wool', 'trousers', 'vogue', 'dresses', 'designs', 'designers', 'shirts', 'jacket', 'wore', 'cashmere', 'burton', 'oscar', 'socks', 'secondhand', 'mulberry', 'dolly', 'skinny', 'fabrics', 'parton', 'skirt', 'garment', 'catwalk', 'garments']
2.0 → ['makeup', 'serum', 'skincare', 'anti ageing', 'glow', 'nail', 'gel', 'concealer', 'lashes', 'lip', '30ml', 'creams', 'facial', 'moisturiser', 'balm', 'vitamin', 'wrinkles', 'brow', 'lipstick', '50ml', 'sunscreen', 'retinol', 'mascara', 'cleansing', 'botox', 'powder', 'moisturising', 'polish', 'cleanser', 'scent']
3.0 → ['fasting', 'obesity', 'diets', 'calories', 'mushrooms', 'obese', 'longo', 'weight loss', 'overweight', 'intake', 'junk', 'junk food', 'vitamin', 'tofu', 'resveratrol', 'dietary', 'patel', 'yoghurt', 'type diabetes', 'hockney', 'eating disorders', 'dairy', 'vitamins', 'nutrients', 'calorie', 'glp', 'dieting', 'compounds', 'creme', 'weight gain']
4.0 → ['elephants', 'conservation', 'bat', 'bats', 'ivory', 'whales', 'velvet', 'populations', 'nest', 'whale', 'ants', 'attenborough', 'temperate', 'habitat', 'endangered', 'david attenborough', 'crabs', 'mouse', 'breeding', 'arctic', 'mimicry', 'crab', 'turtles', 'tunnel', 'predators', 'dolphins', 'nestling', 'chernobyl', 'wolves', 'national park']
5.0 → ['divorce', 'romantic', 'marry', 'sonya', 'jackie', 'maureen', 'romance', 'trish', 'toby', 'gay', 'phil', 'divorced', 'marriages', 'emmy', 'mike', 'getting married', 'ted', 'weddings', 'pamela', 'pete', 'vegas', 'brad', 'pregnant', 'kathleen', 'fiona', 'boyfriend', 'adrian', 'dating', 'friendships', 'christ']
6.0 → ['fridge', 'blender', 'sauce', 'bowl', 'pesto', 'flour', 'espresso', 'chef', 'stove', 'recipe', 'machines', 'marmalade', 'seeds', 'mixer', 'stir', 'dough', 'flavour', 'tsp', 'gas', 'ketchup', 'cooked', 'chilli', 'grill', 'boil', 'recipes', 'baking', 'noodles', 'chopped', 'warranty', 'bake']
7.0 → ['nsw', 'covid 19', 'labor', 'vaccine', 'australians', 'queensland', 'coronavirus', 'federal', 'court', 'premier', 'reports', 'election', 'abc', 'yesterday', 'liberal', 'israel', 'dawson', 'referendum', 'virus', 'coalition', 'tuesday', 'vaccination', 'vaccinated', 'variant', 'indigenous', 'opposition', 'quarantine', 'morrison', 'inquiry', 'hancock']
8.0 → ['flower', 'butterflies', 'roses', 'planting', 'foliage', 'blooms', 'flowering', 'orchard', 'butterfly', 'hirst', 'cuttings', 'shrubs', 'compost', 'bulbs', 'iris', 'edible', 'varieties', 'woodland', 'stems', 'oak', 'orchards', 'watering', 'shrub', 'planted', 'chelsea', 'potter', 'container', 'bloom', 'bailey', 'potatoes']
9.0 → ['chemotherapy', 'screening', 'oncologist', 'prostate', 'diagnosis', 'remission', 'prostate cancer', 'long covid', 'breast cancer', 'nursing', 'syphilis', 'quality life', 'toxicity', 'neurologist', 'cancer patients', 'surgeon', 'eczema', 'nursing home', 'cancers', 'palliative', 'complications', 'organ', 'mom', 'transplant', 'spine', 'craig', 'kidney', 'relieved', 'cognitive', 'illnesses']
10.0 → ['productivity', 'insomnia', 'beds', 'caffeine', 'nap', 'hours sleep', 'boredom', 'bedtime', 'cognitive', 'awake', 'seven hours', 'coach', 'bored', 'sleep night', 'working home', 'saunders', 'night sleep', 'microdosing', 'waking', 'dopamine', 'physical activity', 'scrolling', 'neuroscience', 'duration', 'hormone', 'mindfulness', 'creativity', 'time day', 'cup coffee', 'study suggests']
11.0 → ['wines', 'vodka', 'mid range', 'sparkling', 'splurge', 'price range', 'madeira', 'flavours', 'socks', 'reds', 'jeans', 'cocktail', 'craft', 'red wine', 'grape', 'linen', 'grapes', 'olive oil', 'shirt', 'bedding', 'citrus', 'pint', 'cocktails', 'producers', 'high quality', 'moisturiser', 'durability', 'premium', 'syrup', 'portugal']

#### Cleaning topic-0

In [95]:
topic0_df = guardian_out[guardian_out['topic'] == 0]

In [98]:
model, topic_info, topic0_out = analyze_bertopic(topic0_df, v_min_df=1, v_max_df=0.85,text_col="bodyText",top_n_words=30,
                                     save_csv=None)

2025-07-25 10:11:32,604 - BERTopic - Embedding - Transforming documents to embeddings.
Batches: 100%|███████████████████████████████████████████████████████| 15/15 [02:01<00:00,  8.12s/it]
2025-07-25 10:13:34,458 - BERTopic - Embedding - Completed ✓
2025-07-25 10:13:34,459 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2025-07-25 10:13:34,707 - BERTopic - Dimensionality - Completed ✓
2025-07-25 10:13:34,708 - BERTopic - Cluster - Start clustering the reduced embeddings
2025-07-25 10:13:34,720 - BERTopic - Cluster - Completed ✓
2025-07-25 10:13:34,721 - BERTopic - Representation - Extracting topics using c-TF-IDF for topic reduction.
2025-07-25 10:13:35,348 - BERTopic - Representation - Completed ✓
2025-07-25 10:13:35,349 - BERTopic - Topic reduction - Reducing number of topics
2025-07-25 10:13:35,352 - BERTopic - Representation - Fine-tuning topics using representation models.
2025-07-25 10:13:35,968 - BERTopic - Representation - Completed ✓
2025-07-25 10:13:35,970 - BERTopic - Topic reduction - Reduced number of topics from 4 to 4

In [99]:
topic_info

,Topic,Count,Name,Representation,Representative_Docs
0,0,335,0_pension_cells_died_mice,"[pension, cells, died, mice, humans, told, point, centen...",[Tech entrepreneur Bryan Johnson is talking about 16th-c...
1,1,65,1_muscle_yoga_gym_workout,"[muscle, yoga, gym, workout, strength, muscles, balance,...",[When Baz Luhrmann called the body “the greatest instrum...
2,2,55,2_labour_abortion_party_private,"[labour, abortion, party, private, political, amendment,...",[Lords reform A bill to reform the House of Lords has be...
3,3,14,3_sleep_brain health_screening_screenings,"[sleep, brain health, screening, screenings, cognitive d...","[People in their 50s can be prone to a “vicious cycle”, ..."

In [164]:
topic0_out.shape[0]

469

In [28]:
full_keyword_getter(topic0_out)

-1.0 → ['italy', 'moalem', 'bolzano', 'cyclists', 'births', 'royal mail', 'mail', 'sex', 'chromosome', 'bikes', 'documentary', 'royal', 'province', 'immune', 'survival', 'genetic', 'birth rate', 'humanity', 'sardinia', 'raf', 'military', 'infection', 'walsh', 'austad', 'males', 'maternity', 'immortality', 'benefits', 'drivers', 'girls']
0.0 → ['cells', 'mice', 'humans', 'lifespan', 'scientists', 'data', 'oldest', 'drug', 'diet', 'diseases', 'researchers', 'cell', 'drugs', 'anti', 'centenarians', 'average', 'company', 'senescent', 'based', 'eat', 'results', 'genes', 'patients', 'johnson', 'anti ageing', 'genetic', 'senescent cells', 'exercise', 'scientific', 'effect']
1.0 → ['pension', 'retirement', 'uk', 'older people', 'england', 'state pension', '65', 'society', 'pensions', '60', 'income', 'average', 'poor', 'pension age', 'increase', 'education', 'workers', 'grandchildren', 'elderly', 'expect', 'younger', 'jobs', 'areas', 'asked', '85', 'housing', 'paid', 'calment', 'generation', 'ageism']
2.0 → ['exercise', 'fitness', 'muscle', 'yoga', 'gym', 'weight', 'strength', 'workout', 'minutes', 'balance', 'muscles', 'leg', 'dementia', 'benefits', 'physical activity', 'intensity', 'try', 'sport', 'exercises', 'fit', 'walking', 'times', 'sleep', 'workouts', 'sports', 'class', 'memory', 'adults', 'creatine', 'push']
3.0 → ['nhs', 'abortion', 'party', 'doctors', 'healthcare', 'political', 'patients', 'amendment', 'mps', 'vote', 'secretary', 'insurance', 'hunt', 'ireland', 'northern', 'doctor', 'speech', 'mental', 'northern ireland', 'gp', 'uk', 'reform', 'mental health', 'scottish', 'health service', 'gps', 'tory', 'social care', 'scottish national', 'national party']
4.0 → ['funeral', 'nazi', 'ss', 'asked', 'trauma', 'dead', 'mum', 'doctor', 'truth', 'mccartney', 'dignity', 'fear', 'sense', 'pinker', 'war', 'friend', 'experiences', 'final', 'grief', 'left', 'religious', 'amp', 'society', 'holiday', 'relationships', 'elizabeth', 'doctors', 'event', 'inevitable', 'loved']

##### Cleaning subtopics

###### Subtopic-4

In [31]:
subtopic4_out = topic0_out[topic0_out['topic'] == 4]

In [43]:
subtopic4_out['headline'].tolist()

['None of us wants to think about death. But pretending it won’t happen may not be the best option',
 'Ageing and the mortality alarm: ‘I started panicking about future me’',
 '‘The flight to Zurich sounds like the worst mini-break possible’: Julian Barnes on why Britain must legalise assisted dying ',
 'A holiday is about more than just a break. It’s a chance to dip a toe into a new version of yourself',
 "Sunny nihilism: 'Since discovering I’m worthless my life has felt precious'",
 'Stephen Porges: ‘Survivors are blamed because they don’t fight’',
 'Margaret Drabble: ‘I am not afraid of death. I worry about living’',
 'Gloom descends along with fear of dementia: this is the reality of crumbly life',
 'Death now has no dominion – but it should; it is part of life',
 'The Village Effect by Susan Pinker review – the science of friendship',
 'Why elderly couples often die together: the science of broken hearts',
 "If death becomes yet another commodity we'll die spiritually intestate",
 'Smoke Gets in Your Eyes by Caitlin Doughty review – startling stories from the crematorium',
 "'To hell with him …'"]

`topic0_out = topic0_out[topic0_out['topic']!=4]`

##### Subtopic-3

In [39]:
subtopic3_out = topic0_out[topic0_out['topic']==3]

In [41]:
subtopic3_out['headline'].tolist()

['The Guardian view on Starmer and the NHS: renewal is the right priority',
 'We all know the crisis in UK social care damages lives and the economy: it’s the Treasury we must convince',
 'Fighting for Life by Isabel Hardman; Our NHS by Andrew Seaton review – the NHS at 75',
 '£14bn plan to reduce NHS cancer backlogs in England is failing, MPs say',
 'Now that the Medicare psychologist sessions have been cut, I worry about my clients',
 'Don’t panic when Starmer refers to NHS ‘reform’. He is thwarting Tory moves to destroy it',
 'Beware the vultures circling over the NHS',
 'The Guardian view on attacks on GPs: the NHS is under threat',
 'Women must be allowed to defend abortion as a sex-based right',
 '‘Every man was drinking’: how much do bans on alcohol help women in India?',
 "The Observer view on Boris Johnson's lamentable summer",
 "UK's top gynaecologist spearheads women's health task force",
 "'He is the great survivor': Jeremy Hunt's ascendancy",
 "NDIS funding backflip: Coalition warned not to use people with disabilities 'as pawns'",
 'The Tories’ NHS pledge puts them on a Brexit bus to nowhere',
 'Talking about periods is part of a welcome decline in taboo subjects',
 'The bolshie, brilliant history of the women of Doctor Who',
 'Reform, ration, or return to first principles: the choices for the NHS',
 'Women in the greatest need are being let down by a lack of local support',
 'Americans are in no celebratory mood this Fourth of July. But they should be',
 'Republicans push ahead with plans to hinder insurance coverage for abortions',
 'The cost of the NHS is a matter of perspective',
 'Lesley Regan: ‘I have a responsibility to tell pregnant women the truth’',
 'Cuts to social care are morally wrong, says shadow health secretary',
 'Primary care must remain the bedrock of the NHS',
 'We all want a modern patient-centred NHS. Especially the doctors',
 'Jeremy Hunt can take on the junior doctors by showing he’s for the NHS',
 'Junior doctors, Jeremy Hunt and the facts behind the strike ballot',
 'The new model GP army: on-site vasectomies and Facebook diagnosis',
 "NHS managers are more than just 'bureaucrats with clipboards'",
 'Lizzie Magie invented Monopoly, so why haven’t we heard of her?\r\n',
 'Is there a future for the NHS – Guardian Live event roundup',
 "Queen's speech passes as 50 Labour MPs defy Corbyn and back staying in single market - Politics live",
 "Which country has the world's best healthcare system?",
 'We must end FGM everywhere, not just in the UK',
 'Women and the Vote: A World History by\xa0Jad Adams – review',
 "Big gains made on women's health, but access still unequal, says UN",
 'The US government shutdown is a playground spat that badly damages credibility',
 "Obamacare, much like Britain's NHS, will be a work in progress",
 "Charles Walker MP: 'Mental illness is not a weakness'",
 'The NHS will fail us so long as we look on it as a market',
 "Labour's spending worked. Why don't they defend it?",
 "Cuts won't save healthcare – staff will",
 'NHS SOS by Jacky Davis and Raymond Tallis – review',
 "It's drugs politics, not drugs policy, that needs an inquiry",
 'Today in healthcare: Monday 11 March',
 'Diary',
 "Unions are ready to respond to attacks on healthcare workers' pensions",
 'Society daily 26.05.2010',
 "NHS strike: 'is change necessary? The case has not been made'",
 'These work capability assessments are a farce',
 "Queen's speech: all the bills and what they mean",
 'No more debt. No more taxes. So how can we pay for care?',
 'Yorkshire Ripper begins appeal against whole-life tariff',
 "David Cameron's NHS reforms may leave him feeling sick"]

`topic0_out = topic0_out[topic0_out['topic']!=3]`

***
None of the topics here raised anything related to ageing concept which could be derived in researches, so I will delete them.
***

##### Subtopic-2

In [44]:
subtopic2_out = topic0_out[topic0_out['topic']==2]

In [46]:
subtopic2_out['headline'].tolist()

['How do I stay healthy in my 50s, 60s and 70s?',
 'Falling can be risky. Here’s how to avoid it and what to do if it happens',
 'Treadmills are out, barbells are in: why gym-goers are abandoning cardio for weight training',
 'Owning dog or cat could preserve some brain functions as we age, study says',
 'Athletes and fitness influencers use creatine, but what is it? And does it work?',
 '‘Start exercising!’: secrets of Thailand’s 105-year-old athletics champion',
 'How do I stay healthy in my 70s?',
 'A new start after 60: I did my first pull-up at 63 – then fought to be a ninja warrior',
 'Touch your toes! Six fast, easy ways to improve your mobility – and live a longer life',
 'Is muscle soreness after a workout good or bad?',
 'How do I stay healthy in my 60s?',
 'From strength training in your 20s to yoga in your 80s: how to reach peak fitness at any age',
 'How to start … anything: expert tips for trying something new',
 'Elite sportspeople can live five years longer, study finds',
 'The squat secret: why this simple move is the key to long-term health – and how to improve yours',
 'I ditched the gym and you can too – here are six ways to get fit without it',
 'The secret to why exercise is so good for mental health? ‘Hope molecules’',
 'Japanese seniors pop and lock to breakdancing beats in latest sport tailored to ageing population',
 'Lift, rest, recover: how to start weightlifting',
 'Almost half of dementia cases could be prevented or delayed, study finds',
 'The experts: neurologists on 17 simple ways to look after your brain',
 'Covid pandemic ‘had lasting impact’ on brain health of people aged 50 or over',
 'I spent 60 years sneering at yoga. It turns out I love it – and it does make you healthier and happier',
 'From stiff necks to ‘lazy glutes’: why these unloved muscles could prevent injury – and how to train yours',
 'Getting fitter can reduce prostate cancer risk by 35%, study finds',
 'Oh no! I’m sorry to report that cold plunges are great',
 'How do I stay healthy in my 50s?',
 'Lower socioeconomic status ‘triples risk of early-onset dementia’',
 'The best treadmills for your home: up your indoor miles with our runner-approved picks',
 'Should I worry about working out too hard?',
 'Sweat equity: infrared saunas are suddenly everywhere, but what do they do?',
 'The muscle miracle: can I build enough in my 60s to make it to 100 – even though I’ve never weight-trained?',
 'Bigger, stronger, faster: how my exercise addiction nearly killed me ',
 'Easy does it: 23 nifty fitness hacks for busy lives',
 '‘Excellent evidence that this works’: how mind experts protect their brains',
 '‘A sea of positivity’: older women boost London Marathon numbers',
 'Eat beans and scratch your own back – expert advice on how to age better, inside and out',
 'Can you stand on one leg for 10 seconds? Why balance could be a matter of life and death – and how to improve yours',
 'Why the health benefits of laughter yoga will make you smile',
 'Michael Horvath: the Strava co-founder who’s pacing himself',
 "Older adults can boost longevity 'with just a little exercise'",
 'Second act sensations! Meet the people who reached peak fitness – after turning 50',
 'Banishing burnout in 2021: how to make an exercise routine you’ll actually stick with',
 "Apple Fitness+ review: 'Short of getting a trainer, it's good at getting me to push myself'",
 "Joe Wicks: 'I believe when you give, give, give, the world ends up giving back'",
 "'I'll stay fit in lockdown,' I said. What an absolute joke",
 'Why do people think 41 is too old to exercise? It’s a perfect time to start',
 "Tom Brady's pseudoscientific wellness racket is the American dream",
 'Soreness is good and scales are pointless: the 10 biggest myths in fitness',
 'Share your tips for getting fit – and sticking with it',
 'Why exercise alone won’t save us',
 'Housework could keep brain young, research suggests',
 'Exercise didn’t disappear with the Greeks and Romans',
 'Four steps to a younger, smarter brain',
 'Kearnan Myall: ‘Several England players I know dread training camp’',
 'Mind games: a mental workout to help keep your brain sharp',
 "The slow, steady rise of 'conscious movement'",
 'Keep on running with this smart sport tech',
 'Yoga v pilates: both are popular, but which would work best for you?',
 'Extra time: how smart exercise keeps you younger for longer',
 "'Smashed it': high fiving with F45, the latest fitness craze to inspire evangelical devotion",
 "'I've never slowed down': meet the sports champions playing into their 80s",
 'Raising the barre: how science is saving ballet dancers',
 'Integrated care is key for dementia patients',
 'Why Serena Williams is the greatest sportsperson ever',
 'Bionic legs and smart slacks: exoskeletons that could enhance us all',
 'The Solowheel: check out this new giratory system',
 'The rise of eSports: are addiction and corruption the price of its success?',
 'Getting fit in middle age: a marathon addict, a couch potato and others share their pain',
 "Japan's muscle suit makes light work of heavy lifting",
 'Running: the top five reasons to keep going',
 'Is sex good exercise?',
 'Heart specialist questions benefits of high-intensity Tabata workout regime',
 "Timothy Olson, ultrarunner: 'I run for those moments of blissful peace'",
 'No pain, no gain? Getting the most out of exercise',
 "Martin Bashir: my brother's battle against Duchenne muscular dystrophy",
 'Will the Olympics leave a legacy of good health?',
 'Fitness: MovNat - or moving naturally - the new way to get in shape',
 "Excuses, excuses: 'I've got a sore toe'"]

***
The subtopic-2 has relations to researches since the studies are mentioned.
***

##### Subtopic-1

In [47]:
subtopic1_out = topic0_out[topic0_out['topic']==1]

In [49]:
model, topic_info, subtopic0_1_out = analyze_bertopic(subtopic1_out, v_min_df=1, v_max_df=0.85,text_col="bodyText",top_n_words=30,
                                     save_csv=None)

2025-07-25 07:31:51,383 - BERTopic - Embedding - Transforming documents to embeddings.
Batches: 100%|████████████████████████████████████| 5/5 [00:36<00:00,  7.31s/it]
2025-07-25 07:32:27,961 - BERTopic - Embedding - Completed ✓
2025-07-25 07:32:27,962 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2025-07-25 07:32:28,038 - BERTopic - Dimensionality - Completed ✓
2025-07-25 07:32:28,039 - BERTopic - Cluster - Start clustering the reduced embeddings
2025-07-25 07:32:28,043 - BERTopic - Cluster - Completed ✓
2025-07-25 07:32:28,044 - BERTopic - Representation - Extracting topics using c-TF-IDF for topic reduction.
2025-07-25 07:32:28,183 - BERTopic - Representation - Completed ✓
2025-07-25 07:32:28,183 - BERTopic - Topic reduction - Reducing number of topics
2025-07-25 07:32:28,186 - BERTopic - Representation - Fine-tuning topics using representation models.
2025-07-25 07:32:28,327 - BERTopic - Representation - Completed ✓
2025-07-25 07:32:28,328 - BERTopic - Topic reduction - Reduced number of topics from 3 to 3

In [50]:
topic_info

,Topic,Count,Name,Representation,Representative_Docs
0,-1,15,-1_internet_kirkwood_quarter_digital,"[internet, kirkwood, quarter, digital, connections, newc...","[In the UK, four out of 10 over-65s do not have internet..."
1,0,107,0_60_friends_mother_love,"[60, friends, mother, love, little, calment, book, paren...",[We are entering the age of no retirement. The journey i...
2,1,22,1_blackpool_glasgow_healthy life_kensington,"[blackpool, glasgow, healthy life, kensington, males, ch...",[England’s richest people are living for a decade longer...

In [94]:
subtopic0_1_out['headline'].tolist()

['The thing about ‘ageing gracefully’: whatever you call it, I’ll do it my way',
 'Australia’s life expectancy gap narrows but men in disadvantaged areas dying almost seven years earlier',
 'Why preventing long-term sickness in the UK is an economic necessity',
 'They say turning 44 brings ‘dramatic change’. I can’t wait',
 'A hero for refusing the easy flight out',
 'A short-lived guide to saving the Earth',
 'Public sector should embrace flexible working and trial four-day week',
 'Who’s the mysterious German sandwich thrower? What’s the point of Matt Hancock? It’s the age of the inexplicable',
 '‘Ageing isn’t inevitable’: The 100-Year-Life co-author on how to live well for longer',
 'Every year spent in school or university improves life expectancy, study says',
 'Work until you’re 71? It could be time to echo the French – and get angry',
 'Guilt, worry, resentment: how the ‘club sandwich’ generation juggles caring for parents, children and grandparents',
 'To fix the pensions crisis, we must first reduce poverty ',
 'From gen Z to boomers: what the 2024 budget means for your generation ',
 'Sixty is the new golden age: meet the stellar generation hitting this milestone ',
 'Celebrating the comfort and joy that old friends bring',
 '‘You can make meaningful relationships’: how does friendship change in older age?',
 'One in three say books offer best form of escapism when having a bad day',
 'Australians living longer but working in poor health in later life, research shows',
 'During Covid, callous Tories knew this about old people: they’re very expensive',
 'FOGO, our fear of growing old, is  sweeping the land. Just look at Trinny Woodall',
 'Britain lavishes benefits on plenty of rich pensioners. Let’s means test them now',
 'People living with dementia ‘sitting ducks for financial abuse’',
 'Lady Greengross obituary',
 'Namaste and a nice cup of tea without milk',
 '‘Keep your eyes open – and leap into the future’: 100 centenarians’ 100 tips for a life well lived',
 'Life expectancy gap in England ‘a growing chasm’ exacerbated by Covid',
 'Whatever happened to middle age? The mysterious case of the disappearing life stage',
 'The 60-year career: hope you like work, kids! You might still be doing it in your ninth decade',
 'Watching mother-daughter relationships through health and sickness gives me hope for mine',
 'A bag for life that’s keeping its promise',
 'A recession devastates people’s lives. But there are surprising health benefits when capitalism stops working',
 'Clare Wenger obituary',
 'Edith Redstone obituary',
 'Life expectancy in England rebounds after years of stagnation',
 'Children born now face longer period of ill health in old age',
 'No one can read 50 books a week. So why was I buying or borrowing that many?',
 'Poverty kills people: after coronavirus we can no longer ignore it',
 'Health inequality greater than previously thought, report finds',
 'More women aged 60-64 in work than not for first time in UK – ONS',
 'Life expectancy falls by six months in biggest drop in UK forecasts',
 'Gout gags are not funny for sufferers',
 'Fears of demographic timebomb in UK are unfounded, says study',
 'Number of over-70s still in work more than doubles in a decade',
 "Not dropping the mic: after 51 years, Brentford's MC to keep going at new ground",
 'Why optimists really live longer than pessimists',
 'Men in west London have highest male life expectancy in EU',
 "'People are caught up in magical thinking': was the oldest woman in the world a fraud?",
 'A few good habits to help you age well',
 'English health index to paint detailed picture of nation’s wellbeing',
 'Where to move for… a long life',
 'Let’s burst the age bubble – and bring the generations together',
 'How did old people become political enemies of the young?',
 "UK is 'completely and institutionally ageist'",
 'Figures reveal huge inequalities in health and longevity across UK',
 '‘There are no rules in age’: confession of an almost 90-year-old',
 'The big issue: increased longevity means working practices must change',
 'Why is life expectancy faltering?',
 'Baby boomers led the cult of youth. Now we should heed the wisdom of age',
 'We all want to live longer. But someone must pay',
 'L&G profits rise as UK population dies earlier than expected',
 "Emily Maitlis: ‘I always think, Oh my God, I’m exhausted, I want vodka and bed'",
 'Your state pension in Dorset – £124,000. In Glasgow? £38,000',
 "Final chapter for Pears' Cyclopaedia after 125 years in print",
 'Retain and retrain - how to keep an ageing population happy at work',
 "Inequalities among older people, especially women, 'shameful'",
 "We're living longer but in poorer health, warns thinktank",
 'Jeremy Paxman’s spiteful attack on older people shows he needs to grow up',
 'Our life in three stages – school, work, retirement – will not survive much longer',
 'African American men living in poverty face highest mortality risk, study says',
 'No more ’til death do us part, no more retirement? We must redefine what old age is',
 'How to have a long and healthy retirement',
 "Much like the Queen, we're all going to be working a lot longer",
 'There are fairer ways to set the pension age – but politicians are ducking them',
 'Have fun in your 50s: it’s the key to living longer, science says',
 'Our careers education is flawed: we need to think about skills not jobs',
 'How to live to 100 and be happy (by those who have done it!)',
 'The 100-year-old couple – still married, still going strong',
 'Britons at 90: healthier, wiser, more independent – but it helps if you’re rich',
 'The rise of encore careers: why over-50s are changing patterns of working life',
 'Only a fraction of UK job ads offer flexibility, study finds',
 'Warning for grandparents raiding their pension pots to help out family',
 'The Queen at 90: the secret of one’s success',
 'South-west of England tops list of best places to retire',
 'Want to work as a mental health professional? Our top tips',
 'A world without retirement',
 'Susan Pinker: why face-to-face contact matters in our digital age',
 'Improving with age? How city design is adapting to older populations',
 'Ageing well: whose responsibility is it?',
 'Britain is an ageing country – so maybe it’s time we started seriously to cater for people’s needs',
 'Life expectancy falls for older UK women',
 'Life expectancy increases but gap widens between rich and poor',
 'Study finds social media use beneficial to overall health of elderly',
 "Weekly highlights: People's Climate March, golf courses and Lego creations",
 'Is middle age such a bad thing?',
 'How can older people’s skills be valued after life’s rush hour?',
 'UN scores Australia high for quality of life but low on climate change progress',
 'Loneliness is not a bug with a technological solution',
 'Budget 2014: pensions shakeup could kill off annuity market, say analysts',
 'Ageing: the over-60s have talents that we should tap for the good of all',
 'ONS census of elderly finds almost 25% rise in those aged 85 plus',
 "Britons are living longer than ever, but it doesn't mean we're healthier",
 'Grandparents step in to help students cover their costs',
 'Annuity payouts are a postcode health lottery',
 'Government NHS fund switching for the elderly is grossly unjust',
 'Equity release – the gift that keeps on taking',
 'Older women: has society forgotten how to value them?',
 'Why Blackpool is the most unhealthy place in England',
 'Avoidable deaths: councils will need to get used to unsparing analysis',
 'Good for their age',
 'You want to live to 1,000? Start making friends',
 "Britain 'woefully' under-prepared for rising number of elderly people",
 'Research dispels old myths about ageing',
 'Life expectancy is increasing, but so are social divides',
 'David Bailey: this is what 100 looks like',
 'Ageing population will have huge impact on social services, Lords told',
 'The lost art of letter-writing',
 'London Royal Plus life insurance policy is good money after bad',
 'Somerset and Suffolk towns top life-expectancy list for older people',
 'More than a third of babies born in 2012 will live to 100, report predicts',
 'Older people give so much more than they take from us',
 'Life expectancy shows a growing north-south divide',
 'Can teachers ever have a work-life balance?',
 'Job prospects linked to low birth weight and childhood illness, study says',
 'Vladimir Putin pledges to spend £32bn on increasing Russian life expectancy',
 'Age is a continuum – not two tribes to be made equal',
 'Baby boomers need their own online voice to fight prejudice as they get old',
 "Northerners '20% more likely to die under 75' than southerners",
 'One in six people in the UK today will live to 100, study says',
 "Let's dispel this gloom about living longer and make life better for the old",
 'State pension age petition launched for women hit by pensions delay',
 'Data shows Glasgow has lowest mortality age',
 'Women the losers from welfare cuts',
 "Lucy Mangan: It's time to kick up a stink",
 'Live to be 100? One in four 16-year-olds predicted to become centenarians',
 'Default retirement age to end, say ministers',
 'BMW insures pension fund against rising life expectancy',
 'Q&A: How will the ECJ gender ruling affect my insurance?',
 'I hope when I finally grow up that I will become a Real Old Person',
 'A close call on health inequalities',
 'Convenient myth of the elderly hedonist',
 "The readers' editor on…\u2002ageism in the media",
 'FSA warns over traded investments in life policies',
 'Hey, all of a sudden older people are sexy. It must be election time again']

##### Subtopic-0

#### Cleaning topic-11

***
['wines', 'vodka', 'mid range', 'sparkling', 'splurge', 'price range', 'madeira', 'flavours', 'socks', 'reds', 'jeans'<br>
 'cocktail', 'craft', 'red wine', 'grape', 'linen', 'grapes', 'olive oil', 'shirt', 'bedding','citrus', 'pint', 'cocktails',<br> 
 'producers', 'high quality', 'moisturiser', 'durability', 'premium', 'syrup', 'portugal']
 ***

In [2]:
topic_11 = guardian_out[guardian_out['topic'] == 11]

In [3]:
pd.set_option('display.max_colwidth', None)
topic_11[['headline','trailText','bodyText','links', 'tags']]

                                                                                                                        headline  \
169                                                                                              Bottles with a seal of approval
311   ‘If you pay more than £4, you’re being ripped off’: the fair price for 14 everyday items, from cleaning spray to olive oil
435                                                                                         The magic of vintage fortified wines
444                                                             The marvels of Madeira: one of the great unsung Portuguese wines
612                                                           Sick of spritzes? The ultimate guide to Australian summer drinking
623                                                                                                How malbec scaled the heights
665                                                               French family's last three bottles of 1774 wine up for auction
794                                                    England’s vineyards meet their biggest challenge – a decent bottle of red
873                                                          From amari mania to a vodka revival: what we’ll be drinking in 2017
967                                                                 Co-operative Group toasts success of world-beating champagne
1137                                                             Drink up, it's good for you! A red wine detox holiday in France

                                                                                                                                                                                                   trailText  \
169                                                                                                         Wines that benefit from the influence of a new generation of master-craftspeople in the vineyard
311   Everything seems so expensive these days – but how much should you pay for that bottle of wine, or pair of jeans? A panel of experts explains how to make good choices – and when you’re being fleeced
435                                                                              Complex and beguiling, very old port, sherry and madeira can pack an emotional – and financial – punch, says David Williams
444                                                                                      Madeira may be a great and versatile cooking ingredient, but it’s also the store-cupboard tipple par excellence<br>
612                                               From refreshing cocktails to savoury, grown-up non-alcoholic options, this summer, drinking is lower on sugar, higher on flavour and a little experimental
623                                                                                                                              The rise of the grape that’s at its best on mountain slopes is an epic tale
665                                                                                                            Other bottles of same wine – among the oldest in the world – previously fetched up to €57,000
794                                                                                 The UK climate has long cast a shadow over a homegrown pinot noir, but after years of experiments, is this now changing?
873                                                                                     If you want to keep up with the in-things in drinks this year, here are four trends that could take off in a big way
967                                                                                      <p>Cut-price Les Pionniers vintage champagne wows judges to scoop three of industry's top international honours</p>
1137                                     <p>You don't usually associate detoxing with fun – or booze. But there's plenty of both on a new red wine detox in the Madiran wine region in south-west France</p>


***
None of the topics are related to healthy ageing so we get rid of them.
***

In [4]:
guardian_out = guardian_out[guardian_out['topic']!=11]

#### Cleaning topic-10

***
['productivity', 'insomnia', 'beds', 'caffeine', 'nap', 'hours sleep', 'boredom', 'bedtime', 'cognitive',<br>
'awake', 'seven hours', 'coach', 'bored', 'sleep night', 'working home', 'saunders', 'night sleep', 'microdosing',<br>
'waking', 'dopamine', 'physical activity', 'scrolling', 'neuroscience', 'duration', 'hormone', 'mindfulness',<br>
'creativity', 'time day', 'cup coffee', 'study suggests']
 ***

In [5]:
topic_10 = guardian_out[guardian_out['topic'] == 10]

In [6]:
topic_10

                                                                                                                                  id  \
87                         lifeandstyle/article/2024/jun/23/sleep-restriction-insomnia-lara-williams-treats-supper-club-odyssey-cbti
108   lifeandstyle/2025/jul/14/terrible-nights-sleep-heres-how-to-make-it-through-the-day-and-maybe-even-enjoy-it-one-step-at-a-time
173                                                            lifeandstyle/2024/oct/18/improve-focus-concentration-span-expert-tips
254                                                        world/2023/jun/23/in-the-home-of-the-siesta-the-nap-is-just-a-dream-spain
423                                         lifeandstyle/2021/jan/01/burnt-out-resolutions-a-feel-better-guide-for-the-already-tired
537                             lifeandstyle/2020/sep/24/the-golden-hour-15-ways-to-change-your-life-in-a-work-from-home-lunch-break
584                                                 books/2019/aug/16/rolled-over-why-did-married-couples-stop-sleeping-in-twin-beds
633                                               science/2018/may/23/weekend-lie-ins-could-help-you-avoid-an-early-death-study-says
719                                           wellbeing-at-work/2017/sep/20/do-yoga-work-harder-how-productivity-co-opted-relaxation
734                  lifeandstyle/2018/sep/03/sad-summers-over-18-ways-to-keep-the-health-humour-and-happiness-of-your-holiday-alive
866                                                   lifeandstyle/2016/feb/15/is-it-good-to-be-bored-or-will-it-be-the-death-of-you
1144                                                                     commentisfree/2012/nov/05/live-long-lazy-britain-oldest-man
1252                                                           lifeandstyle/2010/jun/12/indigestion-social-events-hours-sleep-needed

               section              pub_date  \
87      Life and style  2024-06-23T09:00:09Z
108     Life and style  2025-07-14T04:00:02Z
173     Life and style  2024-10-18T10:00:22Z
254         World news  2023-06-23T10:59:06Z
423     Life and style  2020-12-31T16:30:46Z
537     Life and style  2020-09-24T10:30:43Z
584              Books  2019-08-16T14:25:09Z
633            Science  2018-05-23T03:00:11Z
719   Guardian Careers  2017-09-20T15:16:45Z
734     Life and style  2018-09-03T05:00:43Z
866     Life and style  2016-02-15T07:45:04Z
1144           Opinion  2012-11-05T18:40:08Z
1252    Life and style  2010-06-11T23:01:29Z

                                                                                                                                                         web_url  \
87                         https://www.theguardian.com/lifeandstyle/article/2024/jun/23/sleep-restriction-insomnia-lara-williams-treats-supper-club-odyssey-cbti
108   https://www.theguardian.com/lifeandstyle/2025/jul/14/terrible-nights-sleep-heres-how-to-make-it-through-the-day-and-maybe-even-enjoy-it-one-step-at-a-time
173                                                            https://www.theguardian.com/lifeandstyle/2024/oct/18/improve-focus-concentration-span-expert-tips
254                                                        https://www.theguardian.com/world/2023/jun/23/in-the-home-of-the-siesta-the-nap-is-just-a-dream-spain
423                                         https://www.theguardian.com/lifeandstyle/2021/jan/01/burnt-out-resolutions-a-feel-better-guide-for-the-already-tired
537                             https://www.theguardian.com/lifeandstyle/2020/sep/24/the-golden-hour-15-ways-to-change-your-life-in-a-work-from-home-lunch-break
584                                                 https://www.theguardian.com/books/2019/aug/16/rolled-over-why-did-married-couples-stop-sleeping-in-twin-beds
633                                               https://www.theguardian.com/science/2018/may/23/weekend-lie-ins-could-help-you-avoid-an-early-death-study-says
719                                           https://www.theguardian.com/wellbeing-at-work/2017/sep/20/do-yoga-work-harder-how-productivity-co-opted-relaxation
734                  https://www.theguardian.com/lifeandstyle/2018/sep/03/sad-summers-over-18-ways-to-keep-the-health-humour-and-happiness-of-your-holiday-alive
866                                                   https://www.theguardian.com/lifeandstyle/2016/feb/15/is-it-good-to-be-bored-or-will-it-be-the-death-of-you
1144                                                                     https://www.theguardian.com/commentisfree/2012/nov/05/live-long-lazy-britain-oldest-man
1252                                                           https://www.theguardian.com/lifeandstyle/2010/jun/12/indigestion-social-events-hours-sleep-needed

                                                                                                          headline  \
87                         ‘The first few nights were punishing’: how sleep restriction cured my lifelong insomnia
108   Terrible night’s sleep? Here’s how to make it through the day – and maybe even enjoy it – one step at a time
173                                            Pay attention! 12 ways to improve your focus and concentration span
254                                    Naps are healthy, scientists say – so why has Spain given up on the siesta?
423                                                Burntout resolutions: a feel-better guide for the already tired
537                                   The golden hour: 15 ways to change your life in a work-from-home lunch break
584                                               Rolled over: why did married couples stop sleeping in twin beds?
633                                                Weekend lie-ins could help you avoid an early death, study says
719                                                     Do yoga, work harder: how productivity co-opted relaxation
734                      Sad summer’s over? 18 ways to keep the health, humour and happiness of your holiday alive
866                                                       Is it good to be bored (or will it be the death of you)?
1144                                                           Live lazy, live long – look at Britain's oldest man
1252                               Doctor, doctor: Why do I get indigestion when I go out for dinner with friends?

                                                                                                                                                                                    trailText  \
87                            After giving birth, novelist Lara Williams feared she might never sleep again. So she turned to CBT-i, a radical therapy that rewired her relationship to sleep
108                                                   Coffee or no coffee? Almond croissant or exercise snack? Early night or bedtime as usual? You’ll be grateful you made the right choices
173                          From gamifying your to-do list to going for a regular morning walk, top tips for improving concentration from psychotherapists, health coaches and other experts
254                                                                                     As study shows a daytime doze may help brain’s health, for Spaniards the idea is outdated and cliched
423   Normally a fan of January goal-setting, 2021 feels different for <strong>Brigid Delaney</strong> – with the help of experts she’s aiming for more humble but longer lasting good habits
537               It’s all too easy to stay at your desk. But stepping away to exercise, clear out your junk drawer, watch the Sopranos – or have sex – could completely re-energise your day
584                                                         A new cultural history shows that until the 1950s, forward-thinking couples regarded sharing a bed as old-fashioned and unhealthy
633                                     Survey of 38,000 adults shows 65% higher mortality rate for adults getting five hours’ sleep a night unless balanced with longer snooze on ‘days off’
719      Holidays, procrastination and drug-taking were once ways to escape work. Now leisure has been reappropriated to aid work. So is anything actually considered unproductive nowadays?
734                    Join a club, take a detour – and buy a carafe: positive psychologists on how you can take the novelty and openness of your vacation and apply it to your daily routine
866                                                                         One study implies that boredom make you likelier to die earlier, but another concludes that it spurs creativity …
1144                             <strong>Tom Hodgkinson:</strong> Politicians love to castigate slothful Britons, but Reg Dean says idleness helped him live to 110. So slow down. Take a nap
1252                                                                                                            Discomfort at social events. Plus do more hours of sleep equal a longer life?

                   byline  wordcount  \
87          Lara Williams       2368
108            Joel Snape       1737
173        Chloë Hamilton       1462
254   Sam Jones in Madrid        578
423        Brigid Delaney        966
537             Elle Hunt       1642
584          Alison Flood        762
633          Nicola Davis        645
719         Paula Cocozza       1683
734         Paula Cocozza       2232
866         Luisa Dillner        441
1144       Tom Hodgkinson        599
1252         Dr Tom Smith        343


***
None of these topics are related to longevity except these 2:
<br>science/2018/may/23/weekend-lie-ins-could-help-you-avoid-an-early-death-study-says
<br>lifeandstyle/2016/feb/15/is-it-good-to-be-bored-or-will-it-be-the-death-of-you
***

In [7]:
guardian_out = guardian_out[
    (guardian_out['topic'] != 10) |
    (
        (guardian_out['id'] == 'science/2018/may/23/weekend-lie-ins-could-help-you-avoid-an-early-death-study-says') |
        (guardian_out['id'] == 'lifeandstyle/2016/feb/15/is-it-good-to-be-bored-or-will-it-be-the-death-of-you')
    )
]

#### Cleaning topic-9

***
['chemotherapy', 'screening', 'oncologist', 'prostate', 'diagnosis', 'remission', 'prostate cancer', <br>
 'long covid', 'breast cancer', 'nursing', 'syphilis', 'quality life', 'toxicity', 'neurologist', <br>
 'cancer patients', 'surgeon', 'eczema', 'nursing home', 'cancers', 'palliative', 'complications', <br>
 'organ', 'mom', 'transplant', 'spine', 'craig', 'kidney', 'relieved', 'cognitive', 'illnesses']
***

In [8]:
topic_9 = guardian_out[guardian_out['topic'] == 9]

In [9]:
topic_9[['id','section','headline','trailText', 'links','tags']]

                                                                                                                                            id  \
179                                           lifeandstyle/2023/apr/23/the-moment-i-knew-his-accident-in-a-weird-way-was-a-renewal-of-our-vows
186                                                                                                 society/2024/may/08/kris-hallenga-obituary
192                                                                society/2024/feb/22/fighting-talk-why-we-should-mind-our-language-on-cancer
228                                                      commentisfree/2024/feb/16/king-charles-speak-cancer-winning-losing-war-bowel-language
262                                                                      science/2023/jul/09/microbiome-chronic-fatigue-me-long-covid-research
297                                             commentisfree/2023/jun/21/i-am-an-oncologist-can-chatgpt-help-me-deliver-bad-news-to-a-patient
356                       commentisfree/2022/nov/02/its-not-looking-good-is-it-why-patients-families-plead-for-connection-as-much-as-prognosis
374                     commentisfree/2022/sep/01/three-things-i-have-learned-about-end-of-life-care-from-treating-elderly-couples-with-cancer
379   commentisfree/2022/aug/03/when-a-patients-survival-is-dwarfed-by-the-logistics-of-treatment-oncologists-need-to-talk-about-time-toxicity
513                  society/2021/may/19/kris-hallenga-the-woman-diagnosed-with-cancer-at-23-who-convinced-a-generation-to-check-their-breasts
531               commentisfree/2020/jun/23/i-understand-why-my-patient-is-scared-to-lose-her-hair-it-signals-the-loss-of-life-as-she-knows-it
593              commentisfree/2019/sep/18/how-can-i-tell-my-patients-theyll-be-fine-in-a-nursing-home-our-trust-in-the-industry-was-misplaced
754                                                   society/2018/jan/24/to-treat-or-not-to-treat-find-out-what-really-matters-to-the-patient
774                                 commentisfree/2017/aug/30/as-cancer-progresses-some-patients-weep-some-get-angry-and-others-are-bewildered
820                                                                         society/2016/sep/14/monitoring-prostate-cancer-effective-treatment
838                                                                 healthcare-network/2016/sep/22/dying-patient-taught-me-doing-nothing-brave
939                                                                           society/2015/jul/25/morquio-syndrome-nhs-drug-funding-sarah-long
949                                                 science/sifting-the-evidence/2015/jul/06/why-are-some-diseases-screened-for-but-not-others
1001                                                                     commentisfree/2015/mar/16/die-words-daughter-cancer-time-neurosurgeon
1063                                                                                          society/2014/feb/11/ration-cancer-treatments-nhs
1092                                                                           science/2014/nov/14/-sp-so-youve-survived-cancer-but-whats-next
1110                                                                                society/2013/apr/09/families-reduce-organ-donation-refusal
1117                                                                            society/2012/jul/21/mother-dementia-care-elderly-michael-wolff
1119                                                                                       lifeandstyle/2012/nov/18/mother-lung-cancer-smoking
1128                                                                      commentisfree/2013/jan/30/response-stigma-britten-death-still-potent
1296                                                                                               lifeandstyle/2010/jan/12/living-with-eczema

                               section  \
179                     Life and style
186                            Society
192                            Society
228                            Opinion
262                            Science
297                            Opinion
356                            Opinion
374                            Opinion
379                            Opinion
513                            Society
531                            Opinion
593                            Opinion
754                            Opinion
774                            Opinion
820                            Society
838   Healthcare Professionals Network
939                            Society
949                            Science
1001                           Opinion
1063                           Society
1092                           Science
1110                           Society
1117                           Society
1119                    Life and style
1128                           Opinion
1296                    Life and style

                                                                                                                headline  \
179                                         The moment I knew: ‘His accident, in a weird way, was a renewal of our vows’
186                                                                                               Kris Hallenga obituary
192                                                             Fighting talk: why we should mind our language on cancer
228    Let King Charles’s illness finally change how we speak about cancer: it’s not about ‘winning’ or ‘losing’ a ‘war’
262                                                        Does the microbiome hold the key to chronic fatigue syndrome?
297                                               I am an oncologist. Can ChatGPT help me deliver bad news to a patient?
356                     ‘It’s not looking good, is it?’ Why patients’ families plead for connection as much as prognosis
374                         Three things I have learned about end-of-life care from treating elderly couples with cancer
379   When a patient’s survival is dwarfed by the logistics of treatment, oncologists need to talk about ‘time toxicity’
513               Kris Hallenga: the woman diagnosed with cancer at 23 who convinced a generation to check their breasts
531                  I understand why my patient is scared to lose her hair: it signals the loss of life as she knows it
593                How can I tell my patients they'll be fine in a nursing home? Our trust in the industry was misplaced
754                                                To treat or not to treat: find out what really matters to the patient
774                                    As cancer progresses some patients weep, some get angry and others are bewildered
820                                                Monitoring of prostate cancer as effective as treatment in some cases
838                                                          One dying patient taught me that doing nothing can be brave
939                                           ‘Stopping my lifesaving drug will be my end,’ says woman with rare illness
949                                                                   Why are some diseases screened for but not others?
1001                                                                       Before I die, some words for my baby daughter
1063                                                                      Does the NHS need to ration cancer treatments?
1092                                                                             So you've survived cancer. What's next?
1110                                                   We must work with families to reduce organ donation refusal rates
1117                                                                                                    Let my mother go
1119                                                    My mother has early-stage lung cancer, but won't give up smoking
1128                                                Yes, the evidence does show that Benjamin Britten died from syphilis
1296                                                                                     Diary of a homeophobe: part six

                                                                                                                                                                                                                                         trailText  \
179                                                                     Anyone who has been married 30 years understands that longevity comes with wear and tear. For <strong>Kylie Ladd</strong>, a moment of vulnerability was deeply fortifying
186                                                                                                                                       Campaigner who founded the CoppaFeel! cancer awareness charity to encourage women to check their breasts
192                                                                                                                <strong>Letters: </strong>Readers respond to an article by Simon Jenkins on the use of violent terms to speak about the disease
228                                                                                                                As someone treated for bowel cancer, I think attitudes must change but also the language, says Guardian columnist Simon Jenkins
262                                                                                  Often dismissed by the medical establishment, people with complex illnesses such as ME and long Covid are taking the hunt for treatments into their own hands
297                                                                                             The AI tool won’t offer a healing touch or resolve existential grief – but I will still be telling trainees to consult the chatbot in trying times
356                                                                                                     On a phone call the body language is lost. Is my patient’s wife asking me this while doing housework, or are her knuckles white with fear?
374                                                                                                                                                  Experience provides fortitude, equanimity and perspective. Not everyone wants to live forever
379                                                                                           The diagnosis of a life-limiting illness underlines the importance of knowing not only how much time is left but also how and where it will be spent
513                                                                  When she was told she had stage four breast cancer in 2009, Hallenga didn’t even know it could be a danger at her age. Then she started a campaign to save thousands of lives
531                                                                                                                                   The older I grow, the more I realise that the most consequential decisions we make in life are rarely binary
593                                                                                                                                          There is one conversation in medicine that I hate having: telling patients they need residential care
754                                                                                                                                   Informed consent is a tenet of a good doctor-patient relationship, particularly when it comes to the elderly
774                                                                                                                         Oncologists have to give bad news. But we can’t help it when our imaginations are held captive by a particular patient
820                                                                                                                       Localised prostate cancer sufferers have same survival rate after 10 years as those who have surgery, according to study
838                                                                                                               The patient who loved chicken wings showed me that healthcare professionals fail to hear what really matters in end-of-life care
939                                                                                                                                   Sarah Long, oldest survivor of Morquio syndrome, pleads for NHS to provide expensive drug to treat condition
949                                                                                                                                                 Screening for disease has the potential to save lives, but only in very specific circumstances
1001                                                                              Having cancer has made me acutely aware of time’s elasticity. When I was a neurosurgeon it sped by. Now it feels static, but you’ve filled my last days with joy
1063                                                                          <p><strong>Zara Aziz: </strong>As the cost of cancer treatment increases and rationing becomes a reality, it is time we made better use of our limited resources</p>
1092  <strong>Ranjana Srivastava:</strong> It is only in the aftermath of treatment that survivors discern that their adrenalin alone won’t fuel the rest of their recovery. For many, surviving cancer is followed by even more hardship<em></em>
1110                                                                                                   <strong>Zara Aziz: </strong>Kidney transplants makes economic sense since the average cost of haemodialysis is £35,000 per patient per year
1117  Michael Wolff has stood by while doctors keep his mother alive, despite the fact that she has severe dementia. Here, in this provocative and heartbreaking plea, he reveals why our obsession with longevity is making old age a living hell
1119                                                                                                                          <p>I struggle with the smell and her refusal to consider its effects on her health. How should I deal with this?</p>
1128                                                                                                <strong>Response: Paul Kildea:</strong> Despite the doubters, when all the composer's symptoms are considered there can be only one conclusion
1296                                                                                      <p>In his final dispatch from the frontline of eczema, <strong>Peter Beech</strong> reports on a battle won - and a war that will always need waging</p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   links  \

***
None of the articles here are directly related to healthy ageing so we delete them.
***

In [10]:
guardian_out = guardian_out[guardian_out['topic'] != 9]

#### Cleaning topic-8

***
['flower', 'butterflies', 'roses', 'planting', 'foliage', 'blooms', 'flowering',<br>
'orchard', 'butterfly', 'hirst', 'cuttings', 'shrubs', 'compost', 'bulbs', 'iris',<br>
'edible', 'varieties', 'woodland', 'stems', 'oak', 'orchards', 'watering', 'shrub',<br>
'planted', 'chelsea', 'potter', 'container', 'bloom', 'bailey', 'potatoes']
***

In [11]:
topic_8 = guardian_out[guardian_out['topic']==8]

In [15]:
topic_8[['id','section','headline','trailText', 'links','tags']]

,id,section,headline,trailText,links,tags
31,lifeandstyle/2025/jul/11/foxgloves-cottage-garden-classics-town-urban-garden,Life and style,"Foxgloves are cottage garden classics, but they look just as good in town",These quintessential country flowers relish the dappled shade often cast in built-up areas – and there’s a variety for everyone,https://www.rhs.org.uk/plants/150196/digitalis-mertonensis-summer-king/details; https://www.rhs.org.uk/plants/150196/digitalis-mertonensis-summer-king/details; https://www.rhs.org.uk/plants/150196/digitalis-mertonensis-summer-king/details; https://www.rhs.org.uk/plants/339227/digitalis-martina/details; https://www.rhs.org.uk/plants/339227/digitalis-martina/details; https://www.rhs.org.uk/plants/339227/digitalis-martina/details; https://www.rhs.org.uk/plants/96171/digitalis-purpurea-sutton-s-apricot/details; https://www.rhs.org.uk/plants/136477/digitalis-purpurea-pam-s-choice/details; https://www.rhs.org.uk/plants/41734/digitalis-ferruginea/details; https://www.rhs.org.uk/plants/41734/digitalis-ferruginea/details; https://www.rhs.org.uk/plants/41734/digitalis-ferruginea/details; https://www.rhs.org.uk/plants/5861/digitalis-parviflora-jacq/details,Gardening advice; Gardens; Life and style
71,lifeandstyle/2025/may/09/mothers-day-2025-best-flowers-how-to-order-delivery,Life and style,Avoid same-day wilt: how to order the freshest Mother’s Day flowers,"It is estimated only 50% of flowers sold in Australia are locally grown, but florists and growers say local is ‘a superior product’. Here they share tips for buying blooms that last",https://www.fairtrade.net/content/fairtrade/language-masters/en/products/Flowers.html; https://www.theguardian.com/newsletters/2019/oct/18/saved-for-later-sign-up-for-guardian-australias-culture-and-lifestyle-email?CMP=copyembed; https://www.theguardian.com/lifeandstyle/2025/may/06/im-losing-my-mum-to-young-onset-dementia-caring-for-my-baby-reminds-me-who-she-was,Australian lifestyle; Life and style; Plants; Mother's Day
128,lifeandstyle/2025/apr/03/the-leaves-fall-off-but-i-think-thats-normal-the-houseplants-you-just-cant-kill,Life and style,‘The leaves fall off – but I think that’s normal’: the houseplants you just can’t kill,"Some indoor plants wither the moment you turn your back; others shrug off drought, darkness and even ‘watering’ by cats. Here’s how to choose the most hardy specimens. Plus, readers celebrate the greenery that survived against all the odds","https://www.theguardian.com/profile/guardian-community-team; https://www.theguardian.com/tone/letters; mailto:guardian.letters@theguardian.com?body=Please%20include%20your%20name%E2%80%8B%E2%80%8B,%20full%20postal%20address%20and%20phone%20number%20with%20your%20letter%20below.%20Letters%20are%20usually%20published%20with%20the%20author%27s%20name%20and%20city/town/village.%20The%20rest%20of%20the%20information%20is%20for%20verification%20only%20and%20to%20contact%20you%20where%20necessary.",Houseplants; Life and style; Interiors; Gardening advice; Homes
181,lifeandstyle/2024/jan/26/winter-is-not-for-chilling-its-time-to-sharpen-your-tools-and-prep-the-garden,Life and style,Winter is not for chilling – it’s time to sharpen your tools and prep the garden,"It may not be tempting to head outside in the cold, but there’s plenty to be getting on with – and you’ll thank yourself later in the year",https://www.niwaki.com/crean-mate/; https://www.niwaki.com/videos/,Gardening advice; Gardens; Life and style
184,lifeandstyle/2023/nov/03/houseplant-of-the-week-sea-urchin-cactus,Life and style,Houseplant of the week: sea urchin cactus,"Compact, non-spiny and with large luscious flowers, this Tex-Mex native will suit any home",NaN,Houseplants; Life and style
195,lifeandstyle/article/2024/may/03/10-shrubs-that-will-thrive-in-your-garden,Life and style,Shrubs offer resilience and reliability: here are 10 that will thrive in your garden,"As climate change brings volatile weather patterns, the shrub – too often ignored in favour of fashionable perennials – is making a comeback",https://www.theguardian.com/environment/2023/jul/03/prairie-planting-takes-root-uk-gardeners-battle-drought-floods; https://www.theguardian.com/lifeandstyle/2024/apr/20/27-of-the-most-basic-gardening-questions-answered; https://yellowlightedbookshop.co.uk/product/shrouded-in-light/; https://www.rhs.org.uk/plants/185322/fatsia-polycarpa/details; https://www.rhs.org.uk/plants/185322/fatsia-polycarpa/details; https://www.rhs.org.uk/plants/89015/osmanthus-burkwoodii/details; http://bethchatto.co.uk; http://bethchatto.co.uk; https://www.rhs.org.uk/plants/43844/i-vitex-agnus-castus-i/details; http://burncoose.co.uk; https://www.rhs.org.uk/plants/322095/mahonia-eurybracteata-soft-caress/details; http://paramountplants.co.uk; http://paramountplants.co.uk; https://www.rhs.org.uk/plants/238921/juniperus-grey-owl/details; https://www.paramountplants.co.uk/; https://www.paramountplants.co.uk/; https://www.rhs.org.uk/plants/23542/i-sarcococca-ruscifolia-i/details; https://www.rhs.org.uk/plants/260154/sarcococca-ruscifolia-var-chinensis-dragon-gate/details; http://burncoose.co.uk; http://burncoose.co.uk; https://www.rhs.org.uk/plants/10565/lupinus-arboreus/details; https://www.victoriananursery.co.uk/Tree-Lupin/; https://www.rhs.org.uk/plants/374127/fatsia-polycarpa-green-fingers/details; http://bethchatto.co.uk; http://bethchatto.co.uk; https://www.rhs.org.uk/plants/85295/skimmia-confusa-kew-green-(m)/details; http://crocus.co.uk; https://www.rhs.org.uk/plants/21165/rubus-lineatus/details; https://crug-farm.co.uk/; https://crug-farm.co.uk/; https://www.rhs.org.uk/plants/11760/olearia-macrodonta/details; http://emeraldplants.co.uk,Gardens; Gardening advice; Life and style
236,lifeandstyle/article/2024/jul/31/16-ways-grow-portable-garden-take-next-rental,Life and style,Everything must go! 16 ways to grow a portable garden – to take to your next rental,"The rise in renting has coincided with a gardening boom. Here is how to make the most of your outdoor space, even if you don’t own the property","https://www.ons.gov.uk/economy/environmentalaccounts/articles/oneineightbritishhouseholdshasnogarden/2020-05-14; https://www.theguardian.com/uk-news/2023/jan/05/number-households-renting-more-than-doubled-2001-census-england-wales; https://www.theguardian.com/society/2024/feb/08/renters-in-england-face-rising-no-fault-evictions-as-reform-bill-delayed-again; https://www.theguardian.com/business/2023/dec/17/all-my-friends-have-moved-how-uk-cities-have-been-hollowed-out-by-housing-price-rises; https://www.theguardian.com/books/2024/apr/27/safe-haven-or-symbol-of-injustice-what-our-gardens-tell-us-about-the-world-we-live-in#:~:text=Over%20the%20course%20of%202020,globally%2C%20from%20Italy%20to%20India.; https://www.rhs.org.uk/advice/health-and-wellbeing/articles/why-gardening-makes-us-feel-better; https://www.theguardian.com/environment/article/2024/jul/17/londoners-should-be-charged-for-paving-gardens-says-climate-resilience-report; https://guardianbookshop.com/gardeners-world-a-year-in-a-small-garden-9781785948640?utm_source=editoriallink&amp;utm_medium=merch&amp;utm_campaign=article",Gardening advice; Gardens; Life and style; Property; Housing; Society
271,lifeandstyle/2022/mar/06/james-wong-on-gardening-desert-roses-will-soon-win-your-heart,Life and style,Desert roses will soon win your heart,"These beautiful succulents from the deserts of the Arabian peninsular are associated with wealth and longevity, says James Wong",https://twitter.com/Botanygeek?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor,Gardening advice; Life and style; Gardens
278,environment/2023/jun/26/barcelona-centenarian-organic-gardener-joan-carulla-rooftop-farm-aoe,Environment,Still nurturing love and vines: the centenarian who built Barcelona’s first roof garden,"When environmentalist and pacifist Joan Carulla came to the city after growing up during Spain’s civil war, he created an ‘allotment in the sky’ that helped pioneer organic farming",https://vimeo.com/768085959/c09dd6d7d4; https://www.theguardian.com/commentisfree/2022/jan/26/the-guardian-view-on-remembering-the-spanish-civil-war-the-work-must-go-on; https://www.amazon.es/Mi-siglo-verde-lecciones-COLECCION/dp/8419200948; https://www.theguardian.com/business/monsanto; https://www.otoxoproductions.com/; https://www.theguardian.com/environment/2023/mar/18/barcelona-football-camp-nou-stadium-animal-inhabitants-wildlife; https://www.theguardian.com/environment/series/the-age-of-extinction; https://twitter.com/phoeb0?lang=en; https://twitter.com/pgreenfielduk?lang=en,Organic gardening; Europe; Gardens; World news; Vegetables; Food; Spain; Farming; Life and style; Environment; Barcelona
296,lifeandstyle/2022/sep/30/houseplant-of-the-week-african-spear-plant,Life and style,Houseplant of the week: African spear plant,"Happy in any light and capable of surviving weeks of neglect, this is the closest real plant you can get to a fake one",https://www.theguardian.com/lifeandstyle/2022/aug/12/houseplant-of-the-week-string-of-pearls,Life and style; Homes; Interiors; Plants; Houseplants
322,lifeandstyle/2023/mar/24/spring-into-action-five-easy-affordable-gardening-tasks-now-winter-is-over,Life and style,"Spring into action: five easy, affordable gardening tasks now winter is over",Cold snaps and unseasonably warm spells have played havoc with my garden. But now it’s time to get to work – and I have a few ideas,https://www.theguardian.com/lifeandstyle/2023/jan/13/how-to-start-a-sustainable-affordable-garden-right-now; https://www.chilternseeds.co.uk/flowers/hardy-perennials; https://www.rhs.org.uk/propagation/layering; https://www.theguardian.com/lifeandstyle/2016/mar/12/alys-fowler-upwards-self-clinging-climbers-verticals; https://www.theguardian.com/lifeandstyle/2020/aug/08/dont-add-water-be-inspired-plant-beautiful-dry-garden; https://www.bethchatto.co.uk; https://www.potatohouse.co.uk,Gardens; Gardening advice; Life and style; Plants; Soil; Environment
351,lifeandstyle/2022/feb/18/houseplant-of-the-week-rubber-plant,Life and style,Houseplant of the week: rubber plant,"This glossy, tall and long-lasting plant is a thing of eastern beauty – just don’t let your dog or cat chew on it",https://www.theguardian.com/lifeandstyle/2022/feb/04/houseplant-of-the-week-aloe-vera,Interiors; Life and style; Homes
365,lifeandstyle/2022/oct/28/how-to-grow-a-community-orchard,Life and style,How to grow a community orchard: ‘The real value is the connection to others and to nature’,"Small, traditional orchards are making a comeback, providing havens for wildlife and bringing communities together. Our writer picked up his rake and joined in",https://www.overton-biodiversity.org/; https://www.theguardian.com/environment/2022/mar/24/blossom-falls-80-of-small-orchards-in-england-and-wales-lost-since-1900; https://www.buildingconservation.com/articles/traditional-orchards/traditional-orchards.htm; https://www.nationaltrust.org.uk/press-release/national-trust-vows-to-bring-back-the-blossom-as-new-research-reveals-massive-drop-in-orchards-since-1900s; https://www.theorchardproject.org.uk; https://www.theguardian.com/lifeandstyle/2022/mar/02/how-to-cultivate-wellbeing-through-gardening; https://www.rhs.org.uk/fruit/fruit-trees/rootstocks; https://www.rhs.org.uk/plants/74563/i-malus-domestica-i-james-grieve-(d)/details; https://www.rhs.org.uk/plants/74563/i-malus-domestica-i-james-grieve-(d)/details; https://www.rhs.org.uk/plants/63304/i-malus-domestica-i-howgate-wonder-(c)/details; https://www.rhs.org.uk/plants/63304/i-malus-domestica-i-howgate-wonder-(c)/details; https://www.rhs.org.uk/plants/86954/i-prunus-domestica-i-victoria-(d)/details; https://www.rhs.org.uk/plants/11217/i-morus-nigra-i-(f)/details; https://www.rhs.org.uk/plants/59056/i-prunus-avium-i-stella-(f)/details; http://www.theorchardproject.org.uk,Gardens; Life and style; Trees and forests; Volunteering; Plants; Environment
398,books/2022/apr/20/top-10-books-about-gardening-grounding-lulah-ellender,Books,Top 10 books about gardening,"Going beyond how-to guides, these books encompass fiction, history, poetry and ecology to show how gardens can be places of liberation as well as beauty",https://guardianbookshop.com/grounding-9781783786978; https://www.theguardian.com/books/2022/apr/10/grounding-by-lulah-ellender-review-a-literary-hymn-to-gardening; https://guardianbookshop.com/elizabeth-and-her-german-garden-9781784872328; https://guardianbookshop.com/elizabeth-and-her-german-garden-9781784872328; https://guardianbookshop.com/elizabeth-and-her-german-garden-9781784872328; https://guardianbookshop.com/elizabeth-and-her-german-garden-9781784872328; https://www.theguardian.com/books/2018/apr/27/olivia-laing-derek-jarman-modern-nature; https://www.theguardian.com/film/2020/jul/21/derek-jarman-prospect-cottage-dungeness-kent-garden-museum-london; https://guardianbookshop.com/braiding-sweetgrass-9780141991955; https://guardianbookshop.com/the-well-gardened-mind-9780008100735; https://guardianbookshop.com/the-well-tempered-garden-9781780227825; https://guardianbookshop.com/the-morville-hours-9780747598237; https://www.simonandschuster.co.uk/authors/David-Hoffmann/460358263; https://guardianbookshop.com/the-edible-garden-9781846079740; https://www.theguardian.com/lifeandstyle/series/alys-fowler-s-gardening-column; https://www.theguardian.com/books/2019/jul/17/top-10-queer-rural-books; https://guardianbookshop.com/wild-iris-9781857542233; https://www.theguardian.com/lifeandstyle/2017/jan/21/why-january-is-the-month-for-gardening-books; https://guardianbookshop.com/grounding-9781783786978,House and garden books; Gardening advice; Books; Culture; Life and style; Jamaica Kincaid; Louise Glück; Poetry; Fiction; Derek Jarman; Autobiography and memoir
400,lifeandstyle/2021/nov/13/brighten-the-winter-darkness-with-a-bowl-of-irises,Life and style,Brighten the winter darkness with a bowl of irises,Plant now for indoor flowering and enjoy delicate blooms and a gentle scent during chilly January,https://www.theguardian.com/tv-and-radio/sex-education; https://www.theguardian.com/lifeandstyle/2021/oct/09/things-to-do-in-the-garden-this-autumn-best-thing-you-can--is-very-little; https://www.naturalbulbs.co.uk/specialty-bulbs/644-631-iris-reticulata-harmony-bio.html; https://www.organicbulbs.com/autumn-bulbs/iris-reticulata-harmony,Life and style; Gardening advice; Gardens; Winter; Hobbies
573,lifeandstyle/2018/sep/01/why-you-should-grow-ashitaba,Life and style,Why you should grow Ashitaba,"The Angelica known as ‘tomorrow’s leaf’ isn’t just a pretty plant, it also fed the samurai and is thought to boost longevity",https://www.rhs.org.uk/Plants/1274/i-Angelica-archangelica-i/Details; https://www.rhs.org.uk/Plants/1275/i-Angelica-gigas-i/Details; https://www.theguardian.com/lifeandstyle/2018/aug/04/how-to-care-for-roses,Gardening advice; Gardens; Health & wellbeing; Life and style
596,lifeandstyle/2019/dec/07/dreaming-of-a-green-christmas-make-your-own-sustainable-tree,Life and style,Dreaming of a green Christmas: make your own sustainable tree,"Upcycled bike wheels, shredded magazines and papier-mâché baubles… We challenged three eco-minded creators to design a festive tree – with spectacular results",http://www.demelzahill.com/branch; https://www.thenaturaldyeworks.com/; https://www.aerende.co.uk/; https://www.studio306.co.uk/; https://www.workshop.ltd/; https://www.foldswrap.com/; http://hannahbullivant.com; http://www.robiwalters.com/; https://www.plasticfreepledge.com/; https://www.sas.org.uk/; https://www.ghostgear.org/; http://www.clairepotterdesign.com/theecospot/category/project-net%C2%B7worth/; http://clairepotterdesign.com/,Christmas; Interiors; Life and style; Homes; Design; Art and design; Ethical and green living
874,lifeandstyle/gardening-blog/2016/jan/14/chelsea-flower-show-2016-ones-to-watch,Life and style,Chelsea flower show 2016: ones to watch,Jane Perrone picks out some of the most intriguing garden designs for this year’s Chelsea flower show,https://www.jekkasherbfarm.com/; http://www.stjohnshospice.org.uk/; https://www.meningitisnow.org/support-us/news-centre/news-stories/chelsea-flower-show-anniversary-garden-unveiled/; https://www.rhs.org.uk/shows-events/rhs-chelsea-flower-show/exhibitors/2016/gardens/the-brewin-dolphin-garden; https://www.rhs.org.uk/shows-events/rhs-chelsea-flower-show/exhibitors/2016/gardens/a-suffolk-retreat; http://www.julietdesigns.co.uk/; http://www.modernslaverygarden.com; https://en.wikipedia.org/wiki/Aloe_polyphylla,Chelsea flower show; Gardens; Life and style
884,lifeandstyle/2016/may/24/the-best-of-the-chelsea-flower-show,Life and style,The best of the Chelsea flower show,"This year’s gold and silver medallists at Chelsea, from the Telegraph garden’s bronze fins to a garden for car enthusiasts",NaN,Chelsea flower show; Life and style; Gardens; UK news
894,environment/2015/jun/07/are-pot-plants-more-eco-friendly-than-cut-flowers,Environment,Are pot plants more eco friendly than cut flowers?,The global cut-flower industry is a behemoth to be reckoned with – but it’s not straightforward with pot plants either,http://www.fairtrade.org.uk/; http://www.florverde.org/; http://www.ethicaltrade.org/; http://www.theguardian.com/sustainable-business/2015/apr/30/heidelberg-cement-encourages-biodiversity-in-quarries; http://truecostmovie.com/,Ethical and green living; Environment; Life and style
940,lifeandstyle/gardening-blog/2015/aug/12/how-to-get-your-august-garden-back-in-shape,Life and style,How to get your August garden back in shape,"Do you feel like your summer colour has vacated the plot? Lucy Chamberlain, head gardener at East Donyland Hall in Essex, explains ten easy ways to entice it back.",http://www.perrywood.co.uk/; https://www.rhs.org.uk/advice/profile?PID=346; http://www.clematisinternational.com/page31.html; https://www.rhs.org.uk/Plants/94399/i-Clematis-i-Countess-of-Lovelace-(EL)/Details?returnurl=%2Fplants%2Fclimbers%3Fcontext%3Db%25253D144%252526hf%25253D12%252526l%25253Den%252526s%25253Ddesc%25252528plant_merged%25252529%252526sl%25253Dplants%252526r%25253Df%2525252Fplant_plant_type%2525252Fclimbers%26s%3Ddesc(plant_merged)%26page%3D13%26aliaspath%3D%252fplants%252fclimbers; https://www.rhs.org.uk/plants/search-results?form-mode=false&query=phormium; https://www.rhs.org.uk/Plants/97746/Cotinus-coggygria-Royal-Purple/Details; http://www.theguardian.com/lifeandstyle/2015/aug/02/garden-jobs-for-august; https://twitter.com/@bramble36,Gardens; Life and style
1010,lifeandstyle/2014/mar/09/planting-trees-for-the-future,Life and style,Gardens: trees of life,"Planting a tree that will almost certainly outlive you is a humbling experience – especially if it's a native oak, says Dan Pearson",NaN,Gardening advice; Gardens; Life and style
1081,lifeandstyle/2013/nov/29/gardens-rose-cuttings-hardwood,Life and style,Gardens: roses on their own roots,"<p>Don't listen to breeders, roses grow stronger and healthier on their own roots and now is the time to propagate, says <strong>Lucy Bellamy</strong></p>",http://davesgarden.com/guides/pf/go/64595/; https://www.davidaustinroses.com/american/showrose.asp?showr=6255; http://www.rhs.org.uk/Gardens/Harlow-Carr/About-Harlow-Carr/Plant-of-the-month/June/Rosa--Buff-Beauty-; http://www.davidaustinroses.com/english/Showrose.asp?Showr=6837; http://www.botanic.cam.ac.uk/Botanic/Plant.aspx?p=27&ix=20&pid=0&prcid=0&ppid=0; http://apps.rhs.org.uk/plantselector/plant?plantid=1670; http://www.bbc.co.uk/gardening/plants/plant_finder/plant_pages/3393.shtml,Gardens; Life and style

***
All of the articles are closer to gardening than to healthy ageing.
***

In [17]:
guardian_out = guardian_out[guardian_out['topic']!=8]

#### Cleaning topic-7

***
['nsw', 'covid 19', 'labor', 'vaccine', 'australians', 'queensland', 'coronavirus',<br>
'federal', 'court', 'premier', 'reports', 'election', 'abc', 'yesterday', 'liberal',<br>
'israel', 'dawson', 'referendum', 'virus', 'coalition', 'tuesday', 'vaccination',<br>
'vaccinated', 'variant', 'indigenous', 'opposition', 'quarantine', 'morrison', 'inquiry', 'hancock']
***

In [19]:
topic_7 = guardian_out[guardian_out['topic']==7]

In [20]:
topic_7[['id','section','headline','trailText', 'links','tags']]

                                                                                                                                                                     id  \
207                                                    theobserver/commentisfree/2024/apr/28/learn-lessons-covid-before-another-deadly-disease-strikes-observer-letters
222                                                                                                           us-news/2024/jan/15/covid-flu-rsv-mask-policies-hospitals
293           australia-news/live/2025/apr/25/australia-election-2025-live-anthony-albanese-peter-dutton-anzac-day-dawn-ceremony-campaign-labor-hastie-coalition-ntwnfb
310                                                      australia-news/2023/may/23/end-of-native-logging-in-victoria-a-monumental-win-for-forests-say-conservationists
315                                               australia-news/2023/mar/30/covid-vaccine-booster-doses-only-needed-for-high-risk-groups-who-world-health-organization
334                                                                   society/2022/aug/31/most-extraordinary-geoffrey-cumming-wows-melbourne-with-250m-medical-donation
345                                           australia-news/2021/jul/17/secret-weapon-unflappable-kerry-chant-faces-toughest-challenge-yet-as-nsw-covid-outbreak-grows
346       australia-news/live/2025/may/14/australia-news-live-anthony-albanese-jakarta-subianto-liberal-coalition-sussan-ley-energy-trade-tariffs-russia-defence-ntwnfb
350                                                   australia-news/live/2025/jun/26/defence-spending-nsw-queensland-parliament-banks-predict-rate-cuts-in-july-ntwnfb
399                                                     australia-news/2022/jan/18/five-great-reads-an-american-downton-parental-impostor-syndrome-and-a-70s-must-watch
422                      australia-news/live/2024/jul/11/australia-news-live-fire-factory-melbourne-alice-springs-curfew-violence-extended-northern-territory-nt-police
448                  australia-news/live/2024/may/08/news-live-russian-hacker-cybercrime-military-south-china-sea-inflation-interest-rates-cost-of-living-health-vaping
457   australia-news/live/2023/oct/17/australia-politics-live-question-time-israel-palestine-hamas-anthony-albanese-peter-dutton-indigenous-treaty-truth-cost-of-living
462                                                                           world/2021/jan/17/first-fruits-of-vaccine-rollout-should-be-seen-in-weeks-experts-predict
467                                                                                    world/2020/dec/11/oxford-covid-vaccine-to-be-combined-with-sputnik-jab-for-trial
470                                                                                           world/2021/jan/07/boris-johnson-announces-national-vaccine-booking-scheme
487                                                  australia-news/live/2023/feb/19/australia-news-live-nsw-election-dominic-perrottet-linda-reynolds-brittany-higgins
498                                                                                                             commentisfree/2021/jan/08/covid-wave-healthcare-workers
506                   australia-news/live/2023/mar/17/fifa-saudi-sponsor-productivity-report-boost-wages-sydney-trains-fortescue-bottle-water-submarines-albanese-aukus
518                                                                         world/2020/may/07/from-brisbane-to-puerto-rico-how-a-38m-covid-19-test-kit-deal-turned-sour
528                                                                           world/2020/may/15/churches-consider-ticketing-when-they-reopen-after-lockdown-coronavirus
568                                        australia-news/live/2022/aug/30/australia-news-chris-dawson-covid-isolation-politics-anthony-albanese-skills-summit-tax-cuts
619                                                                                        world/2020/apr/20/nhs-frontline-meet-people-risking-lives-tackle-coronavirus
636                                 world/live/2021/dec/07/covid-news-live-omicron-likely-to-become-dominant-variant-harvard-researcher-says-france-to-close-nightclubs
656                                       australia-news/live/2021/may/17/australia-news-live-questions-over-india-covid-test-results-as-repatriation-flights-under-way
660                       australia-news/live/2021/may/18/australia-news-live-business-sector-reopen-borders-covid-coronavirus-scott-morisson-anthony-albanese-vaccines
666                                         australia-news/live/2021/jun/11/australia-coronavirus-live-news-tga-reveals-fatal-clotting-case-one-dead-in-victoria-floods
668                   australia-news/live/2021/apr/20/australia-news-live-states-simplified-speedier-covid-19-vaccine-rollout-tasmania-western-australia-climate-crisis
677                                                                          politics/live/2021/jan/07/coronavirus-boris-johnson-latest-updates-covid-donald-trump-live
694                                           world/live/2020/may/20/coronavirus-australia-news-nsw-travel-restrictions-qld-victoria-covid-manufacturing-latest-updates
749                                                      australia-news/live/2020/sep/14/coronavirus-live-update-melbourne-victoria-nsw-qld-border-lockdown-latest-news
775                                                            world/live/2020/apr/28/uk-coronavirus-live-news-minutes-silence-to-commemorate-key-workers-who-have-died
926                                                                                     world/2014/jun/20/pregnant-asylum-seekers-nauru-transferred-australia-abortions
1015                                                                               global-development/2015/feb/13/ebola-spending-positive-healthcare-legacy-west-africa
1138                                                                                                            commentisfree/2013/jan/01/norovirus-infectious-diseases
1153                                                                                            business/marketforceslive/2012/aug/14/ftse-close-lowest-trading-volumes

                 section  \
207    From the Observer
222              US news
293       Australia news
310       Australia news
315       Australia news
334              Society
345       Australia news
346       Australia news
350       Australia news
399       Australia news
422       Australia news
448       Australia news
457       Australia news
462           World news
467           World news
470           World news
487       Australia news
498              Opinion
506       Australia news
518           World news
528           World news
568       Australia news
619           World news
636           World news
656       Australia news
660       Australia news
666       Australia news
668       Australia news
677             Politics
694           World news
749       Australia news
775             Politics
926           World news
1015  Global development
1138             Opinion
1153            Business

                                                                                                                         headline  \
207                                                      We must learn the lessons of Covid before another deadly disease strikes
222                                                Mask policies return in US as respiratory viruses threaten to strain hospitals
293                                                                                  Anzac Day 2025 live updates – as it happened
310                                        End of native logging in Victoria ‘a monumental win for forests’, say conservationists
315                                                        Covid vaccine booster doses only needed for high-risk groups, WHO says
334                                             ‘Most extraordinary’: Geoffrey Cumming wows Melbourne with $250m medical donation
345                             ‘Secret weapon’: unflappable Kerry Chant faces toughest challenge yet as NSW Covid outbreak grows
346                                   PM says Australia has ‘no more important relationship’ than with Indonesia – as it happened
350                                               War of words between online safety chief and YouTube continues – as it happened
399                                        Five Great Reads: an American Downton, parental impostor syndrome and a 70s must-watch
422                                                             Woman and teenage girl found dead in Sydney home – as it happened
448                  Labor councillor stands by vote to ban same-sex parenting books in Sydney council libraries – as it happened
457                                                      Labor senator condemns Israel’s military action in Gaza – as it happened
462                                                                     First fruits of vaccine rollout 'should be seen in weeks'
467                                                                Oxford Covid vaccine to be combined with Sputnik jab for trial
470                                                    Boris Johnson vows to vaccinate all elderly care home residents this month
487                   Back safeguard mechanism to ‘put climate wars behind us’, Labor urges Coalition and Greens – as it happened
498                                             This Covid wave has trapped healthcare workers in a nightmare. I see it every day
506                                     Four arrested after climate protesters occupy Dominic Perrottet’s office – as it happened
518                                                   From Brisbane to Puerto Rico: how a $38m Covid-19 test kit deal turned sour
528                                                            UK churches consider ticketing for when they reopen after lockdown
568                                                       Lawyer reveals dementia diagnosis after guilty verdict – as it happened
619                                                                   On the frontline: meet the NHS workers tackling coronavirus
636                            Fury in UK after video about No 10 party; early signs Omicron more transmissible – as it happened
656   Scott Morrison to meet Jacinda Ardern in New Zealand; passenger from India flight tests positive for Covid – as it happened
660                          Calls for dedicated quarantine facilities; airline boss’s border comments condemned – as it happened
666                                                                   More than 100,000 Victorians without power – as it happened
668                                    Covid committee demands vaccination timetable; two consent videos removed – as it happened
677             UK coronavirus: hospital numbers in east and south-east England more than double first wave peak – as it happened
694                                       Australian deputy CMO says no medical reason for state border closures – as it happened
749                                     Victoria reports 35 new cases and seven deaths as NSW records four cases – as it happened
775           UK coronavirus live: government to publish daily care home deaths as hospital toll rises to 21,678 - as it happened
926                                                       Pregnant asylum seekers on Nauru transferred to Australia for abortions
1015                                                       Ebola spending: will lack of a positive legacy turn dollars to dolour?
1138                                                                                               Norovirus deserves our respect
1153                                 FTSE closes up but trading volumes at historic lows due to Olympic fatigue and eurozone woes

                                                                                                                                                                                                                                               trailText  \
207                                                                                                                                                     Why has so little been done to make indoor spaces safer, to stop the spread of airborne viruses?
222                                                                                                                                       Covid, flu and RSV rates creep up as vaccination rates for all three remain low, worrying healthcare providers
293                                                                                                                                                                                                                              This blog is now closed
310                                                                                                                                                   The shutting down of the industry six years earlier than scheduled comes after decades of conflict
315                                                                                                                                      Guidance says strong population-level immunity due to infection and vaccination means boosters have less impact
334                                                                                                                                             One of largest donations in Australian history to go towards therapeutic treatments for global pandemics
345                                                                                                  Immersed in facts, the chief health officer has ignored politics, criticism and even broken glasses to guide Gladys Berejiklian’s pandemic response
346                                                                                                                                                                                                                              This blog is now closed
350                                                                                                                                                                                                                              This blog is now closed
399                                                                                                            Guardian Australia’s summer wrap of brilliant writing and juicy journalism selected by our lifestyle editor, <strong>Alyx Gorman</strong>
422                                                                                                                                                                                                                             This blog is now closed.
448                                                                                                                                                                                                                              This blog is now closed
457                                                                                                                                                                                                                             This blog is now closed.
462                                                                                                                                                             Experts agree that the impact of the jab will vary regionally and among different groups
467                                                                                                                                                               UK and Russian scientists to explore whether vaccines given together improves efficacy
470                                                                                                                                                                     PM announces national jab booking scheme in England amid more grim Covid figures
487                                                                                                                                                                                                                              This blog is now closed
498                                                                                                                                         Celebrating healthcare workers as ‘heroes’ obscures the systemic failures that forced us to fill the gap<br>
506                                                                                                                                     Six teenagers and a dozen adults occupied NSW premier’s office, protesting approval of new coal and gas projects
518                                                                                              The obscure Australian company Promedical said it could supply kits desperately needed by the US territory. But its claims did not stand up to scrutiny
528                                                                                                                                                                Measure could help ensure physical distancing once coronavirus controls are eased<br>
568                                                                                                                                                                                                                              This blog is now closed
619   From emergency arrivals to critical care, photojournalist Jonny Weeks was given extraordinary access to University hospital in Coventry to document the Covid-19 pandemic. This photo essay captures the contributions of those who save our lives
636                                                                                                      Early indications Omicron more transmissible than Delta, says Boris Johnson; Nicola Sturgeon says staff should work from home until mid-January
656                                                                                                                                                                                                                              This blog is now closed
660                                                                            Businessman Govind Kant is the second Australian to die from coronavirus in India; Morrison condemns Virgin boss’s ‘insensitive’ border comments. This blog is now closed
666                                                                                                                                                                                                                              This blog is now closed
668                                                                                                                                               Queensland premier says people need confidence in vaccine before mass rollout. This blog is now closed
677                                                                                         Latest updates: hospitals in England treating 50% more Covid patients now than in April; vaccine may be needed every six months; UK reports 52,618 new cases
694                                                                                Deputy chief medical officer Paul Kelly says there is no medical justifications for states keeping borders shut and offers to brief premiers. This blog is now closed
749                                                                                                       Victoria to turn roads and footpaths into dining spaces to help hospitality industry as Queensland border row deepens. Follow all today’s news

***
The majority of topics are related to coronavirus and have little in common to do with healthy ageing.
***

In [22]:
guardian_out = guardian_out[guardian_out['topic']!=7]

#### Cleaning topic-6

***
['fridge', 'blender', 'sauce', 'bowl', 'pesto', 'flour', 'espresso', 'chef',<br>
'stove', 'recipe', 'machines', 'marmalade', 'seeds', 'mixer', 'stir', 'dough',<br>
'flavour', 'tsp', 'gas', 'ketchup', 'cooked', 'chilli', 'grill', 'boil', 'recipes',<br>
'baking', 'noodles', 'chopped', 'warranty', 'bake']
***

In [23]:
topic_6 = guardian_out[guardian_out['topic']==6]

In [24]:
topic_6[['id','section','headline','trailText', 'links','tags']]

                                                                                                                                 id  \
175                                                                                    thefilter/2025/jul/11/best-camping-stoves-uk
187                                    environment/2024/apr/18/ways-keep-leftover-food-fresh-opened-tins-cut-avocados-chefs-experts
238                    lifeandstyle/2023/dec/13/how-to-maximise-your-fridges-efficiency-dont-trust-the-settings-theyre-aspirational
247                                                                                             thefilter/2025/jan/07/best-blenders
251       lifeandstyle/2023/nov/29/stir-fry-recipe-simple-easy-vegetarian-vegan-snow-peas-tempeh-green-beans-chilli-alice-zaslavsky
265                                                               thefilter/2024/oct/30/best-stand-mixers-kitchen-kneading-whipping
270                                                                                      thefilter/2024/nov/21/best-coffee-machines
274                                                                     food/2023/jul/03/should-you-refrigerate-ketchup-store-shelf
299                                  food/2023/sep/03/masala-zone-piccadilly-circus-a-profoundly-cheering-venture-restaurant-review
427             food/2021/oct/25/long-hours-gruelling-work-at-gourmet-travellers-restaurant-awards-winner-calls-for-industry-change
458                                                    food/2020/feb/09/forget-wellness-marmalade-is-the-key-to-a-long-healthy-life
525                                             lifeandstyle/2021/jul/31/oslo-pram-guy-teenage-vacuum-expert-niche-online-reviewers
579                                                 lifeandstyle/2020/jun/21/family-chefs-restaurateurs-following-fathers-footsteps
755                                          lifeandstyle/2018/jan/21/lescargot-london-lets-hope-it-never-changes-restaurant-review
760                                          travel/2018/feb/02/food-tour-cilento-campania-italy-mediterranean-diet-delia-morinelli
765                                       lifeandstyle/2018/jul/12/ready-for-your-selfie-why-public-spaces-are-being-insta-designed
772                                                                 lifeandstyle/2018/feb/16/dan-dan-noodles-recipe-felicity-cloake
797                                  lifeandstyle/2017/feb/10/vasco-and-piero-pavilion-london-w1-restaurant-review-marina-oloughlin
807                                                                      lifeandstyle/2017/aug/06/how-britain-fell-for-wetherspoons
888                                                     lifeandstyle/2016/oct/16/ofm-awards-2016-best-food-personality-jamie-oliver
897                                                                                 environment/2015/oct/18/eco-guide-to-eating-out
907                                   lifeandstyle/2016/feb/25/lahori-charga-recipe-cottage-cheese-chapati-sumayya-usmani-residency
908                    lifeandstyle/2016/may/26/seasonal-recipe-ideas-for-beetroot-leeks-root-vegetables-oliver-rowe-cook-residency
935                                                       lifeandstyle/2015/dec/17/how-bake-perfect-biscotti-coffee-felicity-cloake
944   lifeandstyle/2015/dec/17/apple-chutney-recipe-rhubarb-and-ginger-shrub-homemade-preserves-jarring-kylee-newton-cook-residency
963                                                    lifeandstyle/wordofmouth/2015/jan/26/chef-neil-rankin-why-i-hate-food-trends
975                                                    tv-and-radio/2015/mar/19/bbc-food-television-diet-giles-coren-kew-on-a-plate
987                                        lifeandstyle/2016/feb/21/los-angeles-fast-food-revolution-locol-roy-cho-daniel-patterson
992                                                            lifeandstyle/2015/may/03/percy-and-founders-london-restaurant-review
1012                                                    sustainable-business/2014/oct/21/waste-free-willy-wonka-packaging-consumers
1056                                                  lifeandstyle/2014/jan/25/seaweed-cracker-biscuits-stag-bakeries-isle-of-lewis
1057                                                       lifeandstyle/2014/sep/17/joys-repair-cafe-mad-max-kitkat-nice-cup-of-tea
1083                                                                        lifeandstyle/2014/jun/10/25-recipe-ideas-leftover-pesto
1122                                                    lifeandstyle/the-northerner/2013/feb/20/yorkshire-business-self-sufficiency
1141                                                                           travel/2012/oct/29/newmarket-sausages-european-award
1142                                                                                   lifeandstyle/2011/aug/31/le-caprice-30-years
1146                                                         lifeandstyle/wordofmouth/2012/oct/03/street-food-next-stop-supermarket
1150                                                                              travel/2013/may/10/mumbai-parsi-cafes-indian-food
1157                                                         lifeandstyle/2013/may/10/hugh-fearnley-whittingstall-recipes-sourdough
1176                                                                       lifeandstyle/2012/dec/02/joe-trivelli-dinner-at-my-place
1195                                                                            lifeandstyle/2013/mar/07/live-chat-yotam-ottolenghi
1212                                                                     lifeandstyle/wordofmouth/2011/oct/25/whats-eaten-at-diwali
1251                                                     lifeandstyle/2011/aug/14/riverford-farm-recipes-chicken-and-chocolate-cake
1270                                                                        world/2010/jun/20/pope-unhealthy-childhood-recipes-book
1282                                                                lifeandstyle/wordofmouth/2010/aug/04/british-apple-season-start
1294                                                            lifeandstyle/wordofmouth/2010/feb/02/francesco-mazzei-pizza-express

                            section  \
175                      The Filter
187                     Environment
238                  Life and style
247                      The Filter
251                  Life and style
265                      The Filter
270                      The Filter
274                            Food
299                            Food
427                            Food
458                            Food
525                  Life and style
579                  Life and style
755                            Food
760                          Travel
765                  Life and style
772                            Food
797                  Life and style
807                  Life and style
888                            Food
897                     Environment
907                            Food
908                  Life and style
935                            Food
944                  Life and style
963                            Food
975              Television & radio
987                            Food
992                            Food
1012  Guardian Sustainable Business
1056                 Life and style
1057                 Life and style
1083                 Life and style
1122                           Food
1141                           Food
1142                           Food
1146                 Life and style
1150                         Travel
1157                 Life and style
1176                           Food
1195                           Food
1212                 Life and style
1251                 Life and style
1270                     World news
1282                 Life and style
1294                 Life and style

                                                                                                   headline  \
175                                      The best camping stoves for cooking like a pro in the wild, tested
187                               How to store half a lemon – and 17 other ways to keep leftover food fresh
238             How to maximise your fridge’s efficiency: ‘Don’t trust the settings – they’re aspirational’
247                      The best blenders to blitz like a pro, tried and tested, from Ninja to Nutribullet
251   No wok? No worries: Alice Zaslavsky’s vegetarian snow pea stir-fry with tempeh ‘mince’ and chilli oil
265                                         The best stand mixers to make baking easier – and even more fun
270    The best coffee machines for your home in 2025: your morning brew made easy, according to our expert
274                                       Lost in the sauce: does ketchup go in the fridge or on the shelf?
299                     Masala Zone, Piccadilly Circus: ‘A profoundly cheering venture’ – restaurant review
427     ‘Long hours, gruelling work’: Gourmet Traveller’s restaurant award winner calls for industry change
458                                         Forget 'wellness'. Marmalade is the key to a long, healthy life
525   From Oslo pram guy to the teenage vacuum expert: inside the obsessive world of niche online reviewers
579                              In the family: the chefs and restaurateurs following in father's footsteps
755                                   L’Escargot, London: ‘Let’s hope it never changes’ – restaurant review
760                                             Inspired by Italy’s Delia: a food tour of Cilento, Campania
765                                                      Is Instagram changing the way we design the world?
772                                                                 How to make the perfect dan dan noodles
797                Vasco & Piero’s Pavilion, London W1: ‘This Soho old-timer is rammed’ – restaurant review
807                                                                      How Britain fell for Wetherspoon’s
888                                                     OFM Awards 2016 best food personality: Jamie Oliver
897                                                                             The eco guide to eating out
907                                          Recipes for spiced chicken and chapatis from northern Pakistan
908                                             How to make the most of the season’s leeks, beets and roots
935                                                                        How to make the perfect biscotti
944                                             How to make chutneys, jams and cordials for Christmas gifts
963                                                                Why are we so obsessed with food trends?
975                                                      Does the BBC need to go on a food television diet?
987                                                                    The Los Angeles fast food revolution
992                                                                     Percy & Founders: restaurant review
1012                            Waste-free, Willy Wonka packaging is coming but are consumers ready for it?
1056                                                   Crackers: the baker who puts seaweed in his biscuits
1057                                 The joys of a repair cafe: Mad Max with a KitKat and a nice cup of tea
1083                                                                     25 recipe ideas for leftover pesto
1122                           'Money is like blood – it needs to circulate for local economies to survive'
1141                                                                        Newmarket sausages win EU award
1142                                                            Le Caprice: 30 years and still going strong
1146                                                               Street food's next stop: the supermarket
1150                                                                            Mumbai's Parsi cafe culture
1157                              Bread with character: Hugh Fearnley-Whittingstall's recipes for sourdough
1176                                                                       Joe Trivelli: dinner at my place
1195                                                                            Live chat: Yotam Ottolenghi
1212                                                                                What's eaten at Diwali?
1251                                            Riverford Farm recipes: pork with fennel and chocolate cake
1270                                      Eat up your veal, lard and stuffed pigeon - and you might be pope
1282                                                                        British apple season is upon us
1294                                                       Will Francesco Mazzei deliver for Pizza Express?

                                                                                                                                                                                                                                                      trailText  \
175                                                                                                                                         Forget soggy sandwiches! From pocket-sized burners to multi-hob wonders, these camping stoves came top in our tests
187                                                                                                                       What should you do with opened tins, cut avocados and egg yolks that weren’t required in your recipe? Chefs and food experts tell all
238                                                                                                                 The Australian summer is as good a time as any to make sure your fridge and freezer are in peak condition – and to buy your own thermometer
247                                                                                                                                                 Whizzing up smoothies, soups and purees will be a breeze with our top-rated portable, jug and hand blenders
251                                                                                       If you’ve ever been cursed with a soggy stir-fry, the cookbook author advocates a blanch-and-batch approach that works wonders in her easy vegan spring-summer recipe
265                                                                                      Whether for kneading dough or whipping up a heavy cake mix, these kitchen workhorses chosen by our expert will have you multitasking and saving muscle power with ease
270                                                                                      Discover your perfect coffee maker with our tried-and-tested recommendations, from top-rated brands such as Sage and Nespresso to capsule and manual espresso machines
274                                                                                                                                                            Brands offer different advice on the perennial question. Food experts err on the side of caution
299                                                                                                                                                          One of London’s most opulent rooms finally gets a worthy restaurant, and even the pricing is a joy
427                                                                                                                                                                       Back after a two-year break, the accolades acknowledge an industry in a state of flux
458                                                                                       Since mid-January, readers have been writing in about their marmalade-making habits – and reflections on longevity. Here are the letters we have published so far ...
525                                                                 Wade can tell you the best pram for a tall parent; Matthew knows which cleaner has superior suction power. But how do you become a respected reviewer on the wild west of the internet?<br>
579                                                                                                   To celebrate Father’s Day, Jess and Richie Corrigan, Nathan Outlaw and Missy Malik-Flynn talk about how their upbringings influenced their career choices
755                                                                                                                                      Snails, chandeliers, and suited waiters… this isn’t just a French restaurant, it’s a Soho institution, says Jay Rayner
760                                                  Delia Morinelli helped bring the Mediterranean diet to world attention in the 1970s. Now she’s opened her first restaurant in the Cilento, a quiet corner of Italy that’s perfect for a culinary road trip
765                                                                                    First it was our food. Now whole neighbourhoods are being styled to look good on social media. But by viewing the world through a screen, do we miss the bigger picture?
772                                                                                                                                          A quick noodle dish laced with smoky chilli oil and tingly Sichuan pepper is the ideal choice for Chinese new year
797                                                                                                                                             No fireworks, no dishes created for social media, no mouthy chefs poncing about: no wonder it’s such a success
807                                                                                                         Wetherspoon’s has won a special place in our hearts, bourgeois snobbery notwithstanding. As it nears its 40th birthday, Ed Cumming visits his local
888                                     Not content with more restaurants, books and promoting the sugar tax, Jamie Oliver is now ready to challenge Theresa May over the obesity crisis. And then there are 46 million Brazilian chickens that need his help …
897                                                                                                                   Some restaurants pay lip service to environmental issues. It’s up to us to seek out those that put their ethics first, writes Lucy Siegle
907    <strong>Cook residency: </strong>Childhood holidays in Pakistan’s north recall fertile valleys of lush produce, where the Silk Road gave rise to diverse yet uncomplicated dishes, like this whole spiced chicken and herbed cottage cheese chapatis ...
908             <strong>Cook residency: </strong>Following the food calendar doesn’t only mean you take advantage of vegetables with a fleeting season. With some ideas for those perennial stalwarts up your sleeve – beets, roots, leeks – you’re all set ...
935                                                                                                 These classic Italian biscuits are super-crunchy and great for dipping in coffee, but should you bake them twice? And is a low oven temperature sufficient?
944   <strong>Cook Residency: </strong>Homemade preserves make inexpensive presents that can last for ages. These recipes for an apple and ale chutney, a rhubarb and ginger “shrub” and clementine and whisky marmalade are sure to be gratefully received ...
963                                                                   <strong>Neil Rankin: </strong>I run a barbecue restaurant, but don’t call me trendy – cooking over coals is a time-honoured cuisine. Food gimmicks, on the other hand, really get my goat

***
The topics are mostly related to food, so I will get rid of them.
***

In [26]:
guardian_out = guardian_out[guardian_out['topic']!=6]

#### Cleaning topic-5

***
['divorce', 'romantic', 'marry', 'sonya', 'jackie', 'maureen', 'romance',<br>
'trish', 'toby', 'gay', 'phil', 'divorced', 'marriages', 'emmy', 'mike',<br>
'getting married', 'ted', 'weddings', 'pamela', 'pete', 'vegas', 'brad',<br>
'pregnant', 'kathleen', 'fiona', 'boyfriend', 'adrian', 'dating', 'friendships', 'christ']
***

In [27]:
topic_5 = guardian_out[guardian_out['topic']==5]

In [28]:
topic_5[['id','section','headline','trailText', 'links','tags']]

,id,section,headline,trailText,links,tags
167,lifeandstyle/2024/jan/09/foot-fetish-wife-no-longer-let-me-near-her-feet,Life and style,"Since I admitted to a foot fetish, my wife will no longer let me near her feet",It felt like a way to connect but now she has withdrawn from me. I feel as if sex is always on her terms,mailto:private.lives@theguardian.com; https://www.theguardian.com/letters-terms,Life and style; Sex
174,wellness/2024/feb/02/prioritize-friend-relationships-loneliness-health,Wellness,"‘Face-to-face, hip-to-hip’ friendships help us live longer – so let’s prioritize them","Loneliness is a health epidemic, but friendships can lower blood pressure and cardiovascular reactivity – and make us happier",https://www.insider.com/best-girlfriends-build-stunning-home-where-they-will-retire-together-2019-7; https://www.theguardian.com/wellness/2024/feb/01/dog-etiquette-public-training-covid; https://www.theguardian.com/books/2024/jan/29/is-it-ever-okay-to-ghost-a-friend-its-complicated-gyan-yankovich; https://www.census.gov/library/stories/2023/07/marriage-divorce-rates.html; https://www.psychologytoday.com/us/articles/201009/revenge-the-introvert; https://www.vice.com/en/article/pg7njy/enjoy-your-friends-before-you-lose-them-all-at-age-25; https://www.cdc.gov/aging/publications/features/lonely-older-adults.html; https://journals.sagepub.com/doi/10.1177/1745691614568352; https://journals.plos.org/plosmedicine/article?id=10.1371/journal.pmed.1000316; https://www.hhs.gov/sites/default/files/surgeon-general-social-connection-advisory.pdf; https://www.sciencedirect.com/science/article/pii/S235282732200310X?via%3Dihub; https://www.thefriendshipblog.com/about-the-friendship-doctor/the-friendship-doctor/; https://interactive.guim.co.uk/uploader/embed/2023/11/archive-zip/giv-13425SACijDhlvmi7/; https://www.bluezones.com/2018/08/moai-this-tradition-is-why-okinawan-people-live-longer-better/; https://www.bluezones.com/about/history/; https://academic.oup.com/abm/article/33/3/278/4569368; https://academic.oup.com/abm/article/33/3/278/4569368; https://www.sciencedirect.com/science/article/abs/pii/S002210310800070X?via%3Dihub; https://www.healthline.com/health/relationships/chosen-family#examples; https://www.theguardian.com/wellness/2024/jan/30/communal-living-parenting-isolation-babies-families,Well actually; Friendship; Mental health; Health; Life and style; Relationships; Ageing; Society
208,commentisfree/2023/sep/11/the-secrets-of-a-happy-relationship-sleep-luck-and-takeaways,Opinion,"The secrets of a happy relationship? Sleep, luck and takeaways","A survey asking couples why they stayed together proves the uselessness of people’s opinions. It’s like asking centenarians the secret of a long life, writes Emma Beddington",https://www.theguardian.com/tv-and-radio/2023/sep/07/love-death-review-elizabeth-olsen-is-mesmerising-as-an-axe-murderer; https://www.guinnessworldrecords.com/news/2020/10/the-worlds-oldest-people-and-their-secrets-to-a-long-life-632895,Relationships; Life and style
279,lifeandstyle/2023/jul/01/this-is-how-we-do-it-as-weve-aged-weve-adapted-we-now-love-morning-sex-,Life and style,"This is how we do it: ‘As we’ve aged, we’ve adapted: we now love morning sex’","Clyde and Audrey start each day with a spooning session, and allow each other fantasies",mailto:sexlives@theguardian.com,Life and style; Sex; Relationships
280,books/ng-interactive/2024/may/07/anne-lamott-author-interview,Wellness,"Anne Lamott on love, sobriety and reaching 70: ‘All I’ve learned, I’ve learned because the abyss swallowed me’","The American author’s 20th book reads as a series of parables on grace. In an interview, she reflects on a life she thought she wouldn’t get to live",https://www.nytimes.com/2024/04/21/books/review/anne-lamott-somehow.html; https://www.penguinrandomhouse.com/books/734582/somehow-by-anne-lamott/; https://www.kirkusreviews.com/book-reviews/anne-lamott/bird-by-bird/; https://www.washingtonpost.com/opinions/2023/12/20/aging-friendship-outdoors/; https://podcasts.apple.com/ca/podcast/live-forever-8-surrender/id1676536478?i=1000621344964; https://www.thecrimson.com/article/1927/1/11/mahatma-gandhi-says-he-believes-in/; https://988lifeline.org/; https://988lifeline.org/chat/; https://www.crisistextline.org/; https://www.samaritans.org/; mailto:jo@samaritans.org; mailto:jo@samaritans.ie; https://www.lifeline.org.au/; http://www.befrienders.org/,Well actually; Books; US news; Relationships; Family; Friendship; Ageing; Life and style; Culture
304,lifeandstyle/2022/dec/06/my-new-partner-and-i-havent-had-sex-for-two-weeks-last-time-i-tried-they-were-too-tired-should-we-split-up,Life and style,"My new partner and I haven’t had sex for two weeks. Last time I tried, they were too tired. Should we split up?",I really like them and they say they fancy me. But I’m not getting what I need,mailto:private.lives@theguardian.com; https://www.theguardian.com/letters-terms,Life and style; Sex
307,lifeandstyle/article/2024/jul/13/as-my-wife-and-i-left-our-wedding-i-thought-ive-made-a-huge-mistake-i-love-ted-from-closeted-men-to-a-major-age-gap-finding-love-against-all-odds,Life and style,"‘As my wife and I left our wedding, I thought: I’ve made a huge mistake. I love Ted’: from closeted men to a major age gap – finding love against all odds",They defied expectations – and their critics – to find soulmates,https://www.tedkincaid.com/about/; https://www.instagram.com/blackmarriagetherapy/,Relationships; Family; Life and style; Marriage
380,lifeandstyle/2021/feb/21/how-we-stay-together-i-keep-saying-im-not-the-spring-chicken-you-married,Life and style,How we stay together: 'I keep saying I'm not the spring chicken you married!',"After 50 years together, Nunzio and Maureen know the secret to longevity is always backing themselves and never giving up",https://www.theguardian.com/lifeandstyle/2020/aug/02/easy-to-meet-hard-to-stay-together-share-your-stories; https://www.theguardian.com/lifeandstyle/2021/feb/14/how-we-stay-together-weve-both-had-our-fair-share-of-near-death-experiences; https://www.theguardian.com/australia-news/audio/2021/feb/15/valentines-how-phil-and-jackie-stay-together; https://www.theguardian.com/uk/2000/apr/14/juliahartleybrewer1; https://www.theguardian.com/lifeandstyle/2020/aug/02/easy-to-meet-hard-to-stay-together-share-your-stories,Relationships; Family; Life and style
413,lifeandstyle/2022/feb/13/romantic-love-different-ways-to-connect,Life and style,Romantic love isn’t what it’s cracked up to be. Here’s why we don’t need it,"For increasing numbers of people finding ‘the one’ is no longer the ideal, and there are different, equally valid, ways to connect",https://www.theguardian.com/lifeandstyle/love-and-sex; https://www.theguardian.com/lifeandstyle/relationships; https://www.theguardian.com/lifeandstyle/2017/jul/23/polyamory-new-way-to-love-men-women-sex-relationships-elf-lyons; https://www.theguardian.com/commentisfree/2021/dec/16/knights-princes-scottish-castle-women-christmas-romcoms-fairytales,Relationships; Love & Friendship; Life and style
450,commentisfree/2021/may/15/marriage-bill-melinda-present-alternatives-hadley-freeman,Opinion,Marriage doesn’t work (just ask Bill and Melinda) – so let me present some alternatives,I find the idea of being legally bound to my partner unacceptably claustrophobic,https://www.theguardian.com/technology/2021/may/03/bill-gates-divorce-melinda-gates-billionaire-couple; https://www.dailymail.co.uk/news/article-9539085/The-biggest-divorce-Bezos-Bill-Melinda-Gates-divide-Microsoft-fortune.html; https://www.gavi.org/investing-gavi/funding/donor-profiles/bill-melinda-gates-foundation; https://observer.com/2020/12/how-bill-gates-helped-make-the-covid-19-vaccine-possible/; https://www.bbc.co.uk/news/world-us-canada-56984733; https://www.theguardian.com/film/mel-brooks; https://www.theguardian.com/world/2005/jun/08/usa.film; https://www.theguardian.com/film/2008/sep/27/paulnewman.usa1; https://www.theguardian.com/film/2020/oct/31/helena-bonham-carter-divorce-is-cruel-but-some-parts-are-to-be-recommended; https://www.theguardian.com/film/2020/nov/03/the-fall-of-johnny-depp-how-the-worlds-most-beautiful-movie-star-turned-very-ugly; https://www.theguardian.com/culture/vanessa-paradis; https://www.theguardian.com/culture/amy-poehler; https://www.theguardian.com/culture/will-arnett; https://www.theguardian.com/lifeandstyle/2018/sep/25/truth-about-polyamory-monogamy-open-relationships; https://www.theguardian.com/lifeandstyle/commentisfree/2021/apr/10/a-rich-new-york-playboy-with-a-famous-surname-what-if-jfk-jr-had-lived,Marriage; Melinda French Gates; Bill Gates; Divorce; Life and style; Family; US news
474,lifeandstyle/2020/feb/14/six-things-we-learned-from-asking-couples-how-they-stay-together,Life and style,Valentine's Day: six things we learned from asking couples how they stay together,"From respecting each other’s independence to seeking professional help if needed, long-lasting couples share their wisdom on love",https://www.theguardian.com/lifeandstyle/2019/oct/04/relationships-tell-us-how-you-stay-together; https://www.theguardian.com/lifeandstyle/2020/feb/08/how-we-stay-together-we-dont-waste-precious-time-with-sulking-and-the-silent-treatment; https://www.theguardian.com/lifeandstyle/2020/feb/01/how-we-stay-together-embrace-all-of-the-peculiarities-of-the-other-person; https://www.theguardian.com/lifeandstyle/2019/oct/05/how-we-stay-together-productive-conflict-commitment-and-48-hour-holidays; https://www.theguardian.com/lifeandstyle/2020/feb/08/how-we-stay-together-we-dont-waste-precious-time-with-sulking-and-the-silent-treatment; https://www.theguardian.com/lifeandstyle/2020/feb/08/how-we-stay-together-we-dont-waste-precious-time-with-sulking-and-the-silent-treatment; https://www.theguardian.com/lifeandstyle/2019/nov/09/how-we-stay-together-you-dont-have-to-make-the-other-person-be-just-like-you; https://www.theguardian.com/lifeandstyle/2019/nov/22/how-we-stay-together-love-at-first-sight-is-a-thing; https://www.theguardian.com/lifeandstyle/2020/feb/01/how-we-stay-together-embrace-all-of-the-peculiarities-of-the-other-person; https://www.theguardian.com/lifeandstyle/2019/nov/15/how-we-stay-together-i-think-you-should-fight-every-day-resolve-and-move-on; https://www.theguardian.com/lifeandstyle/2019/oct/12/how-we-stay-together-shared-humour-and-enough-time-apart; https://www.theguardian.com/lifeandstyle/2020/jan/11/how-we-stay-together-find-a-way-to-love-that-thing-you-want-to-change; https://www.theguardian.com/australia-news/audio/2020/feb/12/how-do-you-make-love-last; https://www.theguardian.com/lifeandstyle/2019/dec/07/how-we-stay-together-when-something-bad-happens-it-doesnt-mean-everything-is-bad; https://www.theguardian.com/lifeandstyle/2019/oct/04/relationships-tell-us-how-you-stay-together,Australian lifestyle; Relationships; Life and style; Family; Valentine's Day
483,lifeandstyle/2021/mar/28/how-we-stay-together-i-think-you-need-to-be-challenged,Life and style,How we stay together: 'I think you need to be challenged',"For a moment in their early years, it looked like Sabir and Emmy Samtani would part ways. Now they have three children and a business together",https://www.theguardian.com/lifeandstyle/2020/aug/02/easy-to-meet-hard-to-stay-together-share-your-stories; https://www.theguardian.com/lifeandstyle/2020/aug/02/easy-to-meet-hard-to-stay-together-share-your-stories,Family; Life and style; Relationships
494,lifeandstyle/2021/feb/14/how-we-stay-together-weve-both-had-our-fair-share-of-near-death-experiences,Life and style,How we stay together: 'We've both had our fair share of near-death experiences',High school sweethearts Brad and Sonya have spent more of their lives as a couple than apart – but it hasn’t always been an easy road,https://www.theguardian.com/lifeandstyle/2020/aug/02/easy-to-meet-hard-to-stay-together-share-your-stories; https://www.theguardian.com/lifeandstyle/2021/feb/07/how-we-stay-together-turns-out-were-really-stubborn; https://www.theguardian.com/lifeandstyle/2021/jan/30/how-we-stay-together-just-share-where-you-stand-and-what-you-like-and-what-you-didnt-like; https://www.theguardian.com/lifeandstyle/2020/aug/02/easy-to-meet-hard-to-stay-together-share-your-stories,Relationships; Family; Australia news; Life and style
499,lifeandstyle/2021/feb/07/how-we-stay-together-turns-out-were-really-stubborn,Life and style,How we stay together: 'Turns out we’re really stubborn',"High school sweethearts Bronwen Write and Emma Wilson no longer face a ‘perfect storm of teenage angst’, but their fondness for each other’s company endures",https://www.theguardian.com/lifeandstyle/2020/aug/02/easy-to-meet-hard-to-stay-together-share-your-stories; https://www.theguardian.com/lifeandstyle/2021/jan/30/how-we-stay-together-just-share-where-you-stand-and-what-you-like-and-what-you-didnt-like; https://www.theguardian.com/lifeandstyle/2020/dec/20/how-we-stay-together-i-believe-in-some-sort-of-brain-waves-that-connect; https://www.theguardian.com/lifeandstyle/2020/aug/02/easy-to-meet-hard-to-stay-together-share-your-stories,Life and style; Family; Marriage; LGBTQ+ rights; Australia news; Relationships
505,uk-news/2020/feb/29/how-one-couple-said-i-do-to-romantic-leap-year-traditions,UK news,How one couple said 'I do' to romantic Leap Year traditions,And a great-great grandmother enjoyed her 100th birthday with only her 25th party on the day,NaN,UK news; Brighton; Life and style
512,lifeandstyle/2020/dec/06/how-we-stay-together-its-like-were-one-person-with-two-personalities,Life and style,How we stay together: 'It’s like we’re one person with two personalities',What began as a light office flirtation has resulted in more than three decades of deep commitment for Jackie Rees and Phil Kafcaloudes,https://www.theguardian.com/lifeandstyle/2020/aug/02/easy-to-meet-hard-to-stay-together-share-your-stories; https://www.theguardian.com/lifeandstyle/2020/nov/21/how-we-stay-together-there-is-no-magic-cookbook-of-relationships; https://www.theguardian.com/lifeandstyle/2020/nov/15/how-we-stay-together-we-had-to-share-the-workload; https://www.theguardian.com/lifeandstyle/2020/aug/02/easy-to-meet-hard-to-stay-together-share-your-stories,Life and style; Relationships; Marriage; Family
550,lifeandstyle/2019/feb/22/what-does-lasting-romance-look-like-for-millennials,Life and style,What does lasting romance look like for millennials?,"Perhaps it’s my age, but I think a lot about beginnings and rarely of endings. The divorce invitation came as a surprise",https://www.theguardian.com/lifeandstyle/2019/feb/01/every-time-i-tried-to-go-vegan-my-mum-hailed-it-as-a-fad,Marriage; Life and style; Family; Divorce; Relationships
563,lifeandstyle/2020/jun/07/how-we-stay-together-you-cant-spend-all-your-life-worrying-about-the-other-person,Life and style,How we stay together: 'You can't spend all your life worrying about the other person',"Born on opposite sides of the world, Mike and Trish have managed to maintain their independence, even during 10 years at sea on a small boat together",https://www.theguardian.com/lifeandstyle/2020/apr/25/love-in-a-time-of-covid-tell-us-how-you-stay-together; https://www.theguardian.com/lifeandstyle/2020/may/31/how-we-stay-together-pretty-much-on-a-daily-basis-theres-adjustments; https://www.theguardian.com/lifeandstyle/2020/may/24/how-we-stay-together-if-he-wouldnt-dance-it-wouldnt-have-worked; https://www.theguardian.com/lifeandstyle/2020/apr/25/love-in-a-time-of-covid-tell-us-how-you-stay-together,Life and style; Relationships; Marriage; Tasmania; Australia news
585,lifeandstyle/2020/feb/08/how-we-stay-together-we-dont-waste-precious-time-with-sulking-and-the-silent-treatment,Life and style,How we stay together: we don't waste precious time with sulking and the silent treatment,"One time punks, Sarah Munn and David Swain have kept their shared spirit of rebellion – even though their lives look much different today",https://www.theguardian.com/lifeandstyle/2019/oct/04/relationships-tell-us-how-you-stay-together; https://www.theguardian.com/music/2012/may/01/bow-wow-wow-review; https://www.theguardian.com/lifeandstyle/2020/feb/01/how-we-stay-together-embrace-all-of-the-peculiarities-of-the-other-person; https://www.theguardian.com/lifeandstyle/2020/jan/25/how-we-stay-together-you-have-to-be-best-friends-as-well-as-spouses; https://www.theguardian.com/lifeandstyle/2019/oct/04/relationships-tell-us-how-you-stay-together,Life and style; Relationships; Australia news; Adelaide; South Australia holidays
594,lifeandstyle/2020/feb/01/how-we-stay-together-embrace-all-of-the-peculiarities-of-the-other-person,Life and style,How we stay together: 'Embrace all of the peculiarities of the other person',"Whether its embarking on huge adventures, or relishing mutual laziness Max and Toby Boon have always known how to make it count",https://www.theguardian.com/books/2011/apr/09/jackie-collins-interview; https://www.theguardian.com/lifeandstyle/2019/oct/04/relationships-tell-us-how-you-stay-together; https://www.theguardian.com/lifeandstyle/2020/jan/25/how-we-stay-together-you-have-to-be-best-friends-as-well-as-spouses; https://www.theguardian.com/lifeandstyle/2020/jan/18/how-we-stay-together-the-sense-of-trust-that-we-had-in-each-other-as-friends; https://www.theguardian.com/lifeandstyle/2019/oct/04/relationships-tell-us-how-you-stay-together,Life and style; Relationships; Australia news; Same-sex marriage postal survey; LGBTQ+ rights; Australian lifestyle
736,lifeandstyle/2017/may/29/my-girlfriend-and-i-rarely-have-sex-now-weve-moved-in-together,Life and style,My girlfriend and I rarely have sex now we’ve moved in together,We are both working and studying and our relationship is no longer exciting or romantic,mailto:private.lives@theguardian.com,Sex; Relationships; Life and style
773,lifeandstyle/2017/oct/07/the-con-behind-every-wedding,Life and style,The con behind every wedding,"With her marriage on the rocks, one writer struggles to reconcile her cynicism about happily-ever-after as her own children rush to tie the knot",https://www.theguardian.com/lifeandstyle/2017/jan/21/the-affair-that-saved-our-marriage; https://www.theguardian.com/lifeandstyle/shortcuts/2017/jun/12/rise-silver-splitters-elderly-renters-retired-divorcees-trend; https://www.theguardian.com/lifeandstyle/2017/apr/15/celibate-marriage-sex-sexless-relationship; https://www.theguardian.com/lifeandstyle/2017/jul/01/how-much-do-your-kids-really-need-to-know-about-your-sex-life,Family; Life and style; Marriage; Parents and parenting; Divorce
841,lifeandstyle/2016/mar/28/i-have-as-much-sex-as-i-like-and-its-great-but-i-want-something-more,Life and style,I have as much sex as I like – and it’s great – but I want something more\r\n,"I’m having plenty of fun, but I really hope for commitment and a partner",mailto:private.lives@theguardian.com,Sex; Relationships; Life and style

***
Somewhat related articles:<br>
wellness/2024/feb/02/prioritize-friend-relationships-loneliness-health - 174<br>
Everything else should be deleted.
***

In [31]:
guardian_out = guardian_out[(guardian_out['topic'] != 5) | (guardian_out.index == 174)]

#### Cleaning topic-4

***
['elephants', 'conservation', 'bat', 'bats', 'ivory', 'whales', 'velvet',<br>
'populations', 'nest', 'whale', 'ants', 'attenborough', 'temperate', 'habitat',<br>
'endangered', 'david attenborough', 'crabs', 'mouse', 'breeding', 'arctic', 'mimicry',<br>
'crab', 'turtles', 'tunnel', 'predators', 'dolphins', 'nestling', 'chernobyl', 'wolves', 'national park']
***

In [36]:
topic_4 = guardian_out[guardian_out['topic']==4]

In [44]:
from itables import show
import itables.options as opt

opt.maxBytes = 0  # Disable size limit for large tables

show(topic_4[['headline', 'trailText']], scrollY="500px", scrollCollapse=True)

***
Articles somewhat related to research:<br>
African killifish may hold key to stopping ageing in humans	 - 534<br>
Other articles have little to do with healthy ageing of humans, mainly focusing on the ageing of animals.<br>
***

In [46]:
guardian_out = guardian_out[(guardian_out['topic'] != 4) | (guardian_out.index == 534)]

#### Cleaning topic-3

***
['fasting', 'obesity', 'diets', 'calories', 'mushrooms', 'obese', 'longo',<br>
'weight loss', 'overweight', 'intake', 'junk', 'junk food', 'vitamin', 'tofu',<br>
'resveratrol', 'dietary', 'patel', 'yoghurt', 'type diabetes', 'hockney',<br>
'eating disorders', 'dairy', 'vitamins', 'nutrients', 'calorie', 'glp', 'dieting',<br>
'compounds', 'creme', 'weight gain']
***

In [48]:
topic_3 = guardian_out[guardian_out['topic']==3]

In [50]:
show(topic_3[['section','headline','trailText','tags']], scrollY="500px", scrollCollapse=True)

***
Unrelated topics:
Who needs quinoa? 17 overlooked and affordable superfoods, from peas and potatoes to popcorn and even sugar	- 49
‘I was scared to even eat the vegetables in my fridge’: the eating disorder that focuses on food purity	- 84
All these health scares are making me ill. I need someone to tell me croissants are good for you	
Microdosing: how ‘off-label’ use of weight loss jabs is spreading from US to UK	
Ultra-processed food? Forever chemicals? Declining birth rates? What’s behind rising cancer in the under-50s?	
Keep taking the vitamin D tablets	- 621
Science and mince pies don’t make a good Christmas cocktail	 - 658
The Mediterranean diet is in retreat even in Italy. What now for the foodies’ ideal?	- 697
John Yudkin was a visionary on the harm caused by sugar	- 875
It’s nonsense that the poor can’t cook or eat well cheaply	- 895
Shellshock! Cadbury comes clean on Creme Egg chocolate change	- 971
Do 'superfoods' really exist?	- 1008
Fat China: how are policymakers tackling rising obesity?	 - 1037
David Hockney should stick to painting	 - 1125

Slightly-related topics:
‘I was scared to even eat the vegetables in my fridge’: the eating disorder that focuses on food purity	
From cold showers to hot tomatoes: 10 of Michael Mosley’s top health tips	- 183
The actor and influencer has been called out for glorifying restricted eating. What is it with the rich and their weird ideas about wellness?	- 197
Intermittent fasting: what is it, how does it work – and is it right for you?	- 219
The truth about protein: how to get enough – at every age	- 273
Scientists hope weight-loss drugs could treat addiction and dementia	- 283
18 foods to boost your health – and the planet’s	 - 319
Environmental toxins are worsening obesity pandemic, say scientists	- 424
Does turmeric’s reputation translate into real health benefits?	 - 426
Forget the fries – here’s how we should really get our five a day	 - 443
Extreme fasting: how Silicon Valley is rebranding eating disorders	 - 459
Dopamine fasting: why Silicon Valley is trying to avoid all forms of stimulation	 - 464
British women live shorter lives than most other Europeans	 - 570
US researchers seek to end carbs v fat 'diet wars'	- 627
Modern tribes: the diet guru	- 654
Fit in my 40s: ‘I hadn’t realised that fermentation is so vital to the gut’	 - 690
Hidden, destructive costs of a vegan diet	- 713
Raw deal: is there really any benefit to an uncooked diet?	 - 725
The male diet boom: why men are tackling their midlife obesity crisis	- 745
Michael Mosley: ‘No male in my family has made it beyond 72’	- 901
My hot tips for parents with a fat kid: feed them fun, kindness and dignity	 - 986
Fasting facts: is the 5:2 diet too good to be true?	- 1007
11 ways to eat more healthily – without ruining your life	- 1022
Can resveratrol – the 'wonder chemical' in red wine – live up to the hype?	 - 1064
This column will change your life: clearer costs, better decisions	 - 1094
Sugar is bad for us and we should all stop eating it – right?	- 1121
Keep yourself healthy. Way better than asking a doctor like me to do it for you	- 1145
Oh dear. I'm eating myself to death	- 1158
Public health: saving lives and spending less	 - 1185
High-heel orgasms? Colon cleanses? Celebrity 'science' is a bad joke	- 1190
Have we had our fill of water?	 - 1275
Consider tofu	- 1286

Related-topics:
Life expectancy growth stalls across Europe as England sees sharpest decline, say researchers	 - 42
Becoming obese under age of 30 ‘raises risk of early death by at least 75%’	- 55
Daily multivitamins do not help people live longer, major study finds	- 133
Mushroom magic: why the latest health fad might be on to something	- 492
The Silicon Valley execs who don't eat for days: 'It's not dieting, it's biohacking'	 - 546
Red and processed meat can shorten life, say scientists	- 601
Frequent spicy meals linked to human longevity	- 727
Get off the treadmill: the art of living well in the age of plenty	- 751
Long life? I think we’ve cracked it	- 936
Diets high in meat, eggs and dairy could be as harmful to health as smoking	- 1035
Life is now. Don't let the professional anti-smoking brigade ruin it	- 1043
The secret of the Mediterranean diet? There is no secret	 - 1046
Calorie restriction doesn't slow ageing, monkey study suggests	 - 1079
TV review: Horizon: Eat, Fast and Live Longer; Britain's High Street Gamble	 - 1171
Consider yoghurt	- 1264
***