**Analyze the topics**
--

We have collected the topics with the the help of the two sentence transformers: "allenai-specter" and "all-MiniLM-L6-v2". The former one is for academic purposes while the latter one is for the short texts.

In [36]:
import pandas as pd
df_allenai = pd.read_csv("analyzed_data_new_allenai.csv")
df_allenai = df_allenai.drop('Unnamed: 0', axis=1)
topics_allenai = pd.read_csv("youtube-topics-new-allenai.csv")

In [38]:
df_minilm = pd.read_csv("analyzed_data_new_MiniLm.csv")
topics_minilm = pd.read_csv("youtube-topics-new-MiniLm.csv")

In [58]:
topics_allenai

,Topic,Count,Name,Representation,Representative_Docs
0,-1,9635,-1_biohacking_facial_aging_skin,"['biohacking', 'facial', 'aging', 'skin', 'hea...","['LCN Anti-aging Manicure ', ""Maxine Warsh Fac..."
1,0,2652,0_healthy_healthy aging_longevity_aging,"['healthy', 'healthy aging', 'longevity', 'agi...",['Int: Wise Healthy Aging1 Wise and Healthy Ag...
2,1,844,1_skincare_routine_skincare routine_serum,"['skincare', 'routine', 'skincare routine', 's...",['Anti Aging Skincare Routine For Women Over 5...
3,2,600,2_nutrition_foods_diet_aging foods,"['nutrition', 'foods', 'diet', 'aging foods', ...","[""The Longevity Diet - A Full Day Of Eating In..."
4,3,587,3_biohacking_el_en_que,"['biohacking', 'el', 'en', 'que', 'biohacker',...","['Biohacking y sus beneficios para la salud, e..."
...,...,...,...,...,...
178,177,11,177_laser_dual_fraxel_frank,"['laser', 'dual', 'fraxel', 'frank', 'med', 's...",['Anti-Aging Fraxel Dual Laser A Fall Routine ...
179,178,11,178_business_innovation_award_success,"['business', 'innovation', 'award', 'success',...","[""OCBJ Family Owned Business Awards- Longevity..."
180,179,10,179_excerpt_self_children_social,"['excerpt', 'self', 'children', 'social', 'ric...","[""Biohacking, Psychedelics, &amp; Physical Mas..."
181,180,10,180_technology_safe_supports_ways,"['technology', 'safe', 'supports', 'ways', 'se...",['Technology &amp; Healthy Aging: If It Were O...
182,181,10,181_facelift_late_multi_rejuvenate,"['facelift', 'late', 'multi', 'rejuvenate', 't...",['What can facelift surgery treat? #facialplas...

In [60]:
topics_minilm

,Topic,Count,Name,Representation,Representative_Docs
0,-1,8459,-1_aging_longevity_healthy_nootropics,"['aging', 'longevity', 'healthy', 'nootropics'...",['How To Choose The Right Anti-Aging Cream Ant...
1,0,11355,0_rejuvenation_aging_anti_anti aging,"['rejuvenation', 'aging', 'anti', 'anti aging'...",['Nootropics for Hangovers: High Level Strateg...
2,1,484,1_biohacking_la_en_el,"['biohacking', 'la', 'en', 'el', 'para', 'que'...","['Biohacking y sus beneficios para la salud, e..."
3,2,185,2_rejuvenation_rejuvenation episode_game_play,"['rejuvenation', 'rejuvenation episode', 'game...",['Let&#39;s Play Pokemon Rejuvenation: Episode...
4,3,91,3_klaus_workout_denmark_2012,"['klaus', 'workout', 'denmark', '2012', '2011'...",['MUTANT athlete KLAUS RIIS will be at FIBO 20...
5,4,78,4_exercise video_ball_demonstrating_exercise,"['exercise video', 'ball', 'demonstrating', 'e...",['REJUVENATION | DELTOID FLIES Rejuvenation Pr...
6,5,76,5_sleep_melatonin_night_issues,"['sleep', 'melatonin', 'night', 'issues', 'hea...","['Yeah Yeah Yeah, Sleep... ""I\'ll Sleep When I..."
7,6,71,6_plasma_cutter_stick_140,"['plasma', 'cutter', 'stick', '140', 'longevit...",['LONGEVITY WELDALL TIG WELDER PLASMA CUTTER C...
8,7,70,7_vaginal_vaginal rejuvenation_rejuvenation_tr...,"['vaginal', 'vaginal rejuvenation', 'rejuvenat...","['⭕️ Vaginal Rejuvenation (Vaginoplasty, Vagin..."
9,8,62,8_record_mix_original_guide,"['record', 'mix', 'original', 'guide', 'album'...","[""1992 - Nootropic &#39;Elevation&#39; (Origin..."
10,9,60,9_bulletproof_asprey_bulletproof coffee_dave a...,"['bulletproof', 'asprey', 'bulletproof coffee'...",['Bulletproof Exec Dave Asprey on BioHacking a...
11,10,60,10_на_39 play_let 39_nzt,"['на', '39 play', 'let 39', 'nzt', 'hd', 'play...",['ЭФФЕКТИВНЫЕ упражнения для омоложения! #омол...
12,11,56,11_ovarian_fertility_prp_platelet rich,"['ovarian', 'fertility', 'prp', 'platelet rich...",['Ovarian PRP (Platelet-Rich Plasma)|Ovarian R...
13,12,47,12_arduino_shield_game_games,"['arduino', 'shield', 'game', 'games', 'video'...",['Video Overlay Goggles Arduino Using an Ardui...
14,13,47,13_oral_dental_oral health_dentistry,"['oral', 'dental', 'oral health', 'dentistry',...",['Nutrition and Oral Health | Aging Matters | ...
15,14,46,14_limitless_cooper_nzt_movie,"['limitless', 'cooper', 'nzt', 'movie', 'trail...",['Limitless Movie Review from Haunted Flower G...
16,15,45,15_diy bio_diy_bio_pellet,"['diy bio', 'diy', 'bio', 'pellet', 'water', '...","['DIY bio pellets reactor 1 ', 'DIY Bio-Pellet..."
17,16,41,16_microneedling_exosomes_micro_skin,"['microneedling', 'exosomes', 'micro', 'skin',...",['How does MICRONEEDLING reverse signs of agin...
18,17,37,17_lower_song_brains_click http,"['lower', 'song', 'brains', 'click http', 'pla...","[""Lower Dens - Propagation After just 76 secon..."
19,18,37,18_aubrey_grey_aubrey grey_escape velocity,"['aubrey', 'grey', 'aubrey grey', 'escape velo...",['Aubrey de Grey | Longevity Myth Busting Alli...
20,19,36,19_neurofeedback_brain_therapy_http,"['neurofeedback', 'brain', 'therapy', 'http', ...",['Is Neurofeedback Therapy a Useful Therapy? I...
21,20,36,20_playlists_com ref_ref_visit https,"['playlists', 'com ref', 'ref', 'visit https',...",['Jiu Jitsu Self-Defense vs Weapons - How to D...
22,21,33,21_alpha brain_alpha_onnit_brain,"['alpha brain', 'alpha', 'onnit', 'brain', 'ro...",['Joey Diaz gives his thoughts on Alpha Brain ...
23,22,30,22_nootropics_fuel_motivation_edge,"['nootropics', 'fuel', 'motivation', 'edge', '...",['Korvyx - No Fairy Dust #brainupgrade #nootro...
24,23,29,23_smart drugs_drugs_smart_le,"['smart drugs', 'drugs', 'smart', 'le', 'di', ...",['Quanto costano le smart drugs? LOMBARDIA CHA...
25,24,29,24_rich plasma_platelet rich_platelet_prp,"['rich plasma', 'platelet rich', 'platelet', '...",['PRP Hair Restoration - Hair Rejuvenation and...
26,25,28,25_choline_alpha gpc_gpc_alpha,"['choline', 'alpha gpc', 'gpc', 'alpha', 'comp...",['Alpha-GPC - Nootropics Information What is A...
27,26,28,26_blue_blue zones_zones_buettner,"['blue', 'blue zones', 'zones', 'buettner', 'd...",['The Shocking Secret Of Blue Zones Longevity!...
28,27,27,27_pain_best pain_longevityusa_com longevityusa,"['pain', 'best pain', 'longevityusa', 'com lon...",['Best Pain Cream; Longevity Rehab 1000 Best P...
29,28,27,28_gut_microbiome_bacteria_gut health,"['gut', 'microbiome', 'bacteria', 'gut health'...",['Gut Microbes &amp; Longevity: The Secret to ...
30,29,26,29_stave age_stave_drugs stave_develop smart,"['stave age', 'stave', 'drugs stave', 'develop...",['llive discussion can we should we devel...
31,30,26,30_mushroom_mushrooms_mane_lion,"['mushroom', 'mushrooms', 'mane', 'lion', 'noo...","[""🍄 Day 7: Explore the Unique Chaga Mushroom w..."
32,31,25,31_bulletproof radio_radio_bulletproof_podcast,"['bulletproof radio', 'radio', 'bulletproof', ...",['Bulletproof Radio Q&amp;A - #207 Why you sho...
33,32,24,32_rapid_coupon_coupon code_code,"['rapid', 'coupon', 'coupon code', 'code', 'di...","[""Rapid Fire Q&amp;A Nootropics Rapid Fire Q&A..."
34,33,23,33_las_las vegas_vegas_sports center,"['las', 'las vegas', 'vegas', 'sports center',...","[""Soccer Las Vegas | Longevity Sports Center L..."
35,34,23,34_stave_drugs stave_stave age_related memory,"['stave', 'drugs stave', 'stave age', 'related...",['Can we should we develop smart drugs to stav...
36,35,23,35_tea_herb_spring_herbs,"['tea', 'herb', 'spring', 'herbs', 'http goo',...",['Gynostemma Supreme Tonic Tea Formula (Spring...
37,36,22,36_bulletproof_bulletproof biohacking_biohacki...,"['bulletproof', 'bulletproof biohacking', 'bio...",['The 2015 Bulletproof Biohacking Conference R...
38,37,22,37_dag_noopept_och_en,"['dag', 'noopept', 'och', 'en', '2014', 'april...","['Dag 13, Nootropics (Noopept + Neurostim), 7..."
39,38,22,38_biohacking village_village_def_25,"['biohacking village', 'village', 'def', '25',...",['DEF CON 25 BioHacking Village - Tim Cannon -...
40,39,22,39_edge exclusive_big think_think edge_videos ...,"['edge exclusive', 'big think', 'think edge', ...",['What is your counsel? New videos DAILY: http...
41,40,21,40_keto_john_dr john_biohacking,"['keto', 'john', 'dr john', 'biohacking', 'md'...",['Biohacking: What is Keto An explanation of w...
42,41,21,41_gum_technique_dr john_dentist,"['gum', 'technique', 'dr john', 'dentist', 'su...",['Pinhole Gum Rejuvenation® | Alternative to g...
43,42,20,42_piel_la_cómo_las,"['piel', 'la', 'cómo', 'las', 'del', 'el', 'qu...",['💆🏻\u200d♀️¿Cómo mejorar la texturade la piel...
44,43,19,43_dog_pets_dogs_shape,"['dog', 'pets', 'dogs', 'shape', 'project', 'h...","[""How to feed your dog (for health and longevi..."
45,44,19,44_theanine_caffeine_review_benefits,"['theanine', 'caffeine', 'review', 'benefits',...",['Top 4 L Theanine Benefits ltheanine #biohack...
46,45,19,45_creatine_muscle_power_strength,"['creatine', 'muscle', 'power', 'strength', 'b...","[""Creatine &amp; Healthy Aging: Myth vs. Reali..."
47,46,19,46_cold_ice_water_actually,"['cold', 'ice', 'water', 'actually', 'usa', 'b...",['Beyond Cold Water Boot Camp USA - Dive Door ...
48,47,19,47_aging 101_101_georgia_know aging,"['aging 101', '101', 'georgia', 'know aging', ...",['AGING 101: Pt 2 Physical Health Normal Agin...
49,48,18,48_silicon_complete_implants_extension,"['silicon', 'complete', 'implants', 'extension...",['27C3 Cybernetics for the Masses - Lepht Anon...
50,49,18,49_magnet_implant_clients_stuff,"['magnet', 'implant', 'clients', 'stuff', 'sho...",['Magnet &amp; Paperclips #5 30 paperclips on ...
51,50,18,50_coffee_drinking_longer_tea,"['coffee', 'drinking', 'longer', 'tea', 'study...",['Drinking up to three cups of coffee daily ma...
52,51,18,51_2600 hope_2600_hope 2008_2008,"['2600 hope', '2600', 'hope 2008', '2008', 'ho...",['2600 - The Last HOPE (2008) - Bagcam_02 2600...
53,52,17,52_hearing_loss_public health_healthy,"['hearing', 'loss', 'public health', 'healthy'...",['CLSA Webinar Series: Hearing loss and health...
54,53,17,53_stress_relief_professionals_teach,"['stress', 'relief', 'professionals', 'teach',...",['Stress Relief Anti Aging Tip Your Top 3 Prio...
55,54,17,54_die_ich_auf_hier,"['die', 'ich', 'auf', 'hier', 'marcus', 'mega'...",['Biohacking ✰ Motorik 2.0 Welcome! Ich bin M...
56,55,16,55_arina_teemu arina_teemu_mindfulness,"['arina', 'teemu arina', 'teemu', 'mindfulness...",['#5 Biohakkerin käsikirja -- Voi erikoisjakso...
57,56,16,56_brush_fan_qvc_information buy,"['brush', 'fan', 'qvc', 'information buy', 'co...",['IT Cosmetics CC Anti-Aging Ombre Radiance Br...
58,57,15,57_garden_tree_mp4_trust,"['garden', 'tree', 'mp4', 'trust', 'descriptio...",['Longevity Garden Benefits.mp4 http://bit.ly/...

***Start analyzing***
-

In [68]:
#for the later convenience
dfa   = df_allenai.copy()     
dfm   = df_minilm.copy()       
tpa   = topics_allenai.copy()  
tpm   = topics_minilm.copy()

In [70]:
# Keep only what's needed from the topics tables
tpa_small = tpa[['Topic', 'Name', 'Representation']].rename(
    columns={'Topic':'topic', 'Name':'topic_name', 'Representation':'topic_repr'}
)
tpm_small = tpm[['Topic', 'Name', 'Representation']].rename(
    columns={'Topic':'topic', 'Name':'topic_name', 'Representation':'topic_repr'}
)

# Left-join so every video row gets the topic label/keywords
dfa = dfa.merge(tpa_small, on='topic', how='left')
dfm = dfm.merge(tpm_small, on='topic', how='left')

In [74]:
def topic_diagnostics(df, topics_df, label):
    n_docs = len(df)
    n_topics = (topics_df['Topic'] != -1).sum()
    outliers = (df['topic'] == -1).sum()
    print(f"[{label}] docs={n_docs:,} | topics={n_topics} | outliers={outliers} ({outliers/n_docs:.2%})")
    display(topics_df.head())

topic_diagnostics(dfa, tpa, "SPECTER")
topic_diagnostics(dfm, tpm, "MiniLM")

[SPECTER] docs=22,295 | topics=182 | outliers=9635 (43.22%)

,Topic,Count,Name,Representation,Representative_Docs
0,-1,9635,-1_biohacking_facial_aging_skin,"['biohacking', 'facial', 'aging', 'skin', 'hea...","['LCN Anti-aging Manicure ', ""Maxine Warsh Fac..."
1,0,2652,0_healthy_healthy aging_longevity_aging,"['healthy', 'healthy aging', 'longevity', 'agi...",['Int: Wise Healthy Aging1 Wise and Healthy Ag...
2,1,844,1_skincare_routine_skincare routine_serum,"['skincare', 'routine', 'skincare routine', 's...",['Anti Aging Skincare Routine For Women Over 5...
3,2,600,2_nutrition_foods_diet_aging foods,"['nutrition', 'foods', 'diet', 'aging foods', ...","[""The Longevity Diet - A Full Day Of Eating In..."
4,3,587,3_biohacking_el_en_que,"['biohacking', 'el', 'en', 'que', 'biohacker',...","['Biohacking y sus beneficios para la salud, e..."

[MiniLM] docs=22,295 | topics=58 | outliers=8459 (37.94%)

,Topic,Count,Name,Representation,Representative_Docs
0,-1,8459,-1_aging_longevity_healthy_nootropics,"['aging', 'longevity', 'healthy', 'nootropics'...",['How To Choose The Right Anti-Aging Cream Ant...
1,0,11355,0_rejuvenation_aging_anti_anti aging,"['rejuvenation', 'aging', 'anti', 'anti aging'...",['Nootropics for Hangovers: High Level Strateg...
2,1,484,1_biohacking_la_en_el,"['biohacking', 'la', 'en', 'el', 'para', 'que'...","['Biohacking y sus beneficios para la salud, e..."
3,2,185,2_rejuvenation_rejuvenation episode_game_play,"['rejuvenation', 'rejuvenation episode', 'game...",['Let&#39;s Play Pokemon Rejuvenation: Episode...
4,3,91,3_klaus_workout_denmark_2012,"['klaus', 'workout', 'denmark', '2012', '2011'...",['MUTANT athlete KLAUS RIIS will be at FIBO 20...

From the above results, it seems like MiniLm worked better to our dataset since there are fewer topics and also 37.94% was considered as noisy. Let's analyze it first

Let's seach for the unrelated topics and delete them. Our strategy will be deleting the unrelated topics and videos and re-run the Bert Topic once again.

In [81]:
dfm[dfm['topic']==1].head(50)

,source,video_id,video_url,title,description,channel,comments,views,likes,comments_count,...,country,date,likes_missing,year,engagement,engagement_rate,text,topic,topic_name,topic_repr
40,YouTube,aiq8G9Gx5qo,https://www.youtube.com/watch?v=aiq8G9Gx5qo,Pontus ströbaek.m4v,NaN,Den Ökända Salong Betong AB,NaN,1235.0,2.0,0.0,...,unknown,2010-01-15,False,2010,2.0,0.001619,Pontus ströbaek.m4v,1,1_biohacking_la_en_el,"['biohacking', 'la', 'en', 'el', 'para', 'que'..."
209,YouTube,U3EXfSecZ94,https://www.youtube.com/watch?v=U3EXfSecZ94,greenwheels.mpg,promofilmpje van electrice auto van green wheels.,Hans Steeman,NaN,2522.0,1.0,0.0,...,unknown,2010-03-08,False,2010,1.0,0.000397,greenwheels.mpg promofilmpje van electrice aut...,1,1_biohacking_la_en_el,"['biohacking', 'la', 'en', 'el', 'para', 'que'..."
364,YouTube,5tnB2fBI0GQ,https://www.youtube.com/watch?v=5tnB2fBI0GQ,Mikocionis Deividas.wmv,Mikocionis Deividas.,ljowkabelov,"Blemba, Maladec ... Perspectyvus Tai sakes :} ...",738.0,4.0,1.0,...,unknown,2010-04-26,False,2010,5.0,0.006775,Mikocionis Deividas.wmv Mikocionis Deividas.,1,1_biohacking_la_en_el,"['biohacking', 'la', 'en', 'el', 'para', 'que'..."
418,YouTube,Y-wRk0us1WY,https://www.youtube.com/watch?v=Y-wRk0us1WY,Gumiarc.3gp,hat ez kurva jo!!!=))=)),iissttii1,NaN,390.0,0.0,0.0,...,unknown,2010-05-10,False,2010,0.0,0.000000,Gumiarc.3gp hat ez kurva jo!!!=))=)),1,1_biohacking_la_en_el,"['biohacking', 'la', 'en', 'el', 'para', 'que'..."
578,YouTube,hTPVY6ev-pY,https://www.youtube.com/watch?v=hTPVY6ev-pY,CPCO3 - BioHacking (1/2),Esta conferencia trabaja sobre los conceptos y...,Campus Party,NaN,3429.0,15.0,0.0,...,unknown,2010-06-30,False,2010,15.0,0.004374,CPCO3 - BioHacking (1/2) Esta conferencia trab...,1,1_biohacking_la_en_el,"['biohacking', 'la', 'en', 'el', 'para', 'que'..."
991,YouTube,34aLp0zj7MQ,https://www.youtube.com/watch?v=34aLp0zj7MQ,Empoisonnement au plomb dans des mines d&#39;o...,"""Plus de 400 enfants"" sont morts d'empoisonnem...",AFP,NaN,450.0,2.0,0.0,...,unknown,2010-10-05,False,2010,2.0,0.004444,Empoisonnement au plomb dans des mines d&#39;o...,1,1_biohacking_la_en_el,"['biohacking', 'la', 'en', 'el', 'para', 'que'..."
1169,YouTube,S7fpZExGF_g,https://www.youtube.com/watch?v=S7fpZExGF_g,Hirndoping - Auswirkungen der Umkehrung von mo...,http://konsumpf.de/?p=6743 Durch die Veränderu...,popscenede,Vollkommen frei erfundene Geschichte mit märch...,13801.0,34.0,5.0,...,unknown,2010-11-07,False,2010,39.0,0.002826,Hirndoping - Auswirkungen der Umkehrung von mo...,1,1_biohacking_la_en_el,"['biohacking', 'la', 'en', 'el', 'para', 'que'..."
1174,YouTube,GzwRZja9JcM,https://www.youtube.com/watch?v=GzwRZja9JcM,Hirndoping - Auswirkungen der Umkehrung von mo...,http://konsumpf.de/?p=6743 Durch die Veränderu...,popscenede,Modafinil hat nichts mit den Amphetaminen zu t...,5625.0,10.0,3.0,...,unknown,2010-11-07,False,2010,13.0,0.002311,Hirndoping - Auswirkungen der Umkehrung von mo...,1,1_biohacking_la_en_el,"['biohacking', 'la', 'en', 'el', 'para', 'que'..."
1426,YouTube,OFYLhuFxHRo,https://www.youtube.com/watch?v=OFYLhuFxHRo,Vivre avec le VIH,Vivre avec le VIH Pulsations TV - 103 - décemb...,Hopitaux Universitaires de Genève,Merci Seigneur 🙏 de m&#39;avoir conduit au Dr ...,25258.0,49.0,10.0,...,unknown,2011-01-03,False,2011,59.0,0.002336,Vivre avec le VIH Vivre avec le VIH Pulsations...,1,1_biohacking_la_en_el,"['biohacking', 'la', 'en', 'el', 'para', 'que'..."
1527,YouTube,Yd01DRZV_NM,https://www.youtube.com/watch?v=Yd01DRZV_NM,Lecenje od heroinske zavisnosti.Zavisnost od o...,Posle 22 godine zloupotrebe raznih vrsta narko...,Naltrexone implants,NaN,1441.0,0.0,0.0,...,unknown,2011-01-26,True,2011,0.0,0.000000,Lecenje od heroinske zavisnosti.Zavisnost od o...,1,1_biohacking_la_en_el,"['biohacking', 'la', 'en', 'el', 'para', 'que'..."
2328,YouTube,-dOyoGX_vkc,https://www.youtube.com/watch?v=-dOyoGX_vkc,"KFJ - БиоРобот [acoustic version at Salve,Bat...",live acoustic version of our track BioRobot at...,KFJofficial,miyvars || :()(; &lt;3 || 10 წელი გასულა &lt;3...,5139.0,39.0,4.0,...,unknown,2011-08-30,False,2011,43.0,0.008367,"KFJ - БиоРобот [acoustic version at Salve,Bat...",1,1_biohacking_la_en_el,"['biohacking', 'la', 'en', 'el', 'para', 'que'..."
2387,YouTube,I3vUqFoY5H0,https://www.youtube.com/watch?v=I3vUqFoY5H0,Alimentos que combatem o envelhecimento - 14/0...,Convidado: Dr.Wilmar Accursio - Endocrinologis...,Você Bonita,Excelente || Sobre a folha dá beterraba.. fiqu...,18105.0,231.0,4.0,...,unknown,2011-09-14,False,2011,235.0,0.012980,Alimentos que combatem o envelhecimento - 14/0...,1,1_biohacking_la_en_el,"['biohacking', 'la', 'en', 'el', 'para', 'que'..."
2419,YouTube,RQ6vKAyNMjc,https://www.youtube.com/watch?v=RQ6vKAyNMjc,FRANCE 24 Sur Le Net - SUR LE NET,SUR LE NET L'actualité vue par le net et l'act...,FRANCE 24,NaN,178.0,0.0,0.0,...,unknown,2011-09-20,False,2011,0.0,0.000000,FRANCE 24 Sur Le Net - SUR LE NET SUR LE NET L...,1,1_biohacking_la_en_el,"['biohacking', 'la', 'en', 'el', 'para', 'que'..."
2459,YouTube,fEEBiv_JJP0,https://www.youtube.com/watch?v=fEEBiv_JJP0,"Elektrischer Reporter S03E15 - INDECT, Rentner...",DIGIsellschaft: Indect -- Wer sich im öffentli...,BlinkenTV,Wintermute GmbH... sehr sehr passender Name fü...,978.0,15.0,2.0,...,unknown,2011-10-05,False,2011,17.0,0.017382,"Elektrischer Reporter S03E15 - INDECT, Rentner...",1,1_biohacking_la_en_el,"['biohacking', 'la', 'en', 'el', 'para', 'que'..."
2516,YouTube,L9Qp0qC2bO4,https://www.youtube.com/watch?v=L9Qp0qC2bO4,BRINCAR COM POUCA COISA NO CEV da COLINA DE ...,"Quando há imaginação , com pouca coisa se cons...",DO ALTO DA COLINA Valdonas,NaN,123.0,0.0,0.0,...,unknown,2011-10-19,False,2011,0.0,0.000000,BRINCAR COM POUCA COISA NO CEV da COLINA DE ...,1,1_biohacking_la_en_el,"['biohacking', 'la', 'en', 'el', 'para', 'que'..."
2547,YouTube,zbdeWPwcaIg,https://www.youtube.com/watch?v=zbdeWPwcaIg,Colocando Levaduras en Medio de Cultivo PDA.AVI,Colocando Levaduras obtenidas de guayaba en Me...,uachqbpJESUS,me da mucho gusto que te dediques ala quimica ...,3813.0,8.0,1.0,...,unknown,2011-10-26,False,2011,9.0,0.002360,Colocando Levaduras en Medio de Cultivo PDA.AV...,1,1_biohacking_la_en_el,"['biohacking', 'la', 'en', 'el', 'para', 'que'..."
2666,YouTube,F_DFC1BFcx8,https://www.youtube.com/watch?v=F_DFC1BFcx8,euronews science - Descubriendo el dolor,http://fr.euronews.net/ Todos sabemos lo que e...,euronews (en español),NaN,401.0,2.0,0.0,...,unknown,2011-11-23,False,2011,2.0,0.004988,euronews science - Descubriendo el dolor http:...,1,1_biohacking_la_en_el,"['biohacking', 'la', 'en', 'el', 'para', 'que'..."
3294,YouTube,-0J4c8b-8tw,https://www.youtube.com/watch?v=-0J4c8b-8tw,Nocno umokravanje * VAZOPRESIN,NaN,ordinacija,Da li postoji neko lekovito bilje koje povećav...,1190.0,4.0,1.0,...,unknown,2012-05-10,False,2012,5.0,0.004202,Nocno umokravanje * VAZOPRESIN,1,1_biohacking_la_en_el,"['biohacking', 'la', 'en', 'el', 'para', 'que'..."
3570,YouTube,GcaCP0xDXFA,https://www.youtube.com/watch?v=GcaCP0xDXFA,CPRE - O biohacking no Brasil,NaN,Campus Party,NaN,2587.0,25.0,0.0,...,unknown,2012-07-27,False,2012,25.0,0.009664,CPRE - O biohacking no Brasil,1,1_biohacking_la_en_el,"['biohacking', 'la', 'en', 'el', 'para', 'que'..."
3904,YouTube,6WxwFVT6wwM,https://www.youtube.com/watch?v=6WxwFVT6wwM,Arccsontrekonstrukció: Az utolsó műtét,"Szimmetrikus lett az arcom, és visszaállt az e...",Semmelweis Egyetem,NaN,2219.0,10.0,0.0,...,unknown,2012-10-25,False,2012,10.0,0.004507,Arccsontrekonstrukció: Az utolsó műtét Szimmet...,1,1_biohacking_la_en_el,"['biohacking', 'la', 'en', 'el', 'para', 'que'..."
3935,YouTube,tYT4sE00Ko8,https://www.youtube.com/watch?v=tYT4sE00Ko8,Nutrientes para prevenir el cáncer,Nutrientes para prevenir el cáncer.,El Espectador,noticias inutiles,1587.0,3.0,1.0,...,unknown,2012-10-31,False,2012,4.0,0.002520,Nutrientes para prevenir el cáncer Nutrientes ...,1,1_biohacking_la_en_el,"['biohacking', 'la', 'en', 'el', 'para', 'que'..."
3952,YouTube,iY91JoMWQoM,https://www.youtube.com/watch?v=iY91JoMWQoM,Mundo Bita - Fundo do Mar [clipe infantil],"Cabe todo mundo no submarino amarelo do Bita, ...",Mundo Bita,NaN,727020545.0,1176643.0,0.0,...,unknown,2012-11-01,False,2012,1176643.0,0.001618,Mundo Bita - Fundo do Mar [clipe infantil] Cab...,1,1_biohacking_la_en_el,"['biohacking', 'la', 'en', 'el', 'para', 'que'..."
4324,YouTube,Vt-Jzg29xks,https://www.youtube.com/watch?v=Vt-Jzg29xks,NooRun Suplemento,NooRun es un suplemento alimenticio que mejora...,MrMariobrondo,NI pones la dirección web jajaja || como puedo...,107682.0,11.0,2.0,...,unknown,2013-02-17,False,2013,13.0,0.000121,NooRun Suplemento NooRun es un suplemento alim...,1,1_biohacking_la_en_el,"['biohacking', 'la', 'en', 'el', 'para', 'que'..."
4576,YouTube,XPolHvPQ7dY,https://www.youtube.com/watch?v=XPolHvPQ7dY,La minute blonde du biohacking,"""Les Geeks ne sont pas des terroristes !"" - Qu...",Catherine Coste,L&#39;Halva c&#39;est Grecque... || Ni Hamas n...,739.0,4.0,2.0,...,unknown,2013-04-28,False,2013,6.0,0.008119,"La minute blonde du biohacking ""Les Geeks ne s...",1,1_biohacking_la_en_el,"['biohacking', 'la', 'en', 'el', 'para', 'que'..."
4757,YouTube,vTWUZDX_Wvg,https://www.youtube.com/watch?v=vTWUZDX_Wvg,Nuevas ideas para eliminar la basura espacial....,"Entrevista con el Dr. Manuel Metz, del Institu...",DW Español,NaN,473.0,7.0,0.0,...,unknown,2013-06-10,False,2013,7.0,0.014799,Nuevas ideas para eliminar la basura espacial....,1,1_biohacking_la_en_el,"['biohacking', 'la', 'en', 'el', 'para', 'que'..."
5363,YouTube,ZBspo40ZizY,https://www.youtube.com/watch?v=ZBspo40ZizY,Un biohacker si impianta un sensore sottopelle...,Per altro ancora visita: http://mcaf.ee/j3xzy.,cinda rella,NaN,19.0,0.0,0.0,...,unknown,2013-11-10,False,2013,0.0,0.000000,Un biohacker si impianta un sensore sottopelle...,1,1_biohacking_la_en_el,"['biohacking', 'la', 'en', 'el', 'para', 'que'..."
5474,YouTube,ukmOT5r_mEM,https://www.youtube.com/watch?v=ukmOT5r_mEM,Biohacker züchten Aliivibrio fischeri - Report...,Artikel auf Golem.de: http://www.golem.de/news...,GolemDE,Rechtlich vielleicht schwierig oder wie ist da...,4378.0,50.0,7.0,...,unknown,2013-12-03,False,2013,57.0,0.013020,Biohacker züchten Aliivibrio fischeri - Report...,1,1_biohacking_la_en_el,"['biohacking', 'la', 'en', 'el', 'para', 'que'..."
5804,YouTube,JcbWuB5mxf4,https://www.youtube.com/watch?v=JcbWuB5mxf4,BioHacking e Produtividade Pessoal com BioHack...,Neste bate-papo você vai conhecer o Sebastian ...,Marcus Lucas,"Opa! Quem tiver interesse, segue lá no Instagr...",6000.0,232.0,5.0,...,unknown,2014-03-03,False,2014,237.0,0.039500,BioHacking e Produtividade Pessoal com BioHack...,1,1_biohacking_la_en_el,"['biohacking', 'la', 'en', 'el', 'para', 'que'..."
5898,YouTube,n4p0-uWfEHg,https://www.youtube.com/watch?v=n4p0-uWfEHg,Biohacking - Une vie augmentée - Conférence TE...,Halim est tombé dans la marmite des données à ...,VideosInspirantes,NaN,158.0,4.0,0.0,...,unknown,2014-03-27,False,2014,4.0,0.025316,Biohacking - Une vie augmentée - Conférence TE...,1,1_biohacking_la_en_el,"['biohacking', 'la', 'en', 'el', 'para', 'que'..."
6304,YouTube,OUc7Az6rhDY,https://www.youtube.com/watch?v=OUc7Az6rhDY,"MojoJa#15 - Fabio Santos, Biohacking",O que você vai ouvir: - quantificar = conhecer...,Rodrigo Kherlakian,"Vão me desculpar, mas a vida continua a ser vi...",2587.0,58.0,6.0,...,unknown,2014-07-22,False,2014,64.0,0.024739,"MojoJa#15 - Fabio Santos, Biohacking O que voc...",1,1_biohacking_la_en_el,"['biohacking', 'la', 'en', 'el', 'para', 'que'..."
6598,YouTube,5Z7baa5BRWw,https://www.youtube.com/watch?v=5Z7baa5BRWw,Cyborgs y Performatividad: Inervación Invisibl...,Síguenos en: https://twitter.com/ccunab https:...,UNABTV,Genial la conferencia. Muchas gracias!,297.0,6.0,1.0,...,unknown,2014-09-29,False,2014,7.0,0.023569,Cyborgs y Performatividad: Inervación Invisibl...,1,1_biohacking_la_en_el,"['biohacking', 'la', 'en', 'el', 'para', 'que'..."
6641,YouTube,POABTjZ9UwY,https://www.youtube.com/watch?v=POABTjZ9UwY,100 Cose che Forse Non Sai su Minecraft,Salve a tutti ragazzi... In questo video volev...,BioHack *,"Questo video è uscito quasi 11 anni fa 😳, mi s...",2595822.0,48640.0,3248.0,...,zxx,2014-10-07,False,2014,51888.0,0.019989,100 Cose che Forse Non Sai su Minecraft Salve ...,1,1_biohacking_la_en_el,"['biohacking', 'la', 'en', 'el', 'para', 'que'..."
7092,YouTube,mghPvsFKy8o,https://www.youtube.com/watch?v=mghPvsFKy8o,[EN VIDEO] &quot;Biohacking&quot;: píldoras y ...,NaN,Notiséis WIPR,NaN,22.0,0.0,0.0,...,unknown,2015-02-02,False,2015,0.0,0.000000,[EN VIDEO] &quot;Biohacking&quot;: píldoras y ...,1,1_biohacking_la_en_el,"['biohacking', 'la', 'en', 'el', 'para', 'que'..."
7130,YouTube,2UEOxXX-UaI,https://www.youtube.com/watch?v=2UEOxXX-UaI,Mojo Já #15 - Fabio Santos - Biohacking,Curta o video e assine nosso canal para mais e...,Mojo Ja,NaN,319.0,10.0,0.0,...,unknown,2015-02-11,False,2015,10.0,0.031348,Mojo Já #15 - Fabio Santos - Biohacking Curta ...,1,1_biohacking_la_en_el,"['biohacking', 'la', 'en', 'el', 'para', 'que'..."
7290,YouTube,caV0MvBgxmg,https://www.youtube.com/watch?v=caV0MvBgxmg,O que é Biohacking? - M3M #4,Descubra o que é Biohacking e o que o futuro n...,Yago Medeiros,KKKKKKKKKKKKKK &quot;DIY pra customizar cadern...,2405.0,119.0,19.0,...,unknown,2015-04-02,False,2015,138.0,0.057380,O que é Biohacking? - M3M #4 Descubra o que é ...,1,1_biohacking_la_en_el,"['biohacking', 'la', 'en', 'el', 'para', 'que'..."
7300,YouTube,SI0ujwd8m7Y,https://www.youtube.com/watch?v=SI0ujwd8m7Y,Biohackers crean visión nocturna para humanos,Tal como los súper héroes. Para más noticias v...,El Kiwi Informativo,me gustaría el de poder materializar cualquier...,955.0,30.0,2.0,...,unknown,2015-04-07,False,2015,32.0,0.033508,Biohackers crean visión nocturna para humanos ...,1,1_biohacking_la_en_el,"['biohacking', 'la', 'en', 'el', 'para', 'que'..."
7373,YouTube,iC6dFr3J7K0,https://www.youtube.com/watch?v=iC6dFr3J7K0,BioHack Academy 1: BioFactory al romamakers Ga...,L'era delle biotecnologie fai-da-te è arrivata...,MillepianiTv,NaN,346.0,2.0,0.0,...,unknown,2015-04-22,False,2015,2.0,0.005780,BioHack Academy 1: BioFactory al romamakers Ga...,1,1_biohacking_la_en_el,"['biohacking', 'la', 'en', 'el', 'para', 'que'..."
7558,YouTube,BZe-Rs4N6mM,https://www.youtube.com/watch?v=BZe-Rs4N6mM,Jak si dělám místo ve své hlavě,Pár doplňujících odkazů jako vždy níže: https:...,metalearning_cz,Myslím že i dnešní počítače dělají ve skutečno...,33670.0,720.0,20.0,...,cs,2015-06-13,False,2015,740.0,0.021978,Jak si dělám místo ve své hlavě Pár doplňující...,1,1_biohacking_la_en_el,"['biohacking', 'la', 'en', 'el', 'para', 'que'..."
7575,YouTube,2ddolPylr4E,https://www.youtube.com/watch?v=2ddolPylr4E,Biohackers : les bricoleurs de l&#39;ADN,Abonnez-vous à notre chaîne sur YouTube : http...,FRANCE 24,pirater les corps ça va pas ... vous n&#39;y c...,1925.0,8.0,1.0,...,unknown,2015-06-19,False,2015,9.0,0.004675,Biohackers : les bricoleurs de l&#39;ADN Abonn...,1,1_biohacking_la_en_el,"['biohacking', 'la', 'en', 'el', 'para', 'que'..."
7585,YouTube,JXg2qMssi44,https://www.youtube.com/watch?v=JXg2qMssi44,Quem são os BioHackers,Bem vindo ao IMPACTO ZONE. Clay e Dedé entram ...,Impacto Zone,"Muito estranho esse povo, kkkk mas adorei o a...",206.0,9.0,1.0,...,unknown,2015-06-23,False,2015,10.0,0.048544,Quem são os BioHackers Bem vindo ao IMPACTO ZO...,1,1_biohacking_la_en_el,"['biohacking', 'la', 'en', 'el', 'para', 'que'..."
7719,YouTube,U0GwzLa9h6E,https://www.youtube.com/watch?v=U0GwzLa9h6E,"Raymond McCauley, biohacker: &quot;Evitaremos ...",Entra en http://one.elpais.com Suscríbete a nu...,El Futuro Es Apasionante de Vodafone,Estoy viendo 1 a 1 todos los videos desde el c...,65134.0,105.0,29.0,...,es,2015-07-14,False,2015,134.0,0.002057,"Raymond McCauley, biohacker: &quot;Evitaremos ...",1,1_biohacking_la_en_el,"['biohacking', 'la', 'en', 'el', 'para', 'que'..."
7723,YouTube,OYefO2zY_S0,https://www.youtube.com/watch?v=OYefO2zY_S0,le régime paléo une forme de biohacking,Tu veux perdre du poids ? Récupère vite ton gu...,TheGreenEscape,Recevoir mon guide gratuit sur les régimes fai...,256.0,1.0,1.0,...,en-US,2015-07-15,False,2015,2.0,0.007812,le régime paléo une forme de biohacking Tu veu...,1,1_biohacking_la_en_el,"['biohacking', 'la', 'en', 'el', 'para', 'que'..."
7759,YouTube,a-jv6Nq677U,https://www.youtube.com/watch?v=a-jv6Nq677U,Jak si začít prakticky plnit své sny,Pár doplňujících odkazů jako vždy níže: https:...,metalearning_cz,Uzasnee moc krasne. Ďakujem. Dakujem. Dakujem❤...,28747.0,612.0,8.0,...,cs,2015-07-26,False,2015,620.0,0.021567,Jak si začít prakticky plnit své sny Pár doplň...,1,1_biohacking_la_en_el,"['biohacking', 'la', 'en', 'el', 'para', 'que'..."
7796,YouTube,SoMFNrhon0E,https://www.youtube.com/watch?v=SoMFNrhon0E,Primera Meetup Biohacking Buenos Aires,Introduccion a la primera Meetup de Biohacking...,Leonardo Maddio,NaN,88.0,3.0,0.0,...,es-419,2015-08-05,False,2015,3.0,0.034091,Primera Meetup Biohacking Buenos Aires Introdu...,1,1_biohacking_la_en_el,"['biohacking', 'la', 'en', 'el', 'para', 'que'..."
7798,YouTube,43ciZynyUWM,https://www.youtube.com/watch?v=43ciZynyUWM,BiohackingBA - El origen del biohacking y la ...,Informalísima presentación a cargo de Manu Gim...,Manuel Giménez,"<a href=""https://fbwat.ch/1AsMSGztgmt3sVNZ"">ht...",292.0,4.0,3.0,...,unknown,2015-08-06,False,2015,7.0,0.023973,BiohackingBA - El origen del biohacking y la ...,1,1_biohacking_la_en_el,"['biohacking', 'la', 'en', 'el', 'para', 'que'..."
7849,YouTube,Tkl-7X1tBTE,https://www.youtube.com/watch?v=Tkl-7X1tBTE,Nejste spokojení? Vyřešíme!,Pár doplňujících odkazů jako vždy níže: https:...,metalearning_cz,"Ahoj, zmiňuješ odkaz na vedení deníčku, nikde ...",29952.0,659.0,20.0,...,cs,2015-08-18,False,2015,679.0,0.022670,Nejste spokojení? Vyřešíme! Pár doplňujících o...,1,1_biohacking_la_en_el,"['biohacking', 'la', 'en', 'el', 'para', 'que'..."
7890,YouTube,uYV5Cxzgix8,https://www.youtube.com/watch?v=uYV5Cxzgix8,ONDAS DELTA - CONCILIA EL SUEÑO - REPARA TU CU...,Sonido binaural para conciliar el sueño gracia...,Ismael Abós,🌟NO ESTAS AQUÍ Por CASUALIDAD!Suscríbete para ...,9595765.0,70152.0,2797.0,...,unknown,2015-09-01,False,2015,72949.0,0.007602,ONDAS DELTA - CONCILIA EL SUEÑO - REPARA TU CU...,1,1_biohacking_la_en_el,"['biohacking', 'la', 'en', 'el', 'para', 'que'..."
7995,YouTube,wmSoFpMXdqs,https://www.youtube.com/watch?v=wmSoFpMXdqs,"sistema educacional falho, biohacking e mão ma...","hacks sobre educação, biohacking e a mão mais ...",gabriel goffi.,Quem quiser conhecer mais sobre o tema acessem...,29400.0,1394.0,88.0,...,pt,2015-09-28,False,2015,1482.0,0.050408,"sistema educacional falho, biohacking e mão ma...",1,1_biohacking_la_en_el,"['biohacking', 'la', 'en', 'el', 'para', 'que'..."
8008,YouTube,ErGMsNOKzzQ,https://www.youtube.com/watch?v=ErGMsNOKzzQ,Hacking do ser humano (#10 pt 3) [Inovação ²],Participe do próximo Inovação²! Responda ao qu...,Canaltech,voltem a postar o progarma inteiro em um unico...,8900.0,884.0,15.0,...,zxx,2015-09-30,False,2015,899.0,0.101011,Hacking do ser humano (#10 pt 3) [Inovação ²] ...,1,1_biohacking_la_en_el,"['biohacking', 'la', 'en', 'el', 'para', 'que'..."
8032,YouTube,IN0MihUSh_0,https://www.youtube.com/watch?v=IN0MihUSh_0,BioJam: biohacking och kroppsteknik,Hur påverkas samhällsetiken av den snabba utve...,Människa plus,NaN,209.0,5.0,0.0,...,unknown,2015-10-07,False,2015,5.0,0.023923,BioJam: biohacking och kroppsteknik Hur påverk...,1,1_biohacking_la_en_el,"['biohacking', 'la', 'en', 'el', 'para', 'que'..."

As we can see from above, the topic number 1 of the Minilm consists of spanish, germand and portugeese videos. Those videos are not needed in our research, since it is based on English langugage. So deleting them will not hurt

**Search for the other unrelated topics**

In [91]:
search_keywords = ["longevity", "healthy aging", "biohacking", "rejuvenation", "anti-aging", "nootropics"]

In [95]:
def topic_is_relevant(rep, search_keywords):
    topic_words = eval(rep)  # convert string list to real list
    topic_words = [word.lower() for word in topic_words]
    return any(kw in word for word in topic_words for kw in search_keywords)

# Apply this to all topics
tpm['is_relevant'] = tpm['Representation'].apply(lambda rep: topic_is_relevant(rep, search_keywords))

In [143]:
tpm[tpm['is_relevant']==False]

,Topic,Count,Name,Representation,Representative_Docs,is_relevant,relevance_ratio
4,3,91,3_klaus_workout_denmark_2012,"['klaus', 'workout', 'denmark', '2012', '2011'...",['MUTANT athlete KLAUS RIIS will be at FIBO 20...,False,0.000000
5,4,78,4_exercise video_ball_demonstrating_exercise,"['exercise video', 'ball', 'demonstrating', 'e...",['REJUVENATION | DELTOID FLIES Rejuvenation Pr...,False,0.538462
9,8,62,8_record_mix_original_guide,"['record', 'mix', 'original', 'guide', 'album'...","[""1992 - Nootropic &#39;Elevation&#39; (Origin...",False,0.000000
10,9,60,9_bulletproof_asprey_bulletproof coffee_dave a...,"['bulletproof', 'asprey', 'bulletproof coffee'...",['Bulletproof Exec Dave Asprey on BioHacking a...,False,0.483333
11,10,60,10_на_39 play_let 39_nzt,"['на', '39 play', 'let 39', 'nzt', 'hd', 'play...",['ЭФФЕКТИВНЫЕ упражнения для омоложения! #омол...,False,0.100000
13,12,47,12_arduino_shield_game_games,"['arduino', 'shield', 'game', 'games', 'video'...",['Video Overlay Goggles Arduino Using an Ardui...,False,0.021277
14,13,47,13_oral_dental_oral health_dentistry,"['oral', 'dental', 'oral health', 'dentistry',...",['Nutrition and Oral Health | Aging Matters | ...,False,0.574468
15,14,46,14_limitless_cooper_nzt_movie,"['limitless', 'cooper', 'nzt', 'movie', 'trail...",['Limitless Movie Review from Haunted Flower G...,False,0.043478
16,15,45,15_diy bio_diy_bio_pellet,"['diy bio', 'diy', 'bio', 'pellet', 'water', '...","['DIY bio pellets reactor 1 ', 'DIY Bio-Pellet...",False,0.088889
18,17,37,17_lower_song_brains_click http,"['lower', 'song', 'brains', 'click http', 'pla...","[""Lower Dens - Propagation After just 76 secon...",False,0.675676
20,19,36,19_neurofeedback_brain_therapy_http,"['neurofeedback', 'brain', 'therapy', 'http', ...",['Is Neurofeedback Therapy a Useful Therapy? I...,False,0.083333
21,20,36,20_playlists_com ref_ref_visit https,"['playlists', 'com ref', 'ref', 'visit https',...",['Jiu Jitsu Self-Defense vs Weapons - How to D...,False,0.027778
22,21,33,21_alpha brain_alpha_onnit_brain,"['alpha brain', 'alpha', 'onnit', 'brain', 'ro...",['Joey Diaz gives his thoughts on Alpha Brain ...,False,0.242424
24,23,29,23_smart drugs_drugs_smart_le,"['smart drugs', 'drugs', 'smart', 'le', 'di', ...",['Quanto costano le smart drugs? LOMBARDIA CHA...,False,0.034483
26,25,28,25_choline_alpha gpc_gpc_alpha,"['choline', 'alpha gpc', 'gpc', 'alpha', 'comp...",['Alpha-GPC - Nootropics Information What is A...,False,0.464286
29,28,27,28_gut_microbiome_bacteria_gut health,"['gut', 'microbiome', 'bacteria', 'gut health'...",['Gut Microbes &amp; Longevity: The Secret to ...,False,0.629630
30,29,26,29_stave age_stave_drugs stave_develop smart,"['stave age', 'stave', 'drugs stave', 'develop...",['llive discussion can we should we devel...,False,0.000000
32,31,25,31_bulletproof radio_radio_bulletproof_podcast,"['bulletproof radio', 'radio', 'bulletproof', ...",['Bulletproof Radio Q&amp;A - #207 Why you sho...,False,0.200000
35,34,23,34_stave_drugs stave_stave age_related memory,"['stave', 'drugs stave', 'stave age', 'related...",['Can we should we develop smart drugs to stav...,False,0.000000
38,37,22,37_dag_noopept_och_en,"['dag', 'noopept', 'och', 'en', '2014', 'april...","['Dag 13, Nootropics (Noopept + Neurostim), 7...",False,0.818182
40,39,22,39_edge exclusive_big think_think edge_videos ...,"['edge exclusive', 'big think', 'think edge', ...",['What is your counsel? New videos DAILY: http...,False,0.000000
42,41,21,41_gum_technique_dr john_dentist,"['gum', 'technique', 'dr john', 'dentist', 'su...",['Pinhole Gum Rejuvenation® | Alternative to g...,False,1.000000
43,42,20,42_piel_la_cómo_las,"['piel', 'la', 'cómo', 'las', 'del', 'el', 'qu...",['💆🏻\u200d♀️¿Cómo mejorar la texturade la piel...,False,0.250000
44,43,19,43_dog_pets_dogs_shape,"['dog', 'pets', 'dogs', 'shape', 'project', 'h...","[""How to feed your dog (for health and longevi...",False,0.789474
46,45,19,45_creatine_muscle_power_strength,"['creatine', 'muscle', 'power', 'strength', 'b...","[""Creatine &amp; Healthy Aging: Myth vs. Reali...",False,0.368421
48,47,19,47_aging 101_101_georgia_know aging,"['aging 101', '101', 'georgia', 'know aging', ...",['AGING 101: Pt 2 Physical Health Normal Agin...,False,0.000000
49,48,18,48_silicon_complete_implants_extension,"['silicon', 'complete', 'implants', 'extension...",['27C3 Cybernetics for the Masses - Lepht Anon...,False,0.277778
50,49,18,49_magnet_implant_clients_stuff,"['magnet', 'implant', 'clients', 'stuff', 'sho...",['Magnet &amp; Paperclips #5 30 paperclips on ...,False,0.333333
54,53,17,53_stress_relief_professionals_teach,"['stress', 'relief', 'professionals', 'teach',...",['Stress Relief Anti Aging Tip Your Top 3 Prio...,False,0.470588
55,54,17,54_die_ich_auf_hier,"['die', 'ich', 'auf', 'hier', 'marcus', 'mega'...",['Biohacking ✰ Motorik 2.0 Welcome! Ich bin M...,False,0.823529
56,55,16,55_arina_teemu arina_teemu_mindfulness,"['arina', 'teemu arina', 'teemu', 'mindfulness...",['#5 Biohakkerin käsikirja -- Voi erikoisjakso...,False,0.000000
57,56,16,56_brush_fan_qvc_information buy,"['brush', 'fan', 'qvc', 'information buy', 'co...",['IT Cosmetics CC Anti-Aging Ombre Radiance Br...,False,0.937500

As you can see, I have filtered out unrelated topics based on the keywords. We will look at each cluster and decide if it should be deleted or left. In each topic, we will check if there might be related videos and how percentage are related. Based on that we will also manually look at them. If the topic is completely unrelated, then we will delete them.

In [120]:
#function to check if the video is related or unrelated

def is_video_related(text, keywords):
    text = str(text).lower()
    return any(kw in text for kw in keywords)

In [122]:
#function to check how many percentage of the videos in the topics are related
def check_relevance_ratio(df, topic_id, keywords):
    df_topic = df[df['topic']==topic_id]
    relevant_count = df_topic['text'].apply(lambda x: is_video_related(x, keywords)).sum()
    return relevant_count/len(df_topic)

In [124]:
keywords = ["longevity", "healthy aging", "biohacking", "rejuvenation", "anti-aging", "nootropics"]

In [132]:
check_relevance_ratio(dfm, 4, keywords)

0.5384615384615384

Let's assign their relevance ratio for each topic

In [135]:
tpm['relevance_ratio'] = tpm['Topic'].apply(lambda t: check_relevance_ratio(dfm, t, keywords))

Now, all the topics have their own relevance ratio. Let's check the topics of which relecane ratio is smaller than .20 and if the videos are totally unrelated, we will delete them.

In [149]:
tpm[tpm['relevance_ratio']<=0.20]

,Topic,Count,Name,Representation,Representative_Docs,is_relevant,relevance_ratio
4,3,91,3_klaus_workout_denmark_2012,"['klaus', 'workout', 'denmark', '2012', '2011'...",['MUTANT athlete KLAUS RIIS will be at FIBO 20...,False,0.000000
9,8,62,8_record_mix_original_guide,"['record', 'mix', 'original', 'guide', 'album'...","[""1992 - Nootropic &#39;Elevation&#39; (Origin...",False,0.000000
11,10,60,10_на_39 play_let 39_nzt,"['на', '39 play', 'let 39', 'nzt', 'hd', 'play...",['ЭФФЕКТИВНЫЕ упражнения для омоложения! #омол...,False,0.100000
13,12,47,12_arduino_shield_game_games,"['arduino', 'shield', 'game', 'games', 'video'...",['Video Overlay Goggles Arduino Using an Ardui...,False,0.021277
15,14,46,14_limitless_cooper_nzt_movie,"['limitless', 'cooper', 'nzt', 'movie', 'trail...",['Limitless Movie Review from Haunted Flower G...,False,0.043478
16,15,45,15_diy bio_diy_bio_pellet,"['diy bio', 'diy', 'bio', 'pellet', 'water', '...","['DIY bio pellets reactor 1 ', 'DIY Bio-Pellet...",False,0.088889
20,19,36,19_neurofeedback_brain_therapy_http,"['neurofeedback', 'brain', 'therapy', 'http', ...",['Is Neurofeedback Therapy a Useful Therapy? I...,False,0.083333
21,20,36,20_playlists_com ref_ref_visit https,"['playlists', 'com ref', 'ref', 'visit https',...",['Jiu Jitsu Self-Defense vs Weapons - How to D...,False,0.027778
24,23,29,23_smart drugs_drugs_smart_le,"['smart drugs', 'drugs', 'smart', 'le', 'di', ...",['Quanto costano le smart drugs? LOMBARDIA CHA...,False,0.034483
30,29,26,29_stave age_stave_drugs stave_develop smart,"['stave age', 'stave', 'drugs stave', 'develop...",['llive discussion can we should we devel...,False,0.000000
32,31,25,31_bulletproof radio_radio_bulletproof_podcast,"['bulletproof radio', 'radio', 'bulletproof', ...",['Bulletproof Radio Q&amp;A - #207 Why you sho...,False,0.200000
35,34,23,34_stave_drugs stave_stave age_related memory,"['stave', 'drugs stave', 'stave age', 'related...",['Can we should we develop smart drugs to stav...,False,0.000000
40,39,22,39_edge exclusive_big think_think edge_videos ...,"['edge exclusive', 'big think', 'think edge', ...",['What is your counsel? New videos DAILY: http...,False,0.000000
48,47,19,47_aging 101_101_georgia_know aging,"['aging 101', '101', 'georgia', 'know aging', ...",['AGING 101: Pt 2 Physical Health Normal Agin...,False,0.000000
56,55,16,55_arina_teemu arina_teemu_mindfulness,"['arina', 'teemu arina', 'teemu', 'mindfulness...",['#5 Biohakkerin käsikirja -- Voi erikoisjakso...,False,0.000000

In [340]:
# id's of the topics that should be deleted
# 1? 
# 10 is related, but all the videos are in Russian
# 23 in Italian
# 31 is the videos of the Bulletproof channel. It is moslty related to the topic
# 47 is mostly about caring for the elder people. Not reletated to our research
delete_id =[3, 8, 10, 12, 14, 15, 20, 23, 34, 39, 47, 55]

Let's check out the vides between .20 and .50

In [208]:
tpm[(tpm['relevance_ratio']>=0.20) & (tpm['relevance_ratio']<=0.50)]

,Topic,Count,Name,Representation,Representative_Docs,is_relevant,relevance_ratio
10,9,60,9_bulletproof_asprey_bulletproof coffee_dave a...,"['bulletproof', 'asprey', 'bulletproof coffee'...",['Bulletproof Exec Dave Asprey on BioHacking a...,False,0.483333
22,21,33,21_alpha brain_alpha_onnit_brain,"['alpha brain', 'alpha', 'onnit', 'brain', 'ro...",['Joey Diaz gives his thoughts on Alpha Brain ...,False,0.242424
26,25,28,25_choline_alpha gpc_gpc_alpha,"['choline', 'alpha gpc', 'gpc', 'alpha', 'comp...",['Alpha-GPC - Nootropics Information What is A...,False,0.464286
32,31,25,31_bulletproof radio_radio_bulletproof_podcast,"['bulletproof radio', 'radio', 'bulletproof', ...",['Bulletproof Radio Q&amp;A - #207 Why you sho...,False,0.200000
43,42,20,42_piel_la_cómo_las,"['piel', 'la', 'cómo', 'las', 'del', 'el', 'qu...",['💆🏻\u200d♀️¿Cómo mejorar la texturade la piel...,False,0.250000
46,45,19,45_creatine_muscle_power_strength,"['creatine', 'muscle', 'power', 'strength', 'b...","[""Creatine &amp; Healthy Aging: Myth vs. Reali...",False,0.368421
49,48,18,48_silicon_complete_implants_extension,"['silicon', 'complete', 'implants', 'extension...",['27C3 Cybernetics for the Masses - Lepht Anon...,False,0.277778
50,49,18,49_magnet_implant_clients_stuff,"['magnet', 'implant', 'clients', 'stuff', 'sho...",['Magnet &amp; Paperclips #5 30 paperclips on ...,False,0.333333
52,51,18,51_2600 hope_2600_hope 2008_2008,"['2600 hope', '2600', 'hope 2008', '2008', 'ho...",['2600 - The Last HOPE (2008) - Bagcam_02 2600...,True,0.277778
54,53,17,53_stress_relief_professionals_teach,"['stress', 'relief', 'professionals', 'teach',...",['Stress Relief Anti Aging Tip Your Top 3 Prio...,False,0.470588

In [342]:
# 9 and 31 is about the Dave asprey videos, The founder of the Bulletproof company which focuses on the human health
# 42 all the vidoes are in Spanish
# 48 - cybernetics ? 
delete_id_2 =[42, 48, 51]

Let's now check the videos between 50 and 75 relevance

In [233]:
tpm[(tpm['relevance_ratio']>0.50) & (tpm['relevance_ratio']<=0.75)]

,Topic,Count,Name,Representation,Representative_Docs,is_relevant,relevance_ratio
0,-1,8459,-1_aging_longevity_healthy_nootropics,"['aging', 'longevity', 'healthy', 'nootropics'...",['How To Choose The Right Anti-Aging Cream Ant...,True,0.705521
5,4,78,4_exercise video_ball_demonstrating_exercise,"['exercise video', 'ball', 'demonstrating', 'e...",['REJUVENATION | DELTOID FLIES Rejuvenation Pr...,False,0.538462
6,5,76,5_sleep_melatonin_night_issues,"['sleep', 'melatonin', 'night', 'issues', 'hea...","['Yeah Yeah Yeah, Sleep... ""I\'ll Sleep When I...",True,0.513158
14,13,47,13_oral_dental_oral health_dentistry,"['oral', 'dental', 'oral health', 'dentistry',...",['Nutrition and Oral Health | Aging Matters | ...,False,0.574468
18,17,37,17_lower_song_brains_click http,"['lower', 'song', 'brains', 'click http', 'pla...","[""Lower Dens - Propagation After just 76 secon...",False,0.675676
29,28,27,28_gut_microbiome_bacteria_gut health,"['gut', 'microbiome', 'bacteria', 'gut health'...",['Gut Microbes &amp; Longevity: The Secret to ...,False,0.629630
45,44,19,44_theanine_caffeine_review_benefits,"['theanine', 'caffeine', 'review', 'benefits',...",['Top 4 L Theanine Benefits ltheanine #biohack...,True,0.526316
47,46,19,46_cold_ice_water_actually,"['cold', 'ice', 'water', 'actually', 'usa', 'b...",['Beyond Cold Water Boot Camp USA - Dive Door ...,True,0.578947
53,52,17,52_hearing_loss_public health_healthy,"['hearing', 'loss', 'public health', 'healthy'...",['CLSA Webinar Series: Hearing loss and health...,True,0.647059

In [344]:
# let's explore the -1 at the end since it is a noise
# 17 mostly songs and remix which are not related

delete_id_3 = [17]

Let's now check the videos between 0.75 and 100 relevance

In [254]:
tpm[(tpm['relevance_ratio']>0.75) & (tpm['relevance_ratio']<=1)]

,Topic,Count,Name,Representation,Representative_Docs,is_relevant,relevance_ratio
1,0,11355,0_rejuvenation_aging_anti_anti aging,"['rejuvenation', 'aging', 'anti', 'anti aging'...",['Nootropics for Hangovers: High Level Strateg...,True,0.805020
2,1,484,1_biohacking_la_en_el,"['biohacking', 'la', 'en', 'el', 'para', 'que'...","['Biohacking y sus beneficios para la salud, e...",True,0.869835
3,2,185,2_rejuvenation_rejuvenation episode_game_play,"['rejuvenation', 'rejuvenation episode', 'game...",['Let&#39;s Play Pokemon Rejuvenation: Episode...,True,0.972973
7,6,71,6_plasma_cutter_stick_140,"['plasma', 'cutter', 'stick', '140', 'longevit...",['LONGEVITY WELDALL TIG WELDER PLASMA CUTTER C...,True,0.985915
8,7,70,7_vaginal_vaginal rejuvenation_rejuvenation_tr...,"['vaginal', 'vaginal rejuvenation', 'rejuvenat...","['⭕️ Vaginal Rejuvenation (Vaginoplasty, Vagin...",True,0.942857
12,11,56,11_ovarian_fertility_prp_platelet rich,"['ovarian', 'fertility', 'prp', 'platelet rich...",['Ovarian PRP (Platelet-Rich Plasma)|Ovarian R...,True,0.964286
17,16,41,16_microneedling_exosomes_micro_skin,"['microneedling', 'exosomes', 'micro', 'skin',...",['How does MICRONEEDLING reverse signs of agin...,True,0.878049
19,18,37,18_aubrey_grey_aubrey grey_escape velocity,"['aubrey', 'grey', 'aubrey grey', 'escape velo...",['Aubrey de Grey | Longevity Myth Busting Alli...,True,0.918919
23,22,30,22_nootropics_fuel_motivation_edge,"['nootropics', 'fuel', 'motivation', 'edge', '...",['Korvyx - No Fairy Dust #brainupgrade #nootro...,True,0.966667
25,24,29,24_rich plasma_platelet rich_platelet_prp,"['rich plasma', 'platelet rich', 'platelet', '...",['PRP Hair Restoration - Hair Rejuvenation and...,True,0.931034
27,26,28,26_blue_blue zones_zones_buettner,"['blue', 'blue zones', 'zones', 'buettner', 'd...",['The Shocking Secret Of Blue Zones Longevity!...,True,0.964286
28,27,27,27_pain_best pain_longevityusa_com longevityusa,"['pain', 'best pain', 'longevityusa', 'com lon...",['Best Pain Cream; Longevity Rehab 1000 Best P...,True,0.925926
31,30,26,30_mushroom_mushrooms_mane_lion,"['mushroom', 'mushrooms', 'mane', 'lion', 'noo...","[""🍄 Day 7: Explore the Unique Chaga Mushroom w...",True,0.846154
33,32,24,32_rapid_coupon_coupon code_code,"['rapid', 'coupon', 'coupon code', 'code', 'di...","[""Rapid Fire Q&amp;A Nootropics Rapid Fire Q&A...",True,0.833333
34,33,23,33_las_las vegas_vegas_sports center,"['las', 'las vegas', 'vegas', 'sports center',...","[""Soccer Las Vegas | Longevity Sports Center L...",True,1.000000
36,35,23,35_tea_herb_spring_herbs,"['tea', 'herb', 'spring', 'herbs', 'http goo',...",['Gynostemma Supreme Tonic Tea Formula (Spring...,True,0.782609
37,36,22,36_bulletproof_bulletproof biohacking_biohacki...,"['bulletproof', 'bulletproof biohacking', 'bio...",['The 2015 Bulletproof Biohacking Conference R...,True,0.954545
38,37,22,37_dag_noopept_och_en,"['dag', 'noopept', 'och', 'en', '2014', 'april...","['Dag 13, Nootropics (Noopept + Neurostim), 7...",False,0.818182
39,38,22,38_biohacking village_village_def_25,"['biohacking village', 'village', 'def', '25',...",['DEF CON 25 BioHacking Village - Tim Cannon -...,True,1.000000
41,40,21,40_keto_john_dr john_biohacking,"['keto', 'john', 'dr john', 'biohacking', 'md'...",['Biohacking: What is Keto An explanation of w...,True,0.809524
42,41,21,41_gum_technique_dr john_dentist,"['gum', 'technique', 'dr john', 'dentist', 'su...",['Pinhole Gum Rejuvenation® | Alternative to g...,False,1.000000
44,43,19,43_dog_pets_dogs_shape,"['dog', 'pets', 'dogs', 'shape', 'project', 'h...","[""How to feed your dog (for health and longevi...",False,0.789474
51,50,18,50_coffee_drinking_longer_tea,"['coffee', 'drinking', 'longer', 'tea', 'study...",['Drinking up to three cups of coffee daily ma...,True,0.888889
55,54,17,54_die_ich_auf_hier,"['die', 'ich', 'auf', 'hier', 'marcus', 'mega'...",['Biohacking ✰ Motorik 2.0 Welcome! Ich bin M...,False,0.823529
57,56,16,56_brush_fan_qvc_information buy,"['brush', 'fan', 'qvc', 'information buy', 'co...",['IT Cosmetics CC Anti-Aging Ombre Radiance Br...,False,0.937500
58,57,15,57_garden_tree_mp4_trust,"['garden', 'tree', 'mp4', 'trust', 'descriptio...",['Longevity Garden Benefits.mp4 http://bit.ly/...,True,1.000000

In [346]:
# 1 since al the videos are in different language
# 2 mostly about the pokemon rejuvenation game
# 6 mostly about the longevity welding
# 27 short vidoes of the longevity USA company event. Since it is about the event itself, not so much correlated with our topic
# 37 also different language
# 43 it disscusses the longevity of teh dogs and pets
# 54 in german

delete_id_4 = [1, 2, 6, 27, 33, 37, 54, 56, 57]

In [336]:
dfm[dfm['topic']==57].head(50)

,source,video_id,video_url,title,description,channel,comments,views,likes,comments_count,...,country,date,likes_missing,year,engagement,engagement_rate,text,topic,topic_name,topic_repr
1557,YouTube,-6Vx_-mltWg,https://www.youtube.com/watch?v=-6Vx_-mltWg,Welcome to The Longevity Garden,http://TheLongevityGarden.com -- Welcome to Th...,TheLongevityGarden,NaN,1380.0,3.0,0.0,...,unknown,2011-02-03,False,2011,3.0,0.002174,Welcome to The Longevity Garden http://TheLong...,57,57_garden_tree_mp4_trust,"['garden', 'tree', 'mp4', 'trust', 'descriptio..."
1558,YouTube,Rnl9aoQVVf4,https://www.youtube.com/watch?v=Rnl9aoQVVf4,Longevity Garden Welcome.mp4,http://bit.ly/gZyjN5 Come playfully embrace lo...,LongevityGarden,NaN,15.0,0.0,0.0,...,unknown,2011-02-03,False,2011,0.0,0.000000,Longevity Garden Welcome.mp4 http://bit.ly/gZy...,57,57_garden_tree_mp4_trust,"['garden', 'tree', 'mp4', 'trust', 'descriptio..."
1560,YouTube,JWeeMM5WnLs,https://www.youtube.com/watch?v=JWeeMM5WnLs,Longevity Garden Benefits.mp4,http://bit.ly/gZyjN5 Learn the Benefits of the...,LongevityGarden,NaN,7.0,0.0,0.0,...,unknown,2011-02-03,False,2011,0.0,0.000000,Longevity Garden Benefits.mp4 http://bit.ly/gZ...,57,57_garden_tree_mp4_trust,"['garden', 'tree', 'mp4', 'trust', 'descriptio..."
1561,YouTube,iPo4RxPgDcA,https://www.youtube.com/watch?v=iPo4RxPgDcA,The Benefits of The Longevity Garden,http://TheLongevityGarden.com -- Welcome to th...,TheLongevityGarden,NaN,10.0,0.0,0.0,...,unknown,2011-02-03,False,2011,0.0,0.000000,The Benefits of The Longevity Garden http://Th...,57,57_garden_tree_mp4_trust,"['garden', 'tree', 'mp4', 'trust', 'descriptio..."
1562,YouTube,bNG70mwvhUw,https://www.youtube.com/watch?v=bNG70mwvhUw,Longevity Garden Description.mp4,http://bit.ly/gZyjN5 Step in as Longevity Expe...,LongevityGarden,NaN,19.0,0.0,0.0,...,unknown,2011-02-03,False,2011,0.0,0.000000,Longevity Garden Description.mp4 http://bit.ly...,57,57_garden_tree_mp4_trust,"['garden', 'tree', 'mp4', 'trust', 'descriptio..."
1564,YouTube,aU6JL5e4v6s,https://www.youtube.com/watch?v=aU6JL5e4v6s,Longevity Garden Fear Tree.mp4,http://bit.ly/gZyjN5 Of all the trees in our g...,LongevityGarden,NaN,26.0,0.0,0.0,...,unknown,2011-02-03,False,2011,0.0,0.000000,Longevity Garden Fear Tree.mp4 http://bit.ly/g...,57,57_garden_tree_mp4_trust,"['garden', 'tree', 'mp4', 'trust', 'descriptio..."
1565,YouTube,uJC8E-rt92A,https://www.youtube.com/watch?v=uJC8E-rt92A,The Longevity Garden Description,http://TheLongevityGarden.com-- The Longevity ...,TheLongevityGarden,NaN,225.0,0.0,0.0,...,unknown,2011-02-03,False,2011,0.0,0.000000,The Longevity Garden Description http://TheLon...,57,57_garden_tree_mp4_trust,"['garden', 'tree', 'mp4', 'trust', 'descriptio..."
1569,YouTube,DLxr_r_JMvI,https://www.youtube.com/watch?v=DLxr_r_JMvI,Longevity Garden Free Tree part 2.mp4,http://bit.ly/gZyjN5 Of all the trees in our g...,LongevityGarden,NaN,42.0,0.0,0.0,...,unknown,2011-02-06,False,2011,0.0,0.000000,Longevity Garden Free Tree part 2.mp4 http://b...,57,57_garden_tree_mp4_trust,"['garden', 'tree', 'mp4', 'trust', 'descriptio..."
1591,YouTube,LOwf52LYUH4,https://www.youtube.com/watch?v=LOwf52LYUH4,The Longevity Garden Description,"http:/thelongevitygarden.com,Longevity, Alison...",TheLongevityGarden,NaN,29.0,0.0,0.0,...,unknown,2011-02-13,False,2011,0.0,0.000000,The Longevity Garden Description http:/thelong...,57,57_garden_tree_mp4_trust,"['garden', 'tree', 'mp4', 'trust', 'descriptio..."
1596,YouTube,Q_YMYaQ8k8o,https://www.youtube.com/watch?v=Q_YMYaQ8k8o,Longevity Garden Attachment Tree.mp4,This tree of attachment has learned to let go ...,LongevityGarden,NaN,8.0,0.0,0.0,...,unknown,2011-02-14,False,2011,0.0,0.000000,Longevity Garden Attachment Tree.mp4 This tree...,57,57_garden_tree_mp4_trust,"['garden', 'tree', 'mp4', 'trust', 'descriptio..."
1598,YouTube,iUOCSCPZegM,https://www.youtube.com/watch?v=iUOCSCPZegM,Longevity Garden Attachment Tree.,This tree of attachment has learned to let go ...,TheLongevityGarden,NaN,20.0,0.0,0.0,...,unknown,2011-02-15,False,2011,0.0,0.000000,Longevity Garden Attachment Tree. This tree of...,57,57_garden_tree_mp4_trust,"['garden', 'tree', 'mp4', 'trust', 'descriptio..."
3126,YouTube,x92BSE13Ljk,https://www.youtube.com/watch?v=x92BSE13Ljk,Love and Kindness for Longevity,What kind of tree do you want to lie under at ...,Alison Heath,Thanks for your comment. I know that kindness ...,168.0,3.0,4.0,...,unknown,2012-04-06,False,2012,7.0,0.041667,Love and Kindness for Longevity What kind of t...,57,57_garden_tree_mp4_trust,"['garden', 'tree', 'mp4', 'trust', 'descriptio..."
12284,YouTube,ARymC8kcRp8,https://www.youtube.com/watch?v=ARymC8kcRp8,Protecting the longevity of cotton traits,Cotton grower Neek Morawitz discusses his expe...,MonsantoANZ,NaN,80.0,0.0,0.0,...,en,2018-10-29,False,2018,0.0,0.000000,Protecting the longevity of cotton traits Cott...,57,57_garden_tree_mp4_trust,"['garden', 'tree', 'mp4', 'trust', 'descriptio..."
12295,YouTube,NbQui12RNxA,https://www.youtube.com/watch?v=NbQui12RNxA,Protecting the longevity of cotton traits,Cotton grower Neek Morawitz discusses his expe...,MonsantoANZ,NaN,155.0,0.0,0.0,...,unknown,2018-10-31,False,2018,0.0,0.000000,Protecting the longevity of cotton traits Cott...,57,57_garden_tree_mp4_trust,"['garden', 'tree', 'mp4', 'trust', 'descriptio..."
17982,YouTube,bRliUDbiJHc,https://www.youtube.com/watch?v=bRliUDbiJHc,Farm to Label: Longevity™ Softgels,Welcome to the Farm to Label: A Seed to Seal S...,Young Living Essential Oils,Great news || I thought I heard the word bovin...,4045.0,145.0,4.0,...,en-US,2022-12-05,False,2022,149.0,0.036836,Farm to Label: Longevity™ Softgels Welcome to ...,57,57_garden_tree_mp4_trust,"['garden', 'tree', 'mp4', 'trust', 'descriptio..."

In [348]:
topics_to_delete = delete_id + delete_id_2 + delete_id_3 + delete_id_4
topics_to_delete

[3,
 8,
 10,
 12,
 14,
 15,
 20,
 23,
 34,
 39,
 47,
 55,
 42,
 48,
 51,
 17,
 1,
 2,
 6,
 27,
 33,
 37,
 54,
 56,
 57]

In [350]:
for topic_id in topics_to_delete:
    dfm = dfm[dfm['topic']!=topic_id]

In [367]:
mask = tpm['Topic'].apply(lambda x: x not in topics_to_delete)

In [369]:
tpm_new = tpm [mask]

**Let's save the final results and re-run the bertopic on the cleaned (from unrelated videos) dataset (Minilm SentenceTransformer)**

In [385]:
tpm_new.to_csv("Minilm-sorted-topics.csv", index=False)

In [387]:
dfm.to_csv("Minilm_sorted_data.csv", index=False)

**Let's run the bertopic once again on the cleaned dataset**

In [398]:
from bertopic import BERTopic
from sentence_transformers import SentenceTransformer
from sklearn.feature_extraction.text import CountVectorizer

model = SentenceTransformer("all-MiniLM-L6-v2") #for short texts

# Custom preprocessing with vectorizer
vectorizer_model = CountVectorizer(
    stop_words="english",  
    ngram_range=(1, 2),    
    max_df=0.85,           
    min_df=2,              
    max_features=4000  
)

# Creating BERTopic model
topic_model = BERTopic(
    embedding_model=model,
    vectorizer_model=vectorizer_model,
    nr_topics="auto",
    top_n_words=10,       
    calculate_probabilities=True,
    min_topic_size=30 #reduces overly small clusters
)

In [400]:
texts = dfm['text'].fillna("").tolist()

In [402]:
topics, probs = topic_model.fit_transform(texts)

In [406]:
topic_model.get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,-1,6947,-1_aging_nootropics_healthy_anti,"[aging, nootropics, healthy, anti, anti aging,...",[Anti-aging Skincare Secret - Part I The most ...
1,0,9492,0_rejuvenation_aging_longevity_anti,"[rejuvenation, aging, longevity, anti, anti ag...","[Rejuvenation , RevLite Skin Rejuvenation , Sk..."
2,1,2739,1_biohacking_biohacker_biohack_bulletproof,"[biohacking, biohacker, biohack, bulletproof, ...",[Biohacking Luisa Fernanda González Cárdenas Y...
3,2,996,2_nootropics_cortex_nootropic_stack,"[nootropics, cortex, nootropic, stack, nootrop...",[Nootropics make me agitated? Shorter Fuse? We...
4,3,212,3_drugs_smart_smart drugs_adderall,"[drugs, smart, smart drugs, adderall, students...","[Smart Drugs , Smart Drugs , Smart Drugs Diary ]"
5,4,75,4_anti_anti aging_aging_quot,"[anti, anti aging, aging, quot, doctor, talk, ...","[ศาสตร์มืด, แพง, เรื่องไกลตัว !? สรุปแล้ว Anti..."
6,5,69,5_coffee_mushroom_nootropics_mushrooms,"[coffee, mushroom, nootropics, mushrooms, savv...",[No More Coffee Runs! #Nootropics #Coffee #mid...
7,6,65,6_exercise video_video demonstrating_demonstra...,"[exercise video, video demonstrating, demonstr...",[REJUVENATION | SHOULDER PRESS Rejuvenation Pr...
8,7,55,7_ovarian_prp_fertility_rejuvenation,"[ovarian, prp, fertility, rejuvenation, ivf, p...",[My experience getting Ovarian PRP – Does it r...
9,8,43,8_oral_dental_dentistry_oral health,"[oral, dental, dentistry, oral health, implant...",[Nutrition and Oral Health | Aging Matters | N...
10,9,42,9_attia_peter attia_peter_dr peter,"[attia, peter attia, peter, dr peter, longevit...",[Supplements for Longevity &amp; Their Efficac...
11,10,36,10_neurofeedback_brain_therapy_http,"[neurofeedback, brain, therapy, http, http www...",[Is Neurofeedback Therapy a Useful Therapy? Is...
12,11,35,11_aubrey_grey_aubrey grey_escape velocity,"[aubrey, grey, aubrey grey, escape velocity, v...",[Aubrey de Grey: Longevity Escape Velocity May...
13,12,35,12_body biohack_performance energy_talked_cardiac,"[body biohack, performance energy, talked, car...",[What part of your body would you BIOHACK? We ...

**Saving the results**

In [428]:
dfm['topic'] = topics

In [422]:
tpm_rerun = topic_model.get_topic_info()

In [424]:
dfm.drop(['topic_name', 'topic_repr'], axis=1, inplace=True)

In [432]:
tpm_small = tpm_rerun[['Topic', 'Name', 'Representation']].rename(
    columns={'Topic':'topic', 'Name':'topic_name', 'Representation':'topic_repr'}
)

# Left-join so every video row gets the topic label/keywords
dfm = dfm.merge(tpm_small, on='topic', how='left')

In [442]:
import numpy as np

dfm['topic_prob'] = [p[t] if t != -1 and p is not None else np.nan for p, t in zip(probs, topics)]

In [446]:
dfm.drop('topic_prob', axis=1, inplace=True)

In [450]:
dfm.to_csv("new_minilm_data.csv", index=False)

In [454]:
tpm_rerun.to_csv("new_minilm_topics.csv", index=False)

In [456]:
import pandas as pd

probs_df = pd.DataFrame(probs)
probs_df.columns = [f"Topic_{i}" for i in range(probs_df.shape[1])]

In [460]:
probs_df.to_csv("topic_probs_minilm.csv", index=False)

**Let's try another sentence transformer for the new data**

In [463]:
from bertopic import BERTopic
from sentence_transformers import SentenceTransformer
from sklearn.feature_extraction.text import CountVectorizer

model = SentenceTransformer("paraphrase-mpnet-base-v2") #more nuanced model 

# Custom preprocessing with vectorizer
vectorizer_model = CountVectorizer(
    stop_words="english",  
    ngram_range=(1, 2),    
    max_df=0.85,           
    min_df=2,              
    max_features=4000  
)

# Creating BERTopic model
topic_model = BERTopic(
    embedding_model=model,
    vectorizer_model=vectorizer_model,
    nr_topics="auto",
    top_n_words=10,       
    calculate_probabilities=True,
    min_topic_size=30 #reduces overly small clusters
)

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/594 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [465]:
topics, probs = topic_model.fit_transform(texts)

In [489]:
topic_model.get_topic_info().to_csv("new_paraphrase_topics.csv", index=False)

In [477]:
dfm.drop(['topic_name', 'topic_repr'], axis=1, inplace=True)

In [479]:
dfm['topic'] = topics

In [483]:
tpm_small = topic_model.get_topic_info()[['Topic', 'Name', 'Representation']].rename(
    columns={'Topic':'topic', 'Name':'topic_name', 'Representation':'topic_repr'}
)

# Left-join so every video row gets the topic label/keywords
dfm = dfm.merge(tpm_small, on='topic', how='left')

In [487]:
dfm.to_csv("new_paraphrase_dataset.csv", index=False)

Paraphrases MPnet SentenceTransformer analysis
-

Let's analyze the topics given by the Paraphrase Sentence Transformer.

In [502]:
import pandas as pd

dfp = pd.read_csv("new_paraphrase_dataset.csv")
tpp = pd.read_csv("new_paraphrase_topics.csv")

In [504]:
tpp

,Topic,Count,Name,Representation,Representative_Docs
0,-1,6094,-1_longevity_healthy_healthy aging_anti,"['longevity', 'healthy', 'healthy aging', 'ant...",['The Healthy Ageing Secret The secret to heal...
1,0,3235,0_nootropics_nootropic_brain_stack,"['nootropics', 'nootropic', 'brain', 'stack', ...",['#lionsmane #lionsmanemushroom #nootropics #c...
2,1,2794,1_skin_anti_anti aging_facial,"['skin', 'anti', 'anti aging', 'facial', 'faci...","['Facial rejuvenation ', 'Dr Kusuma: What is ..."
3,2,2746,2_biohacking_biohacker_biohack_bulletproof,"['biohacking', 'biohacker', 'biohack', 'bullet...",['А вы следите за уровнем глюкозы? #биохакинг ...
4,3,1084,3_rejuvenation_music_provided youtube_provided,"['rejuvenation', 'music', 'provided youtube', ...",['Cultured Moments for Rejuvenation Provided t...
5,4,779,4_diet_foods_nutrition_longevity,"['diet', 'foods', 'nutrition', 'longevity', 'e...","[""We did the ProLon five day fast-mimicking lo..."
6,5,676,5_longevity_longevity tv_jeunesse_tv,"['longevity', 'longevity tv', 'jeunesse', 'tv'...",['Jeunesse Longevity TV PL Episode 1 1080P ...
7,6,642,6_healthy aging_healthy_health_healthy ageing,"['healthy aging', 'healthy', 'health', 'health...","['Healthy Aging Kin 250.', 'Healthy Aging RC v..."
8,7,563,7_exercise_fitness_yoga_exercises,"['exercise', 'fitness', 'yoga', 'exercises', '...",['Exercise for Health and Longevity Do you nee...
9,8,265,8_brain_alzheimer_dementia_aging brain,"['brain', 'alzheimer', 'dementia', 'aging brai...","[""Healthy Brain Aging &amp; Dementia Preventio..."
10,9,110,9_qvc_information buy_buy http_buy,"['qvc', 'information buy', 'buy http', 'buy', ...",['IT Cosmetics No-Tug Anti-Aging Waterproof Ge...
11,10,103,10_hand_hand rejuvenation_hands_radiesse,"['hand', 'hand rejuvenation', 'hands', 'radies...",['Hand Rejuvenation at Moradi MD Dr. Amir Mora...
12,11,90,11_di_el_la_que,"['di', 'el', 'la', 'que', 'il', 'medicina', 'p...",['Chilena exigió medicamento para cáncer Una m...
13,12,81,12_die_und_der_für,"['die', 'und', 'der', 'für', 'ist', 'das', 'si...",['NAD - Shootingstar der Anti-Aging-Substanzen...
14,13,71,13_shorts_skincare_dermatologist_youtubeshorts,"['shorts', 'skincare', 'dermatologist', 'youtu...",['The Best Anti-Aging Skincare Routine SHORTSM...
15,14,71,14_coffee_tea_longevity power_longevity,"['coffee', 'tea', 'longevity power', 'longevit...",['Longevity Irish Cream Coffee For more info o...
16,15,70,15_vaginal_vaginal rejuvenation_rejuvenation_l...,"['vaginal', 'vaginal rejuvenation', 'rejuvenat...","['⭕️ Vaginal Rejuvenation (Vaginoplasty, Vagin..."
17,16,70,16_sleep_melatonin_15 minutes_night,"['sleep', 'melatonin', '15 minutes', 'night', ...","['Yeah Yeah Yeah, Sleep... ""I\'ll Sleep When I..."
18,17,70,17_light_led_light therapy_therapy,"['light', 'led', 'light therapy', 'therapy', '...",['Review Renelif Neck led light Therapy device...
19,18,67,18_nmn_nad_resveratrol_supplements,"['nmn', 'nad', 'resveratrol', 'supplements', '...",['What is the best dose of NMN? #antiaging #lo...
20,19,66,19_exercise video_video demonstrating_ball_exe...,"['exercise video', 'video demonstrating', 'bal...",['REJUVENATION | SHOULDER PRESS Rejuvenation P...
21,20,65,20_prp_plasma_rich plasma_platelet rich,"['prp', 'plasma', 'rich plasma', 'platelet ric...",['PRP treatment for Face and Neck rejuvenation...
22,21,60,21_album_longevity_official_feat,"['album', 'longevity', 'official', 'feat', 'mu...",['dani3l - Longevity (feat. Millyz) (Official ...
23,22,58,22_massage_face_face yoga_face massage,"['massage', 'face', 'face yoga', 'face massage...",['Face Yoga &amp; Massage for Glowing Skin | N...
24,23,57,23_aging month_month_september_healthy aging,"['aging month', 'month', 'september', 'healthy...",['September is Health Aging Month http://www.c...
25,24,56,24_ovarian_fertility_prp_rejuvenation,"['ovarian', 'fertility', 'prp', 'rejuvenation'...",['Ovarian rejuvenation PRP Ovarian rejuvenatio...
26,25,51,25_ipl_ipl skin_skin rejuvenation_hair removal,"['ipl', 'ipl skin', 'skin rejuvenation', 'hair...",['IPL Skin Rejuvenation Treatment BIODROGA MD ...
27,26,49,26_muscle_mass_muscle mass_strength,"['muscle', 'mass', 'muscle mass', 'strength', ...",['Maintaining Muscle Mass: The Key to Healthy ...
28,27,47,27_microneedling_micro_microdermabrasion_dermapen,"['microneedling', 'micro', 'microdermabrasion'...",['How does MICRONEEDLING reverse signs of agin...
29,28,46,28_hormone_replacement_replacement therapy_hor...,"['hormone', 'replacement', 'replacement therap...",['Hormone Replacement Therapy Center - Tampa H...
30,29,45,29_stem_cell_stem cell_cell therapy,"['stem', 'cell', 'stem cell', 'cell therapy', ...",['Stem Cell Anti Aging After a preventive medi...
31,30,45,30_nedir_anti_anti aging_ve,"['nedir', 'anti', 'anti aging', 've', 'hifu', ...","[""Anti-aging nedir? Dr. Ayşe Ferzan Aytuğ anti..."
32,31,42,31_insurance_longevity risk_risk_retirement,"['insurance', 'longevity risk', 'risk', 'retir...",['Analysis of past trends and future drivers n...
33,32,39,32_oral_oral health_dental_dentist,"['oral', 'oral health', 'dental', 'dentist', '...",['Nutrition and Oral Health | Aging Matters | ...
34,33,39,33_telomeres_telomere_isagenix_support,"['telomeres', 'telomere', 'isagenix', 'support...",['Isagenix Product B - Antioxidants with Telom...
35,34,37,34_golden habits_golden_habits_habits healthy,"['golden habits', 'golden', 'habits', 'habits ...",['“5 Golden Habits for Healthy Aging — Discove...
36,35,36,35_body biohack_performance energy_talked_heal...,"['body biohack', 'performance energy', 'talked...",['What part of your body would you BIOHACK? We...
37,36,36,36_fall_fall prevention_falls_aging fall,"['fall', 'fall prevention', 'falls', 'aging fa...",['5 Considerations for Healthy Aging and Fall ...
38,37,34,37_aging video_powtoon_animated_healthy,"['aging video', 'powtoon', 'animated', 'health...",['To dads everywhere: Healthy Aging This video...
39,38,32,38_mental health_depression_mental_older,"['mental health', 'depression', 'mental', 'old...",['Aging and Mental Health Older adults face ma...
40,39,32,39_co2_laser_co2 laser_carbon,"['co2', 'laser', 'co2 laser', 'carbon', 'peel'...",['FX CO2 laser rejuvenation of the face and ne...
41,40,32,40_collagen_peptides_peptide_supplement,"['collagen', 'peptides', 'peptide', 'supplemen...","[""HEALTHFARM Premium Anti-aging Marine Collage..."
42,41,32,41_sublative_sublative rejuvenation_ematrix_em...,"['sublative', 'sublative rejuvenation', 'ematr...",['What is Sublative Rejuvenation? Sublative Re...
43,42,32,42_com healthy_transformational_watch free_abi...,"['com healthy', 'transformational', 'watch fre...",['Healthy Aging Sachin Patel https://www.avaiy...
44,43,31,43_develop smart_memory loss_develop_age related,"['develop smart', 'memory loss', 'develop', 'a...",['llive discussion can we should we devel...
45,44,31,44_nerium_real results_real_larry,"['nerium', 'real results', 'real', 'larry', 'a...",['Nerium International - Nerium Oleander Anti-...
46,45,30,45_center_longevity center_longevity_wellness,"['center', 'longevity center', 'longevity', 'w...",['THE KUROTEL SPA AND LONGEVITY CENTER THE KUR...

Let's check the relevance ratio of the each topic with the previosly applied method

In [509]:
#function to check if the video is related or unrelated

def is_video_related(text, keywords):
    text = str(text).lower()
    return any(kw in text for kw in keywords)

In [511]:
#function to check how many percentage of the videos in the topics are related
def check_relevance_ratio(df, topic_id, keywords):
    df_topic = df[df['topic']==topic_id]
    relevant_count = df_topic['text'].apply(lambda x: is_video_related(x, keywords)).sum()
    return relevant_count/len(df_topic)

keywords = ["longevity", "healthy aging", "biohacking", "rejuvenation", "anti-aging", "nootropics"]

In [513]:
tpp['relevance_ratio'] = tpp['Topic'].apply(lambda t: check_relevance_ratio(dfp, t, keywords))

In [515]:
tpp

,Topic,Count,Name,Representation,Representative_Docs,relevance_ratio
0,-1,6094,-1_longevity_healthy_healthy aging_anti,"['longevity', 'healthy', 'healthy aging', 'ant...",['The Healthy Ageing Secret The secret to heal...,0.778142
1,0,3235,0_nootropics_nootropic_brain_stack,"['nootropics', 'nootropic', 'brain', 'stack', ...",['#lionsmane #lionsmanemushroom #nootropics #c...,0.640185
2,1,2794,1_skin_anti_anti aging_facial,"['skin', 'anti', 'anti aging', 'facial', 'faci...","['Facial rejuvenation ', 'Dr Kusuma: What is ...",0.803865
3,2,2746,2_biohacking_biohacker_biohack_bulletproof,"['biohacking', 'biohacker', 'biohack', 'bullet...",['А вы следите за уровнем глюкозы? #биохакинг ...,0.691916
4,3,1084,3_rejuvenation_music_provided youtube_provided,"['rejuvenation', 'music', 'provided youtube', ...",['Cultured Moments for Rejuvenation Provided t...,0.882841
5,4,779,4_diet_foods_nutrition_longevity,"['diet', 'foods', 'nutrition', 'longevity', 'e...","[""We did the ProLon five day fast-mimicking lo...",0.820282
6,5,676,5_longevity_longevity tv_jeunesse_tv,"['longevity', 'longevity tv', 'jeunesse', 'tv'...",['Jeunesse Longevity TV PL Episode 1 1080P ...,0.980769
7,6,642,6_healthy aging_healthy_health_healthy ageing,"['healthy aging', 'healthy', 'health', 'health...","['Healthy Aging Kin 250.', 'Healthy Aging RC v...",0.691589
8,7,563,7_exercise_fitness_yoga_exercises,"['exercise', 'fitness', 'yoga', 'exercises', '...",['Exercise for Health and Longevity Do you nee...,0.824156
9,8,265,8_brain_alzheimer_dementia_aging brain,"['brain', 'alzheimer', 'dementia', 'aging brai...","[""Healthy Brain Aging &amp; Dementia Preventio...",0.422642
10,9,110,9_qvc_information buy_buy http_buy,"['qvc', 'information buy', 'buy http', 'buy', ...",['IT Cosmetics No-Tug Anti-Aging Waterproof Ge...,0.945455
11,10,103,10_hand_hand rejuvenation_hands_radiesse,"['hand', 'hand rejuvenation', 'hands', 'radies...",['Hand Rejuvenation at Moradi MD Dr. Amir Mora...,0.980583
12,11,90,11_di_el_la_que,"['di', 'el', 'la', 'que', 'il', 'medicina', 'p...",['Chilena exigió medicamento para cáncer Una m...,0.488889
13,12,81,12_die_und_der_für,"['die', 'und', 'der', 'für', 'ist', 'das', 'si...",['NAD - Shootingstar der Anti-Aging-Substanzen...,0.728395
14,13,71,13_shorts_skincare_dermatologist_youtubeshorts,"['shorts', 'skincare', 'dermatologist', 'youtu...",['The Best Anti-Aging Skincare Routine SHORTSM...,0.605634
15,14,71,14_coffee_tea_longevity power_longevity,"['coffee', 'tea', 'longevity power', 'longevit...",['Longevity Irish Cream Coffee For more info o...,0.887324
16,15,70,15_vaginal_vaginal rejuvenation_rejuvenation_l...,"['vaginal', 'vaginal rejuvenation', 'rejuvenat...","['⭕️ Vaginal Rejuvenation (Vaginoplasty, Vagin...",0.985714
17,16,70,16_sleep_melatonin_15 minutes_night,"['sleep', 'melatonin', '15 minutes', 'night', ...","['Yeah Yeah Yeah, Sleep... ""I\'ll Sleep When I...",0.600000
18,17,70,17_light_led_light therapy_therapy,"['light', 'led', 'light therapy', 'therapy', '...",['Review Renelif Neck led light Therapy device...,0.857143
19,18,67,18_nmn_nad_resveratrol_supplements,"['nmn', 'nad', 'resveratrol', 'supplements', '...",['What is the best dose of NMN? #antiaging #lo...,0.850746
20,19,66,19_exercise video_video demonstrating_ball_exe...,"['exercise video', 'video demonstrating', 'bal...",['REJUVENATION | SHOULDER PRESS Rejuvenation P...,0.621212
21,20,65,20_prp_plasma_rich plasma_platelet rich,"['prp', 'plasma', 'rich plasma', 'platelet ric...",['PRP treatment for Face and Neck rejuvenation...,0.969231
22,21,60,21_album_longevity_official_feat,"['album', 'longevity', 'official', 'feat', 'mu...",['dani3l - Longevity (feat. Millyz) (Official ...,0.983333
23,22,58,22_massage_face_face yoga_face massage,"['massage', 'face', 'face yoga', 'face massage...",['Face Yoga &amp; Massage for Glowing Skin | N...,0.500000
24,23,57,23_aging month_month_september_healthy aging,"['aging month', 'month', 'september', 'healthy...",['September is Health Aging Month http://www.c...,0.964912
25,24,56,24_ovarian_fertility_prp_rejuvenation,"['ovarian', 'fertility', 'prp', 'rejuvenation'...",['Ovarian rejuvenation PRP Ovarian rejuvenatio...,0.964286
26,25,51,25_ipl_ipl skin_skin rejuvenation_hair removal,"['ipl', 'ipl skin', 'skin rejuvenation', 'hair...",['IPL Skin Rejuvenation Treatment BIODROGA MD ...,0.980392
27,26,49,26_muscle_mass_muscle mass_strength,"['muscle', 'mass', 'muscle mass', 'strength', ...",['Maintaining Muscle Mass: The Key to Healthy ...,0.816327
28,27,47,27_microneedling_micro_microdermabrasion_dermapen,"['microneedling', 'micro', 'microdermabrasion'...",['How does MICRONEEDLING reverse signs of agin...,0.893617
29,28,46,28_hormone_replacement_replacement therapy_hor...,"['hormone', 'replacement', 'replacement therap...",['Hormone Replacement Therapy Center - Tampa H...,0.717391
30,29,45,29_stem_cell_stem cell_cell therapy,"['stem', 'cell', 'stem cell', 'cell therapy', ...",['Stem Cell Anti Aging After a preventive medi...,0.666667
31,30,45,30_nedir_anti_anti aging_ve,"['nedir', 'anti', 'anti aging', 've', 'hifu', ...","[""Anti-aging nedir? Dr. Ayşe Ferzan Aytuğ anti...",0.600000
32,31,42,31_insurance_longevity risk_risk_retirement,"['insurance', 'longevity risk', 'risk', 'retir...",['Analysis of past trends and future drivers n...,1.000000
33,32,39,32_oral_oral health_dental_dentist,"['oral', 'oral health', 'dental', 'dentist', '...",['Nutrition and Oral Health | Aging Matters | ...,0.538462
34,33,39,33_telomeres_telomere_isagenix_support,"['telomeres', 'telomere', 'isagenix', 'support...",['Isagenix Product B - Antioxidants with Telom...,0.846154
35,34,37,34_golden habits_golden_habits_habits healthy,"['golden habits', 'golden', 'habits', 'habits ...",['“5 Golden Habits for Healthy Aging — Discove...,0.864865
36,35,36,35_body biohack_performance energy_talked_heal...,"['body biohack', 'performance energy', 'talked...",['What part of your body would you BIOHACK? We...,0.972222
37,36,36,36_fall_fall prevention_falls_aging fall,"['fall', 'fall prevention', 'falls', 'aging fa...",['5 Considerations for Healthy Aging and Fall ...,0.750000
38,37,34,37_aging video_powtoon_animated_healthy,"['aging video', 'powtoon', 'animated', 'health...",['To dads everywhere: Healthy Aging This video...,0.676471
39,38,32,38_mental health_depression_mental_older,"['mental health', 'depression', 'mental', 'old...",['Aging and Mental Health Older adults face ma...,0.312500
40,39,32,39_co2_laser_co2 laser_carbon,"['co2', 'laser', 'co2 laser', 'carbon', 'peel'...",['FX CO2 laser rejuvenation of the face and ne...,0.875000
41,40,32,40_collagen_peptides_peptide_supplement,"['collagen', 'peptides', 'peptide', 'supplemen...","[""HEALTHFARM Premium Anti-aging Marine Collage...",0.781250
42,41,32,41_sublative_sublative rejuvenation_ematrix_em...,"['sublative', 'sublative rejuvenation', 'ematr...",['What is Sublative Rejuvenation? Sublative Re...,0.968750
43,42,32,42_com healthy_transformational_watch free_abi...,"['com healthy', 'transformational', 'watch fre...",['Healthy Aging Sachin Patel https://www.avaiy...,0.937500
44,43,31,43_develop smart_memory loss_develop_age related,"['develop smart', 'memory loss', 'develop', 'a...",['llive discussion can we should we devel...,0.032258
45,44,31,44_nerium_real results_real_larry,"['nerium', 'real results', 'real', 'larry', 'a...",['Nerium International - Nerium Oleander Anti-...,0.548387
46,45,30,45_center_longevity center_longevity_wellness,"['center', 'longevity center', 'longevity', 'w...",['THE KUROTEL SPA AND LONGEVITY CENTER THE KUR...,0.966667

Relevance ratio of the all topics are more or less good. Let's analyze the topics number 11 and 12 since they seem like consisting of vidieo which are not english

In [524]:
dfp[dfp['topic']==11].head(50)

,source,video_id,video_url,title,description,channel,comments,views,likes,comments_count,...,country,date,likes_missing,year,engagement,engagement_rate,text,topic,topic_name,topic_repr
190,YouTube,p42oD2ycxi8,https://www.youtube.com/watch?v=p42oD2ycxi8,Chilena exigió medicamento para cáncer,Una mujer llegó a los tribunales exigiendo que...,Univision,NaN,261.0,0.0,0.0,...,unknown,2010-03-05,False,2010,0.0,0.000000,Chilena exigió medicamento para cáncer Una muj...,11,11_di_el_la_que,"['di', 'el', 'la', 'que', 'il', 'medicina', 'p..."
433,YouTube,y8p6yRq_62Y,https://www.youtube.com/watch?v=y8p6yRq_62Y,Pieles rejuvenecidas con las últimas técnicas ...,Vídeo para un evento deportivo con el que Clín...,Puntual Webmaster,NaN,84.0,0.0,0.0,...,unknown,2010-05-26,False,2010,0.0,0.000000,Pieles rejuvenecidas con las últimas técnicas ...,11,11_di_el_la_que,"['di', 'el', 'la', 'que', 'il', 'medicina', 'p..."
465,YouTube,x1l8Zho5rA4,https://www.youtube.com/watch?v=x1l8Zho5rA4,LaCore anti aging Promo Español,bHIP GLOBAL ha desarrollado la línea de produc...,sammuss,NaN,455.0,2.0,0.0,...,unknown,2010-06-04,False,2010,2.0,0.004396,LaCore anti aging Promo Español bHIP GLOBAL ha...,11,11_di_el_la_que,"['di', 'el', 'la', 'que', 'il', 'medicina', 'p..."
490,YouTube,1zHt5fx2O1M,https://www.youtube.com/watch?v=1zHt5fx2O1M,VITAMINE PER LA MENTE - LO SPECCHIO,Direttamente dal Format ''Sono un Genio'' del ...,Emiliano Schincaglia,NaN,138.0,0.0,0.0,...,unknown,2010-06-11,False,2010,0.0,0.000000,VITAMINE PER LA MENTE - LO SPECCHIO Direttamen...,11,11_di_el_la_que,"['di', 'el', 'la', 'que', 'il', 'medicina', 'p..."
640,YouTube,4HPLwj_WDNk,https://www.youtube.com/watch?v=4HPLwj_WDNk,Pharmavita RENACENZ TVN Enlaces parte2.mov,2º Parte de el programa Enlaces de TVN realiza...,Pharmavita,NaN,2706.0,12.0,0.0,...,unknown,2010-07-22,False,2010,12.0,0.004435,Pharmavita RENACENZ TVN Enlaces parte2.mov 2º ...,11,11_di_el_la_que,"['di', 'el', 'la', 'que', 'il', 'medicina', 'p..."
641,YouTube,enYjNAEq4Mc,https://www.youtube.com/watch?v=enYjNAEq4Mc,Renacenz testimonios reales,El noticiario Meganoticias realiza reportaje s...,Pharmavita,NaN,13005.0,50.0,0.0,...,unknown,2010-07-22,False,2010,50.0,0.003845,Renacenz testimonios reales El noticiario Mega...,11,11_di_el_la_que,"['di', 'el', 'la', 'que', 'il', 'medicina', 'p..."
649,YouTube,Yq75McpR02E,https://www.youtube.com/watch?v=Yq75McpR02E,Sei nuove droghe,22/07/10 (1536-69) - Sono state scoperte 6 nuo...,SteadyInfo,w la Marijuana terapeutica le altre sostanze s...,3114.0,5.0,5.0,...,unknown,2010-07-26,False,2010,10.0,0.003211,Sei nuove droghe 22/07/10 (1536-69) - Sono sta...,11,11_di_el_la_que,"['di', 'el', 'la', 'que', 'il', 'medicina', 'p..."
685,YouTube,Q74bPzxz9lM,https://www.youtube.com/watch?v=Q74bPzxz9lM,Questura di Verona - Sequestro smart-shop di V...,"JWH-018 e JWH-073, si presentano come profumi ...",Osservatorio dipendenze,NaN,2069.0,4.0,0.0,...,unknown,2010-08-04,False,2010,4.0,0.001933,Questura di Verona - Sequestro smart-shop di V...,11,11_di_el_la_que,"['di', 'el', 'la', 'que', 'il', 'medicina', 'p..."
871,YouTube,jL4jbDxw7tY,https://www.youtube.com/watch?v=jL4jbDxw7tY,Fashionista Recommends Anti-Aging Formula,1-800-260-9404 http://www.MAQUILLAJE.co entrev...,AntiAgingSkinCompany,NaN,103.0,1.0,0.0,...,unknown,2010-09-26,False,2010,1.0,0.009709,Fashionista Recommends Anti-Aging Formula 1-80...,11,11_di_el_la_que,"['di', 'el', 'la', 'que', 'il', 'medicina', 'p..."
895,YouTube,FLkjpUX63cM,https://www.youtube.com/watch?v=FLkjpUX63cM,Cremes para rugas,Os cremes antirrugas ou antissinais bloqueiam ...,Minha Vida,Ou morrendo cedo kkkkkkk || Só cirurgia plásti...,50276.0,278.0,4.0,...,unknown,2010-09-30,False,2010,282.0,0.005609,Cremes para rugas Os cremes antirrugas ou anti...,11,11_di_el_la_que,"['di', 'el', 'la', 'que', 'il', 'medicina', 'p..."
1109,YouTube,3WrCuuhNkW8,https://www.youtube.com/watch?v=3WrCuuhNkW8,"LA NUOVA DROGA, OSSICODONE by Rai3 Umbria post...",NaN,Umbria JournalTV,NaN,6723.0,19.0,0.0,...,unknown,2010-11-18,False,2010,19.0,0.002826,"LA NUOVA DROGA, OSSICODONE by Rai3 Umbria post...",11,11_di_el_la_que,"['di', 'el', 'la', 'que', 'il', 'medicina', 'p..."
1127,YouTube,_0IqQHgNUGk,https://www.youtube.com/watch?v=_0IqQHgNUGk,IV OPEN CIDADE VILA DO CONDE Rotina Filipe Cor...,IV OPEN CIDADE VILA DO CONDE Rotina Filipe Cor...,slnutrition,NaN,555.0,2.0,0.0,...,unknown,2010-11-24,False,2010,2.0,0.003604,IV OPEN CIDADE VILA DO CONDE Rotina Filipe Cor...,11,11_di_el_la_que,"['di', 'el', 'la', 'que', 'il', 'medicina', 'p..."
1663,YouTube,NCABX9mXueM,https://www.youtube.com/watch?v=NCABX9mXueM,Envelhecimento,Dr. Drauzio Varella fala sobre envelhecimento ...,PedroHealth,Ao contrário sempre com 53 quilos a 54 quilos ...,158805.0,1376.0,33.0,...,unknown,2011-05-11,False,2011,1409.0,0.008873,Envelhecimento Dr. Drauzio Varella fala sobre ...,11,11_di_el_la_que,"['di', 'el', 'la', 'que', 'il', 'medicina', 'p..."
1712,YouTube,0NW5PxMGRes,https://www.youtube.com/watch?v=0NW5PxMGRes,Medicina anti-aging en Uhma salud,Conoce cada paso del programa de medicina prev...,Uhma Salud,interesante :D,1826.0,4.0,2.0,...,unknown,2011-05-25,False,2011,6.0,0.003286,Medicina anti-aging en Uhma salud Conoce cada ...,11,11_di_el_la_que,"['di', 'el', 'la', 'que', 'il', 'medicina', 'p..."
2122,YouTube,3ahAZEGd2nU,https://www.youtube.com/watch?v=3ahAZEGd2nU,Vitamina D e anziani,"Intervista al Prof. Paolo Falaschi, UO di Geri...",PharmaStarTV,NaN,648.0,2.0,0.0,...,unknown,2011-10-03,False,2011,2.0,0.003086,Vitamina D e anziani Intervista al Prof. Paolo...,11,11_di_el_la_que,"['di', 'el', 'la', 'que', 'il', 'medicina', 'p..."
2147,YouTube,6E2nd-nWKlU,https://www.youtube.com/watch?v=6E2nd-nWKlU,Clínica Estética e Anti-Aging em Natal-RN - Pr...,Entrevista com Dra. Sonia no Programa Médico A...,clinicainforma,NaN,929.0,7.0,0.0,...,unknown,2011-10-09,False,2011,7.0,0.007535,Clínica Estética e Anti-Aging em Natal-RN - Pr...,11,11_di_el_la_que,"['di', 'el', 'la', 'que', 'il', 'medicina', 'p..."
2170,YouTube,X20OlbqSF5k,https://www.youtube.com/watch?v=X20OlbqSF5k,TEDxSol - Jesús Ávila - Cómo podríamos evitar ...,Jesús Ávila es Investigador del Centro de Biol...,TEDx Talks,SE EVITA COCINANDO CON ACEITE DE COCO ORGANICO...,14112.0,343.0,6.0,...,unknown,2011-10-17,False,2011,349.0,0.024731,TEDxSol - Jesús Ávila - Cómo podríamos evitar ...,11,11_di_el_la_que,"['di', 'el', 'la', 'que', 'il', 'medicina', 'p..."
2390,YouTube,tIKmufI8rV8,https://www.youtube.com/watch?v=tIKmufI8rV8,"«Απρόσεχτος συχνά, αδιάφορος ποτέ!» από το Αχε...",http://kourakis.blogspot.com 24 Οκτωβρίου 2011...,"Δρ. Σήφης Κουράκης, Παιδοψυχολόγος",NaN,299.0,1.0,0.0,...,unknown,2011-12-16,False,2011,1.0,0.003344,"«Απρόσεχτος συχνά, αδιάφορος ποτέ!» από το Αχε...",11,11_di_el_la_que,"['di', 'el', 'la', 'que', 'il', 'medicina', 'p..."
2444,YouTube,z9-WtYwJA-Q,https://www.youtube.com/watch?v=z9-WtYwJA-Q,envejeciendo.avi,Como pasan los años.,Nicolas Enciso,NaN,64.0,0.0,0.0,...,unknown,2011-12-27,False,2011,0.0,0.000000,envejeciendo.avi Como pasan los años.,11,11_di_el_la_que,"['di', 'el', 'la', 'que', 'il', 'medicina', 'p..."
2451,YouTube,EWXTaUAz4Zg,https://www.youtube.com/watch?v=EWXTaUAz4Zg,30 Minutos Viviendo con el Alzheimer - Telemadrid,http://www.telemadrid.es] 14.12.2011 30 Minuto...,Alzheimer Universal,"A nuestra madre porque no la soporto , Se afer...",311243.0,2241.0,156.0,...,unknown,2011-12-29,False,2011,2397.0,0.007701,30 Minutos Viviendo con el Alzheimer - Telemad...,11,11_di_el_la_que,"['di', 'el', 'la', 'que', 'il', 'medicina', 'p..."
3068,YouTube,KfFcqsqaFzs,https://www.youtube.com/watch?v=KfFcqsqaFzs,Alerta por consumo de pastillas inteligentes e...,Informe de América Noticias sobre el peligro d...,Cedro Peru,Si es taaaaaaaan nocivo ¿por qué en países com...,34116.0,36.0,25.0,...,unknown,2012-07-12,False,2012,61.0,0.001788,Alerta por consumo de pastillas inteligentes e...,11,11_di_el_la_que,"['di', 'el', 'la', 'que', 'il', 'medicina', 'p..."
3071,YouTube,AU8i7TNS2aQ,https://www.youtube.com/watch?v=AU8i7TNS2aQ,Alerta con las &quot;Drogas Inteligentes&quot;...,"Nota periodística sobre las ""Drogas Inteligent...",Cedro Peru,En Miraflores lo vendes 128 soles || Necesito ...,4535.0,29.0,16.0,...,unknown,2012-07-12,False,2012,45.0,0.009923,Alerta con las &quot;Drogas Inteligentes&quot;...,11,11_di_el_la_que,"['di', 'el', 'la', 'que', 'il', 'medicina', 'p..."
3073,YouTube,R37wv1JUvzQ,https://www.youtube.com/watch?v=R37wv1JUvzQ,120712 Consumo de &#39;&#39;drogas inteligente...,NaN,PrensaJN19,NaN,249.0,2.0,0.0,...,unknown,2012-07-13,False,2012,2.0,0.008032,120712 Consumo de &#39;&#39;drogas inteligente...,11,11_di_el_la_que,"['di', 'el', 'la', 'que', 'il', 'medicina', 'p..."
3335,YouTube,lnavYbAp5_A,https://www.youtube.com/watch?v=lnavYbAp5_A,Medicina Anti Aging Reggio Emilia Vita Preziosa,"Medicina anti ètà a reggio emilia, percorso Vi...",Poliambulatorio Privato San Michele,NaN,138.0,2.0,0.0,...,unknown,2012-09-25,False,2012,2.0,0.014493,Medicina Anti Aging Reggio Emilia Vita Prezios...,11,11_di_el_la_que,"['di', 'el', 'la', 'que', 'il', 'medicina', 'p..."
3524,YouTube,eNHYeA5b-Ow,https://www.youtube.com/watch?v=eNHYeA5b-Ow,DVD Nutrição Clínica em Anti-Aging,Aprenda os segredos e perólas da Nutrição Clín...,BARM Brasil,NaN,1927.0,26.0,0.0,...,unknown,2012-11-13,False,2012,26.0,0.013492,DVD Nutrição Clínica em Anti-Aging Aprenda os ...,11,11_di_el_la_que,"['di', 'el', 'la', 'que', 'il', 'medicina', 'p..."
3614,YouTube,DVdqNqeISWM,https://www.youtube.com/watch?v=DVdqNqeISWM,Test complement santé : N-acetylglucosamine n...,Demande ton bilan personnalisé et obtiens un p...,Sharefitness,NaN,4005.0,0.0,0.0,...,unknown,2012-12-08,True,2012,0.0,0.000000,Test complement santé : N-acetylglucosamine n...,11,11_di_el_la_que,"['di', 'el', 'la', 'que', 'il', 'medicina', 'p..."
4143,YouTube,R7fTuSSoG3s,https://www.youtube.com/watch?v=R7fTuSSoG3s,O que é Piracetam,NaN,Vistg,Com quantas semanas começa fazer efeito.duas s...,20006.0,197.0,7.0,...,unknown,2013-05-20,False,2013,204.0,0.010197,O que é Piracetam,11,11_di_el_la_que,"['di', 'el', 'la', 'que', 'il', 'medicina', 'p..."
4222,YouTube,9cq7EHOMhZ0,https://www.youtube.com/watch?v=9cq7EHOMhZ0,Medicina healthy-aging,Un piccolo estratto dell'intervento della Dr. ...,Primiano Panunzio,NaN,39.0,1.0,0.0,...,unknown,2013-06-10,False,2013,1.0,0.025641,Medicina healthy-aging Un piccolo estratto del...,11,11_di_el_la_que,"['di', 'el', 'la', 'que', 'il', 'medicina', 'p..."
4267,YouTube,cDX2L9xNkDs,https://www.youtube.com/watch?v=cDX2L9xNkDs,Fernando Armas se somete a tratamiento de reju...,El jurado de 'Yo Soy' desea desaparecer las ar...,Latina Televisión,NaN,358.0,0.0,0.0,...,es-419,2013-06-24,False,2013,0.0,0.000000,Fernando Armas se somete a tratamiento de reju...,11,11_di_el_la_que,"['di', 'el', 'la', 'que', 'il', 'medicina', 'p..."
4292,YouTube,Cd2ujrPY-_M,https://www.youtube.com/watch?v=Cd2ujrPY-_M,Ageing@Coimbra,Coimbra foi distinguida pela União Europeia co...,Universidade de Coimbra,NaN,107.0,3.0,0.0,...,unknown,2013-07-02,False,2013,3.0,0.028037,Ageing@Coimbra Coimbra foi distinguida pela Un...,11,11_di_el_la_que,"['di', 'el', 'la', 'que', 'il', 'medicina', 'p..."
4618,YouTube,io931dZ9BFQ,https://www.youtube.com/watch?v=io931dZ9BFQ,Massimo Spattini - Convegno &quot;Alimentazion...,"Cos'è la Medicina Funzionale Convegno ""Aliment...",Massimo Spattini,NaN,4660.0,49.0,0.0,...,unknown,2013-10-05,False,2013,49.0,0.010515,Massimo Spattini - Convegno &quot;Alimentazion...,11,11_di_el_la_que,"['di', 'el', 'la', 'que', 'il', 'medicina', 'p..."
5198,YouTube,fZ4MY1Hf18w,https://www.youtube.com/watch?v=fZ4MY1Hf18w,Anleitung Vitamin-D Test Biotrakr,"Wir wollen den einfachsten Bluttest anbieten, ...",Flowgrade,Muss mann nüchtern sein ? || This doesn&#39;t ...,6619.0,18.0,2.0,...,de,2014-03-01,False,2014,20.0,0.003022,Anleitung Vitamin-D Test Biotrakr Wir wollen d...,11,11_di_el_la_que,"['di', 'el', 'la', 'que', 'il', 'medicina', 'p..."
5309,YouTube,yXJZd-PKCoQ,https://www.youtube.com/watch?v=yXJZd-PKCoQ,Conferinta Active Healthy Aging,Centrul Infoeuropa din cadrul Ministerului Afa...,Core Invest Health,NaN,99.0,1.0,0.0,...,unknown,2014-04-02,False,2014,1.0,0.010101,Conferinta Active Healthy Aging Centrul Infoeu...,11,11_di_el_la_que,"['di', 'el', 'la', 'que', 'il', 'medicina', 'p..."
5358,YouTube,SqRm_lMXQD4,https://www.youtube.com/watch?v=SqRm_lMXQD4,"IL TEMPO PER SÈ | Living Healthy, Aging Well",IL TEMPO PER SÉ® è una società di professionis...,Gianluca Galli (IL TEMPO PER SÈ),"OTTIMO ED EFFICACE, MA PERCHE, AL FUTURO E NON...",359.0,4.0,2.0,...,unknown,2014-04-18,False,2014,6.0,0.016713,"IL TEMPO PER SÈ | Living Healthy, Aging Well...",11,11_di_el_la_que,"['di', 'el', 'la', 'que', 'il', 'medicina', 'p..."
5597,YouTube,l3KC3cYKe-c,https://www.youtube.com/watch?v=l3KC3cYKe-c,Medicina Anti-Aging com a Dra. Carla Aquino na...,Todos queremos viver mais anos e com saúde. A ...,SYNLAB Portugal,NaN,2126.0,14.0,0.0,...,pt,2014-07-01,False,2014,14.0,0.006585,Medicina Anti-Aging com a Dra. Carla Aquino na...,11,11_di_el_la_que,"['di', 'el', 'la', 'que', 'il', 'medicina', 'p..."
5873,YouTube,ZlqT8udXXDg,https://www.youtube.com/watch?v=ZlqT8udXXDg,Julien Farel Anti-Aging Haircare : La storia d...,E 'ora possibile avere dei capelli belli e san...,"Julien Farel Restore Salon, Spa & Fitness",NaN,427.0,0.0,0.0,...,unknown,2014-09-10,False,2014,0.0,0.000000,Julien Farel Anti-Aging Haircare : La storia d...,11,11_di_el_la_que,"['di', 'el', 'la', 'que', 'il', 'medicina', 'p..."
6136,YouTube,0Pm10MjLNQI,https://www.youtube.com/watch?v=0Pm10MjLNQI,(altre) 50 Cose che Non Sai su MINECRAFT,Visto il discreto successo dello scorso video ...,BioHack *,ho mio dio che bei ricordi e fu cosi che ho co...,1709619.0,27642.0,1539.0,...,zxx,2014-11-12,False,2014,29181.0,0.017069,(altre) 50 Cose che Non Sai su MINECRAFT Visto...,11,11_di_el_la_que,"['di', 'el', 'la', 'que', 'il', 'medicina', 'p..."
6165,YouTube,dVHODxcODGI,https://www.youtube.com/watch?v=dVHODxcODGI,FLUIDO ANTIEDAD Y ANTIARRUGAS CASERO. Anti-agi...,SUSCRIBETE: http://goo.gl/VI8PoS Hoy vamos a p...,LOS TRUCOS DE JULIETA.,Hermosa receta lo voy a haceerr!! || madre mia...,122703.0,0.0,94.0,...,es,2014-11-18,True,2014,94.0,0.000766,FLUIDO ANTIEDAD Y ANTIARRUGAS CASERO. Anti-agi...,11,11_di_el_la_que,"['di', 'el', 'la', 'que', 'il', 'medicina', 'p..."
6680,YouTube,SYN5Fz6kdME,https://www.youtube.com/watch?v=SYN5Fz6kdME,PALESTRA TECNOLOGIAS ANTI-AGING PARA A LONGEVI...,Palestra realizada pelo Prof. Dr . Paul Ling T...,FIVE DIAMONDS OFICIAL,NaN,565.0,19.0,0.0,...,unknown,2015-04-28,False,2015,19.0,0.033628,PALESTRA TECNOLOGIAS ANTI-AGING PARA A LONGEVI...,11,11_di_el_la_que,"['di', 'el', 'la', 'que', 'il', 'medicina', 'p..."
6840,YouTube,Ep05TX05_tA,https://www.youtube.com/watch?v=Ep05TX05_tA,"Longevidad y zonas azules, Reflexión No.11 Cés...",Qué hacer para vivir largo tiempo? Una propues...,Mensajes para vivir- César Fernández,En Uruguay es muy comun vivir hasta los...,23261.0,663.0,15.0,...,es-419,2015-06-14,False,2015,678.0,0.029148,"Longevidad y zonas azules, Reflexión No.11 Cés...",11,11_di_el_la_que,"['di', 'el', 'la', 'que', 'il', 'medicina', 'p..."
6859,YouTube,bVyfBcyADLo,https://www.youtube.com/watch?v=bVyfBcyADLo,Cosa sono i Nootropi?,Questo video e' il riassunto del articolo che ...,Nootropics Italia,Salve sto assumendo brain again black edition ...,2291.0,20.0,5.0,...,unknown,2015-06-22,False,2015,25.0,0.010912,Cosa sono i Nootropi? Questo video e' il riass...,11,11_di_el_la_que,"['di', 'el', 'la', 'que', 'il', 'medicina', 'p..."
6956,YouTube,MGFpjZqtjEM,https://www.youtube.com/watch?v=MGFpjZqtjEM,Nootrópicos Naturales: arándanos azules: Propi...,Los arándanos son una baya que crece de un arb...,Nootropo Sapiens,"De donde saca las características, <br>y funci...",3664.0,41.0,1.0,...,unknown,2015-07-12,False,2015,42.0,0.011463,Nootrópicos Naturales: arándanos azules: Propi...,11,11_di_el_la_que,"['di', 'el', 'la', 'que', 'il', 'medicina', 'p..."
7016,YouTube,mOxgxHyVlGU,https://www.youtube.com/watch?v=mOxgxHyVlGU,LA FÓRMULA ANTI-AGING. EL PLACER DE MANTENERSE...,En este libro hemos seleccionado todos los ele...,Tibidabo Ediciones,NaN,498.0,5.0,0.0,...,unknown,2015-07-29,False,2015,5.0,0.010040,LA FÓRMULA ANTI-AGING. EL PLACER DE MANTENERSE...,11,11_di_el_la_que,"['di', 'el', 'la', 'que', 'il', 'medicina', 'p..."
7054,YouTube,8fkzMuvjdUk,https://www.youtube.com/watch?v=8fkzMuvjdUk,La fórmula anti-aging 1,Spot de promoción del libro La fórmula anti-ag...,Ana García,NaN,71.0,2.0,0.0,...,unknown,2015-08-09,False,2015,2.0,0.028169,La fórmula anti-aging 1 Spot de promoción del ...,11,11_di_el_la_que,"['di', 'el', 'la', 'que', 'il', 'medicina', 'p..."
7059,YouTube,hKPc-WD762s,https://www.youtube.com/watch?v=hKPc-WD762s,NOOTROPICOS - AS DROGAS DA INTELIGÊNCIA - PARTE 1,NOOTRÓPICOS AS DROGAS DA INTELIGÊNCIA- PARTE 1...,Luiz Padalino,Confira as novidades em produtos para o cérebr...,41504.0,1236.0,129.0,...,unknown,2015-08-10,False,2015,1365.0,0.032888,NOOTROPICOS - AS DROGAS DA INTELIGÊNCIA - PART...,11,11_di_el_la_que,"['di', 'el', 'la', 'que', 'il', 'medicina', 'p..."
7105,YouTube,1iT7Id5Xs3c,https://www.youtube.com/watch?v=1iT7Id5Xs3c,Anti Aging Biofotonico Revita Corp,Associação da Máscara de colágeno mais Laser t...,Revita Corp Clínica de Estética,NaN,17.0,1.0,0.0,...,unknown,2015-08-23,False,2015,1.0,0.058824,Anti Aging Biofotonico Revita Corp Associação ...,11,11_di_el_la_que,"['di', 'el', 'la', 'que', 'il', 'medicina', 'p..."
7317,YouTube,LCSKtlD6VV8,https://www.youtube.com/watch?v=LCSKtlD6VV8,Quali sono le cause del diabete infantile?,Pillola di salute di Nutrirelavita.it - Canale...,Nutrire la vita,NaN,3103.0,0.0,0.0,...,unknown,2015-10-19,False,2015,0.0,0.000000,Quali sono le cause del diabete infantile? Pil...,11,11_di_el_la_que,"['di', 'el', 'la', 'que', 'il', 'medicina', 'p..."
7318,YouTube,uXuAczUo4Q0,https://www.youtube.com/watch?v=uXuAczUo4Q0,Il diabete dura tutta la vita?,Pillola di salute di Nutrirelavita.it - Canale...,Nutrire la vita,NaN,79.0,0.0,0.0,...,unknown,2015-10-19,False,2015,0.0,0.000000,Il diabete dura tutta la vita? Pillola di salu...,11,11_di_el_la_que,"['di', 'el', 'la', 'que', 'il', 'medicina', 'p..."
7319,YouTube,9dXSkYJ_LZA,https://www.youtube.com/watch?v=9dXSkYJ_LZA,Esistono delle limitazioni nella vita quotidia...,Pillola di salute di Nutrirelavita.it - Canale...,Nutrire la vita,NaN,64.0,2.0,0.0,...,unknown,2015-10-19,False,2015,2.0,0.031250,Esistono delle limitazioni nella vita quotidia...,11,11_di_el_la_que,"['di', 'el', 'la', 'que', 'il', 'medicina', 'p..."
7347,YouTube,RoerBrW5K7c,https://www.youtube.com/watch?v=RoerBrW5K7c,Cos’è la glicemia?,Pillola di salute di Nutrirelavita.it - Canale...,Nutrire la vita,NaN,2755.0,22.0,0.0,...,unknown,2015-10-26,False,2015,22.0,0.007985,Cos’è la glicemia? Pillola di salute di Nutrir...,11,11_di_el_la_que,"['di', 'el', 'la', 'que', 'il', 'medicina', 'p..."

In [526]:
dfp[dfp['topic']==12].head(50)

,source,video_id,video_url,title,description,channel,comments,views,likes,comments_count,...,country,date,likes_missing,year,engagement,engagement_rate,text,topic,topic_name,topic_repr
127,YouTube,tgQzRaVRb4Q,https://www.youtube.com/watch?v=tgQzRaVRb4Q,BrainPill Remastered,"Hier das alte video in der besten Qualität, di...",crazysoulbrothers,NaN,133.0,1.0,0.0,...,unknown,2010-02-15,False,2010,1.0,0.007519,BrainPill Remastered Hier das alte video in de...,12,12_die_und_der_für,"['die', 'und', 'der', 'für', 'ist', 'das', 'si..."
382,YouTube,nxtAP2L9gkk,https://www.youtube.com/watch?v=nxtAP2L9gkk,Super Schnelles Schlank Getrank,"My German video, wooooo.",Luke Dowker,haha :) love the accent when they talk in germ...,209.0,3.0,2.0,...,unknown,2010-05-10,False,2010,5.0,0.023923,Super Schnelles Schlank Getrank My German vide...,12,12_die_und_der_für,"['die', 'und', 'der', 'für', 'ist', 'das', 'si..."
1244,YouTube,ecW4mLg2NFE,https://www.youtube.com/watch?v=ecW4mLg2NFE,Kinetics Live 21 januari,Kinetics spelar live på Kafé de luxe 21 januar...,simontrummor,NaN,468.0,1.0,0.0,...,unknown,2010-12-29,False,2010,1.0,0.002137,Kinetics Live 21 januari Kinetics spelar live ...,12,12_die_und_der_für,"['die', 'und', 'der', 'für', 'ist', 'das', 'si..."
1253,YouTube,XxoF8UzdIDU,https://www.youtube.com/watch?v=XxoF8UzdIDU,Soxhletextraktion einer Pflanze.mpg,"So stellt man hochwirksame Medizin her, einfac...",Armin M ü l l e r,wielange braucht man dafür<br>? || bringt nich...,1816.0,5.0,6.0,...,unknown,2011-01-02,False,2011,11.0,0.006057,Soxhletextraktion einer Pflanze.mpg So stellt ...,12,12_die_und_der_für,"['die', 'und', 'der', 'für', 'ist', 'das', 'si..."
1621,YouTube,7uHieI1qqbk,https://www.youtube.com/watch?v=7uHieI1qqbk,Pharmeo | Anti Aging (Hautalterung),http://www.pharmeo.de/advanced_search_result.p...,Pharmeo,NaN,1082.0,2.0,0.0,...,unknown,2011-04-28,False,2011,2.0,0.001848,Pharmeo | Anti Aging (Hautalterung) http://www...,12,12_die_und_der_für,"['die', 'und', 'der', 'für', 'ist', 'das', 'si..."
1668,YouTube,tSuTCosFJkM,https://www.youtube.com/watch?v=tSuTCosFJkM,Anti-Aging (thuis-)Behandeling,Neways - de producent van eerlijke producten (...,gezondereweg,NaN,275.0,0.0,0.0,...,unknown,2011-05-12,True,2011,0.0,0.000000,Anti-Aging (thuis-)Behandeling Neways - de pro...,12,12_die_und_der_für,"['die', 'und', 'der', 'für', 'ist', 'das', 'si..."
1733,YouTube,7JwsLYS7a84,https://www.youtube.com/watch?v=7JwsLYS7a84,Anti-Aging bei Fenninger Kosmetik in Salzburg,http://www.fenninger-kosmetik.at Herzlich Will...,WebstyleGmbH,NaN,532.0,1.0,0.0,...,unknown,2011-06-03,False,2011,1.0,0.001880,Anti-Aging bei Fenninger Kosmetik in Salzburg ...,12,12_die_und_der_für,"['die', 'und', 'der', 'für', 'ist', 'das', 'si..."
1774,YouTube,RDU8ff_2O-s,https://www.youtube.com/watch?v=RDU8ff_2O-s,www.boturine-x.com - Kosmetik Boturine-X Anti-...,http://www.boturine-x.com : Einfache und schme...,boturine,NaN,1207.0,3.0,0.0,...,unknown,2011-06-19,False,2011,3.0,0.002486,www.boturine-x.com - Kosmetik Boturine-X Anti-...,12,12_die_und_der_für,"['die', 'und', 'der', 'für', 'ist', 'das', 'si..."
1849,YouTube,gGEcCeuUfsE,https://www.youtube.com/watch?v=gGEcCeuUfsE,ANTI AGING - actiMare natural cosmetics - Meer...,mehr infos: www.actimare.de Onlineshop: www.ac...,actiMare,NaN,405.0,2.0,0.0,...,de,2011-07-14,False,2011,2.0,0.004938,ANTI AGING - actiMare natural cosmetics - Meer...,12,12_die_und_der_für,"['die', 'und', 'der', 'für', 'ist', 'das', 'si..."
1876,YouTube,in7kNoJ_8QA,https://www.youtube.com/watch?v=in7kNoJ_8QA,#27 Ellfiore Testimonial - Anti Aging Pflege,(Werbung) Yuhu - im Jahr 2011 darf ich das Ges...,ElischebaTV,NaN,760.0,7.0,0.0,...,unknown,2011-07-23,False,2011,7.0,0.009211,#27 Ellfiore Testimonial - Anti Aging Pflege (...,12,12_die_und_der_für,"['die', 'und', 'der', 'für', 'ist', 'das', 'si..."
2141,YouTube,V-BvGyMwglE,https://www.youtube.com/watch?v=V-BvGyMwglE,mySUNcompany | Anti-Aging auf modernster Art m...,Lasse Deine innere Jugend wieder strahlen. Mit...,mysuncompany,NaN,218.0,0.0,0.0,...,unknown,2011-10-07,True,2011,0.0,0.000000,mySUNcompany | Anti-Aging auf modernster Art m...,12,12_die_und_der_für,"['die', 'und', 'der', 'für', 'ist', 'das', 'si..."
3328,YouTube,wIDv2sAYB84,https://www.youtube.com/watch?v=wIDv2sAYB84,"Dibi Milano - Lift Perfection, geavanceerde an...",De Lift Perfection serie is de eerste geavance...,Oros Cosmetics Soest,NaN,4125.0,12.0,0.0,...,unknown,2012-09-25,False,2012,12.0,0.002909,"Dibi Milano - Lift Perfection, geavanceerde an...",12,12_die_und_der_für,"['die', 'und', 'der', 'für', 'ist', 'das', 'si..."
3438,YouTube,OwctXlirY28,https://www.youtube.com/watch?v=OwctXlirY28,HydraFacial die Anti-Aging Revolution aus Los ...,Ecomedic präsentiert die Anti-Aging Therapie o...,Hydrafacial Germany,NaN,36780.0,44.0,0.0,...,unknown,2012-10-22,False,2012,44.0,0.001196,HydraFacial die Anti-Aging Revolution aus Los ...,12,12_die_und_der_für,"['die', 'und', 'der', 'für', 'ist', 'das', 'si..."
4213,YouTube,C2DwhbuY-s0,https://www.youtube.com/watch?v=C2DwhbuY-s0,&quot;Anti Aging&quot; Modefilm,Filmprojekt an der AMD Akademie für Mode & Des...,Katharina Kynast,NaN,224.0,1.0,0.0,...,unknown,2013-06-06,False,2013,1.0,0.004464,&quot;Anti Aging&quot; Modefilm Filmprojekt an...,12,12_die_und_der_für,"['die', 'und', 'der', 'für', 'ist', 'das', 'si..."
4216,YouTube,rPpKH2q-7Uk,https://www.youtube.com/watch?v=rPpKH2q-7Uk,A4 Cosmetics - Anti-Aging Wirkstoffkosmetik au...,A4 Cosmetics Gründerin Eva Steinmeyer stellt I...,A4 Cosmetics,NaN,3657.0,7.0,0.0,...,de,2013-06-06,False,2013,7.0,0.001914,A4 Cosmetics - Anti-Aging Wirkstoffkosmetik au...,12,12_die_und_der_für,"['die', 'und', 'der', 'für', 'ist', 'das', 'si..."
4495,YouTube,H2SSgiN-5sc,https://www.youtube.com/watch?v=H2SSgiN-5sc,Adonia Germany - Anwendungsvideo - ATHENA 7 MI...,"Ausführliche Produktinformationen, Inhaltsstof...",ADONIASHOP.eu - Athena 7 Minute Lift - unabhän...,NaN,586.0,3.0,0.0,...,unknown,2013-09-04,False,2013,3.0,0.005119,Adonia Germany - Anwendungsvideo - ATHENA 7 MI...,12,12_die_und_der_für,"['die', 'und', 'der', 'für', 'ist', 'das', 'si..."
5230,YouTube,uboeE6kK7T0,https://www.youtube.com/watch?v=uboeE6kK7T0,Die InfiniteAloe Hautpflege und die InfiniteAl...,Die InfiniteAloe Hautpflege und die High-End I...,InfiniteAloe,NaN,367.0,1.0,0.0,...,unknown,2014-03-11,False,2014,1.0,0.002725,Die InfiniteAloe Hautpflege und die InfiniteAl...,12,12_die_und_der_für,"['die', 'und', 'der', 'für', 'ist', 'das', 'si..."
5543,YouTube,q6pfuzwpnmQ,https://www.youtube.com/watch?v=q6pfuzwpnmQ,Clinique Pflegeroutine Anti-aging,In den kommenden Wochen zeigen euch unsere Cli...,Clinique Deutschland,AngrlTe despiertas a las 3 de la madrugada? Qu...,13317.0,39.0,2.0,...,de,2014-06-12,False,2014,41.0,0.003079,Clinique Pflegeroutine Anti-aging In den komme...,12,12_die_und_der_für,"['die', 'und', 'der', 'für', 'ist', 'das', 'si..."
5722,YouTube,dPMPTHIAgGY,https://www.youtube.com/watch?v=dPMPTHIAgGY,Selen - Schlankmacher Schilddrüse (Kokosnuss),"Kokosöl ist das beste Fett zum braten, weil es...",Brain- und Biohacking Torsten M. Groschupp,"Paranüsse sind belastet || Natriumselenit, aha...",56480.0,350.0,24.0,...,unknown,2014-08-05,False,2014,374.0,0.006622,Selen - Schlankmacher Schilddrüse (Kokosnuss) ...,12,12_die_und_der_für,"['die', 'und', 'der', 'für', 'ist', 'das', 'si..."
5936,YouTube,pdPJdGxvMbs,https://www.youtube.com/watch?v=pdPJdGxvMbs,GENXSKIN - Anti-Aging Control System,De dermo-esthetische aanpak gebaseerd op Cosme...,Huidverjonging,NaN,360.0,5.0,0.0,...,unknown,2014-09-25,False,2014,5.0,0.013889,GENXSKIN - Anti-Aging Control System De dermo-...,12,12_die_und_der_für,"['die', 'und', 'der', 'für', 'ist', 'das', 'si..."
6210,YouTube,5_mP6MgbxrI,https://www.youtube.com/watch?v=5_mP6MgbxrI,Kosmetik und Anti-Aging in Hamburg - Kosmetik ...,http://www.kosmetik-slama.de/ Professionelle u...,InternetOnlineMedia,NaN,648.0,1.0,0.0,...,unknown,2014-11-26,False,2014,1.0,0.001543,Kosmetik und Anti-Aging in Hamburg - Kosmetik ...,12,12_die_und_der_für,"['die', 'und', 'der', 'für', 'ist', 'das', 'si..."
6515,YouTube,LCkcmSmvtyA,https://www.youtube.com/watch?v=LCkcmSmvtyA,Anti Aging Drink,Der beste Anti Aging drink von Polynesien ab 5...,Noni von Morinda,NaN,223.0,1.0,0.0,...,unknown,2015-03-08,False,2015,1.0,0.004484,Anti Aging Drink Der beste Anti Aging drink vo...,12,12_die_und_der_für,"['die', 'und', 'der', 'für', 'ist', 'das', 'si..."
6628,YouTube,iufm5KavE04,https://www.youtube.com/watch?v=iufm5KavE04,Anti Aging mit Kokosöl,Anti Aging mit Kokosöl – Frisch aussehen auch ...,Kokosöl Kenner,Mangobutter? Duftet die so lecker wie sie klin...,4229.0,34.0,1.0,...,unknown,2015-04-14,False,2015,35.0,0.008276,Anti Aging mit Kokosöl Anti Aging mit Kokosöl ...,12,12_die_und_der_für,"['die', 'und', 'der', 'für', 'ist', 'das', 'si..."
6655,YouTube,c__ncavjm5g,https://www.youtube.com/watch?v=c__ncavjm5g,Effektive Anti-Aging Pflege - Was sind gute An...,Wie sieht effektive Anti-Aging Pflege aus? Dr....,Dr. Patricia Ogilvie Fachärztin für Dermatolog...,"<a href=""https://cb.hempmate.com/de-ch/cbd-ant...",2361.0,9.0,1.0,...,de,2015-04-20,False,2015,10.0,0.004235,Effektive Anti-Aging Pflege - Was sind gute An...,12,12_die_und_der_für,"['die', 'und', 'der', 'für', 'ist', 'das', 'si..."
6857,YouTube,5qtqS9mE7d4,https://www.youtube.com/watch?v=5qtqS9mE7d4,"Dana Schweiger, Naturkosmetik Model für vegane...",Dana Schweiger ist die neue Markenbotschafteri...,Dr. Niedermaier Natural Luxury,NaN,1477.0,4.0,0.0,...,unknown,2015-06-22,False,2015,4.0,0.002708,"Dana Schweiger, Naturkosmetik Model für vegane...",12,12_die_und_der_für,"['die', 'und', 'der', 'für', 'ist', 'das', 'si..."
7104,YouTube,BmjViGIq7Gg,https://www.youtube.com/watch?v=BmjViGIq7Gg,Anti-Aging: Das Kosmetikstudio Sandra Dannenberg,Die staatlich anerkannte Kosmetikerin Sandra #...,P PLUS TV,NaN,3579.0,9.0,0.0,...,unknown,2015-08-22,False,2015,9.0,0.002515,Anti-Aging: Das Kosmetikstudio Sandra Dannenbe...,12,12_die_und_der_für,"['die', 'und', 'der', 'für', 'ist', 'das', 'si..."
7322,YouTube,lSTVJCtIJNE,https://www.youtube.com/watch?v=lSTVJCtIJNE,Mira-Skin – Anti-Aging dank Softlifting mit Ul...,Sie wollen Ihre Haut sanft liften – also Hauts...,Techmira International,NaN,1893.0,8.0,0.0,...,unknown,2015-10-21,False,2015,8.0,0.004226,Mira-Skin – Anti-Aging dank Softlifting mit Ul...,12,12_die_und_der_für,"['die', 'und', 'der', 'für', 'ist', 'das', 'si..."
7999,YouTube,p-oqFi7w3vQ,https://www.youtube.com/watch?v=p-oqFi7w3vQ,FGX Beauty Strips unterstützt den Anti-Aging-E...,https://www.regatape.com/ FGX Beauty Strips un...,RegaTape,NaN,400.0,0.0,0.0,...,en,2016-04-27,False,2016,0.0,0.000000,FGX Beauty Strips unterstützt den Anti-Aging-E...,12,12_die_und_der_für,"['die', 'und', 'der', 'für', 'ist', 'das', 'si..."
8018,YouTube,tJ4j0gb6klQ,https://www.youtube.com/watch?v=tJ4j0gb6klQ,Jean D Aveze Algen Gesichtsmaske Anti Aging An...,Wir führen qualifizierte Produktschulungen in ...,www.zoga-beauty.com,NaN,880.0,3.0,0.0,...,unknown,2016-05-04,False,2016,3.0,0.003409,Jean D Aveze Algen Gesichtsmaske Anti Aging An...,12,12_die_und_der_für,"['die', 'und', 'der', 'für', 'ist', 'das', 'si..."
8388,YouTube,YNeIChLjXAg,https://www.youtube.com/watch?v=YNeIChLjXAg,Resist Anti-Aging 10% Niacinamide Booster,"Zie huidverkleuringen vervagen, porien verklei...",Paula's Choice Benelux,NaN,2638.0,0.0,0.0,...,unknown,2016-08-11,False,2016,0.0,0.000000,Resist Anti-Aging 10% Niacinamide Booster Zie ...,12,12_die_und_der_für,"['die', 'und', 'der', 'für', 'ist', 'das', 'si..."
8536,YouTube,pzmrn3O2Dh4,https://www.youtube.com/watch?v=pzmrn3O2Dh4,Lancôme Anti Aging Day Makeup - Fall 2016,Der neue Herbst Make up Trend von Lancôme mit ...,Valeska's Video Blog,NaN,189.0,1.0,0.0,...,en-GB,2016-09-20,False,2016,1.0,0.005291,Lancôme Anti Aging Day Makeup - Fall 2016 Der ...,12,12_die_und_der_für,"['die', 'und', 'der', 'für', 'ist', 'das', 'si..."
9617,YouTube,Y3yXPS7f8k0,https://www.youtube.com/watch?v=Y3yXPS7f8k0,"purebeau noninvasives Lifting, PMU, Fibroblast...",Alle Facetten für vollendete Schönheit.,Joanna Slaska,NaN,420.0,3.0,0.0,...,unknown,2017-08-11,False,2017,3.0,0.007143,"purebeau noninvasives Lifting, PMU, Fibroblast...",12,12_die_und_der_für,"['die', 'und', 'der', 'für', 'ist', 'das', 'si..."
10291,YouTube,SwmRM4ZeNvA,https://www.youtube.com/watch?v=SwmRM4ZeNvA,Reife Haut pflegen | Anti-Aging Serum &amp; Au...,"Das Tutorial zeigt, wie ihr die reife Haut am ...",DERMASENCE,Bin 32 J . Kann bzw darf ich das auch schon be...,31809.0,32.0,5.0,...,de,2018-02-01,False,2018,37.0,0.001163,Reife Haut pflegen | Anti-Aging Serum &amp; Au...,12,12_die_und_der_für,"['die', 'und', 'der', 'für', 'ist', 'das', 'si..."
10646,YouTube,VHvcHqwfvAg,https://www.youtube.com/watch?v=VHvcHqwfvAg,ACARAA-Gesichtsserum: Hochwertige Inhaltsstoff...,"Sarah zeigt Dir in diesem Video, wie Du das AC...",micaraa Mindful Care,NaN,838.0,1.0,0.0,...,unknown,2018-05-11,False,2018,1.0,0.001193,ACARAA-Gesichtsserum: Hochwertige Inhaltsstoff...,12,12_die_und_der_für,"['die', 'und', 'der', 'für', 'ist', 'das', 'si..."
10784,YouTube,ncWIyJ2PPhU,https://www.youtube.com/watch?v=ncWIyJ2PPhU,Healthy Aging aus kulturwissenschaftlicher Sic...,Prof. Dr. Roberta Maierhofer (https://bit.ly/2...,CredoWeb.at,NaN,444.0,6.0,0.0,...,de,2018-06-20,False,2018,6.0,0.013514,Healthy Aging aus kulturwissenschaftlicher Sic...,12,12_die_und_der_für,"['die', 'und', 'der', 'für', 'ist', 'das', 'si..."
10968,YouTube,o8DiZCbiedw,https://www.youtube.com/watch?v=o8DiZCbiedw,Anti-Aging Cremes: Welche ist die Richtige für...,Worauf achten beim Kauf der richtigen Anti-Agi...,Dorow Clinic,NaN,4303.0,55.0,0.0,...,de,2018-08-12,False,2018,55.0,0.012782,Anti-Aging Cremes: Welche ist die Richtige für...,12,12_die_und_der_für,"['die', 'und', 'der', 'für', 'ist', 'das', 'si..."
11029,YouTube,I6yNjkw6FJM,https://www.youtube.com/watch?v=I6yNjkw6FJM,"Anti Aging Foundation, welches ist das richtig...",Hier geht es zur 799 Serum de Teint von Maria ...,Britta Bork,NaN,685.0,0.0,0.0,...,de,2018-08-29,False,2018,0.0,0.000000,"Anti Aging Foundation, welches ist das richtig...",12,12_die_und_der_für,"['die', 'und', 'der', 'für', 'ist', 'das', 'si..."
11085,YouTube,sst5EMewSbc,https://www.youtube.com/watch?v=sst5EMewSbc,JetPeel - Anti-Aging,JetPeel – die neue Hautverjüngungsmethode Nade...,Faceestetik Mannheim,NaN,1713.0,5.0,0.0,...,de,2018-09-08,False,2018,5.0,0.002919,JetPeel - Anti-Aging JetPeel – die neue Hautve...,12,12_die_und_der_für,"['die', 'und', 'der', 'für', 'ist', 'das', 'si..."
11135,YouTube,6yl4bRqkBzQ,https://www.youtube.com/watch?v=6yl4bRqkBzQ,Anti Aging | 6 Wochen koreanische Gesichtspfle...,Ginzai Glow Booster: http://www.ginzai.de/glow...,GINZAI - Kosmetik auf der Basis von Ginseng,NaN,508.0,0.0,0.0,...,de,2018-09-21,True,2018,0.0,0.000000,Anti Aging | 6 Wochen koreanische Gesichtspfle...,12,12_die_und_der_für,"['die', 'und', 'der', 'für', 'ist', 'das', 'si..."
11476,YouTube,sOcTYaPscjM,https://www.youtube.com/watch?v=sOcTYaPscjM,SERUM | Anti-Aging Serum,Das wirkstarke Leichtgewicht. SERUM ist Dein u...,DOCTOR Mi!,👏👏👏👏👏👏👏💕,729.0,6.0,1.0,...,de,2018-12-12,False,2018,7.0,0.009602,SERUM | Anti-Aging Serum Das wirkstarke Leicht...,12,12_die_und_der_für,"['die', 'und', 'der', 'für', 'ist', 'das', 'si..."
11776,YouTube,Fr7yH0eHSKQ,https://www.youtube.com/watch?v=Fr7yH0eHSKQ,Q10 Anti-Aging Creme gegen müde &amp; trockene...,Q10 – der Wirkstoff für mehr Vitalität und Aus...,DALTON MARINE COSMETICS,"Die Creme ist top,ich benutze sie auch.Danke f...",662.0,10.0,1.0,...,unknown,2019-03-18,False,2019,11.0,0.016616,Q10 Anti-Aging Creme gegen müde &amp; trockene...,12,12_die_und_der_für,"['die', 'und', 'der', 'für', 'ist', 'das', 'si..."
11823,YouTube,smdCqcXmmuo,https://www.youtube.com/watch?v=smdCqcXmmuo,Geheimtipp für Anti-Aging und Brightening Gesi...,Hautprobleme gehören für viele Menschen zum Al...,SHR Germany,NaN,2279.0,0.0,0.0,...,de,2019-03-27,True,2019,0.0,0.000000,Geheimtipp für Anti-Aging und Brightening Gesi...,12,12_die_und_der_für,"['die', 'und', 'der', 'für', 'ist', 'das', 'si..."
11824,YouTube,Jcz0MVvJMmQ,https://www.youtube.com/watch?v=Jcz0MVvJMmQ,Anti-Aging durch Fasten? | Mai Thi Nguyen-Kim,Weniger essen. In Tierversuchen konnte das Leb...,Terra X Lesch & Co,"Nicht weniger essen ist die Lösung, sondern da...",162731.0,5081.0,588.0,...,de,2019-03-27,False,2019,5669.0,0.034837,Anti-Aging durch Fasten? | Mai Thi Nguyen-Kim ...,12,12_die_und_der_für,"['die', 'und', 'der', 'für', 'ist', 'das', 'si..."
11851,YouTube,Rhsx_eDa03Q,https://www.youtube.com/watch?v=Rhsx_eDa03Q,Medicorp Anti-Aging Testsieger 100% Erfolgsgar...,Mehr dazu in unserem Beauty-Shop: https://www....,Beauty-Outlet24,NaN,855.0,3.0,0.0,...,unknown,2019-04-02,False,2019,3.0,0.003509,Medicorp Anti-Aging Testsieger 100% Erfolgsgar...,12,12_die_und_der_für,"['die', 'und', 'der', 'für', 'ist', 'das', 'si..."
11881,YouTube,TUOUuTBEpII,https://www.youtube.com/watch?v=TUOUuTBEpII,PureLift™ – nicht-invasiver Face Lift mit Sofo...,"Müde, schlaffe Haut mit einem fahlen Teint kom...",SHR Germany,NaN,1959.0,0.0,0.0,...,de,2019-04-09,True,2019,0.0,0.000000,PureLift™ – nicht-invasiver Face Lift mit Sofo...,12,12_die_und_der_für,"['die', 'und', 'der', 'für', 'ist', 'das', 'si..."
11962,YouTube,cUOyjVRlKmU,https://www.youtube.com/watch?v=cUOyjVRlKmU,Anti-Aging: So altern sind in jugendlicher Sch...,Im Laufe des Alterungsprozesses kommt es in un...,Kiprov - Schönheitsmedizin Wien,NaN,6082.0,16.0,0.0,...,de,2019-05-02,False,2019,16.0,0.002631,Anti-Aging: So altern sind in jugendlicher Sch...,12,12_die_und_der_für,"['die', 'und', 'der', 'für', 'ist', 'das', 'si..."
11964,YouTube,WBTRiwpbJ_c,https://www.youtube.com/watch?v=WBTRiwpbJ_c,Lidstraffung ohne OP! Schonende Anti-Aging-Beh...,"Ein sichtbarer Face Lift ohne Nadeln, Spritzen...",SHR Germany,NaN,9546.0,0.0,0.0,...,de,2019-05-02,True,2019,0.0,0.000000,Lidstraffung ohne OP! Schonende Anti-Aging-Beh...,12,12_die_und_der_für,"['die', 'und', 'der', 'für', 'ist', 'das', 'si..."
12285,YouTube,IrXaSoMrN54,https://www.youtube.com/watch?v=IrXaSoMrN54,Anti-Aging 2.0: 15 Minuten Video anschauen - 1...,Mit diesen einfachen Tipps 15 Jahre mehr Leben...,Dr. Heart,Beeindruckendes Video! Was Antioxidantien ange...,111926.0,5231.0,604.0,...,de,2019-08-08,False,2019,5835.0,0.052133,Anti-Aging 2.0: 15 Minuten Video anschauen - 1...,12,12_die_und_der_für,"['die', 'und', 'der', 'für', 'ist', 'das', 'si..."
12795,YouTube,dbLvjOYrOv0,https://www.youtube.com/watch?v=dbLvjOYrOv0,Medicorp Anti-Aging Systempflege 2019 Made in ...,MEDICORP® ist aus der medizinisch-biologischen...,Beauty-Outlet24,NaN,5050.0,0.0,0.0,...,unknown,2019-12-09,True,2019,0.0,0.000000,Medicorp Anti-Aging Systempflege 2019 Made in ...,12,12_die_und_der_für,"['die', 'und', 'der', 'für', 'ist', 'das', 'si..."
12869,YouTube,zcEoU4tfX6c,https://www.youtube.com/watch?v=zcEoU4tfX6c,ANTI AGING - Diese 3 Dinge bringen wirklich wa...,Hier findet ihr meine Amazon-Shoppingliste❤️ m...,Sheila Gomez,"Liebe Sheila, ich habe dich heute Morgen neu e...",245905.0,4189.0,382.0,...,unknown,2020-01-05,False,2020,4571.0,0.018588,ANTI AGING - Diese 3 Dinge bringen wirklich wa...,12,12_die_und_der_für,"['die', 'und', 'der', 'für', 'ist', 'das', 'si..."

We were right, Let's delete them!

In [529]:
dfp = dfp[(dfp['topic']!=11) & (dfp['topic']!=12)]

In [537]:
tpp = tpp[(tpp['Topic']!=11) & (tpp['Topic']!=12

In [616]:
dfp.to_csv("new_paraphrase_dataset.csv", index=False)
tpp.to_csv("new_paraphrase_topics.csv", index=False)

Topic number 3 is a little suspicious since some of the vidoes are not related. Some vidoes contain the rejuvination of the different things than health (eg. yard, park etc.). Keep or Delete? Some videos contain mental rejuvination musics.

Other topics seems like more or less related